src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Accounts are validated against SAP to ensure a match and to prevent duplication of accounts. &quot;New&quot; indicates that the account has not yet been validated against SAP, &quot;SAP Validated&quot; means that it should exist as a ParentAccount on SAP</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>SAP Validated</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Study__c.object
<CustomObject>
    <description>CSM-ACN-S-0124 - Custom Object study.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>CSM-ACN-S-0124 - Picklist field Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                    <isActive>false</isActive>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <isActive>false</isActive>
                    <label>Complete</label>
                </value>
                <value>
                    <fullName>Data Lock</fullName>
                    <isActive>false</isActive>
                    <label>Data Lock</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                    <isActive>false</isActive>
                    <label>On hold</label>
                </value>
                <value>
                    <fullName>Production (Live)</fullName>
                    <isActive>false</isActive>
                    <label>Production (Live)</label>
                </value>
                <value>
                    <fullName>Set-up/Revision</fullName>
                    <isActive>false</isActive>
                    <label>Set-up/Revision</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StudyID__c</fullName>
        <description>CSM-ACN-S-0124 - Text field for Study ID</description>
        <label>Project Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Study</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Study_Contact_Relationship__c.object
<CustomObject>
    <description>CSM-ACN-S-0124 - Custom Object Study Contact Relationship</description>
    <fields>
        <fullName>AccessStatus__c</fullName>
        <description>CSM-ACN-S-0124 - Picklist field that holds the value of Access Status</description>
        <label>Access Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not requested</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Granted to training</fullName>
                </value>
                <value>
                    <fullName>Initial login successful</fullName>
                </value>
                <value>
                    <fullName>Granted to production</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <description>CSM-ACN-S-0124 - Formula field to take a the Contact&apos;s Email.</description>
        <formula>Contact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactJobTitle__c</fullName>
        <description>CSM-ACN-S-0124 - Formula field that will take the Job Title of Contacts</description>
        <formula>Contact__r.Title</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Job Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactRole__c</fullName>
        <description>CSM-ACN-S-0124 - Picklist that holds values of Contact Role.</description>
        <label>Contact Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Clinical Contact</fullName>
                    <default>true</default>
                    <label>Clinical Contact</label>
                </value>
                <value>
                    <fullName>Sponsor Contact</fullName>
                </value>
                <value>
                    <fullName>QI Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>CSM-ACN-S-0124 - Master Detail Relationship field with Contact Object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Study Contact Relationships</relationshipLabel>
        <relationshipName>Study_Contact_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SendEmailUpdates__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM-ACN-S-0124 - Checkbox to send email updates when checked</description>
        <label>Send Email Updates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CSM-ACN-S-0124 - Picklist that holds Status values</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StudyID__c</fullName>
        <description>CSM-ACN-S-0124 - Formula field that will display the Study ID of associated record.</description>
        <formula>HYPERLINK(&quot;/&quot;&amp; Study__c , Study__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Study ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudyTherapeuticArea__c</fullName>
        <description>CSM-ACN-S-0124 - Formula field that will take the Therapeutic Area of the associated Study</description>
        <formula>TEXT( Study__r.TherapeuticArea__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Study Therapeutic Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <description>CSM-ACN-S-0124 - Master Detail Relationship with Object Study</description>
        <label>Study</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipLabel>Study Contact Relationships</relationshipLabel>
        <relationshipName>Study_Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserGroup__c</fullName>
        <description>CSM-ACN-S-0124 - Picklist that will hold User Group values.</description>
        <label>User Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CRO</fullName>
                </value>
                <value>
                    <fullName>Prostate</fullName>
                </value>
                <value>
                    <fullName>Breast</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Lung</fullName>
                </value>
                <value>
                    <fullName>Site</fullName>
                </value>
                <value>
                    <fullName>Colon/Rectum</fullName>
                </value>
                <value>
                    <fullName>Sponsor</fullName>
                </value>
                <value>
                    <fullName>GYN</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>Lymphoma</fullName>
                </value>
                <value>
                    <fullName>Leukemia</fullName>
                </value>
                <value>
                    <fullName>Skin</fullName>
                </value>
                <value>
                    <fullName>Head/Neck</fullName>
                </value>
                <value>
                    <fullName>Pancreatic/cholangio</fullName>
                </value>
                <value>
                    <fullName>Thyroid</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserTrainedDate__c</fullName>
        <description>CSM-ACN-S-0124 - Date field for User Trained Date</description>
        <label>User Trained Date</label>
        <type>Date</type>
    </fields>
    <label>Study Contact Relationship</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>SC Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_SLT_StudySiteContactRelationship.cls
@isTest
private class TST_SLT_StudySiteContactRelationship {
    /**
    * This method is used to setup data for all methods.
    */
    @testSetup
    static void dataSetup() {
        Account acc = CSM_Util.createRDAccount();
        insert acc;
        Account acc1 = CSM_Util.createRDAccount();
        insert acc1;
        Contact cnt = CSM_Util.createContact(acc.Id,'CaseTestContact');
        insert cnt;
        
    }
    
    /**
    * This test method used for insert and update Case record
    */ 
    static testMethod void testAuditforStudySiteRelationship() {
        CNT_CSM_FieldHistoryTracking.saveFields('Study_Contact_Relationship__c','AccessStatus__c,Contact__c,ContactEmail__c,ContactJobTitle__c,ContactRole__c,CurrencyIsoCode,RecordTypeId,SendEmailUpdates__c,Status__c,Study__c,StudyID__c,StudyTherapeuticArea__c,SystemModstamp,UserGroup__c,UserTrainedDate__c');
        Account acc = [SELECT Id, Name FROM Account WHERE Name = 'CaseRDTestAccount' LIMIT 1];
        Account acc1 = [SELECT Id, Name FROM Account WHERE Name = 'CaseRDTestAccount' LIMIT 1];
        Contact cnt = [SELECT Id, Name FROM Contact WHERE Name = 'CaseTestContact CaseTestContact' LIMIT 1];
        Contact cnt2 = CSM_Util.createContact(acc.Id,'CaseTestContact2');
        insert cnt2;
        Study__c study = CSM_Util.createStudy(acc.Id);
        insert study;
        Study_Contact_Relationship__c contactR = CSM_Util.createStudyContactRelationship(study.Id ,cnt.Id);
        
        Test.startTest();
        insert contactR;
        new SLT_StudySiteContactRelationship().selectByStudySiteContactRelationshipId(new Set<Id>{contactR.Id}, new Set<String>{'Id','Name'});
        
        Test.stopTest();
    }
}