src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>CSM-ACN-S-0036 - Picklist that defines Region with values &quot;&quot;EMEA&quot;, &quot;LATAM&quot;, &quot;NA&quot;, &quot;APAC&quot;</description>
        <label>Regional Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>AMER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Mulesoft_Integration_Control__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-QI-ESPSFDCQI-784 - Custom setting to control various aspects of Mulesoft integration (suppress outbound messages etc.)</description>
    <fields>
        <fullName>Ignore_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-1007</description>
        <label>Ignore Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <label>Mulesoft Integration Control</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Request_Ticket_Number__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Ticket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3361</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Europe/Middle East/Africa EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>USA/Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TST_BCH_CRM_sendEmailToOppOwner.cls
@isTest
public class TST_BCH_CRM_sendEmailToOppOwner {
    
    @IsTest
    static void testexecute() {
        
        Profile profile1 = [SELECT Id FROM Profile WHERE Name =: 'System Administrator' LIMIT 1];
        String UserName = 'testUser1@testGroupUpdate.com'+UserInfo.getOrganizationId();
        User testUser1 = new User(ProfileId = profile1.Id, UserName = UserName,
                                  Email = 'test@iqvia.com', EmailenCodingKey = 'UTF-8', LocalesIdKey = 'en_US',
                                  LanguageLocaleKey = 'en_US', TimeZonesIdKey = 'America/Los_Angeles', Alias = 'extUser',IsActive = true,
                                  LastName = 'lastname', Change_Request_Description__c = 'test', Change_Request_Ticket_Number__c ='test description', EmployeeNumber = '0909090918' , Region__c = 'Europe/Middle East/Africa EMEA');
        insert testUser1;
        Mulesoft_Integration_Control__c mulesoftIntegrationSettings = UTL_TestData.createMulesoftIntegrationControl(UserInfo.getOrganizationId());
        mulesoftIntegrationSettings.Ignore_Validation_Rules__c = true;
        upsert mulesoftIntegrationSettings;
        Account acc = UTL_TestData.createAccount();
        insert acc;
        
        Opportunity opportunityRecord = UTL_TestData.createOpportunity(acc.id);
        opportunityRecord.OwnerId = testUser1.id;
        opportunityRecord.CloseDate = Date.today().addDays(-100);
        opportunityRecord.StageName = '1. Identifying Opportunity';
        insert opportunityRecord;
        
        
        Test.startTest();
        Id batchId = Database.executeBatch(new BCH_CRM_sendEmailToOppOwner('Select id from User Where Id =  \''+testUser1.id+'\''),1);
        Test.stopTest();
    }
}