src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LI_Account_Id__c</fullName>
        <externalId>true</externalId>
        <label>LI Account Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LQ_Account_Id__c</fullName>
        <externalId>true</externalId>
        <label>LQ Account Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MDM_SFDC_Golden_Record_Id__c</fullName>
        <externalId>true</externalId>
        <label>MDM SFDC Golden Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Pending for Descartes</fullName>
                </value>
                <value>
                    <fullName>Rejected by Descartes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_SLT_AccountContactRelation.cls
@isTest
private class TST_SLT_AccountContactRelation {
    @isTest
    static void testMethod1() {
    	test.startTest();
        List<Account> acc = new List<Account>();
    	Account acc1 = UTL_TestData.createAccount();
        Account acc2 = UTL_TestData.createAccount();
        acc.add(acc1);
        acc.add(acc2);
        insert acc;
        acc1.LI_Account_Id__c = acc2.Id;
        acc1.LQ_Account_Id__c = acc2.Id;
        update acc1;
        acc2.MDM_SFDC_Golden_Record_Id__c = acc1.Id;
        acc2.MDM_Validation_Status__c = 'Rejected';
        update acc2;
        test.stopTest();
    }
    
    @isTest
    static void testMethod2() {
        test.startTest();
        List<Account> acc = new List<Account>();
        Account acc1 = UTL_TestData.createAccount();
        acc.add(acc1);
        insert acc;
        new SLT_AccountContactRelation().getAccountContactRelations(new Set<String>{'Id'}, acc1.id, 'test', false);
        test.stopTest();
    }
    
    @isTest
    static void testMethod3() {
        test.startTest();
        List<Account> acc = new List<Account>();
        Account acc1 = UTL_TestData.createAccount();
        acc.add(acc1);
        insert acc;
        List<AccountContactRelation> acr=new SLT_AccountContactRelation().getAccountContactRelationsforOWFUsingSubGroupAndFunction(new Set<String>{'Id'}, acc1.id, 'test', false,new Set<String>{'COE Lead / Category Lead / SME'},new Set<String>{'TSL'});
        test.stopTest();
        System.assertEquals(0, acr.size());
    }
}