src/objects/Account_Compliance__c.object
<CustomObject>
    <description>Created under TPA-MC-ESPSFDCTPA-2218</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Created Under TPA-MC-ESPSFDCTPA-2218</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Compliances</relationshipLabel>
        <relationshipName>Account_Compliances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_TPA_Compliance_Hold_Date__c</fullName>
        <description>Created Under TPA-MC-ESPSFDCTPA--2218</description>
        <label>Vendor TPA Compliance Hold Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vendor_TPA_Compliance_Hold_Reason__c</fullName>
        <description>Created Under TPA-MC-ESPSFDCTPA-2218</description>
        <label>Vendor TPA Compliance Hold Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
	
    <fields>
        <fullName>Vendor_TPA_Compliance_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created Under TPA-MC-ESPSFDCTPA-2218</description>
        <label>Vendor TPA Compliance Hold</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Compliance</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Compliance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Compliances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TPA_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>email recipients</description>
    <fields>
        <fullName>Base_Url__c</fullName>
        <label>Base Url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>TPA Settings</label>
</CustomObject>

src/classes/CNT_TPA_AccountOnHoldReport.cls
public with sharing class CNT_TPA_AccountOnHoldReport {
    @AuraEnabled(cacheable = true)
    public static string baseURL(){
        return TPA_Settings__c.getOrgDefaults().Base_Url__c;
    }
    @AuraEnabled(cacheable=true)
    public static List<Account_Compliance__c> getComplianceHoldData(String sortBy){
        String query = 'SELECT id,Name, Account__r.Name, Vendor_TPA_Compliance_Hold_Date__c,Vendor_TPA_Compliance_Hold_Reason__c, Vendor_TPA_Compliance_Hold__c, (SELECT id, Subject, Description FROM Tasks WHERE subject LIKE \'Vendor was on Hold%\' ORDER BY createdDate DESC)  FROM Account_Compliance__c ORDER BY Account__r.Name ' + (sortBy == null ? 'ASC': sortBy);
        return Database.query(query);
    }
}