src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Pending for Descartes</fullName>
                </value>
                <value>
                    <fullName>Rejected by Descartes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <description>SFDCDEVOPS-186: The validation state of this address with respect to MDM System.</description>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>MDM_Validated</fullName>
        <active>true</active>
        <label>MDM Validated</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BNF_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BNF_Release__c</fullName>
        <label>BNF Release</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BNF_Settings</label>
</CustomObject>

src/objects/Current_Release_Version__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-MC-ESPSFDCQI-3242 - This custom setting holds the current release version</description>
    <fields>
        <fullName>Current_Release__c</fullName>
        <description>CRM-MC-ESPSFDCQI-2944 - Field to store the current release</description>
        <inlineHelpText>Field to store the current release</inlineHelpText>
        <label>Current Release</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Current Release Version</label>
</CustomObject>

src/objects/MIBNF2__c.object
<CustomObject>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the name of the Revenue Analyst who will be processing the BNF.</inlineHelpText>
        <label>Revenue Analyst</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Revenue_Analyst__c.Available_for_Selection__c</field>
                <operation>equals</operation>
                <value>TRUE</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>$Source.MIBNF_Status__c</field>
                <operation>notEqual</operation>
                <value>New</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Revenue_Analyst__c</referenceTo>
        <relationshipName>R00NT0000001UO6hMAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>IMS Billing Org Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>IMS_Sales_Org__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE01</fullName>
                </value>
                <value>
                    <fullName>AE02</fullName>
                </value>
                <value>
                    <fullName>AE03</fullName>
                </value>
                <value>
                    <fullName>AR01</fullName>
                </value>
                <value>
                    <fullName>AT52</fullName>
                </value>
                <value>
                    <fullName>AT71</fullName>
                </value>
                <value>
                    <fullName>AU01</fullName>
                </value>
                <value>
                    <fullName>AU06</fullName>
                </value>
                <value>
                    <fullName>AU07</fullName>
                </value>
                <value>
                    <fullName>AU08</fullName>
                </value>
                <value>
                    <fullName>BD01</fullName>
                </value>
                <value>
                    <fullName>BE51</fullName>
                </value>
                <value>
                    <fullName>BE52</fullName>
                </value>
                <value>
                    <fullName>BE54</fullName>
                </value>
                <value>
                    <fullName>BE63</fullName>
                </value>
                <value>
                    <fullName>BE64</fullName>
                </value>
                <value>
                    <fullName>BE72</fullName>
                </value>
                <value>
                    <fullName>BE73</fullName>
                </value>
                <value>
                    <fullName>BE74</fullName>
                </value>
                <value>
                    <fullName>BO01</fullName>
                </value>
                <value>
                    <fullName>BR01</fullName>
                </value>
                <value>
                    <fullName>BR71</fullName>
                </value>
                <value>
                    <fullName>CA03</fullName>
                </value>
                <value>
                    <fullName>CA04</fullName>
                </value>
                <value>
                    <fullName>CA10</fullName>
                </value>
                <value>
                    <fullName>CA15</fullName>
                </value>
                <value>
                    <fullName>CH07</fullName>
                </value>
                <value>
                    <fullName>CH12</fullName>
                </value>
                <value>
                    <fullName>CH13</fullName>
                </value>
                <value>
                    <fullName>CH51</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Multi Invoice BNF</label>
    <nameField>
        <displayFormat>MIBNF-{000000}</displayFormat>
        <label>MIBNF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Multi Invoice BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MIBNF_Component__c.object
<CustomObject>
    <description>Multi Invoice BNF Component which is child BNF for an Opportunity</description>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <formula>MIBNF__r.Revenue_Analyst__r.User__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue Analyst</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <formula>Text(MIBNF__r.Sales_Org_Code__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales_Org_Code</label>
        <type>Text</type>
    </fields>
    <label>BNF</label>
    <nameField>
        <label>BNF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mulesoft_Integration_Control__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-QI-ESPSFDCQI-784 - Custom setting to control various aspects of Mulesoft integration (suppress outbound messages etc.)</description>
    <fields>
        <fullName>Enable_OLIS_JSON__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CRM-MC-ESPSFDCQI-768</description>
        <label>Enable OLIS JSON</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_OLI_Sync_Validation__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CRM-MC-ESPSFDCQI-1052</description>
        <label>Enable OLI Sync Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Opportunity_Sync_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-1083</description>
        <label>Enable Opportunity Sync Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Mulesoft_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-768</description>
        <label>Is Mulesoft User</label>
        <type>Checkbox</type>
    </fields>
    <label>Mulesoft Integration Control</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Update_Type__c</fullName>
        <defaultValue>&apos;USER&apos;</defaultValue>
        <description>CRM-QI-ESPSFDCQI-1083 Field to specify type of update that is occurring (user update / talkback update via Mulesoft integration / slave update via Mulesoft integration)</description>
        <inlineHelpText>Field to specify type of update that is occurring (user update / talkback update via Mulesoft integration / slave update via Mulesoft integration)</inlineHelpText>
        <label>Update Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Hierarchy_Level__c</fullName>
        <description>CRM-MC-ESPSFDCQI-68 -  Formula field that references the Products Hierarchy Level.</description>
        <formula>TEXT(PricebookEntry.Product2.Hierarchy_Level__c)</formula>
        <inlineHelpText>Details where the Product is set within the Product hierarchy.</inlineHelpText>
        <label>Hierarchy Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LI_OpportunityLineItem_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC Id of shadow OpportunityLineItem record in legacy IMS org</description>
        <externalId>true</externalId>
        <inlineHelpText>SFDC Id of shadow OpportunityLineItem record in legacy IMS org</inlineHelpText>
        <label>LI OpportunityLineItem Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Update_Type__c</fullName>
        <defaultValue>&apos;USER&apos;</defaultValue>
        <description>CRM-QI-ESPSFDCQI-1052 Field to specify type of update that is occurring (user update / talkback update via Mulesoft integration / slave update via Mulesoft integration)</description>
        <inlineHelpText>Field to specify type of update that is occurring (user update / talkback update via Mulesoft integration / slave update via Mulesoft integration)</inlineHelpText>
        <label>Update Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Hierarchy_Level__c</fullName>
        <description>CRM-MC-ESPSFDCQI-68 - Details where the Product is set within the Product Hierarchy.</description>
        <label>Hierarchy Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Analyst__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-3168 - This custom object is used to store the Revenue Analyst.</description>
    <label>Revenue Analyst</label>
    <nameField>
        <label>Revenue Analyst Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Analysts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_Update_Comp_RA.cls
/*
* Version       : 1.0
* Description   : Test Class for Update_Comp_RA MIBNF trigger
*/
@isTest
public class TST_Update_Comp_RA {
    /**
* This method used to set up testdata
*/ 
    @testSetup
    static void dataSetup() {
        Current_Release_Version__c crv = new Current_Release_Version__c();
        crv.Current_Release__c = '3000.01';
        upsert crv;
        BNF_Settings__c bs = new BNF_Settings__c();
        bs.BNF_Release__c = '2019.01';
        upsert bs;
        upsert new  Mulesoft_Integration_Control__c(Enable_OLIS_JSON__c = true, Is_Mulesoft_User__c = false, Enable_OLI_Sync_Validation__c = true, Enable_Opportunity_Sync_Validation__c = true);
        Account acc = UTL_TestData.createAccount();
        insert acc;
        Opportunity opp = UTL_TestData.createOpportunity(acc.Id);
        insert opp;
        Product2 product = UTL_TestData.createProduct();
        product.Hierarchy_Level__c = CON_CRM.MATERIAL_LEVEL_HIERARCHY_OLI;
        insert product;
        PricebookEntry pbEntry = UTL_TestData.createPricebookEntry(product.Id);
        insert pbEntry;
        OpportunityLineItem oppLineItem = UTL_TestData.createOpportunityLineItem(opp.Id, pbEntry.Id);
        oppLineItem.Update_Type__c = CON_CRM.UPDATE_TYPE_MULESOFT_SLAVE;
        oppLineItem.LI_OpportunityLineItem_Id__c = opp.id;
        insert oppLineItem;
        OpportunityLineItemSchedule olis = UTL_TestData.createOpportunityLineItemSchedule(oppLineItem.Id);
        insert olis;
        Revenue_Analyst__c revenueAnalyst = UTL_TestData.createRevenueAnalyst();
        insert revenueAnalyst;
        MIBNF2__c TestMIBNF = UTL_TestData.createMIBNF(opp, revenueAnalyst);
        insert TestMIBNF;
        List<Address__c> addressesList = UTL_TestData.createAddresses(acc);
        for(Integer index = 0; index < addressesList.size(); index++) {
            addressesList[index].MDM_Validation_Status__c = 'Validated';
            addressesList[index].RecordTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByDeveloperName().get('MDM_Validated').getRecordTypeId(); 
        }
        CON_GLOBAL.RELEASE_MAY_2021 = 9999.99;
        insert addressesList;
    }
    
    /**
    * This method used to test sobject field list
    */    
    @IsTest
    static void testUpdateCompRA() {
        Test.startTest();
            MIBNF2__c TestMIBNF = [SELECT id FROM MIBNF2__c LIMIT 1];
            List<Address__c> addressesList= [SELECT Id FROM Address__c];
            MIBNF_Component__c TestMIBNF_Comp = UTL_TestData.createMIBNF_Comp(TestMIBNF,addressesList);
            insert TestMIBNF_Comp;
            
            Revenue_Analyst__c revenueAnalyst2 = UTL_TestData.createRevenueAnalyst();
            insert revenueAnalyst2;

        	MIBNF2__c mibnf = [SELECT Id FROM MIBNF2__c LIMIT 1];
            mibnf.Revenue_Analyst__c = revenueAnalyst2.Id;
            update mibnf;
        Test.stopTest();
    }
    
    @IsTest
    static void testUpdateSalesOrgCode() {
        Test.startTest();
            MIBNF2__c TestMIBNF = [SELECT id FROM MIBNF2__c LIMIT 1];
            List<Address__c> addressesList= [SELECT Id FROM Address__c];
            MIBNF_Component__c TestMIBNF_Comp = UTL_TestData.createMIBNF_Comp(TestMIBNF,addressesList);
            insert TestMIBNF_Comp;
            
            TestMIBNF.Sales_Org_Code__c = 'CH07';
            update TestMIBNF;
        Test.stopTest();
    }
    
}