src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>CSM-ACN-S-0062 - Contact description</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>PEP-ACN-AM_CM-11 Partner type</description>
        <label>Partner Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integrator Partner</fullName>
                </value>
                <value>
                    <fullName>Data Partner</fullName>
                </value>
                <value>
                    <fullName>Tech Partner</fullName>
                </value>
                <value>
                    <fullName>Training Partner</fullName>
                </value>
                <value>
                    <fullName>CLM Agency</fullName>
                </value>
                <value>
                    <fullName>One Home for Sites</fullName>
                </value>
                <value>
                    <fullName>AMESA - Integrator Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Case_Type__c</fullName>
        <label>Portal Case Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Information Offering</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Technology Solutions</fullName>
                </value>
                <value>
                    <fullName>DATA</fullName>
                    <isActive>false</isActive>
                    <label>DATA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_QI_Announcement__c.object
<CustomObject>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Partner_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSM Announcement</label>
    <nameField>
        <displayFormat>AN-{0000000000}</displayFormat>
        <label>CSM QI Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSM Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSM_QI_Data_Portal_Queue_User_details__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Data Portal Queue User details</relationshipLabel>
        <relationshipName>Data_Portal_Queue_User_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Current_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Current Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseRecordType__c</fullName>
        <label>Case Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ActivityPlan</fullName>
                </value>
                <value>
                    <fullName>DATACase</fullName>
                </value>
                <value>
                    <fullName>TechnologyCase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queue_User_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue User Relationship</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Queue_User_Relationship__c.Type__c</field>
                <operation>equals</operation>
                <value>Queue</value>
            </filterItems>
            <infoMessage>Please Select the Queue user Relationship type as queue</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Queue_User_Relationship__c</referenceTo>
        <relationshipLabel>Data Portal Queue User details</relationshipLabel>
        <relationshipName>Data_Portal_Queue_User_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>CSM-1116 Product Segregation to show only selected product to CSH User in Customer Service Hub. differentiate the CSH queue assignment and Product restriction functionality in CSH</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queue Assignment</fullName>
                    <default>true</default>
                    <label>Queue Assignment</label>
                </value>
                <value>
                    <fullName>Product Level Restriction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Portal Queue User details</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>CSM QI Data Portal  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Portal Queue User details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Community_Topics__c</fullName>
        <label>Community Topics</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Topics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecificToCSM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM - ACN - S0024 - Specific to CSM?</description>
        <label>Specific to CSM?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
    <fields>
        <fullName>Pillar__c</fullName>
        <description>CSM-1809: All - User Queue Enhancements</description>
        <formula>CASE(1,IF(BEGINS(LOWER(Name), &apos;data&apos;),1,0), &apos;Information Offering&apos;, IF(BEGINS(LOWER(Name), &apos;rnd&apos;),1,0), &apos;R&amp;D&apos;, IF(BEGINS(LOWER(Name), &apos;tech&apos;),1,0), &apos;Technology Solutions&apos;,&apos;&apos;)</formula>
        <label>Pillar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM - ACN - S-0007 - User Lookup</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Community_Topics.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ADA</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for CLM for Nexxus MI</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for CLM for OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for ePromo</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for Kadrige iDetailing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for Kadrige iSharing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for OCE Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Spend 360</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Spend 360 - US</fullName>
    </customValue>
    <customValue>
        <fullName>Audits Nationaux Ethiques</fullName>
    </customValue>
    <customValue>
        <fullName>Business Rules &amp; Processes</fullName>
    </customValue>
    <customValue>
        <fullName>CLM Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>CLM For Nexxus MI</fullName>
    </customValue>
    <customValue>
        <fullName>CLM For OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Connectivity &amp; Wireless</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Health</fullName>
    </customValue>
    <customValue>
        <fullName>Content for Kadrige iDetailing</fullName>
    </customValue>
    <customValue>
        <fullName>CRM Software</fullName>
    </customValue>
    <customValue>
        <fullName>Dashboard (Flex/SFE)</fullName>
    </customValue>
    <customValue>
        <fullName>DataView</fullName>
    </customValue>
    <customValue>
        <fullName>DDD</fullName>
    </customValue>
    <customValue>
        <fullName>EPPM</fullName>
    </customValue>
    <customValue>
        <fullName>ePromo</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware &amp; Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Hospi 360</fullName>
    </customValue>
    <customValue>
        <fullName>IMS One</fullName>
    </customValue>
    <customValue>
        <fullName>Internal &amp; HD Processes</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA CDW</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA Data Connector</fullName>
    </customValue>
    <customValue>
        <fullName>OneKey</fullName>
    </customValue>
    <masterLabel>Community Topics</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Partner_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Integrator Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Data Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Tech Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CLM Agency</fullName>
    </customValue>
    <customValue>
        <fullName>One Home for Sites</fullName>
    </customValue>
    <customValue>
        <fullName>AMESA - Integrator Partner</fullName>
    </customValue>
    <description>PRM-982: Added two picklist values for Knowledge and CSM Announcement objects.</description>
    <masterLabel>Partner Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_CNT_CSM_Announcements.cls
@isTest
public class TST_CNT_CSM_Announcements {
    @testSetup
    static void dataSetup() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        String profilId2 = [select id from Profile where Name='System Administrator'].Id;
        User accOwner = New User(Alias = 'su',UserRoleId= portalRole.Id, ProfileId = profilId2, Email = 'john2@iqvia.com',IsActive =true,Username ='john2@iqvia.com', LastName= 'testLastName', CommunityNickname ='testSuNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', UserPermissionsKnowledgeUser = true, employeeNumber= '080808081');
        accOwner.Change_Request_Description__c = 'Change Request Descritpion';
        insert accOwner;
        System.runAs (accOwner) {
            Account account = UTL_TestData.createAccount();
            account.ownerId=accOwner.Id;
            insert account;
            Product2 product = UTL_TestData.createProduct();
            product.Community_Topics__c='OneKey';
            product.SpecificToCSM__c = True;
            insert product;
            Asset asset = New asset (Name='AssetTest', AccountId=account.Id, Product2Id = product.id);
            insert asset;
            CSM_QI_Announcement__c announcement = New CSM_QI_Announcement__c(Subject__c='test', Description__c='test',Expiry_Date__c= Date.newInstance(2030, 2, 17) , Contact_User_Type__c= 'HO User', Pillar__c=CON_CSM.S_TECHNOLOGY_SOLUTIONS);
            insert announcement;
        }
    }

    @IsTest
    static void testGetAnnouncementsForCurrentUser() {
        List<CSM_QI_Announcement__c> announcements = new  List<CSM_QI_Announcement__c>();
        Account acc = [SELECT id FROM Account WHERE Name = 'TestAccount'];
        Contact contact = new Contact(
            Firstname='Brian',
            Lastname='Dent',
            Phone='(619)852-4569',
            Department='Mission Control',
            Title='Mission Specialist - Neptune',
            Email='john@acme.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            Partner_Type__c='Integrator Partner',
            AccountId = acc.Id);
        insert contact;
        Queue_User_Relationship__c qurPortal = new Queue_User_Relationship__c(Name = 'Q1',User__c = UserInfo.getUserId(),Type__c = 'Queue');
        insert qurPortal;
        CSM_QI_Data_Portal_Queue_User_details__c dT = new CSM_QI_Data_Portal_Queue_User_details__c();
        dT.Queue_User_Relationship__c = qurPortal.Id;
        dT.Account__c = acc.Id;
        dT.All_Current_Users__c = true;
        dT.CaseRecordType__c = 'TechnologyCase';
        dT.Type__c ='Queue Assignment';
        dT.Order__c = 1;
        insert dT;
        CSM_QI_Data_Portal_Queue_User_details__c dd = new CSM_QI_Data_Portal_Queue_User_details__c();
        dd.Queue_User_Relationship__c = qurPortal.Id;
        dd.Account__c = acc.Id;
        dd.All_Current_Users__c = true;
        dd.CaseRecordType__c = 'DATACase';
        dd.Type__c ='Queue Assignment';
        dd.Order__c = 1;
        insert dd;
        String profilId = [select id from Profile where Name='CSM Customer Community Plus Login User'].Id;
        User user = New User(Alias = 'com', Email = 'john@acme.com',IsActive =true, ContactId = contact.Id, ProfileId = profilId,Username =' john@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', employeeNumber= '080808082');
        insert user;
        Test.startTest();
        system.runAs(user){
            announcements = CNT_CSM_Announcements.getAnnouncementsForCurrentUser(true);
            announcements = CNT_CSM_Announcements.getAnnouncementsForCurrentUser(false);
        }
    }
    
    @IsTest
    static void testGetAnnouncementsForCurrentPRMUser() {
        List<CSM_QI_Announcement__c> announcements = new  List<CSM_QI_Announcement__c>();
        Account acc = [SELECT id FROM Account WHERE Name = 'TestAccount'];
        Contact contact = new Contact(
            Firstname='Brian',
            Lastname='Dent',
            Phone='(619)852-4569',
            Department='Mission Control',
            Title='Mission Specialist - Neptune',
            Email='john@acme.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            Partner_Type__c='Integrator Partner',
            AccountId = acc.Id);
        insert contact;
        String profilId = [select id from Profile where Name='PRM Community User'].Id;
        User user = New User(Alias = 'com', Email = 'john@acme.com',IsActive =true, ContactId = contact.Id, ProfileId = profilId,Username =' johnprm@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', employeeNumber= '080808083');
        insert user;
        Test.startTest();
        system.runAs(user){
            announcements = CNT_CSM_Announcements.getAnnouncementsForCurrentPRMUser(true,true);
            announcements = CNT_CSM_Announcements.getAnnouncementsForCurrentPRMUser(false,false);
        }
    }
}