src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Pending for Descartes</fullName>
                </value>
                <value>
                    <fullName>Rejected by Descartes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>Holds the SAP Code this account if it has been verified. This replaces the SAP_SP_Code__c, SAP_PC_Code__c and SAP_Code__c fields.</description>
        <inlineHelpText>Holds the account&apos;s unique SAP Reference. You may refer to the account by its SAP Reference if you prefer. If it is a Parent-level account (mostly), it will be in the form 5xxxxx, if it is SuperParent-level account, then it is in the form HNCSPxxxxxx.</inlineHelpText>
        <label>SAP Reference</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of the account that this address pertains to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AccountAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enabled_Sales_Orgs__c</fullName>
        <label>Enabled Sales Orgs</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>International_Name__c</fullName>
        <label>Customer Name (Local)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <description>SFDCDEVOPS-186: The validation state of this address with respect to MDM System.</description>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>SAP Base code that corresponds to this address. This is hierarchically-based on the SAP Parent code in the Account and the looked up in SAP. When it is not populated, then this address had not been validated. This is not editable by normal users.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Base code that corresponds to this address.</inlineHelpText>
        <label>SAP Base Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_TGRH_Address.cls
/**
* This test class is used to test all methods in SAP Contact Domain class.
* version : 1.0
*/
@isTest
public class TST_TGRH_Address {
    
    /**
    * This test method used is test Address method.
    */ 
    static testMethod void testMethodForAddress() {
        CON_GLOBAL.RELEASE_MAY_2021 = UTL_GLOBAL.getCurrentReleaseVersion();
        Account newAccount = UTL_TestData.createAccount();
        insert newAccount;
        Test.startTest();
        Address__c TempAddress = new Address__c();
        TempAddress.Name = 'Test Address';
        TempAddress.Enabled_Sales_Orgs__c='IHA, IMS Health Rotkreuz [CH03]';
        TempAddress.Account__c=newAccount.Id;
        TempAddress.SAP_Reference__c = String.valueOf(495000);
        TempAddress.International_Name__c = 'Test Address Name';
        insert TempAddress;
        TempAddress.SAP_Reference__c = '123';
        TempAddress.MDM_Validation_Status__c = 'Validated';
        update TempAddress;
        Address__c TempAddress1 = new Address__c();
        TempAddress1.Name = 'Test Address 1';
        TempAddress1.Enabled_Sales_Orgs__c='IHA, IMS Health Rotkreuz [CH03]';
        TempAddress1.Account__c=newAccount.Id;
        TempAddress1.SAP_Reference__c = String.valueOf(4950000);
        TempAddress1.International_Name__c = 'Test Address Name 1';
        insert TempAddress1;
        TempAddress1.MDM_Validation_Status__c = 'Rejected';
        update TempAddress1;
        Test.stopTest();
    }
    
}