src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductAttributeValue__c.object
<CustomObject>
    <description>Represents the attribute values for a product class</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>CPQ-IQ-LC-9425: User for Amesa price calculation for ATC and OTC codes classification for partial product use.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>National &amp; Sub National</fullName>
                </value>
                <value>
                    <fullName>Sub National</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Attribute Value</label>
    <nameField>
        <displayFormat>AV-{0000000000}</displayFormat>
        <label>Attribute Value Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ATC_OTC_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>LC-8878 : Country Code based on the selection of  ATC OTC Country.</description>
        <label>Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>EG</fullName>
                </value>
                <value>
                    <fullName>JO</fullName>
                </value>
                <value>
                    <fullName>KW</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>SA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>TN</fullName>
                </value>
                <value>
                    <fullName>DZ</fullName>
                </value>
                <value>
                    <fullName>FW</fullName>
                </value>
                <value>
                    <fullName>ZA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hierarchy1_Code__c</fullName>
        <description>LC-8878 : Hierarchy1 Code for the level 1 list.</description>
        <label>Hierarchy1 Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy1_Name__c</fullName>
        <description>LC-8878 : Hierarchy1 Name for the level 1 list of ATC.</description>
        <label>Hierarchy1 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy2_Code__c</fullName>
        <description>LC-8878 : Hierarchy2 Code for the level 2 list of ATC.</description>
        <label>Hierarchy2 Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy2_Name__c</fullName>
        <description>LC-8878 : Hierarchy2 Name for the level 2 list of ATC.</description>
        <label>Hierarchy2 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy3_Code__c</fullName>
        <description>LC-8878 : Hierarchy3 Code for the level 3 list of ATC.</description>
        <label>Hierarchy3 Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy3_Name__c</fullName>
        <description>LC-8878 : Hierarchy3 Name for the level 3 list of ATC.</description>
        <label>Hierarchy3 Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy4_Code__c</fullName>
        <description>LC-8878 : Hierarchy4 Code for the level 4 list of ATC.</description>
        <label>Hierarchy4 Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy4_Name__c</fullName>
        <description>LC-8878 : Hierarchy4 Name for the level 4 list of ATC.</description>
        <label>Hierarchy4 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>LC-8878 : Type for the list ATC.</description>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ATC_OTC Classification</label>
    <nameField>
        <displayFormat>ATC_OTC-{0000}</displayFormat>
        <label>ATC_OTC Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATC_OTC Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CPQ_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key_Generation_Org__c</fullName>
        <description>[Story number]</description>
        <label>Key Generation Org</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CPQ Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Legacy_Quintiles_Opportunity_Number__c</fullName>
        <description>CRM-QI-ESPSFDCQI-314 Opportunity Number of opportunity record in legacy Quintiles org</description>
        <externalId>true</externalId>
        <inlineHelpText>Opportunity Number of opportunity record in legacy Quintiles org</inlineHelpText>
        <label>Legacy Quintiles Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1128 - Indicates which line of business the Opportunity aligns to. Used within the Mulesoft integration.</description>
        <inlineHelpText>Indicates which line of business the Opportunity aligns to.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allscripts Data</fullName>
                </value>
                <value>
                    <fullName>Avacare</fullName>
                </value>
                <value>
                    <fullName>Biosimilars</fullName>
                    <isActive>false</isActive>
                    <label>Biosimilars</label>
                </value>
                <value>
                    <fullName>Biostatistical/Medical Writing</fullName>
                    <isActive>false</isActive>
                    <label>Biostatistical/Medical Writing</label>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Clinical Pharmacology</fullName>
                    <isActive>false</isActive>
                    <label>Clinical Pharmacology</label>
                </value>
                <value>
                    <fullName>Clinical Technology</fullName>
                </value>
                <value>
                    <fullName>Clintec</fullName>
                    <isActive>false</isActive>
                    <label>Clintec</label>
                </value>
                <value>
                    <fullName>Commercial Solutions</fullName>
                </value>
                <value>
                    <fullName>Connected Devices</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Consulting Market Access</fullName>
                </value>
                <value>
                    <fullName>Core Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Core Clinical</label>
                </value>
                <value>
                    <fullName>Data Council</fullName>
                </value>
                <value>
                    <fullName>Data Management</fullName>
                    <isActive>false</isActive>
                    <label>Data Management</label>
                </value>
                <value>
                    <fullName>Data Sciences</fullName>
                </value>
                <value>
                    <fullName>Digital Patient (DPU)</fullName>
                    <isActive>false</isActive>
                    <label>Digital Patient (DPU)</label>
                </value>
                <value>
                    <fullName>DrugDev</fullName>
                    <isActive>false</isActive>
                    <label>DrugDev</label>
                </value>
                <value>
                    <fullName>Early Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Early Clinical</label>
                </value>
                <value>
                    <fullName>Early Clinical Development</fullName>
                </value>
                <value>
                    <fullName>ECG/Cardiac Safety</fullName>
                    <isActive>false</isActive>
                    <label>ECG/Cardiac Safety</label>
                </value>
                <value>
                    <fullName>Evidence Based Medicine (EBM)</fullName>
                </value>
                <value>
                    <fullName>GFR Clinical</fullName>
                    <isActive>false</isActive>
                    <label>GFR Clinical</label>
                </value>
                <value>
                    <fullName>Health Engagement &amp; Communication</fullName>
                </value>
                <value>
                    <fullName>Innovation</fullName>
                </value>
                <value>
                    <fullName>IT Services</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                    <isActive>false</isActive>
                    <label>Lab</label>
                </value>
                <value>
                    <fullName>Lifecycle Safety</fullName>
                    <isActive>false</isActive>
                    <label>Lifecycle Safety</label>
                </value>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Medical Communications</fullName>
                    <isActive>false</isActive>
                    <label>Medical Communications</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__ConfigurationType__c</fullName>
        <description>The product configuration type</description>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                    <default>true</default>
                    <label>Standalone</label>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>CLM-MC-CLMCMA-13641 - Quote types to identify different type of Quotes.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Order Ballpark</fullName>
                </value>
                <value>
                    <fullName>CNF Quote</fullName>
                    <default>true</default>
                    <label>CNF Quote</label>
                </value>
                <value>
                    <fullName>CO Log</fullName>
                </value>
                <value>
                    <fullName>New Change Order</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                </value>
                <value>
                    <fullName>LRA</fullName>
                </value>
                <value>
                    <fullName>ECO-Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_SLT_ProductAttributeValue.cls
@isTest(SeeAllData=false)
public class TST_SLT_ProductAttributeValue {
    @testSetup
    static void dataSetup(){
        Account testAccount = UTL_TestData.createAccount();
        testAccount.Name = 'Test Acc1';
        insert testAccount;
        
        Opportunity testOpportunity = UTL_TestData.createOpportunity(testAccount.Id);
        testOpportunity.Line_of_Business__c = CON_CPQ.SAMPLE_LINE_OF_BUSINESS;
        testOpportunity.Legacy_Quintiles_Opportunity_Number__c = CON_CPQ.TEST_OPPORTUNITY_NUMBER;
        insert testOpportunity;
        
        Product2 product1 = new Product2();
        product1.IsActive = true;
        product1.Name = 'Test Bundle';
        product1.ProductCode = 'CPQ-Bundle';
        product1.Apttus_Config2__ConfigurationType__c = 'Bundle';
        insert product1;
        Product2 product11 = new Product2();
        product11.IsActive = true;
        product11.Name = 'Test Option';
        product11.ProductCode = 'CPQ-TS-AMESA-Data-PI-KLPO';
        product11.Apttus_Config2__ConfigurationType__c = CON_CPQ.OPTION;
        insert product11;
        
        CPQ_Settings__c cpqSetting = new CPQ_Settings__c();
        cpqSetting.Name = 'Test CPQ Setting';
        cpqSetting.Key_Generation_Org__c = UserInfo.getOrganizationId();
        insert cpqSetting; 
        
        ATC_OTC_Classification__c atcClass = new ATC_OTC_Classification__c();
        atcClass.Hierarchy1_Code__c = 'A0';
        atcClass.Hierarchy1_Name__c = 'A0 ALIMENTARY T.& METABOLISM';
        atcClass.Hierarchy2_Code__c = 'A01';
        atcClass.Hierarchy2_Name__c = 'A01 STOMATOLOGICALS';
        atcClass.Hierarchy3_Code__c = 'A01A';
        atcClass.Hierarchy3_Name__c = 'A01A STOMATOLOGICALS';
        atcClass.Hierarchy4_Code__c = 'A01A0';
        atcClass.Hierarchy4_Name__c = 'A01A0 STOMATOLOGICALS';
        atcClass.Country_Code__c = 'KW';
        atcClass.Market_Share__c = 0.24;
        atcClass.Market_Type__c = 'LPO';
        atcClass.Standard_Type__c = CON_CPQ.EPHMRA;
        atcClass.Type__c = CON_CPQ.ATC;
        atcClass.Migration_Id__c = 'TD-20';
        insert atcClass;
    }
    
    static Product2 buildTestProduct(String productName, string type, String code) {
        Product2 product = new Product2();
        product.IsActive = true;
        product.Name = productName;
        product.ProductCode = code;
        return product;
    }
    
    
    @isTest(SeeAllData=false)
    static void testSaveMarketShare() {
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'Test Acc1'];
        Opportunity testOpportunity = [SELECT Id FROM Opportunity WHERE AccountId =: testAccount.Id ];
        Apttus_Config2__PriceList__c testPriceList = TST_TestGeneratorClass.buildTestPriceList('Test PriceList');
        Apttus_Proposal__Proposal__c testProposal = TST_TestGeneratorClass.setProposalData(CON_CPQ.TECH_SOLUTION, testOpportunity.Id, CON_CPQ.AMESA, null,testPriceList.Id);
        
        Product2 testBundleProduct = [SELECT Id FROM Product2 WHERE Name = 'Test Bundle' AND ProductCode = 'CPQ-Bundle'];
        Product2 testOptionProduct =  [SELECT Id FROM Product2 WHERE Name = 'Test Option' AND ProductCode = 'CPQ-TS-AMESA-Data-PI-KLPO'];
        
        insert  TST_TestGeneratorClass.createOptionConfigLineItem(TST_TestGeneratorClass.buildTestConfiguration(testProposal.Id), 1, 1, testBundleProduct.Id, testOptionProduct.Id, 1, 0);
        Apttus_Config2__LineItem__c lineItem = [SELECT Id, Name,Apttus_Config2__ConfigurationId__r.Id From Apttus_Config2__LineItem__c Limit 1];
        
        Apttus_Config2__ProductAttributeValue__c pav= new Apttus_Config2__ProductAttributeValue__c();
        pav.Catergory__c = CON_CPQ.PARTIAL;
        pav.Data_Delivery_Frequency__c = CON_CPQ.QUARTERLY;
        pav.Eligible_Countries__c = 'KW';
        pav.Apttus_Config2__LineItemId__c = lineItem.Id;
        insert pav;
        Apttus_Config2__LineItem__c itemObj = new Apttus_Config2__LineItem__c();
        itemObj.Id = lineItem.Id;
        itemObj.Apttus_Config2__AttributeValueId__c = pav.Id;
        update itemObj;
        
        Apttus_Config2__TempObject__c tempObj = new Apttus_Config2__TempObject__c();
        tempObj.Apttus_Config2__ConfigurationId__c = lineItem.Apttus_Config2__ConfigurationId__r.Id;
        insert tempObj;
        Decimal marketShare = 23.91;
        String selectedAtcOtcCodes = 'A01';
        String quarter = '2023 Q1';
        Map<String, Decimal> aggregateATCOTCMap = new Map<String, Decimal>();
        aggregateATCOTCMap.put('Count', 1);
        Test.startTest();
        String cartLink = CNT_CPQ_ATCClassesController.saveMarketShare(lineItem.Id, marketShare, selectedAtcOtcCodes, quarter, json.serialize(aggregateATCOTCMap));
        String cartLinkGenerate = CNT_CPQ_ATCClassesController.handleCancle(lineItem.Id);
        Test.stopTest();
        System.assert( cartLink != null, 'Cart link fetched Successfully');
        System.assert( cartLinkGenerate != null, 'CartLink generated Successfully');        
    }
    
    @IsTest
    static void testgetAttributeRecords() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1 ];
        Apttus_Proposal__Proposal__c quote = UTL_TestData.setTSProposalData(true, CON_CPQ.TECH_SOLUTION, opp.Id, CON_CPQ.OCE);
        Apttus_Config2__ProductConfiguration__c prodConfig = new Apttus_Config2__ProductConfiguration__c();
        prodConfig.Apttus_QPConfig__Proposald__c = quote.Id;
        insert prodConfig;
        Set<String> attributeSet = new Set<String>{'O_Country__c'}; 
            
        List<Product2> prodList = new List<Product2>();
        Product2 prod = TST_TestGeneratorClass.buildTestProduct('LC9', 'Bundle', CON_CPQ.CPQ_TS_AMESA_Data_PI, 'US', 'Go Blue');       
        prod.CanUseRevenueSchedule = true;
        prodList.add(prod);
        Product2 prod1 = TST_TestGeneratorClass.buildTestProduct('LC9', 'Option', CON_CPQ.CPQ_TS_AMESA_Data_STD, 'US', 'Go Blue');
        prod1.CanUseRevenueSchedule = true;
        prodList.add(prod1);
        Product2 prod2 = TST_TestGeneratorClass.buildTestProduct('LC1', 'Option', CON_CPQ.CPQ_TS_AMESA_Data_SL_SF, 'US', 'Go Blue');
        prod2.CanUseRevenueSchedule = true;
        prodList.add(prod2);
        insert prodList;
        
        List<Apttus_Config2__LineItem__c> lineItemList = new List<Apttus_Config2__LineItem__c>();
        Apttus_Config2__LineItem__c lineItem = TST_TestGeneratorClass.createOptionConfigLineItem(prodConfig.Id, 1, 1, prod.id, prod1.Id, 1, 100);
        lineItemList.add(lineItem);
        Apttus_Config2__LineItem__c lineItem1 = TST_TestGeneratorClass.createOptionConfigLineItem(prodConfig.Id, 1, 1, prod.Id, prod2.Id, 1, 200);
        lineItemList.add(lineItem1);
        insert lineItemList;
        
        List<Apttus_Config2__ProductAttributeValue__c> attributeList = new List<Apttus_Config2__ProductAttributeValue__c>();
        attributeList.add(new Apttus_Config2__ProductAttributeValue__c(O_Country__c = 'India', Apttus_Config2__LineItemId__c = lineItemList[0].Id));
        attributeList.add(new Apttus_Config2__ProductAttributeValue__c(O_Country__c = 'India', Apttus_Config2__LineItemId__c = lineItemList[1].Id));
        insert attributeList;
        
        Test.startTest();
            Map<Id, Apttus_Config2__ProductAttributeValue__c> attributeValue = new SLT_ProductAttributeValue().getProductAttributeRecords(new Set<Id>{attributeList[0].Id}, attributeSet);
            Map<Id, Apttus_Config2__ProductAttributeValue__c> attributeValue1 = new SLT_ProductAttributeValue().getProductAttributeRecords(new Set<Id>{attributeList[1].Id}, attributeSet);
        Test.stopTest();
		
        System.assertEquals(attributeValue.size()>0, true, 'Proposal Product Attribute Value record exists');
        System.assertEquals(attributeValue1.size()>0, true, 'Proposal Product Attribute Value record exists');
    }
}