src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>Holds the SAP Code this account if it has been verified. This replaces the SAP_SP_Code__c, SAP_PC_Code__c and SAP_Code__c fields.</description>
        <inlineHelpText>Holds the account&apos;s unique SAP Reference. You may refer to the account by its SAP Reference if you prefer. If it is a Parent-level account (mostly), it will be in the form 5xxxxx, if it is SuperParent-level account, then it is in the form HNCSPxxxxxx.</inlineHelpText>
        <label>SAP Reference</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of the account that this address pertains to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AccountAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enabled_Sales_Orgs__c</fullName>
        <label>Enabled Sales Orgs</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>International_Name__c</fullName>
        <label>Customer Name (Local)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>SAP Base code that corresponds to this address. This is hierarchically-based on the SAP Parent code in the Account and the looked up in SAP. When it is not populated, then this address had not been validated. This is not editable by normal users.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Base code that corresponds to this address.</inlineHelpText>
        <label>SAP Base Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SAP_Contact__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-3168 - This table contains the possible contact persons defined for a client in SAP based on the partner function of the contact.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>SAP Contacts</relationshipLabel>
        <relationshipName>SAP_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>SAP Contact Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>SAP Contact</label>
    <nameField>
        <label>SAP Contact Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_SLT_SAP_Contact.cls
/*
 * Version       : 1.0
 * Description   : Test Class for SLT_SAP_Contact
 */
@isTest
public class TST_SLT_SAP_Contact {
    
    /**
    * This method used to set up testdata
    */ 
    @testSetup
    static void dataSetup() {
    	Account newAccount = UTL_TestData.createAccount();
        insert newAccount;
        Address__c TempAddress = new Address__c();
        TempAddress.Name = 'Test Address';
        TempAddress.Enabled_Sales_Orgs__c='IHA, IMS Health Rotkreuz [CH03]';
        TempAddress.Account__c=newAccount.Id;
        TempAddress.SAP_Reference__c = String.valueOf(495000);
        TempAddress.International_Name__c = 'Test Address Name';
        insert TempAddress;
        SAP_Contact__c newSAPContact = New SAP_Contact__c();
        newSAPContact.Name= 'Test SAPContact 1';
        newSAPContact.Address__c = TempAddress.Id;
        newSAPContact.SAP_Contact_Number__c = String.valueOf(999999);
        insert newSAPContact;
    }
    
     /**
     * This method used to get SAP Contact by ID
     */    
    @IsTest
    static void testSelectBySapContactId() {
    	Map<Id, SAP_Contact__c> sapContactMap = new Map<Id, SAP_Contact__c>();
    	SAP_Contact__c sapContact = [SELECT Id FROM SAP_Contact__c WHERE Name = 'Test SAPContact 1'];
        Test.startTest();
        sapContactMap = new SLT_SAP_Contact().selectBySapContactId(new Set<Id> {sapContact.Id},new Set<String>{'Name'});
        Test.stopTest();
    }
   
}