src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <description>CSM - ACN - S0036 - Account Country</description>
        <label>Account Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Accounts are validated against SAP to ensure a match and to prevent duplication of accounts. &quot;New&quot; indicates that the account has not yet been validated against SAP, &quot;SAP Validated&quot; means that it should exist as a ParentAccount on SAP</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>SAP Validated</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agency_Program__c.object
<CustomObject>
    <description>PRM- Agency Program Catalog</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Program</label>
    <nameField>
        <label>Partner Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PRM_Contract_Renewal_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PRM-992 : Renewal Contract Reminder Alert modification</description>
        <label>PRM Contract Renewal Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>PEP-ACN-AM_CM-11 Partner type</description>
        <label>Partner Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integrator Partner</fullName>
                </value>
                <value>
                    <fullName>Data Partner</fullName>
                </value>
                <value>
                    <fullName>Tech Partner</fullName>
                </value>
                <value>
                    <fullName>Training Partner</fullName>
                </value>
                <value>
                    <fullName>CLM Agency</fullName>
                </value>
                <value>
                    <fullName>One Home for Sites</fullName>
                </value>
                <value>
                    <fullName>AMESA - Integrator Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1455 - Field value dependent on selected Industry</description>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Agency_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRM Contract management</description>
        <label>Partner Program</label>
        <referenceTo>Agency_Program__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Tracking_started__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Date Tracking started</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_executed_signed_contract_received__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Date executed (signed) contract received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Notification_Date__c</fullName>
        <label>First Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Non_Standard_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Standard Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Notification Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRM_Contract_type__c</fullName>
        <description>PRM contract management</description>
        <label>Partner Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Master Agency Agreement</fullName>
                </value>
                <value>
                    <fullName>Agency Program SOW</fullName>
                </value>
                <value>
                    <fullName>Sandbox Agreement</fullName>
                </value>
                <value>
                    <fullName>Non Disclosure Agreement</fullName>
                </value>
                <value>
                    <fullName>Logo/Trademark Agreement</fullName>
                </value>
                <value>
                    <fullName>Data Program</fullName>
                </value>
                <value>
                    <fullName>Master Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Authorized Training Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>A-SI Partner Program Agreement</fullName>
                </value>
                <value>
                    <fullName>Tech Program</fullName>
                </value>
                <value>
                    <fullName>Technical Advisory Services</fullName>
                </value>
                <value>
                    <fullName>One Home for Sites</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship SOW</fullName>
                    <isActive>false</isActive>
                    <label>Event Sponsorship SOW</label>
                </value>
                <value>
                    <fullName>Training SOW</fullName>
                    <isActive>false</isActive>
                    <label>Training SOW</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Contract_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Parent Contract Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Leader_Region__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012 - The region of the project leader, who is an internal contact.  This field is mapped from opportunities.</description>
        <label>Project Leader Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>USA/Canada</fullName>
                </value>
                <value>
                    <fullName>Europe/Middle East/Africa EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOW_status__c</fullName>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Invoice me</fullName>
                    <isActive>false</isActive>
                    <label>Invoice me</label>
                </value>
                <value>
                    <fullName>Invoice me – with PO</fullName>
                    <isActive>false</isActive>
                    <label>Invoice me – with PO</label>
                </value>
                <value>
                    <fullName>Online Payment</fullName>
                    <isActive>false</isActive>
                    <label>Online Payment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Notification_Date__c</fullName>
        <label>Second Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Third_Notification_Date__c</fullName>
        <label>Third Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Contract_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Ultimate Parent Contract Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>PRM_Contract</fullName>
        <active>true</active>
        <label>PRM Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_CNT_PEP_ContractRenewalNotification.cls
@isTest
public class TST_CNT_PEP_ContractRenewalNotification 
{
    @testSetup
    public static void setup(){     
        Id prmProfileId = [select id from profile where name =: CON_PEP.S_P_PEP_COMMUNITY ].id;
        Account ac = new Account(name ='Acme', CustomerSegment__c = 'GOVERNMENT', Sub_Industry__c = 'STATE') ;
        ac.AccountCountry__c = 'BM' ;
        insert ac;

        Contact con = new Contact(FirstName = 'TestFirstName', LastName ='testCon',AccountId = ac.Id,Email='partneruser@iqvia.partner.com');
        con.Partner_Type__c = 'Integrator Partner; Data Partner';
        con.PRM_Contract_Renewal_Notification__c = True;
        insert con;
        
        User partnerUser = new User(alias = 'test123', email='partneruser@iqvia.partner.com',
                                    emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                                    localesidkey='en_US', profileid = prmProfileId, country='United States',IsActive =true,
                                    ContactId = con.Id,PortalRole='Manager',
                                    timezonesidkey='America/Los_Angeles', username='xyz123490@iqviaTestPartner.com');
        insert partnerUser;
        
        
        User us=[SELECT Contact.AccountId from user WHERE Id= : partnerUser.Id];
        
        Product2 prod = TST_PEP_TestDataFactory.createProduct('Oce Sales');
        prod.Pillar__c = 'Information Offering; Technology Solutions; R&D';
        insert prod;
        
        Agency_Program__c agencyprog = TST_PEP_TestDataFactory.createAgencyProgram(prod);
        agencyprog.Status__c = 'Inactive';
        insert agencyprog;
        
        Contract testContract1 = new Contract(Project_Leader_Region__c='Asia Pacific', 
                                              RecordTypeId=Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('PRM_Contract').getRecordTypeId(),
                                              AccountId=us.Contact.AccountId,
                                              Status='Assigned - Not Started',
                                              Date_Tracking_started__c=Date.newInstance(2024, 12, 9),
                                              Date_executed_signed_contract_received__c = Date.newInstance(2024, 12, 9),
                                              First_Notification_Date__c=Date.today(),
                                              Notification_Counter__c=1,
                                              Agency_Program__c=agencyprog.Id,
                                              Parent_Contract_Number__c = 1234,
                                              Ultimate_Parent_Contract_Number__c = 5678,
                                              SOW_status__c='Signed',
                                              PRM_Contract_type__c='Agency Program SOW',
                                              Non_Standard_Contract__c=false);
        insert testContract1;
        
        Contract testContract2 = new Contract(Project_Leader_Region__c='Asia Pacific', 
                                              RecordTypeId=Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('PRM_Contract').getRecordTypeId(),
                                              AccountId=us.Contact.AccountId,
                                              Status='Assigned - Not Started',
                                              Date_Tracking_started__c=Date.newInstance(2024, 12, 9),
                                              Date_executed_signed_contract_received__c = Date.newInstance(2024, 12, 9),
                                              Second_Notification_Date__c=Date.today(),
                                              Notification_Counter__c=2,
                                              Agency_Program__c=agencyprog.Id,
                                              Parent_Contract_Number__c = 1234,
                                              Ultimate_Parent_Contract_Number__c = 5678,
                                              SOW_status__c='Signed',
                                              PRM_Contract_type__c='Agency Program SOW',
                                              Non_Standard_Contract__c=false);
        insert testContract2;
        User adminUser = TST_PEP_TestDataFactory.createAdminUser('admin','adminPartner@iqvia.com');
        
        System.runAs(adminUser){
            EmailTemplate testEmailTemplate1 = TST_PEP_TestDataFactory.createEmailTemplate('Contract Reminder_First', 'Test_Template1', 'custom');
            testEmailTemplate1.Body = 'test1';
            testEmailTemplate1.FolderId = UserInfo.getUserId();
            insert testEmailTemplate1;
            EmailTemplate testEmailTemplate2 = TST_PEP_TestDataFactory.createEmailTemplate('Contract Reminder_Second', 'Test_Template2', 'custom');
            testEmailTemplate2.Body = 'test2';
            testEmailTemplate2.FolderId = UserInfo.getUserId();
            insert testEmailTemplate2;
            EmailTemplate testEmailTemplate3 = TST_PEP_TestDataFactory.createEmailTemplate('Contract Reminder_Third', 'Test_Template3', 'custom');
            testEmailTemplate3.Body = 'test3';
            testEmailTemplate3.FolderId = UserInfo.getUserId();
            insert testEmailTemplate3;
            EmailTemplate testEmailTemplate4 = TST_PEP_TestDataFactory.createEmailTemplate('Contract Reminder_Expired', 'Test_Template4', 'custom');
            testEmailTemplate4.Body = 'test4';
            testEmailTemplate4.FolderId = UserInfo.getUserId();
            insert testEmailTemplate4;
        }
     /*   Contract testContract3 = new Contract(Project_Leader_Region__c='Asia Pacific', 
                                              RecordTypeId=Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('PRM_Contract').getRecordTypeId(),
                                              AccountId=ac.Id,
                                              Status='Assigned - Not Started',
                                              Date_Tracking_started__c=Date.newInstance(2019, 12, 9),
                                              Date_executed_signed_contract_received__c = Date.newInstance(2019, 12, 9),
                                              Third_Notification_Date__c=Date.today(),
                                              Notification_Counter__c=3,
                                              Agency_Program__c=agencyprog.Id,
                                              Parent_Contract_Number__c = 1234,
                                              Ultimate_Parent_Contract_Number__c = 5678,
                                              PRM_Contract_type__c='Agency Program SOW');
        insert testContract3;*/
        
        /*Contract testContract4 = new Contract(Project_Leader_Region__c='Asia Pacific', 
                                              RecordTypeId=Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('PRM_Contract').getRecordTypeId(),
                                              AccountId=ac.Id,
                                              Status='Assigned - Not Started',
                                              Date_Tracking_started__c=Date.newInstance(2019, 12, 9),
                                              Date_executed_signed_contract_received__c = Date.newInstance(2019, 12, 9),
                                              EndDate=Date.newInstance(2018, 2, 2),
                                              Notification_Counter__c=3,
                                              Agency_Program__c=agencyprog.Id,
                                              Parent_Contract_Number__c = 1234,
                                              Ultimate_Parent_Contract_Number__c = 5678,
                                              PRM_Contract_type__c='Agency Program SOW');
        insert testContract4;
        
        Contract testContract5 = new Contract(Project_Leader_Region__c='Asia Pacific', 
                                              RecordTypeId=Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('PRM_Contract').getRecordTypeId(),
                                              AccountId=ac.Id,
                                              Status='Assigned - Not Started',
                                              Date_Tracking_started__c=Date.newInstance(2019, 12, 9),
                                              Date_executed_signed_contract_received__c = Date.newInstance(2019, 12, 9),
                                              EndDate=Date.newInstance(2018, 2, 2),
                                              Notification_Counter__c=4,
                                              Agency_Program__c=agencyprog.Id,
                                              Parent_Contract_Number__c = 1234,
                                              Ultimate_Parent_Contract_Number__c = 5678,
                                              PRM_Contract_type__c='Agency Program SOW');
        insert testContract5;*/
    }
    
    @isTest
    public static void testcontractRenewalNotification()
    { 
        Test.startTest();
        SchedulableContext sc = null;
        CNT_PEP_ContractRenewalNotification crn = new CNT_PEP_ContractRenewalNotification(); 
        crn.execute(sc);
        Test.stopTest();  
    }
}