src/objects/Account_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Competitors</relationshipLabel>
        <relationshipName>R00N20000001kz6tEAA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <description>ESPSFDCQI-11851</description>
        <formula>TODAY() &lt;= Contract_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Competitor_Category__c</fullName>
        <description>ESPSFDCQI-11851</description>
        <inlineHelpText>If customer is using their own solution, select “In House”; If there is no current solution, select “None”.</inlineHelpText>
        <label>Competitor Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>External Competitor</fullName>
                </value>
                <value>
                    <fullName>IQVIA</fullName>
                </value>
                <value>
                    <fullName>In House</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor</label>
        <referenceTo>Competitor__c</referenceTo>
        <relationshipLabel>Account Competitors</relationshipLabel>
        <relationshipName>R00N20000001kz5CEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <description>ESPSFDCQI-11851</description>
        <inlineHelpText>If you are not certain on the Contract End Date, please input Dec 31st, 2050.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <description>ESPSFDCQI-11851</description>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pillars__c</fullName>
        <description>ESPSFDCQI-11851</description>
        <label>Pillars</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CLINTECH</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER ENGAGEMENT</fullName>
                </value>
                <value>
                    <fullName>IM/PM</fullName>
                </value>
                <value>
                    <fullName>PATIENT</fullName>
                </value>
                <value>
                    <fullName>SRQ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Offerings__c</fullName>
        <description>ESPSFDCQI-11851</description>
        <label>Sub-Offerings</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Pillars__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Align/Roster Manager</fullName>
                </value>
                <value>
                    <fullName>Cenduit</fullName>
                </value>
                <value>
                    <fullName>Clinical Data Analytics Suit (CDAS)</fullName>
                </value>
                <value>
                    <fullName>CMS/DAM</fullName>
                </value>
                <value>
                    <fullName>Consent</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Content Management</fullName>
                </value>
                <value>
                    <fullName>Cost Benchmark</fullName>
                </value>
                <value>
                    <fullName>CRA Central</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>CTMS</fullName>
                </value>
                <value>
                    <fullName>Data Query System (DQS)</fullName>
                </value>
                <value>
                    <fullName>eConsent</fullName>
                </value>
                <value>
                    <fullName>Enterprise Integration Architecture</fullName>
                </value>
                <value>
                    <fullName>Enterprise Service BusIntegration Archi</fullName>
                </value>
                <value>
                    <fullName>eTMF</fullName>
                </value>
                <value>
                    <fullName>HCP/O Engagement</fullName>
                </value>
                <value>
                    <fullName>HCP Engagement</fullName>
                </value>
                <value>
                    <fullName>Hosting &amp; Managed Service (H&amp;MS)</fullName>
                </value>
                <value>
                    <fullName>IM Datalake, Datawarehouse (DWH)</fullName>
                </value>
                <value>
                    <fullName>Incentive</fullName>
                </value>
                <value>
                    <fullName>Investigator Site Portal</fullName>
                </value>
                <value>
                    <fullName>IQVIA Vigilance Platform (IVP)</fullName>
                </value>
                <value>
                    <fullName>Marketing Automation</fullName>
                </value>
                <value>
                    <fullName>MDM</fullName>
                </value>
                <value>
                    <fullName>NBA</fullName>
                </value>
                <value>
                    <fullName>Other Vendor(s)</fullName>
                </value>
                <value>
                    <fullName>Patient Centered Solutions (PCS)</fullName>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>PM (KPI)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Competitor</label>
    <nameField>
        <displayFormat>ACN{00000}</displayFormat>
        <label>Account Competitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Competitor__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-319 - Allows users to select from a large list of Competitors.</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CNT_CRM_AllAccountCompetitors.cls
public class CNT_CRM_AllAccountCompetitors {
    
    @AuraEnabled(cacheable=true)
    public static List<Account_Competitor__c> getAccountCompetitors(Id recordId){
        String condition = '(Account__r.ParentId =  \'' + recordId + '\' OR Account__r.Parent.ParentId =  \'' + recordId + '\' ) AND Account__r.RecordTypeId = \'' +CON_CRM.MDM_VALIDATED_ACCOUNT_RECORD_TYPE_ID +'\'';
        Set <String> fieldSet = new Set<String>{'Id', 'Name', 'Account__c', 'Account__r.Name', 'Competitor_Category__c', 'Competitor__c', 'Competitor__r.Name', 'Sub_Offerings__c', 'Pillars__c', 'Contract_Start_Date__c', 'Contract_End_Date__c', 'Active__c'};
            return new SLT_AccountCompetitor().getAccountCompetitors(fieldset, condition);
    }
}