src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Case_Type__c</fullName>
        <label>Portal Case Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Information Offering</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Technology Solutions</fullName>
                </value>
                <value>
                    <fullName>DATA</fullName>
                    <isActive>false</isActive>
                    <label>DATA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_QI_Data_Portal_Queue_User_details__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Data Portal Queue User details</relationshipLabel>
        <relationshipName>Data_Portal_Queue_User_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Current_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Current Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseRecordType__c</fullName>
        <label>Case Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ActivityPlan</fullName>
                </value>
                <value>
                    <fullName>DATACase</fullName>
                </value>
                <value>
                    <fullName>TechnologyCase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queue_User_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue User Relationship</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Queue_User_Relationship__c.Type__c</field>
                <operation>equals</operation>
                <value>Queue</value>
            </filterItems>
            <infoMessage>Please Select the Queue user Relationship type as queue</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Queue_User_Relationship__c</referenceTo>
        <relationshipLabel>Data Portal Queue User details</relationshipLabel>
        <relationshipName>Data_Portal_Queue_User_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>CSM-1116 Product Segregation to show only selected product to CSH User in Customer Service Hub. differentiate the CSH queue assignment and Product restriction functionality in CSH</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queue Assignment</fullName>
                    <default>true</default>
                    <label>Queue Assignment</label>
                </value>
                <value>
                    <fullName>Product Level Restriction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Portal Queue User details</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>CSM QI Data Portal  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Portal Queue User details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM - ACN - S-0007 - User Lookup</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TST_CNT_CSM_CommunityPage.cls
@isTest
public class TST_CNT_CSM_CommunityPage {
    /**
    * This method used to set up testdata
    */
    @testSetup
    static void dataSetup() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        String profilId2 = [select id from Profile where Name='System Administrator'].Id;
        User accOwner = New User(Alias = 'su',UserRoleId= portalRole.Id, ProfileId = profilId2, Email = 'john2@iqvia.com',IsActive =true,Username ='john2@iqvia.com', LastName= 'testLastName', CommunityNickname ='testSuNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', employeeNumber= '080808081');
        accOwner.Change_Request_Description__c = 'Change Request Descritpion';
        insert accOwner;
        System.runAs (accOwner) {
            Account account = UTL_TestData.createAccount();
            account.ownerId=accOwner.Id;
            insert account;
            Queue_User_Relationship__c qurPortal = new Queue_User_Relationship__c(Name = 'Q1',User__c = UserInfo.getUserId(),Type__c = 'Queue');
            insert qurPortal;
            CSM_QI_Data_Portal_Queue_User_details__c dT = new CSM_QI_Data_Portal_Queue_User_details__c();
            dT.Queue_User_Relationship__c = qurPortal.Id;
            dT.Account__c = account.Id;
            dT.All_Current_Users__c = true;
            dT.CaseRecordType__c = 'TechnologyCase';
            dT.Type__c ='Queue Assignment';
            dT.Order__c = 1;
            insert dT;
            CSM_QI_Data_Portal_Queue_User_details__c dd = new CSM_QI_Data_Portal_Queue_User_details__c();
            dd.Queue_User_Relationship__c = qurPortal.Id;
            dd.Account__c = account.Id;
            dd.All_Current_Users__c = true;
            dd.CaseRecordType__c = 'DATACase';
            dd.Type__c ='Queue Assignment';
            dd.Order__c = 1;
            insert dd;
        }
    }

    /**
    * This method used to get List<Contact> for current user
    */
    @IsTest
    static void testGetUserContact() {
        Account acc = [SELECT id FROM Account WHERE Name = 'TestAccount'];
        Contact contact = new Contact(
            Firstname='Brian',
            Lastname='Dent',
            Phone='(619)852-4569',
            Department='Mission Control',
            Title='Mission Specialist - Neptune',
            Email='john@acme.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            AccountId = acc.Id);
        insert contact;
        String profilId = [select id from Profile where Name='CSM Customer Community Plus Login User'].Id;
        User user = New User(Alias = 'com', Email = 'john@acme.com',IsActive =true, ContactId = contact.Id, ProfileId = profilId,Username =' john@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US',employeeNumber= '080808082');
        insert user;
        Test.startTest();
        List<Contact> contacts = new List<Contact>();
        system.runAs(user){
            contacts =  CNT_CSM_CommunityPage.getUserContact();
        }
        Test.stopTest();
        Integer expected = 1;
        Integer actual = contacts.size();
        System.assertEquals(expected, actual);
    }

    @IsTest
    static void testGetUser() {
        Account acc = [SELECT id FROM Account WHERE Name = 'TestAccount'];
        Contact contact = new Contact(
            Firstname='Brian',
            Lastname='Dent',
            Phone='(619)852-4569',
            Department='Mission Control',
            Title='Mission Specialist - Neptune',
            Email='john@acme.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            AccountId = acc.Id);
        insert contact;
        String profilId = [select id from Profile where Name='CSM Customer Community Plus Login User'].Id;
        User user = New User(Alias = 'com', Email = 'john@acme.com',IsActive =true, ContactId = contact.Id, ProfileId = profilId,Username =' john@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', employeeNumber= '080808083');
        insert user;
        Test.startTest();
        User userContact = new User();
        system.runAs(user){
            userContact =  CNT_CSM_CommunityPage.getUser()[0];
        }
        Test.stopTest();
    }
    
    @IsTest
    private static void testGetStandardUser() {
        Test.startTest();
            User loggedInUser =  CNT_CSM_CommunityPage.getUser()[0];
        Test.stopTest();
        
        System.assertEquals(true, loggedInUser != null, 'Should get User info');
    }
}