src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KBA_Visibility_Restriction__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM-1644: used to limit access only to KBA in relation with the customer.</description>
        <label>KBA Visibility Restriction</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KB_Location__c</fullName>
        <inlineHelpText>Enter KB Location separated by semicolon(;)</inlineHelpText>
        <label>KB Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>A location indicator.  For example, QRTP = Quintiles Research Triangle Park.</description>
        <inlineHelpText>A location indicator.  For example, QRTP = Quintiles Research Triangle Park.</inlineHelpText>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IQVIA_Location</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_Case_Details_Global_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSM Case Details Global Setting</label>
</CustomObject>

src/objects/CSM_QI_KB_Location__c.object
<CustomObject>
    <description>CSM-1805:TECH - EUS - KB Location Visibility Restriction</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSM KB Locations</relationshipLabel>
        <relationshipName>CSM_KB_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSM KB Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSM KB Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IQVIACopilot_ChatGPT__c.object
<CustomObject>
    <description>CSM-2994: ALL - GenAI - Case Summerization</description>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Generate Draft Article</description>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>IQVIA Copilot ChatGPT</relationshipLabel>
        <relationshipName>IQVIA_Copilot_ChatGPT</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IQVIA Copilot ChatGPT</label>
    <nameField>
        <displayFormat>GPT-{0000000000}</displayFormat>
        <label>IQVIA GPT Co Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IQVIA Copilot ChatGPT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Answer__c</fullName>
        <description>CSM-ACN-S-0046 - Rich Text Field for Answer.</description>
        <label>Answer</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>CSM-ACN-S-0046 - Rich textfield for Content</description>
        <label>Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>L1Answer__c</fullName>
        <description>CSM-ACN-S-0046 - Rich textfield for L1 Answer</description>
        <label>L1 Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>L1Content__c</fullName>
        <description>CSM-ACN-S-0046 - Rich Textfield for L1 Content</description>
        <label>L1 Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>L2L3Answer__c</fullName>
        <description>CSM-ACN-S-0046 - Rich TextField for L2/L3 Answer</description>
        <label>L2/L3 Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>L2L3Content__c</fullName>
        <description>CSM-ACN-S-0046 - Rich Textfield for L2/L3 Content</description>
        <label>L2/L3 Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <description>CSM - ACN - S-0046 - Product Name</description>
        <label>ProductName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>CSM-ACN-S-0046 - Text field for Question.</description>
        <label>Question</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <description>CSM - ACN - S-0046 - Sub-Type 1</description>
        <label>Sub-Type 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <description>CSM - ACN - S-0046 - Sub-Type 2</description>
        <label>Sub-Type 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType3__c</fullName>
        <description>CSM - ACN - S-0046 - Sub-Type 3</description>
        <label>Sub-Type 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/objects/Knowledge_Account_RelationShip__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>CSM_QI_KB_Location__c.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CSM_QI_KB_Location__c</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>Knowledge__r.ProductName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <formula>Knowledge__r.SubType1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-Type 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <formula>Knowledge__r.SubType2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-Type 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType3__c</fullName>
        <formula>Knowledge__r.SubType3__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-Type 3</label>
        <type>Text</type>
    </fields>
    <label>Knowledge Account RelationShip</label>
    <nameField>
        <displayFormat>KAR-{0000000}</displayFormat>
        <label>Knowledge Account RelationShip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Account RelationShips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/IQVIA_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEDBA1</fullName>
    </customValue>
    <customValue>
        <fullName>AEDBA2</fullName>
    </customValue>
    <customValue>
        <fullName>AEDBA4</fullName>
    </customValue>
    <customValue>
        <fullName>ALL2</fullName>
    </customValue>
    <customValue>
        <fullName>ARBUE1</fullName>
    </customValue>
    <customValue>
        <fullName>ARBUE2</fullName>
    </customValue>
    <customValue>
        <fullName>ARBUEL</fullName>
    </customValue>
    <customValue>
        <fullName>ATVIE2</fullName>
    </customValue>
    <customValue>
        <fullName>AUMEL1</fullName>
    </customValue>
    <customValue>
        <fullName>AUSLD2</fullName>
    </customValue>
    <customValue>
        <fullName>BASAR2</fullName>
    </customValue>
    <customValue>
        <fullName>BDDHA1</fullName>
    </customValue>
    <customValue>
        <fullName>BDDHA2</fullName>
    </customValue>
    <customValue>
        <fullName>BEANT1</fullName>
    </customValue>
    <customValue>
        <fullName>BEANT2</fullName>
    </customValue>
    <customValue>
        <fullName>BEBES1</fullName>
    </customValue>
    <customValue>
        <fullName>BEWIJ1</fullName>
    </customValue>
    <customValue>
        <fullName>BEZVM1</fullName>
    </customValue>
    <customValue>
        <fullName>BGSOF2</fullName>
    </customValue>
    <customValue>
        <fullName>BOLAP2</fullName>
    </customValue>
    <customValue>
        <fullName>BRSAO1</fullName>
    </customValue>
    <customValue>
        <fullName>BRSAO2</fullName>
    </customValue>
    <customValue>
        <fullName>BRY1</fullName>
    </customValue>
    <customValue>
        <fullName>CAHAL1</fullName>
    </customValue>
    <customValue>
        <fullName>CAKAN1</fullName>
    </customValue>
    <customValue>
        <fullName>CAKRKR</fullName>
    </customValue>
    <customValue>
        <fullName>CAMIS1</fullName>
    </customValue>
    <customValue>
        <fullName>CAOTT1</fullName>
    </customValue>
    <customValue>
        <fullName>CATOR1</fullName>
    </customValue>
    <customValue>
        <fullName>CATOR2</fullName>
    </customValue>
    <description>A location indicator.  For example, QRTP = Quintiles Research Triangle Park</description>
    <masterLabel>IQVIA Location</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet> 

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/CNT_CSM_AttachArticle.cls
public class CNT_CSM_AttachArticle {

    @AuraEnabled
    public static List<SObject> searchArticles(String searchText, String caseId, Integer rowLimit, Integer rowOffset) {
        List<Case> cases = new List<Case>();
        List<List<SObject> > results = new List<List<SObject> >();
        List<SObject> k = new List<SObject>();
        String pillar;
        String product = '';
        String prdCond = '';
        cases = new SLT_Case().selectByCaseIdList(new Set<Id> { caseId }, new Set<String> {'Subject', 'RecordTypeName__c', 'ProductName__c', 'LOS__c', 'AccountId','Account.KBA_Visibility_Restriction__c', 'Contact.KB_Location__c'});
        if(cases.size() > 0) {
            Set<Id> kIds = new Set<Id>();
            for(CaseArticle ca: [SELECT KnowledgeArticleVersionId FROM CaseArticle WHERE CaseId = :caseId]) {
                kIds.add(ca.KnowledgeArticleVersionId);
            }
            if(searchText == '') {
                searchText = cases[0].Subject;
            }
            String KB_Location = cases[0].Contact.KB_Location__c;
            String location_condition = '';
            if (KB_Location != null) {
                KB_Location = '\'' + KB_Location.replace(';','\',\'') +'\'';
                location_condition = ' OR Location__r.Location__c  in ('+ KB_Location +')';
            }
            if(cases[0].RecordTypeName__c == CON_CSM.S_TECHNOLOGY_R_T) {
                pillar = CON_CSM.S_TECHNOLOGY_SOLUTIONS;
                if (cases[0].ProductName__c != null) {
                    product = cases[0].ProductName__c;
                }
            } else if(cases[0].RecordTypeName__c == CON_CSM.S_DATACASE) {
                pillar = CON_CSM.S_INFORMATION_OFFERING;
                if (cases[0].ProductName__c != null) {
                    product = cases[0].ProductName__c;
                }
            } else if(cases[0].RecordTypeName__c == CON_CSM.S_RDCASE || cases[0].RecordTypeName__c == CON_CSM.S_R_D_V_T || cases[0].RecordTypeName__c == CON_CSM.S_ACTIVITY_R_T ) {
                pillar = CON_CSM.S_R_D;
                if (cases[0].LOS__c != null) {
                    product = cases[0].LOS__c;
                }
            }
            if (product != '') {
                prdCond = ' AND ProductName__c = \'' + product +'\'';
            }
            if(cases[0].AccountId != null && cases[0].Account.KBA_Visibility_Restriction__c) {
                Set<Id> knowledgeIds = new Set<Id>();
                for(Knowledge_Account_RelationShip__c kbAccount: Database.query('SELECT Id, Knowledge__c FROM Knowledge_Account_RelationShip__c WHERE Account__c =\'' + cases[0].AccountId + '\' AND (Location__c = \'\' ' + location_condition + ' )')) {
                    knowledgeIds.add(kbAccount.Knowledge__c);
                }
                if(!knowledgeIds.isEmpty()) {
                    String q = 'FIND :searchText IN ALL FIELDS RETURNING Knowledge__kav(Id, RecordTypeId, ArticleNumber, Content__c, L1Content__c, L2L3Content__c, Question__c, Answer__c, L1Answer__c, L2L3Answer__c, Title, knowledgeArticleId, ProductName__c, SubType1__c, SubType2__c, SubType3__c, IsVisibleInCsp, LastPublishedDate WHERE PublishStatus =\'Online\' AND Language = \'en_US\' AND Pillar__c = :pillar AND Id IN :knowledgeIds AND Id NOT IN :kids' + prdCond +' LIMIT '+ rowLimit +' OFFSET ' + rowOffset +' )';
                    results =  search.query(q);
                }
            }
            else {
                if(cases[0].AccountId != null) {
                    String q1 = 'FIND :searchText IN ALL FIELDS RETURNING Knowledge__kav(Id, RecordTypeId, ArticleNumber, Content__c, L1Content__c, L2L3Content__c, Question__c, Answer__c, L1Answer__c, L2L3Answer__c, Title, knowledgeArticleId, ProductName__c, SubType1__c, SubType2__c, SubType3__c, IsVisibleInCsp, LastPublishedDate WHERE PublishStatus =\'Online\' AND Language = \'en_US\' AND Pillar__c = :pillar and Id not in :kids' + prdCond + ' AND Id in (select Knowledge__c from Knowledge_Account_RelationShip__c where Account__c =\''+ cases[0].AccountId +'\' AND (Location__c = \'\' ' + location_condition + ' )) LIMIT '+ rowLimit +' OFFSET ' + rowOffset +' )';
                    List<List<SObject> > results1 =  search.query(q1);
                    results.addAll(results1);
                }
                String q2 = 'FIND :searchText IN ALL FIELDS RETURNING Knowledge__kav(Id, RecordTypeId, ArticleNumber, Content__c, L1Content__c, L2L3Content__c, Question__c, Answer__c, L1Answer__c, L2L3Answer__c, Title, knowledgeArticleId, ProductName__c, SubType1__c, SubType2__c, SubType3__c, IsVisibleInCsp, LastPublishedDate WHERE PublishStatus =\'Online\' AND Language = \'en_US\' AND Pillar__c = :pillar and Id not in :kids' + prdCond + ' AND Id NOT in (select Knowledge__c from Knowledge_Account_RelationShip__c) LIMIT '+ rowLimit +' OFFSET ' + rowOffset +' )';
                List<List<SObject> > results2 =  search.query(q2);
                results.addAll(results2);
            }
        }

        for (List<SObject> sobjs : results){
            k.addAll(sobjs);
        }
        return k;
    }

    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getCaseArticle( String caseId) {
        Set<Id> kIds = new Set<Id>();
        List<Knowledge__kav> results = new List<Knowledge__kav>();
        for(CaseArticle ca: [SELECT KnowledgeArticleVersionId FROM CaseArticle WHERE CaseId = :caseId]) {
            kIds.add(ca.KnowledgeArticleVersionId);
        }
        if(kIds != null && !kIds.isEmpty()) {
            results = new SLT_Knowledge().selectById(kIds);
        }
        return results;
    }

    @AuraEnabled
    public static void insertCaseArticle( String caseId, String knowledgeArticleId) {
        CaseArticle ca  = new CaseArticle (caseId = caseId, KnowledgeArticleId = knowledgeArticleId );
        insert ca;
    }

    @AuraEnabled
    public static void deleteCaseArticle(String caseId, String knowledgeArticleId) {
        try {
            CaseArticle ca = [SELECT Id, KnowledgeArticleVersionId FROM CaseArticle WHERE CaseId = :caseId AND KnowledgeArticleId = :knowledgeArticleId LIMIT 1];
            KnowledgeArticleVersion article = [SELECT Title FROM KnowledgeArticleVersion WHERE Id = :ca.KnowledgeArticleVersionId LIMIT 1];
            String orgDomain = URL.getOrgDomainUrl().toExternalForm();
            String articleUrl = orgDomain + '/lightning/r/Knowledge__kav/' + ca.KnowledgeArticleVersionId + '/view';
            delete ca;
            FeedItem feedItem = new FeedItem();
            feedItem.ParentId = caseId;
            feedItem.Body = 'Article <s><a href="' + articleUrl + '">' + article.Title.escapeHtml4() + '</a></s> has been detached.';
            feedItem.Type = 'ContentPost';
            feedItem.IsRichText = true;
            insert feedItem;
        } catch (Exception e) {
            throw new AuraHandledException('Error deleting CaseArticle: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static List<IQVIACopilot_ChatGPT__c> draftEmailAction(String caseId, String knowledgeArticleId) {
        return CNT_CSM_SNOWChatGPT.askCaseAssistance(caseId, 'Draft Article Email', 'English','en_US',knowledgeArticleId);
    }
    
    @AuraEnabled(cacheable=true)
    public static boolean getDataCustomSetting() {
        CSM_Case_Details_Global_Setting__c emailKb = CSM_Case_Details_Global_Setting__c.getValues('IQVIAKBCopilotDraftEmail');
        Boolean isGenAI = FeatureManagement.checkPermission('CSM_IQVIA_Assistant_Access');
        boolean isCheck = false;
        if((Test.isRunningTest() || isGenAI) && emailKb != null && emailKb.Origin__c != null){
            String userId = UserInfo.getUserId();
            String pg = emailKb.Origin__c;
             List<GroupMember> groupList = Database.query('select Id, GroupId, UserOrGroupId, SystemModstamp from GroupMember where GroupId = :pg and UserOrGroupId =:userId');
            if(groupList != null && groupList.size() > 0){
                isCheck = true;
            }
        }else if(isGenAI){
           isCheck = true;
        }
        return isCheck;
    }
    
}