src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <description>CSM - ACN - S0036 - Account Country</description>
        <label>Account Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>PEP-ACN-AM_CM-11 Partner type</description>
        <label>Partner Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integrator Partner</fullName>
                </value>
                <value>
                    <fullName>Data Partner</fullName>
                </value>
                <value>
                    <fullName>Tech Partner</fullName>
                </value>
                <value>
                    <fullName>Training Partner</fullName>
                </value>
                <value>
                    <fullName>CLM Agency</fullName>
                </value>
                <value>
                    <fullName>One Home for Sites</fullName>
                </value>
                <value>
                    <fullName>AMESA - Integrator Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1455 - Field value dependent on selected Industry</description>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Certification__c.object
<CustomObject>
    <description>Object for Partner Certification on Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account on which the certification is applicable.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Certifications</relationshipLabel>
        <relationshipName>Partner_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Badge_Variation__c</fullName>
        <description>To store the Badge Variation of a Certification.</description>
        <label>Badge Variation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B1</fullName>
                </value>
                <value>
                    <fullName>B2</fullName>
                </value>
                <value>
                    <fullName>B3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <label>Certification Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Partner_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OCE Personal - Integration Partner</fullName>
                </value>
                <value>
                    <fullName>OCE Digital - Integration Partner</fullName>
                </value>
                <value>
                    <fullName>ePromo - Integration Partner</fullName>
                </value>
                <value>
                    <fullName>Remote Detailing - Marketing Agency</fullName>
                </value>
                <value>
                    <fullName>Mobile Inteligence CRM - Marketing Agency</fullName>
                </value>
                <value>
                    <fullName>Personal Detailing - Marketing Agency</fullName>
                </value>
                <value>
                    <fullName>OCE Personal - Marketing Agency</fullName>
                </value>
                <value>
                    <fullName>OCE Digital - Marketing Agency</fullName>
                </value>
                <value>
                    <fullName>ePromo - Marketing Agency</fullName>
                </value>
                <value>
                    <fullName>Logo Use</fullName>
                </value>
                <value>
                    <fullName>Marketing Agency Partner</fullName>
                </value>
                <value>
                    <fullName>System Integrator Partner</fullName>
                </value>
                <value>
                    <fullName>Technology Partner</fullName>
                </value>
                <value>
                    <fullName>OCE Field Email - Marketing Agency</fullName>
                </value>
                <value>
                    <fullName>OCE Survey-Marketing Agency</fullName>
                </value>              
                <value>
                    <fullName>Authorized Training Partner</fullName>
                </value>
                <value>
                    <fullName>ONEKEY Certified Partner</fullName>
                </value>
                <value>
                    <fullName>One Home for Sites Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certification_Start_Date__c</fullName>
        <description>Start Date of Certification</description>
        <label>Certification Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>To check the status of Badges</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JPEG__c</fullName>
        <description>To stor JPEG file URL.</description>
        <label>JPEG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PNG__c</fullName>
        <description>To store PNG file URL.</description>
        <label>PNG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>Partner type picklist</description>
        <label>Partner Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integration Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing Agency</fullName>
                </value>
                <value>
                    <fullName>All Partners</fullName>
                </value>
                <value>
                    <fullName>Technology Partner</fullName>
                </value>
                <value>
                    <fullName>Training Partner</fullName>
                </value>
                <value>
                    <fullName>Data Partner</fullName>
                </value>
                <value>
                    <fullName>One Home for Sites</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SVG__c</fullName>
        <description>To stoer SVG file URL.</description>
        <label>SVG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Partner Certification</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Partner Certification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Certifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_CNT_PEP_AccountCertifications.cls
/*
* Version       : 1.0
* Description   : Test class for CNT_PEP_AccountCertifications
*/
@isTest
public class TST_CNT_PEP_AccountCertifications {
    @testSetup
    static void dataSetup() { 
        Id prmProfileId = [select id from profile where name =: CON_PEP.S_P_PEP_COMMUNITY ].id;
        
        Account ac = new Account(Name = 'Acme',AccountCountry__c='BM', CustomerSegment__c = 'GOVERNMENT', Sub_Industry__c = 'STATE');
        insert ac; 
        
        Contact con = new Contact(FirstName = 'TestFirstName', LastName ='testCon',AccountId = ac.Id,Email='partneruser@iqvia.partner.com');
        con.Partner_Type__c = 'Integrator Partner; Data Partner';
        insert con; 
        
        User partnerUser = new User(alias = 'test123', email='partneruser@iqvia.partner.com',
                                    emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                                    localesidkey='en_US', profileid = prmProfileId, country='United States',IsActive =true,
                                    ContactId = con.Id,
                                    timezonesidkey='America/Los_Angeles', username='xyz123490@iqviaTestPartner.com');
        insert partnerUser;
        System.runAs(partnerUser){
            
            Id certificationRecordTypeId = Schema.SObjectType.Partner_Certification__c.getRecordTypeInfosByName().get('Admin Record').getRecordTypeId();
            Partner_Certification__c pc = new Partner_Certification__c();
            pc.RecordTypeId=certificationRecordTypeId;
            pc.Partner_Type__c='Integration Partner';
            pc.Certification_Name__c='ePromo - Integration Partner';
            pc.Badge_Variation__c='B1';
            pc.JPEG__c='Test Link1';
            pc.PNG__c='Test Link2';
            pc.SVG__c='Test Link3';
            pc.Is_Active__c=True;
            
            insert pc;
            
            Id certificationRecordTypeIdPSO = Schema.SObjectType.Partner_Certification__c.getRecordTypeInfosByName().get('Partner Certification Record').getRecordTypeId();
            Partner_Certification__c pcPSO = new Partner_Certification__c();
            pc.RecordTypeId=certificationRecordTypeIdPSO;
            pcPSO.Partner_Type__c='Integration Partner';
            pcPSO.Certification_Name__c='ePromo - Integration Partner';
            User us=[SELECT Contact.AccountId from user WHERE Id= : partnerUser.Id];
            pcPSO.Account__c=us.Contact.AccountId;
            pcPSO.Certification_Start_Date__c=Date.today();
            insert pcPSO;   
        }
    }
    
    @isTest
    public static void testGetAccountCertifications(){
        User partnerUser = [SELECT id FROM User WHERE email='partneruser@iqvia.partner.com'];
        System.runAs(partnerUser){
            Test.startTest();
            List<Partner_Certification__c> partnerCertifications = CNT_PEP_AccountCertifications.getAccountCertifications();
            Test.stopTest();
            
            System.assertEquals(1, partnerCertifications.size());
        }
    }
    
    @isTest
    public static void testGetBadgeVariations(){
        List<Partner_Certification__c> certificationName=[SELECT Certification_Name__c FROM Partner_Certification__c
                                                          WHERE Certification_Name__c='ePromo - Integration Partner'];
        
        Test.startTest();
        List<Partner_Certification__c> partnerCertifications = CNT_PEP_AccountCertifications.getBadgeVariations(certificationName[0].Certification_Name__c);
        Test.stopTest();
        
        System.assertEquals(1, partnerCertifications.size());
    }
    
    @isTest
    public static void testGetBadgeDownloadURL(){
        List<Partner_Certification__c> certificationDetail=[SELECT Certification_Name__c,Badge_Variation__c FROM Partner_Certification__c
                                                            WHERE Certification_Name__c='ePromo - Integration Partner'];
        String imageFormat1='JPEG';
        String imageFormat2='PNG';
        String imageFormat3='SVG';
        Test.startTest();
        String badgeURL1 = CNT_PEP_AccountCertifications.getBadgeDownloadURL(certificationDetail[0].Certification_Name__c,imageFormat1,certificationDetail[0].Badge_Variation__c);
        String badgeURL2  = CNT_PEP_AccountCertifications.getBadgeDownloadURL(certificationDetail[0].Certification_Name__c,imageFormat2,certificationDetail[0].Badge_Variation__c);
        String badgeURL3  = CNT_PEP_AccountCertifications.getBadgeDownloadURL(certificationDetail[0].Certification_Name__c,imageFormat3,certificationDetail[0].Badge_Variation__c);
        Test.stopTest();
        
        System.assertEquals('Test Link1',  badgeURL1);
        System.assertEquals('Test Link2', badgeURL2);
        System.assertEquals('Test Link3', badgeURL3);
    }
}