src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RDCategorization__c</fullName>
        <description>CSM-ACN-S-0036 - Picklist field with values Sponsor,Site, Internal, External</description>
        <label>R&amp;D Categorization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sponsor</fullName>
                </value>
                <value>
                    <fullName>Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RDClinicalSite__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Must be Only needed for R&amp;D purpose</inlineHelpText>
        <label>R&amp;D Clinical Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RDSponsor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM - ACN - S0036 - R&amp;D Sponsor</description>
        <label>R&amp;D Sponsor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>CSM-ACN-S-0062 - Field to define preferred language</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Preferred_Language</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1455 - Field value dependent on selected Industry</description>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_QI_Case_Categorization__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LOS__c</fullName>
        <label>LOS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Categorization</relationshipLabel>
        <relationshipName>Case_Categorization</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <label>Sub-Type 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <label>Sub-Type 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType3__c</fullName>
        <label>Sub-Type 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Categorization</fullName>
                </value>
                <value>
                    <fullName>Activity</fullName>
                </value>
                <value>
                    <fullName>Knowledge</fullName>
                </value>
                <value>
                    <fullName>CountryReqBusinessHour</fullName>
                </value>
                <value>
                    <fullName>Product Level Restriction</fullName>
                </value>
                <value>
                    <fullName>Affects Version</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Categorization</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Case Categorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Categorization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecificToCSM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM - ACN - S0024 - Specific to CSM?</description>
        <label>Specific to CSM?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
    <fields>
        <fullName>LOS__c</fullName>
        <description>CSM-537</description>
        <label>LOS</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R_D_E2C_LOS</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <description>CSM-1809: All - User Queue Enhancements</description>
        <formula>CASE(1,IF(BEGINS(LOWER(Name), &apos;data&apos;),1,0), &apos;Information Offering&apos;, IF(BEGINS(LOWER(Name), &apos;rnd&apos;),1,0), &apos;R&amp;D&apos;, IF(BEGINS(LOWER(Name), &apos;tech&apos;),1,0), &apos;Technology Solutions&apos;,&apos;&apos;)</formula>
        <label>Pillar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueueName__c</fullName>
        <description>CSM - ACN - S-0007 - Queue Name</description>
        <label>Queue Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Q1</fullName>
                </value>
                <value>
                    <fullName>Q2</fullName>
                </value>
                <value>
                    <fullName>Q3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM - ACN - S-0007 - User Lookup</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Request_Ticket_Number__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Ticket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Q1_Target__c</fullName>
        <label>Q1 Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>User_License_Type__c</fullName>
        <description>MC-CRM-ESPSFDCQI-1512 -</description>
        <formula>Profile.UserLicense.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User License Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Workflow_Email_Record__c.object
<CustomObject>
    <fields>
        <fullName>Email_Action__c</fullName>
        <label>Email Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CDA_01_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CLM_01_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CLM_02_SendEmailFromGBOContractsTriage</fullName>
                </value>
                <value>
                    <fullName>CPQ_02_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CPQ_03_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CPQ_04_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CPQ_05_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CPQ_06_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CPQ_07_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CRM_01_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CRM_02_SendEmail</fullName>
                </value>
                <value>
                    <fullName>CRMINT_01_SendEmail</fullName>
                </value>
                <value>
                    <fullName>PSA_01_LR_DLP_LBI_SRCH_STGY_EMAILS</fullName>
                </value>
                <value>
                    <fullName>CSM_01_SendEmail</fullName>
                </value>
                <value>
                    <fullName>OWF_01_SendEmailForCSSBidBasedOnProductsSelected</fullName>
                </value>
                <value>
                    <fullName>OWF_02_Q2LAB_Bid_History_Scientific_Review</fullName>
                </value>
                <value>
                    <fullName>OWF_03_Q2lab_Strategic_pricing_lead_assigned</fullName>
                </value>
                <value>
                    <fullName>OWF_04_SendEmailForQ2SolutionsBidHistoryAdvionQuoterequested</fullName>
                </value>
                <value>
                    <fullName>OWF_05_SendEmailForQ2SolutionsStrategicPricingInvolved</fullName>
                </value>
                <value>
                    <fullName>OWF_06_SendEmailForQ2SubmitToContracts</fullName>
                </value>
                <value>
                    <fullName>OWF_07_SendEmailForQ2SolutionsBidHistoryTriageNotificationExcludingMerckKGaA</fullName>
                </value>
                <value>
                    <fullName>OWF_08_SendEmailForQ2SolutionsLevel1RankingAlert</fullName>
                </value>
                <value>
                    <fullName>OWF_09_SendEmailForQ2SolutionsLevel2RankingAlert</fullName>
                </value>
                <value>
                    <fullName>OWF_10_SendEmailForQ2SolutionsLevel3RankingAlert</fullName>
                </value>
                <value>
                    <fullName>OWF_11_SendEmailForQ2SolutionsLevel4RankingAlert</fullName>
                </value>
                <value>
                    <fullName>OWF_12_SendEmailForStrategicPricingLeadAlert</fullName>
                </value>
                <value>
                    <fullName>OWF_13_SendEmailForQ2BioFortisEmailAction</fullName>
                </value>
                <value>
                    <fullName>OWF_14_SendEmailForQ2ChinaLocalSolutionEmailAction</fullName>
                </value>
                <value>
                    <fullName>OWF_15_SendEmailForQ2BidOwnerChangeAction</fullName>
                </value>
                <value>
                    <fullName>OWF_17_AwardBidWithStatusReadyToAward</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Module_Name__c</fullName>
        <label>Module Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To_Object_Api__c</fullName>
        <label>Related To Object Api</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To_Object_Id__c</fullName>
        <label>Related To Object ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Email_1__c</fullName>
        <label>To Email 1</label>
        <type>Email</type>
    </fields>
    <label>Workflow Email Record</label>
    <nameField>
        <displayFormat>WER-{000000000}</displayFormat>
        <label>Workflow Email Records</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Email Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/R_D_E2C_LOS.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Account Management</fullName>
    </customValue>
    <customValue>
        <fullName>CD-CSS</fullName>
    </customValue>
    <customValue>
        <fullName>CRC Lab</fullName>
    </customValue>
    <customValue>
        <fullName>EDC Support</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency</fullName>
    </customValue>
    <customValue>
        <fullName>Infosario - QCC</fullName>
    </customValue>
    <customValue>
        <fullName>Infosario Veeva Support</fullName>
    </customValue>
    <customValue>
        <fullName>Public Triage</fullName>
    </customValue>
    <customValue>
        <fullName>Q² Investigator Site Support</fullName>
    </customValue>
    <customValue>
        <fullName>Q² Lab Investigator Services</fullName>
    </customValue>
    <customValue>
        <fullName>Registry Support</fullName>
    </customValue>
    <description>CSM-537</description>
    <masterLabel>R&amp;D E2C LOS</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_UTL_CSM_SendMail.cls
@isTest
public class TST_UTL_CSM_SendMail {
    @testSetup
    static void setup(){
        String profileName='System Administrator';
        Id pId =  [SELECT Id FROM Profile WHERE Name = :profileName].Id;
        Integer noOfUser = 10;
        List<User> userList = new List<User>();
        for(Integer index = 0; index < noOfUser; index++) {
            userList.add(new User(
                ProfileId = pId,
                LastName = 'lastName123'+index,
                Email = 'testuser'+index+'3133@iqvia.com',
                Username = 'tes12'+index+'3@imshealth.com',
                CompanyName = 'TEST',
                Title = 'title',
                Alias = 'alia33'+index,
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                Q1_Target__c = 1.0,
                Change_Request_Description__c = 'test',
                Change_Request_Ticket_Number__c ='test description',
                employeenumber= String.valueOf(System.currentTimeMillis()) + index
            ));
        }
        if(userList != null && !userList.isEmpty()) insert userList;
        Account acct = new Account(Name = 'testSetupTestSiteAccount1', RDSponsor__c = true, RDClinicalSite__c = true, RDCategorization__c = 'Site',CustomerSegment__c = 'GOVERNMENT',Sub_Industry__c = 'STATE');
        insert acct;
        
        Contact con = new Contact(FirstName = 'TestFirstName', Lastname = 'testSetupContact', Phone = '(619)852-4569', Department = 'Mission Control', 
            Title = 'Mission Specialist - Neptune', Email = 'testSetupcon@iqvia.com', AccountId = acct.Id, PreferredLanguage__c = 'en_US');
        insert con;
        
        Queue_User_Relationship__c queues1 = new Queue_User_Relationship__c();
        queues1.Name = 'Q1';
        queues1.QueueName__c = 'Q1';
        queues1.Type__c = 'Queue';
        queues1.User__c = UserInfo.getUserId(); 
        insert queues1;
        
        Queue_User_Relationship__c queueUser1 = new Queue_User_Relationship__c();
        queueUser1.Name = 'Q1';
        queueUser1.QueueName__c = 'Q1';
        queueUser1.Type__c = 'User';
        queueUser1.User__c = UserInfo.getUserId();
        insert queueUser1;
        
        Product2 p2 = new Product2(Name = 'Nexxus MI',Pillar__c = 'Technology Solutions',SpecificToCSM__c = True);
        insert p2;
        Asset a2 = new Asset(Name = 'Nexxus MI', AccountId = acct.Id, Product2Id = p2.id, Status ='Installed');
        insert a2;
        CSM_QI_Case_Categorization__c cc = new CSM_QI_Case_Categorization__c(
            Product__c= p2.Id,SubType1__c = 'Incident-Module', SubType2__c = 'Formularies',
            SubType3__c = '--none--', Active__c = true, Type__c = 'Categorization', Pillar__c = 'Technology Solutions');
            insert cc;
        Id recordTypeIdTechno = Schema.SObjectType.case.getRecordTypeInfosByName().get('TechnologyCase').getRecordTypeId();
        Case cs = new Case();
        cs.ContactId = con.Id;
        cs.AccountId = acct.Id;
        cs.AssignCaseToCurrentUser__c = false;
        cs.OwnerId = UserInfo.getUserId();
        cs.RecordTypeId = recordTypeIdTechno;
        cs.Priority = 'Priority 4';
        cs.Origin = 'Customer Portal';
        cs.Mail_CC_List__c = 'nodata@info.com';
        cs.Subject = 'Techno Test case';
        cs.Description = 'Test class to check case creation ';
        cs.Status = 'New';
        cs.CurrentQueue__c = queueUser1.Id;
        cs.ProductName__c= 'Nexxus MI';
        cs.SubType1__c = 'Incident-Module';
        cs.SubType2__c = 'Formularies';
        cs.SubType3__c = '--none--';
		insert cs;
        
        cs.Watch_List_User__c = userList[0].Id+','+userList[1].Id;
        update cs;
        
        FeedItem item = new FeedItem();
        item.ParentId = cs.Id;
        item.Body = 'Test Post';
        insert item;
    }
	static testMethod void testsendMailToWatchListUser() {
        List<User> users =[SELECT Id,Name,Email FROM User WHERE User_License_Type__c = 'Salesforce' LIMIT 10];
        Test.startTest();
        Case c = [SELECT Id,ContactId,CaseNumber,LOS__c,Priority,RecordTypeName__c,Subject,ProductName__c,Origin,LastModifiedById FROM Case Limit 1];
        
        EmailTemplate et = [select id from EmailTemplate  where Name like 'CSM_Case_Update_Watchlist_Mail' limit 1];
        
        List<UTL_CSM_SendMail.MessageWrapper> messageList = new List<UTL_CSM_SendMail.MessageWrapper>();
        UTL_CSM_SendMail.MessageWrapper message = new UTL_CSM_SendMail.MessageWrapper();
        message.toEmails = new List<String>{users[0].Id};
        message.content = '<html><body><table border="0" cellpadding="5" width="550" cellspacing="5" height="400" >'+
							+'<tr valign="top" height="400" >'+
                            +'<td tEditID="c1r1" style=" background-color:#FFFFFF; color:#000000; bEditID:r3st1; bLabel:main; font-size:12pt; font-family:arial;" aEditID="c1r1" locked="0" >'+
                            +'<![CDATA[<font face="arial" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Case Number <a href="{!Case.Link}">{!Case.CaseNumber}&nbsp;</a> with {!Case.Priority} has been updated</font>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><font face="arial"><br></font></div><div style=""><font face="arial" style="">'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><b>Update Type:</b>&nbsp;UpdateTitle</div><div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style=""><b style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Old and New field value:</b><span style="font-size: 12pt;">&nbsp;</span><span style="font-size: 12pt;">Updatefield</span></div>'+
                            +'</font><font face="arial" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style=""><b style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Update made by:</b><span style="font-size: 12pt;">&nbsp;</span>LastChange</div>'+
                            +'</font><font face="arial" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><b>Case Title:</b>&nbsp;{!Case.Subject}</div><div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style=""><b style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Product:&nbsp;</b>{!Case.ProductName__c}</div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style=""><b style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Case origin:&nbsp;</b>{!Case.Origin}</div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div><div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><b>Case Comment or Post:</b>&nbsp;NewComment</div></font>'+
                            +'<font face="arial" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><b>Please review the Case and take appropriate action.</b></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Click on the link to access the case: <a href="{!Case.Link}">Click Here</a></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><font color="#de350b">PLEASE DO NOT REPLY TO THIS AUTOMATED EMAIL</font></div></font></div>]]></td>'+
                            +'</tr></table></body></html>';
        message.subject = 'Test Mail';
        message.whatId = c.Id;
    	message.targetObjectId = c.ContactId;
        message.isTargetObjectAsRecipient = false;
        message.whatId= c.Id;
        message.changes = 'Test Mail';
        message.changeValue = '';
        message.caseNumber = c.CaseNumber;
        message.priority = c.Priority;
        message.lastModify = c.LastModifiedById;
        message.title = c.Subject;
        if(c.ProductName__c !=null)
        	message.product = c.ProductName__c;
        else
        	message.product = '';
        message.origin = c.Origin;
        message.templateId = et.Id;
        messageList.add(message);
        
        message = new UTL_CSM_SendMail.MessageWrapper();
        message.targetObjectId = c.Id;
        message.isTargetObjectAsRecipient = false;
        
        messageList.add(message);

        UTL_CSM_SendMail.sendMailToWatchListUser(messageList);
        List<Workflow_Email_Record__c> records = [Select Id from Workflow_Email_Record__c];
        Test.stopTest();
    }
    
    static testMethod void testsetWorkflowParameter(){
        Test.startTest();
        Case c = [SELECT Id,ContactId,CaseNumber,LOS__c,Priority,RecordTypeName__c,Subject,ProductName__c,Origin,LastModifiedById FROM Case Limit 1];
		List<User> userlist = [SELECT Id,EMail FROM User WHERE User_License_Type__c = 'Salesforce' LIMIT 2];   
        Test.stopTest();
        UTL_CSM_SendMail.MessageWrapper message = new UTL_CSM_SendMail.MessageWrapper();
        Workflow_Email_Record__c record = new Workflow_Email_Record__c();
        message.toEmails = new List<String>{userlist[0].Id};
        message.content = '<html><body><table border="0" cellpadding="5" width="550" cellspacing="5" height="400" >'+
							+'<tr valign="top" height="400" >'+
                            +'<td tEditID="c1r1" style=" background-color:#FFFFFF; color:#000000; bEditID:r3st1; bLabel:main; font-size:12pt; font-family:arial;" aEditID="c1r1" locked="0" >'+
                            +'<![CDATA[<font face="arial" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Case Number <a href="{!Case.Link}">{!Case.CaseNumber}&nbsp;</a> with {!Case.Priority} has been updated</font>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><font face="arial"><br></font></div><div style=""><font face="arial" style="">'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><b>Update Type:</b>&nbsp;UpdateTitle</div><div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style=""><b style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Old and New field value:</b><span style="font-size: 12pt;">&nbsp;</span><span style="font-size: 12pt;">Updatefield</span></div>'+
                            +'</font><font face="arial" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style=""><b style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Update made by:</b><span style="font-size: 12pt;">&nbsp;</span>LastChange</div>'+
                            +'</font><font face="arial" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><b>Case Title:</b>&nbsp;{!Case.Subject}</div><div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style=""><b style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Product:&nbsp;</b>{!Case.ProductName__c}</div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style=""><b style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Case origin:&nbsp;</b>{!Case.Origin}</div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div><div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><b>Case Comment or Post:</b>&nbsp;NewComment</div></font>'+
                            +'<font face="arial" style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><b>Please review the Case and take appropriate action.</b></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;">Click on the link to access the case: <a href="{!Case.Link}">Click Here</a></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><br></div>'+
                            +'<div style="color: rgb(0, 0, 0); font-family: arial; font-size: 12pt;"><font color="#de350b">PLEASE DO NOT REPLY TO THIS AUTOMATED EMAIL</font></div></font></div>]]></td>'+
                            +'</tr></table></body></html>';
        message.subject = 'Test Mail';
        message.whatId = c.Id;
    	message.targetObjectId = c.ContactId;
        message.isTargetObjectAsRecipient = false;
        message.whatId= c.Id;
        message.changes = 'Test Mail';
        message.changeValue = '';
        message.caseNumber = c.CaseNumber;
        message.priority = c.Priority;
        message.lastModify = c.LastModifiedById;
        message.title = c.Subject;
        if(c.ProductName__c !=null)
        	message.product = c.ProductName__c;
        else
        	message.product = '';
        message.origin = c.Origin;
        message.whatId = c.Id;
        
		UTL_CSM_SendMail.setWorkflowParameter(record, message);
        
        System.assertEquals(record.To_Email_1__c, null);
        System.assertEquals(record.Related_To_Object_Id__c, c.Id);
        System.assertEquals(record.Related_To_Object_Api__c, 'Case');
        System.assertEquals(record.Module_Name__c, 'CSM');
        System.assertEquals(record.Email_Action__c, 'CSM_01_SendEmail');
     }
    
    static testMethod void testIsValidEmailId(){
        System.assertEquals(UTL_CSM_SendMail.isValidEmailId('xyz@abc.com'), true);
        System.assertEquals(UTL_CSM_SendMail.isValidEmailId('xy___33z@abc.com'), true); 
        System.assertEquals(UTL_CSM_SendMail.isValidEmailId('@abc.com'), false); 
        System.assertEquals(UTL_CSM_SendMail.isValidEmailId('abc.com'), false); 
    }
    
    static testMethod void testUpdateEmailMessageMail(){
        Test.startTest();
        List<Case> c = [SELECT Id,ContactId,CaseNumber,LOS__c,Priority,RecordTypeName__c,Subject,ProductName__c,Origin,LastModifiedById,Watch_List_User__c FROM Case Limit 1];
        Test.stopTest();
        UTL_CSM_SendMail.updateEmailMessageMail('Email',c,null);
    }
    static testMethod void testUpdateTaskMail(){
        Test.startTest();
        List<Case> c = [SELECT Id,ContactId,CaseNumber,LOS__c,Priority,RecordTypeName__c,Subject,ProductName__c,Origin,LastModifiedById,Watch_List_User__c FROM Case Limit 1];
        Set<Id> ids = new Set<Id>();
        ids.add(c[0].Id);
        Test.stopTest();
        UTL_CSM_SendMail.updateTaskMail('Call', ids);
    }
    
    static testMethod void testUpdatePostMail(){
        Test.startTest();
        List<Case> cs = [SELECT Id,CaseNumber FROM Case Limit 1];
		List<FeedItem> feeds =[SELECT Id,ParentId,Body,CreatedById from FeedItem LIMIT 1];
        List<Id> caseIds = new List<Id>();
        caseIds.add(cs[0].Id);
        Test.stopTest();
        UTL_CSM_SendMail.updatePostMail(feeds, caseIds);
        
        System.assertEquals(caseIds[0], feeds[0].ParentId,'Success'); 
    }
    static testMethod void testUpdateCaseCommentMail(){
        Test.startTest();
        Case cs = [SELECT Id,CaseNumber FROM Case Limit 1];
        Map<Id,String> posts = new Map<Id,String>();
        posts.put(cs.Id,'Test Case Comment');
        UTL_CSM_SendMail.updateCaseCommentMail(posts);
        Test.stopTest();
    }
}