src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountStatus__c</fullName>
        <description>CSM-ACN-S-0036 - Picklist that defines Account Status with values Active, Inactive.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTIVDN__c</fullName>
        <description>CSM-ACN-S-0036 - Textfield that will hold value for CTI VDN</description>
        <label>CTI VDN</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>CSM-ACN-S-0036 - Textfield that will hold value for Department.</description>
        <label>Department</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentationURLLink__c</fullName>
        <description>CSM-ACN-S-0036 - URL field for Documentation link</description>
        <label>Documentation URL Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>CSM-ACN-S-0036 - Email Field for Account</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>InterfaceStatus__c</fullName>
        <description>CSM-ACN-S-0036 - Picklist that defines Interface Status with values &quot;New ,Submitted ,Validating ,SAP Validated ,Validating ,Rejected&quot;</description>
        <label>Interface Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>SAP Validated</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsThisASpecialHandlingClient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM-ACN-S-0036 - Checkbox to state whether client is a &quot;Special Handling account&quot;</description>
        <label>Is this a Special Handling Client?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MDMID__c</fullName>
        <description>CSM-ACN-S-0036 - Texfield for MDM ID</description>
        <externalId>true</externalId>
        <label>MDM ID</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MIData__c</fullName>
        <description>CSM-ACN-S-0036 - Text field for MI DATA</description>
        <label>MI Data</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RDClinicalSite__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Must be Only needed for R&amp;D purpose</inlineHelpText>
        <label>R&amp;D Clinical Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RDSponsor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM - ACN - S0036 - R&amp;D Sponsor</description>
        <label>R&amp;D Sponsor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>CSM-ACN-S-0036 - Picklist that defines Region with values &quot;&quot;EMEA&quot;, &quot;LATAM&quot;, &quot;NA&quot;, &quot;APAC&quot;</description>
        <label>Regional Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>AMER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAPID__c</fullName>
        <description>CSM-ACN-S-0036 - Textfield that will hold SAP ID</description>
        <label>SAP ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLAApplies__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM-ACN-S-0036 - SLA Applies checkbox.</description>
        <label>SLA Applies?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLAPenalties__c</fullName>
        <description>CSM-ACN-S-0036 - Text field SLA penalties.</description>
        <label>SLA Penalties</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendAutomaticCaseAcknowledgmentEmail__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CSM - ACN - S0023 - Send automatic Case acknowledgment Email checked by default</description>
        <label>Send Automatic Case Acknowledgment Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <description>CSM-ACN-S-0036 - Long Textfield for Tags.</description>
        <label>Tags</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type2__c</fullName>
        <description>CSM-ACN-S-0036 - Multi picklist with values &quot;Analyst ,Clinical Site ,Competitor ,Customer ,Integrator ,Investor Manufacturer ,Partner ,Press ,Prospect ,Reseller ,Sponsor ,Supplier ,Third Party ,Vendor, Other&quot;
PEP-ACN-PRM-53 - added new values : &quot;Data Partner&quot;, &quot;Tech Partner&quot;, &quot;CLM Agency&quot; and renamed &quot;Integrator&quot; into &quot;Integrator Partner&quot;</description>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Integrator</fullName>
                    <label>Integrator Partner</label>
                </value>
                <value>
                    <fullName>Investor</fullName>
                </value>
                <value>
                    <fullName>Press</fullName>
                </value>
                <value>
                    <fullName>Data Partner</fullName>
                </value>
                <value>
                    <fullName>Tech Partner</fullName>
                </value>
                <value>
                    <fullName>CLM Agency</fullName>
                </value>
                <value>
                    <fullName>Clinical Site</fullName>
                </value>
                <value>
                    <fullName>RDS Sponsor</fullName>
                </value>
                <value>
                    <fullName>Client Third Party Vendor</fullName>
                </value>
                <value>
                    <fullName>CRO</fullName>
                </value>
                <value>
                    <fullName>Training Partner</fullName>
                </value>
                <value>
                    <fullName>Investigator</fullName>
                </value>
                <value>
                    <fullName>Manufacturer</fullName>
                    <isActive>false</isActive>
                    <label>Manufacturer</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                    <isActive>false</isActive>
                    <label>Partner</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                    <isActive>false</isActive>
                    <label>Reseller</label>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                    <isActive>false</isActive>
                    <label>Supplier</label>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                    <isActive>false</isActive>
                    <label>Third Party</label>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                    <isActive>false</isActive>
                    <label>Vendor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Credit_Control_Groups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Group_Names__c</fullName>
        <label>Group Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credit Control Groups</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3361</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Europe/Middle East/Africa EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>USA/Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_TGR_Account.cls
/**
* This test class is used to test Account Trigger.
* version : 1.0
*/
@isTest
private class TST_TGR_Account {
    
    @testsetup
    static void setupData(){
        upsert new Credit_Control_Groups__c(Name = 'Group Names', Group_Names__c = 'Credit Control Groups,Super Credit Control Admins');
        Group grp = new Group(name='Super Credit Control Admins');
        insert grp;  
        Id userId = UserInfo.getUserId();
        User testUser = [Select id, Name from User where id = :userId];
        System.runAs(testUser) {
            GroupMember grpMember = new GroupMember(GroupId = grp.Id, UserOrGroupId = userId);
            insert grpMember;
        }
    }
    
    /**
    * This test method used for insert Account record
    */ 
    static testMethod void testInsertContact() {
        test.startTest();
        Account newAccount = UTL_TestData.createAccount();
        insert newAccount;
        test.stopTest();
        Account existingAccount = [SELECT Id, Name FROM Account LIMIT 1];
        System.assertEquals('TestAccount', existingAccount.Name);
    }
    
    
    /**
    * This test method used for insert and update Case record
    */ 
    static testMethod void testAuditforContact() {
        Account acc = CSM_Util.createAccount();
        insert acc;
        CNT_CSM_FieldHistoryTracking.saveFields('Account','AccountNumber,AccountSource,AccountStatus__c,AnnualRevenue,CTIVDN__c,CurrencyIsoCode,Department__c,Description,DocumentationURLLink__c,Email__c,Fax,CustomerSegment__c,InterfaceStatus__c,IsExcludedFromRealign,IsThisASpecialHandlingClient__c,Jigsaw,JigsawCompanyId,LastActivityDate,MasterRecordId,MDMID__c,MIData__c,NumberOfEmployees,Ownership,ParentId,Phone,PhotoUrl,Rating,RDClinicalSite__c,RDSponsor__c,RecordTypeId,Region__c,SAPID__c,SendAutomaticCaseAcknowledgmentEmail__c,ShippingAddress,Sic,SicDesc,Site,SLAApplies__c,SLAPenalties__c,SystemModstamp,Tags__c,TickerSymbol,Type,Type2__c,Website');
        Account accP = CSM_Util.createAccount();
        insert accP;
        Account accP1 = CSM_Util.createAccount();
        insert accP1;
        Test.startTest();
        accP.Description = 'Test Description';
        accP.CustomerSegment__c = 'FINANCIAL COMPANY';
        accP.Sub_Industry__c = 'BANKING';
        accP.Website = 'http://gmail.com';
        update accP;
        accP.Description = 'Test Description Changed';
        accP.Website = 'http://yahoo.com';
        accP.CustomerSegment__c = 'GOVERNMENT';
        accp.Sub_Industry__c = 'STATE';
        update accP;
        accP.Description = null;
        accP.Website = null;
        accP.CustomerSegment__c = null;
        accP.Sub_Industry__c = null;
        update accP;
        CNT_CSM_FieldHistoryTracking.saveFields('Account','AccountNumber,AccountSource,AccountStatus__c,AnnualRevenue,BillingAddress,CTIVDN__c,CurrencyIsoCode,Department__c,Description,DocumentationURLLink__c,Email__c,Fax,CustomerSegment__c,InterfaceStatus__c,IsExcludedFromRealign,IsThisASpecialHandlingClient__c,Jigsaw,JigsawCompanyId,LastActivityDate,MasterRecordId,MDMID__c,MIData__c,NumberOfEmployees,Ownership,ParentId,Phone,PhotoUrl,Rating,RDClinicalSite__c,RDSponsor__c,RecordTypeId,Region__c,SAPID__c,SendAutomaticCaseAcknowledgmentEmail__c,ShippingAddress,Sic,SicDesc,Site,SLAApplies__c,SLAPenalties__c,SystemModstamp,Tags__c,TickerSymbol,Type,Type2__c,Website');
        acc.BillingCity = 'Bangalore';
        acc.BillingCountry = 'India';
        acc.BillingPostalCode = '560016';
        acc.BillingState = 'Karnataka';
        acc.BillingStreet = 'KB-11';
        acc.ParentId = accP.Id;
        update acc;
        acc.BillingCity = 'Paris';
        acc.BillingCountry = 'France';
        acc.BillingPostalCode = '500016';
        acc.BillingState = 'Telangana';
        acc.BillingStreet = 'TH-11';
        acc.ParentId = accP1.Id;
        update acc;
        acc.BillingCity = null;
        acc.BillingCountry = null;
        acc.BillingPostalCode = null;
        acc.BillingState = null;
        acc.BillingStreet = null;
        acc.ParentId = null;
        update acc;
        Test.stopTest(); 
    }
}