src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Accounts are validated against SAP to ensure a match and to prevent duplication of accounts. &quot;New&quot; indicates that the account has not yet been validated against SAP, &quot;SAP Validated&quot; means that it should exist as a ParentAccount on SAP</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>SAP Validated</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Parent_Contract_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Parent Contract Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Contract_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Ultimate Parent Contract Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Stage_Gate_Status_Values__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CRM-MC-ESPSFDCQI-2887</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>CRM-MC-ESPSFDCQI-2887</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Stage Gate Status Values</label>
</CustomObject>

src/classes/TST_DAO_Contract.cls
/**
* This class is used to test DAO_Contract
*/
@isTest
public class TST_DAO_Contract {
    
    @testSetup 
    static void dataSetup() { 
        Account acc = UTL_TestData.createAccount();
        insert acc;
        Stage_Gate_Status_Values__c statusvalue = new Stage_Gate_Status_Values__c();
        statusvalue.Name = 'AnalystPP';
        statusvalue.Status__c = 'Analyst Preparing Customer Budget Deliverable';
        upsert statusvalue;
    }
    
    static testMethod void testContract() {
        Test.startTest();
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Contract cntrt = new Contract();
        cntrt.AccountId = acc.Id;
        cntrt.Status = 'Draft';
        cntrt.CurrencyIsoCode = 'INR';
        cntrt.Status = 'Analyst Preparing Customer Budget Deliverable';
        cntrt.StartDate = System.today();
        cntrt.ContractTerm = 12;
        cntrt.Parent_Contract_Number__c = 1234;
        cntrt.Ultimate_Parent_Contract_Number__c = 5678;
        insert cntrt; 
        cntrt.ContractTerm = 13;
        update cntrt;
        cntrt = [SELECT Id, ContractTerm FROM Contract LIMIT 1];
        System.assertEquals(13, cntrt.ContractTerm);
        try {
            delete cntrt;
        } catch(Exception ex) {
            System.debug(ex.getMessage());
        }
        List<Contract> cntrtList = [SELECT Id, ContractTerm FROM Contract];
        System.assertEquals(0, cntrtList.size());
        Test.stopTest();
    }
}