src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SAP_Code__c</fullName>
        <label>SAP Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>Holds the SAP Code this account if it has been verified. This replaces the SAP_SP_Code__c, SAP_PC_Code__c and SAP_Code__c fields.</description>
        <inlineHelpText>Holds the account&apos;s unique SAP Reference. You may refer to the account by its SAP Reference if you prefer. If it is a Parent-level account (mostly), it will be in the form 5xxxxx, if it is SuperParent-level account, then it is in the form HNCSPxxxxxx.</inlineHelpText>
        <label>SAP Reference</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Accounts are validated against SAP to ensure a match and to prevent duplication of accounts. &quot;New&quot; indicates that the account has not yet been validated against SAP, &quot;SAP Validated&quot; means that it should exist as a ParentAccount on SAP</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>SAP Validated</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of the account that this address pertains to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AccountAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marked_For_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this address marked for deletion in SAP</description>
        <label>Marked For Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>SAP Base code that corresponds to this address. This is hierarchically-based on the SAP Parent code in the Account and the looked up in SAP. When it is not populated, then this address had not been validated. This is not editable by normal users.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Base code that corresponds to this address.</inlineHelpText>
        <label>SAP Base Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to update status when MDM team approves / rejects an address.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BNF2__c.object
<CustomObject>
    <description>Billing Notification Form</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Ship To: Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fair_Value_Type__c</fullName>
        <description>This field is a required field in which the user selects one of the options presented: Stand Alone, MEA with one-off or MEA without one-off. Stand Alone - Sold separately for cash and has value to the client without other services or deliverables.  Meaning it is not purchased as part of another deliverable and its functionality is not dependent on any other IMS services. Multiple Element Arrangement (MEA) - Contracts that involve the delivery or performance of more than one product or service, including those combining historical/back-data with ongoing deliverables</description>
        <label>Fair Value Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Stand Alone</fullName>
                </value>
                <value>
                    <fullName>MEA - with one off</fullName>
                </value>
                <value>
                    <fullName>MEA - without one off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Default_Day__c</fullName>
        <label>Invoice Default Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>Default Material Master Data</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Header_Text__c</fullName>
        <label>Invoice Header Text</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the name of the Revenue Analyst who will be processing the BNF.</inlineHelpText>
        <label>Revenue Analyst</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>No matching Revenue Analyst can be found matching search criteria</errorMessage>
            <filterItems>
                <field>Revenue_Analyst__c.Available_for_Selection__c</field>
                <operation>equals</operation>
                <value>TRUE</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>$Source.BNF_Status__c</field>
                <operation>notEqual</operation>
                <value>New</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Revenue_Analyst__c</referenceTo>
        <relationshipName>R00N70000001hxy1EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase/BNF</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Purchase/BNF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase/BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CRM-MC-ESPSFDCQI-889 - editable by permission set for NGCD group</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triage</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Not Supported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>ESPSFDCQI-3356</description>
        <formula>TEXT(Owner.User_Country__c)</formula>
        <label>User Country</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Revenue_Analyst__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-3168 - This custom object is used to store the Revenue Analyst.</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N70000001hwojEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Analyst</label>
    <nameField>
        <label>Revenue Analyst Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Analysts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>CRM-MC-ESPSFDCQI-626 - Country the User is associated to.</description>
        <inlineHelpText>CRM-MC-ESPSFDCQI-626 - Country the User is associated to.</inlineHelpText>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>User_Country</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/User_Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>APAC Regional</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN Regional</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Mid Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>Cameroon</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Cayman Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Chad</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-626 - Country the User is associated to.</description>
    <masterLabel>User Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/Account_MDM_Extension.cls
public class Account_MDM_Extension {

	private Account Account;
	private ApexPages.StandardController StandardController;
//	public String ARC_MDM_Link {get;private set;}
	public Contact ProxyContact {get;private set;}
	private Map<String,String> EntryUrlParams;
	public Boolean SubmittedForApproval {get; private set;}
	public Boolean CurrentUserIsApprover {get; private set;}
	public Integer NumApprovalHistorySteps {get; private set;}
	
	public Account_MDM_Extension(ApexPages.StandardController controller)
	{
		this.StandardController = controller;
		this.Account = (Account)StandardController.getRecord();
//		this.ARC_MDM_Link = 'http://arc.imshealth.com/xxx';
		this.ProxyContact = new Contact(AccountId = this.Account.Id);
		this.EntryUrlParams = new Map<String,String>(ApexPages.currentPage().getParameters());
		this.SubmittedForApproval = false;
		this.CurrentUserIsApprover = false;
		this.NumApprovalHistorySteps = 0;
		ProcessInstanceWorkitem[] WorkItem_Array = [select Id, ProcessInstance.Id, ProcessInstance.TargetObjectId, ActorId from ProcessInstanceWorkitem  
    								where ProcessInstance.Status like 'Pending' and 
    								ProcessInstance.TargetObjectId = :this.Account.Id];
		if (WorkItem_Array.size() > 0)
		{
			this.SubmittedForApproval = true;
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Account "' + this.Account.Name + '" has already been submitted for approval. Please see below for current approval status.');
			ApexPages.addMessage(myMsg);
		}
		if (Apexpages.currentPage().getParameters().get('error') == 'AccountValidation')
		{
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Account "' + this.Account.Name + '" has not been validated in SAP.');
			ApexPages.addMessage(myMsg);
		}		
	}
	
/*	public pageReference ARC_MDM_Request()
	{
		pageReference MDM_Page = new pageReference(this.ARC_MDM_Link);
		MDM_Page.setRedirect(true);
		return MDM_Page; 
	}*/
	
	public pageReference CreateManualBnf()
    {
    	 //Quick Opp
    	//Update by Himanshu Parashar : 22 sep 2011
    	// Checking for quick opportunity
        String quickOppRecordtypeID;
        String OppRecordType;
        String UserCountry;
        Boolean isQuickOpp;
        for(RecordType recordtypeId : [SELECT Id FROM RecordType where Name Like 'Quick Opportunity' limit 1])
        {
        	quickOppRecordtypeID = recordtypeId.Id;
      
        }
        // Getting Opportunity Record Type
        for(Opportunity opp : [SELECT RecordTypeId FROM Opportunity where id=:ApexPages.currentPage().getParameters().get('OpportunityId') limit 1])
        {
        	OppRecordType = opp.RecordTypeId;
      
        }
        // Getting User Country details
        for(User U : [select User_Country__c from User where Id = :UserInfo.getUserId()])
        {
        	UserCountry=U.User_Country__c;
        }
         
        // Check for Quick Opportunity 
        if(quickOppRecordtypeID!=null && quickOppRecordtypeID!='' && OppRecordType!=null && quickOppRecordtypeID==OppRecordType)
        {
             isQuickOpp=true;  // True if quick opportunity
        }
        else
             isQuickOpp =false;
             
        //Setting default values in case of quick opportunity
        String InvoiceDefaultDay='Default Material Master Data';
	    String FairValue='Stand Alone';
	    String InvoiceHeaderText='Rechnungstext:Lieferdatum:';
	    
	    //Quick Opp
	    		//Update by Himanshu Parashar : 22 sep 2011
	            //Setting default values in case of quick opportunity
	    
        Map<String, String> fieldApiToIdmap = UTL_Sobject.getCustomFieldByIds('BNF2');
        if(isQuickOpp)
        {
            
           	 this.EntryUrlParams.put(fieldApiToIdMap.get('Fair_Value_Type__c'), FairValue);
        	 this.EntryUrlParams.put(fieldApiToIdMap.get('Invoice_Default_Day__c'), InvoiceDefaultDay);
        
        	if(UserCountry!=null && UserCountry=='Germany')
        		this.EntryUrlParams.put(fieldApiToIdMap.get('Invoice_Header_Text__c'), InvoiceHeaderText);
       }
        //******************************************************************
        String bnfPrefix = BNF2__c.SobjectType.getDescribe().getKeyPrefix();
        String NewBnfUrl = '/' + bnfPrefix + '/e?'; 
        this.EntryUrlParams.remove('id');
        this.EntryUrlParams.remove('error');
        this.EntryUrlParams.remove('SalesOrg');              	
        for (String Param:this.EntryUrlParams.keySet())
        {
            NewBnfUrl += '&' + Param + '=' + this.EntryUrlParams.get(Param);
        }
        pageReference NewBnf = new pageReference(NewBnfUrl);
        NewBnf.setRedirect(true);      
        return NewBnf;
    }  	
    
    public void GetApprovalSteps()
    {
        this.Account = [Select A.Id,A.Name, (Select Id, Status From ProcessInstances order by Id desc), 
						(Select ActorId, Comments, CreatedById, CreatedDate, Id, 
						IsPending, OriginalActorId, RemindersSent, StepStatus,ProcessInstanceId From ProcessSteps order by Id desc) 
						from Account A where Id = :this.Account.Id];
		this.NumApprovalHistorySteps = 	this.Account.ProcessInstances.size();					
    }
    
    public List<ApprovalProcessDisplay> getCustomApprovalProcessHistory()
    {
    	system.debug('calling getCustomApprovalProcessHistory()');    	
    	this.GetApprovalSteps();
    	User CurrentUser = [select Id,Profile.Name from User where Id = :UserInfo.getUserId()];
    	List<ApprovalProcessDisplay> ApprovalProcessDisplay_Array = new List<ApprovalProcessDisplay>();    	

    	Map<Id,ProcessInstance> ProcessInstance_Map = new Map<Id,ProcessInstance>();
    	ProcessInstanceWorkitem[] WorkItem_Array = [select Id, ProcessInstance.Id, ProcessInstance.TargetObjectId, ActorId from ProcessInstanceWorkitem  
    								where ProcessInstance.Status like 'Pending' and 
    								ProcessInstance.TargetObjectId = :this.Account.Id];
    	if (WorkItem_Array.size() > 0)
    	{
	    	if (WorkItem_Array[0].ActorId == CurrentUser.Id || Pattern.matches('System Administrator[\\s|[A-z]|[0-9]]*',CurrentUser.Profile.Name))
	    	{
	    		CurrentUserIsApprover = true;
	    	}
    	}
    	for (ProcessInstance P:this.Account.ProcessInstances)
    	{
    		ProcessInstance_Map.put(P.Id,P);
    	}
    	for (ProcessInstanceHistory P:this.Account.ProcessSteps)
    	{
    		ApprovalProcessDisplay TempDisplay = new ApprovalProcessDisplay();
    		//  Use ProxyRa.OwnerId to display ActorId
    		TempDisplay.ProxyRa.OwnerId = P.ActorId;
    		//  Use ProxyRa.User__c to display OriginalActorId
    		TempDisplay.ProxyRa.User__c = P.OriginalActorId;
    		//  Use ProxyTask.ReminderDateTime to display created date
    		TempDisplay.ProxyTask.ReminderDateTime = P.CreatedDate;
    		if (P.StepStatus == 'Approved'  || P.StepStatus == 'Rejected' || P.StepStatus == 'Pending')
    		{
    			TempDisplay.Status = P.StepStatus;
    		}
    		TempDisplay.Comments = P.Comments;
    		if (P.StepStatus != 'Pending')
    		{
    			TempDisplay.Action = 'Approval Request ' + P.StepStatus.replace('Started','Submitted');// + '| ' + P.ProcessInstanceId;
    		}
    		else 
    		{
    			if (CurrentUserIsApprover)
    			{
	    			TempDisplay.ApproveLinkRendered = true;
	    			TempDisplay.ApproveLink = '/p/process/ProcessInstanceWorkitemWizardStageManager?id=' + WorkItem_Array[0].Id;
	    			TempDisplay.ReassignLink = '/' + WorkItem_Array[0].Id + '/e?et=REASSIGN&retURL=%2F' + this.Account.Id;
    			}
    			else
    			{
    				TempDisplay.Action = 'Approval Pending';
    			}
    		}
    		if (P.StepStatus == 'Approved')
    		{
    			TempDisplay.ImgRendered = true;
    			TempDisplay.ImgSrc = '/img/icon/approve12.gif';
    		}
    		if (ProcessInstance_Map.get(P.ProcessInstanceId).Status == 'Pending' && P.StepStatus == 'Pending')
    		{
    			TempDisplay.ImgRendered = true;
    			TempDisplay.ImgSrc = '/img/icon/pending12.gif';
    		}
    		if (P.StepStatus == 'Rejected')
    		{
    			TempDisplay.ImgRendered = true;
    			TempDisplay.ImgSrc = '/img/icon/reject12.gif';
    		}
    		ApprovalProcessDisplay_Array.add(TempDisplay);
    	}
    	return ApprovalProcessDisplay_Array;
    }
    
    public pageReference SubmitAccountForApprovalPage()
    {
    	pageReference retUrl = Page.AccountApprovalSubmit;
    	retUrl.getParameters().put('id',this.Account.Id);
    	retUrl.setRedirect(true);
    	return retUrl;
    }
    
    public pageReference SubmitForMdmApproval()
    {
    	Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
		req1.setObjectId(this.Account.Id);
		// Submit the approval request
		try
		{
			this.StandardController.save();
			Approval.ProcessResult result = Approval.process(req1);
		}
		catch (Exception E)
		{
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,E.getMessage());
            ApexPages.addMessage(myMsg);
            return null;
		}		
		pageReference retUrl = new pageReference('/'+this.Account.Id);
		retUrl.setRedirect(true);
		return retUrl;
    }
    
    public static void UpdateRepresentativeBaseCode(Set <Id> Account_Id_Set)
	{		
		List <Address__c> Address_Array = new List <Address__c>([select Id,Account__c,SAP_Reference__c,Marked_For_Deletion__c from Address__c where Account__c in :Account_Id_Set and Account__c != null]);
		Map <String,Id> Current_Sap_Code_Map = new Map <String,Id>();
		Map <Id,String> Valid_Sap_Code_Map = new Map <Id,String>();
		for (Address__c A:Address_Array)
		{
			if (!A.Marked_For_Deletion__c)
			{
				Current_Sap_Code_Map.put(A.Sap_Reference__c,(Id)A.Account__c);
				Valid_Sap_Code_Map.put((Id)A.Account__c,A.Sap_Reference__c);
			}
		}
		Map <Id,Account> Account_Map = new Map <Id,Account>([select Id,SAP_Code__c from Account where Id in :Account_Id_Set and Status__c = :MDM_Defines.AddressStatus_Map.get('SAP_VALIDATED')]);
		List <Account> Account_Update_Array = new List <Account>();
		for (Account A:Account_Map.values())
		{
			if (Valid_Sap_Code_Map.get(A.Id) != null && (Current_Sap_Code_Map.get(A.SAP_Code__c) == null || Current_Sap_Code_Map.get(A.SAP_Code__c) != A.Id))
			{
				A.SAP_Code__c = Valid_Sap_Code_Map.get(A.Id); 
				Account_Update_Array.add(A);				
			}
		}	
		update Account_Update_Array;
	}
	
    public static void UpdateAddresses(Set <Id> Account_Id_Set)
	{		
		Map <Id,Account> Account_Map = new Map<Id,Account>([select Id,Status__c from Account where Id in :Account_Id_Set and Status__c != :MDM_Defines.AddressStatus_Map.get('SAP_VALIDATED')]);
		Map <String,Id> Current_Sap_Code_Map = new Map <String,Id>();
		Map <Id,String> Valid_Sap_Code_Map = new Map <Id,String>();
		List <Address__c> Address_Array = new List <Address__c>([select Id,Marked_For_Deletion__c from Address__c where Account__c in :Account_Map.keySet()]);
		List <Address__c> AddressUpdate_Array = new List <Address__c>();
		for (Address__c A:Address_Array)
		{
			if (A.Marked_For_Deletion__c != true)
			{
				A.Marked_For_Deletion__c = true;
				AddressUpdate_Array.add(A);
			}
		}
		update AddressUpdate_Array;
	}
	
	
	public pageReference ApprovalProcessRedirect()
	{
		User CurrentUser = [select Id,Profile.Name from User where Id = :UserInfo.getUserId()];
		ProcessInstanceWorkitem[] WorkItem_Array = [select Id, ProcessInstance.Id, ProcessInstance.TargetObjectId, ActorId from ProcessInstanceWorkitem  
    								where ProcessInstance.Status like 'Pending' and 
    								ProcessInstance.TargetObjectId = :this.Account.Id];
    	String RetUrl;
    	if (WorkItem_Array.size() > 0 &&
    		(WorkItem_Array[0].ActorId == CurrentUser.Id || Pattern.matches('System Administrator[\\s|[A-z]|[0-9]]*',CurrentUser.Profile.Name)))
    	{
			if (Apexpages.currentPage().getParameters().get('ApproveReject') != null)
			{
	    			retUrl = '/p/process/ProcessInstanceWorkitemWizardStageManager?id=' + WorkItem_Array[0].Id;
			}
			else if (Apexpages.currentPage().getParameters().get('Reassign') != null)
			{
	    			retUrl = '/' + WorkItem_Array[0].Id + '/e?et=REASSIGN&retURL=%2F' + this.Account.Id;
			}
    	}
    	else
    	{
    		retUrl = '/' + this.Account.Id;
    	}
    	pageReference ApprovalRedirect = new pageReference(retUrl);
    	ApprovalRedirect.setRedirect(true);
    	return ApprovalRedirect;
	}
	
	public class ApprovalProcessDisplay
	{
		public Revenue_Analyst__c ProxyRA {get; private set;}
		public Opportunity ProxyOpp {get; private set;}
		public Task ProxyTask {get; private set;}
		public String Action {get; private set;}
		public String Status {get; private set;}
		public String Comments {get; private set;}
		public String ImgSrc {get; private set;}
		public Boolean ImgRendered {get; private set;}
		public String ApproveLink {get; private set;}
		public String ReassignLink {get; private set;}
		public Boolean ApproveLinkRendered {get; private set;}
				
		public ApprovalProcessDisplay()
		{
			this.ProxyRA = new Revenue_Analyst__c();
			this.ProxyOpp = new Opportunity();
			this.ProxyTask = new Task();
			this.ImgRendered = false;
			this.ImgSrc = '';
			this.Status = '';
			this.Action = '';
			this.Comments = '';
			this.ApproveLinkRendered = false;
			this.ApproveLink = '';
			this.ReassignLink = '';
		}
	}
}