src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Pending for Descartes</fullName>
                </value>
                <value>
                    <fullName>Rejected by Descartes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>Holds the SAP Code this account if it has been verified. This replaces the SAP_SP_Code__c, SAP_PC_Code__c and SAP_Code__c fields.</description>
        <inlineHelpText>Holds the account&apos;s unique SAP Reference. You may refer to the account by its SAP Reference if you prefer. If it is a Parent-level account (mostly), it will be in the form 5xxxxx, if it is SuperParent-level account, then it is in the form HNCSPxxxxxx.</inlineHelpText>
        <label>SAP Reference</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Enabled_Sales_Orgs__c</fullName>
        <label>Enabled Sales Orgs</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <description>SFDCDEVOPS-186: The validation state of this address with respect to MDM System.</description>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>SAP Base code that corresponds to this address. This is hierarchically-based on the SAP Parent code in the Account and the looked up in SAP. When it is not populated, then this address had not been validated. This is not editable by normal users.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Base code that corresponds to this address.</inlineHelpText>
        <label>SAP Base Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MDM_Invoicing_Transaction__c.object
<CustomObject>
    <description>ESPSFDCQI-13635: This object is to hold the e-invoice and tax category details.</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>ESPSFDCQI-13635</description>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>MDM Invoicing Transactions</relationshipLabel>
        <relationshipName>MDM_Invoicing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-13635</description>
        <label>Mail Contact 1</label>
        <referenceTo>SAP_Contact__c</referenceTo>
        <relationshipLabel>MDM Invoicing Transactions (SAP Contact 1)</relationshipLabel>
        <relationshipName>MDM_Invoicing_Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-13635</description>
        <label>Mail Contact 2</label>
        <referenceTo>SAP_Contact__c</referenceTo>
        <relationshipLabel>MDM Invoicing Transactions (SAP Contact 2)</relationshipLabel>
        <relationshipName>MDM_Invoicing_Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-13635</description>
        <label>Mail Contact 3</label>
        <referenceTo>SAP_Contact__c</referenceTo>
        <relationshipLabel>MDM Invoicing Transactions (SAP Contact 3)</relationshipLabel>
        <relationshipName>MDM_Invoicing_Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MDM Invoicing Transaction</label>
    <nameField>
        <displayFormat>Invoice- {000000}</displayFormat>
        <label>MDM Invoicing Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDM Invoicing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SAP_Contact__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-3168 - This table contains the possible contact persons defined for a client in SAP based on the partner function of the contact.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>SAP Contacts</relationshipLabel>
        <relationshipName>SAP_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>First Name</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>Last Name</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <description>SFDCDEVOPS-186: The validation state of this address with respect to MDM System.</description>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Contact_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>SAP Contact Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_External_KEY__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <externalId>true</externalId>
        <label>SAP External KEY</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SAP Contact</label>
    <nameField>
        <label>SAP Contact Display Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_SLT_MDM_Invoicing_Transaction.cls
@isTest
public class TST_SLT_MDM_Invoicing_Transaction {
    
    @testSetup
    public static void dataSetup(){
        Account ac = UTL_TestData.createAccount();
        insert ac;
        
        Address__c add = UTL_TestData.createAddresses(ac)[0];
        add.Enabled_Sales_Orgs__c = 'AE04:US30';
        add.MDM_Validation_Status__c = 'Validated';
        add.RecordTypeId = CON_CRM.Validated_Address_RecordId;
        add.SAP_Reference__c = '123';
        insert add;
        
        List<SAP_Contact__c> listOfSc = new List<SAP_Contact__c>();
        for(Integer i =0; i<4; i++){
            SAP_Contact__c sc = new SAP_Contact__c();
            sc.First_Name__c = 'Test ';
            sc.Last_Name__c = String.valueof(i);
            sc.Address__c = add.Id;
            sc.SAP_External_KEY__c = '000'+i;
            sc.SAP_Contact_Number__c = '000'+i;
            sc.MDM_Validation_Status__c = 'Validated';
            sc.RecordTypeId = CON_CRM.Validated_SAP_Contact_RecordId;
            listOfSc.add(sc);
        }
        insert listOfSc;
        
        MDM_Invoicing_Transaction__c mit = UTL_TestData.createMDMInvoiceTransaction(add, listOfSc);
        insert mit;
    }
    
    @isTest
    public static void testGetInvoiceByCondition(){
        Test.startTest();
        Set<String> mdmFieldSet = new Set<String>{'SAP_Contact_1__c', 'SAP_Contact_2__c', 'SAP_Contact_3__c'};
            Map<Id,SAP_Contact__c> sapMap = new Map<Id,SAP_Contact__c> ([SELECT Id FROM SAP_Contact__c]);
        String mdmCondition = ' Id != null';
        
        List<MDM_Invoicing_Transaction__c> eInvoiceList= new SLT_MDM_Invoicing_Transaction().getInvoiceByCondition(mdmFieldSet, mdmCondition);
        System.assertEquals(1, eInvoiceList.size());
        eInvoiceList = new SLT_MDM_Invoicing_Transaction().getInvoiceBySapContact(mdmFieldSet, sapMap.keySet());
        System.assertEquals(1, eInvoiceList.size());
        Test.stopTest();
        
    }
    
}