src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CSM_QI_Case_Categorization__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Categorization</relationshipLabel>
        <relationshipName>Case_Categorization</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <label>Sub-Type 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <label>Sub-Type 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType3__c</fullName>
        <label>Sub-Type 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Categorization</fullName>
                </value>
                <value>
                    <fullName>Activity</fullName>
                </value>
                <value>
                    <fullName>Knowledge</fullName>
                </value>
                <value>
                    <fullName>CountryReqBusinessHour</fullName>
                </value>
                <value>
                    <fullName>Product Level Restriction</fullName>
                </value>
                <value>
                    <fullName>Affects Version</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Categorization</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Case Categorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Categorization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSM_QI_CaseAutomationScheduler__c.object
<CustomObject>
    <description>CSM-1039 CSM Case Automation Scheduler for Optrack</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSM Case Automation Schedulers</relationshipLabel>
        <relationshipName>CSM_Case_Automation_Schedulers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account Name should match with Asset Account.</errorMessage>
            <filterItems>
                <field>Asset.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>CSM Case Automation Schedulers</relationshipLabel>
        <relationshipName>CSM_Case_Automation_Schedulers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Categorization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Categorization</label>
        <referenceTo>CSM_QI_Case_Categorization__c</referenceTo>
        <relationshipLabel>CSM Case Automation Schedulers</relationshipLabel>
        <relationshipName>CSM_Case_Automation_Schedulers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FrequencyId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FrequencyId</label>
        <referenceTo>CSM_QI_Frequency__c</referenceTo>
        <relationshipLabel>CSM Case Automation Schedulers</relationshipLabel>
        <relationshipName>CSM_Case_Automation_Schedulers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <defaultValue>(&quot;None&quot;)</defaultValue>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <defaultValue>(&quot;Technology Solutions&quot;)</defaultValue>
        <label>Pillar</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CSM_Case_Automation_Schedulers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CSM_Case_Automation_Schedulers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <description>Additional field to record Subtype1 for categorization data</description>
        <label>SubType1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <description>Additional field to record Subtype2 for categorization data</description>
        <label>SubType2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType3__c</fullName>
        <description>Additional field to record Subtype3 for categorization data</description>
        <label>SubType3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSM Case Automation Scheduler</label>
    <nameField>
        <displayFormat>CAS-{000000000}</displayFormat>
        <label>CSM Case Automation Scheduler Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSM Case Automation Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSM_QI_Frequency__c.object
<CustomObject>
    <description>CSM-1039 TECH-CSM Case Automation Scheduler</description>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weekday__c</fullName>
        <label>Weekday</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Frequency</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frequencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
    <fields>
        <fullName>Pillar__c</fullName>
        <description>CSM-1809: All - User Queue Enhancements</description>
        <formula>CASE(1,IF(BEGINS(LOWER(Name), &apos;data&apos;),1,0), &apos;Information Offering&apos;, IF(BEGINS(LOWER(Name), &apos;rnd&apos;),1,0), &apos;R&amp;D&apos;, IF(BEGINS(LOWER(Name), &apos;tech&apos;),1,0), &apos;Technology Solutions&apos;,&apos;&apos;)</formula>
        <label>Pillar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueueName__c</fullName>
        <description>CSM - ACN - S-0007 - Queue Name</description>
        <label>Queue Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Q1</fullName>
                </value>
                <value>
                    <fullName>Q2</fullName>
                </value>
                <value>
                    <fullName>Q3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TECH_QueueUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TECH_QueueUser</label>
        <referenceTo>Queue_User_Relationship__c</referenceTo>
        <relationshipLabel>Queue User Relationship</relationshipLabel>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM - ACN - S-0007 - User Lookup</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Request_Ticket_Number__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Ticket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_DAO_CaseAutomationScheduler.cls
@isTest
private class TST_DAO_CaseAutomationScheduler {

    @testSetup
    private static void dataSetup(){
        Product2 productRecord = UTL_TestData.createProduct();
        insert productRecord;
        Account accRecord = UTL_TestData.createAccount();
        insert accRecord;
        Asset assetRecord = new Asset(Name = 'TestAsset', AccountId = accRecord.Id, Product2Id = productRecord.Id);
        insert assetRecord;
        Id techRecordTypeId =  Schema.SObjectType.Case.getRecordTypeInfosByName().get('TechnologyCase').getRecordTypeId();
        CSM_QI_Case_Categorization__c categorization = new CSM_QI_Case_Categorization__c(Product__c = productRecord.Id, SubType1__c = 'TestSubtype1', 
                                                                                         SubType2__c = 'TestSubtype2 2', SubType3__c = 'TestSubtype3 2', 
                                                                                         RecordTypeId__c = techRecordTypeId, Pillar__c = CON_CSM.S_TECHNOLOGY_SOLUTIONS, Type__c = 'Categorization');
        insert categorization;
    }
    
    @isTest
    static void testSetPrimaryAndSecondaryCurrentQueue(){
        Account accRecord = [SELECT Id FROM Account LIMIT 1];
        Product2 prodRecord = [SELECT Id FROM Product2 LIMIT 1];
        Asset assetRecord = [SELECT Id FROM Asset LIMIT 1];
        CSM_QI_Case_Categorization__c caseCatRecord = [SELECT Id FROM CSM_QI_Case_Categorization__c LIMIT 1];
        UserRole portalRole = [SELECT Id FROM UserRole WHERE DeveloperName = 'CSM' LIMIT 1];
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User adminUser = New User(Alias = 'su', UserRoleId = portalRole.Id, ProfileId = adminProfile.Id, Email = 'adminUser12@iqvia.com', IsActive =true , Username ='adminUser12@iqvia.com.csm', 
                                  LastName= 'testLastName', EmployeeNumber='4345702', CommunityNickname ='testSuNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
                                  LanguageLocaleKey='en_US', Change_Request_Description__c = 'test', Change_Request_Ticket_Number__c ='test description');
        insert adminUser;
        System.runAs(adminUser){
            Queue_User_Relationship__c queue = new Queue_User_Relationship__c();
            queue.Name ='Tech Queue';
            queue.QueueName__c ='Tech Queue';
            queue.Type__c ='Queue';
            insert queue;
            Queue_User_Relationship__c queueUser1 = new Queue_User_Relationship__c();
            queueUser1.Name ='Tech Queue';
            queueUser1.QueueName__c ='Tech Queue';
            queueUser1.Type__c ='User';
            queueUser1.TECH_QueueUser__c = queue.id;
            queueUser1.User__c = UserInfo.getUserId();
            insert queueUser1;
            Queue_User_Relationship__c queueUser2 = new Queue_User_Relationship__c();
            queueUser2.Name ='Tech Queue';
            queueUser2.QueueName__c ='Tech Queue';
            queueUser2.Type__c ='User';
            queueUser2.TECH_QueueUser__c = queue.id;
            queueUser2.User__c = adminUser.Id;
            insert queueUser2;
            
            CSM_QI_CaseAutomationScheduler__c caseAutoRecord = new CSM_QI_CaseAutomationScheduler__c();
            caseAutoRecord.Account_Name__c = accRecord.Id;
            caseAutoRecord.Frequency__c = 'Daily';
            caseAutoRecord.Subject__c = 'Test subject';
            caseAutoRecord.Description__c = 'Test description';
            caseAutoRecord.Primary_Owner__c = UserInfo.getUserId();
            caseAutoRecord.Secondary_Owner__c = adminUser.Id;
            caseAutoRecord.Start_Date__c = Date.today();
            caseAutoRecord.Asset_Name__c = assetRecord.Id;
            
            Test.startTest();
            insert caseAutoRecord;
            
            caseAutoRecord.Case_Categorization__c = caseCatRecord.Id;
            CSM_QI_Frequency__c freqRecord = new CSM_QI_Frequency__c();
            freqRecord.Frequency__c = 'Weekly';
            freqRecord.Weekday__c = 'Wednesday';
            insert freqRecord;
            caseAutoRecord.FrequencyId__c = freqRecord.Id;
            update caseAutoRecord;
            caseAutoRecord.Active__c = True;
            update caseAutoRecord;
            Test.stopTest();
        }
    }
}