src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shared_Folder_Type__c</fullName>
        <label>Shared Folder Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Local Account</fullName>
                </value>
                <value>
                    <fullName>Parent Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Case_Type__c</fullName>
        <label>Portal Case Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Information Offering</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Technology Solutions</fullName>
                </value>
                <value>
                    <fullName>DATA</fullName>
                    <isActive>false</isActive>
                    <label>DATA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>CSM-ACN-S-0062 - Field to define the source</description>
        <label>Source</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_QI_Data_Portal_Queue_User_details__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Data Portal Queue User details</relationshipLabel>
        <relationshipName>Data_Portal_Queue_User_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Current_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Current Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseRecordType__c</fullName>
        <label>Case Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ActivityPlan</fullName>
                </value>
                <value>
                    <fullName>DATACase</fullName>
                </value>
                <value>
                    <fullName>TechnologyCase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queue_User_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue User Relationship</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Queue_User_Relationship__c.Type__c</field>
                <operation>equals</operation>
                <value>Queue</value>
            </filterItems>
            <infoMessage>Please Select the Queue user Relationship type as queue</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Queue_User_Relationship__c</referenceTo>
        <relationshipLabel>Data Portal Queue User details</relationshipLabel>
        <relationshipName>Data_Portal_Queue_User_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>CSM-1116 Product Segregation to show only selected product to CSH User in Customer Service Hub. differentiate the CSH queue assignment and Product restriction functionality in CSH</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queue Assignment</fullName>
                    <default>true</default>
                    <label>Queue Assignment</label>
                </value>
                <value>
                    <fullName>Product Level Restriction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Portal Queue User details</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>CSM QI Data Portal  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Portal Queue User details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSM_QI_View_Stat__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CSM View Stats</relationshipLabel>
        <relationshipName>CSM_View_Stats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObjectApiName__c</fullName>
        <label>ObjectApiName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSH</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>PRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSM View Stat</label>
    <nameField>
        <displayFormat>VS-{0000000000}</displayFormat>
        <label>CSM View Stat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSM View Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Community_Topics__c</fullName>
        <label>Community Topics</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Topics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecificToCSM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM - ACN - S0024 - Specific to CSM?</description>
        <label>Specific to CSM?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM - ACN - S-0007 - User Lookup</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Request_Ticket_Number__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Ticket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Community_Topics.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ADA</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for CLM for Nexxus MI</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for CLM for OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for ePromo</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for Kadrige iDetailing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for Kadrige iSharing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for OCE Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Spend 360</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Spend 360 - US</fullName>
    </customValue>
    <customValue>
        <fullName>Audits Nationaux Ethiques</fullName>
    </customValue>
    <customValue>
        <fullName>Business Rules &amp; Processes</fullName>
    </customValue>
    <customValue>
        <fullName>CLM Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>CLM For Nexxus MI</fullName>
    </customValue>
    <customValue>
        <fullName>CLM For OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Connectivity &amp; Wireless</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Health</fullName>
    </customValue>
    <customValue>
        <fullName>Content for Kadrige iDetailing</fullName>
    </customValue>
    <customValue>
        <fullName>CRM Software</fullName>
    </customValue>
    <customValue>
        <fullName>Dashboard (Flex/SFE)</fullName>
    </customValue>
    <customValue>
        <fullName>DataView</fullName>
    </customValue>
    <customValue>
        <fullName>DDD</fullName>
    </customValue>
    <customValue>
        <fullName>EPPM</fullName>
    </customValue>
    <customValue>
        <fullName>ePromo</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware &amp; Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Hospi 360</fullName>
    </customValue>
    <customValue>
        <fullName>IMS One</fullName>
    </customValue>
    <customValue>
        <fullName>Internal &amp; HD Processes</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA CDW</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA Data Connector</fullName>
    </customValue>
    <masterLabel>Community Topics</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_CNT_PEP_PortalFile.cls
/*
 * Version       : 1.0
 * Description   : Test Class for CNT_PEP_PortalFile
 */
@isTest
private class TST_CNT_PEP_PortalFile {
    
    /**
     * This method used to set up testdata
     */ 
    @testSetup
    static void dataSetup() {
                
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        
         
        String profilId2 = [select id from Profile where Name='System Administrator'].Id;
        User accOwner = New User(Alias = 'su',UserRoleId= portalRole.Id, ProfileId = profilId2, Email = 'john2@iqvia.com',IsActive =true ,Username ='john2@iqvia.com', LastName= 'testLastName', CommunityNickname ='testSuNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', Change_Request_Description__c = 'test', Change_Request_Ticket_Number__c ='test description',EmployeeNumber ='08080808');
        insert accOwner;
        
        System.runAs (accOwner) {
        
            Account account = UTL_TestData.createAccount();
            account.ownerId=accOwner.Id;
            account.Shared_Folder_Type__c='Local Account';
            insert account;
            
            Product2 product = UTL_TestData.createProduct();
            product.Community_Topics__c='CLM Agencies';
            product.SpecificToCSM__c = True;
            insert product;
            Queue_User_Relationship__c qurPortal = new Queue_User_Relationship__c(Name = 'Q1',User__c = UserInfo.getUserId(),Type__c = 'Queue');
            insert qurPortal;
            CSM_QI_Data_Portal_Queue_User_details__c dT = new CSM_QI_Data_Portal_Queue_User_details__c();
            dT.Queue_User_Relationship__c = qurPortal.Id;
            dT.Account__c = account.Id;
            dT.All_Current_Users__c = true;
            dT.CaseRecordType__c = 'TechnologyCase';
            dT.Type__c ='Queue Assignment';
            dT.Order__c = 1;
            insert dT;
            CSM_QI_Data_Portal_Queue_User_details__c dd = new CSM_QI_Data_Portal_Queue_User_details__c();
            dd.Queue_User_Relationship__c = qurPortal.Id;
            dd.Account__c = account.Id;
            dd.All_Current_Users__c = true;
            dd.CaseRecordType__c = 'DATACase';
            dd.Type__c ='Queue Assignment';
            dd.Order__c = 1;
            insert dd;
                    
            Asset asset = new Asset(Name = 'TestAsset', AccountId = account.Id, Product2Id = product.id);
            insert asset;
            
            ContentFolder cf = new ContentFolder(Name='TestContentFolder');
            insert cf;
            ContentFolder cf2 = new ContentFolder(Name='TestContentFolder2', ParentContentFolderId=cf.Id );
            insert cf2; 
            
            ContentVersion cv  = new ContentVersion(Title = 'Penguins', PathOnClient = 'Penguins.jpg',  VersionData = Blob.valueOf('Test Content'), IsMajorVersion = true);
            insert cv;  
            
            Topic topic = New Topic(Name = 'CLM Agencies');
            insert topic;

        }
    }
    
    @IsTest
    static void testGetUserAccount() {
        Account acc = [SELECT id FROM Account WHERE Name = 'TestAccount'];
        Contact contact = new Contact( 
            Firstname='Brian', 
            Lastname='Dent', 
            Phone='(619)852-4569', 
            Department='Mission Control', 
            Title='Mission Specialist - Neptune', 
            Email='john@acme.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            AccountId = acc.Id);
        insert contact;
         
        String profilId = [select id from Profile where Name='CSM Customer Community Plus Login User'].Id;
        User user = New User(Alias = 'com', Email = 'john@acme.com',IsActive =true , ContactId = contact.Id, ProfileId = profilId,Username =' john@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US');
        insert user;
            
        Test.startTest();
        List<Account> a = new List<Account>();
        system.runAs(user){
            a = CNT_PEP_PortalFile.getUserAccount();
        }
        Test.stopTest();
        Integer expected = 1;
        Integer actual = a.size();
        System.assertEquals(expected, actual);
    }

    @IsTest
    static void testGetFolderByFolderNameForCurrentUser(){
        Account acc = [SELECT id FROM Account WHERE Name = 'TestAccount'];
        Contact contact = new Contact( 
            Firstname='Brian', 
            Lastname='Dent', 
            Phone='(619)852-4569', 
            Department='Mission Control', 
            Title='Mission Specialist - Neptune', 
            Email='john@acme.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            AccountId = acc.Id);
        insert contact;
         
        String profilId = [select id from Profile where Name='CSM Customer Community Plus Login User'].Id;
        User user = New User(Alias = 'com', Email = 'john@acme.com',IsActive =true , ContactId = contact.Id, ProfileId = profilId,Username =' john@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US');
        insert user;
            
        Test.startTest();
        List<ContentFolder> contentFolders = new List<ContentFolder>();
        system.runAs(user){
            contentFolders = CNT_PEP_PortalFile.getFolderByFolderNameForCurrentUser('TestContentFolder');
        }
        Test.stopTest();
    }

     @IsTest
    static void testGetSharedFolderByUserParentAccount(){
        Account acc = [SELECT id FROM Account WHERE Name = 'TestAccount'];
        Contact contact = new Contact( 
            Firstname='Brian', 
            Lastname='Dent', 
            Phone='(619)852-4569', 
            Department='Mission Control', 
            Title='Mission Specialist - Neptune', 
            Email='john@acme.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            AccountId = acc.Id);
        insert contact;
         
        String profilId = [select id from Profile where Name='CSM Customer Community Plus Login User'].Id;
        User user = New User(Alias = 'com', Email = 'john@acme.com',IsActive =true , ContactId = contact.Id, ProfileId = profilId,Username =' john@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US');
        insert user;
            
        Test.startTest();
        List<ContentFolder> contentFolders = new List<ContentFolder>();
        system.runAs(user){
            contentFolders = CNT_PEP_PortalFile.getSharedFolderByUserParentAccount();
        }

        acc.Shared_Folder_Type__c='';
        update acc;
        system.runAs(user){
            contentFolders = CNT_PEP_PortalFile.getSharedFolderByUserParentAccount();
        }
        Test.stopTest();
    }

    /**
     * This method used to get List of ContentFolder  for current user
     */    
    @IsTest
    static void testGetFolders() {
        List<ContentFolder> contentFolders = new List<ContentFolder>();
        Account acc = [SELECT id FROM Account WHERE Name = 'TestAccount'];
        Contact contact = new Contact( 
            Firstname='Brian', 
            Lastname='Dent', 
            Phone='(619)852-4569', 
            Department='Mission Control', 
            Title='Mission Specialist - Neptune', 
            Email='yourusername@iqvia.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            AccountId = acc.Id);
        insert contact;
         
        String profilId = [select id from Profile where Name='CSM Customer Community Plus Login User'].Id;
        User user = New User(Alias = 'com', Email = 'yourusername@iqvia.com',IsActive =true , ContactId = contact.Id, ProfileId = profilId,Username =' john@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US');
        insert user;
        Test.startTest();
        system.runAs(user){
                contentFolders = CNT_PEP_PortalFile.getFolders();
        }
        Test.stopTest();
        Integer expected = 1;
        Integer actual = contentFolders.size();
        /** System.assertEquals(expected, actual); */
    }
    
    /**
     * This method used to get List<ContentFolder> by TopicId
     */    
    @IsTest
    static void testGetFolderByTopicId() {
        List<ContentFolder> contentFolders = new List<ContentFolder>();
        Topic topic = [SELECT id FROM Topic WHERE Name = 'CLM Agencies'];
        Test.startTest();
        String id = topic.Id;
        contentFolders = CNT_PEP_PortalFile.getFolderByTopicId(id);
        Test.stopTest();
        Integer expected = 1;
        Integer actual = contentFolders.size();
        /** System.assertEquals(expected, actual); */
    }
    
    /**
     * This method used to get List of ContentFolder by parentContentFolderId
     */    
    @IsTest
    static void testGetFoldersByParentId() {
        User partnerUser = TST_PEP_TestDataFactory.createPartnerUser('partneruser@iqvia.partner.com');
        List<ContentFolder> contentFolders = new List<ContentFolder>();
        ContentFolder f = [SELECT id FROM ContentFolder WHERE Name = 'TestContentFolder'];
        System.runas(partnerUser){
        Test.startTest();
        contentFolders = CNT_PEP_PortalFile.getFoldersByParentId(f.Id);
        Test.stopTest();
        Integer expected = 1;
        Integer actual = contentFolders.size();
        }        
       /** System.assertEquals(expected, actual); **/
    }
     
    @IsTest
    static void testGetFolderMemberByParentId() {
        List<ContentFolderMember> contentFolderMembers = new  List<ContentFolderMember>();
        ContentFolder f = [SELECT Id FROM ContentFolder WHERE Name='TestContentFolder'];
        Test.startTest();
        contentFolderMembers = CNT_PEP_PortalFile.getFolderMemberByParentId(f.Id);
        Test.stopTest();
    }
    
    @IsTest
    static void testLogViewStat() {
        List<ContentFolderMember> contentFolderMembers = new  List<ContentFolderMember>();
        ContentFolder f1 = [SELECT Id FROM ContentFolder WHERE Name='TestContentFolder'];
        CSM_QI_View_Stat__c viewStatRecord = new CSM_QI_View_Stat__c();
        String ContentVersionId ;
        viewStatRecord.ObjectApiName__c = f1.id;
        viewStatRecord.Source__c = 'PRM';
        viewStatRecord.Title__c = 'FileTitle';
        insert viewStatRecord;
        Test.startTest();
        CNT_PEP_PortalFile.logViewStat(f1.Id,'OCE Personal');
        Test.stopTest();
    }
}