src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <description>CSM - ACN - S0036 - Account Country</description>
        <label>Account Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Community_User_Feedback__c.object
<CustomObject>
    <description>PRM-110 :  Provide Documentation Feedback on Sales Collateral Section.</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>Will be use to record feedback body</description>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Community User Feedbacks</relationshipLabel>
        <relationshipName>Community_User_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRM_Sales_Collateral__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To differentiate between article type.</description>
        <label>PRM Sales Collateral</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PRM_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Will be use to record the PRM user who submitted the feedback</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Community_User_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>ProductName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSH</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>PRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Will be use to record feedback subject</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>To indicate whether feedback is of article or sales collateral.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>KB Article</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Community User Feedback</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Community User Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community User Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PRM_User__c</fullName>
        <description>PRM-576-To check PRM User</description>
        <label>PRM User</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Case_Type__c</fullName>
        <label>Portal Case Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Information Offering</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Technology Solutions</fullName>
                </value>
                <value>
                    <fullName>DATA</fullName>
                    <isActive>false</isActive>
                    <label>DATA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>CSM-ACN-S-0062 - Field to define preferred language</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Preferred_Language</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>CSM-ACN-S-0062 - Field to define the source</description>
        <label>Source</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1455 - Field value dependent on selected Industry</description>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_case_Trigger_Handler__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CSM-289 to bypass case trigger if custom setting is not enabled</description>
    <fields>
        <fullName>Difference_By_Last_Created_Time_Case__c</fullName>
        <defaultValue>15</defaultValue>
        <description>Used in CAS_FLW_CSM_Case_SendAllEmailAlerts flow to difference bw LastModified Data and CreatedDate in formula field</description>
        <label>Difference By Last Created Time Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Disable_Case_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable Case Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>CSM Case Trigger Handler</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecificToCSM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM - ACN - S0024 - Specific to CSM?</description>
        <label>Specific to CSM?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_CUF_FLW_PEP_CommunityUserFeedback.cls
@isTest
private class TST_CUF_FLW_PEP_CommunityUserFeedback {
    @testSetup
    static void dataSetup() {
        Group g1 = new Group(Name='SendAllEmailAlerts', type='Queue');
        insert g1;
        QueuesObject q1 ;
        system.runAs(new User(id = UserInfo.getUserId())){
            q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Case');
            insert q1;
        }
        CSM_case_Trigger_Handler__c triggerControlSetting = new CSM_case_Trigger_Handler__c(SetupOwnerId=UserInfo.getOrganizationId(),Disable_Case_Trigger__c = true, Name='IQVIA',Difference_By_Last_Created_Time_Case__c = 60);
        insert triggerControlSetting;
        Account acct = new Account(Name = 'TestAccSendAllEmailAlerts',AccountCountry__c = 'BR', CustomerSegment__c = 'GOVERNMENT', Sub_Industry__c = 'STATE');
        insert acct;
        List<Contact> conList = new List<Contact>();
        Contact cont1 = new Contact( FirstName = 'EmailAlertsFirstName', Lastname='EN', Phone='(619)852-4569', Department='Mission Control', 
                                  Title='Mission Specialist - Neptune', Email='SendAllEmailAlertsEN@iqvia.com', AccountId = acct.Id,PreferredLanguage__c = 'en_US', Portal_Case_Type__c = 'Information Offering; Technology Solutions', Contact_User_Type__C = 'Ho User');       
        conList.add(cont1);
        insert conList;
        
        List<Asset> aList = new List<Asset>();
        Product2 p1 = new Product2( Name = 'DDD', Pillar__c = 'Information Offering; Technology Solutions',SpecificToCSM__c = True);
        insert p1;
        Product2 p2 = new Product2(Name = 'Nexxus MI', Pillar__c = 'Technology Solutions',SpecificToCSM__c = True);
        insert p2;
        
        Asset a1 = new Asset(Name = 'DDD', AccountId = acct.Id, Product2Id = p1.id, Status ='Installed');
        aList.add(a1);
        
        Asset a2 = new Asset(Name = 'Nexxus MI', AccountId = acct.Id, Product2Id = p2.id, Status ='Installed');
        aList.add(a2);
        insert aList;
        
        conList = [Select Id, PreferredLanguage__c,Email,Name from Contact where FirstName = 'EmailAlertsFirstName'];
        String profilId = [select id from Profile where Name='PRM Community User'].Id;
        User user = null;
        List<User> lstUser = new List<User>();
        User autoUser = [select Id,Name from user where Name ='System' Limit 1 ];
        for(Contact con : conList){
            user = new User(Alias = 'as'+con.PreferredLanguage__c, Email = con.Email ,IsActive =true , ContactId = con.Id, ProfileId = profilId,Username =con.Email, LastName= con.Name, CommunityNickname =con.PreferredLanguage__c, TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US');
            lstUser.add(user);
        }
        insert lstUser;
        List<Community_User_Feedback__c> cufList = new List<Community_User_Feedback__c>();
        Community_User_Feedback__c cuf1 = new Community_User_Feedback__c();
        cuf1.Subject__c = 'TST_CAS_FLW_CSM_Case_SendAllEmailAlerts:Agent ';
        cuf1.Body__c = 'Test Body';
        cuf1.Contact__c =  cont1.id;
        cuf1.ProductName__c = p1.id;
        cuf1.PRM_User__c = User.id;
        cuf1.Type__c = 'File';
        cuf1.PRM_Sales_Collateral__c = True; 
        cuf1.Source__c = 'PRM';
        cufList.add(cuf1);
        Community_User_Feedback__c cuf2 = new Community_User_Feedback__c();
        cuf2.Subject__c = 'TST_CAS_FLW_CSM_Case_SendAllEmailAlerts:Agent ';
        cuf2.Body__c = 'Test Body';
        cuf2.Type__c = 'File';
        cuf2.PRM_Sales_Collateral__c = False;
        cuf2.Source__c = 'PRM';
        cufList.add(cuf2);
        insert cufList;
    }
    
    
    @isTest
    static void testFeedbackFromPortalUser(){
        Test.startTest();
        try{
            List<Community_User_Feedback__c> cuflist = [Select Id,Type__c,PRM_Sales_Collateral__c from Community_User_Feedback__c where Subject__c like 'TST_CUF_FLW_PEP_CommunityUserFeedback:System%'];
            for(Community_User_Feedback__c cs : cuflist){
                cs.Subject__c = 'TST_CAS_FLW_CSM_Case_SendAllEmailAlerts:Agent ';
                cs.Type__c = 'File';
                cs.PRM_Sales_Collateral__c = True;
                cs.Body__c = 'Test Body';
				cs.Source__c = 'PRM';
                
            }
            insert cuflist;
        }
        catch(Exception ex){
            
        }
        
        Test.stopTest();
    }
    
    @isTest
    static void testFeedbackFromPortalUser1(){
        Test.startTest();
        try{
            List<Community_User_Feedback__c> cuflist = [Select Id,Type__c,PRM_Sales_Collateral__c,Source__c from Community_User_Feedback__c where Subject__c like 'TST_CUF_FLW_PEP_CommunityUserFeedback:System%'];
            for(Community_User_Feedback__c cs : cuflist){
                cs.Subject__c = 'TST_CAS_FLW_CSM_Case_SendAllEmailAlerts:Agent ';
                cs.Type__c = 'Test Comment ';
                cs.PRM_Sales_Collateral__c = True;
                
            }
            update cuflist;
        }
        catch(Exception ex){
            
        }
        
        Test.stopTest();
    }

}