src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <description>CSM - ACN - S0036 - Account Country</description>
        <label>Account Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RDCategorization__c</fullName>
        <description>CSM-ACN-S-0036 - Picklist field with values Sponsor,Site, Internal, External</description>
        <label>R&amp;D Categorization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sponsor</fullName>
                </value>
                <value>
                    <fullName>Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_QI_Case_Categorization__c.object
<CustomObject>
    <fields>
        <fullName>LOS__c</fullName>
        <label>LOS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Categorization</relationshipLabel>
        <relationshipName>Case_Categorization</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <label>Sub-Type 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <label>Sub-Type 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType3__c</fullName>
        <label>Sub-Type 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Categorization</fullName>
                </value>
                <value>
                    <fullName>Activity</fullName>
                </value>
                <value>
                    <fullName>Knowledge</fullName>
                </value>
                <value>
                    <fullName>CountryReqBusinessHour</fullName>
                </value>
                <value>
                    <fullName>Product Level Restriction</fullName>
                </value>
                <value>
                    <fullName>Affects Version</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Categorization</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Case Categorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Categorization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
    <fields>
        <fullName>LOS__c</fullName>
        <description>CSM-537</description>
        <label>LOS</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>R_D_E2C_LOS</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <description>CSM-1809: All - User Queue Enhancements</description>
        <formula>CASE(1,IF(BEGINS(LOWER(Name), &apos;data&apos;),1,0), &apos;Information Offering&apos;, IF(BEGINS(LOWER(Name), &apos;rnd&apos;),1,0), &apos;R&amp;D&apos;, IF(BEGINS(LOWER(Name), &apos;tech&apos;),1,0), &apos;Technology Solutions&apos;,&apos;&apos;)</formula>
        <label>Pillar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueueName__c</fullName>
        <description>CSM - ACN - S-0007 - Queue Name</description>
        <label>Queue Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Q1</fullName>
                </value>
                <value>
                    <fullName>Q2</fullName>
                </value>
                <value>
                    <fullName>Q3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM - ACN - S-0007 - User Lookup</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/R_D_E2C_LOS.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Account Management</fullName>
    </customValue>
    <customValue>
        <fullName>CD-CSS</fullName>
    </customValue>
    <customValue>
        <fullName>CRC Lab</fullName>
    </customValue>
    <customValue>
        <fullName>EDC Support</fullName>
    </customValue>
    <customValue>
        <fullName>Emergency</fullName>
    </customValue>
    <customValue>
        <fullName>Infosario - QCC</fullName>
    </customValue>
    <customValue>
        <fullName>Infosario Veeva Support</fullName>
    </customValue>
    <customValue>
        <fullName>Public Triage</fullName>
    </customValue>
    <customValue>
        <fullName>Q² Investigator Site Support</fullName>
    </customValue>
    <customValue>
        <fullName>Q² Lab Investigator Services</fullName>
    </customValue>
    <customValue>
        <fullName>Registry Support</fullName>
    </customValue>
    <description>CSM-537</description>
    <masterLabel>R&amp;D E2C LOS</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_CNT_CSM_EmailMessageController.cls
@isTest
private class TST_CNT_CSM_EmailMessageController {

    @testSetup
    static void dataSetup(){
        Product2 product = UTL_TestData.createProduct();
        insert product;
        Account account = UTL_TestData.createAccount();
        insert account;
        Asset asset = new Asset(Name = 'TestAsset', AccountId = account.Id, Product2Id = product.id);
        insert asset;
        Contact contact = UTL_TestData.createContact(account.Id);
        contact.Contact_User_Type__c = 'HO User';
        insert contact;

        Id recordType =  Schema.SObjectType.Case.getRecordTypeInfosByName().get('TechnologyCase').getRecordTypeId();
       
        CSM_QI_Case_Categorization__c categorization = new CSM_QI_Case_Categorization__c(Product__c = product.Id, SubType1__c='TestSubtype1', SubType2__c='TestSubtype2 1',SubType3__c='TestSubtype3 1',RecordTypeId__c=recordType);
        categorization.Pillar__c = 'Information Offering';
        insert categorization;
        categorization = new CSM_QI_Case_Categorization__c(Product__c = product.Id, SubType1__c='TestSubtype1', SubType2__c='TestSubtype2 2',SubType3__c='TestSubtype3 2',RecordTypeId__c=recordType);
        categorization.Pillar__c = 'Technology Solutions';
        insert categorization;
        
        categorization = new CSM_QI_Case_Categorization__c(Los__c ='Los' ,SubType1__c='TestSubtype1', SubType2__c='TestSubtype22',SubType3__c='TestSubtype33',RecordTypeId__c='0126A000000hC34QAE');
        categorization.Pillar__c = 'Technology Solutions';
        insert categorization;
        
        Queue_User_Relationship__c queues=new Queue_User_Relationship__c();
        queues.Name ='Q1';
        queues.QueueName__c ='Q1';
        queues.Type__c ='Queue';
        queues.User__c = UserInfo.getUserId();
        insert queues;
        Queue_User_Relationship__c queueUser=new Queue_User_Relationship__c();
        queueUser.Name ='Q1';
        queueUser.QueueName__c ='Q1';
        queueUser.Type__c ='User';
        queueUser.User__c = UserInfo.getUserId();
        insert queueUser;
        Case c = New Case(Subject = 'TestCase', RecordTypeId=recordType, ContactId = contact.Id, AccountId = account.Id, Status = 'New', Priority = 'Medium', Origin = 'Email',CurrentQueue__c=queues.Id, InitialQueue__c = 'Q1');
        insert c;
        
        EmailMessage mailRecord = new EmailMessage();
        mailRecord.CcAddress = 'testuser1@mail.com';
        mailRecord.CreatedById = UserInfo.getUserId();
        mailRecord.CreatedDate = Datetime.now();
        mailRecord.ParentId = c.Id;
        mailRecord.ToAddress = 'testuser2@mail.com';
        mailRecord.FromAddress = 'no.reply.support@iqvia.com';
        mailRecord.Incoming = true;
        mailRecord.Subject = 'Test Subject {!Case.CaseNumber}';
        mailRecord.HtmlBody = '<p>Test Body {!Contact.FirstName}</p><p>Thanks</br>{!User.FirstName}</p>';
        insert mailRecord;
    }
    
    @isTest
    private static void testGetEmailMessages(){
        EmailMessage mailRecord = [SELECT Id FROM EmailMessage LIMIT 1];
        Test.startTest();
        CNT_CSM_EmailMessageController.getEmailMessages(mailRecord.Id);
        Test.stopTest();
    }
    
    @isTest
    private static void testGetParentDetails(){
        EmailMessage mailRecord = [SELECT Id, ParentId FROM EmailMessage LIMIT 1];
        Test.startTest();
        CNT_CSM_EmailMessageController.getParentDetails(mailRecord.ParentId);
        Test.stopTest();
    }
    
    @isTest
    private static void testGetQueueRelatedEmailAddress(){
        Case caseRecord = [SELECT Id, RecordTypeId FROM Case LIMIT 1];
        Test.startTest();
        CNT_CSM_EmailMessageController.getQueueRelatedEmailAddress('DATA', caseRecord.RecordTypeId, 'Q1');
        CNT_CSM_EmailMessageController.getQueueRelatedEmailAddress('DATA', '0126A000000hC33QAE', 'Data Global E-service');
        Test.stopTest();
    }
    
    @isTest
    private static void testSendMailToUsers(){
        EmailMessage mailRecord = [SELECT Id, ParentId, FromAddress, ToAddress, CcAddress, BccAddress, Subject, HtmlBody FROM EmailMessage LIMIT 1];
        Test.startTest();
        CNT_CSM_EmailMessageController.sendMailToUsers(mailRecord.FromAddress, mailRecord.ToAddress, mailRecord.CcAddress, mailRecord.BccAddress, mailRecord.Subject, mailRecord.HtmlBody, mailRecord.ParentId, new List<Id>(), mailRecord.Id);
        Test.stopTest();
    }
    
    @isTest
    private static void testLoadDataForAttachment(){
        Test.startTest();
        CNT_CSM_EmailMessageController.loadDataForAttachment('Owned');
        Test.stopTest();
    }
    
    @isTest
    private static void testLoadEmailTemplatesForMail(){
        Test.startTest();
        CNT_CSM_EmailMessageController.loadEmailTemplatesForMail('Classic', '');
        CNT_CSM_EmailMessageController.loadEmailTemplatesForMail('Classic', '00l6A000000S42LQAS');
        CNT_CSM_EmailMessageController.loadEmailTemplatesForMail('AllLightning', UserInfo.getUserId());
        CNT_CSM_EmailMessageController.loadEmailTemplatesForMail('AllLightning', '');
        CNT_CSM_EmailMessageController.loadEmailTemplatesForMail('MyLightning', '');
        CNT_CSM_EmailMessageController.loadEmailTemplatesForMail('MyLightning', UserInfo.getUserId());
        CNT_CSM_EmailMessageController.loadEmailTemplatesForMail('SampleLightning', '');
        CNT_CSM_EmailMessageController.loadEmailTemplatesForMail('SampleLightning', UserInfo.getUserId());
        Test.stopTest();
    }
    
    @isTest
    private static void testAddTemplateDataInMail(){
        Test.startTest();
        CNT_CSM_EmailMessageController.addTemplateDataInMail('00X6A000000Iuac');
        Test.stopTest();
    }
    
    @isTest
    private static void testGetOrgWideDefaultQueues(){
        Test.startTest();
        CNT_CSM_EmailMessageController.getOrgWideDefaultQueues();
        Test.stopTest();
    }
    
    @isTest
    private static void testGetFolderDetailsForTemplates(){
        Test.startTest();
        CNT_CSM_EmailMessageController.getFolderDetailsForTemplates('Classic');
        CNT_CSM_EmailMessageController.getFolderDetailsForTemplates('MyLightning');
        Test.stopTest();
    }
    
    @isTest
    private static void testGetContactLeadUserDetails(){
        Test.startTest();
        CNT_CSM_EmailMessageController.getContactLeadUserDetails('Alex');
        CNT_CSM_EmailMessageController.getContactLeadUserDetails('john.doe');
        Test.stopTest();
    }
    
    @isTest
    private static void testGetRecordRelatedToFields(){
        Test.startTest();
        
        Map<String, List<String>> objectMap = new Map<String, List<String>>();
        List<String> fieldList1 = new List<String>();
        fieldList1.add('CaseNumber');
        fieldList1.add('Subject');
        fieldList1.add('Status');
        objectMap.put('Case', fieldList1);
        List<String> fieldList2 = new List<String>();
        fieldList2.add('Name');
        fieldList2.add('AccountCountry__c');
        fieldList2.add('RDCategorization__c');
        objectMap.put('Account', fieldList2);
        List<String> fieldList3 = new List<String>();
        fieldList3.add('FirstName');
        fieldList3.add('LastName');
        fieldList3.add('Email');
        objectMap.put('Contact', fieldList3);
        List<String> fieldList4 = new List<String>();
        fieldList4.add('FirstName');
        fieldList4.add('LastName');
        objectMap.put('User', fieldList4);
        Case caseRecord = [SELECT Id FROM Case LIMIT 1];
        CNT_CSM_EmailMessageController.getRecordRelatedToFields(objectMap, caseRecord.Id);
        Test.stopTest();
    }
}