src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Accounts are validated against SAP to ensure a match and to prevent duplication of accounts. &quot;New&quot; indicates that the account has not yet been validated against SAP, &quot;SAP Validated&quot; means that it should exist as a ParentAccount on SAP</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>SAP Validated</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Study__c.object
<CustomObject>
    <description>CSM-ACN-S-0124 - Custom Object study.</description>
    <fields>
        <fullName>LOS__c</fullName>
        <description>CSM-ACN-S-0124 - Picklist field that holds value for LOS.</description>
        <label>LOS</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AccounManagement</fullName>
                    <label>Account Management</label>
                </value>
                <value>
                    <fullName>Registry Support</fullName>
                </value>
                <value>
                    <fullName>Q² Lab Investigator Services</fullName>
                </value>
                <value>
                    <fullName>Emergency Triage and Unbinding</fullName>
                </value>
                <value>
                    <fullName>EDC Support</fullName>
                </value>
                <value>
                    <fullName>Cardiac Safety Services &amp; Connected Devices</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CSM-ACN-S-0124 - Picklist field Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                    <isActive>false</isActive>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                    <isActive>false</isActive>
                    <label>Cancelled</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <isActive>false</isActive>
                    <label>Complete</label>
                </value>
                <value>
                    <fullName>Data Lock</fullName>
                    <isActive>false</isActive>
                    <label>Data Lock</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                    <isActive>false</isActive>
                    <label>On hold</label>
                </value>
                <value>
                    <fullName>Production (Live)</fullName>
                    <isActive>false</isActive>
                    <label>Production (Live)</label>
                </value>
                <value>
                    <fullName>Set-up/Revision</fullName>
                    <isActive>false</isActive>
                    <label>Set-up/Revision</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Study</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Study_Site_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S0124 - Study Site Relationship</description>
    <fields>
        <fullName>Comment__c</fullName>
        <description>CSM - ACN - S0214 - Comment</description>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KeyContacts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM-ACN-S-0124 - Lookup field with object Contact</description>
        <label>Key Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Study Site Relationships</relationshipLabel>
        <relationshipName>Study_Site_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LOS__c</fullName>
        <description>CSM - ACN - S0124 - LOS</description>
        <label>LOS</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteNumber__c</fullName>
        <description>CSM - ACN - S0124 - Site #</description>
        <label>Site #</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <description>CSM - ACN - S0124 - Master lookup field that filters account of type R&amp;D Clinical site</description>
        <label>Site</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Account is not of type Clinical Site</errorMessage>
            <filterItems>
                <field>Account.RDCategorization__c</field>
                <operation>equals</operation>
                <value>Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Study Site Relationships</relationshipLabel>
        <relationshipName>Study_Site_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SpecificLocationDetails__c</fullName>
        <description>CSM-ACN-S-0124 - Field that will hold the value Specific Location Details, Format: Long Text ares</description>
        <inlineHelpText>Indicate here the details about the internal site location. E.g. room C, floor 4, etc</inlineHelpText>
        <label>Specific Location Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CSM - ACN - S0124 - Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In-Active</fullName>
                </value>
                <value>
                    <fullName>Active-Connectivity</fullName>
                    <isActive>false</isActive>
                    <label>Active-Connectivity</label>
                </value>
                <value>
                    <fullName>Active-Provision&amp;Connectivity</fullName>
                    <isActive>false</isActive>
                    <label>Active-Provision&amp;Connectivity</label>
                </value>
                <value>
                    <fullName>Active-Provisioned</fullName>
                    <isActive>false</isActive>
                    <label>Active-Provisioned</label>
                </value>
                <value>
                    <fullName>Awaiting Sponsor Action</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Sponsor Action</label>
                </value>
                <value>
                    <fullName>Candidate</fullName>
                    <isActive>false</isActive>
                    <label>Candidate</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Enrolling</fullName>
                    <isActive>false</isActive>
                    <label>Enrolling</label>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                    <isActive>false</isActive>
                    <label>Escalated</label>
                </value>
                <value>
                    <fullName>Failed - Computer</fullName>
                    <isActive>false</isActive>
                    <label>Failed - Computer</label>
                </value>
                <value>
                    <fullName>Failed - Connectivity</fullName>
                    <isActive>false</isActive>
                    <label>Failed - Connectivity</label>
                </value>
                <value>
                    <fullName>Failed - HW and connectivity</fullName>
                    <isActive>false</isActive>
                    <label>Failed - HW and connectivity</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                    <isActive>false</isActive>
                    <label>Initiated</label>
                </value>
                <value>
                    <fullName>Not Initiated</fullName>
                    <isActive>false</isActive>
                    <label>Not Initiated</label>
                </value>
                <value>
                    <fullName>Not Participating</fullName>
                    <isActive>false</isActive>
                    <label>Not Participating</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                    <isActive>false</isActive>
                    <label>On Hold</label>
                </value>
                <value>
                    <fullName>Passed</fullName>
                    <isActive>false</isActive>
                    <label>Passed</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                    <isActive>false</isActive>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                    <isActive>false</isActive>
                    <label>Terminated</label>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                    <isActive>false</isActive>
                    <label>Unresponsive</label>
                </value>
                <value>
                    <fullName>Verified</fullName>
                    <isActive>false</isActive>
                    <label>Verified</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StudyTherapeuticArea__c</fullName>
        <formula>TEXT( Study__r.TherapeuticArea__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Study Therapeutic Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <description>CSM - ACN - S0124 - Study</description>
        <label>Study</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipLabel>Study Site Relationships</relationshipLabel>
        <relationshipName>Study_Site_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Site Relationship</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>SS Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Site Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_TGR_StudySiteRelationship.cls
@isTest
private class TST_TGR_StudySiteRelationship {
    /**
    * This method is used to setup data for all methods.
    */
    @testSetup
    static void dataSetup() {
        Account acc  =  CSM_Util.createAccount();
        insert acc;
        Account acc1  =  CSM_Util.createRDAccount();
        insert acc1;
        Contact cnt  =  CSM_Util.createContact(acc.Id,'CaseTestContact');
        insert cnt;
        
    }

    /**
    * This test method used for insert and update Case record
    */ 
    static testMethod void testAuditforStudySiteRelationship() {
        CNT_CSM_FieldHistoryTracking.saveFields('Study_Site_Relationship__c','Comment__c,CurrencyIsoCode,KeyContacts__c,LOS__c,RecordTypeId,Site__c,SiteNumber__c,SpecificLocationDetails__c,Status__c,Study__c,StudyTherapeuticArea__c,SystemModstamp');
        Account acc  =  [SELECT Id, Name FROM Account WHERE Name  =  'CaseTestAccount' LIMIT 1];
         Account acc1  =  [SELECT Id, Name FROM Account WHERE Name  =  'CaseRDTestAccount' LIMIT 1];
        Contact cnt  =  [SELECT Id, Name FROM Contact WHERE Name  =  'CaseTestContact CaseTestContact' LIMIT 1];
        Contact cnt2  =  CSM_Util.createContact(acc.Id,'CaseTestContact2');
        insert cnt2;
        Study__c study = CSM_Util.createStudy(acc1.Id);
        insert study;
         Study_Site_Relationship__c siteR = CSM_Util.createStudySiteRelationship(acc.Id,study.Id ,cnt.Id);
        
        Test.startTest();
        insert siteR;

        siteR.Comment__c = 'Test Comment';
        siteR.KeyContacts__c = cnt2.Id;
        siteR.Status__c = 'In-Active';
        siteR.LOS__c = 'LOS Test';
        siteR.SpecificLocationDetails__c = 'Specific Location Details';
        update siteR;
        siteR.Comment__c = null;
        siteR.KeyContacts__c = null;
        siteR.Status__c = 'Active';
        siteR.LOS__c = 'LOS Test 1';
        siteR.SpecificLocationDetails__c = 'Specific Location Details 1';
           update siteR;
        siteR.LOS__c = null;
         siteR.KeyContacts__c = cnt.Id;
        siteR.SpecificLocationDetails__c = 'Specific Location Details 1';
           update siteR;        
       
        Test.stopTest();
    }
}