src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_IMS__c</fullName>
        <inlineHelpText>The individual industry sub types we deal with in and outside of pharma.</inlineHelpText>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PHARMA</fullName>
                </value>
                <value>
                    <fullName>CONSUMER HEALTH</fullName>
                </value>
                <value>
                    <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
                </value>
                <value>
                    <fullName>SUPPLIERS TO PHARMA</fullName>
                </value>
                <value>
                    <fullName>INFORMATION &amp; SERVICE PROVIDERS</fullName>
                </value>
                <value>
                    <fullName>FINANCIAL COMMUNITY</fullName>
                </value>
                <value>
                    <fullName>INTERMEDIARIES &amp; DISTRIBUTORS</fullName>
                </value>
                <value>
                    <fullName>GOVERNMENT</fullName>
                </value>
                <value>
                    <fullName>PAYERS</fullName>
                </value>
                <value>
                    <fullName>PROVIDERS</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATIONS</fullName>
                </value>
                <value>
                    <fullName>NON PROFIT</fullName>
                </value>
                <value>
                    <fullName>VETERINARY</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_Territory__c</fullName>
        <inlineHelpText>Pick the Geographical Territory that this account pertains to from the list. 
Only use the &quot;IMS Operations&quot; item (last one in the list) for the creation of Global Accounts.</inlineHelpText>
        <label>Territory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Cote d&apos;Ivoire</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <description>SCM-MC-RSOW#- A custom object of Agreement for SCM</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agreement_Term__c</fullName>
        <label>Agreement Term</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Evergreen</fullName>
                </value>
                <value>
                    <fullName>Ad-Hoc</fullName>
                </value>
                <value>
                    <fullName>Fixed Term</fullName>
                </value>
                <value>
                    <fullName>Auto renew</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Signed_Date__c</fullName>
        <description>Date when internal signatory signed</description>
        <label>Company Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Information Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Master Agreement of Consulting</fullName>
                </value>
                <value>
                    <fullName>Master Agreement of Services</fullName>
                </value>
                <value>
                    <fullName>Memorandum</fullName>
                </value>
                <value>
                    <fullName>Agreement</fullName>
                </value>
                <value>
                    <fullName>Order Form</fullName>
                </value>
                <value>
                    <fullName>Third Party Access Agreement</fullName>
                </value>
                <value>
                    <fullName>Co-promotion Agreement</fullName>
                </value>
                <value>
                    <fullName>Non Disclosure Agreement</fullName>
                </value>
                <value>
                    <fullName>Personal Information Protection Agreement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Related_Opportunity_Agreement</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCM Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCM Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Management_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Perform_SCM_Functions_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Perform SCM Functions Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract Management Setting</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Budget_Available__c</fullName>
        <label>Budget Available</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <description>MC_CRM_ESPSFDCQI-11_The actual contract Start Date (for multi-years this should always be the Contract dates and not change annually in case of a renewal)</description>
        <inlineHelpText>The actual contract Start Date (for multi-years this should always be the Contract dates and not change annually in case of a renewal)</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Master Agreement</fullName>
                </value>
                <value>
                    <fullName>C&amp;S Master Service Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>pse__Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>pse__Region__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/pse__Region__c.object
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <fields>
        <fullName>pse__Hierarchy_Depth__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hierarchy Depth</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Request_Ticket_Number__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Ticket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_SCM_NewAggOverrideExt.cls
@isTest
private class TST_SCM_NewAggOverrideExt {
	private static User testUser;
    private static Opportunity testOpportunity;
    private static Account testAccount;
    private static SCM_NewAggOverrideExt scmAggOverrideExt;
    private static Agreement__c testAgreement;
    private static void setUpData(){
        List<Account> testAccounts = new List<Account>();
        testAccount = new Account(Name = 'TestAccountNameForSCM1',CurrencyIsoCode = 'USD',
            Region_Territory__c = 'India',Industry_IMS__c = 'Biotech',CustomerSegment__c = 'GOVERNMENT',Sub_Industry__c = 'STATE');
        testAccounts.add(testAccount);
        insert testAccounts;
        
        insert new pse__Region__c(name='xz',pse__Hierarchy_Depth__c = 0);   
        List<User> listOfUsers = new List<User>();
        List<Profile> profiles = [select id from profile where name = 'System Administrator']; 
        testUser = new User(FirstName = 'testM',LastName = 'testM',Username = 'testSCM'+Math.random()+'@metacube.com',
                            Email =  'testMetacube@metacube.com',Alias = 'TestUsr1',TimeZoneSidKey = 'America/Los_Angeles',EmployeeNumber='0773'+ String.valueOf(System.currentTimeMillis()),
                            LocaleSidKey = 'en_US',EmailEncodingKey = 'UTF-8',ProfileId = profiles.get(0).id ,LanguageLocaleKey ='en_US',
                            Change_Request_Description__c = 'test', Change_Request_Ticket_Number__c ='test description');
        listOfUsers.add(testUser);
        insert listOfUsers;
        
        testOpportunity = new Opportunity (Name='Default' ,StageName = '2 - Verify Opportunity',
            CloseDate = System.today() ,Budget_Available__c = 'Yes',CurrencyIsoCode = 'USD',Amount = 100.00);
        insert testOpportunity; 
        
        List<Agreement__c> testAgreements = new List<Agreement__c>();
        testAgreement = new Agreement__c(Name ='testAgree2',Account__c = testAccount.id,
            Active__c = false,Company_Signed_Date__c = Date.today(),Contract_Start_Date__c = Date.today().addDays(2),
            Contract_Type__c = 'CES Memorandum',Agreement_Term__c = 'Ad-Hoc',
            Related_Opportunity__c = testOpportunity.Id); 
        testAgreements.add(testAgreement);
        insert testAgreements;
    }
    
    @isTest
    private static void testSCM_NewAggOverrideExtShouldReturnSetAttributesWhenValidParamPassed(){
        setUpData();
        System.runAs(testUser)
        { 
            Contract_Management_Setting__c mycs = Contract_Management_Setting__c.getValues(UserInfo.getUserId());
  
            if(mycs == null) {
              mycs = new Contract_Management_Setting__c(Name= UserInfo.getUserId());
              mycs.Perform_SCM_Functions_Flag__c = true;
              insert mycs;
            }
            setupData();
            Test.startTest();
                PageReference pageRef = Page.SCM_AgreementRecordTypeSelectionPage;
                Test.setCurrentPage(pageRef); 
                ApexPages.currentPage().getParameters().put('oppId',testOpportunity.Id);  
            	ApexPages.currentPage().getParameters().put('AccId',testAccount.Id);  
                scmAggOverrideExt = new SCM_NewAggOverrideExt(
                    new Apexpages.StandardController(testAgreement));
            Test.stopTest();
			
            System.assertNotEquals(null,scmAggOverrideExt.oppRec, 'Opportunity Record is null when not expected');
                        
        } 
    }
    
    @isTest
    private static void testRedirectCustomShouldInsertAgreementWhenFieldValueExists(){
        setUpData();
        System.runAs(testUser)
        { 
            Contract_Management_Setting__c mycs = Contract_Management_Setting__c.getValues(UserInfo.getUserId());
  
            if(mycs == null) {
              mycs = new Contract_Management_Setting__c(Name= UserInfo.getUserId());
              mycs.Perform_SCM_Functions_Flag__c = true;
              insert mycs;
            }
            setupData();
            Test.startTest();
                PageReference pageRef = Page.SCM_AgreementRecordTypeSelectionPage;
                Test.setCurrentPage(pageRef); 
                ApexPages.currentPage().getParameters().put('oppId',testOpportunity.Id);  
            	ApexPages.currentPage().getParameters().put('AccId',testAccount.Id);  
                scmAggOverrideExt = new SCM_NewAggOverrideExt(
                    new Apexpages.StandardController(testAgreement));
            	scmAggOverrideExt.selectedAggRecTypeId = ConstantClass.getRecordTypeId('Agreement__c','Japan Agreement');
            	system.debug(scmAggOverrideExt.selectedAggRecTypeId);
            	PageReference returnedPageRef = scmAggOverrideExt.redirectCustom();
            Test.stopTest();
			
            System.assertNotEquals(null,returnedPageRef, 'There is error in insertion of Agreement');
                        
        } 
    }
    
    @isTest
    private static void testRetShouldReturnPageReferenceWhenOppIdPassed(){
        setUpData();
        System.runAs(testUser)
        { 
            Contract_Management_Setting__c mycs = Contract_Management_Setting__c.getValues(UserInfo.getUserId());
  
            if(mycs == null) {
              mycs = new Contract_Management_Setting__c(Name= UserInfo.getUserId());
              mycs.Perform_SCM_Functions_Flag__c = true;
              insert mycs;
            }
            setupData();
            Test.startTest();
                PageReference pageRef = Page.SCM_AgreementRecordTypeSelectionPage;
                Test.setCurrentPage(pageRef); 
                ApexPages.currentPage().getParameters().put('oppId',testOpportunity.Id);     
                scmAggOverrideExt = new SCM_NewAggOverrideExt(
                    new Apexpages.StandardController(testAgreement));
            	PageReference returnedPageRef = scmAggOverrideExt.ret();
            Test.stopTest();
			
            System.assertNotEquals(null,returnedPageRef, 'returnedPageRef is null when not expected');
                        
        } 
    }
    
    @isTest
    private static void testRetShouldReturnPageReferenceWhenAccountIdPassed(){
        setUpData();
        System.runAs(testUser)
        { 
            Contract_Management_Setting__c mycs = Contract_Management_Setting__c.getValues(UserInfo.getUserId());
  
            if(mycs == null) {
              mycs = new Contract_Management_Setting__c(Name= UserInfo.getUserId());
              mycs.Perform_SCM_Functions_Flag__c = true;
              insert mycs;
            }
            setupData();
            Test.startTest();
                PageReference pageRef = Page.SCM_AgreementRecordTypeSelectionPage;
                Test.setCurrentPage(pageRef); 
                ApexPages.currentPage().getParameters().put('AccId',testAccount.Id);    
                scmAggOverrideExt = new SCM_NewAggOverrideExt(
                    new Apexpages.StandardController(testAgreement));
            	PageReference returnedPageRef = scmAggOverrideExt.ret();
            Test.stopTest();
			
            System.assertNotEquals(null,returnedPageRef, 'returnedPageRef is null when not expected');
                        
        } 
    }
    
    @isTest
    private static void testRetShouldReturnPageReferenceWhenNoIdIsPassed(){
        setUpData();
        System.runAs(testUser)
        { 
            Contract_Management_Setting__c mycs = Contract_Management_Setting__c.getValues(UserInfo.getUserId());
  
            if(mycs == null) {
              mycs = new Contract_Management_Setting__c(Name= UserInfo.getUserId());
              mycs.Perform_SCM_Functions_Flag__c = true;
              insert mycs;
            }
            setupData();
            Test.startTest();
                PageReference pageRef = Page.SCM_AgreementRecordTypeSelectionPage;
                Test.setCurrentPage(pageRef); 
                scmAggOverrideExt = new SCM_NewAggOverrideExt(
                    new Apexpages.StandardController(testAgreement));
            	PageReference returnedPageRef = scmAggOverrideExt.ret();
            Test.stopTest();
			
            System.assertNotEquals(null,returnedPageRef, 'returnedPageRef is null when not expected');
                        
        } 
    }
    
    @isTest
    private static void testGetAggRecordTypesShouldReturnRecordTypeOptionsWhenLoggedInUserIsSysAdm(){
        setUpData();
        System.runAs(testUser)
        { 
            Contract_Management_Setting__c mycs = Contract_Management_Setting__c.getValues(UserInfo.getUserId());
  
            if(mycs == null) {
              mycs = new Contract_Management_Setting__c(Name= UserInfo.getUserId());
              mycs.Perform_SCM_Functions_Flag__c = true;
              insert mycs;
            }
            setupData();
            Test.startTest();
                PageReference pageRef = Page.SCM_AgreementRecordTypeSelectionPage;
                Test.setCurrentPage(pageRef); 
            	ApexPages.currentPage().getParameters().put('oppId',testOpportunity.Id);  
            	ApexPages.currentPage().getParameters().put('AccId',testAccount.Id);
                scmAggOverrideExt = new SCM_NewAggOverrideExt(
                    new Apexpages.StandardController(testAgreement));
            	List<SelectOption> listSelectOption = scmAggOverrideExt.getAggRecordTypes();
            Test.stopTest();
			
            System.assertNotEquals(true,listSelectOption.isEmpty(), 'The returned list is blank when not expected');
                        
        } 
    }
}