src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <description>CSM - ACN - S0036 - Account Country</description>
        <label>Account Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agency_Program__c.object
<CustomObject>
    <description>PRM- Agency Program Catalog</description>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Agency Programs</relationshipLabel>
        <relationshipName>Agency_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Program</label>
    <nameField>
        <label>Partner Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agency_Program_Financials__c.object
<CustomObject>
    <description>PRM- Agency Program Financials</description>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price</description>
        <label>Price</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Product</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Partner Program Financials</relationshipLabel>
        <relationshipName>Agency_Program_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Program Financials</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Partner Program Financials Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Program Financials</pluralLabel>
    <recordTypes>
        <fullName>Price</fullName>
        <active>true</active>
        <description>Price Record Type</description>
        <label>Price</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Agency_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRM Contract management</description>
        <label>Partner Program</label>
        <referenceTo>Agency_Program__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Non_Standard_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non Standard Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification_Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Notification Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRM_Contract_type__c</fullName>
        <description>PRM contract management</description>
        <label>Partner Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Master Agency Agreement</fullName>
                </value>
                <value>
                    <fullName>Agency Program SOW</fullName>
                </value>
                <value>
                    <fullName>Sandbox Agreement</fullName>
                </value>
                <value>
                    <fullName>Non Disclosure Agreement</fullName>
                </value>
                <value>
                    <fullName>Logo/Trademark Agreement</fullName>
                </value>
                <value>
                    <fullName>Data Program</fullName>
                </value>
                <value>
                    <fullName>Master Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Authorized Training Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>A-SI Partner Program Agreement</fullName>
                </value>
                <value>
                    <fullName>Tech Program</fullName>
                </value>
                <value>
                    <fullName>Technical Advisory Services</fullName>
                </value>
                <value>
                    <fullName>One Home for Sites</fullName>
                </value>
                <value>
                    <fullName>Event Sponsorship SOW</fullName>
                    <isActive>false</isActive>
                    <label>Event Sponsorship SOW</label>
                </value>
                <value>
                    <fullName>Training SOW</fullName>
                    <isActive>false</isActive>
                    <label>Training SOW</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <label>Renewal Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Time to Renew</fullName>
                </value>
                <value>
                    <fullName>Renewal Requested</fullName>
                </value>
                <value>
                    <fullName>Renewal Contracting</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SOW_status__c</fullName>
        <label>Signature Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Invoice me</fullName>
                    <isActive>false</isActive>
                    <label>Invoice me</label>
                </value>
                <value>
                    <fullName>Invoice me – with PO</fullName>
                    <isActive>false</isActive>
                    <label>Invoice me – with PO</label>
                </value>
                <value>
                    <fullName>Online Payment</fullName>
                    <isActive>false</isActive>
                    <label>Online Payment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DAOH_Contract_PRM.cls
public class DAOH_Contract_PRM {
    
    public static void updateContract(List<Contract> newList,Map<Id, Contract> oldMap) {
        Set<Id> conId=new Set<Id>();
        for(Contract con:newList)
        {
            if(con.Notification_Counter__c==2 && oldMap.get(con.Id).Notification_Counter__c==1)
            {
                con.Renewal_Status__c='Time to Renew';
            }
            
            if(con.Non_Standard_Contract__c==False && (con.Agency_Program__c!=NULL || con.Agency_Program__c!='') && (con.PRM_Contract_type__c=='Agency Program SOW' || con.PRM_Contract_type__c=='Sandbox Agreement' || con.PRM_Contract_type__c=='Data Program'))
            {
                conId.add(con.Id);
            }
        }
        Set<String> fieldSet=new Set<String>{'AccountId','Agency_Program__c'};
        List<Contract> currentContract=new SLT_Contract().fetchContract(conId, fieldSet);

        if(currentContract.size()>0)
        {
           Set<String> fieldSet1=new Set<String>{'AccountCountry__c'};
            List<Account> acc=new SLT_Account().getAccountCountry(fieldSet1, currentContract[0].AccountId);
            String relatedAgencyId=currentContract[0].Agency_Program__c;
            String country=acc[0].AccountCountry__c;
            Id agencyProgramFinancialsPrice = Schema.SObjectType.Agency_Program_Financials__c.getRecordTypeInfosByDeveloperName().get('Price').getRecordTypeId();
            List<Agency_Program_Financials__c> apfProduct=new SLT_Agency_Program_Financials().getAgencyProgramFinancialsDetails(agencyProgramFinancialsPrice, relatedAgencyId, country);
            List<Agency_Program_Financials__c>  defaultProduct=new SLT_Agency_Program_Financials().getAgencyProgramFinancialsDetailsDefault(agencyProgramFinancialsPrice, relatedAgencyId);
            
            for(Contract con:newList)
            {
                if(con.Non_Standard_Contract__c==False && (con.Agency_Program__c!=NULL || con.Agency_Program__c!='') && (con.PRM_Contract_type__c=='Agency Program SOW' || con.PRM_Contract_type__c=='Sandbox Agreement' || con.PRM_Contract_type__c=='Data Program'))
                {
                    if(apfProduct.size()>0)
                    {
                        con.Product__c = apfProduct[0].Product__c;
                        con.Budget__c = apfProduct[0].Price__c;
                        con.CurrencyIsoCode = apfProduct[0].CurrencyIsoCode;
                    }
                    else
                    {
                        if(defaultProduct.size()>0){
                            con.Product__c = defaultProduct[0].Product__c;
                            con.Budget__c = defaultProduct[0].Price__c;
                            con.CurrencyIsoCode = defaultProduct[0].CurrencyIsoCode;
                        }
                    }
                }
            }
        }
        
    } 
    
    public static void updateParentContract(List<Contract> newList,Map<Id, Contract> oldMap) {
        Set<Id> conId=new Set<Id>();
        Set<Id> parentConId=new Set<Id>();
        Set<String> fieldSet = new Set<String>{'Id','ContractNumber'};
        Integer flag=0;
        for(Contract con:newList)
        {
            conId.add(con.Id);
        }
        List<Contract> relatedcontract = new SLT_Contract().selectByContractIdList(conId,fieldSet);        
        List<Contract> parentContract=new SLT_Contract().selectParentContract(relatedcontract[0].ContractNumber);
        if(parentContract.size()>0){
            for(Contract con:newList)
            {
                if(con.SOW_status__c=='Signed' && con.SOW_status__c!=oldMap.get(con.Id).SOW_status__c)
                {
                    parentContract[0].Renewal_Status__c='Renewed';
                    flag=1;
                }
            }
            if(flag==1)
            {
                update parentContract;
            }
        }
    }

    public static void insertContract(List<Contract> newList,Map<Id, Contract> oldMap) 
    {
        Set<Id> conId=new Set<Id>();
        for(Contract con:newList)
        {
            if(con.Non_Standard_Contract__c==False && (con.Agency_Program__c!=NULL || con.Agency_Program__c!=''))
            {
                conId.add(con.Id);
            }
        }
        
        Set<String> fieldSet=new Set<String>{'AccountId','Agency_Program__c'};
        List<Contract> currentContract=new SLT_Contract().fetchContract(conId, fieldSet); 
        if(currentContract.size()>0)
        {
            Set<String> fieldSet1=new Set<String>{'AccountCountry__c'};
            List<Account> acc=new SLT_Account().getAccountCountry(fieldSet1, currentContract[0].AccountId);
            Id agencyProgramFinancialsPrice = Schema.SObjectType.Agency_Program_Financials__c.getRecordTypeInfosByDeveloperName().get('Price').getRecordTypeId();
            String relatedAgencyId=currentContract[0].Agency_Program__c;
            String country=acc[0].AccountCountry__c;
            List<Agency_Program_Financials__c> apfProduct=new SLT_Agency_Program_Financials().getAgencyProgramFinancialsDetails(agencyProgramFinancialsPrice, relatedAgencyId, country);
            List<Agency_Program_Financials__c>  defaultProduct=new SLT_Agency_Program_Financials().getAgencyProgramFinancialsDetailsDefault(agencyProgramFinancialsPrice, relatedAgencyId);
            
            Id contractPRM_RT = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get(CON_PEP.S_PEP_CTR_RECORDTYPE).getRecordTypeId();
            List<Contract> contractToUpdate=new List<Contract>();
            for(Contract con:newList)
            {
                if(con.Non_Standard_Contract__c==False && (con.Agency_Program__c!=NULL || con.Agency_Program__c!='') && (con.PRM_Contract_type__c=='Agency Program SOW' || con.PRM_Contract_type__c=='Sandbox Agreement' || con.PRM_Contract_type__c=='Data Program'))
                {
                    Contract cc=new Contract(Id=con.Id,RecordTypeId=contractPRM_RT,AccountId=con.AccountId,Status='Not Started',Agency_Program__c=con.Agency_Program__c);
                    
                    if(apfProduct.size()>0)
                    {
                        cc.Product__c = apfProduct[0].Product__c;
                        cc.Budget__c = apfProduct[0].Price__c;
                        cc.CurrencyIsoCode = apfProduct[0].CurrencyIsoCode;
                    }
                    else
                    {
                        if(defaultProduct.size()>0){
                            cc.Product__c = defaultProduct[0].Product__c;
                            cc.Budget__c = defaultProduct[0].Price__c;
                            cc.CurrencyIsoCode = defaultProduct[0].CurrencyIsoCode;
                        }
                    }
                    contractToUpdate.add(cc); 
                }
            }
            update contractToUpdate;
        }
    }
    
}