src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_ExternalClient_Info__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CSM to External Client(BISM) User Name , password, URL and key.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <description>Select the default account Id</description>
        <label>Account Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Url__c</fullName>
        <label>Client Url</label>
        <type>Url</type>
    </fields>
    <label>CSM External Client Info</label>
</CustomObject>

src/objects/CSM_Ticket_Genie__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CSM Ticket Genie</relationshipLabel>
        <relationshipName>CSM_Ticket_Genie</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>2340</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FeedBackScore__c</fullName>
        <label>Feed Back Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsAdvanced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advanced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsNativeLanguage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Native Language</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SuggestedResolution__c</fullName>
        <label>Suggested Resolution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>CSM Ticket Genie</label>
    <nameField>
        <displayFormat>TG-{000000000}</displayFormat>
        <label>CSM Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSM Ticket Genie</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
    <fields>
        <fullName>QueueName__c</fullName>
        <description>CSM - ACN - S-0007 - Queue Name</description>
        <label>Queue Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Q1</fullName>
                </value>
                <value>
                    <fullName>Q2</fullName>
                </value>
                <value>
                    <fullName>Q3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM - ACN - S-0007 - User Lookup</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_CNT_CSM_GenieChatGPT.cls
@isTest
private class TST_CNT_CSM_GenieChatGPT {
    
    @testSetup
    static void dataSetup() {
        Account acc = CSM_Util.createAccount();
        acc.Website='http://www.iqvia.com';
        insert acc;
        Contact cnt = CSM_Util.createContact(acc.Id,'CaseTestGenieChatGPTContact');
        insert cnt;
        Account account = UTL_TestData.createAccount();
        account.Website='http://www.iqvia.com';
        insert account;
        Contact contact = UTL_TestData.createContact(account.Id);
        insert contact;
        Id recordType =  Schema.SObjectType.Case.getRecordTypeInfosByName().get('TechnologyCase').getRecordTypeId();
        Queue_User_Relationship__c queues=new Queue_User_Relationship__c();
        queues.Name ='Q1';
        queues.QueueName__c ='Q1';
        queues.Type__c ='Queue';
        queues.User__c = UserInfo.getUserId(); 
        insert queues;
        Queue_User_Relationship__c queueUser=new Queue_User_Relationship__c();
        queueUser.Name ='Q1';
        queueUser.QueueName__c ='Q1';
        queueUser.Type__c ='User';
        queueUser.User__c = UserInfo.getUserId();
        insert queueUser;
        Case c = New Case(Subject = 'TestGenieChatGPTCase',RecordTypeId=recordType, ContactId = contact.Id, AccountId = account.Id, Status = 'New', Priority = 'Medium', Origin = 'Email',CurrentQueue__c=queues.Id,Current_Queue__c = 'Q1');
        insert c;
        CSM_ExternalClient_info__c ec = new CSM_ExternalClient_info__c(Name = 'AskGenie', Client_Url__c = 'http://test-internal-global-ticketgenie.iqvia.com/ticketgenie',Account_Id__c='PUT');
        insert ec;
        CSM_Ticket_Genie__c tg = new CSM_Ticket_Genie__c(Case__c = c.Id, IsAdvanced__c = false, IsNativeLanguage__c = false,SuggestedResolution__c = '{Summary: \'this is Summary\', Resolution: [Check if the Insight Module is active for the user\'s profile.,Provide documentation about the Insight Module and its configuration.,Check if the user has the necessary permissions to view Insights.], References: [https://docs.ims.io/OCE_Personal/WebUSG/Content/OCE/Welcome%20to%20OCE%20Sales.htm,https://docs.ims.io/OCE_Personal/MobileUSG/Content/_OCE/_Welcome/Welcome.htm]}'); 
        insert tg;
    }
    
    private class CNT_CSM_GenieChatGPTMock implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{"Summary":"This is a test summary","Resolution":["Check if the Insight Module is active for the user\'s profile. ","Provide documentation about the Insight Module and its configuration.","Check if the user has the necessary permissions to view Insights.","Verify if there are any filters applied that may be hiding the Insights.","If the issue persists, troubleshoot further by checking the user\'s access to the related objects and fields.","If the issue still persists, escalate to the relevant team for further investigation."],"References":["https://docs.ims.io/OCE_Personal/WebUSG/Content/OCE/Welcome%20to%20OCE%20Sales.htm","https://docs.ims.io/OCE_Personal/MobileUSG/Content/_OCE/_Welcome/Welcome.htm","https://docs.ims.io/OCE_Personal/iPhoneUSG/Content/_iPhone/0_Welcome/11_Welcome_R18.htm"]}';

            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    
    @IsTest
    static void testGetGenieResolution(){
        Case cs = Database.query('Select Id,CaseNumber,RecordTypeName__c,ProductName__c,Account_Name_Article__c from Case LIMIT 1');
        Test.setMock(HttpCalloutMock.class, new CNT_CSM_GenieChatGPTMock());
        Test.startTest();
        CNT_CSM_GenieChatGPT.getGenieResolution(cs, false, false);
        Test.StopTest();
        Id cId = cs.Id;
        CSM_Ticket_Genie__c ticketGenie = Database.query('Select Id,Case__c,SuggestedResolution__c,FeedBackScore__c,Comments__c from CSM_Ticket_Genie__c where Case__c = : cId LIMIT 1');
        CNT_CSM_GenieChatGPT.saveFeedBackdata(ticketGenie);
        CNT_CSM_GenieChatGPT.getTicketGeniedata(cs.Id);
    }

}