src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <description>CSM - ACN - S0036 - Account Country</description>
        <label>Account Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agency_Program__c.object
<CustomObject>
    <description>PRM- Agency Program Catalog</description>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Agency Programs</relationshipLabel>
        <relationshipName>Agency_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Program</label>
    <nameField>
        <label>Partner Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agency_Program_Financials__c.object
<CustomObject>
    <description>PRM- Agency Program Financials</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Countries List</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Apttus_Config2__Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default Value</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price</description>
        <label>Price</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Product</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Partner Program Financials</relationshipLabel>
        <relationshipName>Agency_Program_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Agency Program Field</description>
        <label>Program Name</label>
        <referenceTo>Agency_Program__c</referenceTo>
        <relationshipLabel>Partner Program Financials</relationshipLabel>
        <relationshipName>Agency_Program_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Program Financials</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Partner Program Financials Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Program Financials</pluralLabel>
    <recordTypes>
        <fullName>Price</fullName>
        <active>true</active>
        <description>Price Record Type</description>
        <label>Price</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Agency_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRM Contract management</description>
        <label>Partner Program</label>
        <referenceTo>Agency_Program__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Notification Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Contract_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Parent Contract Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Contract_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Ultimate Parent Contract Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_SLT_Agency_Program.cls
/*
* Version       : 1.0
* Description   : Test Class for SLT_Agency_Program
*/
@isTest
public class TST_SLT_Agency_Program {
    
    @testSetup
    static void dataSetup()
    {
        Account ac = new Account(name ='Acme',CustomerSegment__c = 'GOVERNMENT',Sub_Industry__c = 'STATE') ;
        ac.AccountCountry__c = 'US' ;
        insert ac;
		
        List<Product2> prodList = new List<Product2>(); 
        List<Agency_Program__c> agencyprogramList = new List<Agency_Program__c>();
        List<Contract> contractList = new List<Contract>();
        Product2 prod = TST_PEP_TestDataFactory.createProduct('Oce Sales');
        Product2 prodmarketing = TST_PEP_TestDataFactory.createProduct('Oce Marketing');
        prodList.add(prod);
        prodList.add(prodmarketing);
        Insert prodList;
        
        Agency_Program__c agencyprog = TST_PEP_TestDataFactory.createAgencyProgram(prod);
        Agency_Program__c agencyprogMark = TST_PEP_TestDataFactory.createAgencyProgram(prodmarketing);
        agencyprogramList.add(agencyprog);
        agencyprogramList.add(agencyprogMark);
        insert agencyprogramList;
		
        Contract ctr = TST_PEP_TestDataFactory.createContract('Ctr000125', ac.Id, prod.Id);		
        Contract ctrMark = TST_PEP_TestDataFactory.createContract('Ctr000126', ac.Id, prodmarketing.Id);		
        ctr.Parent_Contract_Number__c = 123;		
        ctr.Ultimate_Parent_Contract_Number__c = 345;		
        ctr.Notification_Counter__c=2;		
        ctr.Agency_Program__c=agencyprog.Id;		
        ctrMark.Parent_Contract_Number__c = 123;		
        ctrMark.Ultimate_Parent_Contract_Number__c = 345;		
        contractList.add(ctr);		
        contractList.add(ctrMark);		
        insert contractList;
        
        Id agencyProgramFinancialsPrice = Schema.SObjectType.Agency_Program_Financials__c.getRecordTypeInfosByDeveloperName().get('Price').getRecordTypeId();
        Agency_Program_Financials__c apf=new Agency_Program_Financials__c();
        apf.RecordTypeId=agencyProgramFinancialsPrice;
        apf.Program_Name__c=agencyprog.Id;
        apf.Country__c='US';
        apf.CurrencyIsoCode='USD';
        apf.Default__c=true;
        apf.Product__c=prod.Id;
        apf.Price__c=100;
        insert apf;  
        
        Agency_Program_Financials__c apf2=new Agency_Program_Financials__c();
        apf2.RecordTypeId=agencyProgramFinancialsPrice;
        apf2.Program_Name__c=agencyprog.Id;
        apf2.Country__c='US';
        apf2.CurrencyIsoCode='USD';
        apf2.Default__c=false;
        apf2.Product__c=prod.Id;
        apf2.Price__c=100;
        insert apf2; 
        
    }
    
    @isTest
    static void testFetchRelatedAgencyProgram()
    {
        Agency_Program__c agencyprog = [SELECT Id, Name, Product__c FROM Agency_Program__c WHERE Name = 'OCE Sales'];
        Agency_Program__c agencyProgram=new Agency_Program__c();
        Test.startTest();
        	agencyProgram=new SLT_Agency_Program().fetchRelatedAgencyProgram(agencyprog.Id);
        Test.stopTest();
        System.assertNotEquals(null, agencyProgram.Id);
    }
    
    @isTest
    static void testFetchAgencyProgramById()
    {
        Agency_Program__c agencyprog = [SELECT Id, Name, Product__c FROM Agency_Program__c WHERE Name = 'OCE Sales'];
        Agency_Program__c agencyProgram=new Agency_Program__c();
        Test.startTest();
        	agencyProgram=new SLT_Agency_Program().fetchAgencyProgramById(agencyprog.Id);
        Test.stopTest();
        System.assertNotEquals(null, agencyProgram.Id);
    }
    
    @isTest
    static void testFetchAllActiveAgencyProgram()
    {
        Agency_Program__c agencyprog = [SELECT Id, Name, Product__c FROM Agency_Program__c WHERE Name = 'OCE Sales'];
        List<Agency_Program__c> agencyProgram=new List<Agency_Program__c>();
        Set<String> fieldSet=new Set<String>{'Id'};
        Test.startTest();
        	agencyProgram=new SLT_Agency_Program().fetchAllActiveAgencyProgram(fieldSet);
        Test.stopTest();
        System.assertNotEquals(null, agencyProgram.size());
    }
    
    @isTest
    static void testFetchActiveAgencyProgram()
    {
        Agency_Program__c agencyprog = [SELECT Id, Name, Product__c FROM Agency_Program__c WHERE Name = 'OCE Sales'];
        List<Agency_Program__c> agencyProgram=new List<Agency_Program__c>();
        Test.startTest();
        	agencyProgram=new SLT_Agency_Program().fetchActiveAgencyProgram();
        Test.stopTest();
        System.assertNotEquals(null, agencyProgram.size());
    }
	
    @isTest
    static void testFetchRelatedAgencyProgramById()
    {
		Contract ctr = [SELECT Id, Product__c, Name FROM Contract WHERE Name = 'Ctr000125'];
        Agency_Program__c agencyprog = [SELECT Id, Name, Product__c FROM Agency_Program__c WHERE Name = 'OCE Sales'];
        List<Agency_Program__c> agencyProgram=new List<Agency_Program__c>();
        Test.startTest();
            agencyProgram=new SLT_Agency_Program().fetchRelatedAgencyProgramById(ctr.Id);
        Test.stopTest();
        System.assertNotEquals(null, agencyProgram.size());
    }
    
    @isTest
    static void testFetchActiveAgencyPrograms()
    {
        List<Account> acc=[SELECT AccountCountry__c FROM Account LIMIT 1];
        Id recordId = Schema.SObjectType.Agency_Program_Financials__c.getRecordTypeInfosByDeveloperName().get('Price').getRecordTypeId();
        Test.startTest();
        List<Agency_Program__c> agencyProgram=new SLT_Agency_Program().fetchActiveAgencyPrograms(acc[0].AccountCountry__c,recordId);
        Test.stopTest();
        System.assertNotEquals(null, agencyProgram.size());
    }
    
    @isTest
    static void testFetchActiveAgencyProgramsDefault()
    {
        List<Account> acc=[SELECT AccountCountry__c FROM Account LIMIT 1];
        Agency_Program__c agencyprog = [SELECT Id, Name, Product__c FROM Agency_Program__c WHERE Name = 'OCE Sales'];
        Set<Id> apId=new Set<Id>{agencyprog.Id};
        Id recordId = Schema.SObjectType.Agency_Program_Financials__c.getRecordTypeInfosByDeveloperName().get('Price').getRecordTypeId();
        Test.startTest();
        List<Agency_Program__c> agencyProgram=new SLT_Agency_Program().fetchActiveAgencyProgramsDefault(recordId,apId);
        Test.stopTest();
        System.assertNotEquals(null, agencyProgram.size());
    }
}