src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <description>CSM - ACN - S0036 - Account Country</description>
        <label>Account Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RDCategorization__c</fullName>
        <description>CSM-ACN-S-0036 - Picklist field with values Sponsor,Site, Internal, External</description>
        <label>R&amp;D Categorization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sponsor</fullName>
                </value>
                <value>
                    <fullName>Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Case_Type__c</fullName>
        <label>Portal Case Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Information Offering</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Technology Solutions</fullName>
                </value>
                <value>
                    <fullName>DATA</fullName>
                    <isActive>false</isActive>
                    <label>DATA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1455 - Field value dependent on selected Industry</description>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_QI_Data_Portal_Queue_User_details__c.object
<CustomObject>
    <fields>
        <fullName>AccountCountry__c</fullName>
        <label>Account Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Data Portal Queue User details</relationshipLabel>
        <relationshipName>Data_Portal_Queue_User_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Current_Users__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Current Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseRecordType__c</fullName>
        <label>Case Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ActivityPlan</fullName>
                </value>
                <value>
                    <fullName>DATACase</fullName>
                </value>
                <value>
                    <fullName>TechnologyCase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queue_User_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue User Relationship</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Queue_User_Relationship__c.Type__c</field>
                <operation>equals</operation>
                <value>Queue</value>
            </filterItems>
            <infoMessage>Please Select the Queue user Relationship type as queue</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Queue_User_Relationship__c</referenceTo>
        <relationshipLabel>Data Portal Queue User details</relationshipLabel>
        <relationshipName>Data_Portal_Queue_User_details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>CSM-1116 Product Segregation to show only selected product to CSH User in Customer Service Hub. differentiate the CSH queue assignment and Product restriction functionality in CSH</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Queue Assignment</fullName>
                    <default>true</default>
                    <label>Queue Assignment</label>
                </value>
                <value>
                    <fullName>Product Level Restriction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Portal Queue User details</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>CSM QI Data Portal  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Portal Queue User details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Community_Topics__c</fullName>
        <label>Community Topics</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Topics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecificToCSM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM - ACN - S0024 - Specific to CSM?</description>
        <label>Specific to CSM?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM - ACN - S-0007 - User Lookup</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Queue_User_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Request_Ticket_Number__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Ticket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Community_Topics.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ADA</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for CLM for Nexxus MI</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for CLM for OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for ePromo</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for Kadrige iDetailing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for Kadrige iSharing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for OCE Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Spend 360</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Spend 360 - US</fullName>
    </customValue>
    <customValue>
        <fullName>Audits Nationaux Ethiques</fullName>
    </customValue>
    <customValue>
        <fullName>Business Rules &amp; Processes</fullName>
    </customValue>
    <customValue>
        <fullName>CLM Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>CLM For Nexxus MI</fullName>
    </customValue>
    <customValue>
        <fullName>CLM For OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Connectivity &amp; Wireless</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Health</fullName>
    </customValue>
    <customValue>
        <fullName>Content for Kadrige iDetailing</fullName>
    </customValue>
    <customValue>
        <fullName>CRM Software</fullName>
    </customValue>
    <customValue>
        <fullName>Dashboard (Flex/SFE)</fullName>
    </customValue>
    <customValue>
        <fullName>DataView</fullName>
    </customValue>
    <customValue>
        <fullName>DDD</fullName>
    </customValue>
    <customValue>
        <fullName>EPPM</fullName>
    </customValue>
    <customValue>
        <fullName>ePromo</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware &amp; Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Hospi 360</fullName>
    </customValue>
    <customValue>
        <fullName>IMS One</fullName>
    </customValue>
    <customValue>
        <fullName>Internal &amp; HD Processes</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA CDW</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA Data Connector</fullName>
    </customValue>
    <customValue>
        <fullName>OneKey</fullName>
    </customValue>
    <masterLabel>Community Topics</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.cls
@isTest
private class TST_CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN {
    
    static testmethod void getAccountCountryList(){
        List<EXT_CSM_CheckboxDetails> checkDtls = new List<EXT_CSM_CheckboxDetails>();
        UserRole portalRole = [Select Id,DeveloperName,PortalType  From UserRole Where DeveloperName = 'IQVIA_Global' and PortalType='None'];
        String profilId2 = [select id from Profile where Name='System Administrator'].Id;
        User accOwner = New User(Alias = 'su',UserRoleId= portalRole.Id, ProfileId = profilId2,EmployeeNumber='075070707', Email = 'john2@iqvia.com',IsActive =true ,Username ='john2@iqvia.com', LastName= 'testLastName', CommunityNickname ='testSuNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', Change_Request_Description__c = 'test', Change_Request_Ticket_Number__c ='test description');
        insert accOwner;
        System.runAs (accOwner) {
        Account acc = new Account(
            Name = 'TestAccount',
            AccountCountry__c = 'IN', 
            RDCategorization__c = 'Site',
            CustomerSegment__c = 'GOVERNMENT',
            Sub_Industry__c = 'STATE');
        //acct.IsCustomerPortal = true;
        insert acc;
        Group g1 = new Group(Name='Tech - Queue T1', type='Queue');
            insert g1;
            QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Case');
            insert q1;
            
            Product2 product = UTL_TestData.createProduct();
            product.Community_Topics__c='OneKey';
            product.SpecificToCSM__c = True;
            insert product;
            
                    
            Asset asset = new Asset(Name = 'TestAsset', AccountId = acc.Id, Product2Id = product.id);
            insert asset;
            
            GroupMember grpUser = new GroupMember (
                UserOrGroupId = accOwner.Id,
                GroupId = g1.Id);
            
            insert grpUser;
            
            Queue_User_Relationship__c qurPortal = new Queue_User_Relationship__c(Name = 'Q1',User__c = UserInfo.getUserId(),Type__c = 'Queue');
            insert qurPortal;
            CSM_QI_Data_Portal_Queue_User_details__c dT = new CSM_QI_Data_Portal_Queue_User_details__c();
            dT.Queue_User_Relationship__c = qurPortal.Id;
            dT.Account__c = acc.Id;
            dT.All_Current_Users__c = true;
            dT.CaseRecordType__c = 'TechnologyCase';
            dT.Type__c ='Queue Assignment';
            dT.Order__c = 1;
            insert dT;
            CSM_QI_Data_Portal_Queue_User_details__c dd = new CSM_QI_Data_Portal_Queue_User_details__c();
            dd.Queue_User_Relationship__c = qurPortal.Id;
            dd.Account__c = acc.Id;
            dd.All_Current_Users__c = true;
            dd.CaseRecordType__c = 'DATACase';
            dd.Type__c ='Queue Assignment';
            dd.Order__c = 1;
            insert dd;
        Contact contact = new Contact( 
            Firstname='Brian', 
            Lastname='Dent', 
            Phone='(619)852-4569', 
            Department='Mission Control', 
            Title='Mission Specialist - Neptune', 
            Email='john@acme.com',
            Portal_Case_Type__c = 'Technology Solutions',
            Contact_User_Type__c='HO User',
            AccountId = acc.Id);
        insert contact;
        
        String profilId = [select id from Profile where Name='CSM Customer Community Plus Login User'].Id;
        User user = New User(Alias = 'com', Email = 'john@acme.com',IsActive =true , ContactId = contact.Id, ProfileId = profilId,Username =' john@acme.com', LastName= 'testLastName', CommunityNickname ='testCommunityNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US');
        insert user;
        Test.startTest();
            checkDtls = CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.getAccountCountryList();
            List<Queue_User_Relationship__c> queueDtls = CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.getTechnoQueueList();
            List<Account> accList = CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.getAllCustomerPortalAccountList(acc.AccountCountry__c);
            List<AggregateResult> assetlist = CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.getAccountProductList(accList[0].Id);
            EXT_CSM_DataTableResponse Response = CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.getPortalDataList();
            CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.addtoCSMDataPortal(acc.AccountCountry__c, acc.Id, null, null, qurPortal.Id, null);
            CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.addtoCSMDataPortal(acc.AccountCountry__c, acc.Id, null, null, qurPortal.Id, null);
            Integer count = CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.getTotalNoOfRows();
            CSM_QI_Data_Portal_Queue_User_details__c portalUser = [Select Id,Name From CSM_QI_Data_Portal_Queue_User_details__c LIMIT 1];
            CNT_CSM_TECHNO_CSH_QUEUE_ASSIGN.deleteRecord(portalUser.id);
        Test.stopTest();
        }
    }
    
}