src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Accounts are validated against SAP to ensure a match and to prevent duplication of accounts. &quot;New&quot; indicates that the account has not yet been validated against SAP, &quot;SAP Validated&quot; means that it should exist as a ParentAccount on SAP</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>SAP Validated</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <description>SCM-MC-RSOW#- A custom object of Agreement for SCM</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Initiation</fullName>
                </value>
                <value>
                    <fullName>Service Provider Request Details</fullName>
                </value>
                <value>
                    <fullName>Client Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SCM Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCM Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CLM_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CLM-MC-CLMCMA-40 - Custom setting for CLM Module.</description>
    <fields>
        <fullName>Contracts_Distribution_Email__c</fullName>
        <description>CLM-MC-CLMCMA-12794 - This field hold email Id of Contracts Distribution</description>
        <label>Contracts Distribution Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docusign_Account_Id__c</fullName>
        <description>CLM-MC-CLMCMA-296 - Docusign_Account_Id for Docusign API Intigration</description>
        <inlineHelpText>Docusign_Account_Id for Docusign API Intigration</inlineHelpText>
        <label>Docusign_Account_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IQVIA_MSA_Account_Id__c</fullName>
        <description>CLM-MC-CLMCMA-18407 - This Field used to store DocuSign App Name for IQVIA MSA .</description>
        <label>IQVIA MSA DocuSign App Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IQVIA_SOW_Account_Id__c</fullName>
        <description>CLM-MC-CLMCMA-18407 - This Field used to store DocuSign App Name for IQVIA SOW.</description>
        <label>IQVIA SOW DocuSign App Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CLM Configuration</label>
</CustomObject>

src/objects/DocuSign_Auth_Data__c.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <description>CLM-MC-CLMCMA-12002 - Field to store Client Id</description>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocusignUser_Id__c</fullName>
        <description>CLM-MC-CLMCMA-12002 - Field to store docusign user Id</description>
        <label>DocusignUser_Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>CLM-MC-CLMCMA-12002 - Field to store docusign user name</description>
        <label>User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Id__c</fullName>
        <description>CLM-MC-CLMCMA-12002 - Field to store account id</description>
        <label>Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Base_URL__c</fullName>
        <description>CLM-MC-CLMCMA-12002 - Field to store base URL</description>
        <label>Base Url</label>
        <type>Url</type>
    </fields>
    <label>DocuSign Authentication</label>
    <nameField>
        <label>DocuSign Auth Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Authentications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IQ_DocuSignEnvelope__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>IQVIA_Agreement__c</referenceTo>
        <relationshipName>DocuSignEnvelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EnvelopeId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Envelope Id from DocuSign</description>
        <externalId>true</externalId>
        <inlineHelpText>Envelope Id from DocuSign</inlineHelpText>
        <label>Envelope Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Envelope status from DocuSign</description>
        <inlineHelpText>Envelope status from DocuSign</inlineHelpText>
        <label>Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocusignUser_Id__c</fullName>
        <inlineHelpText>CLM-MC-CLMCMA-18408: Docusign User ID</inlineHelpText>
        <label>DocusignUser Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Docusign_AccountId__c</fullName>
        <description>CLM-MC-CLMCMA-18408: Docusign Account ID</description>
        <label>Docusign_AccountId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docusign_App_Name__c</fullName>
        <description>CLM-MC-CLMCMA-18408: Text field to store Docusign App name.</description>
        <inlineHelpText>Text field to store Docusign App Name</inlineHelpText>
        <label>Docusign App Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_As_User_Email__c</fullName>
        <description>CLM-MC-CLMCMA-18408: Send as User Email text field.</description>
        <label>Send As User Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signers__c</fullName>
        <description>CLM-MC-CLMCMA-18408: Signers.</description>
        <label>Signers</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IQVIA_Agreement__c.object
<CustomObject>
    <description>CLM-MC-CLMCMA-17657 - Represents an agreement in the system</description>
    <fields>
        <fullName>Docusign_Account_Id__c</fullName>
        <description>CLM-MC-CLMCMA-18407 - The DocuSign App Name to which this agreement is associated to.</description>
        <formula>If($RecordType.DeveloperName == &apos;MSA&apos;, $Setup.CLM_Configuration__c.IQVIA_MSA_Account_Id__c,
If($RecordType.DeveloperName == &apos;USBU&apos;, $Setup.CLM_Configuration__c.IQVIA_SOW_Account_Id__c,$Setup.CLM_Configuration__c.Default_DocuSign_Account_Id__c))</formula>
        <inlineHelpText>The DocuSign App Name to which this agreement is associated to.</inlineHelpText>
        <label>Docusign App Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CLM-MC-CLMCMA-17657 - The sub stage of an agreement – the status underneath a given status category. These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:
Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated, Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Internal Legal Review</fullName>
                </value>
                <value>
                    <fullName>Feedback Awaited</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>Sent for Signatures</fullName>
                </value>
                <value>
                    <fullName>Pending Templates</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>                
                <value>
                    <fullName>Accepted</fullName>
                    <isActive>false</isActive>
                    <label>Accepted</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                    <isActive>false</isActive>
                    <label>Approved Request</label>
                </value>
                <value>
                    <fullName>BUR/Finance Review</fullName>
                    <isActive>false</isActive>
                    <label>BUR/Finance Review</label>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                    <isActive>false</isActive>
                    <label>Being Renewed</label>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                    <isActive>false</isActive>
                    <label>Being Terminated</label>
                </value>
                <value>
                    <fullName>Budget Customer Edits</fullName>
                    <isActive>false</isActive>
                    <label>Budget Customer Edits</label>
                </value>
                <value>
                    <fullName>Budget External Review</fullName>
                    <isActive>false</isActive>
                    <label>Budget External Review</label>
                </value>
                <value>
                    <fullName>Budget Internal Review</fullName>
                    <isActive>false</isActive>
                    <label>Budget Internal Review</label>
                </value>
                <value>
                    <fullName>Budget Preparation</fullName>
                    <isActive>false</isActive>
                    <label>Budget Preparation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IQVIA Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IQVIA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IQVIA_Agreement_Team__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <description>CLM-MC-CLMCMA-17944 - This field stores Id of associated IQVIA Agreement.</description>        
        <label>Agreement</label>
        <referenceTo>IQVIA_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Teams</relationshipLabel>
        <relationshipName>Agreement_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Team</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Agreement Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_BCH_CLM_IQ_BulkDSSendForESignatures.cls
@isTest
public class TST_BCH_CLM_IQ_BulkDSSendForESignatures {
    
    @testSetup
    static void dataSetup() {
        CLM_Configuration__c clmConfiguration = TST_CLM_TestDataFactory.createClmConfigurationSetting(false);
        clmConfiguration.Contracts_Distribution_Email__c = 'test@gmail.com';
        clmconfiguration.IQVIA_SOW_Account_Id__c = 'CLM Test';
        clmconfiguration.IQVIA_MSA_Account_Id__c = 'CLM Test';
        insert clmConfiguration;

        IQVIA_Agreement__c testAgreement = TST_CLM_TestDataFactory.createIQAgreement(CON_CLM.USBU_IQVIA_RECORDTYPEID, false);
        testAgreement.Name = 'Test IQVIA Agreement';
        insert testAgreement;
        
        CNT_CLM_DocuSignESignature.DocuSignRecipientsWrapper docusignWrapper = new CNT_CLM_DocuSignESignature.DocuSignRecipientsWrapper('aOl05000000Gma9CAC', 
            '1', '1', 'certifieddelivery', 'Test', 'xyz@gmail.com', 'privateMessage');
        String mockResponse = JSON.serialize(new List<CNT_CLM_DocuSignESignature.DocuSignRecipientsWrapper>{docusignWrapper});
        IQ_DocuSignEnvelope__c docuApiEnvelopeSent = new IQ_DocuSignEnvelope__c(); 
        docuApiEnvelopeSent.Name = 'Docusign Sent';
        docuApiEnvelopeSent.Docusign_AccountId__c = '98765';
        docuApiEnvelopeSent.Status__c = CON_CLM.SENT_STATUS;
        docuApiEnvelopeSent.Agreement__c = testAgreement.Id;    
        docuApiEnvelopeSent.Signers__c = mockResponse; 
        docuApiEnvelopeSent.Send_As_User_Email__c = 'xyz@gmail.com';
        docuApiEnvelopeSent.EnvelopeId__c = 'fa41d5fb-0289-4968-ba51-e8890196158a';
        docuApiEnvelopeSent.Docusign_App_Name__c = 'CLM Test';
        insert docuApiEnvelopeSent;
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Content';      
        cv.PathOnClient = 'abc.jpg';
        cv.VersionData = Blob.valueOf('Test Content'); 
        insert cv;
        
        List<ContentDocument> contDocs = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument WHERE Title = 'Test Content'];
        ContentDocumentLink contentDocLink = new ContentDocumentLink();
        contentDocLink.LinkedEntityId = testAgreement.Id; 
        contentDocLink.ContentDocumentId = contDocs[0].Id; 
        insert contentDocLink;  
        
        String clearText = 'Test Text Data';
        Blob key = Blob.valueOf(CON_CLM.BLOB_VALUE);
        Blob cipherText = Crypto.encryptWithManagedIV('AES256', key, Blob.valueOf(clearText));
        String encodedCipherText = EncodingUtil.base64Encode(cipherText);       
        IQVIA_Agreement__c agreement = [SELECT Id, Docusign_Account_Id__c FROM IQVIA_Agreement__c WHERE Name = 'Test IQVIA Agreement' LIMIT 1];
        DocuSign_Auth_Data__c dsAuthData = new DocuSign_Auth_Data__c();
        dsAuthData.DocusignUser_Id__c = 'abc';
        dsAuthData.User_Name__c = 'dsuser001';
        dsAuthData.Account_Id__c = agreement.Docusign_Account_Id__c;
        dsAuthData.Base_URL__c = 'https://demo.docusign.net';
        //dsAuthData.Redirect_URL__c = '';
        dsAuthData.Client_Id__c = 'c123';
        dsAuthData.Private_Key__c = 'pkey123';
        dsAuthData.Access_Token__c = '83f620794efd';
        dsAuthData.DocuSign_Pwd__c = encodedCipherText;
        dsAuthData.Reminder_Delay__c = 1.0;
        dsAuthData.Reminder_Frequency__c = 1.0;    
        dsAuthData.Expire_After__c = 2.0;
        dsAuthData.Expire_Warn__c = 2.0;
        dsAuthData.Name = 'CLM Test';
        insert dsAuthData;
        
        Account account = new Account(Name = 'IMS Health Global',CustomerSegment__c = 'GOVERNMENT',Sub_Industry__c = 'STATE');
        insert account;
        
        Contact contact = new Contact(FirstName='test', Email='test@gmail.com', LastName ='lastname');
        contact.Account = account;
        contact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact').getRecordTypeId();
        insert contact;
        
        IQVIA_Agreement_Team__c agreementContact = new IQVIA_Agreement_Team__c();
        agreementContact.Agreement__c = testAgreement.Id;
        agreementContact.Contact__c = contact.Id;
        agreementContact.Type__c = CON_CLM.CONTACT_TYPE;
        agreementContact.DocuSign_Recipient__c = true;
        insert agreementContact;
    }
    
    @isTest
    private static void testDocusignSendForESignaturesBatch() {
        String query = 'SELECT Id, DocuSign_Envelope_Id__c, FF_Agreement_Number__c, Docusign_Account_Id__c,RecordTypeId FROM IQVIA_Agreement__c WHERE Name = \'Test IQVIA Agreement\' LIMIT 1';
        EmailTemplate emailTemp = [SELECT Id, DeveloperName FROM EmailTemplate LIMIT 1];
        BCH_CLM_IQ_BulkDSSendForESignatures docusignBatch = new BCH_CLM_IQ_BulkDSSendForESignatures(query, emailTemp.DeveloperName, 'abc@gmail.com');
        CNT_CLM_DocuSignESignature.DocuSignEnvelopeResponseWrapper derw = new CNT_CLM_DocuSignESignature.DocuSignEnvelopeResponseWrapper();
        derw.envelopeId = '05fb40f1-e33c-4335-8dc1-ee432be8a167'; 
        derw.uri = 'sampleURI';
        derw.statusDateTime = 'today()';
        derw.status = CON_CLM.SENT_STATUS;
        String mockResponse = JSON.serialize(derw);
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new BoxTestMockCallout(mockResponse, 'OK', 201));    
            Database.executeBatch(docusignBatch, 1); 
        Test.stopTest();
        
        IQVIA_Agreement__c agreement = [SELECT Id, Status__c FROM IQVIA_Agreement__c LIMIT 1]; 
        System.assertNotEquals(null, agreement.Status__c, 'The agreement status should be updated to Other Party Signatures');
    } 
}