src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerSegment__c</fullName>
        <description>ESPSFDCQI-15573</description>
        <label>Customer Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Customer_Segment</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Industry__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1354 - Field value dependent on selected Industry.</description>
        <inlineHelpText>Please submit a VIA Ticket to MDM Team if you want to change value at the field on Validated Account (MDM Validation Status = Validated)</inlineHelpText>
        <label>Sub Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CustomerSegment__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Industry</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of the account that this address pertains to.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AccountAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agreement_Repository_Event__e.object
<CustomObject>
    <fields>
        <fullName>AR_Comments__c</fullName>
        <description>CLM-MC-CLMCMA-21472: Field to store AR Comments.</description>
        <label>AR Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>CLM-MC-CLMCMA-21472: Field to store Object name.</description>
        <label>Object Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>CLM-MC-CLMCMA-21472: Field to store record Id.</description>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Agreement Repository Event</label>
    <pluralLabel>Agreement Repository Events</pluralLabel>
</CustomObject>

src/objects/IQVIA_Agreement__c.object
<CustomObject>
    <description>CLM-MC-CLMCMA-17657 - Represents an agreement in the system</description>
    <fields>
        <fullName>Account__c</fullName>      
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CLM-MC-CLMCMA-17657 - The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IQVIA Agreements</relationshipLabel>
        <relationshipName>Acc_IQVIAAgreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement_Repository_Number__c</fullName>
        <description>CLM-MC-CLMCMA-21460 - This field is used to store Agreement Repository Number</description>
        <label>Agreement Repository Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Services__c</fullName>
        <description>CLM-MC-CLMCMA-17657 - Its a multi-select picklist for services.</description>
        <inlineHelpText>List of all applicable Services for this agreement</inlineHelpText>
        <label>Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Xponent</fullName>
                </value>
                <value>
                    <fullName>Xponent Prescribing Dynamics</fullName>
                </value>
                <value>
                    <fullName>DDD</fullName>
                </value>
                <value>
                    <fullName>Electronic Data Transfer Platform Services</fullName>
                </value>
                <value>
                    <fullName>CDS</fullName>
                </value>
                <value>
                    <fullName>Prescriber Profiler</fullName>
                </value>
                <value>
                    <fullName>Patient Companion File</fullName>
                </value>
                <value>
                    <fullName>Provider Companion File</fullName>
                </value>
                <value>
                    <fullName>Payer Companion File</fullName>
                </value>
                <value>
                    <fullName>IQVIA Provider Medicare Part B Services</fullName>
                </value>
                <value>
                    <fullName>NPA Market Dynamics</fullName>
                </value>
                <value>
                    <fullName>NPA</fullName>
                </value>
                <value>
                    <fullName>NPA New to Brand</fullName>
                </value>
                <value>
                    <fullName>NSP</fullName>
                </value>
                <value>
                    <fullName>NMTA</fullName>
                </value>
                <value>
                    <fullName>Channel Dynamics</fullName>
                </value>
                <value>
                    <fullName>IQVIA: Out of Pocket Cost (OPC) Provider</fullName>
                </value>
                <value>
                    <fullName>Remittance Advisor (Ad Hoc)</fullName>
                </value>
                <value>
                    <fullName>Early Insight</fullName>
                </value>
                <value>
                    <fullName>RDM</fullName>
                </value>
                <value>
                    <fullName>Medical Device &amp; Supply Audit (MDSA)</fullName>
                </value>
                <value>
                    <fullName>Total Patient Tracker (TPT)</fullName>
                </value>
                <value>
                    <fullName>Pharmaceutical Sales Force Structures and Strategies (SFSS)</fullName>
                </value>
                <value>
                    <fullName>Retainer Program (National Services)</fullName>
                </value>
                <value>
                    <fullName>PlanTrak</fullName>
                </value>
                <value>
                    <fullName>PlanTrak Co-pay</fullName>
                </value>
                <value>
                    <fullName>Rx Benefit Design</fullName>
                </value>
                <value>
                    <fullName>Formulary Impact Analyzer (FIA)</fullName>
                </value>
                <value>
                    <fullName>PayerTrak</fullName>
                </value>
                <value>
                    <fullName>SMART</fullName>
                </value>
                <value>
                    <fullName>FMV Navigator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IQVIA Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IQVIA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MIBNF2__c.object
<CustomObject>
    <fields>
        <fullName>BNF_Status__c</fullName>
        <description>CRM-MC-ESPSFDCQI-8412</description>
        <label>BNF Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the name of the Revenue Analyst who will be processing the BNF.</inlineHelpText>
        <label>Revenue Analyst</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Revenue_Analyst__c.Available_for_Selection__c</field>
                <operation>equals</operation>
                <value>TRUE</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>$Source.MIBNF_Status__c</field>
                <operation>notEqual</operation>
                <value>New</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Revenue_Analyst__c</referenceTo>
        <relationshipName>R00NT0000001UO6hMAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Multi Invoice BNF</label>
    <nameField>
        <displayFormat>MIBNF-{000000}</displayFormat>
        <label>MIBNF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Multi Invoice BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MIBNF_Component__c.object
<CustomObject>
    <description>Multi Invoice BNF Component which is child BNF for an Opportunity</description>
    <fields>
        <fullName>AR_Comments__c</fullName>
        <description>ESPSFDCQI-17974</description>
        <label>Agreement Repository Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BNF_Status__c</fullName>
        <label>BNF Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Accrual</fullName>
                </value>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>SAP Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Created</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Confirmed</fullName>
                </value>
                <value>
                    <fullName>LO Accepted</fullName>
                </value>
                <value>
                    <fullName>LO Rejected</fullName>
                </value>
                <value>
                    <fullName>RA Accepted</fullName>
                </value>
                <value>
                    <fullName>RA Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Pending</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <formula>MIBNF__r.Revenue_Analyst__r.User__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue Analyst</label>
        <type>Text</type>
    </fields>
    <label>BNF</label>
    <nameField>
        <label>BNF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AR_Comments__c</fullName>
        <description>ESPSFDCQI-17973</description>
        <inlineHelpText>Provide your comments here if Agreement/Agreement repository is not required for this opportunity</inlineHelpText>
        <label>Agreement Repository Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Revenue_Analyst__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-3168 - This custom object is used to store the Revenue Analyst.</description>
    <label>Revenue Analyst</label>
    <nameField>
        <label>Revenue Analyst Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Analysts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Customer_Segment.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES/ NON-PROFIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>FINANCIAL COMPANY</fullName>
    </customValue>
    <customValue>
        <fullName>GOVERNMENT</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH CARE PROFESSIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITALS</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL FIRM</fullName>
    </customValue>
    <customValue>
        <fullName>MANUFACTURER</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIA/ ADVERTISING</fullName>
    </customValue>
    <customValue>
        <fullName>MEDICAL DEVICES &amp; DIAGNOSTICS</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER INDUSTRIES</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER SUPPLIERS TO PHARMA</fullName>
    </customValue>
    <customValue>
        <fullName>PAYERS/ HEALTH INSURANCES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACIES</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMACY BENEFIT MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - EMERGING</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - ESTABLISHED</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA - GENERIC</fullName>
    </customValue>
    <customValue>
        <fullName>PHARMA PACKAGING</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNOLOGY</fullName>
    </customValue>
    <customValue>
        <fullName>WHOLESALER</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
        <isActive>false</isActive>
        <label>LAB SERVICES</label>
    </customValue>
    <customValue>
        <fullName>ACADEMIC INSTITUTE</fullName>
        <isActive>false</isActive>
        <label>ACADEMIC INSTITUTE</label>
    </customValue>
    <customValue>
        <fullName>VETERINARY</fullName>
        <isActive>false</isActive>
        <label>VETERINARY</label>
    </customValue>
    <description>ESPSFDCQI-15573</description>
    <masterLabel>Customer Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Sub_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACADEMIA &amp; RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>ALTERNATE CHANNEL VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>BANKING</fullName>
    </customValue>
    <customValue>
        <fullName>CDMO/ API</fullName>
    </customValue>
    <customValue>
        <fullName>CHARITIES</fullName>
    </customValue>
    <customValue>
        <fullName>CHEMICALS</fullName>
    </customValue>
    <customValue>
        <fullName>CLINICS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTING</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: NUTRITIONALS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: OTC</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PATIENT CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONSUMER HEALTH: PERSONAL CARE</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT RESEARCH</fullName>
    </customValue>
    <customValue>
        <fullName>CONTRACT SALES</fullName>
    </customValue>
    <customValue>
        <fullName>DIAGNOSTICS - THERAPEUTICS</fullName>
    </customValue>
    <customValue>
        <fullName>DISTRIBUTOR ASSOCIATIONS</fullName>
    </customValue>
    <customValue>
        <fullName>DOCTORS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG DISCOVERY SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>FEDERAL/CENTRAL/NATIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>GENERICS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTHCARE WEBSITE PUBLISHERS</fullName>
    </customValue>
    <customValue>
        <fullName>HEALTH INSURANCE (NON-GOVT)</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>INFORMATION SERVICES VENDORS</fullName>
    </customValue>
    <customValue>
        <fullName>INSTITUTIONAL FUND</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA INTERNAL</fullName>
    </customValue>
    <customValue>
        <fullName>LAB SERVICES</fullName>
    </customValue>
    <customValue>
        <fullName>LEGAL</fullName>
    </customValue>
    <customValue>
        <fullName>STATE</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-1354/ ESPSFDCQI-15573</description>
    <masterLabel>Sub Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_DAO_Agreement_Repository_Event.cls
@IsTest
public class TST_DAO_Agreement_Repository_Event {
    @isTest
    private static void testAgreementRepositoryEvent() {
        Account account = new Account(Name = 'IMS Health Global',CustomerSegment__c = 'GOVERNMENT',Sub_Industry__c = 'STATE');
        insert account;
        
        IQVIA_Agreement__c agreement = TST_CLM_TestDataFactory.createIQAgreement(CON_CLM.USBU_IQVIA_RECORDTYPEID, false);
        agreement.Name = 'Test IQVIA Agreement';
        agreement.Account__c = account.Id;
        agreement.Services__c = 'FMV Navigator';
        insert agreement;
        
        Opportunity newOpportunity = TST_CLM_TestDataFactory.createOpportunity(false);
        newOpportunity.stageName = '1. Identifying Opportunity';
        insert newOpportunity;
        
        Revenue_Analyst__c revenueAnalyst = UTL_TestData.createRevenueAnalyst();
        insert revenueAnalyst;
        
        List<Address__c> addressList = UTL_TestData.createAddresses(account);
        insert addressList;
        
        MIBNF2__c TestMIBNF = UTL_TestData.createMIBNF(newOpportunity, revenueAnalyst);
        insert TestMIBNF;
        
        MIBNF_Component__c mic= UTL_TestData.createMIBNF_Comp(TestMIBNF, addressList);
        mic.BNF_Status__c = 'New';
        insert mic;
        
        Test.startTest();
            List<Agreement_Repository_Event__e> events = new List<Agreement_Repository_Event__e>();
            Agreement_Repository_Event__e arEvent1 = new Agreement_Repository_Event__e(AR_Comments__c = 'Test1', Object_Name__c = 'IQVIA_Agreement__c', Record_Id__c = agreement.Id);
            Agreement_Repository_Event__e arEvent2 = new Agreement_Repository_Event__e(AR_Comments__c = 'Test2', Object_Name__c = 'Opportunity', Record_Id__c = newOpportunity.Id);
            Agreement_Repository_Event__e arEvent3 = new Agreement_Repository_Event__e(AR_Comments__c = 'Test3', Object_Name__c = 'MIBNF_Component__c', Record_Id__c = mic.Id);       
            events.add(arEvent1);
            events.add(arEvent2); 
            events.add(arEvent3); 
            EventBus.publish(events);        
        Test.stopTest();

        IQVIA_Agreement__c agr = [Select Id, Name, Agreement_Repository_Number__c From IQVIA_Agreement__c Where Name ='Test IQVIA Agreement' LIMIT 1];
        Opportunity opp = [Select Id, Name, AR_Comments__c From Opportunity Where stageName = '1. Identifying Opportunity' LIMIT 1];
        MIBNF_Component__c miBNf = [Select Id, AR_Comments__c From MIBNF_Component__c where BNF_Status__c = 'New'];       

        System.assertEquals('Test1', agr.Agreement_Repository_Number__c, 'Sould be same');
        System.assertEquals('Test2', opp.AR_Comments__c, 'Sould be same');
        System.assertEquals('Test3', miBNf.AR_Comments__c, 'Sould be same');            
    }
}