src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LI_Mulesoft_Error_Message__c</fullName>
        <label>LI Mulesoft Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LI_Mulesoft_Sync_Status__c</fullName>
        <label>LI Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LI_Mulesoft_Sync_Timestamp__c</fullName>
        <description>CRM-QI-ESPSFDCQI-577 Timestamp indicating when record was successfully synced from IQVIA org to legacy IMS org via Mulesoft integration</description>
        <inlineHelpText>Timestamp indicating when record was successfully synced from IQVIA org to legacy IMS org via Mulesoft integration</inlineHelpText>
        <label>LI Mulesoft Sync Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LI_Mulesoft_Update_GUID__c</fullName>
        <description>CRM-MC-ESPSFDCQI-829 -</description>
        <label>LI Mulesoft Update GUID</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Error_Message__c</fullName>
        <label>LQ Mulesoft Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Status__c</fullName>
        <label>LQ Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Timestamp__c</fullName>
        <description>CRM-QI-ESPSFDCQI-577 Timestamp indicating when record was successfully synced from IQVIA org to legacy Quintiles org via Mulesoft integration</description>
        <inlineHelpText>Timestamp indicating when record was successfully synced from IQVIA org to legacy Quintiles org via Mulesoft integration</inlineHelpText>
        <label>LQ Mulesoft Sync Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Update_GUID__c</fullName>
        <description>CRM-MC-ESPSFDCQI-829 -</description>
        <label>LQ Mulesoft Update GUID</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Mulesoft_Opportunity_Sync__c.object
<CustomObject>
    <fields>
        <fullName>LI_Mulesoft_Error_Message__c</fullName>
        <label>LI Mulesoft Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LI_Mulesoft_Sync_Status__c</fullName>
        <label>LI Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LI_Mulesoft_Sync_Timestamp__c</fullName>
        <label>LI Mulesoft Sync Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LI_Mulesoft_Update_GUID__c</fullName>
        <label>LI Mulesoft Update GUID</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Error_Message__c</fullName>
        <label>LQ Mulesoft Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Status__c</fullName>
        <label>LQ Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Timestamp__c</fullName>
        <label>LQ Mulesoft Sync Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Update_GUID__c</fullName>
        <label>LQ Mulesoft Update GUID</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mulesoft Opportunity Sync</label>
    <nameField>
        <label>Mulesoft Opportunity Sync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mulesoft Opportunity Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LI_Mulesoft_Error_Message__c</fullName>
        <label>LI Mulesoft Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LI_Mulesoft_Sync_Status__c</fullName>
        <label>LI Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LI_Mulesoft_Sync_Timestamp__c</fullName>
        <description>CRM-QI-ESPSFDCQI-577 Timestamp indicating when record was successfully synced from IQVIA org to legacy IMS org via Mulesoft integration</description>
        <inlineHelpText>Timestamp indicating when record was successfully synced from IQVIA org to legacy IMS org via Mulesoft integration</inlineHelpText>
        <label>LI Mulesoft Sync Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Error_Message__c</fullName>
        <label>LQ Mulesoft Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Status__c</fullName>
        <label>LQ Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Timestamp__c</fullName>
        <description>CRM-QI-ESPSFDCQI-577 Timestamp indicating when record was successfully synced from IQVIA org to legacy Quintiles org via Mulesoft integration</description>
        <inlineHelpText>Timestamp indicating when record was successfully synced from IQVIA org to legacy Quintiles org via Mulesoft integration</inlineHelpText>
        <label>LQ Mulesoft Sync Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mulesoft_Opportunity_Sync__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mulesoft Opportunity Sync</label>
        <referenceTo>Mulesoft_Opportunity_Sync__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_TGR_MulesoftOpportunitySync.cls
@isTest
private class TST_TGR_MulesoftOpportunitySync {
    
    static testmethod void insertMulesoftOpportunitySyc () {
        Account acc = UTL_TestData.createAccount();
        insert acc;
        Opportunity opp = UTL_TestData.createOpportunity(acc.Id);
        insert opp;
        Mulesoft_Opportunity_Sync__c mos = new Mulesoft_Opportunity_Sync__c();
        mos.LI_Mulesoft_Update_GUID__c = UTL_Guid.newGuid();
        mos.LI_Mulesoft_Sync_Status__c = CON_CRM.MULESOFT_SYNC_STATUS_PENDING;
        mos.LI_Mulesoft_Sync_Timestamp__c = null;
        mos.LI_Mulesoft_Error_Message__c = null;  
        mos.LQ_Mulesoft_Update_GUID__c = UTL_Guid.newGuid();
        mos.LQ_Mulesoft_Sync_Status__c = CON_CRM.MULESOFT_SYNC_STATUS_PENDING;
        mos.LQ_Mulesoft_Sync_Timestamp__c = null;
        mos.LQ_Mulesoft_Error_Message__c = null;
        mos.Opportunity__c = opp.Id;
        Test.startTest();
        try{
		insert mos;
		}
		catch(exception e){}
        Test.stopTest();
        
    }

}