src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>ESPSFDCQI-16363</description>
        <formula>IF( INCLUDES(Type2__c, &apos;CRO&apos;), &apos;CRO;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Site&apos;), &apos;Site;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Investigator&apos;), &apos;Investigator;&apos;, &apos;&apos;) +
IF( INCLUDES(Type2__c, &apos;Clinical Site&apos;), &apos;Clinical Site&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site_Submission__c.object
<CustomObject>
    <description>ESPSFDCQI-16339</description>
    <label>Site Submission</label>
    <nameField>
        <label>Site Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_CNT_CRM_CreateNewSiteSubmission.cls
@isTest
public class TST_CNT_CRM_CreateNewSiteSubmission {
    
    @isTest
    public static void testCreateSiteSubmissionRecords(){
        Account acc = UTL_TestData.createAccount();
        insert acc;
        
        LoadCRMSampleData.createAvacareSetup();
        
        Opportunity opp = UTL_TestData.createOpportunity(acc.Id);
        insert opp;
        
        String siteIds = '';
        for(Account dp: [SELECT id FROM Account WHERE (Parent.Name = 'Avacare' AND Type__c like '%Clinical Site%')]){
            siteIds += dp.Id +',';
        }
        siteIds.removeEnd(',');
        
        Test.startTest();
        
        Boolean result = CNT_CRM_CreateNewSiteSubmission.createSiteSubmissionRecords(siteIds, opp.Id);
        List<Site_Submission__c> sss = [SELECT Id FROM Site_Submission__c];
        System.assertEquals(true, sss.size() > 0);
        Test.stopTest();
    }
    
}