src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>CSM-ACN-S-0036 - Email Field for Account</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Accounts are validated against SAP to ensure a match and to prevent duplication of accounts. &quot;New&quot; indicates that the account has not yet been validated against SAP, &quot;SAP Validated&quot; means that it should exist as a ParentAccount on SAP</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>SAP Validated</fullName>
                </value>
                <value>
                    <fullName>Validating</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agreement__c.object
<CustomObject>
    <description>SCM-MC-RSOW#- A custom object of Agreement for SCM</description>
    <fields>
        <fullName>Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Activation Failed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Incomplete Request</fullName>
                </value>
                <value>
                    <fullName>Awaiting PO</fullName>
                </value>
                <value>
                    <fullName>BNF submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Execution</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Credit Submitted</fullName>
                </value>
                <value>
                    <fullName>Invoiced with IMS Fees</fullName>
                </value>
                <value>
                    <fullName>Ready for BNF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Initiation</fullName>
                </value>
                <value>
                    <fullName>Service Provider Request Details</fullName>
                </value>
                <value>
                    <fullName>Client Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SCM Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCM Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IQ_DocuSignEnvelope__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>IQVIA_Agreement__c</referenceTo>
        <relationshipName>DocuSignEnvelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Envelope status from DocuSign</description>
        <inlineHelpText>Envelope status from DocuSign</inlineHelpText>
        <label>Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IQ_DocuSignEnvelopeRecipientStatus__c.object
<CustomObject>
    <description>Docusign envelope recipient status</description>
    <fields>
        <fullName>DocuSignEnvelopeId__c</fullName>
        <description>DocuSign Envelope Id master record id (SFDC ID)</description>
        <inlineHelpText>DocuSign Envelope Id master record id (SFDC ID)</inlineHelpText>
        <label>DocuSign Envelope Id</label>
        <referenceTo>IQ_DocuSignEnvelope__c</referenceTo>
        <relationshipLabel>DocuSign Envelope Recipient Status</relationshipLabel>
        <relationshipName>DocuSignEnvelopeRecipientStatus</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Envelope Recipient Status</description>
        <inlineHelpText>Envelope Recipient Status</inlineHelpText>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope Recipient Status</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>DocuSignEnvelopeRecipientStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Envelope Recipient Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IQVIA_Agreement__c.object
<CustomObject>
    <description>CLM-MC-CLMCMA-17657 - Represents an agreement in the system</description>
    <fields>
        <fullName>Status_Category__c</fullName>
        <description>CLM-MC-CLMCMA-17657 - The higher level state of the agreement – In Authoring, In Effect, Expired, etc. These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>In Approval</fullName>
                    <isActive>false</isActive>
                    <label>In Approval</label>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                    <isActive>false</isActive>
                    <label>In Filing</label>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                    <isActive>false</isActive>
                    <label>Renewed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CLM-MC-CLMCMA-17657 - The sub stage of an agreement – the status underneath a given status category. These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:
Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated, Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Internal Legal Review</fullName>
                </value>
                <value>
                    <fullName>Feedback Awaited</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>Sent for Signatures</fullName>
                </value>
                <value>
                    <fullName>Pending Templates</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>                
                <value>
                    <fullName>Accepted</fullName>
                    <isActive>false</isActive>
                    <label>Accepted</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                    <isActive>false</isActive>
                    <label>Approved Request</label>
                </value>
                <value>
                    <fullName>BUR/Finance Review</fullName>
                    <isActive>false</isActive>
                    <label>BUR/Finance Review</label>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                    <isActive>false</isActive>
                    <label>Being Renewed</label>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                    <isActive>false</isActive>
                    <label>Being Terminated</label>
                </value>
                <value>
                    <fullName>Budget Customer Edits</fullName>
                    <isActive>false</isActive>
                    <label>Budget Customer Edits</label>
                </value>
                <value>
                    <fullName>Budget External Review</fullName>
                    <isActive>false</isActive>
                    <label>Budget External Review</label>
                </value>
                <value>
                    <fullName>Budget Internal Review</fullName>
                    <isActive>false</isActive>
                    <label>Budget Internal Review</label>
                </value>
                <value>
                    <fullName>Budget Preparation</fullName>
                    <isActive>false</isActive>
                    <label>Budget Preparation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IQVIA Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IQVIA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IQVIA_Agreement_Team__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <description>CLM-MC-CLMCMA-17944 - This field stores Id of associated IQVIA Agreement.</description>        
        <label>Agreement</label>
        <referenceTo>IQVIA_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Teams</relationshipLabel>
        <relationshipName>Agreement_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Team</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Agreement Team Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_DAOH_CLM_IQ_DocuSignEnvelopeRS.cls
/**
 * This is test class for DAOH_CLM_IQ_DocuSignEnvelopeRS class.
 */
@isTest
private class TST_DAOH_CLM_IQ_DocuSignEnvelopeRS {
    @testSetup
    static void dataSetup() {
        IQ_DocuSignEnvelopeRecipientStatus__c docuApiDocuSignEnvelopeReciStatus = new IQ_DocuSignEnvelopeRecipientStatus__c();
        IQ_DocuSignEnvelopeRecipientStatus__c docuApiDocuSignEnvelopeReciStatus1 = new IQ_DocuSignEnvelopeRecipientStatus__c();
        IQVIA_Agreement__c testAgreement = TST_CLM_TestDataFactory.createIQAgreement(CON_CLM.USBU_IQVIA_RECORDTYPEID, false);
        testAgreement.Status_Category__c = 'In Signatures';
        insert testAgreement;

        IQVIA_Agreement_Team__c testAgreementContact = TST_CLM_TestDataFactory.createIQAgreementContact(testAgreement, true, 'Account');
        IQVIA_Agreement_Team__c testAgreementContact1 = TST_CLM_TestDataFactory.createIQAgreementContact(testAgreement, true, 'Legal Entity 1');
        IQ_DocuSignEnvelope__c docuApiEnvelope = new IQ_DocuSignEnvelope__c();
        docuApiEnvelope.Agreement__c = testAgreement.Id;
        insert docuApiEnvelope;

        docuApiDocuSignEnvelopeReciStatus.DocuSignEnvelopeId__c = docuApiEnvelope.Id;
        docuApiDocuSignEnvelopeReciStatus.Email__c = 'testcontactRec1@example.com';
        docuApiDocuSignEnvelopeReciStatus.RoleName__c = 'Signer';
        docuApiDocuSignEnvelopeReciStatus.RecipientName__c = 'Test';
        docuApiDocuSignEnvelopeReciStatus.SignedDateTime__c = System.now();
        docuApiDocuSignEnvelopeReciStatus.Status__c = CON_CLM.COMPLETED_STATUS;
        docuApiDocuSignEnvelopeReciStatus.Title__c = 'test title';
        insert docuApiDocuSignEnvelopeReciStatus;

        docuApiDocuSignEnvelopeReciStatus1.DocuSignEnvelopeId__c = docuApiEnvelope.Id;
        docuApiDocuSignEnvelopeReciStatus1.Email__c = 'testcontactRec2@example.com';
        docuApiDocuSignEnvelopeReciStatus1.RoleName__c = 'Signer';
        docuApiDocuSignEnvelopeReciStatus1.RecipientName__c = 'Test 2';
        docuApiDocuSignEnvelopeReciStatus1.SignedDateTime__c = System.now();
        docuApiDocuSignEnvelopeReciStatus1.Status__c = CON_CLM.COMPLETED_STATUS;
        docuApiDocuSignEnvelopeReciStatus1.Title__c = 'test title 2';
        insert docuApiDocuSignEnvelopeReciStatus1;
    } 

    @isTest
    private static void testUpdateSignerDetailsInAgreement(){
        List<IQ_DocuSignEnvelopeRecipientStatus__c> lstDocuSignEnvelopeRecipientStatus = new List<IQ_DocuSignEnvelopeRecipientStatus__c>();
        IQ_DocuSignEnvelopeRecipientStatus__c docuApiDocuSignEnvelopeReciStatus1 = [SELECT Id, DocuSignEnvelopeId__c, Email__c, RoleName__c, RecipientName__c, 
            SignedDateTime__c, Status__c, Title__c FROM IQ_DocuSignEnvelopeRecipientStatus__c WHERE Email__c = 'testcontactRec1@example.com'];
        IQ_DocuSignEnvelopeRecipientStatus__c docuApiDocuSignEnvelopeReciStatus2 = [SELECT Id, DocuSignEnvelopeId__c, Email__c, RoleName__c, RecipientName__c, 
            SignedDateTime__c, Status__c, Title__c FROM IQ_DocuSignEnvelopeRecipientStatus__c WHERE Email__c = 'testcontactRec2@example.com'];
        lstDocuSignEnvelopeRecipientStatus.add(docuApiDocuSignEnvelopeReciStatus1);
        lstDocuSignEnvelopeRecipientStatus.add(docuApiDocuSignEnvelopeReciStatus2);

        Test.startTest();
            DAOH_CLM_IQ_DocuSignEnvelopeRS.updateSignerDetailsInAgreement(lstDocuSignEnvelopeRecipientStatus);
        Test.stopTest();

        Integer expected = 2;
        Integer actual = [Select Id From IQ_DocuSignEnvelopeRecipientStatus__c].size();
        system.assertEquals(expected, actual);
    }
}