src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BNF_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BNF_Release__c</fullName>
        <label>BNF Release</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BNF_Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Current_Release_Version__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-MC-ESPSFDCQI-3242 - This custom setting holds the current release version</description>
    <fields>
        <fullName>Current_Release__c</fullName>
        <description>CRM-MC-ESPSFDCQI-2944 - Field to store the current release</description>
        <inlineHelpText>Field to store the current release</inlineHelpText>
        <label>Current Release</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Current Release Version</label>
</CustomObject>

src/objects/MIBNF2__c.object
<CustomObject>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the name of the Revenue Analyst who will be processing the BNF.</inlineHelpText>
        <label>Revenue Analyst</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Revenue_Analyst__c.Available_for_Selection__c</field>
                <operation>equals</operation>
                <value>TRUE</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>$Source.MIBNF_Status__c</field>
                <operation>notEqual</operation>
                <value>New</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Revenue_Analyst__c</referenceTo>
        <relationshipName>R00NT0000001UO6hMAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Multi Invoice BNF</label>
    <nameField>
        <displayFormat>MIBNF-{000000}</displayFormat>
        <label>MIBNF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Multi Invoice BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MIBNF_Component__c.object
<CustomObject>
    <description>Multi Invoice BNF Component which is child BNF for an Opportunity</description>
    <fields>
        <fullName>JSON_Correction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>JSON Correction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OLI_Json_Data_1__c</fullName>
        <label>OLI Json Data 1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OLI_Json_Data_2__c</fullName>
        <label>OLI Json Data 2</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OLI_Json_Data_3__c</fullName>
        <label>OLI Json Data 3</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <formula>MIBNF__r.Revenue_Analyst__r.User__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue Analyst</label>
        <type>Text</type>
    </fields>
    <label>BNF</label>
    <nameField>
        <label>BNF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mulesoft_Integration_Control__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-QI-ESPSFDCQI-784 - Custom setting to control various aspects of Mulesoft integration (suppress outbound messages etc.)</description>
    <fields>
        <fullName>Enable_OLIS_JSON__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CRM-MC-ESPSFDCQI-768</description>
        <label>Enable OLIS JSON</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_OLI_Sync_Validation__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CRM-MC-ESPSFDCQI-1052</description>
        <label>Enable OLI Sync Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Opportunity_Sync_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-1083</description>
        <label>Enable Opportunity Sync Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Mulesoft_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-768</description>
        <label>Is Mulesoft User</label>
        <type>Checkbox</type>
    </fields>
    <label>Mulesoft Integration Control</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Is_this_IQVIA_Biotech__c</fullName>
        <description>ESPSFDCQI-4742</description>
        <label>Is this IQVIA Biotech</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Update_Type__c</fullName>
        <defaultValue>&apos;USER&apos;</defaultValue>
        <description>CRM-QI-ESPSFDCQI-1083 Field to specify type of update that is occurring (user update / talkback update via Mulesoft integration / slave update via Mulesoft integration)</description>
        <inlineHelpText>Field to specify type of update that is occurring (user update / talkback update via Mulesoft integration / slave update via Mulesoft integration)</inlineHelpText>
        <label>Update Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Hierarchy_Level__c</fullName>
        <description>CRM-MC-ESPSFDCQI-68 -  Formula field that references the Products Hierarchy Level.</description>
        <formula>TEXT(PricebookEntry.Product2.Hierarchy_Level__c)</formula>
        <inlineHelpText>Details where the Product is set within the Product hierarchy.</inlineHelpText>
        <label>Hierarchy Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JSON_Correction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>JSON Correction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LI_OpportunityLineItem_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC Id of shadow OpportunityLineItem record in legacy IMS org</description>
        <externalId>true</externalId>
        <inlineHelpText>SFDC Id of shadow OpportunityLineItem record in legacy IMS org</inlineHelpText>
        <label>LI OpportunityLineItem Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Update_Type__c</fullName>
        <defaultValue>&apos;USER&apos;</defaultValue>
        <description>CRM-QI-ESPSFDCQI-1052 Field to specify type of update that is occurring (user update / talkback update via Mulesoft integration / slave update via Mulesoft integration)</description>
        <inlineHelpText>Field to specify type of update that is occurring (user update / talkback update via Mulesoft integration / slave update via Mulesoft integration)</inlineHelpText>
        <label>Update Type</label>
        <length>36</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Hierarchy_Level__c</fullName>
        <description>CRM-MC-ESPSFDCQI-68 - Details where the Product is set within the Product Hierarchy.</description>
        <label>Hierarchy Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Analyst__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-3168 - This custom object is used to store the Revenue Analyst.</description>
    <label>Revenue Analyst</label>
    <nameField>
        <label>Revenue Analyst Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Analysts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_BCH_CRM_UpdateMIBNFJSONData.cls
@isTest
public class TST_BCH_CRM_UpdateMIBNFJSONData {

    @testSetup
    static void dataSetup() {
        Current_Release_Version__c crv = new Current_Release_Version__c();
        crv.Current_Release__c = '3000.01';
        upsert crv;
        BNF_Settings__c bs = new BNF_Settings__c();
        bs.BNF_Release__c = '2019.01';
        upsert bs;
        upsert new  Mulesoft_Integration_Control__c(Enable_OLIS_JSON__c = true, Is_Mulesoft_User__c = false, Enable_OLI_Sync_Validation__c = true, Enable_Opportunity_Sync_Validation__c = true);
        Account acc = UTL_TestData.createAccount();
        insert acc;
        Contact cnt = UTL_TestData.createContact(acc.Id);
        insert cnt;
        Opportunity opp = UTL_TestData.createOpportunity(acc.Id);
        opp.Is_this_IQVIA_Biotech__c = 'No';
        insert opp;
        Product2 product = UTL_TestData.createProduct();
        product.Hierarchy_Level__c = CON_CRM.MATERIAL_LEVEL_HIERARCHY_OLI;
        insert product;
        PricebookEntry pbEntry = UTL_TestData.createPricebookEntry(product.Id);
        insert pbEntry;
        OpportunityLineItem oppLineItem = UTL_TestData.createOpportunityLineItem(opp.Id, pbEntry.Id);
        oppLineItem.Description = 'Testing';
        oppLineItem.Update_Type__c = CON_CRM.UPDATE_TYPE_MULESOFT_SLAVE;
        oppLineItem.LI_OpportunityLineItem_Id__c = opp.id;
        insert oppLineItem;
        OpportunityLineItemSchedule olis = UTL_TestData.createOpportunityLineItemSchedule(oppLineItem.Id);
        insert olis;
        Revenue_Analyst__c revenueAnalyst = UTL_TestData.createRevenueAnalyst();
        insert revenueAnalyst;
        MIBNF2__c TestMIBNF = UTL_TestData.createMIBNF(opp, revenueAnalyst);
        insert TestMIBNF;
    }
    
    static testMethod void test1(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        MIBNF2__c TestMIBNF = [SELECT Id FROM MIBNF2__c LIMIT 1];
        OpportunityLineItem oppLineItem = [SELECT Id, Product2Id FROM OpportunityLineItem LIMIT 1];
        Test.startTest();
            List<Address__c> addressesList = UTL_TestData.createAddresses(acc);
            insert addressesList;
            MIBNF_Component__c TestMIBNF_Comp = UTL_TestData.createMIBNF_Comp(TestMIBNF,addressesList);
            TestMIBNF_Comp.JSON_Correction__c = true;
            TestMIBNF_Comp.OLI_Json_Data_1__c = JSON.serialize(new List<OpportunityLineItem>{oppLineItem});
            TestMIBNF_Comp.OLI_Json_Data_2__c = JSON.serialize(new List<OpportunityLineItem>{oppLineItem});
            TestMIBNF_Comp.OLI_Json_Data_3__c = JSON.serialize(new List<OpportunityLineItem>{oppLineItem});
            insert TestMIBNF_Comp;
            Database.executeBatch(new BCH_CRM_UpdateMIBNFJSONData());
        Test.stopTest();
    }
}