src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Choose the account location&apos;s country from the picklist.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chad</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_Territory__c</fullName>
        <formula>IF(Account__c != null, IF(ISBLANK(TEXT(Account__r.Region_Territory__c)) , TEXT(Account__r.AccountCountry__c), TEXT(Account__r.Region_Territory__c)) , 
		IF(ISBLANK(TEXT(Deleted_Account__r.Region_Territory__c)), TEXT(Deleted_Account__r.AccountCountry__c), (TEXT(Deleted_Account__r.Region_Territory__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1026</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IMS_Legal_Entity__c.object
<CustomObject>
    <description>Created By TPA Module Under TPA-FEATURE-5</description>
    <fields>
        <fullName>IMS_Master_Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created By TPA Module Under TPA-FEATURE-5</description>
        <label>IMS Master Legal Entity</label>
        <referenceTo>IMS_Master_Legal_Entity__c</referenceTo>
        <relationshipLabel>IMS Legal Entities</relationshipLabel>
        <relationshipName>IMS_Legal_Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Title__c</fullName>
        <description>Created By TPA Module Under TPA-FEATURE-5</description>
        <formula>IMS_Master_Legal_Entity__r.Legal_Entity_Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Legal Entity Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_for_ESign__c</fullName>
        <description>Created By TPA Module Under TPA-FEATURE-5</description>
        <formula>IMS_Master_Legal_Entity__r.Name_for_ESign__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name for ESign</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPA_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TPA Request</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipLabel>IMS Legal Entities</relationshipLabel>
        <relationshipName>IMS_Legal_Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IMS Legal Entity</label>
    <nameField>
        <label>IMS Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMS Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IMS_Master_Legal_Entity__c.object
<CustomObject>
    <description>Created By TPA Module Under TPA-FEATURE-5</description>
    <fields>
        <fullName>Legal_Entity_Title__c</fullName>
        <description>Created By TPA Module Under TPA-FEATURE-5</description>
        <label>Legal Entity Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_for_ESign__c</fullName>
        <description>Created By TPA Module Under TPA-FEATURE-5</description>
        <label>Name for ESign</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>IMS Master Legal Entity</label>
    <nameField>
        <label>IMS Master Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IMS Master Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TPA_Request__c.object
<CustomObject>
    <fields>
        <fullName>ClientContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client TPA Requestor Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>TPA Requests(Client)</relationshipLabel>
        <relationshipName>TPA_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Client)</relationshipLabel>
        <relationshipName>TPA_Requests_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Access_Start_Date__c</fullName>
        <label>Data Access Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Provider_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Legal Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Vendor is not a TPA Vendor.</errorMessage>
            <filterItems>
                <field>Address__c.Is_TPA_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Request_Status__c</field>
                <operation>equals</operation>
                <value>Cancelled, Expired, In Effect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Service Provider)</relationshipLabel>
        <relationshipName>TPA_Requests1_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Today_Date_TLLA__c</fullName>
        <formula>IF( Data_Access_Start_Date__c - TODAY() &gt; 0, TEXT(MONTH(Data_Access_Start_Date__c ))+&quot;/&quot; +TEXT(DAY(Data_Access_Start_Date__c ))+&quot;/&quot; +TEXT(YEAR(Data_Access_Start_Date__c )) , TEXT(MONTH(TODAY()))+&quot;/&quot; +TEXT(DAY(TODAY()))+&quot;/&quot; +TEXT(YEAR(TODAY())) )</formula>
        <label>TLLA Effective Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Billing_Mailing_Country__c</fullName>
        <label>Vendor Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Congo</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TPA Request</label>
    <nameField>
        <label>Client Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TPA_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>email recipients</description>
    <fields>
        <fullName>Base_Url_Public__c</fullName>
        <label>Base Url Public</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Is_Template_Watermark_Automated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ESPSFDCTPA-1508: This field is to control watermark in APTTUS generated document based on production/sandbox org</description>
        <label>Is Template Watermark Automated</label>
        <type>Checkbox</type>
    </fields>
    <label>TPA Settings</label>
</CustomObject>

src/classes/CNT_TPA_Helpful_Hints_Addendum.cls
global class CNT_TPA_Helpful_Hints_Addendum { 
    public static string Id {get; set;}
    public static Map<Id,IMS_Legal_Entity__c> mapIdWithLegalEntityList{get; set;}    

    public Boolean isDisplayWatermark {get; set;}
    public string requestName {get; set;}
    public string title {get; set;}
    public static string openmode {get; set;} 
    public string aggNo {get; set;}
    public string aggStartDate {get; set;}
    public static TPA_Request__c tpaRequest {get; set;}
    public String helpfulAddendumNote{get; set;}
    public String helpfulAddendumNote1{get; set;}
    public String helpfulAddendumNote2{get; set;}
    public String helpfulAddendumNote3{get; set;}
    public String helpfulAddendumNote4{get; set;}
    public String helpfulAddendumNote5{get; set;}
    public String helpfulAddendumNote6{get; set;}
    public String helpfulAddendumNote7{get; set;}
    public String helpfulAddendumNote8{get; set;}
    
    public static Map<ID, IMS_Master_Legal_Entity__c> mapOfIdWithlegalEntityObj;
    
    public static Map<Id,wrapperClassOfLegalEntity> mapIdWithObjofwrapperClassOfLegalEntity{get; set;}


     
    public string wordStyle {get; set;}
    public string docTitle {get; set;}
    public string contentStyle {get; set;}
    public string headerStyle {get; set;}
    public string boldEffect {get; set;}
    public string contentParagraph {get; set;}
    public string centerAlign {get; set;}
    public string underlineEffect {get; set;}
    public string italicEffect {get; set;}
    public string marginT1Left {get; set;}
    public string marginT2Left {get; set;}
    public string marginT1Bottom {get; set;}
    public string marginDocOnly1 {get; set;}
    public string margin1 {get; set;}
    public string columnStyle {get; set;}
    public string addendumText {get; set;}

    public string language{
        get{
            system.debug('++'+language);
            return language;
        }
        set;
    }
    public static void loadDataForHelpfulAddendumDocument() {
        system.debug('Inside loadDataForHelpfulAddendumDocument');
        CNT_TPA_RequestSubmissionForm.getLimitsMessage();
        
        mapIdWithLegalEntityList = new Map<Id,IMS_Legal_Entity__c>();

        Id legalEntityId = null;

        for(IMS_Legal_Entity__c obj: [SELECT Id, Name,Name_for_ESign__c ,IMS_Master_Legal_Entity__c,IMS_Master_Legal_Entity__r.id From IMS_Legal_Entity__c Where TPA_Request__c =: Id]) {
            legalEntityId = obj.IMS_Master_Legal_Entity__r.id;
			mapIdWithLegalEntityList.put(obj.IMS_Master_Legal_Entity__r.id, obj);
        }

        mapOfIdWithlegalEntityObj = new Map<ID, IMS_Master_Legal_Entity__c>([Select Name,Name_for_ESign__c,Legal_Entity_Title__c FROM IMS_Master_Legal_Entity__c ]);

        IMS_Master_Legal_Entity__c legalEntityObj;
        string url;
        String name = '';
        mapIdWithObjofwrapperClassOfLegalEntity= new Map<Id,wrapperClassOfLegalEntity>();
        ID legalEntityDocid = null;

        for(Id IdofLegalEntity : mapIdWithLegalEntityList.keySet()) {
            if(mapOfIdWithlegalEntityObj != null && !mapOfIdWithlegalEntityObj.isEmpty() && mapOfIdWithlegalEntityObj.containsKey(IdofLegalEntity)) {
                legalEntityObj = mapOfIdWithlegalEntityObj.get(IdofLegalEntity);
                if(legalEntityObj != null && legalEntityObj.name != null){
                    name = legalEntityObj.name.replaceall('[^a-zA-Z0-9]','_').replaceall('[_ ]+','_').removeEnd('_');
                }
            }

            List<Document> lstdoc = [SELECT Id, FolderId, Folder.Name,SystemModstamp FROM Document WHERE DeveloperName like :name LIMIT 1]; //will review, query in for loop
            if(lstdoc != null && lstdoc.size() >0 ){
               legalEntityDocid =  lstdoc[0].id;
            }
            system.debug('legalEntityDocid:'+legalEntityDocid);
                url =  TPA_Settings__c.getOrgDefaults().Base_Url_Public__c+'/servlet/servlet.ImageServer?id=' +legalEntityDocid+'&oid='+UserInfo.getOrganizationId()+'&contentType=image/png';
        
            mapIdWithObjofwrapperClassOfLegalEntity.put(IdofLegalEntity,new wrapperClassOfLegalEntity(legalEntityObj.name,url,legalEntityObj.Legal_Entity_Title__c,legalEntityObj.Name_for_ESign__c, ''));
        }
        CNT_TPA_RequestSubmissionForm.getLimitsMessage();
    }

     public void LoadStyles(){
        if(openMode == 'word'){
            headerStyle = 'font-family: Arial Narrow;font-size:10.0pt;';
            contentStyle = 'font-family: Arial;font-size:8.0pt;';
            contentParagraph = 'font-family: Arial;font-size:8.0pt;text-align:justify;';
            marginT1Left = 'margin-left:80px;';
            marginT2Left = 'margin-left:20px;';
            marginT1Bottom = 'margin-bottom:10px;';
            marginDocOnly1 = 'margin:0.001in 0.03in 0.03in 0.0in;';
            margin1 = 'margin:0.05in;';
            columnStyle = 'border:1px solid black;text-align:center;';

        }
        else{
            headerStyle = 'font-family: Dialog;font-size:13px;';
            contentStyle = 'font-family: Dialog;font-size:11px;';
            contentParagraph = 'font-family: Dialog;font-size:11px;text-align:justify;';
            marginT1Left = 'margin-left:40px;';
            marginT2Left = 'margin-left:15px;';
            marginT1Bottom = 'margin-bottom:10px;';
            marginDocOnly1 = '';
            margin1 = 'margin:5px;';
            columnStyle = '';
        }
        boldEffect = 'font-weight:bolder;';
        centerAlign = 'text-align:center;';
        underlineEffect = 'text-decoration:underline;';
        italicEffect = 'font-style:italic;';
        wordStyle = '<style>.useDefStyle p {margin:0.0in;} .useDefStyle ol ol li p {margin:0.04in 0.0in 0.1in 0.0in;}</style>';
        addendumText = 'text-align: center; display: table; margin-left: auto; margin-right: auto;';
    }
    public String getPrintView(){
        return
        '<!--[if gte mso 9]>' +
            '<xml>' +
            '<w:WordDocument>' +
            '<w:View>Print</w:View>' +
            '<w:Zoom>125</w:Zoom>' +
            '<w:DoNotOptimizeForBrowser/>' +
            '</w:WordDocument>' +
            '</xml>' +
            '<![endif]>' +
            '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />' +
            '<style>' +
            'p.MsoHeader, li.MsoHeader, div.MsoHeader{margin:0in;margin-top:.0001pt;margin-left:0.8in;mso-pagination:widow-orphan;tab-stops:center 3.0in right 6.0in;}' +
            'p.MsoFooter, li.MsoFooter, div.MsoFooter{margin:0in;margin-bottom:.0001pt;margin-left:-0.45in;mso-pagination:widow-orphan;tab-stops:center 3.0in right 6.0in;}' +
            '@page main{mso-header:h1;mso-footer:f1;}' +
            'div.main{page:main;}' +
            'table#hrdftrtbl{margin:0in 0in 0in 15in;}' +
            '</style>';

    }

    

    public class wrapperClassOfLegalEntity{
        public wrapperClassOfLegalEntity(String legalEntityName,String legalentityurl, String legalEntityTitle,String EsignName, String helpfulAddendumNote){
            name = legalEntityName;
            url = legalentityurl;
            title = legalEntityTitle;
            NameOfESign = EsignName;
            helpfulAddendumNote = helpfulAddendumNote;

        }
        public string url {get;set;}
        public string name {get;set;}
        public string title {get;set;}
        public string NameOfESign {get;set;}
        public string helpfulAddendumNote {get;set;}
    }

    public string vendorLanguage { get; set; }
    public static Map<String, String> supportedLanguageMap{
        get{
            if(supportedLanguageMap == null)
            {
                supportedLanguageMap = new Map<String, String>();
                for(string langCodeMapObj :UTL_TPA_Multilingual.mlGlobalSettings.Supported_Language_Field_Map__c.split(';'))
                {
                    supportedLanguageMap.put(langCodeMapObj.split('~')[0], langCodeMapObj.split('~')[1]);
                }        
            }
            return supportedLanguageMap;
        }
        private set;
    }

    public CNT_TPA_Helpful_Hints_Addendum(){
        system.debug('inside CNT_TPA_Helpful_Hints_Addendum constructor');
        Id = ApexPages.currentPage().getParameters().get('id');
        openmode = ApexPages.currentPage().getParameters().get('mode');
        aggNo = ApexPages.currentPage().getParameters().get('aggNo');
        aggStartDate = ApexPages.currentPage().getParameters().get('aggStartDate');
        isDisplayWatermark = false;
        if(UTL_TPA.tpaSetting.Is_Template_Watermark_Automated__c) {
            isDisplayWatermark = UTL_TPA.isSandboxOrg;
        }

        tpaRequest = [Select Id, name,Client_Address__c,Client_Address__r.Name, Client_Address__r.Region_Territory__c, Client_Address__r.Country__c,
                                     ClientContact__r.firstName,ClientContact__r.lastname,ClientContact__r.Email ,
                                     Service_Provider_Address__r.Name,Today_Date_TLLA__c,Vendor_Billing_Mailing_Country__c,
                                     Data_Access_Start_Date__c,Service_Provider_Address__r.Parent_Vendor_Name__c,Service_Provider_Address__c,Vendor_Language__c,TLLA_Language_Chosen__c,
                                     Today_s_Date__c
                                     FROM TPA_Request__c where id = :Id];
        docTitle = 'TPA Helpful Hints Addendum' ;  
        vendorLanguage = tpaRequest.TLLA_Language_Chosen__c != null ? tpaRequest.TLLA_Language_Chosen__c : (tpaRequest.Vendor_Language__c != null ? tpaRequest.Vendor_Language__c : 'English');
        language = vendorLanguage == 'French' ? 'fr' : 'en_US';
        Date dataAccessstartDate = tpaRequest.Data_Access_Start_Date__c;
        LoadStyles();
        loadDataForHelpfulAddendumDocument();
        List<TPA_Text_Editor__C> listTPA = [Select Id, Content__c, Page_Name__c, Page_Title__c, Page_Type__c, English_Translation__c, Japanese_Translation__c, French_Translation__c FROM TPA_Text_Editor__c WHERE Page_Type__c = 'Helpful Hints Addendum'];
        for(TPA_Text_Editor__C textEditor: listTPA){
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum'){
                for(Id legalEntityId: mapIdWithObjofwrapperClassOfLegalEntity.keySet()){
                    helpfulAddendumNote = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
                    helpfulAddendumNote = helpfulAddendumNote.replace('Client_Request_Number',tpaRequest.Name);
                    helpfulAddendumNote = helpfulAddendumNote.replace('TLLA_Effective_Date', DateTime.newInstance(dataAccessstartDate.year(),dataAccessstartDate.month(),dataAccessstartDate.day()).format('MM/dd/YY'));
                    helpfulAddendumNote = helpfulAddendumNote.replace('IMS_Legal_Entity_Name',mapIdWithObjofwrapperClassOfLegalEntity.get(legalEntityId).Name);
                    helpfulAddendumNote = helpfulAddendumNote.replace('Vendor_Legal_Name',tpaRequest.Service_Provider_Address__r.name);
                    helpfulAddendumNote = helpfulAddendumNote.replace('<strong>','<b class="boldEffect">');
                    helpfulAddendumNote = helpfulAddendumNote.replace('</strong>','</b>');
                    mapIdWithObjofwrapperClassOfLegalEntity.get(legalEntityId).helpfulAddendumNote = helpfulAddendumNote;
                }
                
            }
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum 1'){
                helpfulAddendumNote1 = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
            }
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum 2'){
                helpfulAddendumNote2 = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
            }
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum 3'){
                helpfulAddendumNote3 = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
            }
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum 4'){
                helpfulAddendumNote4 = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
            }
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum 5'){
                helpfulAddendumNote5 = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
            }
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum 6'){
                helpfulAddendumNote6 = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
            }
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum 7'){
                helpfulAddendumNote7 = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
            }
            if(textEditor.Page_Name__c == 'TPA Helpful Hints Addendum 8'){
                helpfulAddendumNote8 = textEditor.get(supportedLanguageMap.get(vendorLanguage)) != null ? String.valueOf(textEditor.get(supportedLanguageMap.get(vendorLanguage))) : String.valueOf(textEditor.Content__c);
            }
            
        }
        
    }

    
    public static void generateHelpfulHintsAddendumDoc(Id reqId, String mode, String argGUID) { // Debug log change
        // Debug log change
        if(UTL_Validate.isValidGuid(argGUID)) {
            UTL_LogFactory.GUID = argGUID; 
        }
        TPA_Request__c objTpaRequest;
        // Debug log change
        try {
            objTpaRequest = SRV_TPA_TPARequest.getRequestInfo(reqId); // Debug log change
            system.debug('Helpful Hints Addendum Generation::::');

            PageReference pdf = Page.VFP_TPA_Helpful_Hints_Addendum;
            pdf.getParameters().put('mode', mode); 
            pdf.getParameters().put('id',reqId);
            pdf.getParameters().put('aggNo',objTpaRequest.Name);
            pdf.getParameters().put('aggStartDate',string.valueOfGmt(objTpaRequest.Data_Access_Start_Date__c));
            Blob body;
            if (Test.IsRunningTest()) {
                body = Blob.valueOf('UNIT.TEST');
            }
            else {
                body = pdf.getContentAsPDF();
            }
            Attachment attach = new Attachment();
            attach.Body = body;
            
            if(mode == 'word'){
                attach.Name = objTpaRequest.Name + '_TPA Helpful Hints Addendum.doc';
            }
            else{
                attach.Name = objTpaRequest.Name + '_TPA Helpful Hints Addendum.pdf';
            } 

            attach.IsPrivate = false;
            attach.ParentId = reqId;
            insert attach;
            string taskSubject = 'TPA Helpful Hints Addendum';
            SRV_TPA_TPARequest.updateActivityHistory(reqId,'Generated ' + taskSubject, true);
        } catch(Exception ex) {
            UTL_LogFactory.getLogLst().Add(UTL_LogFactory.generateAndCommitLog(FALSE, FALSE, UTL_LogFactory.GUID, ex.getMessage(), 'TPA', 'Exception', 'ERROR', 'Line#' + ex.getLineNumber() + ':::CNT_TPA_Helpful_Hints_Addendum:::generateAddendumNotificationDoc', reqId != null ? reqId : ''));
            UTL_LogFactory.saveLogs(UTL_LogFactory.getLogLst(), TRUE);
             
        }
      }


    
}