src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Choose the account location&apos;s country from the picklist.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chad</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_TPA_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked only when an account is created for TPA Functionality</inlineHelpText>
        <label>Is TPA Account?</label>
        <type>Checkbox</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMA_Contract_Detail__c.object
<CustomObject>
    <description>Received data from the AMA Client list and Lettershop List</description>
    <fields>
        <fullName>Client_Services_On_Behalf_Of__c</fullName>
        <label>Client Services - On Behalf Of</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <description>Vendor&apos;s Name</description>
        <label>Client</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TPA AMA Contract Detail</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>AMA Contract Detail Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TPA AMA Contract Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TPA_AMA_Client_Vendor_Match__c.object
<CustomObject>
    <fields>
        <fullName>Client_Name__c</fullName>
        <externalId>true</externalId>
        <label>Client Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Client_Services_On_Behalf_Of__c</fullName>
        <label>Client Services - On Behalf Of</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IMS_Client_Names__c</fullName>
        <label>IMS Client Names</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IMS_Total_Clients__c</fullName>
        <label>IMS Total Clients</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mapped_Account_Id__c</fullName>
        <label>Mapped Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mapped_Account_Name__c</fullName>
        <label>Mapped Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Client_Vendor__c</fullName>
        <label>New Client/Vendor?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Client/Vendor</fullName>
                </value>
                <value>
                    <fullName>Old Client/Vendor With no Mapping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Truncated_Name__c</fullName>
        <label>Truncated Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TPA AMA Client Vendor Match</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>TPA AMA Client Vendor Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TPA AMA Client Vendor Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TPA_AMA_Client_Vendor_Search_Map__c.object
<CustomObject>
    <fields>
        <fullName>AMA_Account_Search_Text__c</fullName>
        <externalId>true</externalId>
        <label>AMA Client/Vendor</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>TPA AMA Client Vendor Search Map</label>
    <nameField>
        <displayFormat>ACV-{0000}</displayFormat>
        <label>TPA AMA Client Vendor Search Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TPA AMA Client Vendor Search Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TPA_AMA_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To Store All the AMA Setting</description>
    <fields>
        <fullName>Dev_Mail_ID_For_Internal_Mails__c</fullName>
        <label>Dev Mail ID For Internal Mails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TPA AMA Settings</label>
</CustomObject>

src/classes/BCH_TPA_AMA_New_Client_Vendor_Script.cls
/**
* @author : Supriya Johari
* To find new Clients and vendors in AMA Process
* Modified the class under ER-3884
*/

global class BCH_TPA_AMA_New_Client_Vendor_Script implements Database.Batchable<sObject>, Database.Stateful {
    public List<AMA_Contract_Detail__c> amaContracts;

    // to truncate Client and vendor name
    public Set<String>charactersToBeTruncated;

    // possible names for usa
    public Set<String>usaPossibleNames;

    public String truncatedName;

    public Map<String, TPA_AMA_Client_Vendor_Match__c> ClientWithTruncatedName = new Map<String, TPA_AMA_Client_Vendor_Match__c>();

    global BCH_TPA_AMA_New_Client_Vendor_Script() {
        usaPossibleNames = new Set<String> {
            'US'
            , 'U.S.'
            , 'USA'
            , 'United States Of America'
            , 'U.S'
            , 'U.S.A'
            , 'United States'
            , 'U.S.A.'
        };
        charactersToBeTruncated = new Set<String> {
            ', inc'
            , ',inc'
            , ' inc'
            , ' inc.'
            , ',inc.'
            , ', inc.'
            , ', llc'
            , ',llc'
            , ' llc'
            , ', llp'
            , ',llp'
            , ' llp'
            , ', corp'
            , ',corp'
            , ' corp'
            , ', lp'
            , ',lp'
            , ' lp'
            , ', ltd'
            , ',ltd'
            , ' ltd'
            , ' ltd.'
            , ', ltd.'
            , ',ltd.'
            , ', l.p.'
            , ',l.P.'
            , ' l.p.'
            , ', us'
            , ',us'
            , ' us'
            , ' &co'
            , ' & co'
            , '. co'
            , '.co'
            , ' co.'
            , ' and company'
            , ' pvt'
            , ' pvt.'
        };
        ClientWithTruncatedName = new Map<String, TPA_AMA_Client_Vendor_Match__c>();

        // to get Client names for which mapping is provided
        List<TPA_AMA_Client_Vendor_Search_Map__c> amaClientVendorSearchList = [select id, AMA_Account_Search_Text__c from TPA_AMA_Client_Vendor_Search_Map__c];

        Set<String> searchMap = new Set<String>();

        for(TPA_AMA_Client_Vendor_Search_Map__c amaClientsSearchMap: amaClientVendorSearchList) {
            if(String.isNotBlank(amaClientsSearchMap.AMA_Account_Search_Text__c))
                searchMap.add(amaClientsSearchMap.AMA_Account_Search_Text__c.toLowerCase());
        }

        // to get all the client and vendors names which does not exist in search Map
        amaContracts = [Select id, Client__c, Client_Services_On_Behalf_Of__c from AMA_Contract_Detail__c where(NOT Client__c Like 'Test_%') AND(NOT Client_Services_On_Behalf_Of__c Like 'Test_%')];
        Set<String> clientSet = new Set<String>();

        for(AMA_Contract_Detail__c amaContract: amaContracts) {
            TPA_AMA_Client_Vendor_Match__c matchObject;

            // for client
            if(String.isNotBlank(amaContract.Client__c) && !searchMap.contains(amaContract.Client__c.trim().toLowerCase())) {
                matchObject = new TPA_AMA_Client_Vendor_Match__c();
                matchObject.Client_Name__c = amaContract.Client__c.trim();
                matchObject.Truncated_Name__c = getTruncatedName(amaContract.Client__c.trim()).trim();
                ClientWithTruncatedName.put(amaContract.Client__c, matchObject);

            }

            // for vendor   
            if(String.isNotBlank(amaContract.Client_Services_On_Behalf_Of__c) && !amaContract.Client_Services_On_Behalf_Of__c.containsIgnoreCase('own behalf') && !searchMap.contains(amaContract.Client_Services_On_Behalf_Of__c.trim().toLowerCase())) {
                matchObject = new TPA_AMA_Client_Vendor_Match__c();
                matchObject.Client_Name__c = amaContract.Client_Services_On_Behalf_Of__c.trim();
                matchObject.Truncated_Name__c = getTruncatedName(amaContract.Client_Services_On_Behalf_Of__c.trim()).trim();
                ClientWithTruncatedName.put(amaContract.Client_Services_On_Behalf_Of__c, matchObject);
            }
        }

        //Deleting the existing AMA Client Vendor matching extracts
        List<TPA_AMA_Client_Vendor_Match__c> amaClientVendorMatchingList = [select id from TPA_AMA_Client_Vendor_Match__c];
        if(amaClientVendorMatchingList.size()>0) {
            delete amaClientVendorMatchingList;
        }

    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select id, name, Country__c, Is_TPA_Account__c From Address__c';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject>objList) {
        for(TPA_AMA_Client_Vendor_Match__c clientVendorMatch: ClientWithTruncatedName.values()) {
            clientVendorMatch.New_Client_Vendor__c = 'New Client/Vendor';
            for(sObject obj: objList) {
                Address__c acc = (Address__c) obj;
                if(String.isNotBlank(acc.name) && acc.name.startsWithIgnoreCase(clientVendorMatch.Truncated_Name__c)) {

                    if(String.isNotBlank(clientVendorMatch.IMS_Total_Clients__c))
                        clientVendorMatch.IMS_Total_Clients__c = clientVendorMatch.IMS_Total_Clients__c + '; ' + acc.name + '"' + acc.id + '"';
                    else
                        clientVendorMatch.IMS_Total_Clients__c = acc.name + '"' + acc.id + '"';

                    if(usaPossibleNames.contains(acc.Country__c) && acc.Is_TPA_Account__c == true) {
                        if(String.isNotBlank(clientVendorMatch.IMS_Client_Names__c))
                            clientVendorMatch.IMS_Client_Names__c = clientVendorMatch.IMS_Client_Names__c + '; ' + acc.name + '"' + acc.id + '"';
                        else
                            clientVendorMatch.IMS_Client_Names__c = acc.name + '"' + acc.id + '"';

                    }

                }
            }
        }

    }


    public String getTruncatedName(String ClientName) {
        Boolean Matched = false;
        truncatedName = ClientName;
        if(Matched == false) {
            for(String truncatedCharacters: charactersToBeTruncated) {

                if(truncatedName.endsWithIgnoreCase(truncatedCharacters)) {
                    truncatedName = truncatedName.removeEndIgnoreCase(truncatedCharacters).trim();
                    truncatedName = truncatedName.removeEnd(',');
                    system.debug('truncated name middle ' + truncatedName);
                    getTruncatedName(truncatedName);
                    Matched = true;
                }

            }
        }
        system.debug('truncated name end' + truncatedName);
        return truncatedName;
    }



    global void finish(Database.BatchableContext BC) {
        //Deleting the existing AMA Client Vendor matching extracts
        List<TPA_AMA_Client_Vendor_Match__c> amaClientVendorMatchingDeletedRecords = [select id from TPA_AMA_Client_Vendor_Match__c where IsDeleted = true ALL ROWS];
        if(amaClientVendorMatchingDeletedRecords.size()>0) {
            DataBase.emptyRecycleBin(amaClientVendorMatchingDeletedRecords);
        }

        List<TPA_AMA_Client_Vendor_Match__c> listToInsert = new List<TPA_AMA_Client_Vendor_Match__c>();


        listToInsert = ClientWithTruncatedName.values();

        for(TPA_AMA_Client_Vendor_Match__c matchObj: listToInsert) {

            List<String> matchAccountsList = new List<String>();
            List<String> mappedAccounts = new List<String>();
            if(String.isNotBlank(matchObj.IMS_Client_Names__c)) {
                matchAccountsList = matchObj.IMS_Client_Names__c.split('; ');
            }

            if(matchAccountsList.size() == 1) {
                mappedAccounts = matchAccountsList.get(0).split('"');
                if(mappedAccounts.size() >= 2) {
                    matchObj.Mapped_Account_Name__c = mappedAccounts.get(0);
                    matchObj.Mapped_Account_Id__c = mappedAccounts.get(1);
                }
            }
        }

        Set<TPA_AMA_Client_Vendor_Match__c> myset = new Set<TPA_AMA_Client_Vendor_Match__c>();
        List<TPA_AMA_Client_Vendor_Match__c> result = new List<TPA_AMA_Client_Vendor_Match__c>();
        myset.addAll(listToInsert);
        result.addAll(myset);
        Schema.SObjectField extrnalField = TPA_AMA_Client_Vendor_Match__c.Fields.Client_Name__c;
        DataBase.upsert(result, extrnalField, false);

        sendMailforNewClientsAndVendor();


    }

    public void sendMailforNewClientsAndVendor() {
        List<Messaging.SingleEmailMessage>mails = new List<Messaging.SingleEmailMessage>();

        // Step 1: Create a new Email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        // Step 2: Set list of people who should get the email
        List<TPA_AMA_Settings__c> amaSetting =  TPA_AMA_Settings__c.getall().values();

        // Step 3: Set who the email is sent from
        List<String> sendTo = new List<String>();
        if(amaSetting != null && amaSetting.size() > 0 && amaSetting.get(0).Dev_Mail_ID_For_Internal_Mails__c != null) {
            sendTo = amaSetting.get(0).Dev_Mail_ID_For_Internal_Mails__c.split(';');
            mail.setToAddresses(sendTo);
        }

        // Step 4. Set email contents - you can use variables!
        mail.setSubject('AMA Client/Vendor Matching extracts updated');
        String body = 'Dear AMA Developer,<br/><br/>';
        body += 'AMA Client/Vendor Matching extracts updated based on new AMA Contract Details file recently uploaded.<br/><br/>';
        body += '<b>Note:-</b> Please observe the matching extracts and send to Vijay if required.<br/><br/>';
        body += 'Thanks.<br/>';
        body += 'Salesforce.<br/>';
        body += 'Submitted by ' + UserInfo.getUserName() + '.<br/>';
        mail.setHtmlBody(body);

        // Step 5. Add your email to the master list
        mails.add(mail);
        
        if(!Test.isRunningTest()) {
            Messaging.sendEmail(mails);
        }
    }

}