src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/dsfs__DocuSign_Envelope__c.object
<CustomObject>
    <description>DocuSign Envelope for Salesforce</description>
    <fields>
        <fullName>dsfs__Document_Name__c</fullName>
        <description>Document Name</description>
        <inlineHelpText>This is a list of PDF Documents located in your Organization&apos;s Salesforce &quot;Documents Tab&quot;.  In order to send with DocuSign you must add a PDF to any of the folders within your Documents Tab in Salesforce.  To Send with other Formats click &quot;Learn More&apos;.</inlineHelpText>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dsfs__Source_Object__c</fullName>
        <description>Source Object</description>
        <inlineHelpText>Source Object</inlineHelpText>
        <label>Source Object</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <displayFormat>DSE-{0000000}</displayFormat>
        <label>DocuSign Envelope</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TPA_Multilingual_Template_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>All Email and Apttus templates mapping in all supported languages.</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Translated_Template_Id__c</fullName>
        <label>Setting Component Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TPA Multilingual Template Setting</label>
</CustomObject>

src/objects/TPA_Request__c.object
<CustomObject>
    <fields>
        <fullName>Client_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Client)</relationshipLabel>
        <relationshipName>TPA_Requests_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Language__c</fullName>
        <label>Client Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_CPC_Expiration_Notice_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is CPC Expiration Notice Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_CPC_Post_Expiration_Notice_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is CPC Post Expiration Notice Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_CPC_Renewal_Notice_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is CPC Renewal Notice Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMA Cancelled</fullName>
                </value>
                <value>
                    <fullName>AMA Discontinued</fullName>
                </value>
                <value>
                    <fullName>Awaiting Account Mgmt Communication</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Confirmation</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Modification</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Vendor Signature</fullName>
                </value>
                <value>
                    <fullName>Awaiting Vendor Submission</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Client Discontinued</fullName>
                </value>
                <value>
                    <fullName>Client Draft</fullName>
                </value>
                <value>
                    <fullName>Closed-IQVIA Affiliate</fullName>
                </value>
		<value>
                	<fullName>Covered By MOU</fullName>
            	</value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Draft Closed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Hold for TPA non-compliance</fullName>
                </value>
                <value>
                    <fullName>In Auto Approval Process</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Initializing Vendor</fullName>
                </value>
                <value>
                    <fullName>In Review By IQVIA</fullName>
                </value>
                <value>
                    <fullName>IQVIA Denied</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Pending IQVIA Review of Voided Envelope</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor AMA Fee Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Pending - Vendor Declined AMA Fees</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Response on Data Destruction from Prior TPAs</fullName>
                </value>
                <value>
                    <fullName>Signature Under Validation</fullName>
                </value>
                <value>
                    <fullName>TPA Approved Awaiting AMA Approval</fullName>
                </value>
                <value>
                    <fullName>Vendor Canceled ‘17 AMA-TPA Exp-12/31/16</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Provider_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Legal Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Vendor is not a TPA Vendor.</errorMessage>
            <filterItems>
                <field>Address__c.Is_TPA_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Request_Status__c</field>
                <operation>equals</operation>
                <value>Cancelled, Expired, In Effect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Service Provider)</relationshipLabel>
        <relationshipName>TPA_Requests1_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Billing_Mailing_Country__c</fullName>
        <label>Vendor Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Congo</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Language__c</fullName>
        <label>Vendor Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TPA Request</label>
    <nameField>
        <label>Client Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_DAOH_DocuSignEnvelopeDocument.cls
@isTest
public class TST_DAOH_DocuSignEnvelopeDocument {
    @isTest
    static void TestDAO_DocusignEnveDoc() {
        TPA_Multilingual_Template_Setting__c templateobj = new TPA_Multilingual_Template_Setting__c( Name = 'Test template', 
                                                                                                     Translated_Template_Id__c = '95E7F69B-6828-4A8B-93B9-20E73F2CE4DC', 
                                                                                                     label__c = 'Docusign Template');
        insert templateobj;
        
        
        Address__c testAccount1 = UTL_TPA_SetupTestData.getAccount();
        testAccount1.Name = 'Test Acc';
        insert testAccount1;

        TPA_Request__c tpaRequest1 = UTL_TPA_SetupTestData.getTestTPARequest();
        tpaRequest1.Request_Status__c = 'In Effect';
        tpaRequest1.OwnerId = UserInfo.getUserId();
        tpaRequest1.Service_Provider_Address__c = testAccount1.Id;
        tpaRequest1.Client_Address__c = testAccount1.Id;
        tpaRequest1.Client_Language__c = 'Japanese';
        tpaRequest1.Vendor_Language__c = 'Japanese';
        tpaRequest1.Vendor_Billing_Mailing_Country__c = 'united states';
        tpaRequest1.Is_CPC_Renewal_Notice_Sent__c = true;
        tpaRequest1.Is_CPC_Expiration_Notice_Sent__c = true;
        tpaRequest1.Is_CPC_Post_Expiration_Notice_Sent__c = true;
        insert tpaRequest1;
        
        Attachment attachment1 = new Attachment();
        attachment1.OwnerId = UserInfo.getUserId();
        attachment1.Name= 'Att1.pdf';
        attachment1.body= Blob.valueOf('Test Body');
        attachment1.ParentId = tpaRequest1.ID ;
        attachment1.IsPrivate = true;
        insert attachment1;
        
        dsfs__DocuSign_Envelope__c ene = new dsfs__DocuSign_Envelope__c(dsfs__Source_Object__c = tpaRequest1.id);
        insert ene;
        
        dsfs__DocuSign_Envelope_Document__c eneDoc = new dsfs__DocuSign_Envelope_Document__c( dsfs__Attachment_NameEx__c = 'Att1.pdf', 
                                                                                             dsfs__Document_ID__c = attachment1.id, 
                                                                                             dsfs__Document_Name__c = 'Att1.pdf', 
                                                                                             dsfs__DocuSign_EnvelopeID__c = ene.id, 
                                                                                             dsfs__External_Document_Id__c = '95E7F69B-6828-4A8B-93B9-20E73F2CE4DC');
        insert eneDoc;
        update eneDoc; 
        delete eneDoc;
    }
}