src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Enter the account location&apos;s City/Town name here</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>Enter the State, Province, County, Prefecture, Kanton, Federal Land (Germany), etc.. here</inlineHelpText>
        <label>Region / State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1026</description>
        <label>City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TPA_Request__c.object
<CustomObject>
    <fields>
        <fullName>Client_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Client)</relationshipLabel>
        <relationshipName>TPA_Requests_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Access_Start_Date__c</fullName>
        <label>Data Access Start Date</label>
        <type>Date</type>
    </fields>
    <label>TPA Request</label>
    <nameField>
        <label>Client Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_DAOH_TpaRequest.cls
@isTest
private class TST_DAOH_TpaRequest {
	private static TPA_Request__c tpaRequest1;
    private static Contact tpaContact;
    private static Address__c testAccount;
    private static Address__c testClientAccount;
    
    static testMethod void myUnitTest() {
        UTL_TPA_SetupTestData.createMultilingualTemplateSettingData();
        
        Date todayDate = Date.today();
        testAccount = UTL_TPA_SetupTestData.getTestAccountByNameAndRegNum('test vendor',1200);
        testClientAccount = UTL_TPA_SetupTestData.getTestAccountByNameAndRegNum('test client',1211);
        testClientAccount.City__c = 'test billing city';
        testClientAccount.State__c = 'test billing state';
        update testClientAccount;
        
        tpaContact = UTL_TPA_SetupTestData.getTestContact(testAccount);
        
        tpaRequest1 = UTL_TPA_SetupTestData.getTPARequestByVendorAccount(testAccount.id);
        tpaRequest1.Client_Address__c = testClientAccount.id;
        date strtDate = date.newInstance(2014, 1, 1);
        tpaRequest1.Data_Access_Start_Date__c = strtDate.addDays(-5);
        update tpaRequest1;
    }
}