src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>MDM_Validation_Status__c</fullName>
        <description>SFDCDEVOPS-186: The validation state of this address with respect to MDM System.</description>
        <label>MDM Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unvalidated</fullName>
                    <default>true</default>
                    <label>Unvalidated</label>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>SAP Base code that corresponds to this address. This is hierarchically-based on the SAP Parent code in the Account and the looked up in SAP. When it is not populated, then this address had not been validated. This is not editable by normal users.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Base code that corresponds to this address.</inlineHelpText>
        <label>SAP Base Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Legacy_Org_Link__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-MC-ESPSFDCQI-789 - Custom Setting to detail the Legacy IMS and Legacy Quintiles environment URLs</description>
    <fields>
        <fullName>Legacy_IMS_URL__c</fullName>
        <description>CRM-MC-ESPSFDCQI-789 - Used to store the Legacy IMS org URL.</description>
        <inlineHelpText>Used to store the Legacy IMS org URL.</inlineHelpText>
        <label>Legacy IMS URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Legacy Org Link</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LI_Opportunity_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>SFDC Id of shadow opportunity in legacy IMS SFDC org</description>
        <externalId>true</externalId>
        <inlineHelpText>SFDC Id of shadow opportunity in legacy IMS SFDC org</inlineHelpText>
        <label>LI Opportunity Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Legacy_Quintiles_Opportunity_Number__c</fullName>
        <description>CRM-QI-ESPSFDCQI-314 Opportunity Number of opportunity record in legacy Quintiles org</description>
        <externalId>true</externalId>
        <inlineHelpText>Opportunity Number of opportunity record in legacy Quintiles org</inlineHelpText>
        <label>Legacy Quintiles Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-927 - A unique opportunity number to identify the opportunity.</description>
        <label>Opportunity Number</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Principle_inCharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-2944</description>
        <inlineHelpText>Select the principal on bid team who will receive credit for the sale</inlineHelpText>
        <label>Principal in Charge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IQVIA_User_Contact</value>
            </filterItems>
            <filterItems>
                <field>Contact.Salesforce_User__r.PIC_Eligible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Contact.Salesforce_User__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Principal in Charge)</relationshipLabel>
        <relationshipName>Opportunities7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>ESPSFDCQI-15073</description>
        <inlineHelpText>The IQVIA Legal Entity under which this deal would be contracted. CRITICAL: It is your responsibility to ensure the Sales Org is in line with the IQVIA contracting entity. If you are not sure what Sales Org to choose, DO NOT GUESS. Reach out to the Sales/Contracting team for this opportunity.</inlineHelpText>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1HQ (NL) BV [NL01]</fullName>
                </value>
                <value>
                    <fullName>1HQ Limited [GB25]</fullName>
                </value>
                <value>
                    <fullName>1HQ Singapore Pte Ltd [SG02]</fullName>
                </value>
                <value>
                    <fullName>1HQ USA LLC [USA8]</fullName>
                </value>
                <value>
                    <fullName>Aileron Solutions, LLC [US49]</fullName>
                </value>
                <value>
                    <fullName>AllCare Plus Pharmacy, LLC [US01]</fullName>
                </value>
                <value>
                    <fullName>AMIX S.à r.l. [FR71]</fullName>
                </value>
                <value>
                    <fullName>Amundsen Group LLC [US38]</fullName>
                </value>
                <value>
                    <fullName>Appature, Inc [US45]</fullName>
                </value>
                <value>
                    <fullName>Ascott Sales Integration PL [AU07]</fullName>
                </value>
                <value>
                    <fullName>Asesorias IMS Health Chile Limitada [CL01]</fullName>
                </value>
                <value>
                    <fullName>Asserta Centroamerica Medicion de Mercados, S.A. [GT01]</fullName>
                </value>
                <value>
                    <fullName>Battaerd Mansley Pty Ltd [BT01]</fullName>
                </value>
                <value>
                    <fullName>BIOAXIS HEALTHCARE SEE SINGLE MEMBER SA [GR72]</fullName>
                </value>
	                <value>
                    <fullName>Bridgethorne Limited [GB23]</fullName>
                </value>
                <value>
                    <fullName>Brogan, Inc [CA04]</fullName>
                </value>
                <value>
                    <fullName>BUZZEOPDMA LLC [US73]</fullName>
                </value>
                <value>
                    <fullName>Cambridge Pharma Consultancy, Inc. [US40]</fullName>
                </value>
                <value>
                    <fullName>Cambridge Pharma Consultancy Ltd [GBC1]</fullName>
                </value>
                <value>
                    <fullName>CDS - Centre de Services SAS [FR79]</fullName>
                </value>
                <value>
                    <fullName>Centrix Innovations (Pty) Ltd [ZA04]</fullName>
                </value>
                <value>
                    <fullName>Ceuta Holdings Ltd [GB21]</fullName>
                </value>				
                <value>
                    <fullName>CFS LLC [US82]</fullName>
                </value>
                <value>
                    <fullName>Compliant Community Projects (Pty) Ltd [ZA03]</fullName>
                </value>
                <value>
                    <fullName>Cronos Consulting [US69]</fullName>
                </value>
                <value>
                    <fullName>Datadina Ecuador S.A. [EC01]</fullName>
                </value>
                <value>
                    <fullName>DataLine Ltd [GB67]</fullName>
                </value>
                <value>
                    <fullName>Data Niche Associates, Inc [US24]</fullName>
                </value>
                <value>
                    <fullName>Dimension Healthcare [AE01]</fullName>
                </value>
                <value>
                    <fullName>Dimension Healthcare [PS01]</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>CRM-MC-ESPSFDCQI-468 - Formula field that references the Products Product Group.</description>
        <formula>TEXT(PricebookEntry.Product2.Product_Group__c)</formula>
        <inlineHelpText>The Product Group of the Opportunity Product.</inlineHelpText>
        <label>Product Group</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Material_Type__c</fullName>
        <label>Material Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <description>CRM-MC-ESPSFDCQI-469 - List of Product Groups for QIMS Products.</description>
        <label>Portfolio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZQUI_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ZQUI Product Eligible for PSA</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Product_Group.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acuta</fullName>
    </customValue>
    <customValue>
        <fullName>Biosimilars</fullName>
    </customValue>
    <customValue>
        <fullName>Biostatistics</fullName>
    </customValue>
    <customValue>
        <fullName>ChannelDynamics Global</fullName>
    </customValue>
    <customValue>
        <fullName>ChannelDynamics Local</fullName>
    </customValue>
    <customValue>
        <fullName>Consent Patient Solution</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Health</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Sales &amp; Medical Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>CSMS GBU Head Office</fullName>
    </customValue>
    <customValue>
        <fullName>CSMS RBU</fullName>
    </customValue>
    <customValue>
        <fullName>DMD Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Data Council</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Product Organization - CS</fullName>
    </customValue>
    <customValue>
        <fullName>ECD Allscripts Data</fullName>
    </customValue>
    <customValue>
        <fullName>ECG/Cardiac Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Early Clinical Development</fullName>
    </customValue>
    <customValue>
        <fullName>End User Services</fullName>
    </customValue>
    <customValue>
        <fullName>Evidence Based Medicine (EBM)</fullName>
    </customValue>
    <customValue>
        <fullName>GFR Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>GFR Head Office</fullName>
    </customValue>
    <customValue>
        <fullName>GFR Pass Thru</fullName>
    </customValue>
    <customValue>
        <fullName>Global Regulatory and Strategy Developme</fullName>
    </customValue>
    <customValue>
        <fullName>Government, Public Health and Other PPG</fullName>
    </customValue>
    <customValue>
        <fullName>HEOR/HTA/DB/LCNIS</fullName>
    </customValue>
    <customValue>
        <fullName>HighPoint Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>Home Health</fullName>
    </customValue>
    <customValue>
        <fullName>IT Services</fullName>
    </customValue>
    <customValue>
        <fullName>Information Offering Overhead</fullName>
    </customValue>
    <customValue>
        <fullName>Information Management</fullName>
    </customValue>
    <customValue>
        <fullName>Innovation</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-469 - List of Product Groups for QIMS Products.</description>
    <masterLabel>Product Group</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/CNT_PSA_CREATE_PROJECT_OPP_SCREEN.cls
/***********************************************
   Name      :     CNT_PSA_CREATE_PROJECT_OPP_SCREEN 
   Date      :     8-April-2019
   Usage     :     Validate Opportunity for create project before redirecting to LI org 
   Author    :     Anju Kumari
***********************************************/

public class CNT_PSA_CREATE_PROJECT_OPP_SCREEN {
    
    public static Boolean isZQUIProduct = false;
    @AuraEnabled 
    public static Map<String, String>  validateOppForProjectCreation(Id opportunityId) {
        Boolean passedValidation = true;
        Id selectedComponentId;
        //Added for RWAS changes
        Map<String,String> result = new Map<String,String>();
        List<String> errorMessages = new List<String>();
        Opportunity currentOpportunity = new Opportunity();
        List <OpportunityLineItem> opportunityLineItemList;
        Boolean onDemandCompOnly = false;
        String tempSalesOrg;
        try {
            List<Opportunity> lstOpportunity = new List<Opportunity>([ SELECT Principle_inCharge__c,LI_Opportunity_Id__c,Name,Opportunity_Number__c,StageName,Legacy_Quintiles_Opportunity_Number__c,AccountId,Sales_Org__c,
                                                                      (SELECT id  FROM OpportunityLineItems where PricebookEntry.Product2.Material_Type__c = 'ZREP' ) FROM Opportunity WHERE id =:opportunityId ]);
            currentOpportunity = lstOpportunity[0];
            // ensure oppty stage it at least stage 4
            if(currentOpportunity == null ||
               currentOpportunity.StageName == null ||
               currentOpportunity.StageName == '' ||
               currentOpportunity.StageName.substring(0,1) == '1') 
            {                   
                passedValidation = false;
                errorMessages.add('Opportunity stage is not valid for creating both Billable Projects or Planned projects.');
            }  
            
            //Principal Incharge Validation
            if(currentOpportunity.OpportunityLineItems.size()>0 && currentOpportunity.Principle_inCharge__c == null && (currentOpportunity.StageName.substring(0,1) == '5' || 
                                                                                                                        currentOpportunity.StageName.substring(0,1) == '6' ||
                                                                                                                        currentOpportunity.StageName.substring(0,1) == '7'))
            {                         
                errorMessages.add('Principal In charge on the opportunity can not be blank when ZREP material type products are added on the Opportunity for creating project.');
                passedValidation = false;           
            }
            else if(currentOpportunity.OpportunityLineItems.size()>0 && currentOpportunity.Principle_inCharge__c == null && (currentOpportunity.StageName.substring(0,1) == '2' || 
                                                                                                                             currentOpportunity.StageName.substring(0,1) == '3' ||
                                                                                                                             currentOpportunity.StageName.substring(0,1) == '4') )
            {
                errorMessages.add('Principal In charge on the opportunity can not be blank when ZREP material type products are added on the Opportunity for creating Planned project.');
                passedValidation = false;
            }
            
            //Address Validation
            SLT_Address accSelector = new SLT_Address();
            List<Address__c> address = accSelector.getSAPValidatedAddress(currentOpportunity.AccountId, new Set<String>{'id','name', 'RecordType.name', 'MDM_Validation_Status__c', 'SAP_Reference__c'});
            if((address.size() == 0 || address == null) && (currentOpportunity.StageName.substring(0,1) == '5' || 
                                                            currentOpportunity.StageName.substring(0,1) == '6' ||
                                                            currentOpportunity.StageName.substring(0,1) == '7') ) 
            {
                passedValidation = false;
                errorMessages.add('At least one MDM validated address is required to create a project. Please click here to contact the MDM team: <a> https://quintiles.service-now.com/via/?id=sc_cat_item&amp;sys_id=4b0859dddb28c8107cf37e77f4961900 </a>');
            }
            else if((address.size() == 0 || address == null) && (currentOpportunity.StageName.substring(0,1) == '2' || 
                                                                 currentOpportunity.StageName.substring(0,1) == '3' ||
                                                                 currentOpportunity.StageName.substring(0,1) == '4') )
            {
                passedValidation = false;
                errorMessages.add('At least one MDM validated address is required to create a Planned project. Please click here to contact the MDM team: <a> https://quintiles.service-now.com/via/?id=sc_cat_item&amp;sys_id=4b0859dddb28c8107cf37e77f4961900 </a>');
            }
            
           opportunityLineItemList = new SLT_OpportunityLineItems(false,false).getComponentData(opportunityId);
            
            //check for on demand products and fire validation accordingly
            if(opportunityLineItemList != null && opportunityLineItemList.size() >0){
                onDemandCompOnly = checkForOnDemandProducts(opportunityLineItemList);
                if(onDemandCompOnly && (currentOpportunity == null ||
                   currentOpportunity.StageName == null ||
                   currentOpportunity.StageName == '' ||
                   currentOpportunity.StageName.substring(0,1) == '1' || 
                   currentOpportunity.StageName.substring(0,1) == '2' || 
                   currentOpportunity.StageName.substring(0,1) == '3' ||
                   currentOpportunity.StageName.substring(0,1) == '4' )){
                    passedValidation = false;
                    errorMessages.add('Opportunity stage <5 is not valid for creating On Demand Project.');
                }
            }
            
            selectedComponentId = getComponentListData(opportunityLineItemList);
            // check for selected component
            if(selectedComponentId == null && (currentOpportunity.StageName.substring(0,1) == '5' || 
                                               currentOpportunity.StageName.substring(0,1) == '6' ||
                                               currentOpportunity.StageName.substring(0,1) == '7') ) 
            {               
                             
                passedValidation = false;
                errorMessages.add('Component is required to create projects.');
            }
            else if(selectedComponentId == null && (currentOpportunity.StageName.substring(0,1) == '2' || 
                                                    currentOpportunity.StageName.substring(0,1) == '3' ||
                                                    currentOpportunity.StageName.substring(0,1) == '4') )
            {
                             
                passedValidation = false;
                errorMessages.add('There are no eligible Services (ZREP) components on the opportunity for which to create a new Planned project.');
            }
            
            List<OpportunityHistory> MaxStageHistory = [ select StageName FROM OpportunityHistory WHERE OpportunityId =:opportunityId order by StageName desc];
            if(!MaxStageHistory.isEmpty()){
                if((MaxStageHistory[0].stageName.substring(0,1) == '5' || MaxStageHistory[0].stageName.substring(0,1) == '6' || MaxStageHistory[0].stageName.substring(0,1) == '7') && (currentOpportunity.StageName.substring(0,1) == '2' || 
																																									   currentOpportunity.StageName.substring(0,1) == '3' ||
																																									   currentOpportunity.StageName.substring(0,1) == '4')) 
                {
                    passedValidation = false;
                    errorMessages.add('This opportunity was already marked as closed won (stage 5 or higher). It is no longer eligible for creation of a planned project.');
                }
            }
            
            result.put('errorMessages',JSON.serialize(errorMessages));
            result.put('legacyOrgOppId', currentOpportunity.LI_Opportunity_Id__c);
            result.put('legacyOrgLink', Legacy_Org_Link__c.getInstance().Legacy_IMS_URL__c);
            if(isZQUIProduct){
                result.put('IsZQUIProduct','ZQUI');
            	result.put('legacyQuintilesOppNumber', currentOpportunity.Legacy_Quintiles_Opportunity_Number__c);
            }
            if(currentOpportunity.Sales_Org__c != '' && currentOpportunity.Sales_Org__c != null){
                tempSalesOrg = EncodingUtil.urlEncode(currentOpportunity.Sales_Org__c,'UTF-8');
                result.put('SalesOrg',tempSalesOrg);
            }
            else{
                tempSalesOrg = 'None';
                result.put('SalesOrg',tempSalesOrg);
            }
            return result;
        } catch(Exception e) {
            return result;
        }
        
        //return passedValidation;
    }
    @AuraEnabled
    public static Id getComponentListData(List <OpportunityLineItem> opportunityLineItemList) {
        if(opportunityLineItemList != null && opportunityLineItemList.size() > 0){ 
            for(OpportunityLineItem oli:opportunityLineItemList) {
                if(('ZQUI').equals(oli.PricebookEntry.Product2.Material_Type__c) 
                   && oli.PricebookEntry.Product2.ZQUI_Product__c) {
                       isZQUIProduct=true;
                       break;
                   }
            }
            return opportunityLineItemList[0].Id;
            
        }
        return null;
    }
    
    public static boolean checkForOnDemandProducts(List <OpportunityLineItem> opportunityLineItemList){
        boolean containsOnlyOndemandComp = true;
        if(opportunityLineItemList != null && opportunityLineItemList.size() > 0){ 
            for(OpportunityLineItem oli:opportunityLineItemList) {
                if(!(CON_PSA.NOVASYTE_CRM).equals(oli.PricebookEntry.Product2.Product_Group__c)) {
                       containsOnlyOndemandComp = false;
                       break;
                   }
            }            
        }
        return containsOnlyOndemandComp;
    }
    
    @AuraEnabled
    public static Legacy_Org_Link__c getLegacyOrgLink(){
        return Legacy_Org_Link__c.getInstance();
    }
}