src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Enter the account location&apos;s City/Town name here</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <inlineHelpText>Choose the account location&apos;s country from the picklist.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chad</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_TPA_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked only when an account is created for TPA Functionality</inlineHelpText>
        <label>Is TPA Account?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Vendor_Checklist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When the vendor is new to TPA</description>
        <label>New Vendor Checklist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <inlineHelpText>Enter the account location&apos;s postal code as complete as possible here.</inlineHelpText>
        <label>PostalCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Vendor_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-453-When checked, the address becomes the Primary Vendor record for vendors with multiple vendor addresses.</description>
        <label>Primary Vendor Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>Enter the State, Province, County, Prefecture, Kanton, Federal Land (Germany), etc.. here</inlineHelpText>
        <label>Region / State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <inlineHelpText>Enter the account location&apos;s street name here</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Tier__c</fullName>
        <label>Vendor Check List</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TPA_Request__c.object
<CustomObject>
    <label>TPA Request</label>
    <nameField>
        <label>Client Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Watch_List__c.object
<CustomObject>
    <fields>
        <fullName>Always_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Always Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country_of_Offering__c</fullName>
        <label>Country of Offering</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Asset_Category__c</fullName>
        <label>Use Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offering__c</fullName>
        <label>Offering</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TPA_Request__c</fullName>
        <label>TPA Request</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use__c</fullName>
        <label>Use Subcategory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Watch Lists</relationshipLabel>
        <relationshipName>Watch_Lists_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TPA Watch List</label>
    <nameField>
        <displayFormat>W-{0000000}</displayFormat>
        <label>Watch List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TPA Watch Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CNT_TPA_ManualReviewView.cls
/**
 * Author: Neetu Bansal
 * Since: June 20, 2015
 * Name: CNT_TPA_ManualReviewView
 * Description: Controller class of TPA_ManualReviewView page
 *              Added by Neetu Bansal under Issue-07325
**/
global with sharing class CNT_TPA_ManualReviewView {
    // To store Vendor
    public Address__c vendor { get; set; }
    // To store Watch List records as JSON
    public String watches { get; set; }
    
    /**
     * Name: Default Constructor
     * Desc: To initialize values
    **/
    public CNT_TPA_ManualReviewView()
    {
        // To get the vendor Id
        String vendorId = ApexPages.currentPage().getParameters().get('vendorId');
        // Initialize list
        watches = JSON.serialize( new List<Watch_List__c>() );
        
        // Check if vendor id is not null
        if( vendorId != null && vendorId != '' )
        {
            // Get the vendor record
            List<Address__c> accounts = [ Select Id, Name, Vendor_Tier__c, Street__c, City__c, State__c, Country__c, PostalCode__c
                                        from Address__c where Id =: vendorId ];
            
            // Check if size > 0
            if( accounts.size() > 0 )
            {
                // Assign the record
                vendor = accounts[0];
                
                // Query all the watch list
                /*List<Watch_List__c> watchList = [ Select Id, Vendor_Address__r.Name, Always_Approved__c, Data_Asset_Category__c, Offering__c, Use__c, Vendor_Address__c, Country_of_Offering__c,
                                                    LastModifiedDate, LastModifiedBy.Name, TPA_Request__c from Watch_List__c where Vendor_Address__c =: vendor.Id
                                                    order by LastModifiedDate DESC ];
                // Store the JSON value
                watches = JSON.serialize( watchList );*/
            }
        }
    }
    
    /**
     * Name: getVendors
     * @param:
     * @return: String - Json of vendors
     * Desc: To get all the vendors
    **/
    public String getVendors()
    {
        // Get the vendor record
        List<Address__c> accounts = [ Select Id, Name, Vendor_Tier__c, Street__c, City__c, State__c, Country__c, PostalCode__c
                                    from Address__c where Is_TPA_Account__c = true
                                    AND (Vendor_Tier__c = 'Y' OR New_Vendor_Checklist__c = true) AND Primary_Vendor_Address__c = true order By Name ];
        
        // Return the JSON value
        return JSON.serialize( accounts );
    }
    
    /**
     * Name: searchWatchList
     * @param: selectedVendorId - Selected vendor Id
     * @return: List<Watch_List__c> - List of watch list for the vendor
     * Desc: To update all the watch list
    **/
    @remoteAction
    public static List<Watch_List__c> searchWatchList( List<String> selectedVendorId , String lastRecId)
    {
        /*Watch_List__c lastWatchListRecord;
        if(lastRecId != null)
            lastWatchListRecord = [Select Id,CreatedDate From Watch_List__c where Id =: lastRecId][0];
        */
        List<Watch_List__c> watchList;
        // Query all the watch list
        if(lastRecId != null){
            watchList = [ Select Id, Vendor_Address__r.Name, Always_Approved__c, Data_Asset_Category__c, Offering__c, Use__c, Vendor_Address__c, Country_of_Offering__c,
            LastModifiedDate, LastModifiedBy.Name,CreatedDate, TPA_Request__c from Watch_List__c where Vendor_Address__c IN : selectedVendorId 
            and Id >: lastRecId order by Id ASC Limit 5000 ];
        }
        else{
            watchList = [ Select Id, Vendor_Address__r.Name, Always_Approved__c, Data_Asset_Category__c, Offering__c, Use__c, Vendor_Address__c, Country_of_Offering__c,
            LastModifiedDate, LastModifiedBy.Name, TPA_Request__c from Watch_List__c where Vendor_Address__c IN : selectedVendorId order by Id ASC Limit 5000 ];
        }
        
        // Return the list
        return watchList;
    }
    
    /**
     * Name: submitApproval
     * @param: watchList - Json of watch list to be updated
     * @return:
     * Desc: To update all the watch list
    **/
    @remoteAction
    global static String submitApproval( String watchList)
    {
        // Deserialize the json to get watch list
        List<Watch_List__c> watches = (List<Watch_List__c>)JSON.deserialize( watchList, List<Watch_List__c>.Class );
        
        // To store vendor Id
        //String vendorId;
        System.debug(watches.size());
        // Check if watches.size() > 0
        if( watches.size() == 0 )
            return 'No Change';
            
        // Map to store old values
        // Key: Watch Id
        // Value: Watch Record
        /*Map<Id, Watch_List__c> watchMap = new Map<Id, Watch_List__c>([ Select Id, Always_Approved__c, Data_Asset_Category__c, Offering__c, Use__c, Country_of_Offering__c,
                                                                        LastModifiedDate, LastModifiedBy.Name, TPA_Request__c from Watch_List__c where Vendor_Address__c =: vendorId
                                                                        order by LastModifiedDate DESC ]);
        
        // List to be updated
        List<Watch_List__c> watchListToBeUpdated = new List<Watch_List__c>();
        
        // Iterate to check which records to be updated
        for( Watch_List__c watch : watches )
        {
            // Check if Map contains and old and new values are different
            if( watchMap.containsKey( watch.Id )
                && ( watchMap.get( watch.Id ).Always_Approved__c != watch.Always_Approved__c ))
            {
                // Add into list
                watchListToBeUpdated.add( watch );
            }
        }
        
        // Check if size > 0, update the list
        if( watchListToBeUpdated.size() > 0 )
        {
            update watchListToBeUpdated;
            return 'Success';
        }
        else
        {
            return 'No Change';
        }*/
        update watches;
        return 'Success';
    }
}