src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Enabled_Sales_Orgs__c</fullName>
        <label>Enabled Sales Orgs</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SAP_Reference__c</fullName>
        <description>SAP Base code that corresponds to this address. This is hierarchically-based on the SAP Parent code in the Account and the looked up in SAP. When it is not populated, then this address had not been validated. This is not editable by normal users.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Base code that corresponds to this address.</inlineHelpText>
        <label>SAP Base Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BNF_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Enable_Customer_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable_Customer_Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Material_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable_Material_Validation</label>
        <type>Checkbox</type>
    </fields>
    <label>BNF_Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MI_BNF_LineItem__c.object
<CustomObject>
    <fields>
        <fullName>MIBNF_Component__c</fullName>
        <label>Multi Invoice BNF Component</label>
        <referenceTo>MIBNF_Component__c</referenceTo>
        <relationshipLabel>MI_BNF_LineItems</relationshipLabel>
        <relationshipName>MI_BNF_LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Itemid__c</fullName>
        <label>Opportunity Line Item ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>MI_BNF_LineItem</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>MI_BNF_LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MI_BNF_LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MIBNF2__c.object
<CustomObject>
    <fields>
        <fullName>BNF_Status__c</fullName>
        <description>CRM-MC-ESPSFDCQI-8412</description>
        <label>BNF Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>IMS Billing Org Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>IMS_Sales_Org__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AE01</fullName>
                </value>
                <value>
                    <fullName>AE02</fullName>
                </value>
                <value>
                    <fullName>AE03</fullName>
                </value>
                <value>
                    <fullName>AR01</fullName>
                </value>
                <value>
                    <fullName>AT52</fullName>
                </value>
                <value>
                    <fullName>AT71</fullName>
                </value>
                <value>
                    <fullName>AU01</fullName>
                </value>
                <value>
                    <fullName>AU06</fullName>
                </value>
                <value>
                    <fullName>AU07</fullName>
                </value>
                <value>
                    <fullName>AU08</fullName>
                </value>
                <value>
                    <fullName>BD01</fullName>
                </value>
                <value>
                    <fullName>BE51</fullName>
                </value>
                <value>
                    <fullName>BE52</fullName>
                </value>
                <value>
                    <fullName>BE54</fullName>
                </value>
                <value>
                    <fullName>BE63</fullName>
                </value>
                <value>
                    <fullName>BE64</fullName>
                </value>
                <value>
                    <fullName>BE72</fullName>
                </value>
                <value>
                    <fullName>BE73</fullName>
                </value>
                <value>
                    <fullName>BE74</fullName>
                </value>
                <value>
                    <fullName>BO01</fullName>
                </value>
                <value>
                    <fullName>BR01</fullName>
                </value>
                <value>
                    <fullName>BR71</fullName>
                </value>
                <value>
                    <fullName>CA03</fullName>
                </value>
                <value>
                    <fullName>CA04</fullName>
                </value>
                <value>
                    <fullName>CA10</fullName>
                </value>
                <value>
                    <fullName>CA15</fullName>
                </value>
                <value>
                    <fullName>CH07</fullName>
                </value>
                <value>
                    <fullName>CH12</fullName>
                </value>
                <value>
                    <fullName>CH13</fullName>
                </value>
                <value>
                    <fullName>CH51</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Multi Invoice BNF</label>
    <nameField>
        <displayFormat>MIBNF-{000000}</displayFormat>
        <label>MIBNF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Multi Invoice BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MIBNF_Component__c.object
<CustomObject>
    <description>Multi Invoice BNF Component which is child BNF for an Opportunity</description>
    <fields>
        <fullName>BNF_Status__c</fullName>
        <label>BNF Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Accrual</fullName>
                </value>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>SAP Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Created</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Confirmed</fullName>
                </value>
                <value>
                    <fullName>LO Accepted</fullName>
                </value>
                <value>
                    <fullName>LO Rejected</fullName>
                </value>
                <value>
                    <fullName>RA Accepted</fullName>
                </value>
                <value>
                    <fullName>RA Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Pending</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MIBNF__c</fullName>
        <description>This Relationship maintain all child BNF connected to one Master Multi Invoice BNF Object which is also child of single Opportunity.</description>
        <label>MIBNF</label>
        <referenceTo>MIBNF2__c</referenceTo>
        <relationshipName>MIBNF_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <formula>Text(MIBNF__r.Sales_Org_Code__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales_Org_Code</label>
        <type>Text</type>
    </fields>
    <label>BNF</label>
    <nameField>
        <label>BNF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Enabled_Sales_Orgs__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3496</description>
        <label>Enabled Sales Orgs</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Material_Type__c</fullName>
        <label>Material Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MI_BNF_Comp_Message_Extension.cls
public class MI_BNF_Comp_Message_Extension {

     //  -------------------------------------------------------------------------------
    //  Member variables
        public string MIBNF_CompId{get;set;}
        public User CurrentUser;
        public MIBNF_Component__c MIBNF_Comp;
        public List<String> errorlst{get;set;}
        public List<OpportunityLineItem> OLIItemList{get;set;}    
        public List<MI_BNF_LineItem__c> MIBNFLineItemList{get;set;}
        public Map<id,MIBNF_Component__c> MIBNFCompMap{get;set;}
     
        public String ProcessInstanceWorkitemMap{get;set;}
        public AddressWrapper objAddressWrapper{get;set;}
        private static Boolean hasAccessBNFAll;
        static {
            hasAccessBNFAll = false;
            List<PermissionSetAssignment> permSetAssList = [SELECT Id, PermissionSet.Name, AssigneeId FROM PermissionSetAssignment WHERE AssigneeId = :Userinfo.getUserId() and  PermissionSet.Name = 'Modify_all_privileges_on_BNF'];
            if(permSetAssList.size() > 0) {
                hasAccessBNFAll = true; 
            }
        }
        
        
        //public MIBNF_Component__c MIBNF_Comppass{get;set;}
        //  -------------------------------------------------------------------------------
        //  Constructor function
        //  -------------------------------------------------------------------------------   
        public MI_BNF_Comp_Message_Extension () 
        {
          
        }
    
    //setter for current user
     public void setCurrentUser(User s)
    {
      
        CurrentUser= s;
        
        ShowInfoMessages();
    }
    //getter for current user
    public User getCurrentUser()
    {
      return this.CurrentUser;
    }
    
     //setter for MIBNF_Comp
     public void setMIBNF_Comp(MIBNF_Component__c s)
    {
        this.MIBNF_Comp = s;
        
    }
    //getter for MIBNF_Comp
    public MIBNF_Component__c getMIBNF_Comp()
    {
     
      return this.MIBNF_Comp;
    }
    
  
    
    
    //Added Date : 13 Feb 2013
    public void ShowInfoMessages()
    {

             errorlst=new List<String>();
            //Added by Himanshu parashar : 12 dec 2012 : When BNF Status is Accepted, Info Message only display to assigned user
            BNF_Settings__c bnfSetting =BNF_Settings__c.getInstance();
         
            //ProcessInstanceWorkitem[] P_array = [select Id, ProcessInstance.TargetObjectId,ActorId from ProcessInstanceWorkitem where ProcessInstance.Status = 'Pending' and ProcessInstance.TargetObjectId = :this.MIBNF_Comp.Id];        
            if(ProcessInstanceWorkitemMap==null)
            	ProcessInstanceWorkitemMap='';
            List<String> P_array= ProcessInstanceWorkitemMap.split(':');
        
            List<Address__c> Address_List = new List<Address__c>();

                //Updated by Himanshu Parashar Date : 7 Feb 2013 : BNF_Settings__c Check
            if(bnfSetting.Enable_Customer_Validation__c==true && objAddressWrapper!=null && objAddressWrapper.map_Filled_Addresses!=null)
            {
                for (String AddressType:objAddressWrapper.map_Filled_Addresses.keySet())
                {
                    Address__c A=objAddressWrapper.map_Filled_Addresses.get(AddressType);
                    Set<String> setAddressSalesOrgs = new Set<String>();
                    if(A.Enabled_Sales_Orgs__c!=null)
                    {
                        List<String> AddressSalesOrgs= A.Enabled_Sales_Orgs__c.split(':'); 
                        setAddressSalesOrgs.addAll(AddressSalesOrgs);
                    }
                    if (A.Enabled_Sales_Orgs__c==null || (setAddressSalesOrgs.size()>0 && setAddressSalesOrgs.contains(this.MIBNF_Comp.MIBNF__r.Sales_Org_Code__c) == false))
                    {
                        errorlst.add(AddressType + ': ' + A.Name + ' (SAP Code: '+ A.SAP_Reference__c + ') is not enabled for ' + this.MIBNF_Comp.MIBNF__r.Sales_Org_Code__c);
                    }
                }
            }
          
   
        if(bnfSetting.Enable_Material_Validation__c==true)
            {
             //Get LineItem from MIBNF LineItem    
             set<Id> JoOppLineItemidSet = new set<Id>();
            //  system.debug('******************coming inside****1.0*******');
             
             //Get all the lineitem belongs to current MIBNF Component
             for (MI_BNF_LineItem__c master :MIBNFLineItemList)
             {
                if(master.MIBNF_Component__c==this.MIBNF_Comp.id)
                {
                    JoOppLineItemidSet.add(master.Opportunity_Line_Itemid__c); 
                }
              
             }
             
                //Added by Himanshu Parashar : 11 dec 2012 : BNF_Status__c Accepted
                for (OpportunityLineItem OLI :OLIItemList)
                {
                   
                    if(JoOppLineItemidSet.contains(OLI.id))
                    {
                        Set<String> setProductSalesOrgs = new Set<String>();
                        if(OLI.PricebookEntry.Product2.Enabled_Sales_Orgs__c!=null)
                        {
                            List<String> ProductSalesOrgs= OLI.PricebookEntry.Product2.Enabled_Sales_Orgs__c.split(':'); 
                            setProductSalesOrgs.addAll(ProductSalesOrgs);
                       
                        }
                        //Updated by Himanshu Parashar Date : 7 Feb 2013 : BNF_Settings__c Check
                         if(OLI.PricebookEntry.Product2.Enabled_Sales_Orgs__c==null || (setProductSalesOrgs.size()>0 && OLI.PricebookEntry.Product2.Material_Type__c == 'ZPUB' && (!setProductSalesOrgs.contains(this.MIBNF_Comp.MIBNF__r.Sales_Org_Code__c))))
                         {
                            errorlst.add('Product '+OLI.PricebookEntry.Product2.ProductCode+' is not enabled for sales org '+ this.MIBNF_Comp.MIBNF__r.Sales_Org_Code__c+ '. Please contact your local Finance representative to resolve this before submitting the BNF.');
                          }
                            
                    }
                    
                    
                     
                }
            }
      MIBNF_Comp=null;  
    }
    
    
 
}