src/objects/Address__c.object
<CustomObject>
    <description>Holds addresses relating to an account.</description>
    <fields>
        <fullName>Marked_For_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this address marked for deletion in SAP</description>
        <label>Marked For Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MDM_Invoicing_Transaction__c.object
<CustomObject>
    <description>ESPSFDCQI-13635: This object is to hold the e-invoice and tax category details.</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>ESPSFDCQI-13635</description>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>MDM Invoicing Transactions</relationshipLabel>
        <relationshipName>MDM_Invoicing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Marked_For_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ESPSFDCQI-13635</description>
        <label>Marked For Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-13635</description>
        <label>Mail Contact 1</label>
        <referenceTo>SAP_Contact__c</referenceTo>
        <relationshipLabel>MDM Invoicing Transactions (SAP Contact 1)</relationshipLabel>
        <relationshipName>MDM_Invoicing_Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-13635</description>
        <label>Mail Contact 2</label>
        <referenceTo>SAP_Contact__c</referenceTo>
        <relationshipLabel>MDM Invoicing Transactions (SAP Contact 2)</relationshipLabel>
        <relationshipName>MDM_Invoicing_Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Contact_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-13635</description>
        <label>Mail Contact 3</label>
        <referenceTo>SAP_Contact__c</referenceTo>
        <relationshipLabel>MDM Invoicing Transactions (SAP Contact 3)</relationshipLabel>
        <relationshipName>MDM_Invoicing_Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>ESPSFDCQI-13635</description>
        <label>Sales Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AE01</fullName>
                    <label>[AE01] Dimensions Healthcare</label>
                </value>
                <value>
                    <fullName>AE02</fullName>
                    <label>[AE02] IQVIA AG - Dubai Branch</label>
                </value>
                <value>
                    <fullName>AE03</fullName>
                    <label>[AE03] Ocshi Solutions &amp; Services</label>
                </value>
                <value>
                    <fullName>AR01</fullName>
                    <label>[AR01] IQVIA Solutions Argentina S.A.</label>
                </value>
                <value>
                    <fullName>AT52</fullName>
                    <label>[AT52] IQVIA Information Solutions GmbH</label>
                </value>
                <value>
                    <fullName>AU01</fullName>
                    <label>[AU01] IQVIA Solutions Australia Pty. Ltd</label>
                </value>
                <value>
                    <fullName>AU07</fullName>
                    <label>[AU07] Ascott Sales Integration PL</label>
                </value>
                <value>
                    <fullName>AU08</fullName>
                    <label>[AU08] Nuevo Health Pty Limited</label>
                </value>
                <value>
                    <fullName>BD01</fullName>
                    <label>[BD01] IMS Health Bangladesh Ltd</label>
                </value>
                <value>
                    <fullName>BE51</fullName>
                    <label>[BE51] IQVIA Solutions Belgium BVBA/SPRL</label>
                </value>
                <value>
                    <fullName>BE52</fullName>
                    <label>[BE52] Forcea NV</label>
                </value>
                <value>
                    <fullName>BE63</fullName>
                    <label>[BE63] REDPHARMA SA</label>
                </value>
                <value>
                    <fullName>BE74</fullName>
                    <label>[BE74] IM Associates BV</label>
                </value>
                <value>
                    <fullName>BO01</fullName>
                    <label>[BO01] IMS Bolivia</label>
                </value>
                <value>
                    <fullName>BR01</fullName>
                    <label>[BR01] IMS Brazil</label>
                </value>
                <value>
                    <fullName>BR71</fullName>
                    <label>[BR71] IMS Health SoluÃ§Ãµes de Tecnologia do Brasil Ltda.</label>
                </value>
                <value>
                    <fullName>CA03</fullName>
                    <label>[CA03] IMS Health Canada Consulting</label>
                </value>
                <value>
                    <fullName>CA10</fullName>
                    <label>[CA10] Privacy Analytics Inc.</label>
                </value>
                <value>
                    <fullName>CH03</fullName>
                    <label>[CH03] IQVIA AG, Branch Rotkreuz</label>
                </value>
                <value>
                    <fullName>CH07</fullName>
                    <label>[CH07] IQVIA AG, Branch Basel</label>
                </value>
                <value>
                    <fullName>CH51</fullName>
                    <label>[CH51] IQVIA AG</label>
                </value>
                <value>
                    <fullName>CL01</fullName>
                    <label>[CL01] ASESORIAS IQVIA SOLUTIONS CHILE LIMITADA</label>
                </value>
                <value>
                    <fullName>CL04</fullName>
                    <label>[CL04] Iasist S.A.U. agencia En Chile</label>
                </value>
                <value>
                    <fullName>CN03</fullName>
                    <label>[CN03] IQVIA Solutions Enterprise Management Consulting (Shanghai) Co., Ltd</label>
                </value>
                <value>
                    <fullName>CN06</fullName>
                    <label>[CN06] IQVIA Solutions Enterprise Management Consulting (Hainan) Co., Ltd.</label>
                </value>
                <value>
                    <fullName>CN71</fullName>
                    <label>[CN71] IMS Health Technology Solutions China Co. Ltd.</label>
                </value>
                <value>
                    <fullName>CO01</fullName>
                    <label>[CO01] IQVIA SOLUTIONS COLOMBIA S.A.</label>
                </value>
                <value>
                    <fullName>CO71</fullName>
                    <label>[CO71] IQVIA TECHNOLOGY SOLUTIONS COLOMBIA LTDA</label>
                </value>
                <value>
                    <fullName>CZ71</fullName>
                    <label>[CZ71] IQVIA Technology Solutions s.r.o.</label>
                </value>
                <value>
                    <fullName>DE04</fullName>
                    <label>[DE04] IQVIA Commercial Software GmbH</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MDM Invoicing Transaction</label>
    <nameField>
        <displayFormat>Invoice- {000000}</displayFormat>
        <label>MDM Invoicing Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDM Invoicing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SLT_MDM_Invoicing_Transaction.cls
/**
* Created by Ronak Mehta on 19-Jun-2023
* Description : Selector Class for MDM_Invoicing_Transaction__c
*/
public class SLT_MDM_Invoicing_Transaction extends fflib_SObjectSelector{
    
    /************constructor************/
    public SLT_MDM_Invoicing_Transaction(){
        super(true, true, true);
    }
    
    /************param constructor************/
    public SLT_MDM_Invoicing_Transaction(Boolean enforceCRUD,Boolean enforceFLS) {
        super(true, enforceCRUD, enforceFLS);
    }
    
    /************Method used to get field list of sobject************/
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> { MDM_Invoicing_Transaction__c.Id, MDM_Invoicing_Transaction__c.SAP_Contact_1__c, MDM_Invoicing_Transaction__c.SAP_Contact_2__c, MDM_Invoicing_Transaction__c.SAP_Contact_3__c, MDM_Invoicing_Transaction__c.Address__c, MDM_Invoicing_Transaction__c.Sales_Org__c};
            }
    
    /************Method used to set up type of sobject************/
    public Schema.SObjectType getSObjectType(){
        return MDM_Invoicing_Transaction__c.sObjectType;
    }
    
    /**
     * This Method Used to get invoice by Condition
     * @params Set<String> fieldSet
     * @params String condition
     * @return List<MDM_Invoicing_Transaction__c>
     */
    public List<MDM_Invoicing_Transaction__c> getInvoiceByCondition(Set<String> fieldSet, String condition){
        return (List<MDM_Invoicing_Transaction__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).setCondition(condition).toSOQL());
        
    }
    
    /**
     * This Method Used to get invoice by Sap Contact Id
     * @params Set<String> fieldSet
     * @params String sapContactIdSet
     * @return List<MDM_Invoicing_Transaction__c>
     */
    public List<MDM_Invoicing_Transaction__c> getInvoiceBySapContact(Set<String> fieldSet, Set<Id> sapContactIdSet){
        return (List<MDM_Invoicing_Transaction__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).setCondition('Marked_For_Deletion__c = false AND (SAP_Contact_1__c IN :sapContactIdSet OR SAP_Contact_2__c IN :sapContactIdSet OR SAP_Contact_3__c IN :sapContactIdSet)').toSOQL());
        
    }
    
}