src/objects/Agency_Program__c.object
<CustomObject>
    <description>PRM- Agency Program Catalog</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Duration_in_month__c</fullName>
        <label>Duration (in month)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Notification__c</fullName>
        <label>First Notification</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Agency Programs</relationshipLabel>
        <relationshipName>Agency_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Notification__c</fullName>
        <label>Second Notification</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Third_Notification__c</fullName>
        <label>Third Notification</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Visible_in_PRM__c</fullName>
        <defaultValue>true</defaultValue>
        <description>PRM-792 : check for visibility on community portal.</description>
        <label>Visible in PRM?</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner Program</label>
    <nameField>
        <label>Partner Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agency_Program_Financials__c.object
<CustomObject>
    <description>PRM- Agency Program Financials</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Countries List</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Apttus_Config2__Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default Value</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price</description>
        <label>Price</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Product</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Partner Program Financials</relationshipLabel>
        <relationshipName>Agency_Program_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Agency Program Field</description>
        <label>Program Name</label>
        <referenceTo>Agency_Program__c</referenceTo>
        <relationshipLabel>Partner Program Financials</relationshipLabel>
        <relationshipName>Agency_Program_Financials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Program Financials</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Partner Program Financials Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Program Financials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Agency_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRM Contract management</description>
        <label>Partner Program</label>
        <referenceTo>Agency_Program__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Contract_Number__c</fullName>
        <label>PRM Child Contract Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Counter__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Notification Counter</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Parent Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SLT_Agency_Program.cls
public class SLT_Agency_Program extends fflib_SObjectSelector {
    
/**
* constructor to initialise CRUD and FLS
*/
    public SLT_Agency_Program() {
        super(false, false, false);
    }
    
/**
* constructor to initialise CRUD and FLS with a parameter for FLS.
*/
    public SLT_Agency_Program(Boolean enforceFLS) {
        super(false, true, enforceFLS);
    }
    
/**
* This method used to get field list of sobject
* @return  List<Schema.SObjectField>
*/
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>();
    }
    
/**
* This method used to set up type of sobject
* @return  Schema.SObjectType
*/
    public Schema.SObjectType getSObjectType() {
        return Agency_Program__c.sObjectType;
    }
    
    public List<Agency_Program__c> fetchAllActiveAgencyProgram(Set<String> fieldSet){
        string activeStatus = CON_PEP.S_PEP_ACTIVE_STATUS;
        return ((List<Agency_Program__c>) Database.query(newQueryFactory(false).selectFields(fieldSet).setCondition('Status__c =: activeStatus').toSOQL()));
    }
    public Agency_Program__c fetchRelatedAgencyProgram(String agencyProgramId){
        return  Database.query('SELECT Name, Product__c FROM Agency_Program__c WHERE id =: agencyProgramId LIMIT 1');
    }
    public List<Agency_Program__c> fetchActiveAgencyProgram(){
        string activeStatus = CON_PEP.S_PEP_ACTIVE_STATUS;
        return  Database.query('SELECT Id, (SELECT Id,EndDate,Notification_Counter__c FROM Contracts__r where New_Contract_Number__c=NULL AND Notification_Counter__c < 4 ORDER BY Id DESC LIMIT 1), Name, Description__c, CurrencyIsoCode, Duration_in_month__c, Price__c, Product__c, Status__c FROM Agency_Program__c where status__c =: activeStatus ORDER BY Name ASC');
    }
    public Agency_Program__c fetchAgencyProgramById(Id agencyProgramId){
        return  Database.query('SELECT Id,Name, Product__c,Duration_in_month__c FROM Agency_Program__c WHERE id =: agencyProgramId LIMIT 1');
    }
    public List<Agency_Program__c> fetchRelatedAgencyProgramById(String relatedAgencyProgram){
        return  Database.query('SELECT Id, Product__c,Duration_in_month__c,First_Notification__c,Second_Notification__c,Third_Notification__c FROM Agency_Program__c WHERE ID =: relatedAgencyProgram');
    }
    public List<Agency_Program__c> fetchActiveAgencyPrograms(String accountCountry,Id recordTypeId){
        string activeStatus = CON_PEP.S_PEP_ACTIVE_STATUS;
        return  Database.query('SELECT Id,(SELECT Id,Price__c,CurrencyIsoCode FROM Agency_Program_Financials__r WHERE Country__c =:accountCountry AND RecordTypeId =:recordTypeId LIMIT 1), (SELECT Id,EndDate,Notification_Counter__c FROM Contracts__r WHERE New_Contract_Number__c=NULL AND Notification_Counter__c < 4 ORDER BY Id DESC LIMIT 1), Name, Description__c, CurrencyIsoCode, Duration_in_month__c, Price__c, Product__c, Status__c, Visible_in_PRM__c FROM Agency_Program__c WHERE status__c =: activeStatus ORDER BY Name ASC');
    }
    
    public List<Agency_Program__c> fetchActiveAgencyProgramsDefault(Id recordTypeId,Set<Id> apId){
        string activeStatus = CON_PEP.S_PEP_ACTIVE_STATUS;
        return  Database.query('SELECT Id,(SELECT Id,Price__c,CurrencyIsoCode FROM Agency_Program_Financials__r WHERE Default__c=true AND RecordTypeId =:recordTypeId LIMIT 1), (SELECT Id,EndDate,Notification_Counter__c FROM Contracts__r WHERE New_Contract_Number__c=NULL AND Notification_Counter__c < 4 ORDER BY Id DESC LIMIT 1), Name, Description__c, CurrencyIsoCode, Duration_in_month__c, Price__c, Product__c, Status__c, Visible_in_PRM__c FROM Agency_Program__c WHERE status__c =: activeStatus And Id IN:apId ORDER BY Name ASC');
    }
}