src/objects/Aggregate_Report__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IQVIAPSA-1217 - Project</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Aggregate Reports</relationshipLabel>
        <relationshipName>Aggregate_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sanofi_Products__c</fullName>
        <label>Sanofi Products</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Aggregate Report</label>
    
    
    
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aggregate Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject> 

src/objects/Drug__c.object
<CustomObject>
    <fields>
        <fullName>Service_Lines__c</fullName>
        <description>IQVIAPSA-3827</description>
        <label>Service Lines</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Lines</valueSetName>
        </valueSet>
    </fields>
    <label>Drug</label>
    <nameField>
        <label>Drug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Proj__c.object
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <fields>
        <fullName>Service_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Service catalogue service line grouping.</description>
        <label>Service Line</label>
        <referenceTo>Service_Line__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Report_Drug__c.object
<CustomObject>
    <fields>
        <fullName>Aggregate_Report__c</fullName>
        <label>Aggregate Report</label>
        <referenceTo>Aggregate_Report__c</referenceTo>
        <relationshipLabel>Report Drugs</relationshipLabel>
        <relationshipName>Report_Drugs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Drug__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Drug</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Drug__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>Drug__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Drug__c</referenceTo>
        <relationshipLabel>Report Drugs</relationshipLabel>
        <relationshipName>Report_Drugs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Report Drug</label>
    <nameField>
        <displayFormat>RD-{000000}</displayFormat>
        <label>Report Drug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Drugs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Line__c.object
<CustomObject>
    <label>Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Lines.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Ad-Promo</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>CEVA</fullName>
    </customValue>
    <customValue>
        <fullName>CMC</fullName>
    </customValue>
    <customValue>
        <fullName>Labelling</fullName>
    </customValue>
    <customValue>
        <fullName>Lifecycle Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Literature</fullName>
    </customValue>
    <customValue>
        <fullName>Local Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Authorisation Application</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Authorisation Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Information</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Safety Services</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Safety Oversight</fullName>
    </customValue>
    <customValue>
        <fullName>Pre- Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management</fullName>
    </customValue>
    <customValue>
        <fullName>Project Startup and Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Publishing</fullName>
    </customValue>
    <customValue>
        <fullName>PVA</fullName>
    </customValue>
    <customValue>
        <fullName>PV Oversight</fullName>
    </customValue>
    <customValue>
        <fullName>PV Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>QPPV</fullName>
    </customValue>
    <customValue>
        <fullName>Quality</fullName>
    </customValue>
    <customValue>
        <fullName>Regulatory Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Regulatory Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Safety Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Signal Management</fullName>
    </customValue>
    <customValue>
        <fullName>PV Support</fullName>
    </customValue>
    <customValue>
        <fullName>Sponsor Audit Support</fullName>
        <isActive>false</isActive>
        <label>Sponsor Audit Support</label>
    </customValue>
    <customValue>
        <fullName>Benefit Risk Assessment (BRA)</fullName>
        <isActive>false</isActive>
        <label>Benefit Risk Assessment (BRA)</label>
    </customValue>
    <masterLabel>Service Lines</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet> 

src/classes/DAOH_Report_Drug.cls
public class DAOH_Report_Drug {
    private static Set<String> sanofiRecordTypeNames = new Set<String>{CON_PSA.AGG_REPORT_REC_TYPE_SANOFI_GSO, CON_PSA.AGG_REPORT_REC_TYPE_SANOFI_PVS};
    private static Integer SANOFI_PRODUCTS_MAX_LENGTH = 80;
        
        
        public static void updateAggregateReportSanofiProducts(List<Report_Drug__c> updatedList, Map<Id,Report_Drug__c> existingRecords){
            List<Aggregate_Report__c> updatedARList = new List<Aggregate_Report__c>();
            
            Set<Id> aggRepSetToBeUpdated = new Set<Id>();
            
            for(Report_Drug__c rd : updatedList){
                aggRepSetToBeUpdated.add(rd.Aggregate_Report__c);
            }
             
            Map<Id,List<Report_Drug__c>> agReportIDToExistingReportDrugMap = new Map<Id,List<Report_Drug__c>>();
            List<Report_Drug__c> relatedReportDrugsExist = new SLT_Report_Drug(false).getReportDrugList(aggRepSetToBeUpdated, new Set<String>{'Id','Aggregate_Report__c','Drug__r.Name'}, 'Aggregate_Report__c' );
            List<Report_Drug__c> drugList;
            for(Report_Drug__c drug : relatedReportDrugsExist){
                drugList = agReportIDToExistingReportDrugMap.get(drug.Aggregate_Report__c);
                if(drugList == null){
                    drugList = new List<Report_Drug__c>();
                    agReportIDToExistingReportDrugMap.put(drug.Aggregate_Report__c,drugList);
                }
                drugList.add(drug);
            }
            for(Id agg : agReportIDToExistingReportDrugMap.keyset()){
                Aggregate_Report__c relatedAggReport = new Aggregate_Report__c(Id = agg);
                
                List<Report_Drug__c> repDgList = agReportIDToExistingReportDrugMap.get(agg);
                String sanofiProd = '';
                for(Report_Drug__c rdg : repDgList){
                    if(rdg.Drug__r.Name != null && rdg.Drug__r.Name != ''){
                        if(sanofiProd != null || sanofiProd != ''){
                            sanofiProd = sanofiProd + ',';
                        }
                        sanofiProd += rdg.Drug__r.Name;
                    }
                }
                sanofiProd = sanofiProd.trim().replaceAll(',,', ',').removeEnd(',').removeStart(',');
                if(sanofiProd!=null || sanofiProd!= ''){
                relatedAggReport.Sanofi_Products__c = sanofiProd.abbreviate(SANOFI_PRODUCTS_MAX_LENGTH);
            }
                updatedARList.add(relatedAggReport);
            }
            if(updatedARList.size() > 0){
                update updatedARList;
            }
        }
    
        public static void deleteFromSanofiProducts(List<Report_Drug__c> deletedList){
            Set<Id> aggRepSetToBeUpdated = new Set<Id>();
            List<Aggregate_Report__c> updatedARList = new List<Aggregate_Report__c>();
            for(Report_Drug__c rd : deletedList){
                aggRepSetToBeUpdated.add(rd.Aggregate_Report__c);
            }
            Map<Id,List<Report_Drug__c>> agReportIDToExistingReportDrugMap = new Map<Id,List<Report_Drug__c>>();
            List<Report_Drug__c> relatedReportDrugsExist = new SLT_Report_Drug(false).getReportDrugList(aggRepSetToBeUpdated, new Set<String>{'Id','Aggregate_Report__c','Drug__r.Name'}, 'Aggregate_Report__c' );
            List<Report_Drug__c> drugList;
            for(Report_Drug__c drug : relatedReportDrugsExist){
                drugList = agReportIDToExistingReportDrugMap.get(drug.Aggregate_Report__c);
                if(drugList == null){
                    drugList = new List<Report_Drug__c>();
                    agReportIDToExistingReportDrugMap.put(drug.Aggregate_Report__c,drugList);
                }
                drugList.add(drug);
            }
            for(Id agg : agReportIDToExistingReportDrugMap.keyset()){
                Aggregate_Report__c relatedAggReport = new Aggregate_Report__c(Id = agg);
                List<Report_Drug__c> repDgList = agReportIDToExistingReportDrugMap.get(agg);
                String sanofiProd = '';
                for(Report_Drug__c rdg : repDgList){
                    if(rdg.Drug__r.Name != null && rdg.Drug__r.Name != ''){
                        if(sanofiProd != null && sanofiProd != ''){
                            sanofiProd = sanofiProd + ',';
                        }
                        sanofiProd += rdg.Drug__r.Name;
                    }
                }
                if(sanofiProd != null && sanofiProd != ''){
                sanofiProd = sanofiProd.trim().replaceAll(',,', ',').removeEnd(',').removeStart(',');
                }
                relatedAggReport.Sanofi_Products__c = sanofiProd.abbreviate(SANOFI_PRODUCTS_MAX_LENGTH);
            
                updatedARList.add(relatedAggReport);
            }
            for(Id agId : aggRepSetToBeUpdated){
                if(!agReportIDToExistingReportDrugMap.containsKey(agId)){
                    Aggregate_Report__c relatedAggReportInAggSet = new Aggregate_Report__c(Id = agId);
                    relatedAggReportInAggSet.Sanofi_Products__c = '';
                    updatedARList.add(relatedAggReportInAggSet);
                }
            }
            if(updatedARList.size() > 0){
                update updatedARList;
            }
        }
    
    public static void validateFields(List<Report_Drug__c> updatedList, Map<Id,Report_Drug__c> existingRecords) {
        Set<Id> aggregateReportIdSet = new Set<Id>();
        Set<Id> drugIdSet = new Set<Id>();
        List<Aggregate_Report__c> arList = new List<Aggregate_Report__c>();
        Set<String> arFieldSet = new Set<String>{'Id','Project__r.Service_Line__r.Name'};
        Map<Id,String> arToServiceLineMap = new Map<Id,String>();
        Map<Id,Drug__c> drugsMap = new Map<Id,Drug__c>();
        
        for(Report_Drug__c reportDrug : updatedList) {
            if(reportDrug.Aggregate_Report__c != null && reportDrug.Drug__c != null) {
                aggregateReportIdSet.add(reportDrug.Aggregate_Report__c);
                drugIdSet.add(reportDrug.Drug__c);
            }
        }
        if(aggregateReportIdSet.size() > 0 && drugIdSet.size() > 0) {
           
            Map<Id,Aggregate_Report__c> arMap = new Map<Id,Aggregate_Report__c>([Select Id, Project__r.Service_Line__r.Name
                                                                                 From Aggregate_Report__c
                                                                                 Where Id in: aggregateReportIdSet]);
            drugsMap = new SLT_Drug(false,false).getDrugById(drugIdSet,new Set<String>{'Id','Service_Lines__c'});
                
            for(Report_Drug__c reportDrug : updatedList) {
                if(arMap.containsKey(reportDrug.Aggregate_Report__c) && drugsMap.containsKey(reportDrug.Drug__c)
                && drugsMap.get(reportDrug.Drug__c).Service_Lines__c != null
                && !drugsMap.get(reportDrug.Drug__c).Service_Lines__c.contains(arMap.get(reportDrug.Aggregate_Report__c).Project__r.Service_Line__r.Name)) {
                
                	reportDrug.addError('The selected Drug is not associated with the related Project\'s Service Line. Please select another Drug.');
            	}
            }
        }        
    }
}