src/objects/Aggregate_Report__c.object
<CustomObject>
    <fields>
        <fullName>Service_Line_Lead__c</fullName>
        <description>IQVIAPSA-1217 - Service Line Lead</description>
        <formula>Project__r.Service_Line_Lead__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Line Lead</label>
        <type>Text</type>
    </fields>
    <label>Aggregate Report</label>
    
    
    
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aggregate Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject> 

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EmployeeNumber__c</fullName>
        <description>CSM-ACN-S-0132 - Text field for employee number</description>
        <externalId>true</externalId>
        <label>Employee Number</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/pse__Grp__c.object
<CustomObject>
    <customHelpPage>pse__GroupHelp</customHelpPage>
    <description>An entity that usually represents a functional business area or business vertical. Groups are organized as an independent hierarchy determined by the Parent Group field, with parent and child records of the same type. Every group in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Permission_Control__c.object
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Group containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Group.</description>
        <inlineHelpText>This is the Group containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Group.</inlineHelpText>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Permission Controls</relationshipLabel>
        <relationshipName>Permission_Controls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the opportunity that this permission control applies to.</description>
        <inlineHelpText>Lookup to the opportunity that this permission control applies to.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Permission Controls</relationshipLabel>
        <relationshipName>Permission_Controls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Project containing Assignments for Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Project, only in relation to the Project.</description>
        <inlineHelpText>This is the Project containing Assignments for Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Project, only in relation to the Project.</inlineHelpText>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Permission Controls</relationshipLabel>
        <relationshipName>Permission_Controls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Proj__c.object
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 Creating Bid History lookup for OWF Process</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Bid_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Service Line Lead</description>
        <label>Service Line Lead</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Service Line Manager)</relationshipLabel>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Service catalogue service line grouping.</description>
        <label>Service Line</label>
        <referenceTo>Service_Line__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person responsible for this project (optional). If not provided, it&apos;s assumed that the record Owner is the project manager.</description>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.pse__Is_Resource__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Is_Resource_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects Managed</relationshipLabel>
        <relationshipName>ProjectsManaged</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Start-up</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Conduct</fullName>
                </value>
                <value>
                    <fullName>Close-out</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Missing Paperwork</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Resource_Request__c.object
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Bid_History_Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - The service line Lead of the service line project associated with this resource request</description>
        <inlineHelpText>The service line Lead of the service line project associated with this resource request</inlineHelpText>
        <label>Service Line Lead</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Resource Requests (Service Line Manager)</relationshipLabel>
        <relationshipName>Resource_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <description>PSA-CLD-USNONE - Lookup to Service Line Project - Service Line</description>
        <formula>pse__Project__r.Service_Line__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Lookup to Service Line Project - Service Line</inlineHelpText>
        <label>Service Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Line__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PSA-CLD-USNONE - Date of the template version</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Line_Code__c</fullName>
        <description>PSA-CLD-USNONE - Unique code used by the system for lookups</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique code used by the system for lookups</inlineHelpText>
        <label>Service Line Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_TGR_Proj.cls
/**
 * This test class is used to test ProjectTrigger.
 * This is the main Test class for Project Trigger and is copied over to dependant Trigger handler Test classes TST_DAO_Proj.cls as well as TST_DAOH_PSA_Project.cls.
 * Any change to the main test class needs to be reflected in their dependant test classes
 * version : 1.0
 */
 
@isTest
private class TST_TGR_Proj {

    /**
     * This method used to set up testdata
     */ 
    @testSetup
    static void dataSetup() 
	{
        Account acc = UTL_OWF_TestData.createAccount();
        insert acc;
        pse__Grp__c grp = UTL_OWF_TestData.createGroup();
        insert grp;
        Contact cont = UTL_OWF_TestData.createContact(acc.Id);
        cont.pse__Is_Resource__c = true;
        cont.pse__Is_Resource_Active__c = true;
        cont.pse__Group__c = grp.Id;
        insert cont;        
        pse__Permission_Control__c permissionControlGroup = UTL_OWF_TestData.createPermissionControl(null, null, grp, null);
        insert permissionControlGroup;
        Opportunity opp = UTL_OWF_TestData.createOpportunity(acc.Id);
        insert opp;
        Bid_History__c agreement = UTL_OWF_TestData.createBidHistoryByRecordType(acc.Id, opp.Id, CON_OWF.OWF_CLINICAL_BID_BID_HISTORY_RECORD_TYPE_ID);
        insert agreement; 
    }
	
	
	/**
    * This test method check project and agreement has same opportunity
    */    
    static testMethod void testNames()
	{
        pse__Proj__c bidProject = [Select Id, Name, Bid_History__r.Name from pse__Proj__c limit 1];
		Bid_History__c agreement = [SELECT Id, Name FROM Bid_History__c Limit 1];
        
        //Checking the project Name and Agreement Name
        String projectName = bidProject.Bid_History__r.Name ;
        String agreementName = agreement.Name;
		system.assertEquals(bidProject.Bid_History__r.Name, agreement.Name);
    }
	
	
//These methods are for testing PSA
	static pse__Proj__c parentproject;
	static pse__Proj__c project;
	static pse__Proj__c pvsProject;
	static Service_Line__c agReportServiceLine;
	static Service_Line__c pvsServiceLine;
	static Contact contact;
	static pse__Resource_Request__c resourcerequest;
    static Aggregate_Report__c ar; 
	static void setupTestData () 
	{

		List<sObject> toSave = new List<sObject>();

		//Group - for PV Solutions
		pse__Grp__c grp = new pse__Grp__c( Name='PV Solutions' );
		insert grp;

        // service line
        agReportServiceLine = new Service_Line__c (
            Active__c = true,
            Service_Line_Code__c = 'TEST1',
            Name = 'Aggregate Reporting'
		);
		insert agReportServiceLine;

        pvsServiceLine = new Service_Line__c (
            Active__c = true,
            Service_Line_Code__c = 'TEST2',
            Name = 'PV Solutions'
		);
		insert pvsServiceLine;
        
        Opportunity opp =[Select id,Name from Opportunity limit 1];

		// Parent Project
		parentproject = UTL_PSA_TestData.createProjects(1, false)[0];
		parentproject.pse__Stage__c = 'Start-up';
        parentproject.pse__Opportunity__c = opp.id;
		insert parentProject;

		// project
		project = UTL_PSA_TestData.createServiceLineProject(parentProject, 'Aggregate Reporting Project', false);
		project.Service_Line__c = agReportServiceLine.Id;
        project.pse__Opportunity__c = opp.id;
		insert project;
        
		pvsProject = UTL_PSA_TestData.createServiceLineProject(parentProject, 'PV Solutions Project', false);
		pvsProject.Service_Line__c = pvsServiceLine.Id;
        pvsProject.pse__Opportunity__c = opp.id;
		insert pvsProject;

		UTL_PSA_TestData.createPermissionControls();

		//contacts
        RecordType contactRT = [SELECT Id from RecordType where Name='IQVIA User Contact'];
		UTL_PSA_TestData.createResources(1,false);
        Contact contact = [Select id,FirstName,LastName,Email from Contact limit 1];
		contact.RecordTypeId = contactRT.Id;
		contact.pse__Salesforce_User__c = UserInfo.getUserId();
		contact.pse__Group__c = grp.id;
        contact.EmployeeNumber__c = '123';
		update contact;

		//resource request
		resourcerequest = UTL_PSA_TestData.createResourceRequests(1, project, false)[0];
        resourcerequest.pse__Project__c = pvsProject.id;
        resourcerequest.pse__Opportunity__c = opp.id;
		insert resourcerequest;
	}

	@IsTest
	static void testInsertServiceLineProjectFields () 
	{
		contact = UTL_PSA_TestData.createResources(1,false)[0];
		contact.pse__Salesforce_User__c = UserInfo.getUserId();
		insert contact;
		Test.startTest();
		pse__Proj__c anotherproject = UTL_PSA_TestData.createProjects(1, false)[0];
		Id recTypeId = UTL_PSA_TestData.lookupRecordTypeId('pse__Proj__c', CON_PSA.PROJ_REC_TYPE_RDS_SERVICELINE);
		anotherproject.recordTypeId = recTypeId;
		anotherproject.Service_Line_Lead__c= contact.Id;
		insert anotherproject;
		Test.stopTest();
		
		// verify that Project's Project Manager matches Service Line Lead.
		pse__Proj__c projectAfterInsert = [SELECT Name,Service_Line_Lead__c,pse__Project_Manager__c from pse__Proj__c where Id=: anotherproject.Id];
		System.assertEquals(contact.Id, projectAfterInsert.pse__Project_Manager__c);
		System.assertEquals(projectAfterInsert.Service_Line_Lead__c, projectAfterInsert.pse__Project_Manager__c);
	}


	@IsTest
	static void testCascadeToServiceLineProjects() 
	{
		setupTestData();
		Test.startTest();
		// parent project's Stage is updated
		parentproject.pse__Stage__c = 'Completed';
		update parentproject;
		Test.stopTest();

		// verify that Parent project's stage is updated to 'Completed'' .
		pse__Proj__c parentprojectAfterUpdate = [SELECT Name,pse__Stage__c from pse__Proj__c where Id=: parentproject.Id];
		System.assertEquals('Completed', parentprojectAfterUpdate.pse__Stage__c);

		// verify that Sub project's stage is updated to 'Not Active' .
		pse__Proj__c subprojectAfterUpdate = [SELECT Name,pse__Stage__c from pse__Proj__c where Id=: project.Id];
		System.debug('subprojectAfterUpdate.pse__Stage__c'+ subprojectAfterUpdate.pse__Stage__c);
		//System.assertEquals('Not Active', subprojectAfterUpdate.pse__Stage__c);
	}
}