src/objects/AMA_Agreement_Detail__c.object
<CustomObject>
    <fields>
        <fullName>TPA_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TPA Request</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipName>AMA_Agreement_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TPA AMA Agreement</label>
    <nameField>
        <displayFormat>AMA-{0000}</displayFormat>
        <label>AMA Agreement Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TPA AMA Agreement Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TPA_Assigned_TP_Processor__c.object
<CustomObject>
    <description>TPA-MC-ESPSFDCTPA-1507-TPA to make changes in adding assign TP Processor values as the configuration process.</description>
    <fields>
        <fullName>Initials__c</fullName>
        <label>Initials</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>TPA Assigned TP Processor</label>
    <nameField>
        <label>TPA Assigned TP Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Assigned TP Processors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TPA_Commercial_Review__c.object
<CustomObject>
    <fields>
        <fullName>TPA_Request__c</fullName>
        <label>TPA Request</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipLabel>TPA Commercial Reviews</relationshipLabel>
        <relationshipName>TPA_Commercial_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TPA Commercial Review</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>TPA Commercial Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TPA Commercial Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TPA_Request__c.object
<CustomObject>
    <fields>
        <fullName>AMA_Agreement_required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created By TPA Module Under TPA-FEATURE-5</description>
        <inlineHelpText>Check if AMA agreement is required</inlineHelpText>
        <label>AMA Agreement required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AMA_USPrescriberData__c</fullName>
        <label>Includeded U.S. prescriber level data?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Please select from the below</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Client)</relationshipLabel>
        <relationshipName>TPA_Requests_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Project_Name__c</fullName>
        <label>Client Project Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Access_End_Date__c</fullName>
        <label>Data Access End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Access_Start_Date__c</fullName>
        <label>Data Access Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Period_End_Date__c</fullName>
        <label>Data Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Period_Start_Date__c</fullName>
        <label>Data Period Start Date</label>
        <type>Date</type>
    </fields>
	<fields>
		<fullName>is_Bulk_TPA_Request__c</fullName>
		<description>Created Under TPA-MC-ESPSFDCTPA-2419</description>
		<defaultValue>false</defaultValue>
		<label>TPA Matrix File Upload Request</label>
		<type>Checkbox</type>
	</fields>
    <fields>
        <fullName>Is_Exhibit_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-1380-If yes then add ad-hoc additional terms to TLLA.</description>
        <label>TPA Has Ad-hoc Additional Term(s)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Manually_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Partially_Renewed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-2202-Checked if TPA request is renewed partially from the parent TPA request.</description>
        <label>Is Partially Renewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Renewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Renewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_South_Africa_Sub_Off__c</fullName>
        <defaultValue>false</defaultValue>
		<description>Created Under TPA-MC-ESPSFDCTPA-2232</description>
        <label>Is South Africa Sub Off</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Specific_Vendors_APLD_Off__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-2833</description>
        <label>is Specific Vendors APLD Off</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Specific_Vendors_LAAD_Off__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-2833</description>
        <label>is Specific Vendors LAAD Off</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Specific_Vendors_Long_Prescr_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-2833</description>
        <label>is Specific Vendors Long Prescr Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Specific_Vendors_Medical_Claims_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-2833</description>
        <label>is Specific Vendors Medical Claims Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Vendor_Name_Contains_DeepIntent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor Name Contains DeepIntent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Vendor_Name_Contains_Edith__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-2462</description>
        <label>Is Vendor Name Contains Edith</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Vendor_Name_Contains_MedPro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TPA-MC-ESPSFDCTPA-1067</description>
        <label>Is Vendor Name Contains MedPro</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Vendor_Related_to_Source_Symphony_Acc__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created under CR-11826</description>
        <label>Is Vendor Related to Source/Symphony Acc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manual_Trigger_Reasons__c</fullName>
        <label>Manual Trigger Reasons</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data accessed via IQVIA Licensed Software</fullName>
                </value>
                <value>
                    <fullName>Prescriber Level Data Included</fullName>
                </value>
                <value>
                    <fullName>Total selected uses more than three</fullName>
                </value>
                <value>
                    <fullName>Vendor requires review</fullName>
                </value>
                <value>
                    <fullName>Vendor Checklist was blank or not valued</fullName>
                </value>
                <value>
                    <fullName>Chosen Vendor in the Payment Risk list</fullName>
                </value>
                <value>
                    <fullName>Other Use Selected</fullName>
                </value>
                <value>
                    <fullName>Selected Use requires Manual Review</fullName>
                </value>
                <value>
                    <fullName>Selected Offering requires Manual Review</fullName>
                </value>
                <value>
                    <fullName>Offering Requires Fee</fullName>
                </value>
                <value>
                    <fullName>Other Offering Selected</fullName>
                </value>
                <value>
                    <fullName>USE Offering Combination needs approval</fullName>
                </value>
                <value>
                    <fullName>Total offerings exceeds maximum allowed</fullName>
                </value>
                <value>
                    <fullName>Client Country differs from Data Country</fullName>
                </value>
                <value>
                    <fullName>Total unique offerings more than three</fullName>
                </value>
                <value>
                    <fullName>Different Client Country from Offering</fullName>
                </value>
                <value>
                    <fullName>Vendor Has Limited Master TPA Certificate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Request</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipLabel>TPA Requests</relationshipLabel>
        <relationshipName>TPA_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewed_As__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewed As</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipLabel>TPA Requests (Renewed As)</relationshipLabel>
        <relationshipName>TPA_Requests_Renewed_As</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Provider_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Legal Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Vendor is not a TPA Vendor.</errorMessage>
            <filterItems>
                <field>Address__c.Is_TPA_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Request_Status__c</field>
                <operation>equals</operation>
                <value>Cancelled, Expired, In Effect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Service Provider)</relationshipLabel>
        <relationshipName>TPA_Requests1_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TPA_Ad_Hoc_Term_Last_Update__c</fullName>
        <label>TPA Ad-Hoc Term Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TPA_Assigned_TP_Processor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned TP Processor</label>
        <referenceTo>TPA_Assigned_TP_Processor__c</referenceTo>
        <relationshipLabel>TPA Requests</relationshipLabel>
        <relationshipName>TPA_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TPA_Processor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TPA Processor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>TPA Requests (TPA Processor Contact)</relationshipLabel>
        <relationshipName>TPA_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_App_Submitted__c</fullName>
        <label>Vendor App Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vendor_Website__c</fullName>
        <label>Vendor Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>is_20_or_more_Offering_Present__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is 20 or more Offering Present</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isbatchProcessing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isbatchProcessing</label>
        <type>Checkbox</type>
    </fields>
    <label>TPA Request</label>
    <nameField>
        <label>Client Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BCH_TPA_Update_Commercial_Review.cls
global class BCH_TPA_Update_Commercial_Review implements Database.Batchable<sObject>, Database.Stateful{
    public static Boolean updateTemporaryDetails = false;
    public static Boolean isProcessingSeconary = false; 
    public string comEmailID;
    public string tempAction;
    public Boolean sendComReviewEmail;
    String OffName;
    public Boolean includeTestDataOnly{
        get{
            if(includeTestDataOnly == null) {
                includeTestDataOnly = false;
            }
            return includeTestDataOnly;
        }
        set;
    }
    public Boolean BatchForTemporaryComUpdate = false;
    global BCH_TPA_Update_Commercial_Review(Boolean forTemporaryComUpdate, String comID, String action, Boolean sendEmail, String OfferingName){
        BatchForTemporaryComUpdate = forTemporaryComUpdate;
        comEmailID = comID;
        tempAction = action;
        sendComReviewEmail = sendEmail;
        OffName = OfferingName;
    }
    public Map<String,String> keysWithNewId = new Map<String,String>();
    public Set<Id> reqsSet =  new Set<Id>();
    Set<String> assetNames = new Set<String>();
    Set<String> assetCategoryNames = new Set<String>();
    Set<String> assetBUNames = new Set<String>();
    Set<String> assetUseNames = new Set<String>();
    Set<String> assetUseCategoryNames = new Set<String>();
    global BCH_TPA_Update_Commercial_Review(){
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        intializeSets();
        String query = 'Select Id,Is_Exhibit_Required__c,Name,Manual_Trigger_Reasons__c,Is_South_Africa_Sub_Off__c,Is_Vendor_Name_Contains_DeepIntent__c,Is_Vendor_Name_Contains_Edith__c,';
        query += 'Is_Vendor_Related_to_Source_Symphony_Acc__c,is_20_or_more_Offering_Present__c,Is_Vendor_Name_Contains_MedPro__c,isbatchProcessing__c,';
        query += 'is_Specific_Vendors_LAAD_Off__c,is_Specific_Vendors_APLD_Off__c,is_Specific_Vendors_Long_Prescr_Data__c,is_Specific_Vendors_Medical_Claims_Data__c,';
        query += 'Data_Period_Start_Date__c,Data_Period_End_Date__c,Client_Project_Name__c,Client_Address__r.Name,Is_Manually_Approved__c,TPA_Ad_Hoc_Term_Last_Update__c,';
        query += 'Data_Access_Start_Date__c,Data_Access_End_Date__c,Parent_Request__c,Parent_Request__r.Name,Parent_Request__r.Renewed_As__c,is_Bulk_TPA_Request__c,';
        query += 'Is_Partially_Renewed__c,Vendor_Website__c,AMA_USPrescriberData__c,TPA_Processor_Contact__r.Name,Parent_Request__r.Is_Renewed__c,';
        query += 'Service_Provider_Address__r.Name,Client_Address__c,Service_Provider_Address__c,AMA_Agreement_required__c,Vendor_App_Submitted__c,';
        query += 'TPA_Assigned_TP_Processor__r.Initials__c,TPA_Assigned_TP_Processor__r.Is_Active__c,Co_Assigned_Global_TP_Processor__c, Co_Assigned_Global_TP_Processor__r.Is_Active__c,Co_Assigned_Global_TP_Processor__r.Initials__c,Requires_Manual_Review__c,TP_Processor_Email__c,vendor_language__c,TLLA_Batch_Call_Sent_On__c,';
        query += 'Request_Status__c,Is_VSN_Acknowlege_By_Client__c,isClientOnComplianceHold__c,isVendorOnComplianceHold__c,Is_Potential_Vendor_Case__c,';
        query += 'isLegalEntityPresent__c,Pending_Acknowledgements__c,Is_Vendor_Veeva_for_all_Use__c,Is_Veeva_Use_CRM_Off_OneKey__c,is_Veeva_Use_CRM__c,Is_Veeva_Use_CRM_SubNational_Off__c,Ack_Understanding_of_Prescriber_Data__c,';
        query += '(select id, name, CreatedDate from Attachments order by createddate desc),(Select Id,AMA_Manual_Review__c,Is_AMA_License_Required__c From AMA_Agreement_Details__r) From TPA_Request__c where';
        query += ' Id in: reqsSet';
        query += ' and Request_Status__c in (\'Awaiting Account Mgmt Communication\',\'' + UTL_TPA.AWAITING_CLIENT_CONFIRMATION + '\',\'Awaiting Client Modification\',\'Awaiting Final Review\',\'In Review By IQVIA\',\'Pending Vendor AMA Fee Acknowledgement\',\'Pending - Vendor Declined AMA Fees\',\'TPA Approved Awaiting AMA Approval\',\'Pending Vendor Response on Data Destruction from Prior TPAs\',\'Hold for TPA non-compliance\') ';
        
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> objList){
        String key ;
        List<String> emails = new List<String>();
        Set<String> useOffValues = new Set<String>();
        Set<String> secUseOffValues = new Set<String>();
        List<Id> commonRevIds = new List<Id>();
        List<Id> offSecRevIds = new List<Id>();
        List<TPA_Commercial_Review__c> comReviewsList = new List<TPA_Commercial_Review__c>();
        List<TPA_Commercial_Review__c> comRevsToUpdate = new List<TPA_Commercial_Review__c>();
        Map<Id,TPA_Request__c> reqWithId = new Map<Id,TPA_Request__c>();
        Set<Id> requestsIdsToCheck = new Set<Id>();
        Map<String,List<String>> reqWithvendorReviews = new Map<String,List<String>>();
        Map<String,List<String>> reqWithoffSecReviews = new Map<String,List<String>>();
        Map<String,List<String>> reqWithReviews = new Map<String,List<String>>();
        Map<String,List<TPA_Data_Asset__c>> requestWithtpaDataAssets = new Map<String,List<TPA_Data_Asset__c>>();
        Map<Id,List<TPA_Commercial_Review__c>> comRevsMap = new Map<Id,List<TPA_Commercial_Review__c>>();
        List<Id> tpaReqIds = new List<Id>();
        List<TPA_Request__c> reqDetailsWithReviews = new List<TPA_Request__c>();
        Boolean reviewUpdated = false;
        
        for(sObject sobj:objList){
            TPA_Request__c tpaReq = (TPA_Request__c)sobj;
            tpaReqIds.add(tpaReq.Id);
            reqDetailsWithReviews.add(tpaReq);
            reqWithId.put(tpaReq.Id, tpaReq);
        }
        if(!BatchForTemporaryComUpdate) {
        offSecRevIds = new List<Id>();
        commonRevIds = new List<Id>();
        secUseOffValues = new Set<String>();
        useOffValues = new Set<String>();
        for(TPA_Commercial_Review__c comreview:[Select Id,Name,Is_Review_Secondary__c,Status__c,Action__c,Action_Needed_By__c,Manual_Review_Reason__c,Receiver_s_Email__c,Associated_Offering_to_Review__c,Associated_Offering_Category__c,BU__c,Associated_Use_to_Review__c,Associated_Offering_s_Use_Category_s__c,Retrigger_By__c,Retrigger_Date__c,TPA_Request__c,TPA_Request__r.Id From TPA_Commercial_Review__c where Associated_Offering_Category__c in: assetCategoryNames and BU__c in: assetBUNames and Associated_Use_to_Review__c in: assetUseNames and Associated_Offering_s_Use_Category_s__c in: assetUseCategoryNames and Status__c Not in ('Combination Approved', 'Combination Approved and Future Approved' ) and TPA_Request__c in: tpaReqIds]){

            Boolean offFound = ((comreview.Associated_Offering_to_Review__c != null && comreview.Associated_Offering_to_Review__c.contains(':')) ? !assetNames.contains(resolvedOfferingName(comreview.Associated_Offering_to_Review__c.split(':')[0])) : !assetNames.contains(comreview.Associated_Offering_to_Review__c));
            if(comreview.Associated_Offering_to_Review__c == null || offFound){
                continue;
            }

            key = '';
            key +=comreview.Associated_Use_to_Review__c + ';';
            key +=comreview.Associated_Offering_s_Use_Category_s__c + ';';
            key +=comreview.Associated_Offering_Category__c + ';';
            key +=comreview.BU__c + ';';
            if(comreview.Associated_Offering_to_Review__c != null && comreview.Associated_Offering_to_Review__c.contains(':')){
                key += resolvedOfferingName(comreview.Associated_Offering_to_Review__c.split(':')[0]);
            }
            else{
                key +=comreview.Associated_Offering_to_Review__c;
            }
            system.debug('key:::'+key);
            if(keysWithNewId.containsKey(Key) && keysWithNewId.get(key) != null && (comreview.Action_Needed_By__c != null && !comreview.Action_Needed_By__c.contains('TP-Country') && !comreview.Action_Needed_By__c.contains('TP-US'))){
                emails = keysWithNewId.get(key).split('~');
                String priEmail = '',secEmail = '';
                if(emails != null && emails.size() > 1 && emails[1].trim() != '') {
                    secEmail = emails[1];
                } else if(emails != null && emails.size() > 0 && emails[0].trim() != '') {
                    priEmail = emails[0];
                }

                if(!comreview.Is_Review_Secondary__c && priEmail != ''){
                    comreview.Receiver_s_Email__c = priEmail;
                    reviewUpdated = true;
                }
                else if(comreview.Is_Review_Secondary__c && secEmail != ''){
                    comreview.Receiver_s_Email__c = secEmail;
                    reviewUpdated = true;
                }
                else{
                    continue;
                }

                if(reviewUpdated){
                    if(comreview.Manual_Review_Reason__c == 'Offering Requires Secondary Commercial Review' && comreview.Status__c == 'Awaiting Review' && !secUseOffValues.contains('Offering Requires Secondary Commercial Review' + comreview.TPA_Request__c+comreview.Associated_Offering_to_Review__c+comreview.Associated_Use_to_Review__c)){
                        secUseOffValues.add('Offering Requires Secondary Commercial Review' + comreview.TPA_Request__c+comreview.Associated_Offering_to_Review__c+comreview.Associated_Use_to_Review__c);
                        offSecRevIds.add(comreview.Id);
                        isProcessingSeconary = true;
                    }
                    if(comreview.Manual_Review_Reason__c != 'Offering Requires Secondary Commercial Review' && !useOffValues.contains(comreview.TPA_Request__c+comreview.Associated_Offering_to_Review__c+comreview.Associated_Use_to_Review__c)){
                        useOffValues.add(comreview.TPA_Request__c+comreview.Associated_Offering_to_Review__c+comreview.Associated_Use_to_Review__c);
                        commonRevIds.add(comreview.Id);                    
                    }
                    commonRevIds.addAll(offSecRevIds);
                    if(!commonRevIds.isEmpty()){
                        reqWithReviews.put(comreview.TPA_Request__c,commonRevIds);
                    }
                    
                    comreview.Retrigger_By__c = UTL_TPA_Multilingual.CurrentUser.Name;
                    comreview.Retrigger_Date__c = Datetime.now();
                    comRevsToUpdate.add(comreview);
                    requestsIdsToCheck.add(comreview.TPA_Request__r.Id);
                    List<TPA_Commercial_Review__c> comRevs = new List<TPA_Commercial_Review__c>();
                    if(comRevsMap.containsKey(comreview.TPA_Request__r.Id)){
                        comRevs = comRevsMap.get(comreview.TPA_Request__r.Id);
                    }
                    comRevs.add(comreview);
                    comRevsMap.put(comreview.TPA_Request__r.Id,comRevs);
                    reviewUpdated = false;
                }

                
            }
        }
		}else{
            String commericalEmail = '%' + comEmailID + '%';
            Map<String,TPA_Assigned_TP_Processor__c> temporaryComOwnerMap = UTL_TPA.getTemporaryComOwnerMapWithOff();
            Date todayDate = System.now().date();
            for(TPA_Commercial_Review__c comreview:[Select Id,Associated_Offering_to_Review__c,Receiver_s_Email__c,TPA_Request__r.Id from TPA_Commercial_Review__c where Status__c Not in ('Combination Approved', 'Combination Approved and Future Approved' ) and TPA_Request__c in: tpaReqIds and Receiver_s_Email__c like: commericalEmail]){
                String temoraryDetails = '';
                String CorrectOffName = '';
                if(comreview.Associated_Offering_to_Review__c != null && comreview.Associated_Offering_to_Review__c.contains(':')){
                    CorrectOffName = resolvedOfferingName(comreview.Associated_Offering_to_Review__c.split(':')[0]);
                }
                else{
                    CorrectOffName = comreview.Associated_Offering_to_Review__c;
                }
                if(tempAction == 'update' || (tempAction == 'delete' && (OffName == null || OffName == '' || OffName.contains(CorrectOffName)))){
                    if(comreview.Receiver_s_Email__c != null){
                        for(String revID : comreview.Receiver_s_Email__c.split(';')){
                            TPA_Assigned_TP_Processor__c obj;
                            if(temporaryComOwnerMap.containsKey(revID.toLowerCase() + '~' + CorrectOffName)){
                                obj = temporaryComOwnerMap.get(revID.toLowerCase() + '~' + CorrectOffName);
                            }
                            else if(temporaryComOwnerMap.containsKey(revID.toLowerCase())){
                                obj = temporaryComOwnerMap.get(revID.toLowerCase());
                            }
                            if(obj != null){
                                temoraryDetails += revID + ' - Temp. CO - ' + obj.Temporary_Commercial_Owner_Email__c + ' From ' + DateTime.newInstance(obj.Out_of_Office_Leave_Start_Date__c.year(),obj.Out_of_Office_Leave_Start_Date__c.month(),obj.Out_of_Office_Leave_Start_Date__c.day()).format('MM/dd/YY') + ' To ' + DateTime.newInstance(obj.Out_of_Office_Leave_End_Date__c.year(),obj.Out_of_Office_Leave_End_Date__c.month(),obj.Out_of_Office_Leave_End_Date__c.day()).format('MM/dd/YY') + ';'; 
                                if(obj.Out_of_Office_Leave_Start_Date__c <= todayDate &&  obj.Out_of_Office_Leave_End_Date__c >= todayDate){
                                    if(!reqWithReviews.containsKey(comreview.TPA_Request__r.Id)) {
                                        reqWithReviews.put(comreview.TPA_Request__r.Id, new list<Id>{comreview.Id});
                                    } else {
                                        reqWithReviews.get(comreview.TPA_Request__r.Id).add(comreview.Id);
                                    }
                                }
                            }
                        }
                    }
                    
                    if(temoraryDetails == '' && tempAction == 'delete'){
                        comreview.Temporary_Reviewer_s_Email__c = '';
                        comRevsToUpdate.add(comreview);
                        if(sendComReviewEmail){
                            if(!reqWithReviews.containsKey(comreview.TPA_Request__r.Id)) {
                                reqWithReviews.put(comreview.TPA_Request__r.Id, new list<Id>{comreview.Id});
                            } else {
                                reqWithReviews.get(comreview.TPA_Request__r.Id).add(comreview.Id);
                            }
                        }
                    }

                    if(temoraryDetails != ''){
                        comreview.Temporary_Reviewer_s_Email__c = temoraryDetails;
                        comRevsToUpdate.add(comreview);
                    }

                }
                
                
                system.debug('comreview:'+comreview);
                system.debug('reqWithReviews:'+reqWithReviews);
                // if(temporaryComOwnerMap.get(comEmailID.toLowerCase()).Out_of_Office_Leave_Start_Date__c <= todayDate &&  temporaryComOwnerMap.get(comEmailID.toLowerCase()).Out_of_Office_Leave_End_Date__c >= todayDate){
                //     if(!reqWithReviews.containsKey(comreview.TPA_Request__r.Id)) {
                //         reqWithReviews.put(comreview.TPA_Request__r.Id, new list<Id>{comreview.Id});
                //     } else {
                //         reqWithReviews.get(comreview.TPA_Request__r.Id).add(comreview.Id);
                //     }
                // }

            }

        }
        if(comRevsToUpdate.size() > 0){
            try{
                if(BatchForTemporaryComUpdate) {
                    updateTemporaryDetails = true;
                }
                update comRevsToUpdate;
                updateTemporaryDetails = false;
            }
            catch(Exception e)
            {
                UTL_LogFactory.generateAndCommitLog(TRUE, 
                                                    FALSE, 
                                                    UTL_LogFactory.GUID, 
                                                    'Exception: ' + e.getMessage() +', Line: '+e.getLineNumber(), 
                                                    'TPA', 
                                                    'Exception', 
                                                    'ERROR', 
                                                    ':::BCH_TPA_Update_Commercial_Review:::execute', 
                                                    '');
            }

        }

        /*if(!BatchForTemporaryComUpdate) {
            for(TPA_Request__c tparequest: reqDetailsWithReviews) {
                reqWithId.put(tparequest.Id, tparequest);
                offSecRevIds = new List<Id>();
                commonRevIds = new List<Id>();
                secUseOffValues = new Set<String>();
                useOffValues = new Set<String>();
                System.debug('comRevsMap//'+comRevsMap);
                if(comRevsMap.get(tparequest.Id) == null){
                    continue;
                }
                for(TPA_Commercial_Review__c comRevObj: comRevsMap.get(tparequest.Id)) {
                    if(comRevObj.Manual_Review_Reason__c == 'Offering Requires Secondary Commercial Review' && !secUseOffValues.contains('Offering Requires Secondary Commercial Review' + comRevObj.TPA_Request__c+comRevObj.Associated_Offering_to_Review__c+comRevObj.Associated_Use_to_Review__c)){
                        secUseOffValues.add('Offering Requires Secondary Commercial Review' + comRevObj.TPA_Request__c+comRevObj.Associated_Offering_to_Review__c+comRevObj.Associated_Use_to_Review__c);
                        offSecRevIds.add(comRevObj.Id);
                        isProcessingSeconary = true;
                    }
                    if(comRevObj.Manual_Review_Reason__c != 'Offering Requires Secondary Commercial Review' && !useOffValues.contains(comRevObj.TPA_Request__c+comRevObj.Associated_Offering_to_Review__c+comRevObj.Associated_Use_to_Review__c)){
                        useOffValues.add(comRevObj.TPA_Request__c+comRevObj.Associated_Offering_to_Review__c+comRevObj.Associated_Use_to_Review__c);
                        commonRevIds.add(comRevObj.Id);                    
                    }
                }
                commonRevIds.addAll(offSecRevIds);
                if(!commonRevIds.isEmpty()){
                    reqWithReviews.put(tparequest.Id,commonRevIds);
                }
            }
        }*/
        if(!BatchForTemporaryComUpdate) {
            for(Id tparequestID: reqWithReviews.keySet()){
                SRV_TPA_TPARequest.tpaRequest = reqWithId.get(tparequestID);
                SRV_TPA_TPARequest.multiRetriggerIds = reqWithReviews.get(tparequestID);
                //SRV_TPA_TPARequest.multiRetriggerForSecondaryReviews = isProcessingSeconary;
                SRV_TPA_TPARequest.reminderSecOfferingMailRequired = isProcessingSeconary;
                if(!Test.isRunningTest()){
                    SRV_TPA_TPARequest.sendApprovalMailToCommericialOwnerForBulk();
                }
                SRV_TPA_TPARequest.multiRetriggerForSecondaryReviews = false;
                SRV_TPA_TPARequest.multiRetriggerIds = null;
            }
        }else{
            for(Id tparequestID: reqWithReviews.keySet()){
                SRV_TPA_TPARequest.tpaRequest = reqWithId.get(tparequestID);
                SRV_TPA_TPARequest.multiRetriggerIds = reqWithReviews.get(tparequestID);
                if(!Test.isRunningTest()){
                    SRV_TPA_TPARequest.sendApprovalMailToCommericialOwnerForBulk();
                }
                SRV_TPA_TPARequest.multiRetriggerIds = null;
            }
        }
    }
    global void finish(Database.BatchableContext BC){
        
    }
    public String resolvedOfferingName(String offeringName){
        String resolvedName = '';
        resolvedName = offeringName.replace(' [Patient as Consumer]', '')
            .replace('STI Data - Custom Report Name', 'STI Data Custom Report Name')
        	.removeEnd(' Provide Market');
        if(OfferingName.contains('Study Name')){
            resolvedName = OfferingName + ' & Project Delivery Date';
        }
        return resolvedName;
    } 
    global void intializeSets(){
        List<String> splitedKey ;
        for(String key:keysWithNewId.KeySet()){
            splitedKey = key.split(';');
            if(splitedKey != null && splitedKey.size() == 5){
                assetNames.add(splitedKey[4]);
                assetBUNames.add(splitedKey[3]);
                assetCategoryNames.add(splitedKey[2]);
                assetUseNames.add(splitedKey[0]);
                assetUseCategoryNames.add(splitedKey[1]);
            }
        }
    }
}