src/objects/Annual_Performance_Chart__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ESPSFDCQI-7294 :Used to Store Goal,selected Stages and Quarter per User for Annual Performance Chart</description>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage_Selectced_Label__c</fullName>
        <defaultValue>&apos;3, 4, 5, 6&apos;</defaultValue>
        <label>Opportunity Stage Selectced Label</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage_Selectced__c</fullName>
        <defaultValue>&apos;[&quot;3. Developing Proposal&quot;, &quot;4. Delivering Proposal&quot;, &quot;5. Finalizing Deal&quot;, &quot;6. Received ATP/LOI&quot;]&apos;</defaultValue>
        <label>Opportunity Stage Selectced</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quater_Selected__c</fullName>
        <defaultValue>&apos;All&apos;</defaultValue>
        <label>Quater Selected</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Annual Performance Chart</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Early_Engagement_COE__c</fullName>
        <description>CRM-MC-ESPSFDCQI-6161</description>
        <inlineHelpText>This Field auto populates from the Early Engagement record.  Populated if MSL or TSL were involved with customer prior to RFP. Not Applicable if no involvement.</inlineHelpText>
        <label>TSSU Early Engagement COE</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Meaningful Early Engagement</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>Rheumatology</fullName>
                </value>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>Psychiatry</fullName>
                </value>
                <value>
                    <fullName>Endocrinology (Diabetes, Metabolism)</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular</fullName>
                </value>
                <value>
                    <fullName>Reproductive Health</fullName>
                </value>
                <value>
                    <fullName>Nephrology (Renal)</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Infectious Diseases &amp; Vaccines</fullName>
                </value>
                <value>
                    <fullName>Allergy &amp; Respiratory</fullName>
                </value>
                <value>
                    <fullName>Biosimilars</fullName>
                </value>
                <value>
                    <fullName>Early Phase</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
                <value>
                    <fullName>Rare Diseases</fullName>
                </value>
                <value>
                    <fullName>Cell and Gene Therapy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1128 - Indicates which line of business the Opportunity aligns to. Used within the Mulesoft integration.</description>
        <inlineHelpText>Indicates which line of business the Opportunity aligns to.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allscripts Data</fullName>
                </value>
                <value>
                    <fullName>Avacare</fullName>
                </value>
                <value>
                    <fullName>Biosimilars</fullName>
                    <isActive>false</isActive>
                    <label>Biosimilars</label>
                </value>
                <value>
                    <fullName>Biostatistical/Medical Writing</fullName>
                    <isActive>false</isActive>
                    <label>Biostatistical/Medical Writing</label>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Clinical Pharmacology</fullName>
                    <isActive>false</isActive>
                    <label>Clinical Pharmacology</label>
                </value>
                <value>
                    <fullName>Clinical Technology</fullName>
                </value>
                <value>
                    <fullName>Clintec</fullName>
                    <isActive>false</isActive>
                    <label>Clintec</label>
                </value>
                <value>
                    <fullName>Commercial Solutions</fullName>
                </value>
                <value>
                    <fullName>Connected Devices</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Consulting Market Access</fullName>
                </value>
                <value>
                    <fullName>Core Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Core Clinical</label>
                </value>
                <value>
                    <fullName>Data Council</fullName>
                </value>
                <value>
                    <fullName>Data Management</fullName>
                    <isActive>false</isActive>
                    <label>Data Management</label>
                </value>
                <value>
                    <fullName>Data Sciences</fullName>
                </value>
                <value>
                    <fullName>Digital Patient (DPU)</fullName>
                    <isActive>false</isActive>
                    <label>Digital Patient (DPU)</label>
                </value>
                <value>
                    <fullName>DrugDev</fullName>
                    <isActive>false</isActive>
                    <label>DrugDev</label>
                </value>
                <value>
                    <fullName>Early Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Early Clinical</label>
                </value>
                <value>
                    <fullName>Early Clinical Development</fullName>
                </value>
                <value>
                    <fullName>ECG/Cardiac Safety</fullName>
                    <isActive>false</isActive>
                    <label>ECG/Cardiac Safety</label>
                </value>
                <value>
                    <fullName>Evidence Based Medicine (EBM)</fullName>
                </value>
                <value>
                    <fullName>GFR Clinical</fullName>
                    <isActive>false</isActive>
                    <label>GFR Clinical</label>
                </value>
                <value>
                    <fullName>Health Engagement &amp; Communication</fullName>
                </value>
                <value>
                    <fullName>Innovation</fullName>
                </value>
                <value>
                    <fullName>IT Services</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                    <isActive>false</isActive>
                    <label>Lab</label>
                </value>
                <value>
                    <fullName>Lifecycle Safety</fullName>
                    <isActive>false</isActive>
                    <label>Lifecycle Safety</label>
                </value>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Medical Communications</fullName>
                    <isActive>false</isActive>
                    <label>Medical Communications</label>
                </value>
                <value>
                    <fullName>Q2 Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Potential_Regions__c</fullName>
        <description>CRM-MC-ESPSFDCQI-8</description>
        <label>Potential Regions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Europe/Middle East/Africa EMEA</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
                <value>
                    <fullName>India Only</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>USA/Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_CNT_CRM_AnnualPerformanceChart.cls
@isTest
public class TST_CNT_CRM_AnnualPerformanceChart {
    
    @testSetup
    static void setUpTestData() {
        Annual_Performance_Chart__c ac = Annual_Performance_Chart__c.getInstance(UserInfo.getUserId());
        ac.Opportunity_Stage_Selectced__c = '["3. Developing Proposal", "4. Delivering Proposal", "5. Finalizing Deal", "6. Received ATP/LOI"]';
        ac.Opportunity_Stage_Selectced_Label__c= '3, 4, 5, 6';
        ac.Quater_Selected__c='All';
        ac.Goal__c = 1500;
        upsert ac;
    }
    
    @isTest
    static void testGetMetaData() {
        Map<String, Object> returnMap = new Map<String,Object>();
        Test.startTest();
        	returnMap = CNT_CRM_AnnualPerformanceChart.getMetaData();
        Test.stopTest();
        System.assertEquals(1500, returnMap.get('goal'));
    }
    
    @isTest
    static void testSetMetaData() {
        Test.startTest();
        	CNT_CRM_AnnualPerformanceChart.setMetaData(2100,'Q1','["3. Developing Proposal"]','3');
        Test.stopTest();
        Annual_Performance_Chart__c ac = Annual_Performance_Chart__c.getInstance();
        System.assertEquals(2100, ac.Goal__c);
    }
    
    @isTest
    static void testGetAllData() {
        Account acc = UTL_TestData.createAccount();
        insert acc;
        Opportunity opp = UTL_TestData.createOpportunity(acc.Id);
        opp.Line_of_Business__c = 'Q2 Solutions';
        opp.StageName = '3. Developing Proposal';
        opp.Amount = 1200;
        opp.Potential_Regions__c = 'Asia Pacific';
        opp.CloseDate = Date.today();
        opp.Early_Engagement_COE__c = 'Gastroenterology';
        insert opp;        
        Map<String, Object> returnMap = new Map<String,Object>();
        Test.startTest();
        	returnMap = CNT_CRM_AnnualPerformanceChart.getAllData();
        Test.stopTest();
        Annual_Performance_Chart__c ac = Annual_Performance_Chart__c.getInstance();
        System.assertEquals(1200, returnMap.get('totalOpenAmount'));
    }

}