src/objects/Apex_Error_Log__c.object
<CustomObject>
    <description>Captures apex errors to be used for further evaluation and resolution. Can be used within automation to send alerts to specific users or group of users.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Details the apex error message received.</description>
        <inlineHelpText>Details the apex error message received.</inlineHelpText>
        <label>Error Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object the apex error occurred at.</description>
        <inlineHelpText>The object the apex error occurred at.</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If an apex error is initiated by a specific user this field details the running user.</description>
        <inlineHelpText>The specific user who initiated the apex error.</inlineHelpText>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Apex_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Apex Error Log</label>
    <nameField>
        <displayFormat>AE-{00000000}</displayFormat>
        <label>Apex Error Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Current_Milestone__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3012</description>
        <label>Current Milestone</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Status__c</fullName>
        <label>LQ Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract_Milestone__c.object
<CustomObject>
    <description>linked to contract and bid history record to enable milestone tracking</description>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract_Number</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Contract_Milestone</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LQ_Contract_Milestone_id__c</fullName>
        <externalId>true</externalId>
        <label>LQ Contract Milestone id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Status__c</fullName>
        <label>LQ Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone_Number__c</fullName>
        <formula>if(ispickval( Milestone__c , &apos;1. Assigned to OGC team member&apos;), 1, 
if(ispickval( Milestone__c , &apos;2. Insufficient information to proceed&apos;), 2, 
if(ispickval( Milestone__c, &apos;3. Contract in preparation&apos;),3, 
if(ispickval( Milestone__c , &apos;4. Contract in review: initial draft&apos;),4, 
if(ispickval( Milestone__c , &apos;5. Contract in review: subsequent drafts&apos;),5, 
if(ispickval( Milestone__c, &apos;6. Contract in review: CPM&apos;),6, 
if(ispickval( Milestone__c , &apos;7. Contract in review: Client/Vendor&apos;), 7, 
if(ispickval( Milestone__c , &apos;8. Contract in review: Data Protection&apos;), 8, 
if(ispickval( Milestone__c , &apos;9. Contract in review: Finance&apos;), 9, 
if(ispickval( Milestone__c , &apos;10. Contract in review: Other Q Department&apos;), 10, 
if(ispickval( Milestone__c , &apos;11. Contract in review: QA&apos;), 11, 
if(ispickval( Milestone__c , &apos;12. Contract in review: Risk Management &apos;), 12, 
if(ispickval( Milestone__c , &apos;13. Contract under signature&apos;), 13, 
if(ispickval( Milestone__c , &apos;14. Awaiting call with client/vendor &apos;), 14, 
0) 
)))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milestone Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milestone_Total_Business_Days__c</fullName>
        <label>Milestone Total Business Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <displayFormat>CM{00000000}</displayFormat>
        <label>Milestone Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Outbound_Message_Deletion_Queue__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-766</description>
    <fields>
        <fullName>LQ_Id__c</fullName>
        <description>CRM-MC-ESPSFDCQI-766</description>
        <label>LQ Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LQ_Mulesoft_Sync_Status__c</fullName>
        <description>CRM-MC-ESPSFDCQI-766 Field indicating status of Mulesoft sync from IQVIA org to legacy Quintiles org</description>
        <inlineHelpText>Field indicating status of Mulesoft sync from IQVIA org to legacy Quintiles org</inlineHelpText>
        <label>LQ Mulesoft Sync Status</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>CRM-MC-ESPSFDCQI-766</description>
        <label>Operation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordID__c</fullName>
        <description>CRM-MC-ESPSFDCQI-766</description>
        <label>RecordID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObjectType__c</fullName>
        <description>CRM-MC-ESPSFDCQI-766</description>
        <label>SObjectType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Outbound Message Deletion Queue</label>
    <nameField>
        <label>Outbound Message Deletion Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Message Deletion Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DAOH_ContractMilestone.cls
/**
 * This is ContractMilestone trigger handler class.
 * version : 1.0
 */
public class DAOH_ContractMilestone {
    
    /**
     * in this method we updating contracts
     * @params  List<Contract_Milestone__c> newList
     * @return  void
     */
    public static void updateContracts(List<Contract_Milestone__c> newList) {
        List<Contract> contractsToUpdate = new List<Contract>();
        for(Contract_Milestone__c currentContractMilestone : newList ){
            if(currentContractMilestone.Contract_Number__c != null){
                contractsToUpdate.add(new Contract(Id=currentContractMilestone.Contract_Number__c, 
                                                   Current_Milestone__c=currentContractMilestone.Milestone_number__c));
            }
        }
        try{
            update contractsToUpdate;
        }catch(Exception e){
            System.debug('Failed due to : '+e);
        }
    }
    
    /**
     * in this method we updating Contract_Milestone__c
     * @params  List<Contract_Milestone__c> newList
     * @return  void
     */
    public static void updateContractMilestone(List<Contract_Milestone__c> newList) {
        Set<Id> contractMilestoneIds = new Set<Id>();
        Set<String> fieldSet = new Set<String>{'Id','Milestone_Total_Business_Days__c'};
        for(Integer i = 1; i <= 10; i++){
            fieldSet.add('V' + i + '_Total_Business_Days__c');
        }    
        for(Contract_Milestone__c currentContractMilestone : newList ){
            contractMilestoneIds.add(currentContractMilestone.Id);
        }
        List<Contract_Milestone__c> contractMilestoneNewList = new SLT_ContractMilestone().selectByIdFilter(contractMilestoneIds, fieldSet);
        List<Contract_Milestone__c> contractMilestonesToUpdate = new List<Contract_Milestone__c>();
        for(Contract_Milestone__c currentContractMilestone : contractMilestoneNewList ){
            Integer milestoneTotalBusinessDays = 0;
            for(Integer i = 1; i <= 10; i++){
                if(currentContractMilestone.get('V' + i + '_Total_Business_Days__c') != null){
                    milestoneTotalBusinessDays += Integer.valueOf(currentContractMilestone.get('V' + i + '_Total_Business_Days__c'));
                }
            }
            currentContractMilestone.Milestone_Total_Business_Days__c = milestoneTotalBusinessDays;
            contractMilestonesToUpdate.add(currentContractMilestone );
        }
        try{
            UTL_ExecutionControl.stopMilestoneTriggerExecution = true;
            update contractMilestonesToUpdate;
            UTL_ExecutionControl.stopMilestoneTriggerExecution = false;
        }catch(Exception e){
            Apex_Error_Log__c apexErrorLog = new Apex_Error_Log__c();
            apexErrorLog.Running_User__c = UserInfo.getUserId();
            apexErrorLog.Object__c = 'Contract_Milestone__c';
            apexErrorLog.Error_Message__c = e.getStackTraceString();
            insert apexErrorLog;
        }
    }
    
    /**
    * This method is used to update Contract Milestone fields
    * @params  newList List<Contract_Milestone__c>
    * @params oldMap Map<id, Contract_Milestone__c>
    * @return  void
    */
    public static void setContractMileStoneFields(List<Contract_Milestone__c> newList, Map<Id, Contract_Milestone__c> oldMap) {
        for(Contract_Milestone__c milestone : newList) {
            // FEATURE-3828
            if(Trigger.isInsert || milestone.LQ_Mulesoft_Sync_Status__c == oldMap.get(milestone.Id).LQ_Mulesoft_Sync_Status__c || (milestone.LQ_Mulesoft_Sync_Status__c != oldMap.get(milestone.Id).LQ_Mulesoft_Sync_Status__c 
                                    && (milestone.LQ_Mulesoft_Sync_Status__c != CON_CRM.MULESOFT_SYNC_STATUS_COMPLETED &&  milestone.LQ_Mulesoft_Sync_Status__c != CON_CRM.MULESOFT_SYNC_STATUS_FAILED))) {
                milestone.LQ_Mulesoft_Sync_Status__c = CON_CRM.MULESOFT_SYNC_STATUS_PENDING;
            }
        }
    }
    
    /**
     * This method is used to update Outbound Message Deletion Queue
     * @params  List<Contract_Milestone__c> deleteList
     * @return  void
     */
    public static void createOutboundMessageDeletionQueue(List<Contract_Milestone__c> deleteList) {
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new Schema.SObjectType[] {
                Outbound_Message_Deletion_queue__c.SobjectType
            }
        );
        Outbound_Message_Deletion_queue__c outBound;
        Boolean toCommit = false;
        for(Contract_Milestone__c contMilestone : deleteList) {
            outBound = new Outbound_Message_Deletion_queue__c();
            outBound.Operation__c = CON_CRM.DELETE_LABEL;
            if(contMilestone.LQ_Contract_Milestone_id__c != null) {
                outBound.LQ_Id__c = contMilestone.LQ_Contract_Milestone_id__c;
            }
            outBound.SObjectType__c = CON_CRM.CONTRACT_MILESTONE_OBJECT_API;
            outBound.RecordID__c = contMilestone.Id;
            uow.registerNew(outBound);
            toCommit = true;
        }
        
        if(toCommit) {
            uow.commitWork();
        }
    }
}