src/objects/appirio_core__App_Log__c.object
<CustomObject>
    <customHelpPage>appirio_core__AppLogHelp</customHelpPage>
    <description>Saves a log of general events that occur during batch processing of billing events and actuals (app logs are not used for any other area of Certinia PSA). This may include status and error messages. Administrators can use app logs to track down processing errors.</description>
    <label>App Log</label>
    <nameField>
        <displayFormat>LOG-{YYYYMMDD}-{00000000}</displayFormat>
        <label>Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Audit_Log__c.object
<CustomObject>
    <description>Used to record insertion, deletion, and modification of records from other objects.</description>
    <fields>
        <fullName>Field__c</fullName>
        <description>PSA-CLD-USNONE - The API name of the field that has been modified</description>
        <inlineHelpText>The API name of the field that has been modified</inlineHelpText>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <description>PSA-CLD-USNONE - The new value of the field in question</description>
        <inlineHelpText>The new value of the field in question</inlineHelpText>
        <label>New Value</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>PSA-CLD-USNONE - The name of the object on which this operation was executed</description>
        <inlineHelpText>The name of the object on which this operation was executed</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>The operation done to the record</description>
        <inlineHelpText>The operation done to the record</inlineHelpText>
        <label>Operation</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INSERT</fullName>
                </value>
                <value>
                    <fullName>UPDATE</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
                <value>
                    <fullName>UNDELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prior_Value__c</fullName>
        <description>PSA-CLD-USNONE - The prior value of the field in question.</description>
        <inlineHelpText>The prior value of the field in question.</inlineHelpText>
        <label>Prior Value</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reason_for_Deletion__c</fullName>
        <description>PSA-CLD-USNONE - The reason the given record was deleted (supplied by user)</description>
        <inlineHelpText>The reason the given record was deleted (supplied by user)</inlineHelpText>
        <label>Reason for Deletion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <description>PSA-CLD-USNONE - The Salesforce ID of the changed record</description>
        <externalId>true</externalId>
        <inlineHelpText>The Salesforce ID of the changed record</inlineHelpText>
        <label>Record ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Replay_ID__c</fullName>
        <description>The replay ID from the Change Event</description>
        <externalId>true</externalId>
        <inlineHelpText>The replay ID from the Change Event</inlineHelpText>
        <label>Replay ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <description>PSA-CLD-USNONE - The date and time of the change</description>
        <inlineHelpText>The date and time of the change</inlineHelpText>
        <label>Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Key__c</fullName>
        <description>The Transaction ID from the Change Event</description>
        <externalId>true</externalId>
        <inlineHelpText>The Transaction ID from the Change Event</inlineHelpText>
        <label>Transaction Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - The user who made the change, addition, or deletion.</description>
        <inlineHelpText>The user who made the change, addition, or deletion.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audit Log</label>
   
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Audit Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QUE_SRV_PSA_AuditLog.cls
public class QUE_SRV_PSA_AuditLog implements Queueable {
    private final SRV_PSA_AuditLog.AuditLogWrapper[] auditLogWrappers;
    private Integer cursor;
    public static final Integer SIZE_LIMIT = 5000;
    public static final Integer QUEUE_LIMIT = 20000;
    @TestVisible Boolean allOrNone = true; // audit log insert dml option
    
    public QUE_SRV_PSA_AuditLog(List<SRV_PSA_AuditLog.AuditLogWrapper> wrapperList) {
        this(wrapperList,0);
    }

    public QUE_SRV_PSA_AuditLog(List<SRV_PSA_AuditLog.AuditLogWrapper> wrapperList, Integer startAt) {
        if( wrapperList.size() > QUEUE_LIMIT){
            LimitException e  = new LimitException();
            e.setMessage('Hit Audit Queue Limit of '+QUEUE_LIMIT+' with an input of '+wrapperList.size()+'. Please break this up and create multiple queues.');
            throw e;
        }
        this.cursor = startAt; 
        this.auditLogWrappers = wrapperList;
        System.debug('@@ QUE_SRV_PSA_AuditLog constructor starting cursor position ' + this.cursor+' ('+startAt+')');
        System.debug('@@ QUE_SRV_PSA_AuditLog constructor (wrapperList.size())' + wrapperList.size());
    }
    
    public void execute(QueueableContext context) {
        this.insertAuditLogs(auditLogWrappers);
    }
        /*
* save to custom audit log object
*/
    public void insertAuditLogs (SRV_PSA_AuditLog.AuditLogWrapper[] auditLogWrappers) {
        System.debug('@@ QUE_SRV_PSA_AuditLog.insertAuditLogs starting processing with index '+this.cursor);
        // build sobjects from wrapper!
        Audit_Log__c[] auditLogsToSave = new Audit_Log__c[]{};
        SRV_PSA_AuditLog.AuditLogWrapper logWrapper;
        Integer wrapperSize;
        Integer counter;
        for( counter = 0, wrapperSize = auditLogWrappers.size(); this.cursor < wrapperSize && counter < SIZE_LIMIT; counter++) {
            logWrapper = auditLogWrappers[this.cursor];
            DateTime rightNow = System.now();
            Audit_Log__c auditlog = new Audit_Log__c(
                Record_ID__c = logWrapper.recordId.left(18),
                Operation__c = logWrapper.operation,
                Field__c = logWrapper.field,
                Time__c = logWrapper.logTime,
                Object__c  = logWrapper.logObject,
                Transaction_Key__c = logWrapper.transactionKey,
                Replay_ID__c = logWrapper.replayId,
                User__c = logWrapper.userId
            );
            // if (logWrapper.priorValue != null) {
            //   auditlog.Prior_Value__c = JSON.serialize(logWrapper.priorValue);
            // }
            if (logWrapper.newValue != null) {
                // auditlog.New_Value__c = JSON.serialize(logWrapper.newValue);
                auditlog.New_Value__c = logWrapper.newValue;
            }
            if(logWrapper.operation == 'DELETE' && !SRV_PSA_AuditLog.ignoreObjs.contains(logWrapper.logObject)) {
                auditlog.Reason_for_Deletion__c = logWrapper.reasonForDeletion;
            } else if(logWrapper.operation == 'DELETE' && SRV_PSA_AuditLog.ignoreObjs.contains(logWrapper.logObject)){
                auditlog.Reason_for_Deletion__c = '';
            }
            
            auditLogsToSave.add(auditlog);
            this.cursor++;
        }
        
        System.debug('@@ QUE_SRV_PSA_AuditLog.insertAuditLogs (auditLogsToSave.size())' + auditLogsToSave.size());
        
        if (auditLogsToSave != null && auditLogsToSave.size() > 0) {
            // now save it!
            saveAuditLogSObjects(auditLogsToSave);
        }
        
        //If we have leftovers that didn't fit, we chain another queue and pass the current position
        if (this.cursor + 1 < wrapperSize){
        System.debug('@@ QUE_SRV_PSA_AuditLog.insertAuditLogs found more wrappers to process after index '+this.cursor+', starting new queue');
            System.enqueueJob(new QUE_SRV_PSA_AuditLog(auditLogWrappers,this.cursor));
        }
        // // RAISE A LIMIT EXCEPTION TO TEST BATCH APEX ERROR EVENT!
        // LimitException e  = new LimitException();
        // e.setMessage('TESTING. This is a constructed LimitException! Catch It If You Can!');
        // throw e;
        
    }
    
    @TestVisible
    private void saveAuditLogSObjects(Audit_Log__c[] auditLogsToSave) {
        if (auditLogsToSave != null  && auditLogsToSave.size() > 0) {
            Database.SaveResult[] srList = Database.insert(auditLogsToSave, allOrNone);
            // check for errors and log messages
            appirio_core__App_Log__c[] errorLogs = new appirio_core__App_Log__c[]{};
                for (Integer i=0; i< srList.size(); i++) {
                    Database.SaveResult sr = srList[i];
                    if (!sr.isSuccess()) {
                        String[] errors = new String[]{};
                            for(Database.Error err : sr.getErrors()) {
                                errors.add(err.getMessage());
                            }
                        String errMsg =  String.join(errors, ',');
                        String errData = JSON.serialize(auditLogsToSave[i]);
                        String origin = SRV_PSA_AuditLog.APP_LOG_ORIGIN;
                        appirio_core__App_Log__c appLog = UTL_PSA_AppLog.writeLog(origin, UTL_PSA_AppLog.APP_LOG_ERROR_LEVEL, errMsg, errData, false);
                        
                        errorLogs.add(appLog);
                    }
                }
            if (errorLogs.size() > 0) {
                fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<SObjectType> { appirio_core__App_Log__c.SObjectType });
                uow.registerNew(errorLogs);
                uow.commitWork();
            }
        }
    }
    
}