src/objects/Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver Group</label>
        <referenceTo>Approver_Group__c</referenceTo>
        <relationshipLabel>Approval Matrix</relationshipLabel>
        <relationshipName>Approval_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver_1__c</fullName>
        <description>CPQ-LC-9745: This field is used to store Approver.</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>	Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Approval Matrix (Approver 1)</relationshipLabel>
        <relationshipName>Approval_Matrix5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_Approve__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CPQ-LC-9745: This field is used set the value of Auto Approve to approve the process automatically.</description>
        <label>Auto Approve	</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the country for Approval.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Asia Mid Markets</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
                <value>
                    <fullName>East Africa</fullName>
                </value>
                <value>
                    <fullName>Ecuador</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>El Salvador</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Levels__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the levels for Approval.</description>
        <label>Levels</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
                <value>
                    <fullName>Level 4</fullName>
                </value>
                <value>
                    <fullName>Level 5</fullName>
                </value>
                <value>
                    <fullName>Level 6</fullName>
                </value>
                <value>
                    <fullName>Level 7</fullName>
                </value>
                <value>
                    <fullName>Level 8</fullName>
                </value>
                <value>
                    <fullName>Level 9</fullName>
                </value>
                <value>
                    <fullName>Level 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Max_Amount__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Maximum Amount for Approval.</description>
        <label>Max Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Discount_Amount__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Maximum Discount Amount for Approval.</description>
        <label>Max Discount Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Amount__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Minimum Amount for Approval.</description>
        <label>Min Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Discount_Amount__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Minimum Discount Amount for Approval.</description>
        <label>Min Discount Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Discount_Percent__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Maximum Discount Amount for Approval.</description>
        <label>Max Discount Percent</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Gross_Margin__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Maximum Gross Margin for Approval.</description>
        <label>Max Gross Margin</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Min_Discount_Percent__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Minimum Discount Percent for Approval.</description>
        <label>Min Discount Percent</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Min_Gross_Margin__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Minimum Gross Margin for Approval.</description>
        <label>Min Gross Margin</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pricing_Tool__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the value of pricing tool for Approval.</description>
        <label>Pricing Tool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Name__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the track name for Approval.</description>
        <label>Track Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Matrix</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Approval Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Actual_Discount_Value__c</fullName>
        <description>CPQ-LC-8018- Make to hold discount value for quotes where AstraZeneca  selected as value in Account field</description>
        <inlineHelpText>This field only applies to AstraZeneca accounts.</inlineHelpText>
        <label>Actual Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <description>BUG LC-9347 : This field is used to calculate sum of Net Price of all proposal line item associated to the Quote/Proposal</description>
        <label>Total Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Discount_Percent__c</fullName>
        <label>Discount %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Approver_1__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Approver 1 for Approval process.</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Proposals (Approver 1)</relationshipLabel>
        <relationshipName>Proposals3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver_Level__c</fullName>
        <description>CPQ-LC-9745-This field is used to store the Approver level for each step in Approval process.</description>
        <label>Approver Level</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CountryCode__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Min_Gross_Margin__c</fullName>
        <inlineHelpText>Captures Minimum Gross Margin without Pass Through products</inlineHelpText>
        <label>Min Gross Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <recordTypes>
        <fullName>Tech_Solution</fullName>
        <active>true</active>
        <description>Proposal record for Tech Solution</description>
        <label>Tech Solution</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Apttus_Proposal__Discount_Percent__c</fullName>
        <label>Discount Percent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>APAC Regional</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>ASEAN Regional</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Mid Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <description>CRM-MC-ESPSFDCQI-319 - List of countries.</description>
    <masterLabel>Countries</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_SLT_ApprovalMatrix.cls
@isTest
private class TST_SLT_ApprovalMatrix {

    static Approval_Matrix__c setApprovalMatrixData(){
        Approver_Group__c approverGroup = UTL_TestData.createApproverGroup(CON_CPQ.APPROVER_GROUP_PL, CON_CPQ.GENERAL);
        insert approverGroup;
        Approval_Matrix__c approvalMatrix = UTL_TestData.createApprovalMatrix(approverGroup, CON_CPQ.OPPORTUNITY_RFP,
            CON_CPQ.JAPAN, CON_CPQ.ONCOLOGY, CON_CPQ.SALES_USER, '', '', '', '', CON_CPQ.APPROVER_SALES_LOCAL_PHARMA,
            CON_CPQ.MD, CON_CPQ.Role_TSSU1, CON_CPQ.ONCOLOGY, CON_CPQ.CUSTOMER_NAME);
        insert approvalMatrix;
        return approvalMatrix;
    }
    
    @isTest
    static void testSelectApprovalMatrixById(){
        Approval_Matrix__c testApprovalMatrix  = setApprovalMatrixData();
        
        Test.startTest();
        	List<Approval_Matrix__c> approvalMatrixList = new SLT_ApprovalMatrix().selectById(new Set<Id>{testApprovalMatrix.Id});
        Test.stopTest();
    }
    
    @isTest
    static void testSelectApprovalMatrixCondition(){
        setApprovalMatrixData();
        
        Test.startTest();
        	List<Approval_Matrix__c> testApprovalMatrixList = new SLT_ApprovalMatrix().selectApprovalMatrixCondition(CON_CPQ.OPPORTUNITY_RFP, CON_CPQ.JAPAN);
        Test.stopTest();
    }
    
    @isTest
    static void testSelectApprovalMatrixByOpportunityType(){
        setApprovalMatrixData();
        
        Test.startTest();
        	List<Approval_Matrix__c> testApprovalMatrixList = new SLT_ApprovalMatrix().selectApprovalMatrixByOpportunityType(CON_CPQ.OPPORTUNITY_RFP);
        Test.stopTest();
    }
    
    @isTest
    static void testgetApprover(){
        Account account = UTL_OCE_TestData.createaccount();
        insert account;
        Opportunity opportunity = UTL_OCE_TestData.createOpportunity(account.Id);
        insert opportunity;
        Apttus_Proposal__Proposal__c thisProposal = UTL_TestData.setTSProposalData(false, CON_CPQ.TECH_SOLUTION, opportunity.Id, CON_CPQ.OCE);
        thisProposal.Approver_Level__c = 1;
        thisProposal.Total_Amount__c = 40000;
        thisProposal.CountryCode__c = 'India';
        thisProposal.Min_Gross_Margin__c = 40;
        thisProposal.Apttus_Proposal__Discount_Percent__c = 0;
        thisProposal.Actual_Discount_Value__c = 0;
        insert thisProposal;
        Approval_Matrix__c approvalMatrix = new Approval_Matrix__c(Levels__c= 'Level 1', Country__c = 'India', Min_Amount__c = 0, Max_Amount__c = 50000, Min_Gross_Margin__c = 0, Max_Gross_Margin__c = 45, Min_Discount_Percent__c = -100, Max_Discount_Percent__c = 100, Min_Discount_Amount__c = -99999999, Max_Discount_Amount__c = 99999999, Approver_1__c = UserInfo.getUserId(), Track_Name__c = 'CPQ', Pricing_Tool__c = 'OCE', Auto_Approve__c = FALSE );
        insert approvalMatrix;
        Set<String> fieldSet = new Set<String> {CON_CPQ.ID , CON_CPQ.LEVELS, CON_CPQ.PRIORITY,CON_CPQ.COUNTRY, CON_CPQ.MIN_AMOUNT, CON_CPQ.MAX_AMOUNT, CON_CPQ.MIN_GORSS_MARGIN, CON_CPQ.MAX_GORSS_MARGIN, CON_CPQ.MIN_DISCOUNT_PERCENT, CON_CPQ.MAX_DISCOUNT_PERCENT, CON_CPQ.MIN_DISCOUNT_AMOUNT, CON_CPQ.MAX_DISCOUNT_AMOUNT, CON_CPQ.APPROVER1, CON_CPQ.APPROVER2, CON_CPQ.APPROVER3, CON_CPQ.APPROVER4, CON_CPQ.APPROVER5, CON_CPQ.OBJECT_NAME, CON_CPQ.TRACK_NAME, CON_CPQ.PRICING_TOOL, CON_CPQ.AUTO_APPROVE};
        String condition = 'Min_Amount__c <= ' + thisProposal.Total_Amount__c +
				   ' AND Max_Amount__c > ' + thisProposal.Total_Amount__c +
				   ' AND Min_Gross_Margin__c <= ' + (thisProposal.Min_Gross_Margin__c == null? 0 : thisProposal.Min_Gross_Margin__c) +
				   ' AND Max_Gross_Margin__c > ' + (thisProposal.Min_Gross_Margin__c == null? 0 : thisProposal.Min_Gross_Margin__c) +
                   ' AND Min_Discount_Percent__c <= ' + (thisProposal.Apttus_Proposal__Discount_Percent__c == null? 0 : thisProposal.Apttus_Proposal__Discount_Percent__c) +
				   ' AND Max_Discount_Percent__c > ' + (thisProposal.Apttus_Proposal__Discount_Percent__c == null? 0 : thisProposal.Apttus_Proposal__Discount_Percent__c) +
				   ' AND Min_Discount_Amount__c <= ' + (thisProposal.Actual_Discount_Value__c == null? 0 : thisProposal.Actual_Discount_Value__c) +
				   ' AND Max_Discount_Amount__c > ' + (thisProposal.Actual_Discount_Value__c == null? 0 : thisProposal.Actual_Discount_Value__c) +
				   ' AND Country__c = ' + '\''+thisProposal.CountryCode__c + '\''+
				   ' AND Pricing_Tool__c = ' + '\'' + thisProposal.Select_Pricing_Tool__c + '\''+
				   ' AND Track_Name__c = ' + '\''+CON_CPQ.CPQ + '\'';
        
        Test.startTest();
        	List<Approval_Matrix__c> testApprovalMatrixList = new SLT_ApprovalMatrix().getApprover(fieldSet, condition);
        Test.stopTest();
    }
    @isTest
    static void testgetDiscountMatrix(){
        Approval_Matrix__c approvalMatrix = new Approval_Matrix__c(Levels__c= 'Level 1', Country__c = 'India', Min_Amount__c = 0, Max_Amount__c = 50000, Min_Gross_Margin__c = 0, Max_Gross_Margin__c = 45, Min_Discount_Percent__c = -100, Max_Discount_Percent__c = 100, Min_Discount_Amount__c = -99999999, Max_Discount_Amount__c = 99999999, Approver_1__c = UserInfo.getUserId(), Track_Name__c = 'CPQ', Pricing_Tool__c = 'OCE', Auto_Approve__c = FALSE );
        insert approvalMatrix;
        Set<String> approvalMatrixFieldSet = new Set<String> {CON_CPQ.MIN_AMOUNT, CON_CPQ.MAX_AMOUNT,  CON_CPQ.MIN_DISCOUNT_PERCENT, CON_CPQ.MAX_DISCOUNT_PERCENT, CON_CPQ.MIN_DISCOUNT_AMOUNT, CON_CPQ.MAX_DISCOUNT_AMOUNT};
        String condition = 'Process_Type__c = ' + '\'' + CON_CPQ.DISCOUNT_VALIDATION + '\'' +
                           ' AND Min_Amount__c < ' + approvalMatrix.Min_Amount__c +
                           ' AND Max_Amount__c >= ' + approvalMatrix.Max_Amount__c +
                           ' AND (Min_Discount_Percent__c <= ' + approvalMatrix.Min_Discount_Percent__c +
                           ' OR Min_Discount_Amount__c <= ' + approvalMatrix.Min_Discount_Amount__c +')';
        Test.startTest();
        	List<Approval_Matrix__c> testApprovalMatrixList = new SLT_ApprovalMatrix().getDiscountMatrix(approvalMatrixFieldSet, condition);
        Test.stopTest();
    }

    @isTest
    static void testGetApproverByPricingTool(){
        Approval_Matrix__c approvalMatrix = new Approval_Matrix__c(Levels__c= 'Level 1', Process_Type__c = CON_CPQ.APPROVAL_PROCESS, Country__c = 'India', Min_Amount__c = 0, Max_Amount__c = 50000, Min_Gross_Margin__c = 0, Max_Gross_Margin__c = 45, Min_Discount_Percent__c = -100, Max_Discount_Percent__c = 100, Min_Discount_Amount__c = -99999999, Max_Discount_Amount__c = 99999999, Approver_1__c = UserInfo.getUserId(), Track_Name__c = 'CPQ', Pricing_Tool__c = 'AMESA', Auto_Approve__c = FALSE );
        insert approvalMatrix;
        Set<String> approvalMatrixFieldSet = new Set<String> {CON_CPQ.MIN_AMOUNT, CON_CPQ.MAX_AMOUNT,  CON_CPQ.MIN_DISCOUNT_PERCENT, CON_CPQ.MAX_DISCOUNT_PERCENT, CON_CPQ.MIN_DISCOUNT_AMOUNT, CON_CPQ.MAX_DISCOUNT_AMOUNT};
        String condition = 'Process_Type__c = ' + '\'' + CON_CPQ.APPROVAL_PROCESS + '\'';
        List<String> assignedPricingTools = new List<String> {CON_CPQ.AMESA};
        Test.startTest();
        	List<Approval_Matrix__c> testApprovalMatrixList = new SLT_ApprovalMatrix().getApproverByPricingTool(approvalMatrixFieldSet, condition, assignedPricingTools);
        Test.stopTest();
    }
}