src/objects/Approval_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Approver_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver Group</label>
        <referenceTo>Approver_Group__c</referenceTo>
        <relationshipLabel>Approval Matrix</relationshipLabel>
        <relationshipName>Approval_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Arena</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>Biogen</fullName>
                </value>
                <value>
                    <fullName>Celgene</fullName>
                </value>
                <value>
                    <fullName>Daiichi Sankyo</fullName>
                </value>
                <value>
                    <fullName>Esperion</fullName>
                </value>
                <value>
                    <fullName>Genentech</fullName>
                </value>
                <value>
                    <fullName>Medivation</fullName>
                </value>
                <value>
                    <fullName>Merck KGaA</fullName>
                </value>
                <value>
                    <fullName>Novartis</fullName>
                </value>
                <value>
                    <fullName>Pfizer</fullName>
                </value>
                <value>
                    <fullName>Roche</fullName>
                </value>
                <value>
                    <fullName>Sunovion</fullName>
                </value>
                <value>
                    <fullName>Takeda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Global_Project_Unit__c</fullName>
        <label>Global Project Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA excluding Japan</fullName>
                </value>
                <value>
                    <fullName>Central Nervous System</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular Renal Metabolic</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <label>MD</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>No MD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Ballpark</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USA/Canada</fullName>
                </value>
                <value>
                    <fullName>Europe/Middle East/Africa EMEA</fullName>
                </value>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>To store Id of user</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BD Line Manager</fullName>
                </value>
                <value>
                    <fullName>Country Sales head</fullName>
                </value>
                <value>
                    <fullName>Delivery Head</fullName>
                </value>
                <value>
                    <fullName>Demand Head</fullName>
                </value>
                <value>
                    <fullName>In Copy 1</fullName>
                </value>
                <value>
                    <fullName>In Copy 2</fullName>
                </value>
                <value>
                    <fullName>Managing Director</fullName>
                </value>
                <value>
                    <fullName>Primary 1</fullName>
                </value>
                <value>
                    <fullName>Primary 2</fullName>
                </value>
                <value>
                    <fullName>R&amp;DS 1</fullName>
                </value>
                <value>
                    <fullName>R&amp;DS 2</fullName>
                </value>
                <value>
                    <fullName>R&amp;DS 3</fullName>
                </value>
                <value>
                    <fullName>R&amp;DS 4</fullName>
                </value>
                <value>
                    <fullName>R&amp;DS 5</fullName>
                </value>
                <value>
                    <fullName>R&amp;DS 6</fullName>
                </value>
                <value>
                    <fullName>R&amp;DS 7</fullName>
                </value>
                <value>
                    <fullName>cc</fullName>
                </value>
                <value>
                    <fullName>cc 1</fullName>
                </value>
                <value>
                    <fullName>Back Up</fullName>
                </value>
                <value>
                    <fullName>Head</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>TSSU 1</fullName>
                </value>
                <value>
                    <fullName>TSSU 2</fullName>
                </value>
                <value>
                    <fullName>TSSU 3</fullName>
                </value>
                <value>
                    <fullName>TSSU 4</fullName>
                </value>
                <value>
                    <fullName>TSSU 5</fullName>
                </value>
                <value>
                    <fullName>TSSU 6</fullName>
                </value>
                <value>
                    <fullName>TSSU 7</fullName>
                </value>
                <value>
                    <fullName>TSSU 8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <label>Sales</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Emerging BioPharma</fullName>
                </value>
                <value>
                    <fullName>DNU OTHER MIDSIZED PHARMA</fullName>
                </value>
                <value>
                    <fullName>EBP EMERGING BIOPHARMA</fullName>
                </value>
                <value>
                    <fullName>GLOBAL PHARMA</fullName>
                </value>
                <value>
                    <fullName>LARGE PHARMA</fullName>
                </value>
                <value>
                    <fullName>LOCAL (SMALL) PHARMA</fullName>
                </value>
                <value>
                    <fullName>MID-SIZE PHARMA</fullName>
                </value>
                <value>
                    <fullName>MIDSIZED GROWTH</fullName>
                </value>
                <value>
                    <fullName>LARGE</fullName>
                </value>
                <value>
                    <fullName>Mid Sized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Therapy_Area__c</fullName>
        <label>Therapy Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acute Care</fullName>
                </value>
                <value>
                    <fullName>Allergy/Immunology</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular</fullName>
                </value>
                <value>
                    <fullName>Dermatology</fullName>
                </value>
                <value>
                    <fullName>Gastrointestinal</fullName>
                </value>
                <value>
                    <fullName>Hematology</fullName>
                </value>
                <value>
                    <fullName>Hepatology</fullName>
                </value>
                <value>
                    <fullName>Infectious Disease</fullName>
                </value>
                <value>
                    <fullName>Medical Genetics</fullName>
                </value>
                <value>
                    <fullName>Nephrology</fullName>
                </value>
                <value>
                    <fullName>Neurology</fullName>
                </value>
                <value>
                    <fullName>Oncology</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pediatrics</fullName>
                </value>
                <value>
                    <fullName>Psychiatry</fullName>
                </value>
                <value>
                    <fullName>Respiratory</fullName>
                </value>
                <value>
                    <fullName>Rheumatology</fullName>
                </value>
                <value>
                    <fullName>Transplantation</fullName>
                </value>
                <value>
                    <fullName>Endocrinology/Diabetes</fullName>
                </value>
                <value>
                    <fullName>Rare Diseases</fullName>
                </value>
                <value>
                    <fullName>Sexual Health</fullName>
                </value>
                <value>
                    <fullName>Vaccines</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X0_5M_USD__c</fullName>
        <label>0 - 5M USD</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X10_20M_USD__c</fullName>
        <label>10 - 20M USD</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X20_50M_USD__c</fullName>
        <label>20 - 50M USD</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X50M_USD__c</fullName>
        <label>50M + USD</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X5_10M_USD__c</fullName>
        <label>5 - 10M USD</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Approval Matrix</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Approval Matrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Approver_Group__c.object
<CustomObject>
    <label>Approver Group</label>
    <nameField>
        <label>Approver Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approver Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SLT_ApproverGroup.cls
public with sharing class SLT_ApproverGroup extends fflib_SObjectSelector {
    public SLT_ApproverGroup() {
        super(false, false, false);
    }
    
    /**
     * This method used to get field list of sobject
     * @return  List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Approver_Group__c.Id,
            Approver_Group__c.Name
        };
    }    
    
    /**
     * This method used to set up type of sobject
     * @return  Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Approver_Group__c.sObjectType;
    }
    
    public List<Approver_Group__c> selectById(Set<ID> idSet) {
        return (List<Approver_Group__c>) selectSObjectsById(idSet);
    }
    
    public List<Approver_Group__c> getApproverGroupWithApprovalMatrixList() {
        return Database.query('SELECT Id, Name, (SELECT Id, Name, Approver_Group__c, Opportunity_Type__c, Region__c, X0_5M_USD__c, X5_10M_USD__c,'+
            'X10_20M_USD__c,' + 'X20_50M_USD__c, X50M_USD__c FROM Approval_Matrix__r) FROM Approver_Group__c');
    }
    
    public List<Approver_Group__c> getApproverGroupWithApprovalMatrixListWithApproverGroupFilter(String approverGroupName, String opportunityType,
        String customerType, String therapyArea, String region, String role, String sales, String md, String customerEmail,
        String globalProjectUnit, String customer) {  
        
        String approverGroupType = String.escapeSingleQuotes(approverGroupName.trim());
        String val = '\'%' + String.escapeSingleQuotes(approverGroupName.trim()) + '%\'';
        String approverGroupOpportunity = '\'%' + String.escapeSingleQuotes(opportunityType.trim()) + '%\'';
        
        if(approverGroupType == CON_CPQ.APPROVER_GROUP_TSSU){
            return Database.query('SELECT Id, Name, (SELECT Id, Name, Approver_Group__c, Opportunity_Type__c, Role__c, Sales__c, Md__c, Region__c,' +
                'Global_Project_Unit__c, Customer__c, ' + customerType + ' ,Therapy_Area__c, ' + customerEmail + ' FROM Approval_Matrix__r WHERE ' +  customerType +
                ' != null AND Opportunity_Type__c LIKE ' + approverGroupOpportunity + 'AND Region__c LIKE \'' + region + '\' AND Therapy_Area__c LIKE \'' + therapyArea +
                '\' AND Role__c LIKE \'' + role + '\' ) FROM Approver_Group__c Where Name LIKE ' + val);
        }
        else if(approverGroupType == CON_CPQ.APPROVER_GROUP_PL){
            return Database.query('SELECT Id, Name, (SELECT Id, Name, Approver_Group__c, Opportunity_Type__c, Role__c, Sales__c, Md__c, Region__c,' +
                'Global_Project_Unit__c, Customer__c, ' + customerType + ' ,Therapy_Area__c, ' + customerEmail + ' FROM Approval_Matrix__r WHERE ' + customerType +
                ' != null AND Opportunity_Type__c LIKE ' + approverGroupOpportunity + 'AND Role__c LIKE \'' + role + '\' AND Therapy_Area__c LIKE \'' + therapyArea +
                '\' AND Global_Project_Unit__c LIKE \'' + globalProjectUnit + '\' ) FROM Approver_Group__c Where Name LIKE ' + val);
        }
        else if(approverGroupType == CON_CPQ.APPROVER_GROUP_PL_CUSTOMER){
            return Database.query('SELECT Id, Name, (SELECT Id, Name, Approver_Group__c, Opportunity_Type__c, Role__c, Sales__c, Md__c, Region__c,' +
                'Global_Project_Unit__c, Customer__c, ' + customerType + ' ,Therapy_Area__c, ' + customerEmail +  ' FROM Approval_Matrix__r WHERE ' + customerType +
                ' != null AND Opportunity_Type__c LIKE ' + approverGroupOpportunity + 'AND Role__c LIKE \'' + role + '\' AND Therapy_Area__c LIKE \'' + therapyArea +
                '\' AND Customer__c LIKE \'' + customer + '\') FROM Approver_Group__c Where Name LIKE ' + '\'%' + CON_CPQ.APPROVER_GROUP_PL + '%\'');
        }
        else{
            return Database.query('SELECT Id, Name, (SELECT Id, Name, Approver_Group__c, Opportunity_Type__c, Role__c, Sales__c, Md__c, Region__c,' +
                'Global_Project_Unit__c, Customer__c, ' + customerType + ' ,Therapy_Area__c, ' + customerEmail + ' FROM Approval_Matrix__r WHERE '+ customerType +
                ' != null AND Opportunity_Type__c LIKE ' + approverGroupOpportunity + 'AND Region__c LIKE \'' + region + '\' AND Sales__c LIKE \'' + sales +
                '\' AND MD__c LIKE \'' + md + '\' AND Role__c LIKE \'' + role + '\') FROM Approver_Group__c Where Name LIKE ' + val);
        }
    }
}