src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IQVIA_Quote__c</fullName>
        <description>This field captures the IQVIA Quote id. Provide the capability to access the IQVIA Quote directly from the Conga quote.</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IQVIA Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Select_Pricing_Tool__c</fullName>
        <description>LC-5101: The field is having the name of selected Pricing Tool.</description>
        <inlineHelpText>The field is having the name of selected Pricing Tool.</inlineHelpText>
        <label>Pricing Tool Selected</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPQ_UPT</fullName>
                    <label>Unit Pricing Tool</label>
                </value>
                <value>
                    <fullName>LCS_UPT</fullName>
                    <label>LCS UPT</label>
                </value>
                <value>
                    <fullName>GRA_UPT</fullName>
                    <label>GRA UPT</label>
                </value>
                <value>
                    <fullName>IQB_UPT</fullName>
                    <isActive>false</isActive>
                    <label>IQB UPT</label>
                </value>
                <value>
                    <fullName>BMS Fixed Unit Pricing by Project</fullName>
                </value>
                <value>
                    <fullName>Biogen pricing tool</fullName>
                </value>
                <value>
                    <fullName>Central Lab Spreadsheet Calculator</fullName>
                </value>
                <value>
                    <fullName>Client Budget Tool</fullName>
                </value>
                <value>
                    <fullName>Client Pricing Tool</fullName>
                </value>
                <value>
                    <fullName>Customer Non-standard Pricing</fullName>
                </value>
                <value>
                    <fullName>EBP QIP</fullName>
                </value>
                <value>
                    <fullName>ECG Standalone Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Feasibility Calculator</fullName>
                </value>
                <value>
                    <fullName>Fee for Service Budget - Rates Only</fullName>
                </value>
                <value>
                    <fullName>Functional Non-standard Pricing</fullName>
                </value>
                <value>
                    <fullName>IntegRate ECD</fullName>
                </value>
                <value>
                    <fullName>LCS QIP</fullName>
                </value>
                <value>
                    <fullName>LinkPSB</fullName>
                </value>
                <value>
                    <fullName>NOBI</fullName>
                </value>
                <value>
                    <fullName>POP Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>PRISM</fullName>
                </value>
                <value>
                    <fullName>Proforma</fullName>
                </value>
                <value>
                    <fullName>QIP Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Regulatory-Non-QIP Budget tool</fullName>
                </value>
                <value>
                    <fullName>SMART Ready Upload Worksheet(s)</fullName>
                </value>
                <value>
                    <fullName>Small Study QIP</fullName>
                </value>
                <value>
                    <fullName>Takeda CDM Fixed unit File</fullName>
                </value>
                <value>
                    <fullName>Non SF Unit Pricing Tool</fullName>
                </value>
                <value>
                    <fullName>Unit_Pricing_Tool</fullName>
                    <isActive>false</isActive>
                    <label>Unit_Pricing_Tool</label>
                </value>
                <value>
                    <fullName>No QIP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <recordTypes>
        <fullName>Tech_Solution</fullName>
        <active>true</active>
        <description>Proposal record for Tech Solution</description>
        <label>Tech Solution</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <description>This field captures the stage of the quote life cycle.</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                 <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>CPQ-IQ-LC-12533: This field captures the type of licenses.</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Per Study</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GBU__c</fullName>
        <description>This field provides visibility of quote global business unit.</description>
        <label>Pathway</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RDS</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>Tech Solution</fullName>
                </value>
                <value>
                    <fullName>RDS Non-SF</fullName>
                </value>
                <value>
                    <fullName>RDS SF</fullName>
                </value>
                <value>
                    <fullName>RDS Non-SF WRF</fullName>
                    <label>RDS Non-SF (WRF)</label>
                </value>
                <value>
                    <fullName>Non-RDS</fullName>
                    <isActive>false</isActive>
                    <label>Del-Others</label>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <isActive>false</isActive>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Tools__c</fullName>
        <description>Read-only field that captures the list of all the selected pricing tools at the time of Quote creation. It gives visibility to different pricing tools that need to be configured under the current Quote.</description>
        <label>Pricing Tool(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>GBU__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete Consent</fullName>
                </value>
                <value>
                    <fullName>Q2 Solutions</fullName>
                </value>
                <value>
                    <fullName>QIP Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Central Lab Spreadsheet Calculator</fullName>
                </value>
                <value>
                    <fullName>SMART Ready Upload Worksheet(s)</fullName>
                </value>
                <value>
                    <fullName>Regulatory-Non-QIP Budget tool</fullName>
                </value>
                <value>
                    <fullName>IntegRate ECD</fullName>
                </value>
                <value>
                    <fullName>ECG Standalone Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Feasibility Calculator</fullName>
                </value>
                <value>
                    <fullName>Takeda CDM Fixed unit File</fullName>
                </value>
                <value>
                    <fullName>BMS Fixed Unit Pricing by Project</fullName>
                </value>
                <value>
                    <fullName>Functional Non-standard Pricing</fullName>
                </value>
                <value>
                    <fullName>Customer Non-standard Pricing</fullName>
                </value>
                <value>
                    <fullName>Fee for Service Budget - Rates Only</fullName>
                </value>
                <value>
                    <fullName>Small Study QIP</fullName>
                </value>
                <value>
                    <fullName>Client Pricing Tool</fullName>
                </value>
                <value>
                    <fullName>Biogen pricing tool</fullName>
                </value>
                <value>
                    <fullName>Proforma</fullName>
                </value>
                <value>
                    <fullName>LinkPSB</fullName>
                </value>
                <value>
                    <fullName>EBP QIP</fullName>
                </value>
                <value>
                    <fullName>PRISM</fullName>
                </value>
                <value>
                    <fullName>POP Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>NOBI</fullName>
                </value>
                <value>
                    <fullName>LCS QIP</fullName>
                </value>
                <value>
                    <fullName>Client Budget Tool</fullName>
                </value>
                <value>
                    <fullName>Non SF Unit Pricing Tool</fullName>
                </value>
                <value>
                    <fullName>No QIP</fullName>
                </value>
                <value>
                    <fullName>Non SF LCS Unit Pricing Tool</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Unit Pricing Tool</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Read-only field that captures the account from the linked opportunity. Provide the capability to access the account directly from the quote.</description>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Read-only field that captures the opportunity value on which Quote is created.</description>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>IQVIA Quotes</relationshipLabel>
        <relationshipName>IQVIA_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IQVIA Quote</label>
    <nameField>
        <displayFormat>IQ-{0000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IQVIA Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_UTL_CPQ_ProductFilterCallback.cls
@isTest
private class TST_UTL_CPQ_ProductFilterCallback {
    @testSetup
    static void dataSetup() {
        Account acc = UTL_TestData.createAccount();
        insert acc;
        Opportunity testOpportunity= UTL_TestData.createOpportunity(acc.Id);
        insert testOpportunity;
        
        Quote__c quote = new Quote__c();
        quote.Pricing_Tools__c = CON_CPQ.COMPLETE_CONSENT;
        quote.Approval_Stage__c = 'Draft';
        quote.GBU__c = CON_CPQ.GBU_DPS;
        quote.Related_Opportunity__c = testOpportunity.Id;
        quote.Related_Account__c = acc.Id;
        quote.License_Type__c = 'Per Study';
        insert quote; 
        Apttus_Config2__PriceList__c pl = TST_TestGeneratorClass.buildTestPriceList('Q2 Solutions - USD');
        pl.CurrencyIsoCode = 'USD';
        insert pl;
        
        Id recordTypeId = SObjectType.Apttus_Proposal__Proposal__c.getRecordTypeInfosByDeveloperName().get(CON_CPQ.TECH_SOLUTION).getRecordTypeId();
        Apttus_Proposal__Proposal__c proposal = UTL_TestData.createQuote();
        proposal.Apttus_Proposal__Account__c = acc.Id;
        proposal.RecordTypeId = recordTypeId;
        proposal.IQVIA_Quote__c = quote.Id;
        proposal.Apttus_Proposal__Opportunity__c = testOpportunity.Id;
        proposal.Select_Pricing_Tool__c = CON_CPQ.Complete_Consent;
        proposal.Apttus_Proposal__Approval_Stage__c = 'Draft';
        proposal.Apttus_QPConfig__PriceListId__c = pl.Id;
        insert proposal;
        
        Product2 prod = TST_TestGeneratorClass.buildTestProduct('SL-Development Metabolism', 'Bundle', 'Q_111813', 'US', 'Go Blue');
        prod.Apttus_Config2__HasOptions__c = true;
        prod.Apttus_Config2__HasAttributes__c = true;
        insert prod;
        
        Apttus_Config2__PriceListItem__c pli = TST_TestGeneratorClass.buildTestPriceListItem(pl.Id, prod.Id, 'PLI-011');  
        insert pli;   
    }
    
    @isTest
    static void testProductsExcludeForDPS() {
        Apttus_Proposal__Proposal__c proposal = [SELECT Id, IQVIA_Quote__r.License_Type__c, IQVIA_Quote__r.Document_Type__c FROM Apttus_Proposal__Proposal__c LIMIT 1];
        Apttus_Config2__ConfigCustomClasses__c apttusPricingCallbackClass = new Apttus_Config2__ConfigCustomClasses__c();
        apttusPricingCallbackClass.Apttus_Config2__ProductFilterCallbackClass__c = 'CPQ_ProductFilterCallback';
        apttusPricingCallbackClass.Name = 'System Properties'; 
        insert apttusPricingCallbackClass;
        Apttus_Config2__ProductConfiguration__c pc = new Apttus_Config2__ProductConfiguration__c();
        pc.Apttus_QPConfig__Proposald__c = proposal.Id;
        insert pc;
        Test.startTest();
            Apttus_Config2.CustomClass.ActionParams params = new Apttus_Config2.CustomClass.ActionParams();
            params.ConfigurationId = pc.Id;
            String condition =  UTL_CPQ_ProductFilterCallback.productsExcludeForDPS(proposal.IQVIA_Quote__r.License_Type__c, proposal.IQVIA_Quote__r.Document_Type__c);
            String condition2 =  UTL_CPQ_ProductFilterCallback.productsExcludeForDPS(proposal.IQVIA_Quote__r.License_Type__c, CON_CPQ.PDF_DOCUMENT_BUNDLES);
            String condition3 =  UTL_CPQ_ProductFilterCallback.productsExcludeForDPS(proposal.IQVIA_Quote__r.License_Type__c, CON_CPQ.INTERACTIVE_INDIVIDUAL_DOCUMENT);
            String condition4 =  UTL_CPQ_ProductFilterCallback.productsExcludeForDPS(proposal.IQVIA_Quote__r.License_Type__c, CON_CPQ.INTERACTIVE_DOCUMENT_BUNDLE);
        Test.stopTest();
        system.assertEquals(True, condition.length() > 0 , 'Product code should not be null');
        system.assertEquals(True, condition2.length() > 0 , 'Product code should not be null');
        system.assertEquals(True, condition3.length() > 0 , 'Product code should not be null');
        system.assertEquals(True, condition4.length() > 0 , 'Product code should not be null');
    }
}