src/objects/Apttus__DocumentVersion__c.object
<CustomObject>
    <description>Represents a document version</description>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the agreement associated with the document version</description>
        <inlineHelpText>ID of the agreement associated with the document version</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Document Versions</relationshipLabel>
        <relationshipName>DocumentVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__DocumentType__c</fullName>
        <description>Document type represents type of document in agreement life cycle</description>
        <inlineHelpText>Document type represents type of document in agreement life cycle</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement Document</fullName>
                </value>
                <value>
                    <fullName>Supporting Document</fullName>
                </value>
                <value>
                    <fullName>Executed Document</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PL Checklist</fullName>
                </value>
                <value>
                    <fullName>QC Checklist</fullName>
                </value>
                <value>
                    <fullName>PFM Approval</fullName>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Pricing Calculator</fullName>
                </value>
                <value>
                    <fullName>Discount Approval</fullName>
                </value>
                <value>
                    <fullName>BAM Approval</fullName>
                </value>
                <value>
                    <fullName>LCN Approval</fullName>
                </value>
                <value>
                    <fullName>Finance Approval</fullName>
                </value>
                <value>
                    <fullName>GLD Approval</fullName>
                </value>
                <value>
                    <fullName>Other MSA Approval</fullName>
                </value>
                <value>
                    <fullName>Strategic Pricing Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__IsTransient__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates a transient version. A new version is in transient state until the document is successfully attached to the version. Workflow rules should check this field to test for false before firing so that rules are not incorrectly fired when transient versions are created .</description>
        <inlineHelpText>Indicates a transient version. A new version is in transient state until the document is successfully attached to the version. Workflow rules should check this field to test for false before firing.</inlineHelpText>
        <label>Is Transient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus__LatestVersionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to latest version object</description>
        <inlineHelpText>Lookup to latest version object</inlineHelpText>
        <label>Latest Version Detail</label>
        <referenceTo>Apttus__DocumentVersionDetail__c</referenceTo>
        <relationshipLabel>Document Versions</relationshipLabel>
        <relationshipName>DocumentVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__LatestVersion__c</fullName>
        <description>Represents the most recent version of this document</description>
        <inlineHelpText>Represents the most recent version of this document</inlineHelpText>
        <label>Latest Version</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus__Title__c</fullName>
        <description>Title of the document</description>
        <inlineHelpText>Title of the document</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Document Version</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Versions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__DocumentVersionDetail__c.object
<CustomObject>
    <description>Holds the version details of a document</description>
    <fields>
        <fullName>Apttus__Action2__c</fullName>
        <description>The action which created the version</description>
        <inlineHelpText>The action which created the version</inlineHelpText>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Generate Agreement</fullName>
                </value>
                <value>
                    <fullName>Regenerate Agreement</fullName>
                </value>
                <value>
                    <fullName>Create Offline Agreement</fullName>
                </value>
                <value>
                    <fullName>Import Offline Agreement</fullName>
                </value>
                <value>
                    <fullName>Check In</fullName>
                </value>
                <value>
                    <fullName>Signed Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__ContentId__c</fullName>
        <description>ID of the associated content</description>
        <externalId>true</externalId>
        <inlineHelpText>ID of the associated content</inlineHelpText>
        <label>Content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus__DocumentVersionId__c</fullName>
        <description>Lookup to the Document Version this record is part of</description>
        <inlineHelpText>Lookup to the Document Version this record is part of</inlineHelpText>
        <label>Document Version</label>
        <referenceTo>Apttus__DocumentVersion__c</referenceTo>
        <relationshipLabel>Document Version Details</relationshipLabel>
        <relationshipName>Document_Version_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus__IsTransient__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates a transient version. A new version is in transient state until the document is successfully attached to the version. Workflow rules should check this field to test for false before firing so that rules are not incorrectly fired when transient versions are created .</description>
        <inlineHelpText>Indicates a transient version. A new version is in transient state until the document is successfully attached to the version. Workflow rules should check this field to test for false before firing.</inlineHelpText>
        <label>Is Transient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus__Title__c</fullName>
        <description>The title of the document version</description>
        <inlineHelpText>The title of the document version</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus__VersionMajor__c</fullName>
        <description>Major version</description>
        <inlineHelpText>Major version</inlineHelpText>
        <label>Version Major</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus__VersionMinor__c</fullName>
        <description>Minor version</description>
        <inlineHelpText>Minor version</inlineHelpText>
        <label>Version Minor</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus__VersionRevision__c</fullName>
        <description>Revision version</description>
        <inlineHelpText>Revision version</inlineHelpText>
        <label>Version Revision</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Version Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Version Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IQ_DocuSignEnvelope__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>APTS_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CLMCMA-21028: lookup to Conga Agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>DocuSign Envelopes</relationshipLabel>
        <relationshipName>DocuSign_Envelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocumentName__c</fullName>
        <description>List of Document names stored as JSON String of List&lt;String&gt; object</description>
        <inlineHelpText>List of Document names stored as JSON</inlineHelpText>
        <label>Document Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Docusign_AccountId__c</fullName>
        <description>CLM-MC-CLMCMA-18408: Docusign Account ID</description>
        <label>Docusign_AccountId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_As_User_Email__c</fullName>
        <description>CLM-MC-CLMCMA-18408: Send as User Email text field.</description>
        <label>Send As User Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <label>DocuSign Envelope Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QUE_CLM_DocusignSendForESignatures.cls
/**
* This Queueable class is used for the purpose of updating docusign E signatures status
*/ 
public class QUE_CLM_DocusignSendForESignatures implements Queueable, Database.AllowsCallouts {
    String baseUrl;
    IQ_DocuSignEnvelope__c env;   
    String authCode;
    public QUE_CLM_DocusignSendForESignatures(String baseUrl, IQ_DocuSignEnvelope__c env, String authCode) {
        this.baseUrl = baseUrl;
        this.env = env;
        this.authCode = authCode;
    }
    
    public void execute(QueueableContext context) { 
        migrateAsCombinedDocument();
    }
    
    /**
    * This method is used for migrating documents and changing status 
    */
    @testVisible
    private void migrateAsCombinedDocument() {  
        Integer numOfDocuments = 0;
        List<ContentDocumentLink> cdList = new List<ContentDocumentLink>();
        String userEmail = env.Send_As_User_Email__c;
        String accId = env.Docusign_AccountId__c;
        String documentUri = '/envelopes/' + env.Name + '/documents';  
        HttpResponse docDetailsresponse = CNT_APTMS_AddDocusignRecipient.doHttpCallout(baseUrl, documentUri, 'GET', authCode, null, userEmail);
        if(docDetailsresponse.getStatusCode() == 401) {
            authCode = CNT_APTMS_AddDocusignRecipient.getJWTAccessToken(accId, userEmail);
            docDetailsresponse = CNT_APTMS_AddDocusignRecipient.doHttpCallout(baseUrl, documentUri, 'GET', authCode, null, userEmail);
        }
        CNT_APTMS_AddDocusignRecipient.envelopeDocumentsResponseWrapper resdocs = 
            (CNT_APTMS_AddDocusignRecipient.envelopeDocumentsResponseWrapper)JSON.deserialize(
                docDetailsresponse.getBody(), CNT_APTMS_AddDocusignRecipient.envelopeDocumentsResponseWrapper.class);
        for(CNT_APTMS_AddDocusignRecipient.envelopeDocuments doc : resdocs.envelopeDocuments) { 
            if(doc.documentId != 'certificate') {
                numOfDocuments++;
            }
        }
        List<HttpResponse> responselist = new List<HttpResponse>();
        for(Integer i = 1; i <= numOfDocuments; i++) {
            HttpResponse response = CNT_APTMS_AddDocusignRecipient.doHttpCallout(baseUrl, documentUri + '/' + i, 'GET', authCode, null, userEmail);
            if(response.getStatusCode() == 401) {
                authCode = CNT_APTMS_AddDocusignRecipient.getJWTAccessToken(accId,userEmail);
                response = CNT_APTMS_AddDocusignRecipient.doHttpCallout(baseUrl, documentUri, 'GET', authCode, null,userEmail);
            }
            responselist.add(response);
        }
        HttpResponse responseCertificate = CNT_APTMS_AddDocusignRecipient.doHttpCallout(baseUrl,
            documentUri+ '/' + 'certificate', 'GET', authCode, null,userEmail);
        if(responseCertificate.getStatusCode() == 401) {
            authCode = CNT_APTMS_AddDocusignRecipient.getJWTAccessToken(accId,userEmail);
            responseCertificate = CNT_APTMS_AddDocusignRecipient.doHttpCallout(baseUrl,
                documentUri, 'GET', authCode, null, userEmail);
        }
        IQ_DocuSignEnvelope__c envelope = env;            
        List<String> docNames = (List<String>)Json.deserialize(envelope.DocumentName__c, List<String>.class);
        Integer documentNameIndex = 0; 
        String docName;
        List<ContentVersion> cvList = new List<ContentVersion>();
        for(HttpResponse rec : responselist) {
            if(rec.getStatusCode() == 200) {
                if(docNames.size() > documentNameIndex){
                    docName = (docNames[documentNameIndex] != null) && (docNames[documentNameIndex] != '') ? docNames[documentNameIndex] : '';
                }else{
                    docName = CON_CLM.CERT_OF_COMPLETION;
                }
                ContentVersion cVersion = new ContentVersion();
                cVersion.ContentLocation = 'S'; 
                cVersion.PathOnClient = docName + '.pdf';
                cVersion.Origin = 'H';
                cVersion.OwnerId = UserInfo.getUserId();
                cVersion.Title = docName.contains('.doc') ? docName.substring(0, docName.indexOf('.doc'))+'.pdf' : docName;
                cVersion.VersionData = rec.getBodyAsBlob();
                cvList.add(cVersion);
            }
            else {
                CNT_APTMS_AddDocusignRecipient.ResponseErrorWrapper resError = (CNT_APTMS_AddDocusignRecipient.ResponseErrorWrapper)JSON.deserialize(
                    rec.getBody(), CNT_APTMS_AddDocusignRecipient.ResponseErrorWrapper.class);
            }
            documentNameIndex++; 
        }
        if(cvList.size() > 0) {
            Set<Id> cvIds = new Set<Id>();
            List<ContentDocumentLink> cdlList = new List<ContentDocumentLink>();
            try {  
                fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
                    new Schema.SObjectType[] {
                        ContentVersion.SObjectType
                    }
                );
                uow.registerNew(cvList);
                uow.commitWork();
            } 
            catch(DMLException dmlExp) {
                System.debug(System.LoggingLevel.ERROR, dmlExp.getMessage() + ' \n ' + dmlExp.getStackTraceString());
            }
            for(ContentVersion rec : cvList) {
                cvIds.add(rec.Id);
            }
            List<ContentVersion> cvNewList = new SLT_ContentVersion().selectById(cvIds);
            List<Apttus__DocumentVersion__c> docVerList = new List<Apttus__DocumentVersion__c>();
            Map<Id, Apttus__DocumentVersion__c> contentVersionIdToDocumentVersionMap = new Map<Id, Apttus__DocumentVersion__c>();
            Map<Id, Apttus__DocumentVersionDetail__c> contentVersionIdToDocumentVersionDetailMap = new Map<Id, Apttus__DocumentVersionDetail__c>();  
            for(ContentVersion cv : cvNewList) {
                Apttus__DocumentVersion__c docVer = new Apttus__DocumentVersion__c();
                docVer.Apttus__Title__c = cv.Title.contains('.') ? cv.Title.substring(0, cv.Title.indexOf('.'))+'.pdf' : cv.Title;
                docVer.Name = CON_CLM.SIGNED_DOCUMENT;
                docVer.Apttus__AgreementId__c = envelope.APTS_Agreement__c;
                docVer.Apttus__LatestVersion__c = '1.0.0';
                docVer.Apttus__DocumentType__c = CON_CLM.EXECUTED_DOCUMENT;
                contentVersionIdToDocumentVersionMap.put(cv.Id, docVer);
            }
            try {  
                fflib_SObjectUnitOfWork uow1 = new fflib_SObjectUnitOfWork(
                    new Schema.SObjectType[] {
                        Apttus__DocumentVersion__c.SObjectType
                    }
                );
                uow1.registerNew(contentVersionIdToDocumentVersionMap.values());
                uow1.commitWork();
            }
            catch(DMLException dmlExp) {
                System.debug(System.LoggingLevel.ERROR, dmlExp.getMessage() + ' \n ' + dmlExp.getStackTraceString());
            }            
            for(ContentVersion cv : cvNewList) {
                if(contentVersionIdToDocumentVersionMap.containsKey(cv.Id))  {
                    Apttus__DocumentVersionDetail__c docVersionDetail = new Apttus__DocumentVersionDetail__c();
                    docVersionDetail.Name = '1.0.0';
                    docVersionDetail.Apttus__Title__c = cv.Title;
                    docVersionDetail.Apttus__DocumentVersionId__c = contentVersionIdToDocumentVersionMap.get(cv.Id).Id;
                    docVersionDetail.Apttus__ContentId__c = cv.ContentDocumentId;
                    docVersionDetail.Apttus__Action2__c = CON_CLM.SIGNED_DOCUMENT;
                    docVersionDetail.Apttus__VersionMajor__c = 1;
                    docVersionDetail.Apttus__VersionMinor__c = 0;
                    docVersionDetail.Apttus__VersionRevision__c = 0;       
                    docVersionDetail.Apttus__IsTransient__c = false;    
                    contentVersionIdToDocumentVersionDetailMap.put(cv.Id, docVersionDetail);
                }
            }
            try {  
                fflib_SObjectUnitOfWork uow2 = new fflib_SObjectUnitOfWork(
                    new Schema.SObjectType[] {
                        Apttus__DocumentVersionDetail__c.SObjectType
                    }
                );
                uow2.registerNew(contentVersionIdToDocumentVersionDetailMap.values());
                uow2.commitWork();
            } catch(DMLException dmlExp) {
                System.debug(System.LoggingLevel.ERROR, dmlExp.getMessage() + ' \n ' + dmlExp.getStackTraceString());
            }
            for(ContentVersion cv : cvNewList) {
                if(contentVersionIdToDocumentVersionDetailMap.containsKey(cv.Id)) {
                    contentVersionIdToDocumentVersionMap.get(cv.Id).Apttus__LatestVersionId__c = contentVersionIdToDocumentVersionDetailMap.get(cv.Id).Id;
                    ContentDocumentLink cDocLink = new ContentDocumentLink();
                    cDocLink.ContentDocumentId = cv.ContentDocumentId;
                    cDocLink.LinkedEntityId = contentVersionIdToDocumentVersionDetailMap.get(cv.Id).Id;
                    cDocLink.ShareType = 'I';
                    cDocLink.Visibility = 'InternalUsers';          
                    cdList.add(cDocLink);                      
                }
            }
            try {  
                fflib_SObjectUnitOfWork uow3 = new fflib_SObjectUnitOfWork(
                    new Schema.SObjectType[] {
                        Apttus__DocumentVersion__c.SObjectType, ContentDocumentLink.SObjectType
                    }
                );
                uow3.registerDirty(contentVersionIdToDocumentVersionMap.values());
                uow3.registerNew(cdList);
                uow3.commitWork();
            } catch(DMLException dmlExp) {
                System.debug(System.LoggingLevel.ERROR, dmlExp.getMessage() + ' \n ' + dmlExp.getStackTraceString());
            }    
        }
    }
}