src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    

    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/dsfs__DocuSign_Envelope__c.object
<CustomObject>
    <description>DocuSign Envelope for Salesforce</description>
    <fields>
        <fullName>dsfs__Source_Object__c</fullName>
        <description>Source Object</description>
        <inlineHelpText>Source Object</inlineHelpText>
        <label>Source Object</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope</label>
    <nameField>
        <displayFormat>DSE-{0000000}</displayFormat>
        <label>DocuSign Envelope</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_SLT_DocusignRecipient.cls
@isTest
private class TST_SLT_DocusignRecipient {

    @isTest
    private static void testSelectByIdShouldReturnList() {
        dsfs__DocuSign_Envelope__c envelope = new dsfs__DocuSign_Envelope__c();
        Apttus__APTS_Agreement__c agreement = TST_CLM_TestDataFactory.createAgreement(null, true);
        TST_CLM_TestDataFactory.createAgreementExtension(agreement.Id, true);
        
        TST_CLM_TestDataFactory.createClmConfigurationSetting(true);
        envelope.dsfs__Source_Object__c = agreement.Id;
        insert envelope;
        
        dsfs__DocuSign_Envelope_Recipient__c envelopeRecipient = new dsfs__DocuSign_Envelope_Recipient__c();
        envelopeRecipient.dsfs__DocuSign_EnvelopeID__c = envelope.Id;
        insert envelopeRecipient;

        Test.startTest();
            List<dsfs__DocuSign_Envelope_Recipient__c> resultList = new SLT_DocusignRecipient().selectById(
                new Set<Id>{envelopeRecipient.Id});
        Test.stopTest();

        System.assertNotEquals(0, resultList.size(), 'dsfs__DocuSign_Envelope_Recipient__c list should not be empty.');
    }
}