src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the price list is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migration_Id__c</fullName>
        <description>LC-8998: Used to perform data migration</description>
        <externalId>true</externalId>
        <label>Migration Id</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <fields>
        <fullName>Apttus_Config2__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the price list item is active. Inactive price list items are ignored.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AllocateGroupAdjustment__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether group adjustments should be allocated to the product</description>
        <label>Allocate Group Adjustment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AllowManualAdjustment__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether manual price adjustments are allowed for the product</description>
        <label>Allow Manual Adjustment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceListId__c</fullName>
        <description>ID of the price list associated with the product</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the product associated with the price list</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__RollupPriceToBundle__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the option price is rolled up to the bundle. Only applicable to product options.This field is deprecated. Use the Price Included in Bundle field instead.</description>
        <inlineHelpText>Indicates whether the quantity is auto updated when the default quantity field gets a new value</inlineHelpText>
        <label>Auto Update Quantity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The charge type sequence</description>
        <inlineHelpText>The charge type sequence</inlineHelpText>
        <label>Sequence</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Migration_Id__c</fullName>
        <description>LC-8998: Used to perform data migration</description>
        <externalId>true</externalId>
        <label>Migration Id</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceMatrix__c.object
<CustomObject>
    <description>Represents a price matrix associated with a price list entry</description>
    <fields>
        <fullName>Apttus_Config2__EnableDateRange__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether date range is enabled for the matrix</description>
        <inlineHelpText>Indicates whether date range is enabled for the matrix</inlineHelpText>
        <label>Enable Date Range</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EnableUsageIndexing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Index the usage quantity to enable cumulative usage rating</description>
        <inlineHelpText>Index the usage quantity to enable cumulative usage rating</inlineHelpText>
        <label>Enable Usage Indexing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsCumulativeRange__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the range dimension values are cumulative. This field is deprecated. Use the Cumulative Range value type instead.</description>
        <label>Is Cumulative Range (Deprecated)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceListItemId__c</fullName>
        <description>ID of the associated price list item</description>
        <label>Price List Item</label>
        <referenceTo>Apttus_Config2__PriceListItem__c</referenceTo>
        <relationshipLabel>Matrix Pricing</relationshipLabel>
        <relationshipName>PriceMatrices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The matrix evaluation sequence</description>
        <label>Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__StopProcessingMoreMatrices__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to prevent subsequent matrices from processing.</description>
        <label>Stop Processing More Matrices</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migration_Id__c</fullName>
        <description>LC-8998: Used to perform data migration</description>
        <externalId>true</externalId>
        <label>Migration Id</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Price Matrix</label>
    <nameField>
        <displayFormat>PM-{0000000000}</displayFormat>
        <label>Matrix Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Matrices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceMatrixEntry__c.object
<CustomObject>
    <description>Represents a single entry in a price matrix</description>
    <fields>
        <fullName>Apttus_Config2__IsIncluded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the tier is included</description>
        <inlineHelpText>Indicates whether the tier is included</inlineHelpText>
        <label>Is Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceMatrixId__c</fullName>
        <description>ID of the associated matrix</description>
        <label>Price Matrix</label>
        <referenceTo>Apttus_Config2__PriceMatrix__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>MatrixEntries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The matrix entry sequence</description>
        <label>Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Migration_Id__c</fullName>
        <description>LC-8998: Used to perform data migration</description>
        <externalId>true</externalId>
        <label>Migration Id</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Price Matrix Entry</label>
    <nameField>
        <displayFormat>ME-{0000000000}</displayFormat>
        <label>Matrix Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Matrix Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Migration_Id__c</fullName>
        <label>Migration Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_BCH_CPQ_CreatePriceMatrixEntry.cls
@IsTest
public class TST_BCH_CPQ_CreatePriceMatrixEntry {
	@testSetup
    static void dataSetup() {

        Apttus_Config2__PriceList__c priceList = TST_TestGeneratorClass.buildTestPriceList('Test PriceList');
        insert priceList;
   
        Product2 product = TST_TestGeneratorClass.buildTestProduct('LC9', 'Option','CPQ-TS-AMESA-Data-PI-KLPO', 'US', 'Go Blue');
        insert product;  
    }

    @isTest
    static void testCreatePriceMatrixEntry() {
        
        ID priceListiId = [SELECT ID FROM Apttus_Config2__PriceList__c LIMIT 1].ID;
        ID productId = [SELECT ID FROM Product2 LIMIT 1].ID;
        
        Apttus_Config2__PriceListItem__c priceListItem = new Apttus_Config2__PriceListItem__c();
        priceListItem.Apttus_Config2__Active__c = true;
        priceListItem.Apttus_Config2__PriceListId__c = priceListiId;
        priceListItem.Apttus_Config2__ProductId__c = productId;
        priceListItem.Apttus_Config2__RollupPriceToBundle__c = true; 
        priceListItem.Apttus_Config2__AllowManualAdjustment__c = true;
        priceListItem.Apttus_Config2__AllocateGroupAdjustment__c = true; 
        priceListItem.Migration_Id__c = 'PLI-011'; 
        insert priceListItem;
        
        Apttus_Config2__PriceMatrix__c priceMatrix = new Apttus_Config2__PriceMatrix__c(Apttus_Config2__PriceListItemID__c = priceListItem.ID, 
                                                                                        Apttus_Config2__EnableDateRange__c=false, 
                                                                                        Apttus_Config2__EnableUsageIndexing__c=false, 
                                                                                        Apttus_Config2__IsCumulativeRange__c=false, 
                                                                                        Apttus_Config2__Sequence__c=1, 
                                                                                        Apttus_Config2__StopProcessingMoreMatrices__c=false,
                                                                                        Migration_Id__c = 'PM-012');
        insert priceMatrix;
 
        Apttus_Config2__PriceMatrixEntry__c priceMatrixEntry = new Apttus_Config2__PriceMatrixEntry__c(Apttus_Config2__PriceMatrixID__c = priceMatrix.ID, 
                                                                                                       Apttus_Config2__IsIncluded__c = false, 
                                                                                                       Apttus_Config2__Sequence__c = 1,
                                                                                                       Migration_Id__c = 'PME-013');
        
        List<Apttus_Config2__PriceMatrixEntry__c> pmeList = new List<Apttus_Config2__PriceMatrixEntry__c>();
        pmeList.add(priceMatrixEntry);
        
        Test.startTest();
            BCH_CPQ_CreatePriceMatrixEntry objBatch = new BCH_CPQ_CreatePriceMatrixEntry(pmeList, '2024', 'AMESA', 1, 2);
            Database.executeBatch(objBatch);
        Test.stopTest();

        Apttus_Config2__PriceMatrixEntry__c createdPME = [SELECT ID FROM Apttus_Config2__PriceMatrixEntry__c LIMIT 1];
        System.assertNotEquals(null, createdPME, 'Price Matrix Entry created successfully');
    }
}