src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Proposal_Category__c</fullName>
        <description>The quote/proposal category</description>
        <inlineHelpText>The quote/proposal category</inlineHelpText>
        <label>Proposal Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                </value>
                <value>
                    <fullName>Rebid</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Project Specific</fullName>
                </value>
                <value>
                    <fullName>Ballpark</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Change_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CPQ: LC-8242 - Field is created to show the Change Order Quote association with  CNF Quotes.</description>
        <inlineHelpText>Proposal ID of the associated Change Order Quote.</inlineHelpText>
        <label>Related Change Order</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Associated CNF Quotes</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Global_project_unit__c</fullName>
        <description>MC-CRM-ESPSFDCQI-2690 -</description>
        <label>Global Project Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AA/Japan</fullName>
                </value>
                <value>
                    <fullName>AA excluding Japan</fullName>
                </value>
                <value>
                    <fullName>Access to Patients</fullName>
                </value>
                <value>
                    <fullName>Biogen</fullName>
                </value>
                <value>
                    <fullName>BioNTech</fullName>
                </value>
                <value>
                    <fullName>Biostats</fullName>
                </value>
                <value>
                    <fullName>Boehringer Ingelheim</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular Renal Metabolic</fullName>
                </value>
                <value>
                    <fullName>Central Laboratory</fullName>
                </value>
                <value>
                    <fullName>Central Nervous System</fullName>
                </value>
                <value>
                    <fullName>Clinical Monitoring</fullName>
                </value>
                <value>
                    <fullName>Clinical Technology</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Daiichi Sankyo</fullName>
                </value>
                <value>
                    <fullName>Data Management</fullName>
                </value>
                <value>
                    <fullName>Early Clinical Development</fullName>
                </value>
                <value>
                    <fullName>Electro Cardiogram</fullName>
                </value>
                <value>
                    <fullName>Feasibility</fullName>
                </value>
                <value>
                    <fullName>Flexible Resourcing Projects</fullName>
                </value>
                <value>
                    <fullName>GI-IWH</fullName>
                </value>
                <value>
                    <fullName>Gilead</fullName>
                </value>
                <value>
                    <fullName>GlaxoSmithKline</fullName>
                </value>
                <value>
                    <fullName>Global Regulatory Affairs</fullName>
                </value>
                <value>
                    <fullName>Internal Medicine</fullName>
                </value>
                <value>
                    <fullName>IQVIA Biotech CNS</fullName>
                </value>
                <value>
                    <fullName>IQVIA Biotech CVRM</fullName>
                </value>
                <value>
                    <fullName>IQVIA Biotech Dermatology</fullName>
                </value>
                <value>
                    <fullName>IQVIA Biotech Immunology</fullName>
                </value>
                <value>
                    <fullName>IQVIA Biotech Immuno-oncology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_this_IQVIA_Biotech__c</fullName>
        <description>ESPSFDCQI-4742</description>
        <label>Is this IQVIA Biotech</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_Quintiles_Opportunity_Number__c</fullName>
        <description>CRM-QI-ESPSFDCQI-314 Opportunity Number of opportunity record in legacy Quintiles org</description>
        <externalId>true</externalId>
        <inlineHelpText>Opportunity Number of opportunity record in legacy Quintiles org</inlineHelpText>
        <label>Legacy Quintiles Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Number_of_Potential_Regions__c</fullName>
        <description>ESPSFDCQI-2184 : This field is part of the OWF Process.</description>
        <label>Number of Potential Regions</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_CNT_CPQ_SendEmailOnCOQuoteAcceptance.cls
@isTest
private class TST_CNT_CPQ_SendEmailOnCOQuoteAcceptance {
    /**
    * This method is used to setup data for all methods.
    */
    @testSetup
    static void dataSetup() { 
        Account acc = UTL_TestData.createAccount();
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TestOpportunity';
        opp.stageName = CON_CRM.IDENTIFYING_OPP_STAGE;
        opp.AccountId = acc.Id;
        opp.CurrencyIsoCode = CON_CPQ.USD;
        opp.Is_this_IQVIA_Biotech__c = CON_CPQ.YES_TITLE_CASE;
        opp.Legacy_Quintiles_Opportunity_Number__c = CON_CPQ.TEST_OPPORTUNITY_NUMBER;
        opp.CloseDate = System.today();
        opp.Global_project_unit__c = 'AA/Japan';
        opp.Number_of_Potential_Regions__c = 0;
        insert opp;
        
        Bid_History__c clinicalBid = UTL_TestData.setClinicalBidData(CON_CPQ.AGREEMENT_RECORDTYPE_CLINICAL_BID, opp.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT);
        List<Apttus_Proposal__Proposal__c> proposalList = new List<Apttus_Proposal__Proposal__c>();
        
        Apttus_Proposal__Proposal__c quote1 = UTL_TestData.setProposalData(CON_CPQ.AGREEMENT_RECORDTYPE_BUDGET, opp.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT, clinicalBid.Id);
        quote1.Apttus_Proposal__Proposal_Category__c = CON_CPQ.CHNAGE_ORDER;
        quote1.CurrencyIsoCode = CON_CPQ.USD;
        update quote1;
        
        Apttus_Proposal__Proposal__c quote2 = UTL_TestData.setProposalData(CON_CPQ.AGREEMENT_RECORDTYPE_BUDGET, opp.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT, clinicalBid.Id);
        quote2.Apttus_Proposal__Proposal_Category__c = CON_CPQ.CNF;
        quote2.CurrencyIsoCode = CON_CPQ.USD;
        proposalList.add(quote2);
        
        Apttus_Proposal__Proposal__c quote3 = UTL_TestData.setProposalData(CON_CPQ.AGREEMENT_RECORDTYPE_BUDGET, opp.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT, clinicalBid.Id);
        quote3.Apttus_Proposal__Proposal_Category__c = CON_CPQ.CNF;
        quote3.CurrencyIsoCode = CON_CPQ.USD;
        proposalList.add(quote3);
        
        Apttus_Proposal__Proposal__c quote4 = UTL_TestData.setProposalData(CON_CPQ.AGREEMENT_RECORDTYPE_BUDGET, opp.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT, clinicalBid.Id);
        quote4.Apttus_Proposal__Proposal_Category__c = CON_CPQ.CNF;
        quote4.Related_Change_Order__c = quote1.Id;
        quote4.CurrencyIsoCode = CON_CPQ.USD;
        proposalList.add(quote4);
        update proposalList;  
    }

    @isTest 
    static void testGetAllCNFProposal() {
        Opportunity opp =[SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        	CNT_CPQ_SendEmailOnCOQuoteAcceptance.getAllCNFProposal();
        Test.stopTest();
        
        List<Apttus_Proposal__Proposal__c> cnfProposalList =[SELECT Id FROM Apttus_Proposal__Proposal__c WHERE Apttus_Proposal__Proposal_Category__c =: CON_CPQ.CNF AND Apttus_Proposal__Opportunity__c =: opp.Id];
        System.assertEquals(3, cnfProposalList.size(), 'CNF Record retrieved Successfully');
        
    }
    
    @isTest 
    static void testGetNonAssociatedCNF() {
        Opportunity opp =[SELECT Id FROM Opportunity LIMIT 1];
        CNT_CPQ_SendEmailOnCOQuoteAcceptance.coOpportunityId =opp.Id;
        
        Apttus_Proposal__Proposal__c coProposal = [SELECT Id, Name FROM Apttus_Proposal__Proposal__c WHERE Apttus_Proposal__Proposal_Category__c =: CON_CPQ.CHNAGE_ORDER LIMIT 1];
        CNT_CPQ_SendEmailOnCOQuoteAcceptance.recordID =coProposal.Id;
        
        Test.startTest();
        	List<Apttus_Proposal__Proposal__c> nonAssociatedCNF = CNT_CPQ_SendEmailOnCOQuoteAcceptance.getNonAssociatedCNF();
        Test.stopTest();
        System.assertEquals(2, nonAssociatedCNF.size(), 'Non-associated CNF Record retrieved Successfully');
        
    }
    
    @isTest 
    static void testGetAssociatedCNF() {
        Opportunity opp =[SELECT Id FROM Opportunity LIMIT 1];
        CNT_CPQ_SendEmailOnCOQuoteAcceptance.coOpportunityId =opp.Id;
        
        Apttus_Proposal__Proposal__c coProposal = [SELECT Id, Name FROM Apttus_Proposal__Proposal__c WHERE Apttus_Proposal__Proposal_Category__c =: CON_CPQ.CHNAGE_ORDER LIMIT 1];
        CNT_CPQ_SendEmailOnCOQuoteAcceptance.recordID =coProposal.Id;
        
        Test.startTest();
        	List<Apttus_Proposal__Proposal__c> associatedCNF = CNT_CPQ_SendEmailOnCOQuoteAcceptance.getAssociatedCNF();
        Test.stopTest();
        System.assertEquals(1, associatedCNF.size(), 'Associated CNF Record retrieved Successfully'); 
    }
     
}