src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    

    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>PSA</fullName>
        <active>true</active>
        <label>Project Specific Agreement</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Related_Agreement__c.object
<CustomObject>
    <description>To identify the different types of relationships between agreements</description>
    <fields>
        <fullName>Apttus__APTS_Contract_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship From</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>R00N50000001Xl0WEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__APTS_Contract_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship To</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>R00N50000001Xl0KEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Relationship_From_Type__c</fullName>
        <label>Relationship From Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Related NDA Is</fullName>
                </value>
                <value>
                    <fullName>Is NDA For</fullName>
                </value>
                <value>
                    <fullName>Is Master Of</fullName>
                </value>
                <value>
                    <fullName>Is Child Of</fullName>
                </value>
                <value>
                    <fullName>Is Related Contract</fullName>
                </value>
                <value>
                    <fullName>Is SOW Of</fullName>
                </value>
                <value>
                    <fullName>Is Amendment For</fullName>
                </value>
                <value>
                    <fullName>Is Amended By</fullName>
                </value>
                <value>
                    <fullName>Is Superceded By</fullName>
                </value>
                <value>
                    <fullName>Is Renewed By</fullName>
                </value>
                <value>
                    <fullName>Is Renewal For</fullName>
                </value>
                <value>
                    <fullName>Is Full Service Master Of</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Relationship_To_Type__c</fullName>
        <label>Relationship To Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Related NDA Is</fullName>
                </value>
                <value>
                    <fullName>Is NDA For</fullName>
                </value>
                <value>
                    <fullName>Is Master Of</fullName>
                </value>
                <value>
                    <fullName>Is Child Of</fullName>
                </value>
                <value>
                    <fullName>Is Related Contract</fullName>
                </value>
                <value>
                    <fullName>Is SOW Of</fullName>
                </value>
                <value>
                    <fullName>Is Amendment For</fullName>
                </value>
                <value>
                    <fullName>Is Amended By</fullName>
                </value>
                <value>
                    <fullName>Is Superceded By</fullName>
                </value>
                <value>
                    <fullName>Is Renewal For</fullName>
                </value>
                <value>
                    <fullName>Is Renewal By</fullName>
                </value>
                <value>
                    <fullName>Is Full Service Child Of</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Related Agreement</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_TGR_APTS_Related_Agreement.cls
/**
 * This test class is used to test Related Agreement Trigger.
 * version : 1.0
 */
@isTest
public class TST_TGR_APTS_Related_Agreement {
    @testSetup
    static void dataSetup() 
	{
        List<Apttus__APTS_Agreement__c> agreementList = new List<Apttus__APTS_Agreement__c>();
        Apttus__APTS_Agreement__c testAgreementPSA1 = TST_CLM_TestDataFactory.createAgreement(CON_CLM.PSA_RECORDTYPEID, false);
        testAgreementPSA1.Name = 'Test PSA agreement 1';
        agreementList.add(testAgreementPSA1);
        
        Apttus__APTS_Agreement__c testAgreementPSA2 = TST_CLM_TestDataFactory.createAgreement(CON_CLM.PSA_RECORDTYPEID, false);
        testAgreementPSA2.Name = 'Test PSA agreement 2';
        agreementList.add(testAgreementPSA2);
        
        insert agreementList;
        
        Apttus__APTS_Related_Agreement__c relatedAgreement = new Apttus__APTS_Related_Agreement__c();
        relatedAgreement.Name = 'Current Agreement';
        relatedAgreement.Apttus__Relationship_From_Type__c = 'Is Amended By';
        relatedAgreement.Apttus__APTS_Contract_From__c = testAgreementPSA1.Id;
        relatedAgreement.Apttus__Relationship_To_Type__c = 'Is Amendment For';
        relatedAgreement.Apttus__APTS_Contract_To__c = testAgreementPSA2.Id;
        insert relatedAgreement;
    }
        
    @IsTest
    static void testInsertOnRelatedAgreement() 
    {
        List<Apttus__APTS_Agreement__c> agreementList = new List<Apttus__APTS_Agreement__c>();
        Apttus__APTS_Agreement__c testAgreementPSA1 = TST_CLM_TestDataFactory.createAgreement(CON_CLM.PSA_RECORDTYPEID, false);
        testAgreementPSA1.Name = 'Test PSA agreement 1';
        agreementList.add(testAgreementPSA1);
        
        Apttus__APTS_Agreement__c testAgreementPSA2 = TST_CLM_TestDataFactory.createAgreement(CON_CLM.PSA_RECORDTYPEID, false);
        testAgreementPSA2.Name = 'Test PSA agreement 2';
        agreementList.add(testAgreementPSA2);
        
        insert agreementList;
        
        Apttus__APTS_Related_Agreement__c relatedAgreement = new Apttus__APTS_Related_Agreement__c();
        relatedAgreement.Name = 'Current Agreement 1';
        relatedAgreement.Apttus__Relationship_From_Type__c = 'Is Amended By';
        relatedAgreement.Apttus__APTS_Contract_From__c = testAgreementPSA1.Id;
        relatedAgreement.Apttus__Relationship_To_Type__c = 'Is Amendment For';
        relatedAgreement.Apttus__APTS_Contract_To__c = testAgreementPSA2.Id;
        
        Test.startTest();
            insert relatedAgreement;
        Test.stopTest();
        
        List<Apttus__APTS_Related_Agreement__c> relatedAgreementList = [SELECT Id, Name, Apttus__Relationship_From_Type__c
            FROM Apttus__APTS_Related_Agreement__c WHERE Name = 'Current Agreement 1'];
        System.assertEquals(1, relatedAgreementList.size());
    }
    
    @IsTest
    static void testUpdateOnRelatedAgreement() 
    {
        Apttus__APTS_Related_Agreement__c relatedAgreement = [SELECT Id, Name, Apttus__Relationship_From_Type__c
            FROM Apttus__APTS_Related_Agreement__c WHERE Name = 'Current Agreement'][0];
        relatedAgreement.Apttus__Relationship_From_Type__c = 'Is Master Of';
        
        Test.startTest();
            update relatedAgreement;
        Test.stopTest();
        
       Apttus__APTS_Related_Agreement__c updatedRelatedAgreement = [SELECT Id, Name, Apttus__Relationship_From_Type__c
            FROM Apttus__APTS_Related_Agreement__c WHERE Name = 'Current Agreement'][0];
        System.assertEquals('Is Master Of', updatedRelatedAgreement.Apttus__Relationship_From_Type__c);    
    }
    
    @IsTest
    static void testDeleteOnRelatedAgreement() 
    {
        Apttus__APTS_Related_Agreement__c relatedAgreement = [SELECT Id, Name, Apttus__Relationship_From_Type__c
            FROM Apttus__APTS_Related_Agreement__c WHERE Name = 'Current Agreement'][0];
        
        Test.startTest();
            delete relatedAgreement;
        Test.stopTest();
        
        List<Apttus__APTS_Related_Agreement__c> relatedAgreementList = [SELECT Id, Name, Apttus__Relationship_From_Type__c
            FROM Apttus__APTS_Related_Agreement__c WHERE Name = 'Current Agreement'];
        System.assertEquals(0, relatedAgreementList.size());
    }
    
    @IsTest
    static void testUnDeleteOnRelatedAgreement() 
    {
        Apttus__APTS_Related_Agreement__c relatedAgreement = [SELECT Id, Name, Apttus__Relationship_From_Type__c
            FROM Apttus__APTS_Related_Agreement__c WHERE Name = 'Current Agreement'][0];
        delete relatedAgreement;
        
        Test.startTest();
            undelete relatedAgreement;
        Test.stopTest();
        
        List<Apttus__APTS_Related_Agreement__c> relatedAgreementList = [SELECT Id, Name, Apttus__Relationship_From_Type__c
            FROM Apttus__APTS_Related_Agreement__c WHERE Name = 'Current Agreement'];
        System.assertEquals(1, relatedAgreementList.size());
    }
}