src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_Proposal__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Prospect Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SFDC_520_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>R00N70000001yUfDEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Proposal__Proposal_Category__c</fullName>
        <description>The quote/proposal category</description>
        <inlineHelpText>The quote/proposal category</inlineHelpText>
        <label>Proposal Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                </value>
                <value>
                    <fullName>Rebid</fullName>
                </value>
                <value>
                    <fullName>Preliminary</fullName>
                </value>
                <value>
                    <fullName>Project Specific</fullName>
                </value>
                <value>
                    <fullName>Ballpark</fullName>
                </value>
                <value>
                    <fullName>CNF</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bid_Number__c</fullName>
        <description>CPQ-LC-5555 : Clinical Bid Number field to be displayed on Proposal Related list on Clinical Bid.
        CPQ-LC-6896 : Referrence field change from Parent_Bid__c to Clinical_Bid__c after clinical bid movement from Agreement to Bid History object</description>
        <formula>Clinical_Bid__r.Bid_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bid Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget_Tool_Version_Date__c</fullName>
        <description>This field is used to capture the budget tool version date</description>
        <label>Budget Tool Version Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Link__c</fullName>
        <description>To store box path link</description>
        <label>External Link</label>
        <type>Url</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPQ_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Box_Path__c</fullName>
        <description>This path is used to generate the Box URL which is used on Quote and notification emails after SFC plan</description>
        <inlineHelpText>Please provide URL with correct domain of box</inlineHelpText>
        <label>Box Path</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>SFC_Template_Date__c</fullName>
        <label>SFC Template Date</label>
        <type>Date</type>
    </fields>
    <label>CPQ Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Legacy_Quintiles_Opportunity_Number__c</fullName>
        <description>CRM-QI-ESPSFDCQI-314 Opportunity Number of opportunity record in legacy Quintiles org</description>
        <externalId>true</externalId>
        <inlineHelpText>Opportunity Number of opportunity record in legacy Quintiles org</inlineHelpText>
        <label>Legacy Quintiles Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/QUE_CPQ_BudgetBoxFoldersJob.cls
/*
 * Version       : 1.0
 * Description   : Queueable Apex for create box folder for budget object.
 */
public class QUE_CPQ_BudgetBoxFoldersJob implements Queueable, Database.allowsCallouts 
{
    
    private List<Apttus_Proposal__Proposal__c> budgetList;
    
    public QUE_CPQ_BudgetBoxFoldersJob(List<Apttus_Proposal__Proposal__c> budgetList) 
    {
        Set<Id> budgetIdSet = new Set<Id>();
        for(Apttus_Proposal__Proposal__c budget : budgetList) 
        {
            budgetIdSet.add(budget.Id);
        }
        Set<String> fieldSet = new Set<String>{CON_CPQ.PROPOSAL_CATEGORY, CON_CPQ.PROPOSAL_RELATED_ACCOUNT_NAME, 
            CON_CPQ.PROPOSAL_RELATED_OPPORTUNITY_QUINTILES_NUMBER, CON_CPQ.NAME, CON_CPQ.AGREEMENT_BID_NUMBER, CON_CPQ.BUDGET_TOOL_VERSION_DATE};
        this.budgetList = new SLT_Proposal().getProposalsById(budgetIdSet, fieldSet);
    }

    public void execute(QueueableContext context) 
    {
        Box.Toolkit toolkit = new Box.Toolkit();
        CPQ_Settings__c cpqSetting = CPQ_Settings__c.getOrgDefaults();
        String boxDefaultPath = cpqSetting.Box_Path__c;
        for (Apttus_Proposal__Proposal__c budget : this.budgetList) 
        {
            String folderName = '';
            if(budget.Apttus_Proposal__Proposal_Category__c == CON_CPQ.INITIAL
              || budget.Apttus_Proposal__Proposal_Category__c == CON_CPQ.REBID)    
            {
                folderName = budget.Apttus_Proposal__Opportunity__r.Legacy_Quintiles_Opportunity_Number__c + ' - ' + 
                    budget.Bid_Number__c;
            }
            else
            {
                folderName = budget.Apttus_Proposal__Account__r.Name + ' ' + 
                    budget.Apttus_Proposal__Opportunity__r.Legacy_Quintiles_Opportunity_Number__c + ' ' + budget.Name;
            }
            String budgetFolderId = toolkit.createFolderForRecordId(budget.Id, folderName, false);
            if(budget.Budget_Tool_Version_Date__c >= cpqSetting.SFC_Template_Date__c) {
                if(budgetFolderId != null){
                    budget.External_Link__c = boxDefaultPath.replace('0', budgetFolderId);
                }
                else {
                    budget.External_Link__c = boxDefaultPath;
                }
            }
            else {
                budget.External_Link__c = CON_CPQ.BLANK;
            }
            if(budgetFolderId == null)
                system.debug('most recent error: ' + toolkit.mostRecentError);
        }
        update this.budgetList;
        toolkit.commitChanges();
    }
}