src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    

    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SObject_Sharing__c.object
<CustomObject>
    <description>Master table which stores Sharing Rules</description>
    <fields>
        <fullName>Enable_Sharing_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sharing Calculation is enabled for this record or not</description>
        <inlineHelpText>Sharing Calculation is enabled for this record or not</inlineHelpText>
        <label>Enable Sharing Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Sobject__c</fullName>
        <description>Parent SObject Api Name to fetch sharing logic</description>
        <inlineHelpText>Parent SObject Api Name to fetch sharing logic</inlineHelpText>
        <label>Parent Sobject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sharing_Territory_Label__c</fullName>
        <description>Apex Sharing Reason on Sharing Sobject for Territory</description>
        <inlineHelpText>Apex Sharing Reason on Sharing Sobject for Territory</inlineHelpText>
        <label>Sharing Territory Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SObject Sharing</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sobject Sharing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SObject Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_SLT_sObjectSharing.cls
/*
* Version       : 1.0
* Description   : This test class is used for Select SObject Sharing.
*/
@ISTest
private class TST_SLT_sObjectSharing {
    
    @testSetup
    static void dataSetup() {
        
        SObject_Sharing__c sObjSharing = new SObject_Sharing__c(Enable_Sharing_Calculation__c =true, 
                                         Parent_Sobject__c = 'Apttus__APTS_Agreement__c', Sharing_Territory_Label__c ='Opportunity');
        insert sObjSharing;    
    }
    
    @isTest
    static void testGetSObjectSharing(){
        
        LIst<SObject_Sharing__c> sobjectSharingList = [SELECT id, Enable_Sharing_Calculation__c FROM SObject_Sharing__c];
        Test.startTest();        
        Set<String> sObjectSharingFieldSet = new Set<String>{'Id', 'Enable_Sharing_Calculation__c'};
        List<SObject_Sharing__c> checkSObjectSharingList = new SLT_sObjectSharing().getSObjectSharing(sObjectSharingFieldSet);      
        Test.stopTest();
        System.assertEquals(sobjectSharingList[0].Id, checkSObjectSharingList[0].Id);        
    }
}