src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Subtype__c</fullName>
        <description>The subtype of the agreement for a given agreement type</description>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>ATP</fullName>
                </value>
                <value>
                    <fullName>SUWO</fullName>
                </value>
                <value>
                    <fullName>General Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Work Order</fullName>
                </value>
                <value>
                    <fullName>Master Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Other Master Agreement</fullName>
                </value>
                <value>
                    <fullName>DS3 SOW</fullName>
                </value>
                <value>
                    <fullName>AMESA SOW</fullName>
                </value>
                <value>
                    <fullName>Master Laboratory Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Letter Of Intent</fullName>
                </value>
                <value>
                    <fullName>General Consulting Agreement</fullName>
                </value>
                <value>
                    <fullName>General Services Agreement - Small Projects</fullName>
                </value>
                <value>
                    <fullName>Termination Agreements</fullName>
                </value>
                <value>
                    <fullName>Other Agreements</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
				<value>
                    <fullName>RX PHARMA or BIOTECH MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>EMERGING MARKET-LARGE</fullName>
                </value>
                <value>
                    <fullName>EMERGING MARKET-MID</fullName>
                </value>
                <value>
                    <fullName>START UP PHARMACEUTICAL</fullName>
                </value>
                <value>
                    <fullName>PRE-COMMERCIAL</fullName>
                </value>
                <value>
                    <fullName>OVER-THE-COUNTER PHARMACEUTICAL</fullName>
                </value>
                <value>
                    <fullName>MEDICAL EQUIPMENT &amp; SUPPLY MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>HEALTHCARE PROVIDER</fullName>
                </value>
                <value>
                    <fullName>HEALTHCARE PROVIDER – LIMITED</fullName>
                </value>
                <value>
                    <fullName>PHYSICIAN AUTHENTICATION (Website Operations)</fullName>
                </value>
                <value>
                    <fullName>DR. FINDER WEBSITE</fullName>
                </value>
                <value>
                    <fullName>PHYSICIAN AUTHENTICATION – Y/N ONLY (Website Operations)</fullName>
                </value>
                <value>
                    <fullName>COMMERCIAL MARKET RESEARCH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IQVIA_Project_Manager_Con__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CLM-MC-CLMCMA-9896 - This field is a lookup to user containing the IQVIA Project Manager value.</description>
        <label>IQVIA Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>IQVIA User Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Agreements (IQVIA Project Manager)</relationshipLabel>
        <relationshipName>AGR_IQVIA_Project_Managers_Con</relationshipName>
        <type>Lookup</type>
    </fields>
    

    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-1808 - Related user of the contact</description>
        <inlineHelpText>CRM-MC-ESPSFDCQI-1808 - Related user of the contact</inlineHelpText>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_DAOH_CRM_APTS_Agreement.cls
@isTest
public class TST_DAOH_CRM_APTS_Agreement {

    @isTest
    static void testUpdateEarlyEngagementCOE(){
        Test.startTest();
        	DAOH_CRM_APTS_Agreement.updateRfpReceivedDate(new List<Apttus__APTS_Agreement__c>(),new Map<Id,Apttus__APTS_Agreement__c>());
        Test.stopTest();
    }
    
    @isTest
    static void testUpdateSurveyPIC(){
        Contact testContact = new Contact(FirstName = 'TestFirstName', LastName = 'Test', Email = 'test@test.com', RecordTypeId = CON_CRM.CONTACT_RECORD_TYPE_IQVIA_USER_CONTACT, pse__Salesforce_User__c = UserInfo.getUserId(), Salesforce_User__c = UserInfo.getUserId());
        insert testContact;
        Apttus__APTS_Agreement__c agreement = TST_CLM_TestDataFactory.createAgreement(CON_CLM.PSA_RECORDTYPEID, false);
        agreement.Apttus__Subtype__c = 'Work Order';
        agreement.IQVIA_Project_Manager_Con__c = testContact.Id;
        insert agreement;
    }
}