src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    

    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_Proposal__RelatedProposalId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the related or parent quote/proposal</description>
        <inlineHelpText>ID of the related or parent quote/proposal</inlineHelpText>
        <label>Related Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Related Proposals</relationshipLabel>
        <relationshipName>RelatedProposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CPQ_ProposalLifecycle.cls
global class CPQ_ProposalLifecycle extends Apttus_Proposal.AbstractQuoteLifecycleCallback {

    global override void afterClone(Apttus_Proposal__Proposal__c originalSO, Apttus_Proposal__Proposal__c cloneSO) {
        cloneSO.Apttus_Proposal__RelatedProposalId__c = originalSO.Id;
    }
	
     /**
     * Callback invoked after an agreement is created from a quote/proposal
     * @param quoteSO the quote sobject 
     * @param agreementSO the new agreement sobject 
     */
    
    global override void afterCreateAgreement(Apttus_Proposal__Proposal__c quoteSO, Apttus__APTS_Agreement__c agreementSO) {
        if(agreementSO.RecordTypeId == CON_CLM.AMESA_RECORDTYPEID) {
            UTL_CLM.setAgreementFields(quoteSO,agreementSO);
        }
    }
}