src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus__Description__c</fullName>
        <description>The line description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Schedule1_Id__c</fullName>
        <description>CLM-MC-CLMCMA-3848 - Id of the schedule1 attachment record</description>
        <label>Schedule1 Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CNT_CLM_LoadSchedule1.cls
/*
 * Version       : 1.0
 * Description   : Apex Controller for Load Schedule1 lightning component
 */
public class CNT_CLM_LoadSchedule1 {

    @AuraEnabled
    public static Id createAgreementLineItem(Id agreementId, Id contentDocumentId) {
        if (agreementId == null || contentDocumentId == null) {
            return null;
        }
        Id attachmentId = convertContentDocumentToAttachment(contentDocumentId);
        Set<String> fieldSet = new Set<String>{'Id','Name'};
        List<Apttus__AgreementLineItem__c> agreementLineItems = new SLT_AgreementLineItems()
            .selectSchedule1ByAgreementIds(new Set<Id>{agreementId}, fieldSet);
        Apttus__AgreementLineItem__c lineItem;
        
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
        new Schema.SObjectType[] {
            Apttus__AgreementLineItem__c.SobjectType
        }
        );        
        
        if (!agreementLineItems.isEmpty()) {
            lineItem = agreementLineItems.get(0);
            lineItem.Schedule1_Id__c = attachmentId;
            uow.registerDirty(lineItem);
        }
        else {
            lineItem = new Apttus__AgreementLineItem__c();
            lineItem.Apttus__AgreementId__c = agreementId;
            lineItem.Apttus__Description__c = CON_CLM.FILE_NAME_SCHEDULE1;
            lineItem.Schedule1_Id__c = attachmentId;
            uow.registerNew(lineItem);
        }
        
        uow.commitWork();
        return lineItem.Id;
    }
    
    /**
    * This method is used to convert ContentDocument to Attachment 
    * @param Id contentDocumentId
    * @return Id attachment
    */
    @testVisible
    private static Id convertContentDocumentToAttachment(Id contentDocumentId) {
        Attachment attachmentToInsert = new Attachment();
        ContentDocument contentDocumentToDelete = new ContentDocument();
        Set<String> fieldSet = new Set<String>{'Title', 'Description', 'VersionData', 'FirstPublishLocationId', 'OwnerId', 'FileExtension'};
        List<ContentDocument> lstContentDocument = new SLT_ContentDocument().selectById(new Set<Id>{contentDocumentId});
        if(!lstContentDocument.isEmpty()) {
            contentDocumentToDelete = lstContentDocument.get(0);
        }
        List<ContentVersion> lstContentVersion = new SLT_ContentVersion().getContentVersionByDocumentIds(new Set<Id>
            {contentDocumentId}, fieldSet);
        if(lstContentVersion != null && !lstContentVersion.isEmpty()) {
            ContentVersion contentVersionRecord = lstContentVersion.get(0); 
            attachmentToInsert.ParentId = contentVersionRecord.FirstPublishLocationId;
            attachmentToInsert.Name = contentVersionRecord.Title + '.' + contentVersionRecord.FileExtension;
            attachmentToInsert.Description = contentVersionRecord.Description;
            attachmentToInsert.OwnerId = contentVersionRecord.OwnerId;
            attachmentToInsert.Body = contentVersionRecord.VersionData;
        }
        try {  
            fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<SObjectType>{
                Attachment.SObjectType, ContentDocument.SObjectType});
            uow.registerNew(attachmentToInsert);
            uow.registerDeleted(contentDocumentToDelete);
            uow.commitWork();
        } 
        catch(DMLException dmlExp) {
            System.debug(System.LoggingLevel.ERROR, dmlExp.getMessage() + ' \n ' + dmlExp.getStackTraceString());
        }     
        return attachmentToInsert.Id;  
    }
}