src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <fields>
        <fullName>Apttus_Proposal__Approval_Stage__c</fullName>
        <description>The proposal approval stage</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Submit for Review</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Sign Off</fullName>
                </value>
                <value>
                    <fullName>Final Review</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-2962 -</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Generic_Contract</fullName>
        <active>true</active>
        <description>This category is used for agreements that are being negotiated, but the exact contract form has not yet been determined</description>
        <label>Generic Contract</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Legacy_Quintiles_Opportunity_Number__c</fullName>
        <description>CRM-QI-ESPSFDCQI-314 Opportunity Number of opportunity record in legacy Quintiles org</description>
        <externalId>true</externalId>
        <inlineHelpText>Opportunity Number of opportunity record in legacy Quintiles org</inlineHelpText>
        <label>Legacy Quintiles Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1128 - Indicates which line of business the Opportunity aligns to. Used within the Mulesoft integration.</description>
        <inlineHelpText>Indicates which line of business the Opportunity aligns to.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allscripts Data</fullName>
                </value>
                <value>
                    <fullName>Avacare</fullName>
                </value>
                <value>
                    <fullName>Biosimilars</fullName>
                    <isActive>false</isActive>
                    <label>Biosimilars</label>
                </value>
                <value>
                    <fullName>Biostatistical/Medical Writing</fullName>
                    <isActive>false</isActive>
                    <label>Biostatistical/Medical Writing</label>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Clinical Pharmacology</fullName>
                    <isActive>false</isActive>
                    <label>Clinical Pharmacology</label>
                </value>
                <value>
                    <fullName>Clinical Technology</fullName>
                </value>
                <value>
                    <fullName>Clintec</fullName>
                    <isActive>false</isActive>
                    <label>Clintec</label>
                </value>
                <value>
                    <fullName>Commercial Solutions</fullName>
                </value>
                <value>
                    <fullName>Connected Devices</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Consulting Market Access</fullName>
                </value>
                <value>
                    <fullName>Core Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Core Clinical</label>
                </value>
                <value>
                    <fullName>Data Council</fullName>
                </value>
                <value>
                    <fullName>Data Management</fullName>
                    <isActive>false</isActive>
                    <label>Data Management</label>
                </value>
                <value>
                    <fullName>Data Sciences</fullName>
                </value>
                <value>
                    <fullName>Digital Patient (DPU)</fullName>
                    <isActive>false</isActive>
                    <label>Digital Patient (DPU)</label>
                </value>
                <value>
                    <fullName>DrugDev</fullName>
                    <isActive>false</isActive>
                    <label>DrugDev</label>
                </value>
                <value>
                    <fullName>Early Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Early Clinical</label>
                </value>
                <value>
                    <fullName>Early Clinical Development</fullName>
                </value>
                <value>
                    <fullName>ECG/Cardiac Safety</fullName>
                    <isActive>false</isActive>
                    <label>ECG/Cardiac Safety</label>
                </value>
                <value>
                    <fullName>Evidence Based Medicine (EBM)</fullName>
                </value>
                <value>
                    <fullName>GFR Clinical</fullName>
                    <isActive>false</isActive>
                    <label>GFR Clinical</label>
                </value>
                <value>
                    <fullName>Health Engagement &amp; Communication</fullName>
                </value>
                <value>
                    <fullName>Innovation</fullName>
                </value>
                <value>
                    <fullName>IT Services</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                    <isActive>false</isActive>
                    <label>Lab</label>
                </value>
                <value>
                    <fullName>Lifecycle Safety</fullName>
                    <isActive>false</isActive>
                    <label>Lifecycle Safety</label>
                </value>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Medical Communications</fullName>
                    <isActive>false</isActive>
                    <label>Medical Communications</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CLM-MC-CLMCMA-16597 - This field is lookup to BidHistory.</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_CNT_CPQ_CreateQuote.cls
@isTest
public class TST_CNT_CPQ_CreateQuote {
    static Opportunity setOpportunityData(Id accountId) {
        
        Opportunity testOpportunity = UTL_TestData.createOpportunity(accountId);
        testOpportunity.Line_of_Business__c = CON_CPQ.SAMPLE_LINE_OF_BUSINESS;
        testOpportunity.Legacy_Quintiles_Opportunity_Number__c = CON_CPQ.TEST_OPPORTUNITY_NUMBER;
        insert testOpportunity;
        return testOpportunity;
    }
    
    static Account setAccountData() {
        
        Account testAccount = UTL_TestData.createAccount();
        insert testAccount;
        return testAccount;
    }
    
    static Contract setContractData(Opportunity opp, String recordTypeDevName) {
        
        Contract testContract = UTL_TestData.createContract(opp, recordTypeDevName);
        insert testContract;
        return testContract;
    }
    
    @isTest
    static void testGetRelatedQuotesDetailsFromContract() {
        Account testAccount = setAccountData();
        Opportunity testOpportunity = setOpportunityData(testAccount.Id);
        Contract testContract = setContractData(testOpportunity, 'Generic_Contract');
        testContract.Opportunity__c = testOpportunity.Id;
        update testContract;
        Bid_History__c testClinicalBid = UTL_TestData.setClinicalBidData(CON_CPQ.AGREEMENT_RECORDTYPE_CLINICAL_BID, testOpportunity.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT);
        Apttus_Proposal__Proposal__c testQuoteData = UTL_TestData.setProposalData(CON_CPQ.AGREEMENT_RECORDTYPE_BUDGET, testOpportunity.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT, testClinicalBid.Id);
        testQuoteData.Apttus_Proposal__Approval_Stage__c = CON_CPQ.CANCELLED;
        update testQuoteData;
        Test.startTest();
            CNT_CPQ_CreateQuote.AllQuoteDetails allQuoteDetails = CNT_CPQ_CreateQuote.getRelatedQuotesDetails(false,testContract.Id);
            Id newBudgetId = allQuoteDetails.quoteId;
        Test.stopTest();
        System.assertNotEquals(newBudgetId, null, 'A primary and Accepted quote is present on opportunity');
    }
    
    @isTest
    static void testGetRelatedQuotesDetailsFromOpportunity() {
        Account testAccount = setAccountData();
        Opportunity testOpportunity = setOpportunityData(testAccount.Id);
        Bid_History__c testClinicalBid = UTL_TestData.setClinicalBidData(CON_CPQ.AGREEMENT_RECORDTYPE_CLINICAL_BID, testOpportunity.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT);
        Apttus_Proposal__Proposal__c testQuoteData = UTL_TestData.setProposalData(CON_CPQ.AGREEMENT_RECORDTYPE_BUDGET, testOpportunity.Id, CON_CPQ.AGREEMENT_SELECT_PRICING_TOOL_CPQ_UPT, testClinicalBid.Id);
        testQuoteData.Apttus_Proposal__Approval_Stage__c = CON_CPQ.CANCELLED;
        update testQuoteData;
        Test.startTest();
            CNT_CPQ_CreateQuote.AllQuoteDetails allQuoteDetails = CNT_CPQ_CreateQuote.getRelatedQuotesDetails(true,testOpportunity.Id);    
        Test.stopTest();
        Id newBudgetId = allQuoteDetails.quoteId;
        System.assertNotEquals(newBudgetId, null, 'A primary and Accepted quote is present on opportunity');
    }
}