src/objects/Apttus_Proposal__Proposal__c.object
<CustomObject>
    <description>Quote/Proposal object which holds dates and line items, many quotes/proposals may be related to a single opportunity, a quote/proposal may have many detail lines</description>
    <label>Quote/Proposal</label>
    <nameField>
        <displayFormat>Q-{00000000}</displayFormat>
        <label>Proposal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Proposal__Proposal_Line_Item__c.object
<CustomObject>
    <description>Represents a product or service line item associated with a quote/proposal</description>
    <fields>
        <fullName>Apttus_Proposal__Proposal__c</fullName>
        <description>ID of the associated quote/proposal</description>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>R00N70000001yUfBEAU</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BidGrid_Country__c</fullName>
        <description>Bidgrid country is used to store the country where service is provided whether resource is from the same country or not.</description>
        <label>BidGrid Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>APAC Regional</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>ASEAN Regional</fullName>
                </value>
                <value>
                    <fullName>Asia Mid Markets</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chad</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Country__c</fullName>
        <description>Pricing country is used to charge the price for a particular service, from where resource is used.</description>
        <label>Pricing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>APAC Regional</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>ASEAN Regional</fullName>
                </value>
                <value>
                    <fullName>Asia Mid Markets</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Chad</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Proposal Line Item</label>
    <nameField>
        <displayFormat>QL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DAOH_Proposal_Line_Item.cls
public class DAOH_Proposal_Line_Item {
    /**
    * This method is used to set Currency of PLI as per proposal's currency
    * @params  newProposalLineItemList List<Apttus_Proposal__Proposal_Line_Item__c>
    * @params  Map<Id, Apttus_Proposal__Proposal_Line_Item__c> oldMap
    * @return  void
    */
    public static void setLineItemCurrency(List<Apttus_Proposal__Proposal_Line_Item__c> newProposalLineItemList, Map<Id, Apttus_Proposal__Proposal_Line_Item__c> oldMap) {
        Set<Id> proposalIdSet = new Set<Id>();
        List<Apttus_Proposal__Proposal_Line_Item__c> updatedList = new List<Apttus_Proposal__Proposal_Line_Item__c>();
        for (Apttus_Proposal__Proposal_Line_Item__c pli : newProposalLineItemList) {
            proposalIdSet.add(pli.Apttus_Proposal__Proposal__c);
            updatedList.add(pli);
        }
        if(proposalIdSet.size() > 0) {
            Map<Id,Apttus_Proposal__Proposal__c> relatedProposalMap = new SLT_Proposal().selectByProposalIds(proposalIdSet, new Set<String> {CON_CPQ.ID, CON_CPQ.CURRENCYISOCODE, CON_CPQ.RECORD_TYPE_ID});
            for (Apttus_Proposal__Proposal_Line_Item__c lineItem : updatedList) {
                if(relatedProposalMap != null && relatedProposalMap.containsKey(lineItem.Apttus_Proposal__Proposal__c) 
                   && (relatedProposalMap.get(lineItem.Apttus_Proposal__Proposal__c).RecordType.Id == CPQ_Utility.proposalRDSNonSFRecordTypeId 
                       || relatedProposalMap.get(lineItem.Apttus_Proposal__Proposal__c).RecordType.Id == CPQ_Utility.proposalBudgetRecordTypeId))
                    lineItem.CurrencyIsoCode = relatedProposalMap.get(lineItem.Apttus_Proposal__Proposal__c).CurrencyIsoCode; 
            }
        }
    }
    
    public static void setPLICountry(List<Apttus_Proposal__Proposal_Line_Item__c> newProposalLineItemList, Map<Id, Apttus_Proposal__Proposal_Line_Item__c> oldRecordsMap) {
        for (Apttus_Proposal__Proposal_Line_Item__c pli : newProposalLineItemList) {
            if (pli.BidGrid_Country__c == CON_CPQ.MACEDONIA) {
                pli.BidGrid_Country__c = CON_CPQ.REPUBLIC_OF_NORTH_MACEDONIA;
            }
            if (pli.Pricing_Country__c == CON_CPQ.MACEDONIA) {
                 pli.Pricing_Country__c = CON_CPQ.REPUBLIC_OF_NORTH_MACEDONIA;
            }
        }
    }
}