src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N50000001Xl0FEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Subtype__c</fullName>
        <description>The subtype of the agreement for a given agreement type</description>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>ATP</fullName>
                </value>
                <value>
                    <fullName>SUWO</fullName>
                </value>
                <value>
                    <fullName>General Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Work Order</fullName>
                </value>
                <value>
                    <fullName>Master Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Other Master Agreement</fullName>
                </value>
                <value>
                    <fullName>DS3 SOW</fullName>
                </value>
                <value>
                    <fullName>AMESA SOW</fullName>
                </value>
                <value>
                    <fullName>Master Laboratory Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Letter Of Intent</fullName>
                </value>
                <value>
                    <fullName>General Consulting Agreement</fullName>
                </value>
                <value>
                    <fullName>General Services Agreement - Small Projects</fullName>
                </value>
                <value>
                    <fullName>Termination Agreements</fullName>
                </value>
                <value>
                    <fullName>Other Agreements</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
				<value>
                    <fullName>RX PHARMA or BIOTECH MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>EMERGING MARKET-LARGE</fullName>
                </value>
                <value>
                    <fullName>EMERGING MARKET-MID</fullName>
                </value>
                <value>
                    <fullName>START UP PHARMACEUTICAL</fullName>
                </value>
                <value>
                    <fullName>PRE-COMMERCIAL</fullName>
                </value>
                <value>
                    <fullName>OVER-THE-COUNTER PHARMACEUTICAL</fullName>
                </value>
                <value>
                    <fullName>MEDICAL EQUIPMENT &amp; SUPPLY MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>HEALTHCARE PROVIDER</fullName>
                </value>
                <value>
                    <fullName>HEALTHCARE PROVIDER – LIMITED</fullName>
                </value>
                <value>
                    <fullName>PHYSICIAN AUTHENTICATION (Website Operations)</fullName>
                </value>
                <value>
                    <fullName>DR. FINDER WEBSITE</fullName>
                </value>
                <value>
                    <fullName>PHYSICIAN AUTHENTICATION – Y/N ONLY (Website Operations)</fullName>
                </value>
                <value>
                    <fullName>COMMERCIAL MARKET RESEARCH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>OWF-MC-ESPSFDCQI-2160</description>
        <formula>TEXT(Apttus__Related_Opportunity__r.Line_of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    

    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>PSA</fullName>
        <active>true</active>
        <label>Project Specific Agreement</label>
    </recordTypes>
    <recordTypes>
        <fullName>RWLP</fullName>
        <active>true</active>
        <label>RWLP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1128 - Indicates which line of business the Opportunity aligns to. Used within the Mulesoft integration.</description>
        <inlineHelpText>Indicates which line of business the Opportunity aligns to.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allscripts Data</fullName>
                </value>
                <value>
                    <fullName>Avacare</fullName>
                </value>
                <value>
                    <fullName>Biosimilars</fullName>
                    <isActive>false</isActive>
                    <label>Biosimilars</label>
                </value>
                <value>
                    <fullName>Biostatistical/Medical Writing</fullName>
                    <isActive>false</isActive>
                    <label>Biostatistical/Medical Writing</label>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Clinical Pharmacology</fullName>
                    <isActive>false</isActive>
                    <label>Clinical Pharmacology</label>
                </value>
                <value>
                    <fullName>Clinical Technology</fullName>
                </value>
                <value>
                    <fullName>Clintec</fullName>
                    <isActive>false</isActive>
                    <label>Clintec</label>
                </value>
                <value>
                    <fullName>Commercial Solutions</fullName>
                </value>
                <value>
                    <fullName>Connected Devices</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Consulting Market Access</fullName>
                </value>
                <value>
                    <fullName>Core Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Core Clinical</label>
                </value>
                <value>
                    <fullName>Data Council</fullName>
                </value>
                <value>
                    <fullName>Data Management</fullName>
                    <isActive>false</isActive>
                    <label>Data Management</label>
                </value>
                <value>
                    <fullName>Data Sciences</fullName>
                </value>
                <value>
                    <fullName>Digital Patient (DPU)</fullName>
                    <isActive>false</isActive>
                    <label>Digital Patient (DPU)</label>
                </value>
                <value>
                    <fullName>DrugDev</fullName>
                    <isActive>false</isActive>
                    <label>DrugDev</label>
                </value>
                <value>
                    <fullName>Early Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Early Clinical</label>
                </value>
                <value>
                    <fullName>Early Clinical Development</fullName>
                </value>
                <value>
                    <fullName>ECG/Cardiac Safety</fullName>
                    <isActive>false</isActive>
                    <label>ECG/Cardiac Safety</label>
                </value>
                <value>
                    <fullName>Evidence Based Medicine (EBM)</fullName>
                </value>
                <value>
                    <fullName>GFR Clinical</fullName>
                    <isActive>false</isActive>
                    <label>GFR Clinical</label>
                </value>
                <value>
                    <fullName>Health Engagement &amp; Communication</fullName>
                </value>
                <value>
                    <fullName>Innovation</fullName>
                </value>
                <value>
                    <fullName>IT Services</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                    <isActive>false</isActive>
                    <label>Lab</label>
                </value>
                <value>
                    <fullName>Lifecycle Safety</fullName>
                    <isActive>false</isActive>
                    <label>Lifecycle Safety</label>
                </value>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Medical Communications</fullName>
                    <isActive>false</isActive>
                    <label>Medical Communications</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SLT_APTS_Agreement.cls
/*
 * Version       : 1.0
 * Description   : This Apex class is selector layer for OpportunitySplit
 */
public class SLT_APTS_Agreement extends fflib_SObjectSelector {
    
    public String orderByField = 'CreatedDate';
    
    /**
     * constructor to initialize CRUD and FLS
     */
    public SLT_APTS_Agreement() {
        super(false, true, true);
    }
    
    /**
     * constructor to initialise CRUD and FLS with a parameter for FLS.
     */
    public SLT_APTS_Agreement(Boolean enforceFLS) {
        super(false, true, enforceFLS);
    }
    
    /**
      */
    public SLT_APTS_Agreement(Boolean enforceCRUD,Boolean enforceFLS) {
        super(true, enforceCRUD, enforceFLS);
    }
    
    /**
     * Method to override OrderBy
     */
     
    public override String getOrderBy() {
        return orderByField;
    } 
    
    /**
     * This method used to get field list of sobject
     * @return  List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>();
    }
    
    /**
     * This method used to set up type of sobject
     * @return  Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Apttus__APTS_Agreement__c.sObjectType;
    }
    
    /**
     * This method used to get Agreements by Id
     * @return  Map<Id, Apttus__APTS_Agreement__c>
     */
    public Map<Id, Apttus__APTS_Agreement__c> getAgreementsById(Set<ID> idSet, Set<String> fieldSet) {
        return new Map<Id, Apttus__APTS_Agreement__c>((List<Apttus__APTS_Agreement__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).setCondition('Id in :idSet').toSOQL()));
    }
    
    /**
     * This method used to get Agreements by with Project, Resource Requests and Assigments
     * @params  Set<Id> agreementIdset
     * @params  Set<String> agreementFieldSet
     * @params  Set<String> projectFieldSet
     * @params  Set<String> resRequestFieldSet
     * @params  Set<String> assignmentFieldSet
     * @return  Map<Id, Apttus__APTS_Agreement__c>

    public Map<Id, Apttus__APTS_Agreement__c> selectByIdWithAgreementAndProjsResReqsAssignments(Set<ID> agreementIdset, Set<String> agreementFieldSet, Set<String> projectFieldSet, 
                                                                                    Set<String> resRequestFieldSet, Set<String> assignmentFieldSet) {
        fflib_QueryFactory agreementQueryFactory = newQueryFactory(true);
        fflib_QueryFactory.SortOrder fieldSortOrder = fflib_QueryFactory.SortOrder.DESCENDING;
        new SLT_Project(false,false).addQueryFactorySubselect(agreementQueryFactory, CON_OWF.AGREEMENT_PROJECTS, true).selectFields(projectFieldSet);
        new SLT_Resource_Request(false,false).addQueryFactorySubselect(agreementQueryFactory, CON_OWF.AGREEMENT_RESOURCE_REQUESTS, true).selectFields(resRequestFieldSet);
        new SLT_Assignment(false,false).addQueryFactorySubselect(agreementQueryFactory, CON_OWF.AGREEMENT_ASSIGNMENTS, true).selectFields(assignmentFieldSet);
        String queryString = agreementQueryFactory.selectFields(agreementFieldSet).setCondition('Id in :agreementIdset').toSOQL();
        return new Map<Id, Apttus__APTS_Agreement__c>((List<Apttus__APTS_Agreement__c>) Database.query(queryString));
    }
     */
    /**
     * This method used to get Agreements by with Resource Requests
     * @params  Set<Id> agreementIdset
     * @params  Set<String> agreementFieldSet
     * @params  Set<String> resRequestFieldSet
     * @return  Map<Id, Apttus__APTS_Agreement__c>

    public Map<Id, Apttus__APTS_Agreement__c> selectByIdWithAgreementResourceRequests(Set<ID> agreementIdset, Set<String> agreementFieldSet, Set<String> resRequestFieldSet) {
        fflib_QueryFactory agreementQueryFactory = newQueryFactory(true);
        fflib_QueryFactory.SortOrder fieldSortOrder = fflib_QueryFactory.SortOrder.DESCENDING;
        new SLT_Resource_Request(false,false).addQueryFactorySubselect(agreementQueryFactory, CON_OWF.AGREEMENT_RESOURCE_REQUESTS, true).selectFields(resRequestFieldSet);
        String queryString = agreementQueryFactory.selectFields(agreementFieldSet).setCondition('Id in :agreementIdset').toSOQL();
        return new Map<Id, Apttus__APTS_Agreement__c>((List<Apttus__APTS_Agreement__c>) Database.query(queryString));
    }
     */
    /**
     * This method used to get Agreements and related ResourceRequests
     * @return  Map<Id, Opportunity>

    public Map<Id, Apttus__APTS_Agreement__c> getAgreementAndResReqsByOppId(Set<ID> sObjectIdSet, Set<String> fieldSet, Set<String> resReqFieldSet, String agrCond, String resReqCond) {
        fflib_QueryFactory agreementQueryFactory = newQueryFactory(true);
        fflib_QueryFactory.SortOrder fieldSortOrder = fflib_QueryFactory.SortOrder.DESCENDING;
        new SLT_Resource_Request(false,false).addQueryFactorySubselect(agreementQueryFactory, CON_OWF.AGREEMENT_RESOURCE_REQUESTS, true).selectFields(resReqFieldSet).setCondition(resReqCond);
        String queryString = agreementQueryFactory.selectFields(fieldSet).setCondition(agrCond).toSOQL();
        return new Map<Id, Apttus__APTS_Agreement__c>((List<Apttus__APTS_Agreement__c>) Database.query(queryString));
    }
     */
    /**
     * This method used to get Agreement by with Opportunity
     * @params  Set<Id> agreementIdset
     * @params  Set<String> agreementFieldSet
     * @return  Map<Id, Apttus__APTS_Agreement__c>
     */
    public Map<Id, Apttus__APTS_Agreement__c> getAgreementByOppID(Set<ID> opportunityIdset, Set<String> agreementFieldSet) {
        fflib_QueryFactory agreementQueryFactory = newQueryFactory(true);
        String queryString = agreementQueryFactory.selectFields(agreementFieldSet).setCondition('Apttus__Related_Opportunity__c in :opportunityIdset').toSOQL();
        system.debug('Query-->' + queryString);
        return new Map<Id, Apttus__APTS_Agreement__c>((List<Apttus__APTS_Agreement__c>) Database.query(queryString));
    }
    
    /**
     * This method used to get Agreement by with Opportunity
     * @params  Set<Id> agreementIdset
     * @params  Set<String> agreementFieldSet
     * @return  Map<Id, Apttus__APTS_Agreement__c>
     */
    public Map<Id, Apttus__APTS_Agreement__c> getAgreementByOppIDSortByCreatedDateDesc(Set<ID> opportunityIdset, Set<String> agreementFieldSet) {
        orderByField = 'CreatedDate DESC';
        fflib_QueryFactory agreementQueryFactory = newQueryFactory(true);
        String queryString = agreementQueryFactory.selectFields(agreementFieldSet).setCondition('Apttus__Related_Opportunity__c in :opportunityIdset').toSOQL();
        system.debug('Query-->' + queryString);
        return new Map<Id, Apttus__APTS_Agreement__c>((List<Apttus__APTS_Agreement__c>) Database.query(queryString));
    }
	
    public Map<Id, Apttus__APTS_Agreement__c> getBudgetsRelatedToOpportunity(Set<Id> opportunityIdSet, Set<String> agreementFieldSet, String conditon) {
        orderByField = 'CreatedDate ASC';
        fflib_QueryFactory agreementQueryFactory = newQueryFactory(true);
        String queryString = agreementQueryFactory.selectFields(agreementFieldSet).setCondition(conditon).toSOQL();
        return new Map<Id, Apttus__APTS_Agreement__c>((List<Apttus__APTS_Agreement__c>) Database.query(queryString));
    }
    
    /**
     * This method used to get Agreement by  Opportunity Id order by createdDate Desc
     * @params  Set<Id> oppIdSet
     * @params  Set<String> agreementFieldSet
     * @return  List<Apttus__APTS_Agreement__c>
     */
    public List<Apttus__APTS_Agreement__c> getAgreementsByOppIds(Set<ID> oppIdSet, Set<String> agreementFieldSet, Set<String> LOB1Set, Set<String> LOB2Set) {
        fflib_QueryFactory queryFactory = newQueryFactory(false);
        queryFactory.selectFields(agreementFieldSet);
        queryFactory.setCondition('Apttus__Related_Opportunity__c IN :oppIdSet AND ( ( RecordType.DeveloperName = \'PSA\' AND Apttus__Related_Opportunity__r.Line_of_Business__c IN :LOB1Set AND Apttus__Subtype__c IN (\'Work Order\', \'Change Order\') ) OR ( RecordType.DeveloperName = \'RWLP\' AND Apttus__Related_Opportunity__r.Line_of_Business__c IN :LOB2Set AND  Apttus__Subtype__c IN ( \'Change Order\', \'ATP\', \'SUWO\', \'Amendment\') ))');
        queryFactory.setOrdering(new fflib_QueryFactory.Ordering('Apttus__APTS_Agreement__c', 'CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING));
        system.debug(queryFactory.toSOQL());
        return (List<Apttus__APTS_Agreement__c>) Database.query(queryFactory.toSOQL());
    }
    
}