src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    

    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-1808 - Related user of the contact</description>
        <inlineHelpText>CRM-MC-ESPSFDCQI-1808 - Related user of the contact</inlineHelpText>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/pse__Assignment__c.object
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Bid_History_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Sub_Group__c</fullName>
        <description>OWF-MC-This field is part of the OWF Process.</description>
        <formula>TEXT(pse__Resource__r.Sub_Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Resource Sub-Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subgroup_Name__c</fullName> 
        <description>OWF-MC-ESPSFDCQI-4846-This field is part of the OWF Process.</description>
        <formula>TEXT( pse__Resource_Request__r.SubGroup__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subgroup Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Resource_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Resource Request Lookup populated only when assignment is created from a resource request.</description>
        <label>Resource Request</label>
        <referenceTo>pse__Resource_Request__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.pse__Is_Resource__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Is_Resource_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <recordTypes>
        <fullName>RDS_Assignment</fullName>
        <active>true</active>
        <description>PSA-CLD-USNONE - Assignment used by the R&amp;DS organization</description>
        <label>RDS Assignment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Proj__c.object
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 Creating Bid History lookup for OWF Process</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Bid_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Related Program.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Bid</fullName>
        <active>true</active>
        <description>OWF-MC-ESPSFDCQI-2160</description>
        <label>Bid</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Related Program</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <inlineHelpText>You do not have to define the Project field when creating a child task. The Project field auto-populates from the parent task and overwrites any entered value.</inlineHelpText>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>RDS_Project_Task</fullName>
        <active>true</active>
        <description>PSA-CLD-USNONE- RDS Project Task</description>
        <label>RDS Project Task</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Resource_Request__c.object
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Bid_History_Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Created_Automatically__c</fullName>
        <defaultValue>false</defaultValue>
        <description>OWF-MC-ESPSFDCQI-4387 - If this is true then it denotes that the RR is created automatically</description>
        <inlineHelpText>If this is true then it denotes that the Resource Request is created automatically</inlineHelpText>
        <label>Is Created Automatically</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <description>OWF-MC-ESPSFDCQI-3042-This field is part of the OWF Process.</description>
        <label>SubGroup</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AIML Solutions</fullName>
                </value>
                <value>
                    <fullName>GBO-Lead PD</fullName>
                </value>
                <value>
                    <fullName>GBO-Bid Grid</fullName>
                </value>
                <value>
                    <fullName>GBO-RFI</fullName>
                </value>
                <value>
                    <fullName>GBO-Strategic Writer</fullName>
                </value>
                <value>
                    <fullName>GBO-Support CA</fullName>
                </value>
                <value>
                    <fullName>GBO-Support PD</fullName>
                </value>
                <value>
                    <fullName>GBO-Lead Contracts Analyst</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>TSL-Japan</fullName>
                </value>
                <value>
                    <fullName>Medical-MSL</fullName>
                </value>
                <value>
                    <fullName>Biosimilar-COE</fullName>
                </value>
                <value>
                    <fullName>ECD-COE</fullName>
                </value>
                <value>
                    <fullName>CAGT-COE</fullName>
                </value>
                <value>
                    <fullName>PRD-COE</fullName>
                </value>
                <value>
                    <fullName>TAL</fullName>
                </value>
                <value>
                    <fullName>Feasibility Analytics</fullName>
                </value>
                <value>
                    <fullName>Site Analytics</fullName>
                </value>
                <value>
                    <fullName>Design Analytics</fullName>
                </value>
                <value>
                    <fullName>Global Analytics</fullName>
                </value>
                <value>
                    <fullName>SPN Product Specialist</fullName>
                </value>
                <value>
                    <fullName>DSB-DM</fullName>
                </value>
                <value>
                    <fullName>DSB-LCS</fullName>
                </value>
                <value>
                    <fullName>DSB-Bios</fullName>
                </value>
                <value>
                    <fullName>DSB-MW</fullName>
                </value>
                <value>
                    <fullName>DSB-CEVA</fullName>
                </value>
                <value>
                    <fullName>DSB-Clinical</fullName>
                </value>
                <value>
                    <fullName>DSB-GSA</fullName>
                </value>
                <value>
                    <fullName>STS-Lead</fullName>
                </value>
                <value>
                    <fullName>CTS-Lead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>pse__Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>pse__Assignment__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Suggest a resource to use</inlineHelpText>
        <label>Suggested Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.pse__Is_Resource__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Contact.pse__Is_Resource_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Full_User_Name__c</fullName>
        <formula>FirstName &amp;&quot; &quot; &amp; LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full User Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SLT_Assignment.cls
/*
 * Version       : 1.0
 * Description   : This Apex class is selector layer for Assignment
 */
public class SLT_Assignment extends fflib_SObjectSelector {
    
    /**
     * constructor to initialize CRUD and FLS
     */
    public SLT_Assignment() {
        super(false, true, true);
    }
    
    /**
     * constructor to initialise CRUD and FLS with a parameter for FLS.
     */
    public SLT_Assignment(Boolean enforceFLS) {
        super(false, true, enforceFLS);
    }
    
    
    public SLT_Assignment(Boolean enforceFLS,Boolean enforceCRUD) {
        super(false, enforceFLS, enforceCRUD);
    }
    
    /**
     * This method used to get field list of sobject
     * @return  List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>();
    }
    /**
    * This method used to get pse__Assignment__c by Id
    * @return  List<pse__Assignment__c>
    */
    public List<pse__Assignment__c> selectById(Set<Id> idSet){

        return (List<pse__Assignment__c>) selectSObjectsById(idSet);
    }
    /**
     * This method used to set up type of sobject
     * @return  Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return pse__Assignment__c.sObjectType;
    }
    
    /**
     * This method used to get Resource requests with Assigments
     * @params  Set<ID> resourceRequestIdset
     * @params  Set<String> assignmentFieldSet
     * @return  Map<Id, pse__Assignment__c>
     */
    public Map<Id, pse__Assignment__c> selectAssignmentsByIdSet(Set<ID> sObjectIdset, String condition, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition(condition).toSOQL();
        return new Map<Id, pse__Assignment__c>((List<pse__Assignment__c>) Database.query(queryString));
    }
    /**
     * This method used to get Resource requests with Assigments
     * @params  Set<ID> resourceRequestIdset
     * @params  Set<String> assignmentFieldSet
     * @return  Map<Id, pse__Assignment__c>
     */
    public Map<Id, pse__Assignment__c> selectAssignmentsByFilter(Set<ID> sObjectIdset, 
                                                                 String condition, 
                                                                 Set<String> clientNameStringList, 
                                                                 Set<String> projectCodeSet, 
                                                                 Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition(condition).toSOQL();
        return new Map<Id, pse__Assignment__c>((List<pse__Assignment__c>) Database.query(queryString));
    }
    
    /**
     * This method used to get Assignemnt of Resource Request
     * @params  Set<Id> resourceRequestIdset
     * @params  Set<String> assignmentFieldSet
     * @return  Map<Id, pse__Assignment__c>
     */
    public Map<Id, pse__Assignment__c> getAssignmentResourceRequest(Set<ID> resourceRequestIdset, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('pse__Resource_Request__c in :resourceRequestIdset').toSOQL();
        return new Map<Id, pse__Assignment__c>((List<pse__Assignment__c>) Database.query(queryString));
    }
    
    /**
     * This method used to get Assignemnt of Resource
     * @params  Set<Id> sObjectIdset
     * @params  String assignmentCondition
     * @params  Set<String> assignmentFieldSet
     * @return  List<pse__Assignment__c>
     */
    public List<pse__Assignment__c> getAssignmentByResource(Set<Id> sObjectIdset, String assignmentCondition, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition(assignmentCondition).toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }
    
    /**
     * This method used to get Assignemnt of Resource
     * @params  Set<Id> resourceIdSet
     * @params  Set<Id> projectIdSet
     * @params  Set<String> assignmentFieldSet
     * @return  List<pse__Assignment__c>
     */
    public List<pse__Assignment__c> getAssignmentByResourceAndProject(Set<Id> resourceIdSet, Set<Id> projectIdSet, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('pse__Resource__c IN :resourceIdSet AND pse__Project__c IN :projectIdSet').toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }

    /**
     * This method used to get Assignemnt of Resource
     * @params  Set<Id> sObjectIdset
     * @params  Date currentDate
     * @params  String assignmentCondition
     * @params  Set<String> assignmentFieldSet
     * @return  List<pse__Assignment__c>
     */
    public List<pse__Assignment__c> getAssignmentByResourceAndCondition(Set<Id> sObjectIdset,Date currentDate, String assignmentCondition, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition(assignmentCondition).toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }
    
    /**
     * This method used to get Assignemnt of Resource
     * @params  Set<Id> agrIdset
     * @params  String assignmentCondition
     * @params  Set<String> assignmentFieldSet
     * @return  List<pse__Assignment__c>

    public List<pse__Assignment__c> getAssignmentByAgrAndCondition(Set<Id> agrIdset, String assignmentCondition, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('Agreement__c in: agrIdset '+assignmentCondition).toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }
     */
    /**
     * This method used to get Assignemnt of Resource
     * @params  Set<Id> agrIdset
     * @params  String assignmentCondition
     * @params  Set<String> assignmentFieldSet
     * @return  List<pse__Assignment__c>
     */
    public List<pse__Assignment__c> getAssignmentByBhrAndCondition(Set<Id> agrIdset, String assignmentCondition, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('Bid_History__c in: agrIdset '+assignmentCondition).toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }
    
    /**
     * This method retrieves assignments associated with a program
     */
    public List<pse__Assignment__c> getAssignmentsByProgram(Set<Id> programIdSet, Set<String> assignmentFieldSet){
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('pse__Project__r.Program__c in :programIdSet').toSOQL();
        return (List<pse__Assignment__c>) Database.query(queryString);
    }

    /**
     * This method retrieves assignments associated with a projects or it's child project
     */
    public List<pse__Assignment__c> getAssignmentsByProject(Set<Id> projectIdSet, Set<String> assignmentFieldSet){
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('pse__Project__c in :projectIdSet').toSOQL();
        return (List<pse__Assignment__c>) Database.query(queryString);
    }
    
    /**
     * This method used to get assignment by Agreement Id
     * @return  List<Apttus__APTS_Agreement__c>

    public List<pse__Assignment__c> selectAssignmentByAgreementId(Id agreementId, String resourceSubGroup) {
        return Database.query('SELECT Id, Name, Resource_Sub_Group__c, pse__Resource__r.Salesforce_User__r.Full_User_Name__c, pse__Resource_Request__r.Is_Created_Automatically__c FROM pse__Assignment__c WHERE pse__Resource_Request__r.SubGroup__c = \'' +
            resourceSubGroup + '\' AND Agreement__c = \'' + agreementId + '\'');            
    }
     */
    /**
     * This method used to get assignment by Clinical Bid Id
     * @return  List<Apttus__APTS_Agreement__c>
     */
    public List<pse__Assignment__c> selectAssignmentByClinicalBidId(Id clinicalBidID, String resourceSubGroup) {
        return Database.query('SELECT Id, Name, Resource_Sub_Group__c, pse__Resource__r.Salesforce_User__r.Full_User_Name__c, pse__Resource_Request__r.Is_Created_Automatically__c, Bid_History__c FROM pse__Assignment__c WHERE pse__Resource_Request__r.SubGroup__c = \'' +
            resourceSubGroup + '\' AND Bid_History__c = \'' + clinicalBidID + '\'');            
    }
    /*
     public List<pse__Assignment__c> getAssignmentListFromAgreement(Set<Id> agreementIdSet, Set<String> fieldSet){
         fflib_QueryFactory resourceRequestQueryFactory = newQueryFactory(true);
         String queryString = resourceRequestQueryFactory.selectFields(fieldSet).setCondition('Agreement__c in :agreementIdSet ').toSOQL();
         return (List<pse__Assignment__c>)Database.query(queryString);
     }
     */
    /*
    public List<pse__Assignment__c> getAssignmentByAgrAndConditionOrderByAgreementOwner(Set<Id> agrIdset, String assignmentCondition, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('Agreement__c in: agrIdset '+assignmentCondition).setOrdering('pse__Resource_Request__r.Is_Created_Automatically__c', fflib_QueryFactory.SortOrder.DESCENDING, true).toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }
     */
    public List<pse__Assignment__c> getAssignmentByBhrAndConditionOrderByBhrOwner(Set<Id> agrIdset, String assignmentCondition, Set<String> assignmentFieldSet){
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('Bid_History__c in: agrIdset '+assignmentCondition).setOrdering('pse__Resource_Request__r.Is_Created_Automatically__c', fflib_QueryFactory.SortOrder.DESCENDING, true).toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }
    
    /**
     * This method used to get Assignemnt of Resource
     * @params  Set<Id> resourceIdSet
     * @params  Set<Id> projectIdSet
     * @params  Set<String> assignmentFieldSet
     * @return  List<pse__Assignment__c>

    public List<pse__Assignment__c> getAssignmentByDSBSubgroupAndAgreementId(Set<Id> agreementIdSet, String subGroup, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('Agreement__c IN :agreementIdSet AND Subgroup_Name__c Like \''+subGroup+'\'').toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }
     */
    /**
    * This method used to get Latest AssignmentID ,Resource and Status order by Is_Created_Automatically__c desc
    * @return  pse__Assignment__c
    */
    public List<pse__Assignment__c> getAssignmentByAgreementRecordTypeAndStatus(Set<Id> clinicalBidId, String status, String recordTypeName, Set<String> rrRoles) {
        return Database.query('SELECT Id, Name, Pse__Resource__r.Name, Bid_History__c, Pse__Resource_Request__r.Name, Pse__Resource__r.Pse__Salesforce_User__c, Pse__Resource_Request__r.Is_Created_Automatically__c, Pse__Resource_Request__r.SubGroup__c, Pse__Status__c, Sub_role__c, Subgroup_Name__c, RecordType.Name FROM pse__Assignment__c WHERE Bid_History__c IN: clinicalBidId AND Pse__Resource__c != \'\' AND Pse__Status__c =: status AND '+
            'recordType.Name =: recordTypeName AND pse__Resource_Request__r.SubGroup__c IN : rrRoles order by pse__Resource_Request__r.Is_Created_Automatically__c desc,  pse__Resource_Request__r.SubGroup__c DESC, LastModifiedDate DESC');
    }
    
     /**
    * This method used to get Latest AssignmentID ,Resource and Status order by Is_Created_Automatically__c desc
    * @return  pse__Assignment__c

    public List<pse__Assignment__c> getAssignmentByAgreementRecordTypeAndStatusAndAutomatic(Set<Id> agreementId, String status, String recordTypeName) {
        return Database.query('Select Id, Name, pse__Resource__r.Name, Agreement__c, pse__Resource_Request__r.Name, pse__Resource__r.pse__Salesforce_User__c, pse__Resource_Request__r.Is_Created_Automatically__c, pse__Resource_Request__r.SubGroup__c , pse__Status__c, Sub_role__c, Subgroup_Name__c, recordType.Name from pse__Assignment__c where Agreement__c IN: agreementId AND pse__Resource__c != \'\' AND pse__Status__c =: status AND '+
            'recordType.Name =: recordTypeName AND pse__Resource_Request__r.Is_Created_Automatically__c = true order by pse__Resource_Request__r.Is_Created_Automatically__c DESC, pse__Resource_Request__r.SubGroup__c DESC, LastModifiedDate DESC');
    }
    */
    /**
    * This method used to get Automatic Latest AssignmentID ,Resource and Status order by Is_Created_Automatically__c, SubGroup__c, LastModifieddate desc
    * @return  pse__Assignment__c

    public List<pse__Assignment__c> getAssignmentByAgreementRecordTypeAndStatusAndAutomaticBySubGroup(Set<Id> agreementId, String status, String recordTypeName, List<String> subGroupList) {
        return Database.query('Select Id, Name, pse__Resource__r.Name, Agreement__c, pse__Resource_Request__r.Name, pse__Resource__r.pse__Salesforce_User__c, pse__Resource_Request__r.Is_Created_Automatically__c, pse__Resource_Request__r.SubGroup__c, pse__Status__c,Sub_role__c, Subgroup_Name__c,recordType.Name from pse__Assignment__c where Agreement__c IN: agreementId AND pse__Resource__c != \'\' AND pse__Status__c =: status AND '+
            'recordType.Name =: recordTypeName AND pse__Resource_Request__r.Is_Created_Automatically__c = true  AND Subgroup_Name__c IN: subGroupList order by pse__Resource_Request__r.Is_Created_Automatically__c DESC,  pse__Resource_Request__r.SubGroup__c DESC, LastModifiedDate DESC');
    }
    */
    /**
    * This method used to get Manual Latest AssignmentID ,Resource and Status order by Is_Created_Automatically__c, SubGroup__c, LastModifieddate desc
    * @return  pse__Assignment__c

    public List<pse__Assignment__c> getAssignmentByAgreementRecordTypeAndStatusAndManualBySubGroup(Set<Id> agreementId, String status, String recordTypeName, List<String> subGroupList) {
        return Database.query('Select Id, Name, pse__Resource__r.Name, Agreement__c, pse__Resource_Request__r.Name, pse__Resource__r.pse__Salesforce_User__c, pse__Resource_Request__r.Is_Created_Automatically__c, pse__Resource_Request__r.SubGroup__c , pse__Status__c, Sub_role__c, Subgroup_Name__c, recordType.Name from pse__Assignment__c where Agreement__c IN: agreementId AND pse__Resource__c != \'\' AND pse__Status__c =: status AND '+
            'recordType.Name =: recordTypeName AND pse__Resource_Request__r.Is_Created_Automatically__c = false  AND Subgroup_Name__c IN: subGroupList order by pse__Resource_Request__r.Is_Created_Automatically__c DESC,  pse__Resource_Request__r.SubGroup__c DESC, LastModifiedDate DESC');
    }
    */
    /**
    * This method used to get records by Latest AssignmentID and Salesforce User
    * @return  pse__Assignment__c
    */
    public List<pse__Assignment__c> getAssignmentClinicalBidAndUser(List<Id> clinicalBidId, List<Id> userIds) {
        return Database.query('SELECT Id, pse__Resource__r.pse__Salesforce_User__c, Bid_History__c, pse__Resource_Request__r.SubGroup__c, Subgroup_Name__c ' + 
            'FROM pse__Assignment__c WHERE Bid_History__c IN: clinicalBidId AND pse__Resource__r.pse__Salesforce_User__c IN: userIds');
    }
    
    /* This method used to get Latest AssignmentID ,Resource, Status and SubGrouporder by Is_Created_Automatically__c desc
    * @return  pse__Assignment__c

    public List<pse__Assignment__c> getAssignmentByAgreementRecordTypeStatusAndSubGroup(Set<Id> agreementId, String status, String recordTypeName,  List<String> subGroupList) {
        return Database.query('Select Id, Name, pse__Resource__r.Name,Agreement__c, pse__Resource_Request__r.Name, pse__Resource__r.pse__Salesforce_User__c, pse__Resource_Request__r.Is_Created_Automatically__c, pse__Resource_Request__r.SubGroup__c , pse__Status__c,Sub_role__c, Subgroup_Name__c, recordType.Name from pse__Assignment__c where Agreement__c IN: agreementId AND pse__Resource__c != \'\' AND pse__Status__c =: status AND '+
            'recordType.Name =: recordTypeName AND Subgroup_Name__c IN: subGroupList order by pse__Resource_Request__r.Is_Created_Automatically__c desc, pse__Resource_Request__r.SubGroup__c DESC, LastModifiedDate DESC ');
    }
    */
    
    /**
     * This method used to get rltd Assignments' list by Project Id
     * @return  Map<Id, pse__Assignment__c> key: 
     */
    public Map<Id, List<pse__Assignment__c>> selectAssignmentsByProjId(Set<String> idSet,Set<String> fieldSet) {
        Map<Id, List<pse__Assignment__c>> returnMap = new Map<Id, List<pse__Assignment__c>>();

        //Id rdsProjTaskRecordTypeId = Schema.SObjectType.pse__Project_Task__c.getRecordTypeInfosByDeveloperName().get('RDS_Project_Task').getRecordTypeId();
        for (pse__Assignment__c pt : (List<pse__Assignment__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).setCondition('pse__Project__c in :idSet').toSOQL())) {
            
            List<pse__Assignment__c> tempList = returnMap.get(pt.pse__Project__c);
            
            if (tempList != null) {
                tempList.add(pt);
                returnMap.put(pt.pse__Project__c, tempList);
            } else {
                returnMap.put(pt.pse__Project__c, new List<pse__Assignment__c>{pt});
            }
        }

        return returnMap;
    }
    
    /**
     * This method retrieves active assignments associated with a projects or it's child project
     */
    public List<pse__Assignment__c> getActiveAssignmentsByProject(Set<Id> projectIdSet, Set<String> assignmentFieldSet){
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('Active__c = true AND pse__Project__c in :projectIdSet AND RecordType.DeveloperName = \'RDS_Assignment\'').toSOQL();
        return (List<pse__Assignment__c>) Database.query(queryString);
    }
    
    /**
     * This method retrieves active service line lead assignments associated with a PVS project and with RDS Project in the set
     */

    
    public List<pse__Assignment__c> getActiveAssignmentsByProjectLitratureANDPvSolution(Set<Id> parentProjectIdSet, String whereClause, Set<String> assignmentFieldSet){
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition(whereClause).toSOQL();
        return (List<pse__Assignment__c>) Database.query(queryString);
    }
	
	/**
	 * This method is used to get Assignment by userId and Bid Id.
	 */
    public List<pse__Assignment__c> getAssignmentBySubgroupAndbidIdAnduserId(Set<Id> bidIdSet, Set<String> subGroup, Set<String> assignmentFieldSet,Set<Id> userIds, String assignmentCondition) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition(assignmentCondition).toSOQL();
		return ((List<pse__Assignment__c>) Database.query(queryString));
    }
		
    public List<pse__Assignment__c> getAssignmentByBhrAndConditionOrderByRRCreatedDate(Set<Id> oppIdSet, String assignmentCondition, Set<String> assignmentFieldSet) {
        fflib_QueryFactory assignmentQueryFactory = newQueryFactory(true);
        String queryString = assignmentQueryFactory.selectFields(assignmentFieldSet).setCondition('Bid_History__r.Bid_History_Related_Opportunity__c in: oppIdSet '+assignmentCondition).setOrdering('pse__Resource_Request__r.CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING, true).toSOQL();
        return ((List<pse__Assignment__c>) Database.query(queryString));
    }
}