src/objects/Apttus__APTS_Template__c.object
<CustomObject>
    <description>Contract language templates available in the system. These templates specify guidance, language, local setitngs, and include Word attachment templates representing the bulk of actual contracts that can be used when creating a first draft . Templates can include standard and non-standard language.</description>
    <label>Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CPQ_Mapping_Field_Set__mdt.object
<CustomObject>
    <fields>
        <fullName>Document_Formats__c</fullName>
        <label>Document Formats</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Tool__c</fullName>
        <label>Pricing Tool</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature_Selection__c</fullName>
        <description>This field contains the type of feature of the particular entry.</description>
        <label>Feature Selection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <label>Template Name</label>
        <length>131071</length>
        <type>LongTextArea</type>
    </fields>
    <label>CPQ Mapping Field Set</label>
    <pluralLabel>CPQ Mapping Field Sets</pluralLabel>
</CustomObject>

src/objects/CPQ_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CPQ Settings</label>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Pricing_Tool__c</fullName>
        <description>CLM-MC-CLMCMA-13641-Used To Select Pricing Tool For Quote</description>
        <label>Pricing Tool</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No QIP</fullName>
                </value>
                <value>
                    <fullName>Outcome</fullName>
                </value>
                <value>
                    <fullName>POP Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>QIP Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>POP</fullName>
                    <isActive>false</isActive>
                    <label>POP</label>
                </value>
                <value>
                    <fullName>QIP</fullName>
                    <isActive>false</isActive>
                    <label>QIP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote__c.object
<CustomObject>
    <label>IQVIA Quote</label>
    <nameField>
        <displayFormat>IQ-{0000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IQVIA Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CNT_CPQ_GenerateDocument.cls
public class CNT_CPQ_GenerateDocument {
    @AuraEnabled
    public static String getAvailableTemplate(String recordId, String objectAPIName, String pricingTools) {
        Set<String> pricingToolSet = new Set<String>();
        Set<String> templateNameSet = new Set<String>();
        String documentNames = '';
        List<CPQ_Mapping_Field_Set__mdt> cpqTemplateList = new List<CPQ_Mapping_Field_Set__mdt>();
        for (String pricingTool : pricingTools.split(';')) {
             pricingToolSet.add(pricingTool);
        }
        if (pricingToolSet.size() > 0) {
            cpqTemplateList = [SELECT Id, Pricing_Tool__c, Template_Name__c, Document_Formats__c FROM CPQ_Mapping_Field_Set__mdt WHERE Pricing_Tool__c IN : pricingToolSet AND Feature_Selection__c = 'Document Generation'];
        }
        if (cpqTemplateList.size() > 0 ) {
            for (CPQ_Mapping_Field_Set__mdt templateName : cpqTemplateList) {
                for (String tPname : templateName.Template_Name__c.split(';')) {
                     templateNameSet.add(tPname);
                }
            }
            if (templateNameSet.size() > 0) {
                for (String templateNames : templateNameSet) {
                     documentNames += templateNames + ',';
                } 
            }
            return documentNames.substring(0, documentNames.length()-1);
        } else {
            return CON_CPQ.FAILED;  
        }
    }

    @AuraEnabled
    public static String generateDocument(String templateName, Id recordId, String objectAPIName, String format) {
        Id templateId;
        if (!String.isBlank(templateName)) {
            templateId = [SELECT Id FROM Apttus__APTS_Template__c WHERE NAME =: templateName LIMIT 1].Id;
        }
        CPQ_Settings__c cpqs = [SELECT Id, Name, Client_Id__c, Client_Secret__c FROM CPQ_Settings__c LIMIT 1];
        String sessionId = getAccessToken(cpqs.Client_Id__c, cpqs.Client_Secret__c);
        if (sessionId.contains(CON_CPQ.ERROR)) {
            return sessionId;
        }
        return generateRequest(templateId, sessionId, recordId, objectAPIName, format);
    }

    public static String getAccessToken(String clientId, String clientSecret) {
        try {
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint(Url.getOrgDomainUrl() + '/services/oauth2/token?grant_type=client_credentials&client_id=' + clientId + '&client_secret=' + clientSecret);
            req.setMethod('POST');
            HttpResponse res = h.send(req);
            while (res.getStatusCode() == 302) {
                req.setEndpoint(res.getHeader('Location'));
                res = new Http().send(req);
            }
            Object result = JSON.deserializeUntyped(res.getBody());
            Map<String, Object> resultMap = (Map<String, Object>)result;
            String accessToken = (String)resultMap.get('access_token');
            return accessToken;
        } catch(Exception ex) {
            return 'Error: ' + ex.getMessage();
        }
    }
    
    public static String generateRequest(Id templateId, String sessionId, Id recordId, String objectAPIName, String format) {
        string serverUrl = '';
        String contentDocumentId;
        try {
            if (!Test.isRunningTest()) {  
                serverUrl = System.Url.getOrgDomainUrl().toExternalForm() + '/services/Soap/u/50.0/' + UserInfo.getOrganizationId();
                contentDocumentId = Apttus.MergeWebService.generateCustomDoc(templateId, recordId, objectAPIName, 'Full access', format, false, sessionId, serverUrl);
            }
        } catch(Exception ex) {
            return 'Error: ' + ex.getMessage();
        }
        return contentDocumentId;
    }

    @AuraEnabled
    public static Quote__c getPricingTools(String recordId) {
        Quote__c quote = new SLT_IQVIA_Quote().getQuoteDetails(recordId);
        return quote;
    }

    @AuraEnabled
    public static Boolean updateContentDocuments(List<String> generatedDocuments){
        try {
            List<ContentDocument> contentDocuments = new List<ContentDocument>();
            if (!generatedDocuments.isEmpty()) {
                for (ContentDocument contentDocument : [SELECT Title, Description FROM ContentDocument WHERE Id IN: generatedDocuments]) {
                    contentDocument.Title = CON_CPQ.DRAFT_PREFIX + '_' + contentDocument.Title;
                    contentDocument.Description = CON_CPQ.DRAFT_PREFIX;
                    contentDocuments.add(contentDocument);
                }
                if (!contentDocuments.isEmpty()) {
                    update contentDocuments;
                    return true;
                }
            }
            return false;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}