src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N50000001Xl0FEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Subtype__c</fullName>
        <description>The subtype of the agreement for a given agreement type</description>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>ATP</fullName>
                </value>
                <value>
                    <fullName>SUWO</fullName>
                </value>
                <value>
                    <fullName>General Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Work Order</fullName>
                </value>
                <value>
                    <fullName>Master Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Other Master Agreement</fullName>
                </value>
                <value>
                    <fullName>DS3 SOW</fullName>
                </value>
                <value>
                    <fullName>AMESA SOW</fullName>
                </value>
                <value>
                    <fullName>Master Laboratory Services Agreement</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Letter Of Intent</fullName>
                </value>
                <value>
                    <fullName>General Consulting Agreement</fullName>
                </value>
                <value>
                    <fullName>General Services Agreement - Small Projects</fullName>
                </value>
                <value>
                    <fullName>Termination Agreements</fullName>
                </value>
                <value>
                    <fullName>Other Agreements</fullName>
                </value>
                <value>
                    <fullName>Change Order</fullName>
                </value>
				<value>
                    <fullName>RX PHARMA or BIOTECH MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>EMERGING MARKET-LARGE</fullName>
                </value>
                <value>
                    <fullName>EMERGING MARKET-MID</fullName>
                </value>
                <value>
                    <fullName>START UP PHARMACEUTICAL</fullName>
                </value>
                <value>
                    <fullName>PRE-COMMERCIAL</fullName>
                </value>
                <value>
                    <fullName>OVER-THE-COUNTER PHARMACEUTICAL</fullName>
                </value>
                <value>
                    <fullName>MEDICAL EQUIPMENT &amp; SUPPLY MANUFACTURER</fullName>
                </value>
                <value>
                    <fullName>HEALTHCARE PROVIDER</fullName>
                </value>
                <value>
                    <fullName>HEALTHCARE PROVIDER – LIMITED</fullName>
                </value>
                <value>
                    <fullName>PHYSICIAN AUTHENTICATION (Website Operations)</fullName>
                </value>
                <value>
                    <fullName>DR. FINDER WEBSITE</fullName>
                </value>
                <value>
                    <fullName>PHYSICIAN AUTHENTICATION – Y/N ONLY (Website Operations)</fullName>
                </value>
                <value>
                    <fullName>COMMERCIAL MARKET RESEARCH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IQVIA_Project_Manager_Con__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CLM-MC-CLMCMA-9896 - This field is a lookup to user containing the IQVIA Project Manager value.</description>
        <label>IQVIA Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>IQVIA User Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Agreements (IQVIA Project Manager)</relationshipLabel>
        <relationshipName>AGR_IQVIA_Project_Managers_Con</relationshipName>
        <type>Lookup</type>
    </fields>
    

    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>PSA</fullName>
        <active>true</active>
        <label>Project Specific Agreement</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Sat_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <description>Unique field created so that we do not have duplicate survey records for an opportunity.</description>
        <label>Opportunity Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Client Sat Survey</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Customer Survey Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Sat Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Update_Survey_Event__e.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-9854</description>
    <fields>
        <fullName>Is_Insert__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <description>CRM-MC-ESPSFDCQI-9854</description>
        <label>Opportunity ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_record_ID__c</fullName>
        <description>CRM-MC-ESPSFDCQI-9854</description>
        <label>Related record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_PIC_ID__c</fullName>
        <description>CRM-MC-ESPSFDCQI-9854</description>
        <label>Survey PIC ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Update Survey Event</label>
    <pluralLabel>Update Surveys Event</pluralLabel>
</CustomObject>

src/classes/DAOH_CRM_APTS_Agreement.cls
public class DAOH_CRM_APTS_Agreement {
    
    public static void updateRfpReceivedDate(List<Apttus__APTS_Agreement__c> newList, Map < Id, Apttus__APTS_Agreement__c > oldMap) {
    }
    
    /**
     * This method is used to update Survey PIC on latest Client_Sat_Survey__c object
     * @params  List<Apttus__APTS_Agreement__c> newList
     * @params  Map<Id, Apttus__APTS_Agreement__c> oldMap
     * @return  void
     */
    public static void updateSurveyPIC(List<Apttus__APTS_Agreement__c> newList, Map<Id, Apttus__APTS_Agreement__c> oldMap){
        Set<Id> agrIdSet = new Set<Id>();
        List<Apttus__APTS_Agreement__c> agrExtList = new List<Apttus__APTS_Agreement__c>();
        Set<ID> oppIdSet = new Set<ID>();
        List<Update_Survey_Event__e> updateSurveyEventList_e = new List<Update_Survey_Event__e>();
        Update_Survey_Event__e updateSurveyEvent = null;
        
        for(Apttus__APTS_Agreement__c agr : newList) {
            if( ((agr.RecordTypeId == CON_CLM.PSA_RECORDTYPEID && (agr.Apttus__Subtype__c == 'Work Order' || agr.Apttus__Subtype__c =='Change Order' )) || ( agr.RecordTypeId == CON_CLM.RWLP_RECORDTYPEID && (agr.Apttus__Subtype__c =='Change Order' || agr.Apttus__Subtype__c == 'ATP' || agr.Apttus__Subtype__c == 'SUWO' || agr.Apttus__Subtype__c == 'Amendment')) ) && (Trigger.isInsert || (Trigger.isUpdate && agr.IQVIA_Project_Manager_Con__c != oldMap.get(agr.id).IQVIA_Project_Manager_Con__c)) && agr.IQVIA_Project_Manager_Con__c != null){//PSA
                agrIdSet.add(agr.Id);
            }
        }
        if(agrIdSet.size() > 0) {
            //Map<Id, Apttus__APTS_Agreement__c> agridToAgrMap = new SLT_APTS_Agreement(false, false).getAgreementsById(agrIdSet, new Set<String>{'Id', 'Apttus__Related_Opportunity__c', 'IQVIA_Project_Manager_Con__c'});
            for(Apttus__APTS_Agreement__c agr : newList) {
                if(!oppIdSet.contains(agr.Apttus__Related_Opportunity__c) && agrIdSet.contains(agr.Id)) {
                    oppIdSet.add(agr.Apttus__Related_Opportunity__c);
                    updateSurveyEvent = new Update_Survey_Event__e(Related_record_ID__c = agr.Id, Survey_PIC_ID__c = agr.IQVIA_Project_Manager_Con__c, Opportunity_ID__c = agr.Apttus__Related_Opportunity__c, Is_Insert__c = Trigger.isInsert);
                    updateSurveyEventList_e.add(updateSurveyEvent);
                }
            }
            if(updateSurveyEventList_e.size() > 0){
                EventBus.publish(updateSurveyEventList_e); 
            }
        }
    }
}