src/objects/Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.object
<CustomObject>
    <description>Docusign envelope recipient status</description>
    <fields>
        <fullName>Apttus_DocuApi__DocuSignEnvelopeId__c</fullName>
        <description>DocuSign Envelope Id master record id (SFDC ID)</description>
        <inlineHelpText>DocuSign Envelope Id master record id (SFDC ID)</inlineHelpText>
        <label>DocuSign Envelope Id</label>
        <referenceTo>Apttus_DocuApi__DocuSignEnvelope__c</referenceTo>
        <relationshipLabel>DocuSign Envelope Recipient Status</relationshipLabel>
        <relationshipName>DocuSignEnvelopeRecipientStatus</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_DocuApi__RecipientName__c</fullName>
        <description>Name of the Recipient from DocuSign (sent as part of the Envelope)</description>
        <inlineHelpText>Name of the Recipient from DocuSign (sent as part of the Envelope)</inlineHelpText>
        <label>Recipient Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_DocuApi__SignedDateTime__c</fullName>
        <description>Recipients Signed Date Time</description>
        <inlineHelpText>Recipients Signed Date Time</inlineHelpText>
        <label>Signed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Apttus_DocuApi__Status__c</fullName>
        <description>Envelope Recipient Status</description>
        <inlineHelpText>Envelope Recipient Status</inlineHelpText>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Envelope Recipient Status</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>DocuSignEnvelopeRecipientStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Envelope Recipient Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SLT_APTS_DocuApi_DS_EnvRecipientStatus.cls
/*
 * Version       : 1.0
 * Description   : This Apex class is selector layer for SLT_Apttus_DocuApi_DocuSignEnvelopeRecipientStatus
 */
public class SLT_APTS_DocuApi_DS_EnvRecipientStatus extends fflib_SObjectSelector{

    public SLT_APTS_DocuApi_DS_EnvRecipientStatus()
    {
    }
	
    public SLT_APTS_DocuApi_DS_EnvRecipientStatus(Boolean enforceCRUD,Boolean enforceFLS) {
        super(true, enforceCRUD, enforceFLS);
    }
	
    /**
    * This method used to get field list of sobject
    */
    public List<Schema.SObjectField> getSObjectFieldList(){

        return new List<Schema.SObjectField> {
            Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.Id,
            Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.Apttus_DocuApi__SignedDateTime__c,
            Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.Apttus_DocuApi__Status__c,
            Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.Apttus_DocuApi__DocuSignEnvelopeId__c,
            Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.Apttus_DocuApi__RecipientName__c
        };
    }
	
    /**
    * This method used to set up type of sobject
    * @return  Schema.SObjectType
    */
    public Schema.SObjectType getSObjectType(){
        return Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c.sObjectType;
    }
	
    /**
    *  This method is use to query Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c
	* @param Set idSet
	* @param Set fieldSet
	* @return List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>
    */
    public List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c> getDocuSignEnvelopeByIdAndStatus(Set<Id> idSet, Set<String> fieldSet){
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.selectFields(fieldSet);
        queryFactory.setCondition('Id in: idSet');
        queryFactory.setOrdering(new fflib_QueryFactory.Ordering('Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c', 'CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING));
        
        return (List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>) Database.query(queryFactory.toSOQL());
    }
    
    /**
    *  This method is use to query Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c based on EnvelopeId
	* @param Id EnvelopeId
	* @param Set fieldSet
	* @return List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>
    */
    public List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c> getDSEnvelopeRecipientStatusByEnvelopeId(Id EnvelopeId, Set<String> fieldSet){
        fflib_QueryFactory queryFactory = newQueryFactory();
        queryFactory.selectFields(fieldSet);
        queryFactory.setCondition('Apttus_DocuApi__DocuSignEnvelopeId__c = :EnvelopeId');
        queryFactory.setOrdering(new fflib_QueryFactory.Ordering('Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c', 'CreatedDate', fflib_QueryFactory.SortOrder.ASCENDING));
        
        return (List<Apttus_DocuApi__DocuSignEnvelopeRecipientStatus__c>) Database.query(queryFactory.toSOQL());
    }
}