src/objects/Archive_Search_Strategy__c.object
<CustomObject>
    <description>It is user to store search strategy records of a &apos;LR project overview&apos; record where Lr Project overview record status=completed or cancelled.</description>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>IQVIAPSA-5449</description>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LR_Project_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LR Project Overview</label>
        <referenceTo>LR_Project_Overview__c</referenceTo>
        <relationshipLabel>Search Strategies</relationshipLabel>
        <relationshipName>Archive_Search_Strategies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Archive Search Strategy</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archive Search Strategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LR_Project_Overview__c.object
<CustomObject>
    <description>This section is used to track literature project status, project details, product concerned, team locations, deliverable type, deliverable timelines, literature metrics, and key performance indicators (KPI) to measure the overall performance of the literature project.</description>
    <label>LR Project Overview</label>
    <nameField>
        <label>ID</label>
        <startingNumber>163644</startingNumber>
        <fullName>Name</fullName>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LR Project Overviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Search_Strategy__c.object
<CustomObject>
    <description>A literature search strategy is used in literature review for each substance group and constitutes of multiple keywords and components combined into a search string to retrieve scientific publications related to the product. This section is used to capture the versions of the search strategy document approved by the client, date approved, and when it is due for annual revision.</description>
    <fields>
        <fullName>LR_Project_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LR Project Overview</label>
        <referenceTo>LR_Project_Overview__c</referenceTo>
        <relationshipLabel>Search Strategies</relationshipLabel>
        <relationshipName>Search_Strategies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Strategy</label>
    <nameField>
        <label>Search Strategy Name</label>
        <startingNumber>21750</startingNumber>
        <fullName>Name</fullName>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Search Strategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SLT_PSA_ArchiveSearchStrategy.cls
public with sharing class SLT_PSA_ArchiveSearchStrategy extends fflib_SObjectSelector {
    
    //constructor to initialize CRUD and FLS
    public SLT_PSA_ArchiveSearchStrategy() {
        super(false, true, true);
    }
    
    //constructor to initialise CRUD and FLS with a parameter for FLS.
    public SLT_PSA_ArchiveSearchStrategy(Boolean enforceFLS, Boolean enforceCRUD) {
        super(false, enforceCRUD, enforceFLS);
    }
    
    /**
    * This method used to get field list of sobject
    * @return  List<Schema.SObjectField>
    */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{Archive_Search_Strategy__c.Id, Archive_Search_Strategy__c.Name};
    }
    
    /**
    * This method used to set up type of sobject
    * @return  Schema.SObjectType
    */
    public Schema.SObjectType getSObjectType() {
        return Archive_Search_Strategy__c.sObjectType;
    }
    
    /**
    * This method used to query Search_Strategy__c
    * @return  List<Search_Strategy__c>
    */
    public List<Archive_Search_Strategy__c> getArchiveSearchStrategies(Set<String> fieldSet){
        return (List<Archive_Search_Strategy__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).toSOQL());
    }
    
    /*
    * This method used to query Search_Strategy__c By lRProjectOverViewIds
    * @return  Search_Strategy__c 
    */
    public List<Archive_Search_Strategy__c> getArchiveSSRecordsFromLRIdForListView(String recordId, Set<String> fieldSet){
        return (List<Archive_Search_Strategy__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).setCondition('LR_Project_Overview__c =: recordId AND Inactive__c = false').setLimit(5).toSOQL());
    }
    
    public Integer getTotalNumberOfRecords(Set<id> archiveSsIdSet){
        Integer NumberOfRecords = 0;
        NumberOfRecords = [SELECT COUNT() FROM Archive_Search_Strategy__c WHERE Id =: archiveSsIdSet];
        return NumberOfRecords;
    }
    
    public List<Archive_Search_Strategy__c> getArchiveSSByIdsForPagination(Set<id> archiveSsFieldSet, Set<String> fieldSet, Integer pageSize, Integer offset){
        return (List<Archive_Search_Strategy__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).setCondition('Id IN : archiveSsFieldSet').setLimit(pageSize).setOFFSET(offset).toSOQL());
    }
    
    public List<Archive_Search_Strategy__c> getArchiveSSByLRIDS(Set<id> lrIds, Set<String> fieldSet, String whereClause, String orderByField){
        return (List<Archive_Search_Strategy__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).setCondition(whereClause).addOrdering(orderByField, fflib_QueryFactory.SortOrder.DESCENDING).toSOQL());
    }
    
    public List<Archive_Search_Strategy__c> getArchiveSSByLRID(Set<id> lrIds, Set<String> fieldSet){
        return (List<Archive_Search_Strategy__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).setCondition('LR_Project_Overview__c IN : lrIds AND Inactive__c =false').toSOQL());
    }
}