src/objects/Billing_Schedule__c.object
<CustomObject>
    <label>Billing Schedule</label>
    <nameField>
        <label>Billing Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Schedule_Item__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Schedule__c</fullName>
        <label>Billing Schedule</label>
        <referenceTo>Billing_Schedule__c</referenceTo>
        <relationshipLabel>Billing Schedule Items</relationshipLabel>
        <relationshipName>Billing_Schedule_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Schedule Item</label>
    <nameField>
        <label>Billing Schedule Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Billing_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Schedule</label>
        <referenceTo>Billing_Schedule__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/TST_SLT_BillingScheduleItem.cls
@isTest
public class TST_SLT_BillingScheduleItem {
    
    @testSetup
    public static void dataSetup() {
        Account acc = UTL_TestData.createAccount();
        insert acc;
        Opportunity opp = UTL_TestData.createOpportunity(acc.Id);
        insert opp;
        Product2 prod = UTL_TestData.createProduct();
        insert prod;
        PricebookEntry pe = UTL_TestData.createPricebookEntry(prod.Id);
        insert pe;
        OpportunityLineItem oli = UTL_TestData.createOpportunityLineItem(opp.Id, pe.Id);
        insert oli;
    }
    
    @isTest
    public static void getBillingScheduleItemOliId(){
        OpportunityLineItem oli = [SELECT Id FROM OpportunityLineItem LIMIT 1];
        
        Billing_Schedule__c bs = UTL_TestData.createBillingSchedule(oli.Id);
        insert bs;
        Billing_Schedule_Item__c bsi = UTL_TestData.createBillingScheduleItem(bs.Id);
        insert bsi;
        
        Test.startTest();
        List<Billing_Schedule_Item__c> bsiList = new SLT_BillingScheduleItem().getBillingScheduleItemOliId(new Set<Id>{oli.Id}, new Set<String>{'Id'});
        System.assertEquals(bsiList.size() > 0, true);
        Test.stopTest();
    }
    
}