src/objects/BNF2__c.object
<CustomObject>
    <description>Billing Notification Form</description>
    <fields>
        <fullName>Therapy_Area__c</fullName>
        <label>Therapy Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allergy [25]</fullName>
                </value>
                <value>
                    <fullName>Antibiotics, Antifungals [1]</fullName>
                </value>
                <value>
                    <fullName>Autoimmune biologics [18]</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular [2]</fullName>
                </value>
                <value>
                    <fullName>Central Nervous System [3]</fullName>
                </value>
                <value>
                    <fullName>Dermatology [4]</fullName>
                </value>
                <value>
                    <fullName>Diabetes [5]</fullName>
                </value>
                <value>
                    <fullName>Erytropoetine (EPO) [19]</fullName>
                </value>
                <value>
                    <fullName>Female Health [6]</fullName>
                </value>
                <value>
                    <fullName>Gastroenterology [7]</fullName>
                </value>
                <value>
                    <fullName>Growth Hormone [20]</fullName>
                </value>
                <value>
                    <fullName>Haemophilia [35]</fullName>
                </value>
                <value>
                    <fullName>Hepatitis C [21]</fullName>
                </value>
                <value>
                    <fullName>HIV, Anti-virals [8]</fullName>
                </value>
                <value>
                    <fullName>Immunomodulators [22]</fullName>
                </value>
                <value>
                    <fullName>Kidney Disease [26]</fullName>
                </value>
                <value>
                    <fullName>Mental Health [27]</fullName>
                </value>
                <value>
                    <fullName>Metabolics [9]</fullName>
                </value>
                <value>
                    <fullName>Multiple [24]</fullName>
                </value>
                <value>
                    <fullName>Multiple Sclerosis [23]</fullName>
                </value>
                <value>
                    <fullName>None [0]</fullName>
                </value>
                <value>
                    <fullName>Oncology [10]</fullName>
                </value>
                <value>
                    <fullName>Ophthalmology [17]</fullName>
                </value>
                <value>
                    <fullName>Pain [11]</fullName>
                </value>
                <value>
                    <fullName>Rare Disease [28]</fullName>
                </value>
                <value>
                    <fullName>Respiratory [12]</fullName>
                </value>
                <value>
                    <fullName>Rheumatoid Arthritis [13]</fullName>
                </value>
                <value>
                    <fullName>Transplantation [14]</fullName>
                </value>
                <value>
                    <fullName>Urology [15]</fullName>
                </value>
                <value>
                    <fullName>Vaccines [16]</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase/BNF</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Purchase/BNF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase/BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Revenue__c.object
<CustomObject>
    <description>Stores the data for Sales Team dashboard</description>
    <fields>
        <fullName>Gross_FY_Value__c</fullName>
        <formula>Gross_Q1_Value__c + Gross_Q2_Value__c + Gross_Q3_Value__c + Gross_Q4_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross FY Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <label>Opportunity Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Team_Hierarchy_AE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Hierarchy - AE</label>
        <referenceTo>Sales_Team_Hierarchy_AE__c</referenceTo>
        <relationshipLabel>Sales Revenue</relationshipLabel>
        <relationshipName>Sales_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <description>Tells whether the Sales Data is of type Budget, Pipeline or Revenue</description>
        <label>Scenario</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                </value>
                <value>
                    <fullName>Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Revenue</label>
    <nameField>
        <displayFormat>SD# {00000000}</displayFormat>
        <label>Sales Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Revenue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Team_Hierarchy_AE__c.object
<CustomObject>
    <label>Sales Team Hierarchy - AE</label>
    <nameField>
        <label>Sales Team Hierarchy - AE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Team Hierarchy - AE&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TST_SalesTeam_DashboardFilterClass.cls
@isTest
public class TST_SalesTeam_DashboardFilterClass {
    private static DashboardDisplayController controller; 
    private static SalesteamDashboard_DataSetUp testDataCon;
    
    static void setUpController() {
        controller = new DashboardDisplayController();
    }
    static void setUpTestDataForFilter()
    {
        testDataCon = new SalesteamDashboard_DataSetUp();
        testDataCon.setUpRegions();
        testDataCon.setUpUsers();
        testDataCon.setUpAccounts();
        testDataCon.setUpUserHierarchies(); 
        testDataCon.setUpSalesRevenueForFilterTesting();
    }
    static testmethod void test1() {
        
        setUpController();
        setUpTestDataForFilter();
        
        SalesTeam_DashboardFilterClass filters = new SalesTeam_DashboardFilterClass();
        filters.selectedSTHids.add(testDataCon.accExecSTH1.id);
        filters.QueryLevel = 'AE';
        filters.HierarchyLevel = SalesTeam_DashboardFilterClass.SALESTEAM;
        controller.setFilterCriteria(filters);//sales revenue data exists for this sales Team Hierarchy ID
        SalesTeam_DashboardFilterClass filterReturnVal = controller.getFilterCriteria();
        System.assertEquals(filters,filterReturnVal);
        test.startTest();
        for(SelectOption pc : DashboardDisplayController.GraphOptions)
        {
            System.assertEquals(true, pc.getValue().contains('Stage') || pc.getValue().contains('Forecast Category'));
        }
        controller.filterCriteria.selGraphOptn = 'Forecast Category';
        filters.OfferingGroup.add(SalesteamDashboard_DataSetUp.OG_Pharma);
        filters.OfferingSegment.add(SalesteamDashboard_DataSetUp.OS_National);
        filters.OfferingType.add(SalesteamDashboard_DataSetUp.OT_Core);
        filters.COEName.add(SalesteamDashboard_DataSetUp.CN_BrandCS);
        filters.ParentAccount.add(SalesteamDashboard_DataSetUp.OG_Pharma);
        filters.ServiceLine.add(SalesteamDashboard_DataSetUp.OS_National);
        filters.ServiceLineGroup.add(SalesteamDashboard_DataSetUp.OT_Core);
        filters.GlobalProduct.add(SalesteamDashboard_DataSetUp.CN_BrandCS);
        controller.RefreshDashboard();
        test.stopTest();
    }
    static testMethod void test2()  {
        setUpController();
        setUpTestDataForFilter();
        SalesTeam_DashboardFilterClass filters = new SalesTeam_DashboardFilterClass();
        filters.selectedSTHids.add(testDataCon.accExecSTH1.id);
        filters.QueryLevel = 'AE';
        filters.HierarchyLevel = SalesTeam_DashboardFilterClass.SALESTEAM;
        filters.selGraphOptn = 'Stage';
        controller.setFilterCriteria(filters);
        test.startTest();
        AggregateResult[] lstAggSalesRevBUD = [Select Sum(Gross_FY_Value__c) sumFY from Sales_Revenue__c where Sales_Team_Hierarchy_AE__c = :testDataCon.accExecSTH1.id and Scenario__c = :SalesTeam_DashboardFilterClass.BUDGET];
        AggregateResult[] lstAggSalesRevREV = [Select Sum(Gross_FY_Value__c) sumFY from Sales_Revenue__c where Sales_Team_Hierarchy_AE__c = :testDataCon.accExecSTH1.id and Scenario__c = :SalesTeam_DashboardFilterClass.REVENUE];
        AggregateResult[] lstAggSalesRevPIPE = [Select Sum(Gross_FY_Value__c) sumFY from Sales_Revenue__c s where s.Sales_Team_Hierarchy_AE__c = :testDataCon.accExecSTH1.id and s.Scenario__c = :SalesTeam_DashboardFilterClass.PIPELINE  and (s.Opportunity_Stage__c = '1' or s.Opportunity_Stage__c ='2' or s.Opportunity_Stage__c ='3' or s.Opportunity_Stage__c ='4' or s.Opportunity_Stage__c ='5')];
        AggregateResult[] lstAggSalesRevPIPE6a = [Select Sum(Gross_FY_Value__c) sumFY from Sales_Revenue__c s where s.Sales_Team_Hierarchy_AE__c = :testDataCon.accExecSTH1.id and s.Scenario__c = :SalesTeam_DashboardFilterClass.PIPELINE and s.Opportunity_Stage__c = '6'];
        AggregateResult[] lstAggSalesRevPIPE5 = [Select Sum(Gross_FY_Value__c) sumFY from Sales_Revenue__c s where s.Sales_Team_Hierarchy_AE__c = :testDataCon.accExecSTH1.id and s.Scenario__c = :SalesTeam_DashboardFilterClass.PIPELINE  and s.Opportunity_Stage__c ='5'];
        decimal expValue =((decimal)lstAggSalesRevBUD[0].get('sumFY') - (decimal)lstAggSalesRevREV[0].get('sumFY'));
        String expValS = ''+(expValue.setScale(0, System.RoundingMode.UP)).format();
        decimal expValue1 =((decimal)lstAggSalesRevBUD[0].get('sumFY') - (decimal)lstAggSalesRevREV[0].get('sumFY') - (decimal)lstAggSalesRevPIPE5[0].get('sumFY') - (decimal)lstAggSalesRevPIPE6a[0].get('sumFY'));
        String expValS1 = ''+(expValue1.setScale(0, System.RoundingMode.UP)).format();
        filters.isJapaneseUser = true;
        controller.setFilterCriteria(filters);
        filters.calcAdjTarget();
        Schema.DescribeFieldResult dfr = BNF2__c.Therapy_Area__c.getDescribe();
        SalesTeam_DashboardFilterClass.populateOptions(dfr);
        SalesTeam_DashboardFilterClass std = new SalesTeam_DashboardFilterClass();
        std.QueryLevel = 'PC';
        std.selectedVP = 'TEST';
        std.queryStr('SimpleExcelLst','Pipeline15');
        std.QueryLevel = 'TM';
        std.queryStr('test','Pipeline6a');
        std.selectedSTHids = new List<String>{'null'};
        std.calcAdjTarget();
        test.stopTest();
    }
}