src/objects/BNF2__c.object
<CustomObject>
    <description>Billing Notification Form</description>
    <fields>
        <fullName>Bill_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Address__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>MDM Validated</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Purchase/BNF&apos;s (Bill To)</relationshipLabel>
        <relationshipName>Purchase_BNF_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Purchase_BNF_s1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase/BNF</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Purchase/BNF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase/BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Proxy_SCM_Agreement__c.object
<CustomObject>
    <description>CRM-QI-ESPSFDCQI-1273 Custom object used to store status of SCM agreement in legacy IMS org to validate in IQVIA org and prevent changes to opportunity based on SCM agreement status</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-QI-ESPSFDCQI-1273 Link to Opportunity to which agreement is related</description>
        <inlineHelpText>Link to Opportunity to which agreement is related</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proxy SCM Agreements</relationshipLabel>
        <relationshipName>Proxy_SCM_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>CRM-QI-ESPSFDCQI-1273 Record type name of SCM agreement record in legacy IMS org (synced to IQVIA via Mulesoft)</description>
        <inlineHelpText>Record type name of SCM agreement record in legacy IMS org (synced to IQVIA via Mulesoft)</inlineHelpText>
        <label>Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Proxy SCM Agreement</label>
    <nameField>
        <label>Proxy SCM Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proxy SCM Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SCM_BNFAddressUpdateHelper.cls
/**
   created by Naveena Bagria :ER 797 :29-04-2014
*/

public with sharing class SCM_BNFAddressUpdateHelper 
{   
    //Method that checks if Bill_To has been updated on BNF and then call the method 'UpdateAggr' which updates it on the aggrement
    public void onBeforeInsert(List<BNF2__c>BnfList)
    {
            UpdateBNF(BnfList);                 
    }
    
    //method 'UpdateBnf' to update Bill_To on Aggrement
    public void UpdateBNF(List<BNF2__c>BnfList)
    {
        
        Map<Id,BNF2__c> OppBnfsMap = new Map<Id,BNF2__c>();
        List<Proxy_SCM_Agreement__c>aggrmtsList = new List<Proxy_SCM_Agreement__c>();
        
        //Iterate through BNF's and get related Opportunities
        for(BNF2__c Bnf : BnfList)
        {       
            OppBnfsMap.put(Bnf.Opportunity__c , Bnf);
        } 
        //System.debug('Opps-------->'+OppBnfsMap.keySet());
        /*if(!OppBnfsMap.isEmpty())
        //Updated By Rakesh : 27 Feb 2015 : ER-1584 : Modify RecordType checks
        //aggrmtsList = [Select a.Bill_To__c,a.Opportunity__c From Proxy_SCM_Agreement__c a where a.Opportunity__c IN :OppBnfsMap.keySet() AND ( a.Record_Type_Name__c = 'SOW' OR a.Record_Type_Name__c = 'Academia')];
        
        
        //Iterate through related agreemnts and update Bill_To
        if(aggrmtsList!=null && !aggrmtsList.isEmpty())
        {
            for( Proxy_SCM_Agreement__c aggr : aggrmtsList)
            {
                if(oppBnfsMap.containsKey(aggr.Opportunity__c) && oppBnfsMap.containsKey(aggr.Opportunity__c)!=null)
                {       
                    //oppBnfsMap.get(aggr.Opportunity__c).Bill_To__c = aggr.Bill_To__c ;      
                }
            }   
            
            //Update the related Agreements 
           
            ConstantClass.stopRecrsvTriggerAgreement = true;    
        } */
    }
    
}