src/objects/BNF2__c.object
<CustomObject>
    <description>Billing Notification Form</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Purchase_BNF_s1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase/BNF</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Purchase/BNF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase/BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BNF_Count__c</fullName>
        <description>ESPSFDCQI-14231: Numbers of BNF records (iBNF/eBNF/MiBNF Component) on the opportunity</description>
        <formula>Opportunity_Extension__r.BNF_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BNF Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-14509</description>
        <label>Opportunity Extension</label>
        <referenceTo>Opportunity_Extension__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity_Extension__c.object
<CustomObject>
    <description>ESPSFDCQI-14509</description>
    <fields>
        <fullName>BNF_Count__c</fullName>
        <description>ESPSFDCQI-14231</description>
        <label>BNF Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>ESPSFDCQI-14509</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Extensions</relationshipLabel>
        <relationshipName>Opportunity_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Extension</label>
    <nameField>
        <displayFormat>OE-{000000}</displayFormat>
        <label>Opportunity Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DAOH_BNF2.cls
public class DAOH_BNF2 {
    
    /**
     * method to update Related Opportunity Fields
     * @param List<BNF2__c> newList
     * @param Map<Id, BNF2__c> oldMap
     */
    public static void updateOpportunityFields(List<BNF2__c> newList, Map<Id, BNF2__c> oldMap){
        Boolean toCommit = false;
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork( new Schema.SObjectType[] { Opportunity_Extension__c.SobjectType } );
        
        if(Trigger.isInsert || Trigger.isDelete){
            Set<Id> oppIdSet = new Set<Id>();
            Map<Id, Opportunity_Extension__c> OppIdToOppExtMap = new Map<Id, Opportunity_Extension__c>();
            Map<Opportunity_Extension__c, Decimal> oppExtToBnfCount = new Map<Opportunity_Extension__c, Decimal>();
            
            for(BNF2__c bnf: newList){
                oppIdSet.add(bnf.Opportunity__c);
            }
            
            for(Opportunity_Extension__c OE : new SLT_Opportunity_Extension().getOpportunityExtensionByOppId(oppIdSet)){
                OppIdToOppExtMap.put(OE.Opportunity__c, OE);
            }
            
            for(BNF2__c bnf: newList){
                Opportunity_Extension__c oppExt = OppIdToOppExtMap.containsKey(bnf.Opportunity__c) ? OppIdToOppExtMap.get(bnf.Opportunity__c) : null;
                Decimal bnfCount = (oppExt != null && oppExt.BNF_Count__c != null) ? oppExt.BNF_Count__c : 0;
                bnfCount = (Trigger.isInsert ? (bnfCount +1) : (bnfCount -1));
                oppExtToBnfCount.put(oppExt, bnfCount);
            }
            
            for(Opportunity_Extension__c oppExt: oppExtToBnfCount.keySet()){
                if(oppExt != null){
                    oppExt.BNF_Count__c = oppExtToBnfCount.containsKey(oppExt) ? oppExtToBnfCount.get(oppExt) : 0;
                    toCommit = true;
                    uow.registerDirty(oppExt);
                }
            }
        }
        if(toCommit){
            UTL_ExecutionControl.stopTriggerExecution = true;
            uow.commitWork();
            UTL_ExecutionControl.stopTriggerExecution = false;
        }
    }
}