src/objects/CDA_Legal_POC_Cross_Walk__c.object
<CustomObject>
    <description>This will be used to assign the appropriate attorney as per the selected language.</description>
    <fields>
        <fullName>CDA_Language__c</fullName>
        <label>CDA Language</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Spanish (LatAm)</fullName>
                    <isActive>false</isActive>
                    <label>Spanish (LatAm)</label>
                </value>
                <value>
                    <fullName>Spanish (Spain)</fullName>
                    <isActive>false</isActive>
                    <label>Spanish (Spain)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_POC_Email_Address__c</fullName>
        <label>Legal POC Email Address</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Legal_POC_First_Name__c</fullName>
        <label>Legal POC First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_POC_Last_Name__c</fullName>
        <label>Legal POC Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CDA Legal POC Cross Walk</label>
    <nameField>
        <label>CDA Legal POC Cross Walk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDA Legal POC Cross Walks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CDA_Request__c.object
<CustomObject>
    <description>created under ER-3556</description>
    <fields>
        <fullName>CDA_Format__c</fullName>
        <inlineHelpText>Used to determine format of CDA agremeent needed</inlineHelpText>
        <label>CDA Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PDF</fullName>
                </value>
                <value>
                    <fullName>Protected Word</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDA_Id__c</fullName>
        <description>A unique identification number assigned to each CDA Request.</description>
        <displayFormat>CDA-{000000}</displayFormat>
        <inlineHelpText>A unique identification number assigned to each CDA Request.</inlineHelpText>
        <label>CDA Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>CDA_Language__c</fullName>
        <description>Language dependent on he CDA type. updated &apos;IQVIA&apos; under CR-11488</description>
        <inlineHelpText>Templates using local language are available for these specific languages. If the language you require is not available, please submit your request by email to LegalReview-CDARequests@iqvia.com.</inlineHelpText>
        <label>CDA Language</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CDA_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Chinese (Bilingual)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDA_Type__c</fullName>
        <label>CDA Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>QuintilesIMS_Business__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>CEVA</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Auditor</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>China &amp; Southeast Asia</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Pacific Asia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Canada &amp; US</fullName>
                    <isActive>false</isActive>
                    <label>Canada &amp; US</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originating_Requestor_Flag__c</fullName>
        <description>Identifies if this request is being submitted by one person on behalf of a different IQVIA resource. Created by Vikram Singh under CR-11764.</description>
        <label>Originating Requestor Flag</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originating_Requestor_IQVIA_Email__c</fullName>
        <description>IQVIA email address of the Originating IQVIA Requestor. Created by Vikram Singh under CR-11764.</description>
        <inlineHelpText>Provide the IQVIA email address for the Originating Requestor for whom you are submitting this request.  He/She will receive copies of all email notifications related to this CDA Request.</inlineHelpText>
        <label>Originating Requestor IQVIA Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Point_of_Contact_Name__c</fullName>
        <description>Full Name of Recipient Point of Contact</description>
        <formula>Recipient_Point_of_Contact_First_Name__c +&apos; &apos;+  Recipient_Point_of_Contact_Last_Name__c</formula>
        <label>Recipient Point of Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>these are the statuses for CDA request.</description>
        <inlineHelpText>Current Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Draft</fullName>
                </value>
                <value>
                    <fullName>Acquiring Internal IQVIA Signature</fullName>
                </value>
                <value>
                    <fullName>Awaiting Requestor Submission</fullName>
                </value>
                <value>
                    <fullName>Awaiting GLD Competitor Approval</fullName>
                </value>
                <value>
                    <fullName>In Review by IQVIA</fullName>
                </value>
                <value>
                    <fullName>Language Review</fullName>
                </value>
                <value>
                    <fullName>Submitted for Processing</fullName>
                </value>
                <value>
                    <fullName>Awaiting OGC Competitor Approval</fullName>
                </value>
                <value>
                    <fullName>Validating Recipient Provided Document</fullName>
                </value>
                <value>
                    <fullName>Sent for Recipient Review</fullName>
                </value>
                <value>
                    <fullName>Sent for Recipient Signature</fullName>
                </value>
                <value>
                    <fullName>Returned to Requestor</fullName>
                </value>
                <value>
                    <fullName>Signature Request Denied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Contract Executed</fullName>
                </value>
                <value>
                    <fullName>Disclosure Period Ended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_documents_would_you_like_to_provide__c</fullName>
        <description>created by Vikram Singh under CR-11146</description>
        <label>What documents would you like to provide</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Word Redlined Only</fullName>
                </value>
                <value>
                    <fullName>Word Cleaned Version Only</fullName>
                </value>
                <value>
                    <fullName>Word Redlined and Clean versions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_is_the_Study_Sponsor_situation__c</fullName>
        <inlineHelpText>Is there a study sponsor? If so, is the competitor ready to reveal the sponsor?</inlineHelpText>
        <label>What is the Study Sponsor situation?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Competitor_Contracting_Capacity__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Study Sponsor</fullName>
                </value>
                <value>
                    <fullName>Study Sponsor identified</fullName>
                </value>
                <value>
                    <fullName>Study Sponsor – Recipient not ready to reveal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CDA Request</label>
    <nameField>
        <label>CDA Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_UTL_CDAUtility.cls
@isTest(seeAllData=false)
public class TST_UTL_CDAUtility {
    @testSetup
    public static void setupData() {
        TST_CDA_SetupData testSetup = new TST_CDA_SetupData();
        testSetup.setUpCustomSetting();
        testSetup.setUpContactForEmail();
        testSetup.setupUserRequestor();
        testSetup.setupUserNegotiator();

        //Added by Vikram Singh under CR-11576 Start
        CDA_Approved_Governing_Law_Location__c governingLaw = TST_CDA_SetupData.getGoverningLaw('Test GL');
        insert governingLaw;

        QI_Legal_Entity__c testQiLegalEntity = TST_CDA_SetupData.createQiLegalEntity('Test Entity1', UTL_CDAUtility.CDA_BUSINESS_PART_LQ, governingLaw); //Updated by Vikram Singh under CR-11576
        insert testQiLegalEntity;

        //create Legal POC Attorney record
        CDA_Legal_POC_Cross_Walk__c testLegalPOC = new CDA_Legal_POC_Cross_Walk__c(CDA_Language__c='Chinese',Legal_POC_First_Name__c='TestChinese',Legal_POC_Last_Name__c='Attorney',Legal_POC_Email_Address__c='test@abc.com');
        insert testLegalPOC;

        CDA_Account__c testCdaAccount = testSetup.cdaAccount;

        CDA_Request__c cdaRequest = testSetup.setupTestDataForCustomer(testQiLegalEntity);
        cdaRequest.Originating_Requestor_Flag__c = 'Yes';
        cdaRequest.Originating_Requestor_IQVIA_Email__c = 'orignating@req.com';
        cdaRequest.What_documents_would_you_like_to_provide__c = UTL_CDAUtility.CDA_RESPONSE_DOCTYPE_REDLINED;
        update cdaRequest;

        CDA_Request__c cdaRequest2 = testSetup.setupTestDataForAuditor(testQiLegalEntity);

        Attachment testAttachment1 = testSetup.getAttachment(UTL_CDAUtility.GENERATED_DOCUMENT_KEYWORD + '_Test Attachment' + UTL_CDAUtility.EXTENTION_DOC , cdaRequest2.Id);
        Attachment testAttachment2 = testSetup.getAttachment(UTL_CDAUtility.RED_LINE_KEYWORD , cdaRequest.Id);
        Attachment testAttachment3 = testSetup.getAttachment(UTL_CDAUtility.RED_LINE_KEYWORD + UTL_CDAUtility.COMPLETED_KEYWORD, cdaRequest.Id);
        Attachment testAttachment4 = testSetup.getAttachment(UTL_CDAUtility.RED_LINE_KEYWORD + UTL_CDAUtility.CLEANED_DOC_KEYWORD, cdaRequest.Id);
    }

    @isTest
    public static void runCdaUtilityTest() {
        map<String, CDA_Governing_Law_Name_and_PrintName__mdt> tstGoverningLawNameAndPrintNameMap = UTL_CDAUtility.governingLawNameAndPrintNameMap;
        Set<String> tstSetOfUserIdsHavingApttusLicense = UTL_CDAUtility.setOfUserIdsHavingApttusLicense;
        CDA_Request__c cdaRequest = new CDA_Request__c();
        String query = 'SELECT id, Name, CDA_Id__c, CDA_Type__c, CDA_Format__c, Status__c, What_is_the_Study_Sponsor_situation__c, Recipient_Point_of_Contact_Name__c, Negotiator_Assigned_List__c, CDA_Language__c, OwnerId, RecordTypeId, Requestor_Admin_Email_Flag__c, Originating_Requestor_Flag__c, Originating_Requestor_IQVIA_Email__c, Recipient_Account_Name_Formula__c FROM CDA_Request__c';
        List<CDA_Request__c> cdaRequestList = Database.query(query);
        
        if(cdaRequestList.size() > 0) {
            cdaRequest = cdaRequestList[0];
        }
        
        cdaRequest.Additional_Contact_Flag__c = 'Yes';
        cdaRequest.Additional_Contact_Details__c = 'TEST,TEST1,Test2';
        update cdaRequest;

        UTL_CDAUtility.logRef();
        UTL_CDAUtility.setLogObject(cdaRequest.Id, 'logDetail', 'otherDetail');
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setTemplateId(UTL_CDAUtility.getTemplateId('templateName', 'language'));
        email.setCcAddresses(new List<String>{'test@test.com'});
        email.setToAddresses(new List<String>{'test@test.com'});
        Contact con = new Contact(FirstName = 'Test', LastName = 'Con', email = 'test@test.com');
        insert con;
        email.setTargetObjectId(con.Id);
        email.setWhatId(cdaRequest.Id);
        UTL_CDAUtility.sendNotificationEmail(new List <Messaging.SingleEmailMessage>{email});
        UTL_CDAUtility.sendEmailThroughWorkflow(email);
        UTL_CDAUtility.getDocumentName(cdaRequest, UTL_CDAUtility.CDASOURCE_QUINTILESIMS);
        UTL_CDAUtility.getRelationObjectFieldStr('QI_Legal_Entity__c', 'QI_Legal_Entity_Name__c');
        UTL_CDAUtility.getObjectFieldStr('CDA_Request__c');
        UTL_CDAUtility.getUserDetails();
        UTL_CDAUtility.getAdditionalContactsDetails(cdaRequest.Id);
        UTL_CDAUtility.login('user', 'password');
        Boolean isSandbox = UTL_CDAUtility.isSandboxOrg;
    } 
}