src/objects/CDA_Account__c.object
<CustomObject>
    <description>Separate table of Accounts for CDA project.</description>
    <fields>
        <fullName>Account_Source__c</fullName>
        <label>Account Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>IMS Org</fullName>
                </value>
                <value>
                    <fullName>CDA Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CDA Account</label>
    <nameField>
        <label>CDA Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDA Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CDA_Request__c.object
<CustomObject>
    <description>created under ER-3556</description>
    <fields>
        <fullName>CDA_Effective_Date__c</fullName>
        <description>updated &apos;IQVIA&apos; under CR-11488</description>
        <inlineHelpText>A date within a time frame that is 60 days prior to the current date and 90 days after the current date. if initial disclosure was more than 60 days prior to current date, Please contact the CDA Negotiator team at LegalReview-CDARequests@iqvia.com</inlineHelpText>
        <label>CDA Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CDA_Type__c</fullName>
        <label>CDA Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>QuintilesIMS_Business__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>CEVA</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Auditor</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>China &amp; Southeast Asia</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Pacific Asia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Canada &amp; US</fullName>
                    <isActive>false</isActive>
                    <label>Canada &amp; US</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cust_Legal_Entity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of the customer requesting the audit.</inlineHelpText>
        <label>Customer Legal Entity Name</label>
        <referenceTo>CDA_Account__c</referenceTo>
        <relationshipLabel>CDA Requests</relationshipLabel>
        <relationshipName>CDA_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_executed_signed_contract_received__c</fullName>
        <description>The date the agreement status was changed to Contract Executed.</description>
        <label>Date executed (signed) contract received</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>QuintilesIMS_Affiliates_Value__c</fullName>
        <description>updated &apos;IQVIA&apos; under CR-11488</description>
        <inlineHelpText>Identifies if the CDA covers all IQVIA Affiliates.</inlineHelpText>
        <label>IQVIA Affiliates</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QuintilesIMS_Business__c</fullName>
        <inlineHelpText>Select the applicable business area which will be making the disclosures of Confidential Information. &quot;TAS&quot; was formally known as &quot;IQVIA Commercial&quot;. CSMS was formally known as &quot;IQVIA IES&quot;. As new business areas are added the selection list is expanded.</inlineHelpText>
        <label>IQVIA Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contract Sales &amp; Medical Solutions (CSMS) (Legacy IES)</fullName>
                </value>
                <value>
                    <fullName>Q Squared</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Development Solutions (RDS) (Legacy Quintiles)</fullName>
                </value>
                <value>
                    <fullName>Technology &amp; Analytics Solutions (TAS) (Legacy IMS)</fullName>
                </value>
                <value>
                    <fullName>Real World Solutions</fullName>
                </value>
                <value>
                    <fullName>Strategic Sites (Master CDA used with strategic sites about potential trials IF the sponsor has accepted their usage)</fullName>
                </value>
                <value>
                    <fullName>Public Health</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
                <value>
                    <fullName>Clinical Research (Legacy Quintiles)</fullName>
                    <isActive>false</isActive>
                    <label>Clinical Research (Legacy Quintiles)</label>
                </value>
                <value>
                    <fullName>Combined Offerings (Both)</fullName>
                    <isActive>false</isActive>
                    <label>Combined Offerings (Both)</label>
                </value>
                <value>
                    <fullName>Data and Services (Legacy IMS)</fullName>
                    <isActive>false</isActive>
                    <label>Data and Services (Legacy IMS)</label>
                </value>
                <value>
                    <fullName>Legacy IMS</fullName>
                    <isActive>false</isActive>
                    <label>Legacy IMS</label>
                </value>
                <value>
                    <fullName>Legacy Quintiles</fullName>
                    <isActive>false</isActive>
                    <label>Legacy Quintiles</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Recipient’s company name which will be the executing party to the CDA.</inlineHelpText>
        <label>Recipient Account Name</label>
        <referenceTo>CDA_Account__c</referenceTo>
        <relationshipLabel>CDA Requests (Recipient Account Name)</relationshipLabel>
        <relationshipName>CDA_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Carbon_Copies__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>You will be carbon copied on all emails to the Recipient unless you remove the checkmark from the box.</inlineHelpText>
        <label>Requestor Carbon Copies</label>
        <type>Checkbox</type>
    </fields>
    <label>CDA Request</label>
    <nameField>
        <label>CDA Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_CDA_New_CDA_Accounts_Report.cls
/**
 * @Author  : Babita Dadarwal
 * @Name    : TST_CDA_New_CDA_Accounts_Report
 * @Purpose : Test class for SCH_CDA_New_CDA_Account_Report Scheduler.
 */
@isTest(seeAllData = false)
private class TST_CDA_New_CDA_Accounts_Report {

    @testSetup
    public static void setupData() {
        TST_CDA_SetupData testSetup = new TST_CDA_SetupData();
        testSetup.setUpCustomSetting();

        CDA_Request__c cdaRecordAuditor =  new CDA_Request__c();
        cdaRecordAuditor.QuintilesIMS_Business__c = UTL_CDAUtility.CDA_BUSINESS_PART_LQ;
        cdaRecordAuditor.CDA_Type__c = UTL_CDAUtility.AUDITOR;
        cdaRecordAuditor.CDA_Effective_Date__c = Date.today();
        cdaRecordAuditor.QuintilesIMS_Affiliates_Value__c = 'Yes';
        cdaRecordAuditor.Requestor_Carbon_Copies__c = false;
        cdaRecordAuditor.Date_executed_signed_contract_received__c = System.now();
        insert cdaRecordAuditor;

        CDA_Account__c testCustomerAccount  = new CDA_Account__c();
        testCustomerAccount.Name = 'Test Account';
        testCustomerAccount.Account_Source__c = 'CDA Process';
        insert testCustomerAccount;

        CDA_Account__c testRecipientAccount  = new CDA_Account__c();
        testRecipientAccount.Name = 'Test Account';
        testRecipientAccount.Account_Source__c = 'CDA Process';
        insert testRecipientAccount;

        cdaRecordAuditor.Cust_Legal_Entity_Name__c = testCustomerAccount.Id;
        cdaRecordAuditor.Recipient_Account__c = testRecipientAccount.Id;
        Update cdaRecordAuditor;
    }

    @isTest static void test_Scheduler_Execute() {
        Test.startTest();

        String CRON_EXP = '0 0 0 3 9 ? ' + (Date.Today().year() + 1);
        String jobId = System.schedule('testNewCdaAccountScheduler', CRON_EXP, new SCH_CDA_New_CDA_Account_Report());

        Test.stopTest();
    }
}