src/objects/CDA_Request__c.object
<CustomObject>
    <description>created under ER-3556</description>
    <fields>
        <fullName>CDA_Format__c</fullName>
        <inlineHelpText>Used to determine format of CDA agremeent needed</inlineHelpText>
        <label>CDA Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PDF</fullName>
                </value>
                <value>
                    <fullName>Protected Word</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CDA_Id__c</fullName>
        <description>A unique identification number assigned to each CDA Request.</description>
        <displayFormat>CDA-{000000}</displayFormat>
        <inlineHelpText>A unique identification number assigned to each CDA Request.</inlineHelpText>
        <label>CDA Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>CDA_Type__c</fullName>
        <label>CDA Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>QuintilesIMS_Business__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>CEVA</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Auditor</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>China &amp; Southeast Asia</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Pacific Asia</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Canada &amp; US</fullName>
                    <isActive>false</isActive>
                    <label>Canada &amp; US</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_Account_Name_Formula__c</fullName>
        <description>This is used for email template. Updated Label by Vikram Singh under CR-11817.</description>
        <formula>IF( OR(ISNULL(Recipient_Account__c),ISBLANK(Recipient_Account__c) ), Recipient_Account_Name_Other__c , Recipient_Account__r.CDA_Account_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recipient Account Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>these are the statuses for CDA request.</description>
        <inlineHelpText>Current Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Draft</fullName>
                </value>
                <value>
                    <fullName>Acquiring Internal IQVIA Signature</fullName>
                </value>
                <value>
                    <fullName>Awaiting Requestor Submission</fullName>
                </value>
                <value>
                    <fullName>Awaiting GLD Competitor Approval</fullName>
                </value>
                <value>
                    <fullName>In Review by IQVIA</fullName>
                </value>
                <value>
                    <fullName>Language Review</fullName>
                </value>
                <value>
                    <fullName>Submitted for Processing</fullName>
                </value>
                <value>
                    <fullName>Awaiting OGC Competitor Approval</fullName>
                </value>
                <value>
                    <fullName>Validating Recipient Provided Document</fullName>
                </value>
                <value>
                    <fullName>Sent for Recipient Review</fullName>
                </value>
                <value>
                    <fullName>Sent for Recipient Signature</fullName>
                </value>
                <value>
                    <fullName>Returned to Requestor</fullName>
                </value>
                <value>
                    <fullName>Signature Request Denied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Contract Executed</fullName>
                </value>
                <value>
                    <fullName>Disclosure Period Ended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CDA Request</label>
    <nameField>
        <label>CDA Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/dsfs__DocuSign_Status__c.object
<CustomObject>
    <description>DocuSign Status is the foundation Custom Object for integration of DocuSign and Salesforce.</description>
    <fields>
        <fullName>CDA_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CDA Request</label>
        <referenceTo>CDA_Request__c</referenceTo>
        <relationshipLabel>DocuSign Status</relationshipLabel>
        <relationshipName>DocuSign_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dsfs__DocuSign_Envelope_ID__c</fullName>
        <label>DocuSign Envelope ID</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Status</label>
    <nameField>
        <displayFormat>DSX-{0000000}</displayFormat>
        <label>Envelope#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TGRH_CDAAttachment.cls
public class TGRH_CDAAttachment {
    private static CDA_Request__c cdaRequest;
    public static Boolean isNegotiator {
        get {
            return (SRV_CDA_CDARequest.getUserPermission() == UTL_CDAUtility.NEGOTIATOR || SRV_CDA_CDARequest.getUserPermission() == UTL_CDAUtility.SYS_ADMIN);
        }
        set;
    }

    public static Boolean isEndStatus {
        get {
            if(cdaRequest != null) {
                return (cdaRequest.Status__c == UTL_CDAUtility.STATUS_CONTRACTEXECUTED || cdaRequest.Status__c == UTL_CDAUtility.STATUS_CANCELEDBYREQUESTOR || cdaRequest.Status__c == UTL_CDAUtility.STATUS_DISCLOSUREPERIODENDED);    //Updated by Vikram Singh under Item #254
            }
            return false;
        }
        set;
    }
    
    public static void handleOnBeforeInsertAttachment(List<Attachment> newList, Set<Id> parentIdSet) {
        Map<Id, dsfs__DocuSign_Status__c> dsStausMapWithId;
        if(parentIdSet != null && parentIdSet.size() > 0) {
            //dsStausMapWithId = new Map<Id, dsfs__DocuSign_Status__c>([SELECT id, CDA_Request__c, CDA_Request__r.CDA_Id__c, CDA_Request__r.id, CDA_Request__r.CDA_Type__c, CDA_Request__r.Recipient_Account_Name_Formula__c, CDA_Request__r.CDA_Format__c, dsfs__DocuSign_Envelope_ID__c FROM dsfs__DocuSign_Status__c WHERE Id In: parentIdSet and CDA_Request__c != null ORDER BY createddate desc]);
            String query = 'SELECT id, CDA_Request__c, CDA_Request__r.CDA_Id__c, CDA_Request__r.id, CDA_Request__r.CDA_Type__c, CDA_Request__r.Recipient_Account_Name_Formula__c, CDA_Request__r.CDA_Format__c, dsfs__DocuSign_Envelope_ID__c FROM dsfs__DocuSign_Status__c WHERE Id In: parentIdSet and CDA_Request__c != null ORDER BY createddate desc';
            dsStausMapWithId = new Map<Id, dsfs__DocuSign_Status__c>((List<dsfs__DocuSign_Status__c>)Database.query(query));
        }
        if(dsStausMapWithId != null && dsStausMapWithId.size() > 0) {
            for(Attachment attach: newList) {
                if(dsStausMapWithId.containsKey(attach.ParentId)) {
                    attach.Name = UTL_CDAUtility.getDocumentName(dsStausMapWithId.get(attach.ParentId).CDA_Request__r, UTL_CDAUtility.COMPLETED_KEYWORD);
                    SRV_CDA_DocusignStatus.splitSignedDocument(dsStausMapWithId.get(attach.ParentId).CDA_Request__r.id, dsStausMapWithId.get(attach.ParentId).dsfs__DocuSign_Envelope_ID__c);
                    attach.ParentId = dsStausMapWithId.get(attach.ParentId).CDA_Request__c;
                }
            }
        }
    }
    
    public static void handleOnBeforeDeleteAttachment(List<Attachment> attachmentList, Set<Id> parentIdSet) {
        List<CDA_Request__c> cdaRequestList = [SELECT id, Name, Status__c, Owner.Id, Owner.Name FROM CDA_Request__c WHERE Id IN :parentIdSet];
        if(cdaRequestList != null && cdaRequestList.size() > 0) {
            
            for(Attachment attach: attachmentList) {
                for(CDA_Request__c cdaReq : cdaRequestList) {
                    cdaRequest = cdaReq;
                    if(!UTL_CDAUtility.forceUpdateStatus && attach.ParentId == cdaReq.Id && (isEndStatus  || (!isNegotiator && attach.OwnerId != UserInfo.getUserId()))) {
                        attach.ParentId.addError('You are not authorized to delete this attachment.');
                    }
                }
            }
        }
    }
    
    public static void handleOnAfterUpdateAttachment(List<Attachment> newList, Set<Id> parentIdSet) {
        if(UTL_CDAUtility.isBatchProcessing){
            String fieldStr = UTL_CDAUtility.getObjectFieldStr('CDA_Request__c');
            List<CDA_Request__c> cdaRequestList = Database.query('SELECT ' + fieldStr + ' FROM CDA_Request__c WHERE id in: parentIdSet and Status__c = \'' + UTL_CDAUtility.STATUS_SUBMITTEDFORPROCESSING + '\'');
            if(cdaRequestList != null && cdaRequestList.size() > 0) {
                for (Attachment attach: newList) {
                    system.debug('####inside DAOH_Attachment.AfterUpdate attach: '+attach);
                    system.debug('####inside DAOH_Attachment.AfterUpdate CDARequest: '+cdaRequestList[0]);
                    if(attach.Name.contains(UTL_CDAUtility.GENERATED_DOCUMENT_KEYWORD) && attach.Name.contains(cdaRequestList[0].Name) && cdaRequestList[0].Status__c == UTL_CDAUtility.STATUS_SUBMITTEDFORPROCESSING) {
                        system.debug('####inside DAOH_Attachment.AfterUpdate Calling Docusign');
                        //Once CDA generated let's submit the request for further processing
                        QUE_CDA_AsyncSendCDADoc asyncSendDocQue = new QUE_CDA_AsyncSendCDADoc();
                        asyncSendDocQue.cdaRequest = cdaRequestList[0];
                        System.enqueueJob(asyncSendDocQue);
                    }
                }
            }
        }
    }
}