src/objects/Community_Topic__c.object
<CustomObject>
    <label>Community Topic</label>
    <nameField>
        <label>Community Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>ProductName__c</fullName>
        <description>CSM - ACN - S-0046 - Product Name</description>
        <label>ProductName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Knowledge</relationshipLabel>
        <relationshipName>Knowledge</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/objects/Knowledge_Account_RelationShip__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>Knowledge__r.ProductName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductName</label>
        <type>Text</type>
    </fields>
    <label>Knowledge Account RelationShip</label>
    <nameField>
        <displayFormat>KAR-{0000000}</displayFormat>
        <label>Knowledge Account RelationShip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Account RelationShips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Community_Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Topic</label>
        <referenceTo>Community_Topic__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CNT_CSM_KnowledgeBrowser.cls
/*
 * Version       : 1.0
 * Description   : Apex Controller for LXC_CSM_KnowledgeBrowser 
 */ 
public class CNT_CSM_KnowledgeBrowser {
    
    /*
    * Return a List of products Name with Community_Topic__c not null and and present in CaseCategorization Object 
    */
    @AuraEnabled
    public static List<AggregateResult> getProducts(){ 
        List<AggregateResult> products = new List<AggregateResult>();
        List<Product2> prds = new List<Product2>();
        prds = new SLT_Product2().getProductWithFilter(new Set<String>{'Name'},'Community_Topic__c != \'\' ');
        Set<String> prdNames = new Set<String>();
        for(Product2 prd: prds){
            prdNames.add(prd.Name);
        }
        products = new SLT_CaseCategorization().getProducts(prdNames);
        return products;
    }
    /*
    * Return List of Knowledge__kav by productName
    */
    @AuraEnabled
    public static List<Knowledge__kav> getArticlesByProductName(String productName){
        List<Knowledge__kav> articles =  new SLT_Knowledge().selectByProductName(productName);
        return articles;
    }

    @AuraEnabled
    public static List<Knowledge__kav> getArticlesByProductName2(String productName, String accountId){
        List<Knowledge__kav> articles = new List<Knowledge__kav>();
        Set<Id> knowledgeIds = new  Set<Id>(); 
        if (accountId!=''){
        for (Knowledge_Account_RelationShip__c ak:  Database.query('select Knowledge__c from Knowledge_Account_RelationShip__c where Knowledge__r.PublishStatus =\'Online\' and Knowledge__r.ProductName__c = \''+productName+'\' and Knowledge__r.IsMasterLanguage = true and Account__c=\''+ accountId + '\'')){
            knowledgeIds.add(ak.Knowledge__c);
        }
            articles =  new SLT_Knowledge().selectById(knowledgeIds);
        }else{
            articles =  new SLT_Knowledge().selectByProductName(productName);
        }
        return articles;
    }

    @AuraEnabled
    public static Map<Id, Account> getAccountsArticlesByProductName(String productName){
        Map<Id, Account> accounts = new Map<Id, Account>();
        Set<Id>  accountIds = new  Set<Id>(); 
        for (Knowledge_Account_RelationShip__c ak:  Database.query('select Account__c from Knowledge_Account_RelationShip__c where Knowledge__r.PublishStatus =\'Online\' and Knowledge__r.IsMasterLanguage = true and Knowledge__r.ProductName__c = \''+productName+'\'')){
            accountIds.add(ak.Account__c);
        }
        accounts = new SLT_Account().selectByAccountId(accountIds, new Set<String>{'id', 'Name'});
        return accounts;
    }
}