src/objects/Community_Topic__c.object
<CustomObject>
    <label>Community Topic</label>
    <nameField>
        <label>Community Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CSM_QI_Case_Categorization__c.object
<CustomObject>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Categorization</relationshipLabel>
        <relationshipName>Case_Categorization</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <label>Sub-Type 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <label>Sub-Type 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Categorization</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Case Categorization ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Categorization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <description>CSM - ACN - S-0046 - Product Name</description>
        <label>ProductName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Knowledge</relationshipLabel>
        <relationshipName>Knowledge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <description>CSM - ACN - S-0046 - Sub-Type 1</description>
        <label>Sub-Type 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <description>CSM - ACN - S-0046 - Sub-Type 2</description>
        <label>Sub-Type 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/objects/Knowledge_Account_RelationShip__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>Knowledge__r.ProductName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType1__c</fullName>
        <formula>Knowledge__r.SubType1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-Type 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType2__c</fullName>
        <formula>Knowledge__r.SubType2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-Type 2</label>
        <type>Text</type>
    </fields>
    <label>Knowledge Account RelationShip</label>
    <nameField>
        <displayFormat>KAR-{0000000}</displayFormat>
        <label>Knowledge Account RelationShip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Account RelationShips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Community_Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Topic</label>
        <referenceTo>Community_Topic__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Community_Topics__c</fullName>
        <label>Community Topics</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Community_Topics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SpecificToCSM__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CSM - ACN - S0024 - Specific to CSM?</description>
        <label>Specific to CSM?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Change_Request_Description__c</fullName>
        <description>ESPSFDCQI-4835</description>
        <label>Change Request Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Community_Topics.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ADA</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for CLM for Nexxus MI</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for CLM for OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for ePromo</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for Kadrige iDetailing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for Kadrige iSharing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for OCE Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Documentation for OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Spend 360</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregate Spend 360 - US</fullName>
    </customValue>
    <customValue>
        <fullName>Audits Nationaux Ethiques</fullName>
    </customValue>
    <customValue>
        <fullName>Business Rules &amp; Processes</fullName>
    </customValue>
    <customValue>
        <fullName>CLM Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>CLM For Nexxus MI</fullName>
    </customValue>
    <customValue>
        <fullName>CLM For OCE Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Connectivity &amp; Wireless</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Health</fullName>
    </customValue>
    <customValue>
        <fullName>Content for Kadrige iDetailing</fullName>
    </customValue>
    <customValue>
        <fullName>CRM Software</fullName>
    </customValue>
    <customValue>
        <fullName>Dashboard (Flex/SFE)</fullName>
    </customValue>
    <customValue>
        <fullName>DataView</fullName>
    </customValue>
    <customValue>
        <fullName>DDD</fullName>
    </customValue>
    <customValue>
        <fullName>EPPM</fullName>
    </customValue>
    <customValue>
        <fullName>ePromo</fullName>
    </customValue>
    <customValue>
        <fullName>Hardware &amp; Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Hospi 360</fullName>
    </customValue>
    <customValue>
        <fullName>IMS One</fullName>
    </customValue>
    <customValue>
        <fullName>Internal &amp; HD Processes</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA CDW</fullName>
    </customValue>
    <customValue>
        <fullName>IQVIA Data Connector</fullName>
    </customValue>
    <masterLabel>Community Topics</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/TST_CNT_CSM_KnowledgeBrowser.cls
/*
 * Version       : 1.0
 * Description   : Test Class for CNT_CSM_KnowledgeBrowser
 */
@isTest
public class TST_CNT_CSM_KnowledgeBrowser {
    /**
    * This method used to set up testdata
    */
    @testSetup
    static void dataSetup() {
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        String profilId2 = [select id from Profile where Name='System Administrator'].Id;
        User accOwner = New User(Alias = 'su',UserRoleId= portalRole.Id, ProfileId = profilId2,EmployeeNumber='070707078', Email = 'john2@iqvia.com',IsActive =true,Username ='john2@iqvia.com', LastName= 'testLastName', CommunityNickname ='testSuNickname', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US', UserPermissionsKnowledgeUser = true);
        accOwner.Change_Request_Description__c = 'Change Request Descritpion';
        insert accOwner;
        System.runAs (accOwner) {
            Account account = UTL_TestData.createAccount();
            account.ownerId=accOwner.Id;
            insert account;
            Community_topic__c ct = new Community_topic__c(Name='topicName');
            insert ct;
            Product2 product = UTL_TestData.createProduct();
            product.Community_topic__c = ct.Id;
            product.SpecificToCSM__c = True;
            insert product;
            Asset asset = new Asset(Name='TestAsset', AccountId = account.Id, Product2Id = product.id);
            insert asset;
            Contact contact = UTL_TestData.createContact(account.Id);
            insert contact;
            Knowledge__kav knowledge = new Knowledge__kav(Title = 'TestTitle', language = 'en_US',UrlName='TestUrlName', IsVisibleInCsp= true, Product__c= product.Id, ProductName__c='TestProduct', Pillar__c=CON_CSM.S_TECHNOLOGY_SOLUTIONS);
            insert knowledge;
            Knowledge__kav k = [SELECT Id,KnowledgeArticleId FROM Knowledge__kav WHERE Id =: knowledge.Id];
            KbManagement.PublishingService.publishArticle(k.KnowledgeArticleId, true);
            Knowledge_Account_RelationShip__c kar = new Knowledge_Account_RelationShip__c(Knowledge__c = knowledge.Id, Account__c = account.Id);
            insert kar;
            Knowledge__kav knowledge2 = new Knowledge__kav(Title = 'TestTitle2', language = 'en_US',UrlName='TestUrlName2', IsVisibleInCsp= true, Product__c= product.Id, ProductName__c='TestProduct', Pillar__c=CON_CSM.S_TECHNOLOGY_SOLUTIONS);
            insert knowledge2;
            Knowledge__kav k2 = [SELECT Id,KnowledgeArticleId FROM Knowledge__kav WHERE Id =: knowledge2.Id];
            KbManagement.PublishingService.publishArticle(k2.KnowledgeArticleId, true);
            CSM_QI_Case_Categorization__c categorization = new CSM_QI_Case_Categorization__c(Product__c = product.Id, SubType1__c='Please Specify', SubType2__c='Please Specify', Pillar__c=CON_CSM.S_TECHNOLOGY_SOLUTIONS);
            insert categorization;
        }
    }

    /**
    * This method used to get a List of Knowledge__kav by productName
    */
    @IsTest
    static void testGetArticlesByProductName() {
        List<Knowledge__kav> articles = new  List<Knowledge__kav>();
        Test.startTest();
        articles = CNT_CSM_KnowledgeBrowser.getArticlesByProductName('TestProduct');
        Test.stopTest();
        Integer expected = 2;
        Integer actual = articles.size();
        System.assertEquals(expected, actual);
    }

    @IsTest
    static void testGetArticlesByProductName2() {
        List<Knowledge__kav> articles = new  List<Knowledge__kav>();
        Account acc = [SELECT Id FROM Account Where Name='TestAccount'];
        Test.startTest();
        articles = CNT_CSM_KnowledgeBrowser.getArticlesByProductName2('TestProduct',acc.Id);
        Test.stopTest();
        Integer expected = 1;
        Integer actual = articles.size();
        System.assertEquals(expected, actual);
    }

    /**
    * This method used to get a List of products with Community_Topics__c not null and and present in CaseCategorization Object
    */
    @IsTest
    static void testGetProducts() {
        List<AggregateResult> products = new List<AggregateResult>();
        Test.startTest();
        products = CNT_CSM_KnowledgeBrowser.getProducts();
        Test.stopTest();
        Integer expected = 1;
        Integer actual = products.size();
        System.assertEquals(expected, actual);
    }

    @IsTest
    static void testGetAccountsArticlesByProductName() {
        Map<Id, Account>  accounts = new Map<Id, Account>();
        Test.startTest();
        accounts = CNT_CSM_KnowledgeBrowser.getAccountsArticlesByProductName('TestProduct');
        Test.stopTest();
        Integer expected = 1;
        Integer actual = accounts.size();
        System.assertEquals(expected, actual);
    }
}