src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-1808 - Related user of the contact</description>
        <inlineHelpText>CRM-MC-ESPSFDCQI-1808 - Related user of the contact</inlineHelpText>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Email_Notification_To_User__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ESPSFDCQI-5533</description>
    <fields>
        <fullName>Account_Ids__c</fullName>
        <description>Insert account ids with comma separated</description>
        <label>Account Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Ids__c</fullName>
        <description>Insert users id with comma seperated.(email will send to these users)</description>
        <label>User Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email Notification To User</label>
</CustomObject>

src/objects/Mulesoft_Integration_Control__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-QI-ESPSFDCQI-784 - Custom setting to control various aspects of Mulesoft integration (suppress outbound messages etc.)</description>
    <fields>
        <fullName>Enable_OLIS_JSON__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CRM-MC-ESPSFDCQI-768</description>
        <label>Enable OLIS JSON</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_OLI_Sync_Validation__c</fullName>
        <defaultValue>true</defaultValue>
        <description>CRM-MC-ESPSFDCQI-1052</description>
        <label>Enable OLI Sync Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Opportunity_Sync_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-1083</description>
        <label>Enable Opportunity Sync Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Mulesoft_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-768</description>
        <label>Is Mulesoft User</label>
        <type>Checkbox</type>
    </fields>
    <label>Mulesoft Integration Control</label>
</CustomObject>

src/objects/SWAT_Intake__c.object
<CustomObject>
    <description>ESPSFDCQI-5751</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-5751</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>SWAT Intakes</relationshipLabel>
        <relationshipName>SWAT_Intakes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submit_Form_To_SWAT_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <description>ESPSFDCQI-5751</description>
        <label>Submit Form To SWAT Team</label>
        <type>Checkbox</type>
    </fields>
    <label>SWAT Intake</label>
    <nameField>
        <displayFormat>SIF-{00000}</displayFormat>
        <label>SWAT Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SWAT Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SWAT_Intake_alert__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>ESPSFDCQI-5751</description>
    <fields>
        <fullName>Users_Email__c</fullName>
        <description>ESPSFDCQI-5751</description>
        <label>Users Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SWAT Intake alert</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PIC_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-742 - Details if the user is eligible to be a Principle in Charge on an Opportunity.</description>
        <inlineHelpText>Details if the user is eligible to be a Principle in Charge on an Opportunity.</inlineHelpText>
        <label>PIC Eligible</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TST_TGR_SWAT_Intake.cls
@isTest
public class TST_TGR_SWAT_Intake {
    @testSetup
    static void dataSetup() {
        Account acc1 = UTL_TestData.createAccount();
        acc1.Name = 'Test Parent Acc';
        insert acc1;
        upsert new  Mulesoft_Integration_Control__c(name = 'testSetting', Enable_OLIS_JSON__c = true, Is_Mulesoft_User__c = true, Enable_OLI_Sync_Validation__c = true, Enable_Opportunity_Sync_Validation__c = true);
        Account acc = UTL_TestData.createAccount();
        acc.ParentId = acc1.Id;
        insert acc;
        List<User> userList = UTL_TestData.createUser(CON_CRM.SYSTEM_ADMIN_PROFILE, 2);
        userList.addall(UTL_TestData.createUser('Sales User', 1));
        userList[0].PIC_Eligible__c = true;
        userList[0].IsActive = true;
        userList[1].PIC_Eligible__c = true;
        userList[1].IsActive = true;
        insert userList;
        upsert new Email_Notification_To_User__c(User_Ids__c = userList[0].Id,Account_Ids__c = acc1.Id);
        upsert new SWAT_Intake_alert__c(Users_Email__c = userList[0].Email);
        Contact cnt = UTL_TestData.createContact(acc.Id);
        cnt.RecordTypeId = CON_CRM.IQVIA_USER_CONTACT_RECORD_TYPE_ID;
        cnt.Salesforce_User__c = userList[0].Id;
        insert cnt;
        Account acc2 = [SELECT Id, Name FROM Account WHERE Name = 'TestAccount'];
        Opportunity opp = UTL_TestData.createOpportunity(acc2.Id);
        Test.startTest();
        insert opp;
        SWAT_Intake__c swt = new SWAT_Intake__c();
		swt.Opportunity__c = opp.Id;
        swt.Submit_Form_To_SWAT_Team__c = true;
        insert swt;
    }
    /**
    * This test method used for insert and update SWAT Intake record
    */ 
    static testMethod void test2() {
        SWAT_Intake__c swt = [SELECT Id, Name FROM SWAT_Intake__c limit 1];
        swt.Submit_Form_To_SWAT_Team__c = true;
        update swt;
    }
}