src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Available_for_Triage_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>OWF - MC- ESPSFDCQI-2234- This field is part of the OWF Process.</description>
        <label>Available for Triage Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <description>OWF - MC- ESPSFDCQI-2248- This field is part of the OWF Process.</description>
        <label>Sub-Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AIML Solutions</fullName>
                </value>
                <value>
                    <fullName>GBO-Lead PD</fullName>
                </value>
                <value>
                    <fullName>GBO-RFI</fullName>
                </value>
                <value>
                    <fullName>GBO-Lead Contracts Analyst</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>TSL-Japan</fullName>
                </value>
                <value>
                    <fullName>Medical-MSL</fullName>
                </value>
                <value>
                    <fullName>TAL</fullName>
                </value>
                <value>
                    <fullName>Site Analytics</fullName>
                </value>
                <value>
                    <fullName>Feasibility Analytics</fullName>
                </value>
                <value>
                    <fullName>DSB-Clinical</fullName>
                </value>
                <value>
                    <fullName>SPN Product Specialist</fullName>
                </value>
                <value>
                    <fullName>CAGT-COE</fullName>
                </value>
                <value>
                    <fullName>Design Analytics</fullName>
                </value>
                <value>
                    <fullName>DSB-MW</fullName>
                </value>
                <value>
                    <fullName>DSB-Bios</fullName>
                </value>
                <value>
                    <fullName>DSB-DM</fullName>
                </value>
                <value>
                    <fullName>DSB-CEVA</fullName>
                </value>
                <value>
                    <fullName>DSB-LCS</fullName>
                </value>
                <value>
                    <fullName>DSB-GSA</fullName>
                </value>
                <value>
                    <fullName>CSMS-Lead PD</fullName>
                </value>
                <value>
                    <fullName>ECD-COE</fullName>
                </value>
                <value>
                    <fullName>LCS Product Specialist</fullName>
                </value>
                <value>
                    <fullName>LCS Bid Defense</fullName>
                </value>
                <value>
                    <fullName>GBO-Strategic Writer</fullName>
                </value>
                <value>
                    <fullName>GBO-Support CA</fullName>
                </value>
                <value>
                    <fullName>GBO-Support PD</fullName>
                </value>
                <value>
                    <fullName>GBO-Bid Grid</fullName>
                </value>
                <value>
                    <fullName>Biosimilar-COE</fullName>
                </value>
                <value>
                    <fullName>PRD-COE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/pse__Assignment__c.object
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Bid_History_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bid_Number__c</fullName>
        <description>OWF-MC-ESPSFDCQI-4846-This field is part of the OWF Process.</description>
        <formula>Bid_History__r.Bid_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bid Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse__Resource_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Resource Request Lookup populated only when assignment is created from a resource request.</description>
        <label>Resource Request</label>
        <referenceTo>pse__Resource_Request__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Permission_Control__c.object
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Group containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Group.</description>
        <inlineHelpText>This is the Group containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Group.</inlineHelpText>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Permission Controls</relationshipLabel>
        <relationshipName>Permission_Controls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Proj__c.object
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 Creating Bid History lookup for OWF Process</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Bid_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bid_Number__c</fullName>
        <description>OWF-QI-US-2761 - This field is part of the OWF Process.
IQVIAPSA-3950 - updating field reference to Bid History</description>
        <formula>Bid_History__r.Bid_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bid Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Resource_Request__c.object
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Bid_History_Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <description>OWF-MC-ESPSFDCQI-3042-This field is part of the OWF Process.</description>
        <label>SubGroup</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AIML Solutions</fullName>
                </value>
                <value>
                    <fullName>GBO-Lead PD</fullName>
                </value>
                <value>
                    <fullName>GBO-Bid Grid</fullName>
                </value>
                <value>
                    <fullName>GBO-RFI</fullName>
                </value>
                <value>
                    <fullName>GBO-Strategic Writer</fullName>
                </value>
                <value>
                    <fullName>GBO-Support CA</fullName>
                </value>
                <value>
                    <fullName>GBO-Support PD</fullName>
                </value>
                <value>
                    <fullName>GBO-Lead Contracts Analyst</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>TSL-Japan</fullName>
                </value>
                <value>
                    <fullName>Medical-MSL</fullName>
                </value>
                <value>
                    <fullName>Biosimilar-COE</fullName>
                </value>
                <value>
                    <fullName>ECD-COE</fullName>
                </value>
                <value>
                    <fullName>CAGT-COE</fullName>
                </value>
                <value>
                    <fullName>PRD-COE</fullName>
                </value>
                <value>
                    <fullName>TAL</fullName>
                </value>
                <value>
                    <fullName>Feasibility Analytics</fullName>
                </value>
                <value>
                    <fullName>Site Analytics</fullName>
                </value>
                <value>
                    <fullName>Design Analytics</fullName>
                </value>
                <value>
                    <fullName>Global Analytics</fullName>
                </value>
                <value>
                    <fullName>SPN Product Specialist</fullName>
                </value>
                <value>
                    <fullName>DSB-DM</fullName>
                </value>
                <value>
                    <fullName>DSB-LCS</fullName>
                </value>
                <value>
                    <fullName>DSB-Bios</fullName>
                </value>
                <value>
                    <fullName>DSB-MW</fullName>
                </value>
                <value>
                    <fullName>DSB-CEVA</fullName>
                </value>
                <value>
                    <fullName>DSB-Clinical</fullName>
                </value>
                <value>
                    <fullName>DSB-GSA</fullName>
                </value>
                <value>
                    <fullName>STS-Lead</fullName>
                </value>
                <value>
                    <fullName>CTS-Lead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <description>OWF-MC-ESPSFDCQI-2896-This field is part of the OWF Process.</description>
        <label>Sub Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_CNT_OWF_CreateAssignmentFromResReq.cls
/**
 * This test class is used to test all methods in Resource Request trigger.
 * version : 1.0 
 */
@isTest(seeAllData=false)
private class TST_CNT_OWF_CreateAssignmentFromResReq {
    
	/**
    * This method used to set up testdata
    */ 
    @testSetup
    static void dataSetup() 
	{
        Account acc = UTL_OWF_TestData.createAccount();
        insert acc;
        pse__Grp__c grp = UTL_OWF_TestData.createGroup();
        insert grp;
        Contact cont = UTL_OWF_TestData.createContact(acc.Id);
        cont.pse__Is_Resource__c = true;
        cont.pse__Is_Resource_Active__c = true;
        cont.pse__Group__c = grp.Id;
        cont.sub_group__c = 'TSL-Japan';
        cont.Available_for_triage_flag__c = true;
        cont.pse__Salesforce_User__c = userInfo.getUserId();
        insert cont;
        pse__Permission_Control__c permissionControlGroup = UTL_OWF_TestData.createPermissionControl(null, null, grp, null);
        insert permissionControlGroup;
        Opportunity opp = UTL_OWF_TestData.createOpportunity(acc.Id);
        insert opp;
        Bid_History__c agreement = UTL_OWF_TestData.createBidHistoryByRecordType(acc.Id, opp.Id, CON_OWF.OWF_CLINICAL_BID_BID_HISTORY_RECORD_TYPE_ID);
        agreement.Bid_Number__c = 1;
        agreement.Bid_Due_Date__c = System.today().AddDays(5);
        insert agreement; 
        pse__Proj__c bidProject = [Select id from pse__Proj__c where Bid_History__c =: agreement.Id];
        pse__Resource_Request__c resourceRequest = UTL_OWF_TestData.createResourceRequestForBidHistory(agreement.Id, opp.Id, bidProject.Id);
        resourceRequest.pse__Group__c = grp.Id;
        resourceRequest.subgroup__c = 'TSL-Japan';
        resourceRequest.Suggested_FTE__c = 11;
        insert resourceRequest;
    }
	
    
    /**
    * This test method used to test getSuggestedFTEFromResRequest method
    */
    @isTest
    static void testGetSuggestedFTEFromResRequest() 
	{
        Test.startTest();
			Contact cont = [SELECT Id, Name FROM Contact limit 1];
			Bid_History__c agreement = [SELECT Id, Name FROM Bid_History__c limit 1];
			pse__Proj__c bidProject = [Select id from pse__Proj__c where Bid_History__c =: agreement.Id];        
			pse__Resource_Request__c resRequest = [SELECT Id, Name FROM pse__Resource_Request__c where subgroup__c = 'TSL-Japan' limit 1];
			pse__Schedule__c schedule = UTL_OWF_TestData.createSchedule();
			insert schedule;
			pse__Assignment__c assignment = UTL_OWF_TestData.createAssignmentForBidHistory(agreement.Id, bidProject.Id, schedule.Id, cont.Id, resRequest.Id);
			insert assignment;
        Test.stopTest();
			
        String expected = 'Assignment already exists';
        String actual = CNT_OWF_CreateAssignmentFromResReq.getSuggestedFTEFromResRequest(String.valueOf(resRequest.Id));
        system.assertEquals(expected, actual, 'Verifying CNT_OWF_CreateAssignmentFromResReq.getSuggestedFTEFromResRequest Functionality');
    }
    
	
    /**
    * This test method used to test createAssignment method
    */
    @isTest
    static void testCreateAssignment() 
	{
        pse__Resource_Request__c resRequest = [SELECT Id, Name FROM pse__Resource_Request__c where subgroup__c = 'TSL-Japan'];
        Contact cont = [Select Id From Contact order by CreatedDate asc limit 1];
        
        Test.startTest();
            String resultMessage = CNT_OWF_CreateAssignmentFromResReq.assignResourceAndCreateAssignment(resRequest.Id, cont.Id);
            system.assertEquals('success', resultMessage, 'Verifying CNT_OWF_CreateAssignmentFromResReq.assignResourceAndCreateAssignment Functionality');
        Test.stopTest();
    }
    
	
    /**
    * This test method used to test createAssignment method
    */
    @isTest
    static void testCreateAssignmentWithError() {
        pse__Resource_Request__c resRequest = [SELECT Id, Name FROM pse__Resource_Request__c where subgroup__c = 'TSL-Japan'];
        Contact cont = [Select Id From Contact order by CreatedDate asc limit 1];
        cont.sub_group__c = 'TSL';
        update cont;
        
        Test.startTest();
            String resultMessage = CNT_OWF_CreateAssignmentFromResReq.assignResourceAndCreateAssignment(resRequest.Id, cont.Id);
            system.assertNotEquals('success', resultMessage, 'Verifying CNT_OWF_CreateAssignmentFromResReq.assignResourceAndCreateAssignment Functionality');
        Test.stopTest();
    }
    
	
    /**
    * This test method used to test createAssignment method
    */
    @isTest
    static void testHasAccess() 
	{
        Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(new pse__Resource_Request__c());
            CNT_OWF_CreateAssignmentFromResReq cnt = new CNT_OWF_CreateAssignmentFromResReq(sc);
            cnt.hasAccess = true;
        Test.stopTest();
        
        Boolean expected = true;
        Boolean actual = cnt.hasAccess;
        system.assertEquals(expected, actual, 'Verifying CNT_OWF_CreateAssignmentFromResReq.hasAccess Functionality');
    }
}