src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_User_Type__c</fullName>
        <label>Contact User Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HO User</fullName>
                </value>
                <value>
                    <fullName>Rep User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <description>PEP-ACN-AM_CM-11 Partner type</description>
        <label>Partner Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Integrator Partner</fullName>
                </value>
                <value>
                    <fullName>Data Partner</fullName>
                </value>
                <value>
                    <fullName>Tech Partner</fullName>
                </value>
                <value>
                    <fullName>Training Partner</fullName>
                </value>
                <value>
                    <fullName>CLM Agency</fullName>
                </value>
                <value>
                    <fullName>One Home for Sites</fullName>
                </value>
                <value>
                    <fullName>AMESA - Integrator Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Portal_Case_Type__c</fullName>
        <label>Portal Case Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Information Offering</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Technology Solutions</fullName>
                </value>
                <value>
                    <fullName>DATA</fullName>
                    <isActive>false</isActive>
                    <label>DATA</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Partner_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/globalValueSets/Partner_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Integrator Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Data Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Tech Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CLM Agency</fullName>
    </customValue>
    <customValue>
        <fullName>One Home for Sites</fullName>
    </customValue>
    <customValue>
        <fullName>AMESA - Integrator Partner</fullName>
    </customValue>
    <description>PRM-982: Added two picklist values for Knowledge and CSM Announcement objects.</description>
    <masterLabel>Partner Type</masterLabel>
</GlobalValueSet>

src/classes/CNT_PEP_PartnerPortalSearch.cls
public class CNT_PEP_PartnerPortalSearch { 
    public class PEP_SearchResult {
    @AuraEnabled
    public String id {get; set;}
    @AuraEnabled
    public String objName {get; set;}
    @AuraEnabled
    public SObject sobj {get; set;}
    }
    @AuraEnabled
    public static List<PEP_SearchResult> searchForIds(String searchText, String searchObject, Integer rowLimit, Integer rowOffset) {
        List<User> users = new List<User>();
        String partnerType = '';
        List<PEP_SearchResult> srList = new List<PEP_SearchResult>();
        users = new SLT_User().selectContactDetailByUser(new Set<Id> {userInfo.getUserId()}, new Set<String>  {'Contact.Portal_Case_Type__c','Contact.Contact_User_Type__c','AccountId','Contact.Partner_Type__c'});
        partnerType = users[0].Contact.Partner_Type__c;
        partnerType = '\'' + partnerType.replace(';','\',\'') +'\'';
        if (users.size() > 0 && users[0].Contact != null && users[0].AccountId != null) {
            Set<String> pillar = new Set<String>(users[0].Contact.Portal_Case_Type__c.split(';'));
            String userType = users[0].Contact.Contact_User_Type__c;
            Set<String> ids = new Set<String>();
            List<asset> assets = new SLT_Asset().getAssetsWithFilter(new Set<String>{'Product2Id'}, 'AccountId=\''+ users[0].AccountId +'\' AND Status !=\'Obsolete\' AND Product2Id !=\'\'');
            for (Integer i=0; i<assets.size(); i++) {
                ids.add(assets[i].Product2Id);
            }
            List<List<SObject>> results = new List<List<SObject>>();            
            if(searchObject == '' || searchObject == 'Case') {
                List<List<SObject>> results1 = new SLT_Case().getSearchResults(searchText, pillar, users[0].AccountId,ids, partnerType, rowLimit, rowOffset);           
                results.addAll(results1);
            }
            if(searchObject == '' || searchObject == 'Knowledge__kav') {
                List<List<SObject>> results2 = new SLT_Knowledge().getSearchResultsPRM1(searchText, pillar, users[0].AccountId, ids, partnerType, rowLimit, rowOffset);
                List<List<SObject>> results3 = new SLT_Knowledge().getSearchResultsPRM2(searchText, pillar, users[0].AccountId, ids, partnerType, rowLimit, rowOffset);
                results.addAll(results2);
                results.addAll(results3);
            }
            
            if(searchObject == '' || searchObject == 'ContentDocument') {
                List<List<SObject>> results4 = new SLT_ContentDocument().getSearchResultsContentDocument(searchText, rowLimit, rowOffset);
                results.addAll(results4);
            }
            
            System.debug('Articles result : ' + results);
            for (List<SObject> sobjs : results) {
                for (SObject sobj : sobjs) {
                    PEP_SearchResult sr = new PEP_SearchResult();
                    sr.id = sobj.Id;
                    sr.objName = string.valueOf(sobj.Id.getsobjecttype());
                    sr.sobj = sobj;
                    if( sr.objName == 'Knowledge__kav') {
                        srList.add(sr);
                    }else if(sr.objName == 'Case'){
                        srList.add(sr);
                    }else{
                        srList.add(sr);
                    }
                }
            }
        }
        return srList;
    }
}