src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Available_for_Triage_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>OWF - MC- ESPSFDCQI-2234- This field is part of the OWF Process.</description>
        <label>Available for Triage Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <description>OWF - MC- ESPSFDCQI-2248- This field is part of the OWF Process.</description>
        <label>Sub-Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AIML Solutions</fullName>
                </value>
                <value>
                    <fullName>GBO-Lead PD</fullName>
                </value>
                <value>
                    <fullName>GBO-RFI</fullName>
                </value>
                <value>
                    <fullName>GBO-Lead Contracts Analyst</fullName>
                </value>
                <value>
                    <fullName>TSL</fullName>
                </value>
                <value>
                    <fullName>TSL-Japan</fullName>
                </value>
                <value>
                    <fullName>Medical-MSL</fullName>
                </value>
                <value>
                    <fullName>TAL</fullName>
                </value>
                <value>
                    <fullName>Site Analytics</fullName>
                </value>
                <value>
                    <fullName>Feasibility Analytics</fullName>
                </value>
                <value>
                    <fullName>DSB-Clinical</fullName>
                </value>
                <value>
                    <fullName>SPN Product Specialist</fullName>
                </value>
                <value>
                    <fullName>CAGT-COE</fullName>
                </value>
                <value>
                    <fullName>Design Analytics</fullName>
                </value>
                <value>
                    <fullName>DSB-MW</fullName>
                </value>
                <value>
                    <fullName>DSB-Bios</fullName>
                </value>
                <value>
                    <fullName>DSB-DM</fullName>
                </value>
                <value>
                    <fullName>DSB-CEVA</fullName>
                </value>
                <value>
                    <fullName>DSB-LCS</fullName>
                </value>
                <value>
                    <fullName>DSB-GSA</fullName>
                </value>
                <value>
                    <fullName>CSMS-Lead PD</fullName>
                </value>
                <value>
                    <fullName>ECD-COE</fullName>
                </value>
                <value>
                    <fullName>LCS Product Specialist</fullName>
                </value>
                <value>
                    <fullName>LCS Bid Defense</fullName>
                </value>
                <value>
                    <fullName>GBO-Strategic Writer</fullName>
                </value>
                <value>
                    <fullName>GBO-Support CA</fullName>
                </value>
                <value>
                    <fullName>GBO-Support PD</fullName>
                </value>
                <value>
                    <fullName>GBO-Bid Grid</fullName>
                </value>
                <value>
                    <fullName>Biosimilar-COE</fullName>
                </value>
                <value>
                    <fullName>PRD-COE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pse__Is_Resource__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resource</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mulesoft_Integration_Control__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-QI-ESPSFDCQI-784 - Custom setting to control various aspects of Mulesoft integration (suppress outbound messages etc.)</description>
    <fields>
        <fullName>Ignore_Validation_Rules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-1007</description>
        <label>Ignore Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Mulesoft_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-768</description>
        <label>Is Mulesoft User</label>
        <type>Checkbox</type>
    </fields>
    <label>Mulesoft Integration Control</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <description>CRM-MC-ESPSFDCQI-2690 -</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Line_of_Business__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Non-Compete</fullName>
                </value>
                <value>
                    <fullName>Ballpark</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/pse__Assignment__c.object
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Bid_History_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bid_Number__c</fullName>
        <description>OWF-MC-ESPSFDCQI-4846-This field is part of the OWF Process.</description>
        <formula>Bid_History__r.Bid_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bid Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget_Deliverable__c</fullName>
        <description>OWF-MC-ESPSFDCQI-2190-This field is part of the OWF Process.</description>
        <formula>TEXT(Bid_History__r.Budget_Deliverable__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget Deliverable</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFP_Ranking__c</fullName>
        <description>OWF-MC-ESPSFDCQI-2190-This field is part of the OWF Process.</description>
        <formula>TEXT(Bid_History__r.RFP_Ranking__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RFP Ranking</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__Resource_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Resource Request Lookup populated only when assignment is created from a resource request.</description>
        <label>Resource Request</label>
        <referenceTo>pse__Resource_Request__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>pse__Schedule__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Grp__c.object
<CustomObject>
    <customHelpPage>pse__GroupHelp</customHelpPage>
    <description>An entity that usually represents a functional business area or business vertical. Groups are organized as an independent hierarchy determined by the Parent Group field, with parent and child records of the same type. Every group in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Permission_Control__c.object
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Group containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Group.</description>
        <inlineHelpText>This is the Group containing Resources that are the target of the specified action(s) - e.g. delegated Timecard Entry on behalf of Resources in this Group.</inlineHelpText>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Permission Controls</relationshipLabel>
        <relationshipName>Permission_Controls</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Proj__c.object
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 Creating Bid History lookup for OWF Process</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Bid_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bid_Number__c</fullName>
        <description>OWF-QI-US-2761 - This field is part of the OWF Process.
IQVIAPSA-3950 - updating field reference to Bid History</description>
        <formula>Bid_History__r.Bid_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bid Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Bid</fullName>
        <active>true</active>
        <description>OWF-MC-ESPSFDCQI-2160</description>
        <label>Bid</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Resource_Request__c.object
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Bid_History_Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Deliverable__c</fullName>
        <description>OWF-MC-ESPSFDCQI-2247</description>
        <formula>TEXT( Bid_History__r.Budget_Deliverable__c )</formula>
        <label>Budget Deliverable</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFP_Ranking__c</fullName>
        <description>OWF-MC-ESPSFDCQI-2247</description>
        <formula>TEXT( Bid_History__r.RFP_Ranking__c )</formula>
        <label>RFP Ranking</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Group__c</fullName>
        <description>OWF-MC-ESPSFDCQI-2896-This field is part of the OWF Process.</description>
        <label>Sub Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pse__Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>pse__Assignment__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>pse__Grp__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <recordTypes>
        <fullName>OWF_Resource_Request</fullName>
        <active>true</active>
        <description>OWF-MC-ESPSFDCQI-2896</description>
        <label>OWF Resource Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Schedule__c.object
<CustomObject>
    <customHelpPage>pse__ScheduleHelp</customHelpPage>
    <description>Represents start and end dates and weekly working hours for an assignment. You enter schedule details when you create an assignment, which also creates an associated schedule record. Although schedule records have the fields Scheduled Hours and Scheduled Days, these are not intended for users to enter time directly. Their values are system-generated based on schedule dates, patterns, and exceptions. Specific deviations from schedules are represented as schedule exceptions.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>Schedule{000000}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_BCH_OWF_Clean_AGR_Related_Projects.cls
@isTest(seeAllData=false)
private class TST_BCH_OWF_Clean_AGR_Related_Projects {

    @testSetup
    static void dataSetup() 
	{
        
        User testUser = UTL_OWF_TestData.createUser('System Administrator',1)[0];
        insert testUser;
        Mulesoft_Integration_Control__c mfc = new Mulesoft_Integration_Control__c();
        mfc.Is_Mulesoft_User__c = true;
        mfc.Ignore_Validation_Rules__c = true;
        mfc.SetupOwnerId = testUser.Id;
        insert mfc;
        
		System.runAs(testUser)
        {
			Account acc = UTL_OWF_TestData.createAccount();
			insert acc;
			pse__Grp__c grp = UTL_OWF_TestData.createGroup();
			insert grp;
			Contact cont = UTL_OWF_TestData.createContact(acc.Id);
			cont.pse__Is_Resource__c = true;
			cont.pse__Is_Resource_Active__c = true;
			cont.pse__Group__c = grp.Id;
			cont.FirstName = UserInfo.getFirstName();
			cont.LastName = UserInfo.getLastName();
			cont.sub_group__c = 'TSL-Japan';
			cont.available_for_triage_flag__c = true;
			insert cont;
			pse__Permission_Control__c permissionControlGroup = UTL_OWF_TestData.createPermissionControl(null, null, grp, null);
			insert permissionControlGroup;
			Opportunity opp = UTL_OWF_TestData.createOpportunity(acc.Id);
			insert opp;
			Bid_History__c agreement = UTL_OWF_TestData.createBidHistoryByRecordType(acc.Id, opp.Id, CON_OWF.OWF_CLINICAL_BID_BID_HISTORY_RECORD_TYPE_ID);
            agreement.Bid_Number__c = 0;
			agreement.Opportunity_Type__c = CON_OWF.OPPORTUNITY_TYPE;
			agreement.RFP_Ranking__c = '2';
			agreement.Budget_Deliverable__c= CON_OWF.BUDGET_DELIVERABLE;
			test.startTest();
			insert agreement;        
			pse__Proj__c bidProject = [Select id from pse__Proj__c  where Bid_History__c =: agreement.Id];
			update bidProject; 
			pse__Schedule__c schedule = UTL_OWF_TestData.createSchedule();
			insert schedule;
			pse__Resource_Request__c resourceRequest = UTL_OWF_TestData.createResourceRequestForBidHistory(agreement.Id, opp.Id, bidProject.Id);
			resourceRequest.pse__Group__c = grp.Id;
			resourceRequest.RecordTypeId = Schema.SObjectType.pse__Resource_Request__c.getRecordTypeInfosByDeveloperName().get('OWF_Resource_Request').getRecordTypeId();   
			insert resourceRequest;
			pse__Assignment__c assignement =  UTL_OWF_TestData.createAssignmentForBidHistory(agreement.Id, bidProject.Id, schedule.Id, cont.Id, resourceRequest.Id);
			insert assignement;
			test.stopTest();
        }
		
        pse__Proj__c  bidProject1 = [Select id from pse__Proj__c limit 1];
        Map<Id,String> projectIdToErrorMessageMap = new Map<Id,String>();
        projectIdToErrorMessageMap.put(bidProject1.Id,'Error in Project deletion through queuable job: ' + 'Error in Project deletion through queuable job: TGR_Proj: execution of AfterDelete'
										+'caused by: fflib_SObjectDomain.DomainException: Permission to delete an pse__Proj__c denied.'
										+'Class.fflib_SObjectDomain.handleAfterDelete: line 233, column 1'
										+'Class.fflib_SObjectDomain: line 376, column 1'
										+'Class.fflib_SObjectDomain.triggerHandler: line 321, column 1'
										+'Trigger.TGR_Proj: line 8, column 1');
        UTL_OWF.createApexErrorLogs('Project (pse__Proj__c)', 'Error in Project deletion through queuable job: ', projectIdToErrorMessageMap);
    }
    
	@isTest
    static void testDeleteAgreementCascading()
    {        
        List<Map<Id,String>> coverageFixList = new List<Map<Id, String>>();
        Map<Id,String> coverageFixMap = new Map<Id,String>();
        Bid_History__c bid = [Select Id from Bid_History__c limit 1];
        coverageFixMap.put(bid.id,'Error in Project deletion through Batch: ' + 'Error in Project deletion through Batch: TGR_Proj: execution of AfterDelete'
										+'caused by: fflib_SObjectDomain.DomainException: Permission to delete an pse__Proj__c denied.'
										+'Class.fflib_SObjectDomain.handleAfterDelete: line 233, column 1'
										+'Class.fflib_SObjectDomain: line 376, column 1'
										+'Class.fflib_SObjectDomain.triggerHandler: line 321, column 1'
										+'Trigger.TGR_Proj: line 8, column 1');
        Test.startTest();
        BCH_OWF_Clean_AGR_Related_Projects batch = new BCH_OWF_Clean_AGR_Related_Projects();
        coverageFixList.add(coverageFixMap);
        batch.projectIdToErrorMessageMapList = coverageFixList;
        DataBase.executeBatch(batch,10);
        
        
        List<pse__Proj__c> bidProject = [Select Id from pse__Proj__c limit 1];
        Test.stopTest();
		Integer expected = 1;
        Integer actual = bidProject.size();
        system.assertEquals(expected, actual,'Verifying BCH_OWF_Clean_AGR_Related_Projects Functionality');
    }
}