src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>A location indicator.  For example, QRTP = Quintiles Research Triangle Park.</description>
        <inlineHelpText>A location indicator.  For example, QRTP = Quintiles Research Triangle Park.</inlineHelpText>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IQVIA_Location</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remove_KB_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Remove KB Access</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Answer__c</fullName>
        <description>CSM-ACN-S-0046 - Rich Text Field for Answer.</description>
        <label>Answer</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>CSM-ACN-S-0046 - Rich textfield for Content</description>
        <label>Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>L1Answer__c</fullName>
        <description>CSM-ACN-S-0046 - Rich textfield for L1 Answer</description>
        <label>L1 Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>L1Content__c</fullName>
        <description>CSM-ACN-S-0046 - Rich Textfield for L1 Content</description>
        <label>L1 Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>L2L3Answer__c</fullName>
        <description>CSM-ACN-S-0046 - Rich TextField for L2/L3 Answer</description>
        <label>L2/L3 Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>L2L3Content__c</fullName>
        <description>CSM-ACN-S-0046 - Rich Textfield for L2/L3 Content</description>
        <label>L2/L3 Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <description>CSM - ACN - S-0046 - Product Name</description>
        <label>ProductName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Knowledge</relationshipLabel>
        <relationshipName>Knowledge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>CSM-ACN-S-0046 - Text field for Question.</description>
        <label>Question</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Knowledge</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/objects/Knowledge_Account_RelationShip__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>CSM_QI_KB_Location__c.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CSM_QI_KB_Location__c</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>Knowledge__r.ProductName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductName</label>
        <type>Text</type>
    </fields>
    <label>Knowledge Account RelationShip</label>
    <nameField>
        <displayFormat>KAR-{0000000}</displayFormat>
        <label>Knowledge Account RelationShip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Account RelationShips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/IQVIA_Location.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AEDBA1</fullName>
    </customValue>
    <customValue>
        <fullName>AEDBA2</fullName>
    </customValue>
    <customValue>
        <fullName>AEDBA4</fullName>
    </customValue>
    <customValue>
        <fullName>ALL2</fullName>
    </customValue>
    <customValue>
        <fullName>ARBUE1</fullName>
    </customValue>
    <customValue>
        <fullName>ARBUE2</fullName>
    </customValue>
    <customValue>
        <fullName>ARBUEL</fullName>
    </customValue>
    <customValue>
        <fullName>ATVIE2</fullName>
    </customValue>
    <customValue>
        <fullName>AUMEL1</fullName>
    </customValue>
    <customValue>
        <fullName>AUSLD2</fullName>
    </customValue>
    <customValue>
        <fullName>BASAR2</fullName>
    </customValue>
    <customValue>
        <fullName>BDDHA1</fullName>
    </customValue>
    <customValue>
        <fullName>BDDHA2</fullName>
    </customValue>
    <customValue>
        <fullName>BEANT1</fullName>
    </customValue>
    <customValue>
        <fullName>BEANT2</fullName>
    </customValue>
    <customValue>
        <fullName>BEBES1</fullName>
    </customValue>
    <customValue>
        <fullName>BEWIJ1</fullName>
    </customValue>
    <customValue>
        <fullName>BEZVM1</fullName>
    </customValue>
    <customValue>
        <fullName>BGSOF2</fullName>
    </customValue>
    <customValue>
        <fullName>BOLAP2</fullName>
    </customValue>
    <customValue>
        <fullName>BRSAO1</fullName>
    </customValue>
    <customValue>
        <fullName>BRSAO2</fullName>
    </customValue>
    <customValue>
        <fullName>BRY1</fullName>
    </customValue>
    <customValue>
        <fullName>CAHAL1</fullName>
    </customValue>
    <customValue>
        <fullName>CAKAN1</fullName>
    </customValue>
    <customValue>
        <fullName>CAKRKR</fullName>
    </customValue>
    <customValue>
        <fullName>CAMIS1</fullName>
    </customValue>
    <customValue>
        <fullName>CAOTT1</fullName>
    </customValue>
    <customValue>
        <fullName>CATOR1</fullName>
    </customValue>
    <customValue>
        <fullName>CATOR2</fullName>
    </customValue>
    <description>A location indicator.  For example, QRTP = Quintiles Research Triangle Park</description>
    <masterLabel>IQVIA Location</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet> 

src/classes/CNT_CSM_EinsteinBot_SearchFAQ.cls
public class CNT_CSM_EinsteinBot_SearchFAQ {

    
    public class SearchInput{
        @InvocableVariable(required = true)
        public String searchKeyword;
        
        @InvocableVariable(required=true)
        public Id routableId;
        
        //@InvocableVariable(required = true)
        //public Product2 productName;
    }
    
    public class SearchOutput{
        @InvocableVariable(required = true)
        public String searchOutput;
    }

    @InvocableMethod(label='SearchFAQ')
    public static List<SearchOutput> searchFAQ(List<SearchInput> searchInputList){
        String keyword = searchInputList[0].searchKeyword;
        Id chatSessionId = searchInputList[0].routableId;
        String faqResult = 'RICH_TEXT:';
        // Fetch the existing products linked to the account of current user
        LiveChatTranscript chatContactRecord = [SELECT ContactId FROM LiveChatTranscript WHERE Id = :chatSessionId LIMIT 1];
        
        if(chatContactRecord != null && chatContactRecord.ContactId != null){
            Id contactId = chatContactRecord.ContactId;
            Id accountId = null;
            boolean isCSHKBAccess = false;
            string commaSeparatedKnowledge ='\'';
            List<Product2> products = CNT_CSM_EinsteinBot_ProductsAccess.getContactProducts(contactId);
            List<Contact> con = Database.query('Select Id,AccountId,Remove_KB_Access__c from Contact where Id =:contactId');
            if(con != null){
                for(Contact c: con){
                    accountId = c.AccountId;
                    isCSHKBAccess = c.Remove_KB_Access__c;
                }
                
                List<Knowledge_Account_RelationShip__c > karList = Database.query('select Id, Name, Account__c, Knowledge__c,Knowledge__r.ArticleNumber,  Location__c from Knowledge_Account_RelationShip__c where Account__c =:accountId and Knowledge__c != null');
                for(Knowledge_Account_RelationShip__c kar : karList){
                    commaSeparatedKnowledge =commaSeparatedKnowledge + kar.Knowledge__r.ArticleNumber + '\',\'';
                }
                commaSeparatedKnowledge = commaSeparatedKnowledge.left(commaSeparatedKnowledge.length()-2);
            }
            if(isCSHKBAccess){
                faqResult +='You donot have the access to view knowledge articles.Please contact system administrator to enable the knowledge article access.';
            }else if(products != null && !products.isEmpty() && !isCSHKBAccess){
                string commaSeparatedproduct ='\'';
                for(Product2 p : products){
                    commaSeparatedproduct =commaSeparatedproduct + p.Name + '\',\'';
                }
                commaSeparatedproduct = commaSeparatedproduct.left(commaSeparatedproduct.length()-2);
                String query = 'FIND \'' +String.escapeSingleQuotes(keyword)+'\' IN ALL Fields Returning Knowledge__kav(Id, Title, UrlName, Content__c, L1Content__c, L2L3Content__c, Question__c, Answer__c, L1Answer__c, L2L3Answer__c WHERE Language=\'en_US\' AND PublishStatus = \'Online\' AND IsLatestVersion = true AND IsVisibleInCsp = true AND ';
                if(commaSeparatedKnowledge.length() > 5){
                    query+='(ArticleNumber in ('+commaSeparatedKnowledge+') OR ProductName__c in ('+commaSeparatedproduct+')) ) WITH SNIPPET (target_length=1500) LIMIT 5';
                }else{
                    query+= 'ProductName__c in ('+commaSeparatedproduct+') ) WITH SNIPPET (target_length=1500) LIMIT 5';   
                }
                Search.SearchResults searchResults = Search.find(query);
                List<Search.SearchResult> articleList = new List<Search.SearchResult>();
                articleList = searchResults.get('Knowledge__kav');
                String articleBaseUrl = getCommunityBaseUrl();
                for(Search.SearchResult searchResult : articleList){
                    Knowledge__kav article = (Knowledge__kav) searchResult.getSObject();
                    String snippet = searchResult.getSnippet();
                    if(snippet != null){
                        String articleSummary = summarizeArticleForChatbot(articleBaseUrl, article,snippet,String.escapeSingleQuotes(keyword));
                        faqResult = faqResult + articleSummary;    
                    }
                }
            }
        }
        if(faqResult == 'RICH_TEXT:'){
            faqResult = 'No result found';
        }
        
        List<SearchOutput> faqOutputs = new List<SearchOutput>();
        SearchOutput output = new SearchOutput();
        output.searchOutput = faqResult;
        faqOutputs.add(output);
        return faqOutputs;
    }
    
    public static String getCommunityBaseUrl(){
        List<Network> communityNetworks = [SELECT Id FROM Network WHERE Name ='IQVIA Customer Service Hub'];
        String baseUrl = '';
        if(communityNetworks.size() > 0){
            Network communityNetwork = communityNetworks[0];
            String loginUrl = Network.getLoginUrl(communityNetwork.Id);
            baseUrl = loginUrl.replace('/login', '/s/article/');
        }
        return baseUrl;
    }
    
    public static String summarizeArticleForChatbot(String articleBaseUrl, Knowledge__kav article, String snippet,String searchWord){
        String summary, url;
        url = articleBaseUrl + article.UrlName+'?searchword='+searchWord;
        
        if(snippet != null){
            summary = 'Article : <a href="'+url+'" target="_blank">'+article.Title+'</a>\n \n\n'+snippet+' \n\n-----------------------------------\n\n';
        }/*else{
            summary = 'Article : <a href="'+url+'" target="_blank">'+article.Title+'</a>\n\n-----------------------------------\n\n';
        }*/
        
        return summary;
    }
}