src/objects/Country_Sales_Head__c.object
<CustomObject>
    <fields>
        <fullName>Approver_Name__c</fullName>
        <label>Approver Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Sales__c</fullName>
        <label>Country Sales</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sale_Type__c</fullName>
        <label>Sale Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Emerging BioPharma</fullName>
                </value>
                <value>
                    <fullName>Mid Sized</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country Sales Head</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Country Sales Head Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Sales Heads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_SLT_CountrySalesHead.cls
@isTest
public class TST_SLT_CountrySalesHead {
    
    @testSetup
    static void dataSetup() {
        Country_Sales_Head__c countrySalesHead = UTL_TestData.createCountrySalesHeadData(CON_CPQ.SALE_TYPE_LARGE,CON_CPQ.COUNTRY,CON_CPQ.CUSTOMER_NAME);
        insert countrySalesHead;
    }
    
    @IsTest
    static void testSelectById() {
        Country_Sales_Head__c countrySalesHead = [SELECT Id,Country_Sales__c,Approver_Name__c,Sale_Type__c FROM Country_Sales_Head__c limit 1];	
        List<Country_Sales_Head__c> countrySalesHeadList1 = new SLT_CountrySalesHead().selectById(new Set<Id> {countrySalesHead.Id});
        List<Country_Sales_Head__c> countrySalesHeadList2 = SLT_CountrySalesHead.selectCountrySalesHeadByFilter(countrySalesHead.Sale_Type__c, countrySalesHead.Country_Sales__c, countrySalesHead.Approver_Name__c);
        System.assertEquals(countrySalesHeadList1.size() > 0, true);
        System.assertEquals(countrySalesHeadList2.size() > 0, true);
    }
}