src/objects/CRM_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-MC-ESPSFDCQI-2016 / ESPSFDCQI-16229</description>
    <fields>
        <fullName>Closed_Lost_Opportunity_Email_Recipient__c</fullName>
        <description>ESPSFDCQI-17772</description>
        <inlineHelpText>This Field Hold the Email Address of the User who will receive Email when any Sales/RDS User Opportunity is on  Stage = 7b closed lost with Loss Type = &apos;Loss details to be confirmed&apos; for Last 30 Days</inlineHelpText>
        <label>Closed Lost Opportunity Email Recipient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRM Config</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Last_Modified_By_USER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-9041</description>
        <label>Last Modified By (USER)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunitiesdOFj</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_Quintiles_Opportunity_Number__c</fullName>
        <description>CRM-QI-ESPSFDCQI-314 Opportunity Number of opportunity record in legacy Quintiles org</description>
        <externalId>true</externalId>
        <inlineHelpText>Opportunity Number of opportunity record in legacy Quintiles org</inlineHelpText>
        <label>Legacy Quintiles Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1128 - Indicates which line of business the Opportunity aligns to. Used within the Mulesoft integration.</description>
        <inlineHelpText>Indicates which line of business the Opportunity aligns to.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allscripts Data</fullName>
                </value>
                <value>
                    <fullName>Avacare</fullName>
                </value>
                <value>
                    <fullName>Biosimilars</fullName>
                    <isActive>false</isActive>
                    <label>Biosimilars</label>
                </value>
                <value>
                    <fullName>Biostatistical/Medical Writing</fullName>
                    <isActive>false</isActive>
                    <label>Biostatistical/Medical Writing</label>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Clinical Pharmacology</fullName>
                    <isActive>false</isActive>
                    <label>Clinical Pharmacology</label>
                </value>
                <value>
                    <fullName>Clinical Technology</fullName>
                </value>
                <value>
                    <fullName>Clintec</fullName>
                    <isActive>false</isActive>
                    <label>Clintec</label>
                </value>
                <value>
                    <fullName>Commercial Solutions</fullName>
                </value>
                <value>
                    <fullName>Connected Devices</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Consulting Market Access</fullName>
                </value>
                <value>
                    <fullName>Core Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Core Clinical</label>
                </value>
                <value>
                    <fullName>Data Council</fullName>
                </value>
                <value>
                    <fullName>Data Management</fullName>
                    <isActive>false</isActive>
                    <label>Data Management</label>
                </value>
                <value>
                    <fullName>Data Sciences</fullName>
                </value>
                <value>
                    <fullName>Digital Patient (DPU)</fullName>
                    <isActive>false</isActive>
                    <label>Digital Patient (DPU)</label>
                </value>
                <value>
                    <fullName>DrugDev</fullName>
                    <isActive>false</isActive>
                    <label>DrugDev</label>
                </value>
                <value>
                    <fullName>Early Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Early Clinical</label>
                </value>
                <value>
                    <fullName>Early Clinical Development</fullName>
                </value>
                <value>
                    <fullName>ECG/Cardiac Safety</fullName>
                    <isActive>false</isActive>
                    <label>ECG/Cardiac Safety</label>
                </value>
                <value>
                    <fullName>Evidence Based Medicine (EBM)</fullName>
                </value>
                <value>
                    <fullName>GFR Clinical</fullName>
                    <isActive>false</isActive>
                    <label>GFR Clinical</label>
                </value>
                <value>
                    <fullName>Health Engagement &amp; Communication</fullName>
                </value>
                <value>
                    <fullName>Innovation</fullName>
                </value>
                <value>
                    <fullName>IT Services</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                    <isActive>false</isActive>
                    <label>Lab</label>
                </value>
                <value>
                    <fullName>Lifecycle Safety</fullName>
                    <isActive>false</isActive>
                    <label>Lifecycle Safety</label>
                </value>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Medical Communications</fullName>
                    <isActive>false</isActive>
                    <label>Medical Communications</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1508</description>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Non-competitive bid</fullName>
                </value>
                <value>
                    <fullName>Competitive bid</fullName>
                </value>
                <value>
                    <fullName>Competitive status unknown</fullName>
                </value>
                <value>
                    <fullName>Stopped</fullName>
                </value>
                <value>
                    <fullName>Duplicate Opportunity</fullName>
                </value>
                <value>
                    <fullName>No response</fullName>
                </value>
                <value>
                    <fullName>IQVIA decision not to propose/bid</fullName>
                </value>
                <value>
                    <fullName>Change in client needs or strategy</fullName>
                </value>
                <value>
                    <fullName>Operational Cleaning</fullName>
                </value>
                <value>
                    <fullName>Loss details to be confirmed</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                    <isActive>false</isActive>
                    <label>Lost to Competitor</label>
                </value>
                <value>
                    <fullName>Lost to in-house</fullName>
                    <isActive>false</isActive>
                    <label>Lost to in-house</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lost_Date__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3994</description>
        <label>Lost Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner_Email__c</fullName>
        <description>CRM-MC-ESPSFDCQI-7474</description>
        <formula>Owner.Email</formula>
        <label>Owner Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X7b_Closed_Lost_Stage_Entry__c</fullName>
        <description>MC_CRM_ESPSFDCQI-117_The date the Opportunity moved into the 7b. Closed Lost stage for the first time. This field is updated through the Opportunity trigger.</description>
        <inlineHelpText>The date the Opportunity moved into the 7b. Closed Lost stage for the first time.</inlineHelpText>
        <label>7b. Closed Lost Stage Entry</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BCH_CRM_SendEmailLostfor30days.cls
/*
* Author       : Balkrishan Gohil
* Story        : ESPSFDCQI-17772
* Purpose 1    : Batch to Send Email To Opportunity Owner where Opportunity Owner's Profile Sales/RDS user and Their Opportunity is on Stage = 7b closed lost with Loss Type = 'Loss details to be confirmed'.
*/
global class BCH_CRM_SendEmailLostfor30days implements Database.Batchable<Sobject>,Database.RaisesPlatformEvents {
    
    String query = null;
    public BCH_CRM_SendEmailLostfor30days() {        
    }   
    
    public BCH_CRM_SendEmailLostfor30days(String query) {
        this.query = query;
    }
    /*
     * start method 
     * @params  Database.BatchableContext context
     * @return  Database.QueryLocator
    */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        if(query != null) {
            return Database.getQueryLocator(query);
        } else {
            return Database.getQueryLocator([Select id from User Where Profile.Name IN ('Sales User','RDS User') and IsActive = true]);
        }
    }
    /*
     * Execute method 
     * @params  Database.BatchableContext context
     * 
    */
    global void execute(Database.BatchableContext bc,List<User> userList) { 
        List<Opportunity> userToOpportunityList = [Select id,Name,OwnerId,Owner.Name,Legacy_Quintiles_Opportunity_Number__c,AccountId,Account.Name,Lost_Date__c,Loss_Type__c,StageName,Owner_Email__c,Owner.IsActive,Last_Modified_By_USER__r.Email from Opportunity where StageName = '7b. Closed Lost' AND X7b_Closed_Lost_Stage_Entry__c =: Date.Valueof(System.today().addDays(-30)) AND OwnerId IN : userList AND Loss_Type__c = 'Loss details to be confirmed' AND Line_of_Business__c IN ('Clinical','Clinical Technology','Connected Devices','Data Sciences','Early Clinical Development','Patient & DCT Solutions','Regulatory & Drug Development Solutions','Safety & Med Info')];
        Map<id,List<Opportunity>> userToOpportunityMap = new Map<id,List<Opportunity>>();
        
        if(userToOpportunityList.size() > 0){
            For(Opportunity opp : userToOpportunityList){
                if(!userToOpportunityMap.containsKey(opp.OwnerId)){
                    userToOpportunityMap.put(opp.OwnerId,new List<Opportunity>());
                }
                userToOpportunityMap.get(opp.OwnerId).add(opp);
            }
        }
        
         if(userToOpportunityMap.size() > 0){
            
            List<UTL_CRM_SendEmail.MessageWrapper> messageList = new List<UTL_CRM_SendEmail.MessageWrapper>();
            
            for(Id op : userToOpportunityMap.keyset()){
                Integer i = 1 ;
                String emailBody = '';
                String subject = '';
                List<Opportunity> opp = userToOpportunityMap.get(op);
                if(opp.Size() > 0){
                    UTL_CRM_SendEmail.MessageWrapper message = new UTL_CRM_SendEmail.MessageWrapper();
                    if(opp[0].Owner.IsActive){
                        message.toEmails = new List<String>{opp[0].Owner_Email__c};
                    }else{
                        message.toEmails = new List<String>{opp[0].Last_Modified_By_USER__r.Email};
                    }
                    subject = 'Opportunity Loss details require updating';
                    emailBody = 'Dear '+ opp[0].Owner.Name +'<br/><br/>';
                    emailBody += 'Please can you review the following opportunity(s) and update the Loss details with correct Loss details.<br/><br/>';
                    emailBody += '<table cellspacing="2" cellpadding="3" width="720" align="center" border="1">';     
                    emailBody += '<tr style="text-align:center;border: 0.1px solid black;"><th> Legacy Quintiles Opportunity Number </th><th> Account Name </th><th> Opportunity Name </th><th> Opportunity Stage </th><th> Loss Type </th><th> Loss Date </th><tr>'; 
                    for(Opportunity opps : opp){
                        emailBody += '<tr style="text-align:left;border: 0.1px solid black;"><td>'+ (opps.Legacy_Quintiles_Opportunity_Number__c == Null ? '' : opps.Legacy_Quintiles_Opportunity_Number__c) +'</td><td>'+ '<a href="'+URL.getOrgDomainURL().toExternalForm()+'/'+opps.AccountId+'">'+opps.Account.Name+'</a>' +'</td><td>'+ '<a href="'+URL.getOrgDomainURL().toExternalForm()+'/'+opps.Id+'">'+opps.Name+'</a>'+'</td><td>'+ opps.StageName +'</td><td>'+ opps.Loss_Type__c + '</td><td>'+ String.valueOf(opps.Lost_Date__c) +'<br/></td></tr>';
                    }
                    emailBody +='</table> <br/><br/>';
                    emailBody += 'Thank You';
                    CRM_Config__c csSetting = CRM_Config__c.getOrgDefaults();
                    if(String.isNotBlank(csSetting.Closed_Lost_Opportunity_Email_Recipient__c)){
                        message.ccEmails = new List<String>{csSetting.Closed_Lost_Opportunity_Email_Recipient__c};   
                    }
                    message.subject = subject;
                    message.staticContent = emailBody;
                    messageList.add(message);
                }
            }
            
            if(messageList.size()>0){
                UTL_CRM_SendEmail.sendEmailThroughWorkflow(messageList);
            }
            
        }
        
    }
    
    /*
    * To send emails on exception. This method is called after all batches are processed.
    */
    global void finish(Database.BatchableContext BC) {
    }
}