src/objects/CRM_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-MC-ESPSFDCQI-2016 / ESPSFDCQI-16229</description>
    <fields>
        <fullName>Opportunity_FPI_date__c</fullName>
        <description>ESPSFDCQI-17052</description>
        <label>Opportunity FPI date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Last_Modified_Date__c</fullName>
        <description>ESPSFDCQI-17052</description>
        <label>Opportunity Last Modified Date</label>
        <type>DateTime</type>
    </fields>
    <label>CRM Config</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FPI_Date__c</fullName>
        <description>MC_CRM_ESPSFDCQI-55</description>
        <label>FPI Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legacy_Quintiles_Opportunity_Number__c</fullName>
        <description>CRM-QI-ESPSFDCQI-314 Opportunity Number of opportunity record in legacy Quintiles org</description>
        <externalId>true</externalId>
        <inlineHelpText>Opportunity Number of opportunity record in legacy Quintiles org</inlineHelpText>
        <label>Legacy Quintiles Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1128 - Indicates which line of business the Opportunity aligns to. Used within the Mulesoft integration.</description>
        <inlineHelpText>Indicates which line of business the Opportunity aligns to.</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allscripts Data</fullName>
                </value>
                <value>
                    <fullName>Avacare</fullName>
                </value>
                <value>
                    <fullName>Biosimilars</fullName>
                    <isActive>false</isActive>
                    <label>Biosimilars</label>
                </value>
                <value>
                    <fullName>Biostatistical/Medical Writing</fullName>
                    <isActive>false</isActive>
                    <label>Biostatistical/Medical Writing</label>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Clinical Pharmacology</fullName>
                    <isActive>false</isActive>
                    <label>Clinical Pharmacology</label>
                </value>
                <value>
                    <fullName>Clinical Technology</fullName>
                </value>
                <value>
                    <fullName>Clintec</fullName>
                    <isActive>false</isActive>
                    <label>Clintec</label>
                </value>
                <value>
                    <fullName>Commercial Solutions</fullName>
                </value>
                <value>
                    <fullName>Connected Devices</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Consulting Market Access</fullName>
                </value>
                <value>
                    <fullName>Core Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Core Clinical</label>
                </value>
                <value>
                    <fullName>Data Council</fullName>
                </value>
                <value>
                    <fullName>Data Management</fullName>
                    <isActive>false</isActive>
                    <label>Data Management</label>
                </value>
                <value>
                    <fullName>Data Sciences</fullName>
                </value>
                <value>
                    <fullName>Digital Patient (DPU)</fullName>
                    <isActive>false</isActive>
                    <label>Digital Patient (DPU)</label>
                </value>
                <value>
                    <fullName>DrugDev</fullName>
                    <isActive>false</isActive>
                    <label>DrugDev</label>
                </value>
                <value>
                    <fullName>Early Clinical</fullName>
                    <isActive>false</isActive>
                    <label>Early Clinical</label>
                </value>
                <value>
                    <fullName>Early Clinical Development</fullName>
                </value>
                <value>
                    <fullName>ECG/Cardiac Safety</fullName>
                    <isActive>false</isActive>
                    <label>ECG/Cardiac Safety</label>
                </value>
                <value>
                    <fullName>Evidence Based Medicine (EBM)</fullName>
                </value>
                <value>
                    <fullName>GFR Clinical</fullName>
                    <isActive>false</isActive>
                    <label>GFR Clinical</label>
                </value>
                <value>
                    <fullName>Health Engagement &amp; Communication</fullName>
                </value>
                <value>
                    <fullName>Innovation</fullName>
                </value>
                <value>
                    <fullName>IT Services</fullName>
                </value>
                <value>
                    <fullName>Lab</fullName>
                    <isActive>false</isActive>
                    <label>Lab</label>
                </value>
                <value>
                    <fullName>Lifecycle Safety</fullName>
                    <isActive>false</isActive>
                    <label>Lifecycle Safety</label>
                </value>
                <value>
                    <fullName>Medical Affairs</fullName>
                </value>
                <value>
                    <fullName>Medical Communications</fullName>
                    <isActive>false</isActive>
                    <label>Medical Communications</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Loss_Type__c</fullName>
        <description>CRM-MC-ESPSFDCQI-1508</description>
        <label>Loss Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Non-competitive bid</fullName>
                </value>
                <value>
                    <fullName>Competitive bid</fullName>
                </value>
                <value>
                    <fullName>Competitive status unknown</fullName>
                </value>
                <value>
                    <fullName>Stopped</fullName>
                </value>
                <value>
                    <fullName>Duplicate Opportunity</fullName>
                </value>
                <value>
                    <fullName>No response</fullName>
                </value>
                <value>
                    <fullName>IQVIA decision not to propose/bid</fullName>
                </value>
                <value>
                    <fullName>Change in client needs or strategy</fullName>
                </value>
                <value>
                    <fullName>Operational Cleaning</fullName>
                </value>
                <value>
                    <fullName>Loss details to be confirmed</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                    <isActive>false</isActive>
                    <label>Lost to Competitor</label>
                </value>
                <value>
                    <fullName>Lost to in-house</fullName>
                    <isActive>false</isActive>
                    <label>Lost to in-house</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owner_Email__c</fullName>
        <description>CRM-MC-ESPSFDCQI-7474</description>
        <formula>Owner.Email</formula>
        <label>Owner Email</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BCH_CRM_SendEmailToClosedOpp.cls
/*
* Author       : Balkrishan Gohil
* Story        : ESPSFDCQI-17052
* Purpose 1    : Batch to Send Email To Opportunity Owner where Opportunity is on Stage = 7B. Closed Lost And have FPI Date > Today + 6 Months .
*/
global class BCH_CRM_SendEmailToClosedOpp implements Database.Batchable<Sobject>,Database.Stateful {
    
    private Date highestFpiDate ;
    private DateTime recentLastModifiedDate;
    
    String query = null;
    public BCH_CRM_SendEmailToClosedOpp() {        
    }   
    
    public BCH_CRM_SendEmailToClosedOpp(String query) {
        this.query = query;
    }
    
    /*
     * start method 
     * @params  Database.BatchableContext context
     * @return  Database.QueryLocator
    */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        if(query != null) {
            return Database.getQueryLocator(query);
        } else {
            return Database.getQueryLocator([Select id from User Where Profile.Name IN ('Sales User','RDS User') and IsActive = true]);
        }
    }
    /*
     * Execute method 
     * @params  Database.BatchableContext context
     * 
    */
    global void execute(Database.BatchableContext bc,List<User> userList) {
        Date opp_FPI_Date = CRM_Config__c.getOrgDefaults().Opportunity_FPI_date__c ;
        DateTime opp_Latest_Opp_Modified_Date = CRM_Config__c.getOrgDefaults().Opportunity_Last_Modified_Date__c ;
        if(highestFpiDate == Null){
            highestFpiDate = CRM_Config__c.getOrgDefaults().Opportunity_FPI_date__c;
        }
        if(recentLastModifiedDate == Null){
            recentLastModifiedDate = CRM_Config__c.getOrgDefaults().Opportunity_Last_Modified_Date__c ;
        }
        
        List<Opportunity> userToOppList = new List<Opportunity>();
        Map<Id,List<Opportunity>> userToOppMap = new Map<Id,List<Opportunity>>();
        if(opp_FPI_Date == Null || opp_Latest_Opp_Modified_Date == Null){
            userToOppList = [Select id,FPI_Date__c,LastModifiedDate,Account.Name,Name,Legacy_Quintiles_Opportunity_Number__c,StageName,Owner_Email__c,Owner.Name from Opportunity where StageName = '7b. Closed Lost' AND OwnerId IN : userList AND Line_of_Business__c in ('Clinical','Early Clinical Development','Data Sciences','Safety & Med Info','Patient & DCT Solutions','Regulatory & Drug Development Solutions') AND Loss_Type__c NOT IN ('Operational Cleaning','Duplicate Opportunity') AND FPI_Date__c > NEXT_N_DAYS:180];
        }
        if(opp_FPI_Date != Null && opp_Latest_Opp_Modified_Date != Null){
            userToOppList = [Select id,FPI_Date__c,LastModifiedDate,Account.Name,Name,Legacy_Quintiles_Opportunity_Number__c,StageName,Owner_Email__c,Owner.Name from Opportunity where StageName = '7b. Closed Lost' AND OwnerId IN : userList AND Line_of_Business__c in ('Clinical','Early Clinical Development','Data Sciences','Safety & Med Info','Patient & DCT Solutions','Regulatory & Drug Development Solutions') AND Loss_Type__c NOT IN ('Operational Cleaning','Duplicate Opportunity') AND FPI_Date__c > :opp_FPI_Date AND LastModifiedDate > :opp_Latest_Opp_Modified_Date AND FPI_Date__c > NEXT_N_DAYS:180];
        }

        if(userToOppList.size() > 0){
            For(Opportunity opp : userToOppList){
                if(!userToOppMap.containsKey(opp.OwnerId)){
                    userToOppMap.put(opp.OwnerId,new List<Opportunity>());
                }
                userToOppMap.get(opp.OwnerId).add(opp);
            }
        }
        
        if(userToOppMap.size() > 0){
            
            List<UTL_CRM_SendEmail.MessageWrapper> messageList = new List<UTL_CRM_SendEmail.MessageWrapper>();
            
            for(Id op : userToOppMap.keyset()){
                Integer i = 1 ;
                String emailBody = '';
                String subject = '';
                List<Opportunity> opp = userToOppMap.get(op);
                if(opp.Size() > 0){
                    UTL_CRM_SendEmail.MessageWrapper message = new UTL_CRM_SendEmail.MessageWrapper();
                    message.toEmails = new List<String>{opp[0].Owner_Email__c};
                    subject = 'Opportunity review - Study Progress';
                    emailBody = 'Dear '+ opp[0].Owner.Name +'<br/><br/>';
                    emailBody += 'It is important that we follow up with Customers regarding the opportunities listed below, based on their upcoming FPI date. Please inquire about the progress of the study and offer any assistance that IQVIA can provide to ensure its success. By checking in with the customer, we can demonstrate our commitment to their project, even though it has been lost or stopped and build a stronger relationship with them. Approach the follow-up with a proactive and collaborative mindset, seeking to understand their needs and offering solutions that align with their goals. By doing so, we can position ourselves as a trusted partner and increase the like likelihood of future business opportunities.<br/><br/>';
                    emailBody += '<table cellspacing="2" cellpadding="3" width="720" align="center" border="1">';     
                    emailBody += '<tr style="text-align:center;border: 0.1px solid black;"><th> # </th><th> Account Name </th><th> Opportunity Name </th><th> Legacy Quintiles Opportunity Number </th><th> Opportunity Stage </th><th> FPI Date (DD-MM-YYYY) </th><tr>'; 
                    for(Opportunity opps : opp){
                        if(highestFpiDate == Null){
                            highestFpiDate = opps.FPI_Date__c;
                        }else{
                            highestFpiDate = highestFpiDate < opps.FPI_Date__c ? opps.FPI_Date__c : highestFpiDate ;
                        }
                        if(recentLastModifiedDate == Null){
                            recentLastModifiedDate = opps.LastModifiedDate;
                        }else{
                            recentLastModifiedDate = recentLastModifiedDate < opps.LastModifiedDate ? opps.LastModifiedDate : recentLastModifiedDate ;
                        }
                        DateTime dt = Date.valueOf(opps.FPI_Date__c);
                        String fpiDate = dt.format('dd-MM-YYYY');
                        emailBody += '<tr style="text-align:left;border: 0.1px solid black;"><td>'+ i +'</td><td>' + opps.Account.Name +'</td><td>'+ '<a href="'+URL.getOrgDomainURL().toExternalForm()+'/'+opps.Id+'">'+opps.Name+'</a>'+'</td><td>'+ opps.Legacy_Quintiles_Opportunity_Number__c +'</td><td>'+ opps.StageName + '</td><td>' + fpiDate + '<br/></td></tr>';
                        i++;
                    }
                    emailBody +='</table>';
                    message.subject = subject;
                    message.staticContent = emailBody;
                    messageList.add(message);
                }
            }
            
            if(messageList.size()>0){
                UTL_CRM_SendEmail.MODULE_ALERT_NAME = 'CRM_02_SendEmail';
                UTL_CRM_SendEmail.sendEmailThroughWorkflow(messageList);
            }
            
        }
        
    }
    
    /*
    * To send emails on exception. This method is called after all batches are processed.
    */
    global void finish(Database.BatchableContext BC) {
        CRM_Config__c crmConfigCS = CRM_Config__c.getOrgDefaults();
        if(highestFpiDate != Null){
            crmConfigCS.Opportunity_FPI_date__c = highestFpiDate;
        }
        if(recentLastModifiedDate != Null){
            crmConfigCS.Opportunity_Last_Modified_Date__c = recentLastModifiedDate;   
        }       
        Upsert crmConfigCS CRM_Config__c.Id;
    }
}