src/objects/CSM_QI_Knowledge_Article_Review__c.object
<CustomObject>
    <description>CSM-1892: ALL - KB Periodic revision component</description>
    <fields>
        <fullName>Comment__c</fullName>
        <description>CSM-1892: ALL - KB Periodic revision component</description>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Knowledge Article Reviews</relationshipLabel>
        <relationshipName>Knowledge_Article_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <label>Knowledge Article Review</label>
    <nameField>
        <displayFormat>KAR-{000000000}</displayFormat>
        <label>Article Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Article Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/classes/CNT_CSM_KnowledgeReview.cls
public class CNT_CSM_KnowledgeReview {
    @AuraEnabled
    public static List<CSM_QI_Knowledge_Article_Review__c> getAllKnowledgeReviewList(String articleId){
        List<Knowledge__kav> articleIds = Database.query('SELECT Id, KnowledgeArticleId FROM Knowledge__kav WHERE Id =:articleId LIMIT 1');
        String kaId = null;
        List<CSM_QI_Knowledge_Article_Review__c> karList = new List<CSM_QI_Knowledge_Article_Review__c>();
        if(articleIds != null && !articleIds.isEmpty()){
            for(Knowledge__kav kv : articleIds){
                kaId = kv.KnowledgeArticleId;
            }
            karList = Database.query('SELECT Id,Comment__c,Review_Date__c,CreatedDate,LastModifiedById,LastModifiedBy.Name,LastModifiedBy.FullPhotoUrl,Knowledge__r.VersionNumber FROM CSM_QI_Knowledge_Article_Review__c WHERE Knowledge__r.KnowledgeArticleId = :kaId order by LastModifiedDate desc');
        }
        return karList;
    }
    @AuraEnabled
    public static List<CSM_QI_Knowledge_Article_Review__c> insertKnowledgeReview(String articleId,Date reviewDate,String reviewComment){
                CSM_QI_Knowledge_Article_Review__c kar = new CSM_QI_Knowledge_Article_Review__c(Knowledge__c = articleId, Review_Date__c = reviewDate, Comment__c = reviewComment);
        insert kar;
        return getAllKnowledgeReviewList(articleId);
    }
    
}