src/objects/CSM_QI_Folder_File_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>CSM_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSM-Folder</label>
        <referenceTo>CSM_QI_Folder__c</referenceTo>
        <relationshipLabel>CSM-Folder File Relationship</relationshipLabel>
        <relationshipName>CSM_Folder_File_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Id__c</fullName>
        <label>File Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CSM-Folder File Relationship</label>
    <nameField>
        <displayFormat>CSMFF-{0000000}</displayFormat>
        <label>CSM-Folder File Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSM-Folder File Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CNT_CSM_MikadoFiles.cls
/*
 * Version       : 1.0
 * Description   : Apex Controller for MikadoFiles component.
 */
public with sharing class CNT_CSM_MikadoFiles {
    
    @AuraEnabled
    public static void updateContentFolderMember (String parentContentFolderId, String childRecordId,String csmFolderId ){
       List<ContentFolderMember> cfm = new SLT_ContentFolderMember().selectByChildRecordId(new Set<id> {childRecordId});
        if(cfm != null && !cfm.isEmpty()){
            cfm[0].ParentContentFolderId = parentContentFolderId;
            update cfm;
        }
        
       CSM_QI_Folder_File_Relationship__c ffr = new CSM_QI_Folder_File_Relationship__c();
       ffr.CSM_Folder__c=csmFolderId;
       ffr.File_Id__c=childRecordId;
       insert ffr;
    }
    
    @AuraEnabled
    public static List<ContentFolderMember> getFiles(String csmFolderId ){
        List<CSM_QI_Folder_File_Relationship__c> ffrList = [ select Id, CSM_Folder__c, File_Id__c from CSM_QI_Folder_File_Relationship__c where CSM_Folder__c= :csmFolderId ];
        Set<String> fileIds = new Set<String>();
        for (Integer i=0; i<ffrList.size();i++)
            fileIds.add(ffrList[i].File_Id__c);
        return new SLT_ContentFolderMember().selectByChildRecordId(fileIds);
    }
    
    @AuraEnabled
    public static void deleteContentDocumentById(String contentDocumentId){
        List<CSM_QI_Folder_File_Relationship__c> ffrList = [ select Id, CSM_Folder__c, File_Id__c from CSM_QI_Folder_File_Relationship__c where File_Id__c= :contentDocumentId ];
        delete ffrList[0];
        ContentDocument cd = New ContentDocument (Id=contentDocumentId);
        delete cd;
    }
}