src/objects/CSM_QI_Knowledge_Article_Order__c.object
<CustomObject>
    <fields>
        <fullName>ArticleNumber__c</fullName>
        <label>Article Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Article Order</label>
    <nameField>
        <displayFormat>KAO-{00000}</displayFormat>
        <label>Knowledge Article Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Article Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Article_Chapter__c</fullName>
        <label>Article Chapter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Partner_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pillar__c</fullName>
        <label>Pillar</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pillar</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReviewDate__c</fullName>
        <defaultValue>(Today() + 365)</defaultValue>
        <description>CSM-ACN-S-0047 - Review Date</description>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/objects/Knowledge_Account_RelationShip__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>CSM_QI_KB_Location__c.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CSM_QI_KB_Location__c</referenceTo>
        <relationshipLabel>Knowledge Account RelationShips</relationshipLabel>
        <relationshipName>Knowledge_Account_RelationShips</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Knowledge Account RelationShip</label>
    <nameField>
        <displayFormat>KAR-{0000000}</displayFormat>
        <label>Knowledge Account RelationShip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Account RelationShips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Partner_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Integrator Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Data Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Tech Partner</fullName>
    </customValue>
    <customValue>
        <fullName>CLM Agency</fullName>
    </customValue>
    <customValue>
        <fullName>One Home for Sites</fullName>
    </customValue>
    <customValue>
        <fullName>AMESA - Integrator Partner</fullName>
    </customValue>
    <description>PRM-982: Added two picklist values for Knowledge and CSM Announcement objects.</description>
    <masterLabel>Partner Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Pillar.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Information Offering</fullName>
    </customValue>
    <customValue>
        <fullName>Technology Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>R&amp;D</fullName>
    </customValue>
    <masterLabel>Pillar</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/DAOH_Knowledge.cls
public class DAOH_Knowledge {
    
    public static void addAccountKnowledgeRecord(List<Knowledge__kav> newKnowledgeList){
        set<string> articleNumberSet = new set<string>();
        List<Knowledge_Account_RelationShip__c> newKAccountList =new List<Knowledge_Account_RelationShip__c>();
        Knowledge_Account_RelationShip__c newKAccount;
        for(Knowledge__kav knowId : newKnowledgeList)  {
            articleNumberSet.add(knowId.ArticleNumber);
        }
        List<Knowledge_Account_RelationShip__c> knowledgeAccount = [SELECT id,Account__c, Location__c, Knowledge__r.PublishStatus,Knowledge__r.ArticleNumber FROM Knowledge_Account_RelationShip__c WHERE Knowledge__r.ArticleNumber in: articleNumberSet and Knowledge__r.PublishStatus ='Online'];
        if(knowledgeAccount.size()>0)  {
            for(Knowledge_Account_RelationShip__c knowRelation : knowledgeAccount ){
                for (Knowledge__kav knowledgeRecord : newKnowledgeList){
                    if(knowledgeRecord.PublishStatus == 'Draft')  {
                        newKAccount = new Knowledge_Account_RelationShip__c();
                        newKAccount.Knowledge__c = knowledgeRecord.id;
                        if(knowRelation.Account__c != null)
                            newKAccount.Account__c = knowRelation.Account__c;
                        if(knowRelation.Location__c != null)
                            newKAccount.Location__c = knowRelation.Location__c;
                        newKAccountList.add(newKAccount);
                    }
                }
            }
            if(newKAccountList.size()>0)
                insert newKAccountList;
        } 
    }

    public static void updateVisibleToPartner(List<Knowledge__kav> newKnowledgeList){
        List<Knowledge__kav> knowArticles = new List<Knowledge__kav>();
        Set<String> knowId = new Set<String>();
        String partnerType = 'Integrator Partner;Data Partner;Tech Partner;One Home for Sites;AMESA - Integrator Partner';
        for(Knowledge__kav ka : newKnowledgeList)
        {
            if(ka.IsVisibleInCsp == true && ka.IsVisibleInPrm == false && ka.PublishStatus == 'Draft')
            {
                ka.IsVisibleInPrm = true;
                if(ka.Partner_Type__c == null || ka.Partner_Type__c == '')
                {
                    ka.Partner_Type__c = partnerType;
                }
            }
        
        }
    }
    
    public static void setDefaultValuesinDraftStatus(List<Knowledge__kav> newList){
        for(Knowledge__kav k : newList)  {
            if(k.Pillar__c != null && k.Pillar__c == 'R&D' && k.PublishStatus == 'Draft')  {
                k.ValidationStatus = 'Not Validated';
            }
            k.ReviewDate__c = System.today().addYears(1);
        }
    }

    public static void deleteArticleOrder(List<Knowledge__kav> newList, Map<Id, Knowledge__kav> oldMap) {
        List<String> ArticleNumbers = new List<String>();
        for (Knowledge__kav newRecord : newList) {
            Knowledge__kav oldRecord = oldMap.get(newRecord.Id);
            if (oldRecord != null && oldRecord.Article_Chapter__c != null && oldRecord.Article_Chapter__c != '' && oldRecord.Article_Chapter__c != newRecord.Article_Chapter__c) {
                ArticleNumbers.add(newRecord.ArticleNumber);
            }
        }
        if (!ArticleNumbers.isEmpty()) {
            List<CSM_QI_Knowledge_Article_Order__c> articleOrdersToDelete = [
                SELECT Id
                FROM CSM_QI_Knowledge_Article_Order__c
                WHERE ArticleNumber__c IN :ArticleNumbers
            ];
            
            if (!articleOrdersToDelete.isEmpty()) { 
                delete articleOrdersToDelete;
            }
        }
    }
}