src/objects/Drug_Product__c.object
<CustomObject>
    <description>ESPSFDCQI-12898: This object stores approved and pipeline drugs master data. Data is being pushed from MIDAS and Pipeline databases.</description>
    <fields>
        <fullName>International_Drug_Name__c</fullName>
        <description>ESPSFDCQI-12898</description>
        <label>International Drug Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Drug Product</label>
    <nameField>
        <displayFormat>Drug-  {0000000}</displayFormat>
        <label>Drug Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drug Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_CNT_CRM_AutoCompleteSearch.cls
@isTest
public class TST_CNT_CRM_AutoCompleteSearch {
    
    @isTest
    public static void testFindRecords(){
        Drug_Product__c DrugProduct = UTL_TestData.createDrugProducts();
        insert DrugProduct;
        
        Test.startTest();
        List<sobject> result = CNT_CRM_AutoCompleteSearch.findRecords('','Drug_Product__c', 'International_Drug_Name__c', 'Name, International_Drug_Name__c', '30');
        System.assertEquals(true,result.size() > 0);
        result = CNT_CRM_AutoCompleteSearch.findRecords('Molecule_Name','Drug_Product__c', 'International_Drug_Name__c', 'Name, International_Drug_Name__c', '30');
        Test.stopTest();
    }
}