src/objects/Event_Journals__c.object
<CustomObject>
    <description>IQVIAPSA-4469</description>
    <fields>
        <fullName>Active__c</fullName>
        <description>IQVIAPSA-4469</description>
        <label>Active?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>IQVIAPSA-4469</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Initial_Search_Started__c</fullName>
        <description>IQVIAPSA-4469</description>
        <label>Date Initial Search Started</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Last_Journal_Search_was_Performed__c</fullName>
        <description>IQVIAPSA-4469</description>
        <label>Date Last Journal Search was Performed</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Next_Journal_Search_is_Due__c</fullName>
        <description>IQVIAPSA-4469</description>
        <label>Date Next Journal Search is Due</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency_of_Journal__c</fullName>
        <description>IQVIAPSA-4469</description>
        <label>Frequency of Journal</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bi-Annual (Twice a year)</fullName>
                </value>
                <value>
                    <fullName>Bi-Monthly (Every two months)</fullName>
                </value>
                <value>
                    <fullName>Bi-Weekly (Every two weeks)</fullName>
                </value>
                <value>
                    <fullName>Every 9 Months</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Yearly (Annual)</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Journal_Name__c</fullName>
        <description>IQVIAPSA-4469</description>
        <label>Journal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>IQVIAPSA-4469</description>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Event Journals</label>
    <nameField>
        <label>Unique ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LR_Event_Journals_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Event_Journals_M__c</fullName>
        <label>Event Journals</label>
        <referenceTo>Event_Journals__c</referenceTo>
        <relationshipLabel>LR Event Journals Relationship</relationshipLabel>
        <relationshipName>LR_Event_Journals_Relationship</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LR Event Journals Relationship</label>
    <nameField>
        <label>LR Event Journals Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LR Event Journals Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CNT_PSA_Event_Journals_ListView.cls
public class CNT_PSA_Event_Journals_ListView {
    
    @AuraEnabled(cacheable=true)
    public static List<Event_Journals__c> getEventJournalData(String recordId){
        Set<String> lrEjFieldSet = new Set<String>{'Id', 'Event_Journals_M__c'};
        Set<Id> lridSet = new Set<Id>();
        lridSet.add(recordId);
        List<LR_Event_Journals_Relationship__c> lrEjList = new SLT_LR_Event_Journals_Relationship().getLREJRelationshipFromLrId(lridSet, lrEjFieldSet);
        Set<Id> eventJournalIdSet = new Set<Id>();
        for(LR_Event_Journals_Relationship__c lrEjRec : lrEjList){
            eventJournalIdSet.add(lrEjRec.Event_Journals_M__c);
        }
        Set<String> ejFieldSet = new Set<String>{'Id', 'Name', 'Country__c', 'Journal_Name__c', 'URL__c', 'Frequency_of_Journal__c', 'Date_Initial_Search_Started__c', 'Date_Last_Journal_Search_was_Performed__c', 'Date_Next_Journal_Search_is_Due__c', 'Active__c'};
        return new SLT_Event_Journals().getEventJournalsByIds(eventJournalIdSet, ejFieldSet);
    }
    @AuraEnabled(cacheable=false)
    public static String getEventJournalDataForView( String recordId, Integer pageSize, Integer pageNumber, Integer totalRecords ){
       String jsonObjItm = '';
        Set<String> lrEjFieldSet = new Set<String>{'Id', 'Event_Journals_M__c'};
        Set<Id> lridSet = new Set<Id>();
        lridSet.add(recordId);
        List<LR_Event_Journals_Relationship__c> lrEjList = new SLT_LR_Event_Journals_Relationship().getLREJRelationshipFromLrId(lridSet, lrEjFieldSet);
        Set<Id> eventJournalIdSet = new Set<Id>();
        for(LR_Event_Journals_Relationship__c lrEjRec : lrEjList){
            eventJournalIdSet.add(lrEjRec.Event_Journals_M__c);
        }
        
        Set<String> ejFieldSet = new Set<String>{'Id', 'Name', 'Country__c', 'Journal_Name__c', 'URL__c', 'Frequency_of_Journal__c', 'Date_Initial_Search_Started__c', 'Date_Last_Journal_Search_was_Performed__c', 'Date_Next_Journal_Search_is_Due__c', 'Active__c','LastModifiedDate'};
        Integer offset = (pageNumber - 1) * pageSize;  
        
        if( totalRecords == 0 ){
         	totalRecords = [SELECT COUNT() FROM Event_Journals__c WHERE Id =: eventJournalIdSet];
        }
        Integer recordEnd = pageSize * pageNumber;
       	EventItemWrapper ejObj =  new EventItemWrapper();  
        ejObj.pageNumber = pageNumber;
        ejObj.pageSize = pageSize;        
        ejObj.recordStart = offset + 1;
        ejObj.recordEnd = totalRecords >= recordEnd ? recordEnd : totalRecords;
        ejObj.totalRecords = totalRecords;
        ejObj.eventJournals = new SLT_Event_Journals().getEventJournalsByIdsForPagination(eventJournalIdSet, ejFieldSet,pageSize,offset );
        jsonObjItm = JSON.serialize(ejObj);
        return jsonObjItm;
    }
    public class EventItemWrapper {       
        public Integer recordStart {get;set;}
        public Integer pageNumber {get;set;}
        public Integer totalRecords {get;set;}
        public Integer recordEnd {get;set;}
        public Integer pageSize {get;set;}       
        public List<Event_Journals__c> eventJournals {get;set;}
    }
}