src/objects/IMS_Use_Offering_Atypical_Combination__c.object
<CustomObject>
    <fields>
        <fullName>Offering_Category__c</fullName>
        <description>Category of the selected offering.</description>
        <formula>TEXT( Offering_Name__r.Geo_Level__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Category of the selected offering.</inlineHelpText>
        <label>Offering Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offering_Country_del__c</fullName>
        <label>Offering Country</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offering_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offering Name</label>
        <referenceTo>IMS_Data_Asset__c</referenceTo>
        <relationshipLabel>IMS Use Offering Atypical Combinations</relationshipLabel>
        <relationshipName>IMS_Use_Offering_Atypical_Combinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Offering_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Offering Name</label>
        <referenceTo>IMS_Secondary_Data_Asset__c</referenceTo>
        <relationshipLabel>IMS Use Offering Atypical Combinations</relationshipLabel>
        <relationshipName>IMS_Use_Offering_Atypical_Combinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Use Category</label>
        <referenceTo>TPA_Purpose_Category__c</referenceTo>
        <relationshipLabel>IMS Use Offering Atypical Combinations</relationshipLabel>
        <relationshipName>IMS_Use_Offering_Atypical_Combinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Use Name</label>
        <referenceTo>IMS_TPA_Purpose__c</referenceTo>
        <relationshipLabel>IMS Use Offering Atypical Combinations</relationshipLabel>
        <relationshipName>IMS_Use_Offering_Atypical_Combinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>IMS Use Offering Atypical Combination</label>
    <nameField>
        <displayFormat>UseOffComb-{0000}</displayFormat>
        <label>IMS Use Offering Atypical Combination Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMS Use Offering Atypical Combinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SLT_IMSUseOfferingAtypicalCombination.cls
/*
 * Version       : 1.0
 * Description   : Selector Class for IMS_Use_Offering_Atypical_Combination__c
 */
public class SLT_IMSUseOfferingAtypicalCombination extends fflib_SObjectSelector {    
    /**
     * This method used to get field list of sobject
     * @return  List<Schema.SObjectField>
     */
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            IMS_Use_Offering_Atypical_Combination__c.Id,
            IMS_Use_Offering_Atypical_Combination__c.Use_Category__c,
            IMS_Use_Offering_Atypical_Combination__c.Use_Name__c,
            IMS_Use_Offering_Atypical_Combination__c.Offering_Country_del__c,
            IMS_Use_Offering_Atypical_Combination__c.Offering_Category__c, 
            IMS_Use_Offering_Atypical_Combination__c.Offering_Name__c,
            IMS_Use_Offering_Atypical_Combination__c.Secondary_Offering_Name__c, 
            IMS_Use_Offering_Atypical_Combination__c.isActive__c
        };
    }

    /**
     * This method used to set up type of sobject
     * @return  Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return IMS_Use_Offering_Atypical_Combination__c.sObjectType;
    }

    /**
     * This method used to get all IMS_Use_Offering_Atypical_Combinations
     * @return  List<IMS_Use_Offering_Atypical_Combination__c>
     */
    public List<IMS_Use_Offering_Atypical_Combination__c> selectAllAtypicalUseOffComb(Set<String> fieldSet) {
        return (List<IMS_Use_Offering_Atypical_Combination__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).toSOQL());
    }

    public static SLT_IMSUseOfferingAtypicalCombination instance {
        get {
            if(instance == null) {
                instance = new SLT_IMSUseOfferingAtypicalCombination();
            }
            return instance;
        }
        set;
    }
}