src/objects/Investigator_Grant__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-2952</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Investigator Grants</relationshipLabel>
        <relationshipName>Bid_History_Investigator_Grants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Investigator Grant</label>
    <nameField>
        <displayFormat>IG-{000000}</displayFormat>
        <label>Investigator Grants names</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigator Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OWF_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>OWF-MC-ESPSFDCQI-2183-Holds config and default values for OWF globally</description>
    <label>OWF Config</label>
</CustomObject>

src/objects/pse__Grp__c.object
<CustomObject>
    <customHelpPage>pse__GroupHelp</customHelpPage>
    <description>An entity that usually represents a functional business area or business vertical. Groups are organized as an independent hierarchy determined by the Parent Group field, with parent and child records of the same type. Every group in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Permission_Control__c.object
<CustomObject>
    <customHelpPage>pse__PermissionControlHelp</customHelpPage>
    <description>Grants a set of stand-alone or cascading permissions to a single Salesforce user, with reference to either a resource, region, practice, group, or project. Controls whether the user can carry out specific processes including: logging time on behalf of other resources, entering expenses, staffing, and viewing and editing projects in Project Task Gantt and Gantt.</description>
    <label>Permission Control</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Permission Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permission Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_TGR_Investigator_Grant.cls
/**
* This test class is used to test all methods in Investigator Grant trigger.
* version : 1.0
*/
@isTest
public class TST_TGR_Investigator_Grant {
    /**
    * This method is used to setup data for all methods.
    */
    @testSetup
    static void dataSetup() 
	{
        Account acc = UTL_OWF_TestData.createAccount();
        insert acc;
        pse__Grp__c grp = UTL_OWF_TestData.createGroup();
        insert grp;
        OWF_Config__c owfConfig = UTL_OWF_TestData.createOWFConfig(grp.Id);
        insert owfConfig;
        pse__Permission_Control__c permissionControlGroup = UTL_OWF_TestData.createPermissionControl(null, null, grp, null);
        insert permissionControlGroup;
        Opportunity opp = UTL_OWF_TestData.createOpportunity(acc.Id);
        insert opp;
        Bid_History__c bidHistory = UTL_OWF_TestData.createBidHistoryByRecordType(acc.Id, opp.Id, CON_OWF.OWF_CLINICAL_BID_BID_HISTORY_RECORD_TYPE_ID);
        insert bidHistory; 
    }
    
	
    /**
    * This test method used for insert and update opportunity record
    */ 
    static testMethod void testInvestigatorGrantInsert() 
	{   
        Bid_History__c bidHistory =[Select id from Bid_History__c limit 1];
        Test.startTest();
        Investigator_Grant__c investigatorGrantRecord = UTL_OWF_TestData.createInvestigatorGrantByBidHistory(bidHistory.id);
        insert investigatorGrantRecord;
		Test.stopTest();
		Integer expected = 1;
        Integer actual = [Select id from Investigator_Grant__c].size();
        system.assertEquals(expected, actual);
    }

}