src/objects/Log_History__c.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Detail__c</fullName>
        <label>Log Detail</label>
        <length>32765</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <label>Log_Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NONE</fullName>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                    <default>true</default>
                    <label>DEBUG</label>
                </value>
                <value>
                    <fullName>FINE</fullName>
                </value>
                <value>
                    <fullName>FINER</fullName>
                </value>
                <value>
                    <fullName>FINEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Log_Module__c</fullName>
        <label>Log_Module</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CDA</fullName>
                </value>
                <value>
                    <fullName>CLM</fullName>
                </value>
                <value>
                    <fullName>CPQ</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>CRM(UK)</fullName>
                </value>
                <value>
                    <fullName>CSM</fullName>
                </value>
                <value>
                    <fullName>OWF</fullName>
                </value>
                <value>
                    <fullName>PRM</fullName>
                </value>
                <value>
                    <fullName>PSA</fullName>
                </value>
                <value>
                    <fullName>RWAS</fullName>
                </value>
                <value>
                    <fullName>SCM</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>DEVOPS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log History</label>
    <nameField>
        <displayFormat>LH-{000000000}</displayFormat>
        <label>Log History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Log_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Log_Data_to_keep_for__c</fullName>
        <description>Number of Days you want to keep data created from today (prior data will be deleted by old logs cleanup batch)</description>
        <inlineHelpText>Number of Days you want to keep data created from today (prior data will be deleted by old logs cleanup batch)</inlineHelpText>
        <label>Log Data to keep for</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Severity_Level__c</fullName>
        <description>Severity Level can be between {NONE, ERROR, WARN, INFO, DEBUG, FINE, FINER, FINEST}</description>
        <inlineHelpText>Severity Level can be between {NONE, ERROR, WARN, INFO, DEBUG, FINE, FINER, FINEST}</inlineHelpText>
        <label>Severity Level</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Log Setting</label>
</CustomObject>

src/classes/TST_UTL_LogFactory.cls
@isTest
public class TST_UTL_LogFactory { 
    @testSetup
    static void setupTestData() {
        insert new Log_Setting__c(Name = 'TPA', Log_Data_to_keep_for__c = 6, Severity_Level__c = 'DEBUG');
    }
    
    public static testMethod void testMethod1() {
        Log_History__c tstLog = new Log_History__c(Log_Module__c = 'TPA', Log_Level__c = 'DEBUG', GUID__c = UTL_LogFactory.Guid, Log_Detail__c = 'Test');
        
        UTL_LogFactory.instance.getLogInstance();
        UTL_LogFactory.getLogLst();
        UTL_LogFactory.resetLogList();
        UTL_LogFactory.saveLogs(tstLog, false);
        tstLog.Id = null;
        UTL_LogFactory.saveLogs(new List<Log_History__c>{tstLog}, false);
        UTL_LogFactory.generateAndCommitLog(true, false, UTL_LogFactory.Guid, 'Test', 'TPA', null, 'DEBUG', 'otherDetails', null);
        tstLog.Id = null;
        UTL_LogFactory.commitLogsAsync(JSON.serialize(New List<Log_History__c>{tstLog}), true);
        tstLog.Id = null;
        UTL_LogFactory.commitLogsAsync(JSON.serialize(tstLog), false);
        tstLog.GUID__c = null;
        UTL_LogFactory.saveLogs(tstLog, false);
        tstLog.GUID__c = UTL_LogFactory.Guid;
        tstLog.Log_Detail__c = null;
        UTL_LogFactory.saveLogs(tstLog, false);
        tstLog.Log_Detail__c = 'Test';
        tstLog.Log_Module__c = null;
        UTL_LogFactory.isValidLog(tstLog);
        tstLog.Log_Module__c = 'TPA';
        tstLog.Log_Level__c = null;
        UTL_LogFactory.saveLogs(tstLog, false);
        UTL_LogFactory.saveLogs(new List<Log_History__c>{tstLog}, false);
    }
}