src/objects/MIBNF2__c.object
<CustomObject>
    <fields>
        <fullName>BNF_Status__c</fullName>
        <description>CRM-MC-ESPSFDCQI-8412</description>
        <label>BNF Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Multi Invoice BNF</label>
    <nameField>
        <displayFormat>MIBNF-{000000}</displayFormat>
        <label>MIBNF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Multi Invoice BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MIBNF_Component__c.object
<CustomObject>
    <description>Multi Invoice BNF Component which is child BNF for an Opportunity</description>
    <fields>
        <fullName>BNF_Status__c</fullName>
        <label>BNF Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Accrual</fullName>
                </value>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>SAP Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Created</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Confirmed</fullName>
                </value>
                <value>
                    <fullName>LO Accepted</fullName>
                </value>
                <value>
                    <fullName>LO Rejected</fullName>
                </value>
                <value>
                    <fullName>RA Accepted</fullName>
                </value>
                <value>
                    <fullName>RA Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Pending</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MIBNF__c</fullName>
        <description>This Relationship maintain all child BNF connected to one Master Multi Invoice BNF Object which is also child of single Opportunity.</description>
        <label>MIBNF</label>
        <referenceTo>MIBNF2__c</referenceTo>
        <relationshipName>MIBNF_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BNF</label>
    <nameField>
        <label>BNF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MI_BNF_Header_Ex.cls
public with sharing class MI_BNF_Header_Ex {
    
    
    public MIBNF2__c MIBNF;
    public Boolean IsEditable = true;
    public Boolean UserIsSysAdmin {get;private set;}
    public Boolean ErrorFlag{get;private set;}
    private Boolean hasAccessBNFAll;
     
    public MI_BNF_Header_Ex (ApexPages.StandardController controller) 
    { 
        IsEditable = true;
        this.hasAccessBNFAll = false;
        List<PermissionSetAssignment> permSetAssList = [SELECT Id, PermissionSet.Name, AssigneeId FROM PermissionSetAssignment WHERE AssigneeId = :Userinfo.getUserId() and  PermissionSet.Name = 'Modify_all_privileges_on_BNF'];
        if(permSetAssList.size() > 0) {
            hasAccessBNFAll = true; 
        }
        ErrorFlag=false;
        MIBNF = (MIBNF2__c)controller.getRecord();
        User CurrentUser = [select Id,Profile.Name from User where Id = :userInfo.getUserId()];
        this.UserIsSysAdmin = CurrentUser.Profile.Name.toUpperCase().contains('SYSTEM ADMINISTRATOR');         
		Set<Id> MIBNF_Comp_Id_Set = new Set<Id>();
        for (MIBNF_Component__c MIBNF_Comp:[Select Id,BNF_Status__c From MIBNF_Component__c where MIBNF__c=:MIBNF.Id])
        {
            MIBNF_Comp_Id_Set.add(MIBNF_Comp.Id);            
        }       
        //  Check for any pending approvals on any of the child MIBNF's
        List<ProcessInstanceWorkitem> P_list = new List<ProcessInstanceWorkitem>([select Id, ProcessInstance.Id, ProcessInstance.TargetObjectId, ActorId from ProcessInstanceWorkitem  where ProcessInstance.Status = 'Pending' and ProcessInstance.TargetObjectId in :MIBNF_Comp_Id_Set]);
        if (P_list.size() > 0)         
             IsEditable = false;
        //  If any of the child MIBNF's is assigned to the current user, allow them to edit
        for (ProcessInstanceWorkitem P:P_list)
        {
        	if (P.ActorId == userInfo.getUserId())
        		IsEditable = true;
        }
               
    }
    
    // Prevent user from editing Header Details if any child BNF in Approval Stage
    public Pagereference Redirect()
    {
             
         if (!IsEditable && !UserIsSysAdmin && !hasAccessBNFAll)
         {
             ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Multi Invoice Header cannot be edited once related BNF\'s have been approved.');
             ApexPages.addMessage(errMsg); 
             ErrorFlag=true;
         }
        return null;         
    }
    
    // Cancel Action
    public Pagereference Cancel()
    {
         pageReference retURL=new pageReference(ApexPages.currentPage().getParameters().get('retURL'));
         return retURL;
         
     }
}