src/objects/MIBNF_Component__c.object
<CustomObject>
    <description>Multi Invoice BNF Component which is child BNF for an Opportunity</description>
    <fields>
        <fullName>MIBNF__c</fullName>
        <description>This Relationship maintain all child BNF connected to one Master Multi Invoice BNF Object which is also child of single Opportunity.</description>
        <label>MIBNF</label>
        <referenceTo>MIBNF2__c</referenceTo>
        <relationshipName>MIBNF_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BNF</label>
    <nameField>
        <label>BNF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>BNF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BNF</label>
        <referenceTo>BNF2__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIBNF_Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIBNF Component</label>
        <referenceTo>MIBNF_Component__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIBNF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MIBNF</label>
        <referenceTo>MIBNF2__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <recordTypes>
        <fullName>BNF_Note</fullName>
        <active>true</active>
        <label>BNF Note</label>
    </recordTypes>
    <recordTypes>
        <fullName>MIBNF_Component_Note</fullName>
        <active>true</active>
        <label>MIBNF Component Note</label>
    </recordTypes>
    <recordTypes>
        <fullName>MIBNF_Note</fullName>
        <active>true</active>
        <label>MIBNF Note</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EXT_CRM_Note_Detail.cls
public class EXT_CRM_Note_Detail {
    
    Note__c noteRecord;
    Id redirectId;
    public String noteRecordType{get;private set;}
    
    public EXT_CRM_Note_Detail(ApexPages.StandardController controller) {
        this.noteRecord = (Note__c)controller.getRecord();
        this.noteRecordType = ApexPages.currentPage().getParameters().get('recordType');
        this.redirectId = ApexPages.currentPage().getParameters().get('redirectId');
        if(noteRecord.Id == null) {
            if(noteRecordType == 'BNF_Note') {
                noteRecord.BNF__c = this.redirectId;
            } else if(noteRecordType == 'MIBNF_Note') {
                noteRecord.MIBNF__c = this.redirectId;
            } else if(noteRecordType == 'MIBNF_Component_Note') {
                noteRecord.MIBNF_Component__c = this.redirectId;
            }
            noteRecord.recordTypeId = Schema.SObjectType.Note__c.getRecordTypeInfosByDeveloperName().get(noteRecordType).getRecordTypeId();
        } else {
            this.noteRecordType = Schema.SObjectType.Note__c.getRecordTypeInfosById().get(noteRecord.recordtypeid).getDeveloperName(); 
            if(noteRecordType == 'BNF_Note') {
                this.redirectId = noteRecord.BNF__c; 
            } else if(noteRecordType == 'MIBNF_Note') {
                this.redirectId = noteRecord.MIBNF__c;
            } else if(noteRecordType == 'MIBNF_Component_Note') {
                this.redirectId = noteRecord.MIBNF_Component__c;
            }
        }
    }
    public PageReference Save() {
        upsert this.noteRecord;
        return new PageReference('/' +  this.redirectId);
    }
    public PageReference Cancel() {
        return new PageReference('/' +  this.redirectId);
    }
}