src/objects/MIBNF2__c.object
<CustomObject>
    <fields>
        <fullName>Addendum__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates that this is an add-on to a previously &quot;In Hand&quot; opportunity where a BNF had been submitted and approved.</inlineHelpText>
        <label>Revised BNF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BNF_Status__c</fullName>
        <description>CRM-MC-ESPSFDCQI-8412</description>
        <label>BNF Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>MIBNFS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the name of the Revenue Analyst who will be processing the BNF.</inlineHelpText>
        <label>Revenue Analyst</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Revenue_Analyst__c.Available_for_Selection__c</field>
                <operation>equals</operation>
                <value>TRUE</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>$Source.MIBNF_Status__c</field>
                <operation>notEqual</operation>
                <value>New</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Revenue_Analyst__c</referenceTo>
        <relationshipName>R00NT0000001UO6hMAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Multi Invoice BNF</label>
    <nameField>
        <displayFormat>MIBNF-{000000}</displayFormat>
        <label>MIBNF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Multi Invoice BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MIBNF_Component__c.object
<CustomObject>
    <description>Multi Invoice BNF Component which is child BNF for an Opportunity</description>
    <fields>
        <fullName>Addendum__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates that this is an add-on to a previously &quot;In Hand&quot; opportunity where a MIBNF had been submitted and approved.</inlineHelpText>
        <label>Revised BNF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BNF_Status__c</fullName>
        <label>BNF Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Accrual</fullName>
                </value>
                <value>
                    <fullName>Addendum</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>SAP Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Created</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Confirmed</fullName>
                </value>
                <value>
                    <fullName>LO Accepted</fullName>
                </value>
                <value>
                    <fullName>LO Rejected</fullName>
                </value>
                <value>
                    <fullName>RA Accepted</fullName>
                </value>
                <value>
                    <fullName>RA Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Pending</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Rejected</fullName>
                </value>
                <value>
                    <fullName>SAP Contract Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MIBNF__c</fullName>
        <description>This Relationship maintain all child BNF connected to one Master Multi Invoice BNF Object which is also child of single Opportunity.</description>
        <label>MIBNF</label>
        <referenceTo>MIBNF2__c</referenceTo>
        <relationshipName>MIBNF_Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BNF&apos;s</relationshipLabel>
        <relationshipName>BNF_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Analyst__c</fullName>
        <formula>MIBNF__r.Revenue_Analyst__r.User__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue Analyst</label>
        <type>Text</type>
    </fields>
    <label>BNF</label>
    <nameField>
        <label>BNF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BNF&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Revenue_Analyst__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-3168 - This custom object is used to store the Revenue Analyst.</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N70000001hwojEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Analyst</label>
    <nameField>
        <label>Revenue Analyst Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Analysts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MI_BNF_Comp_Submit_Approval.cls
public with sharing class MI_BNF_Comp_Submit_Approval {
    //  -------------------------------------------------------------------------------
    //  Member variables
    //  -------------------------------------------------------------------------------
   
    public MIBNF_Component__c MIBNF_Comp{get;private set;}
    public Boolean errorFlag{get;private set;}
    public Boolean errorFlagID{get;private set;}
    
    //  -------------------------------------------------------------------------------
    //  Constructor function
    //  -------------------------------------------------------------------------------   
     public MI_BNF_Comp_Submit_Approval () 
    {       
            String msgText='';
             //  Issue-09971
            MIBNF_Comp=[Select name,MIBNF__r.Opportunity__c,MIBNF__r.Revenue_Analyst__c,  MIBNF__r.Revenue_Analyst__r.Name, MIBNF__r.Revenue_Analyst__r.User__c,MIBNF__r.Revenue_Analyst__r.User__r.name,Addendum__c,BNF_Status__c,MIBNF__r.Opportunity__r.StageName From MIBNF_Component__c where id=:ApexPages.currentPage().getParameters().get('id') limit 1];
            
    }
    
    public PageReference cancel()
    {
            PageReference oppView;
            if(MIBNF_Comp.id!=null)
            {
               oppView = new PageReference('/apex/MI_BNF_View?id=' + MIBNF_Comp.MIBNF__c);
            }
           
            oppView.setRedirect(true);
            return oppView;
    } 
    
     //submit BNF for approval 
     public PageReference SubmitRequest()
     {
           PageReference oppView = null;
           
           //Processing request          
           try {
                Approval.ProcessSubmitRequest request=new Approval.ProcessSubmitRequest();
                request.setObjectId(MIBNF_Comp.Id);
                //  Issue-09971
                request.setComments('BNF submitted to ' + MIBNF_Comp.MIBNF__r.Revenue_Analyst__r.Name);
                Approval.ProcessResult result = Approval.process(request);
                errorFlag=false;
                oppView = new PageReference('/apex/MI_BNF_View?id=' + MIBNF_Comp.MIBNF__c);      
                oppView.setRedirect(true);
                                  
             }
            catch(Exception e)
            {
                errorFlag=true;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            }
          
            return oppView;
     }
}