src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <description>CRM-MC-ESPSFDCQI-927 - A unique opportunity number to identify the opportunity.</description>
        <label>Opportunity Number</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Renewal_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Task</label>
        <referenceTo>Renewal_Task__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I&amp;A</fullName>
                </value>
                <value>
                    <fullName>C&amp;S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Dashboard_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Cloning_Batch_Size__c</fullName>
        <description>This field is used to manage batch size in OpportunityRenewals_CloningScheduler class</description>
        <inlineHelpText>This field is used to manage batch size in OpportunityRenewals_CloningScheduler class</inlineHelpText>
        <label>Cloning Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Year__c</fullName>
        <label>Renewal Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Renewal Dashboard Settings</label>
</CustomObject>

src/objects/Renewal_Task__c.object
<CustomObject>
    <description>Object to hold dashboard data for opportunity clone enhancements.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Tasks</relationshipLabel>
        <relationshipName>Renewal_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal Task</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Renewal Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_EXT_CRM_OpportunityRenewals_AddDBOpp.cls
/**
* This class is the implementation of 'Add Opp' button on the DB.
*
* Date : 19th Oct, 2010.
* Author : Metacube Software Ltd.
*/
@isTest
private class TST_EXT_CRM_OpportunityRenewals_AddDBOpp {
    private static testmethod void testAddOppController(){
        Test.startTest();
        Account testAcc = UTL_CRM_OpportunityRenewalTestData.setupAccount('Detail Controller Account');
        List<Opportunity> oppList = UTL_CRM_OpportunityRenewalTestData.setupOpportunity(testAcc , 1);
        //List<Renewal_Task__c> rtList = UTL_CRM_OpportunityRenewalTestData.setupRenewalTasks(testAcc , 1);
        
        System.assertEquals(1, oppList.size());
        
        Renewal_Dashboard_Settings__c RDSetting = new Renewal_Dashboard_Settings__c();
        RDSetting.Cloning_Batch_Size__c = 5	;
        RDSetting.Renewal_Year__c = 2017;
        insert RDSetting; 
        
        //ApexPages.currentPage().getParameters().put('id' ,rtList[0].id );
        EXT_CRM_OpportunityRenewals_AddDBOpp sc = new EXT_CRM_OpportunityRenewals_AddDBOpp();
        sc.oppId = oppList[0].id;
        sc.addDBOpportunity();
        
        System.assertEquals(true, sc.isAddSuccessful );        
        Test.stopTest();
    }
    
    private static testmethod void testAddOppControllerNegative(){
        Test.startTest();
        Account testAcc = UTL_CRM_OpportunityRenewalTestData.setupAccount('Detail Controller Account');
        String standardPricebookId =Test.getStandardPricebookId();
        Product2 prod = UTL_CRM_OpportunityRenewalTestData.getProdRecord();
        prod.Business_Type__c = 'I&A';
        prod.CanUseRevenueSchedule=true;
        insert prod;
        
        PricebookEntry PE1 = UTL_CRM_OpportunityRenewalTestData.getPbEntryRecord(prod);
        PE1.IsActive = true;
        PE1.CurrencyIsoCode = 'USD';
        insert PE1;   
        
        //List<Opportunity> oppList = UTL_CRM_OpportunityRenewalTestData.setupOpportunity(testAcc , 1);
        List<Renewal_Task__c> rtList = UTL_CRM_OpportunityRenewalTestData.setupRenewalTasks(testAcc , 1);
        
        System.assertEquals(1, rtList.size());
        //ApexPages.currentPage().getParameters().put('id' ,rtList[0].id );
        EXT_CRM_OpportunityRenewals_AddDBOpp sc = new EXT_CRM_OpportunityRenewals_AddDBOpp();
        sc.oppId = rtList [0].Opportunity__c;
        sc.addDBOpportunity();
        
        System.assertEquals(false, sc.isAddSuccessful );        
        Test.stopTest();
    }
    
    private static testmethod void testSearchOpportunity () {
        Test.startTest();
        Account testAcc = UTL_CRM_OpportunityRenewalTestData.setupAccount('Detail Controller Account');
        List<Opportunity> oppList = UTL_CRM_OpportunityRenewalTestData.setupOpportunity(testAcc , 1);
        
        System.assertEquals(1, oppList.size());
        EXT_CRM_OpportunityRenewals_AddDBOpp sc = new EXT_CRM_OpportunityRenewals_AddDBOpp();
        //empty search string test
        sc.searchOppNum = '';
        sc.doSearch();
        System.assertEquals(true, sc.resultOppList == null ); 
        String oppNum = [SELECT ID, Opportunity_Number__c from Opportunity where id =: oppList[0].id limit 1].Opportunity_Number__c;
        System.debug('oppNum = ' + oppNum );
        sc.searchOppNum = oppNum ;
        System.debug('sc.searchOppNum = ' + sc.searchOppNum );
        sc.doSearch();
        System.debug('oppList[0].Opportunity_Number__c = ' + oppList[0].Opportunity_Number__c);
        System.debug('sc.resultOppList = ' + sc.resultOppList );
        //sosl queries do not return any results in test methods
        //http://www.salesforce.com/us/developer/docs/apexcode/Content/apex_testing_SOSL.htm
        System.assertEquals(true, sc.resultOppList.size()!= null );    
        Test.stopTest();
    }

}