src/objects/Package_License_Configuration__mdt.object
<CustomObject>
    <fields>
        <fullName>Package_License_Name__c</fullName>
        <label>Package License Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retain_License__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retain License</label>
        <type>Checkbox</type>
    </fields>
    <label>Package License Configuration</label>
    <pluralLabel>Package License Configurations</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <description>ESPSFDCQI-2350 Timestamp of most recent user activation date</description>
        <label>Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Active_Inactive_Reason__c</fullName>
        <description>SFDCDEVOPS-467 Added a new picklist value to identify the Infrequent user deactivation.</description>
        <label>Active/Inactive Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New User</fullName>
                </value>
                <value>
                    <fullName>Reactivation</fullName>
                </value>
                <value>
                    <fullName>Deactivation (Inactivity)</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
                <value>
                    <fullName>Other (Manual Deactivation)</fullName>
                </value>
                <value>
                    <fullName>Deactivation (Infrequent User)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Infrequent_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SFDCDEVOPS-467 : Infrequent users are the ones who don’t need salesforce access on daily basis and login once in a week or every 2 week.

These users are identified based on login pattern and number of times their account deactivated and reactivated in the past.</description>
        <label>Infrequent User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Excluded_From_Deactivation_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CRM-MC-ESPSFDCQI-6059</description>
        <label>Is Excluded From Deactivation Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_License_Type__c</fullName>
        <description>MC-CRM-ESPSFDCQI-1512 -</description>
        <formula>Profile.UserLicense.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User License Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User_Activation_Input_Variables__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SFDCDEVOPS-472 Input Variables used in apex class for the business logic.</description>
    <fields>
        <fullName>Allowed_Reactivation__c</fullName>
        <description>Number of reactivations allowed to become an infrequent user. If this number is higher than 2 then user will be marked as Infrequent user at the time of deactivation.</description>
        <label>Allowed Reactivation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Activation Input Variables</label>
</CustomObject>

src/objects/User_Audit_Log__c.object
<CustomObject>
    <description>ESPSFDCQI-4835</description>
    <fields>
        <fullName>Active_Inactive_Reason__c</fullName>
        <description>SFDCDEVOPS-467 Added a new picklist value to identify the infrequent user deactivation.</description>
        <label>Active/Inactive Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New User</fullName>
                </value>
                <value>
                    <fullName>Reactivation</fullName>
                </value>
                <value>
                    <fullName>Deactivation (Inactivity)</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
                <value>
                    <fullName>Other (Manual Deactivation)</fullName>
                </value>
                <value>
                    <fullName>Deactivation (Infrequent User)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <label>New Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Audit_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Audit Log</label>
    <nameField>
        <label>User Audit Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Downgrade_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CRM-MC-ESPSFDCQI-6059</description>
    <fields>
        <fullName>Activation_Date_Duration_in_Days__c</fullName>
        <description>CRM-MC-ESPSFDCQI-6059</description>
        <label>Activation Date Duration in Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Login_Duration_in_Days__c</fullName>
        <description>CRM-MC-ESPSFDCQI-6059</description>
        <label>Last Login Duration in Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notification_emails__c</fullName>
        <description>CRM-MC-ESPSFDCQI-6059</description>
        <label>Notification emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_ID_to_be_excluded__c</fullName>
        <description>CRM-MC-ESPSFDCQI-6059</description>
        <label>Profile ID to be excluded</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Ids__c</fullName>
        <description>CRM-MC-ESPSFDCQI-6059</description>
        <label>User Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_License_type_to_be_Included__c</fullName>
        <description>CRM-MC-ESPSFDCQI-6059</description>
        <label>User License type to be Included</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Downgrade Setting</label>
</CustomObject>

src/classes/BCH_CRM_DowngradeUserLicence.cls
/**
* Batch to deactivate the Users
*/ 
public class BCH_CRM_DowngradeUserLicence implements Database.Batchable<Sobject>,Database.Stateful {
    public List<String> errorMsgList;
    public List<String> exceptionList;
    public Boolean isValidQuery = true;
    public Set<Id> removeLicenceUserId;
    //SFDCDEVOPS-834: packageLicenseExcludedSet for storing Package licenses that should be excluded.   
    public Set<String> packageLicenseExcludedSet;
    public BCH_CRM_DowngradeUserLicence(){
        errorMsgList = new List<String>();
        exceptionList = new List<String>(); 
        removeLicenceUserId = new Set<Id>();
        packageLicenseExcludedSet = new Set<String>();
    }
    public Database.QueryLocator start(Database.BatchableContext context) {
        Set<String> profileIdExcludedSet = new Set<String>();
        Set<String> userLicenceIncludedSet = new Set<String>();
        Set<String> userIdSet = new Set<String>();
        User_Downgrade_Setting__c userDownCs = User_Downgrade_Setting__c.getInstance();
        Organization org = [SELECT IsSandbox FROM Organization];
        String query = 'SELECT Id, Name, firstName, lastName, EmployeeNumber, Profile.Name, User_License_Type__c, IsActive FROM User WHERE';
        query += ' IsActive = true AND Is_Excluded_From_Deactivation_Process__c = false';

        //SFDCDEVOPS-834 Adding Package Licenses to set through Custom Metadata that should be excluded
        Map<String, Package_License_Configuration__mdt> packageLicenseMd = Package_License_Configuration__mdt.getAll();
        if(packageLicenseMd != null) {
            for(String packageLicenseRec : packageLicenseMd.keySet()) {
                Boolean retainLicense = packageLicenseMd.get(packageLicenseRec).Retain_License__c;
                if(retainLicense) {
                    packageLicenseExcludedSet.add(packageLicenseMd.get(packageLicenseRec).Package_License_Name__c);
                }
            }
        }
        if (userDownCs != null) {
            if (userDownCs.Profile_ID_to_be_excluded__c != null) {
                profileIdExcludedSet.addAll((userDownCs.Profile_ID_to_be_excluded__c).split(','));
            }
            if (userDownCs.User_License_type_to_be_Included__c != null) {
                userLicenceIncludedSet.addAll((userDownCs.User_License_type_to_be_Included__c).split(','));
            }
            if(userDownCs.Activation_Date_Duration_in_Days__c != null && userDownCs.Last_Login_Duration_in_Days__c != null) {
                query += ' AND ProfileId NOT IN :profileIdExcludedSet AND User_License_Type__c IN :userLicenceIncludedSet';
                query += ' AND (Activation_Date__c < LAST_N_DAYS:'+ Integer.valueOf(userDownCs.Activation_Date_Duration_in_Days__c) + ')';
                query += ' AND (LastLoginDate < LAST_N_DAYS:' + Integer.valueOf(userDownCs.Last_Login_Duration_in_Days__c) + ' OR LastLoginDate = null)';
            } else {
                isValidQuery = false;
            }
            if (org.IsSandbox || Test.isRunningTest()) {
                if (userDownCs.OrgId__c == null) {
                    if (userDownCs.User_Ids__c != null) {
                        userIdSet.addAll((userDownCs.User_Ids__c).split(','));
                        query += ' AND Id IN :userIdSet';
                    } else {
                        isValidQuery = false;
                    }
                } else {
                    if(userDownCs.OrgId__c != UserInfo.getOrganizationId()){
                        isValidQuery = false;
                    }
                }
            }
        } else {
            isValidQuery = false;
        }
        if(Test.isRunningTest() || !isValidQuery){
            query += ' LIMIT 1';
        }
        System.debug(query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext context, List<User> records) {
        User_Activation_Input_Variables__c userConfig = User_Activation_Input_Variables__c.getValues('BusinessLogic');
        integer allowedReactivation = Integer.valueOf(userConfig.Allowed_Reactivation__c);
        
        // Set of users, who can be marked as Infrequent users.
        Set<Id> infrequentsUsers = new Set<Id>(New Map<Id, AggregateResult>([SELECT User__r.id, count(id) FROM User_Audit_Log__c WHERE User__c IN : records AND Field_Name__c = 'IsActive' AND New_Value__c = 'true' GROUP BY User__r.id HAVING COUNT(id) > : allowedReactivation]).keySet());

        if (isValidQuery) {
            for (User user : records) {
                user.IsActive = false;
                user.Active_Inactive_Reason__c = 'Deactivation (Inactivity)';
                // Need to be revised*.
                if(infrequentsUsers.contains(user.id)) {
                    user.Infrequent_User__c = true;
                }
                removeLicenceUserId.add(user.Id);
            }
            try {  
                List<Database.SaveResult> saveResultList = Database.update(records, false);
                for(integer i =0; i<records.size();i++){
                    String msg = '';
                    If(!saveResultList[i].isSuccess()){
                        msg += records.get(i).firstName+' '+records.get(i).lastName;
                        msg +=' (SFDC Id: '+ records.get(i).id+' Employee Number '+records.get(i).EmployeeNumber+ ' ) ' 
                            +'\n'+'Error: "';        
                        for(Database.Error err: SaveResultList[i].getErrors()){  
                            msg += err.getmessage()+'"\n\n';
                        }
                    }
                    if(msg!='')
                        errorMsgList.add(msg);
                }
            } catch (Exception exp) {
                String exceptionMsg ='While deactivating users:-'+'\n';
                for(User u : records){
                    exceptionMsg += u.firstName+' '+u.lastName+'(SFDC Id: '+u.id+')'+'\n';
                }
                exceptionMsg  +='\n Some Exception Occurred As Follows:'+'\n';
                exceptionList.add(ExceptionMsg); 
            }
        }
    }
    
    public void finish(Database.BatchableContext BC){
        List<String> toAddresses = new List<String>();
        User_Downgrade_Setting__c userDownCs = User_Downgrade_Setting__c.getInstance();
        Set<String> notificationEmailSet = new Set<String>();
         //SFDCDEVOPS-834:Calling this method for removing package license after user deactivation
        if(removeLicenceUserId.size() > 0) {
            if(!packageLicenseExcludedSet.isEmpty()) {
                removePackageLicenseOfDeactivatedUser(removeLicenceUserId, packageLicenseExcludedSet);
            }
            else {
                removePackageLicence(removeLicenceUserId);
            }
        }

        if (userDownCs != null) {
            if (userDownCs.Notification_emails__c != null) {
                notificationEmailSet.addAll((userDownCs.Notification_emails__c).split(','));
                for(String email : notificationEmailSet){
                    toAddresses.add(email);
                }
                if (isValidQuery) {
                    if(errorMsgList.size()>0){  
                        sendMailOnError(errorMsgList, toAddresses);
                    }
                    else if(exceptionList.size()>0){
                        sendMailOnException(exceptionList, toAddresses);
                    }
                } else {
                    String exceptionMsg ='While deactivating users:- Custom Setting (User Downgrade Setting) data is corrupted.'+'\n';
                    exceptionList.add(ExceptionMsg);
                    sendMailOnException(exceptionList, toAddresses);
                }       
            }
        }
    }
    
    public static void removePackageLicence(Set<Id> removeLicenceUserId){
        List<UserPackageLicense> userPackageLicense = [Select Id, UserId from UserPackageLicense Where UserId IN :removeLicenceUserId];
        List<UserPackageLicense> updatePakage = new List<UserPackageLicense>();
        if(userPackageLicense.size() > 0) {
            for(UserPackageLicense userLic : userPackageLicense) {
                updatePakage.add(userLic);
            }
        }
        
        if(updatePakage.size() > 0) {   
            delete updatePakage;
        }
    }

    //SFDCDEVOPS-834 : Method defined for removing package licenses for deactivated users excluding (packageLicenseExcludedSet)
    public static void removePackageLicenseOfDeactivatedUser(Set<Id> removeLicenceUserId, Set<String> packageLicenseExcludedSet){
        //SFDCDEVOPS-834: Retrieve the UserPackageLicense records to be revoked from user excluding (packageLicenseExcludedSet).
        List<UserPackageLicense> userPackageLicense = [Select Id, UserId from UserPackageLicense Where UserId IN :removeLicenceUserId AND Packagelicense.Namespaceprefix NOT IN:packageLicenseExcludedSet];
        List<UserPackageLicense> updatePakage = new List<UserPackageLicense>();
        if(userPackageLicense.size() > 0) {
            for(UserPackageLicense userLic : userPackageLicense) {
                updatePakage.add(userLic);
            }
        }
        
        if(updatePakage.size() > 0) {    
            delete updatePakage;
        }
    }

    
    public static void sendMailOnException(List<String> exception_List,List<String> toAddresses){
        String bodyText = '';
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddresses);     
        mail.setSubject('Exceptions were thrown while Deactivating Users');                       
        bodyText  +='==============Exception========\n'; 
        for(String exp : exception_List){              
            bodyText += exp;      
        }               
        mail.setPlainTextBody(bodyText);  
        try{
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(Exception e) {
            System.debug('Email Failed: ' + e.getMessage());
        }          
    }
    
    public static void sendMailOnError(List<String> Error_msg_List,List<String> toAddresses){
        String bodyText ;
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddresses);       
        mail.setSubject('Error : Deactivating '+Error_msg_List.size()+' user(s) who are not logged in for specified number of days.');            
        bodyText = '';
        bodyText += '***********************************************'+'\n';   
        bodyText += Error_msg_List.size()+' '+'USER(S) COULD NOT BE DEACTIVATED '+'\n';         
        bodyText += '***********************************************'+'\n';
        bodyText += '==  Errors encountered while deactivating users who are not logged in for specified number of days.  =='+'\n\n';
        for(integer i =0 ; i<Error_msg_List.size();i++ ){   
            bodyText += i+1 + '.';
            bodyText += Error_msg_List.get(i) + '\n';                
        }  
        mail.setPlainTextBody(BodyText);  
        try{
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch(Exception e) {
            System.debug('Email Failed: ' + e.getMessage());
        }                 
    }
}