src/objects/PC_Pricing_Calculator__x.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-806 - External object for Legacy IMS Pricing Assistant custom object.</description>
    <externalDataSource>Legacy_IMS</externalDataSource>
    <externalName>PC_Pricing_Calculator__c</externalName>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>CRM-MC-ESPSFDCQI-824</description>
        <externalDeveloperName>Opportunity__c</externalDeveloperName>
        <label>Opportunity</label>
        <length>18</length>
        <referenceTargetField>Opportunity.LI_Opportunity_Id__c</referenceTargetField>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pricing Assistants</relationshipLabel>
        <relationshipName>Pricing_Assistants</relationshipName>
        <type>IndirectLookup</type>
    </fields>
    <label>Pricing Assistant</label>
    <pluralLabel>Pricing Assistants</pluralLabel>
</CustomObject>

src/classes/SLT_PricingAssistant.cls
public class SLT_PricingAssistant extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>();
    }
    public SLT_PricingAssistant() {
        super(true, false, false);
    }
    public Schema.SObjectType getSObjectType() {
        return PC_Pricing_Calculator__x.sObjectType;
    }
    public static List<PC_Pricing_Calculator__x> getPricingAssistantRecord(String oppId){
        return [SELECT Id FROM PC_Pricing_Calculator__x WHERE  Opportunity__c = :oppId];
    }
}