src/objects/Product_Group_Relationship__c.object
<CustomObject>
    <description>Used to store relation between Products and Collaboration groups</description>
    <fields>
        <fullName>Collaboration_Group_Id__c</fullName>
        <description>Used to store related collaboration group Id</description>
        <label>Collaboration Group Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Group Relationships</relationshipLabel>
        <relationshipName>Product_Group_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Group Relationship</label>
    <nameField>
        <label>Product Group Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Group Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SLT_ProductGroupRelationship.cls
/*
 * Version       : 1.0
 * Description   : This Apex class is selector layer for Product_Group_Relationship__c
 */
public without sharing class SLT_ProductGroupRelationship extends fflib_SObjectSelector  {
    /**
* This method used to get field list of sobject
* @return  List<Schema.SObjectField>
*/
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Product_Group_Relationship__c.Product__c,
            Product_Group_Relationship__c.Name,
            Product_Group_Relationship__c.Id,
            Product_Group_Relationship__c.Collaboration_Group_Id__c
        };
    }
    
    /**
     * This method used to set up type of sobject
     * @return  Schema.SObjectType
     */
    public Schema.SObjectType getSObjectType() {
        return Product_Group_Relationship__c.sObjectType;
    }
    
    /**
     * This method used to get Product_Group_Relationship__c by Id
     * @return  List<Product_Group_Relationship__c>
     */
    public List<Product_Group_Relationship__c> selectById(Set<ID> idSet) {
        return (List<Product_Group_Relationship__c>) selectSObjectsById(idSet);
    }
    
    /**
    * This method used to get listsof Product_Group_Relationship__c
    * @return  list
    */
    public List<Product_Group_Relationship__c> getProductRelationships(Set<String> fields, String condition) {
        fflib_QueryFactory factory = newQueryFactory(true);
        factory.selectFields(fields);

        if(!String.isBlank(condition)) {
            factory.setCondition(condition);
        }
        return Database.query(factory.toSOQL());
    }
}