src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>I&amp;A</fullName>
                </value>
                <value>
                    <fullName>C&amp;S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Task__c.object
<CustomObject>
    <description>Object to hold dashboard data for opportunity clone enhancements.</description>
    <fields>
        <fullName>Cloned_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Newly cloned opportunity as a result of execution of renewal task.</description>
        <label>Cloned Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Tasks (Cloned Opportunity)</relationshipLabel>
        <relationshipName>Renewal_Tasks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cloning_Status__c</fullName>
        <label>Cloning Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Renewal Tasks</relationshipLabel>
        <relationshipName>Renewal_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal Task</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Renewal Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_EXT_CRM_OpportunityRenewal_PDetail.cls
@isTest
private class TST_EXT_CRM_OpportunityRenewal_PDetail {
    private static testmethod void testRenewalTaskDetailWrapper(){
        EXT_CRM_OpportunityRenewal_PDetail.RenewalTaskDetailWrapper wr = new EXT_CRM_OpportunityRenewal_PDetail.RenewalTaskDetailWrapper(null, null);
        System.assert(wr.isShown == false);
    
    }
    
    private static testmethod void testDetailController(){
        Account testAcc = UTL_CRM_OpportunityRenewalTestData.setupAccount('Detail Controller Account');
        
        String standardPricebookId =Test.getStandardPricebookId();
        Product2 prod = UTL_CRM_OpportunityRenewalTestData.getProdRecord();
        prod.Business_Type__c = 'I&A';
        prod.CanUseRevenueSchedule=true;
        insert prod;
        
        PricebookEntry PE1 = UTL_CRM_OpportunityRenewalTestData.getPbEntryRecord(prod);
        PE1.IsActive = true;
        PE1.CurrencyIsoCode = 'USD';
        insert PE1;
        
        List<Renewal_Task__c> rtList = UTL_CRM_OpportunityRenewalTestData.setupRenewalTasks(testAcc , 1);
        
        System.assertEquals(1, rtList.size());
        ApexPages.currentPage().getParameters().put('id' ,rtList[0].id );
        ApexPages.StandardController sc = new ApexPages.StandardController(rtList[0]);
        
        EXT_CRM_OpportunityRenewal_PDetail detailController = new EXT_CRM_OpportunityRenewal_PDetail(sc);
        
        System.assertEquals(1, detailController.rtdWrappperList.size());
        detailController.saveProducts();
        
        System.assertEquals(detailController.rt.Cloning_Status__c, CON_CRM_OpportunityRenewals.QUEUED_STATUS_STR);
        
    }
    
    private static testmethod void testDropAllProductsForlone(){
        Account testAcc = UTL_CRM_OpportunityRenewalTestData.setupAccount('Detail Controller Account');
        
        String standardPricebookId =Test.getStandardPricebookId();
        Product2 prod = UTL_CRM_OpportunityRenewalTestData.getProdRecord();
        prod.Business_Type__c = 'I&A';
        prod.CanUseRevenueSchedule=true;
        insert prod;
        
        PricebookEntry PE1 = UTL_CRM_OpportunityRenewalTestData.getPbEntryRecord(prod);
        PE1.IsActive = true;
        PE1.CurrencyIsoCode = 'USD';
        insert PE1;
        
        List<Renewal_Task__c> rtList = UTL_CRM_OpportunityRenewalTestData.setupRenewalTasks(testAcc , 1);
        
        System.assertEquals(1, rtList.size());
        ApexPages.currentPage().getParameters().put('id' ,rtList[0].id );
        ApexPages.StandardController sc = new ApexPages.StandardController(rtList[0]);
        
        EXT_CRM_OpportunityRenewal_PDetail detailController = new EXT_CRM_OpportunityRenewal_PDetail(sc);    
        //set rtdWrappperList with empty list.
        List<EXT_CRM_OpportunityRenewal_PDetail.RenewalTaskDetailWrapper> ob = new List<EXT_CRM_OpportunityRenewal_PDetail.RenewalTaskDetailWrapper > ();
        detailController.saveProducts();       
        try{
            detailController.rt.Cloned_Opportunity__c =null;
            detailController.rt.Opportunity__c = null ;
            detailController.saveProducts();
        }catch(Exception e){
            
        }
        
    }
    
    private static testmethod void testDetailControllerException(){
        Account testAcc = UTL_CRM_OpportunityRenewalTestData.setupAccount('Detail Controller Account');
        
        String standardPricebookId =Test.getStandardPricebookId();
        Product2 prod = UTL_CRM_OpportunityRenewalTestData.getProdRecord();
        prod.Business_Type__c = 'I&A';
        prod.CanUseRevenueSchedule=true;
        insert prod;
        
        PricebookEntry PE1 = UTL_CRM_OpportunityRenewalTestData.getPbEntryRecord(prod);
        PE1.IsActive = true;
        PE1.CurrencyIsoCode = 'USD';
        insert PE1;
        
        List<Renewal_Task__c> rtList = UTL_CRM_OpportunityRenewalTestData.setupRenewalTasks(testAcc , 1);
     
        System.assertEquals(1, rtList.size());
        ApexPages.currentPage().getParameters().put('id' ,rtList[0].id );
        ApexPages.StandardController sc = new ApexPages.StandardController(rtList[0]);
        
        EXT_CRM_OpportunityRenewal_PDetail detailController = new EXT_CRM_OpportunityRenewal_PDetail(sc);  
        detailController.rtdWrappperList.clear();
        //set rtdWrappperList with empty list.
        //List<EXT_CRM_OpportunityRenewal_PDetail.RenewalTaskDetailWrapper> ob = new List<EXT_CRM_OpportunityRenewal_PDetail.RenewalTaskDetailWrapper > ();
        detailController.saveProducts();
        
        System.assertEquals(detailController.rt.Cloning_Status__c, CON_CRM_OpportunityRenewals.QUEUED_STATUS_STR); 
    }
}