src/objects/PSA_Metric__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>PSA-CLD-USNONE - The date this metric becomes effective
            Reference ID used by external systems</description>
        <externalId>true</externalId>
        <inlineHelpText>Reference ID used by external systems</inlineHelpText>
        <label>External ID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSA_Metric_Unique_ID__c</fullName>
        <description>PSA-CLD-USNONE - Unique ID to allow for updates</description>
        <displayFormat>{0000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>PSA-CLD-USNONE - Unique ID to allow for updates</inlineHelpText>
        <label>PSA Metric Unique ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Related ServiceLine</description>
        <label>Service Line</label>
        <referenceTo>Service_Line__c</referenceTo>
        <relationshipName>Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Related service</description>
        <inlineHelpText>Related service</inlineHelpText>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Service__c.Service_Line__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Line__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>PSA Metrics</relationshipLabel>
        <relationshipName>PSA_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Metric</label>
    <nameField>
        <label>PSA Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSA Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PSA_Metric_Issue__c.object
<CustomObject>
    <description>PSA-CLD-IQVIAPSA-1292 A junction object that connects PSA Metrics with particular services to be validated when saving deliverables. Causes issue to be generated when validations fail.</description>
    <fields>
        <fullName>PSA_Metric__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-IQVIAPSA-1292 Which PSA Metric to use for validating the deliverable</description>
        <label>PSA Metric</label>
        <referenceTo>PSA_Metric__c</referenceTo>
        <relationshipLabel>PSA Metric Issues</relationshipLabel>
        <relationshipName>PSA_Metric_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <description>PSA-CLD-IQVIAPSA-1292 PSA/GRA Metric Issue Configuration</description>
        <formula>Service__r.Service_Code__c</formula>
        <label>Service Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <formula>PSA_Metric__r.Service_Line__c</formula>
        <label>Service Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-IQVIAPSA-1292 Optionally limit application of metric validations to deliverables of this service</description>
        <inlineHelpText>Optionally limit this validation to one service, instead of applying to all deliverables beneath the PSA Metric&apos;s Service Line.</inlineHelpText>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>PSA Metric Issues</relationshipLabel>
        <relationshipName>PSA_Metric_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PSA Metric Issue</label>
    <nameField>
        <displayFormat>PMV-{0000}</displayFormat>
        <label>PSA Metric Isue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSA Metric Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Service_Code__c</fullName>
        <description>PSA-CLD-USNONE - Service Code</description>
        <externalId>true</externalId>
        <label>Service Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Service Line</description>
        <label>Service Line</label>
        <referenceTo>Service_Line__c</referenceTo>
        <relationshipLabel>Service Lines</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Line__c.object
<CustomObject>
    <fields>
        <fullName>Service_Line_Code__c</fullName>
        <description>PSA-CLD-USNONE - Unique code used by the system for lookups</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique code used by the system for lookups</inlineHelpText>
        <label>Service Line Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_SLT_PSA_Metric_Issue.cls
/*
* TST_SLT_PSA_Metric_Issue
*
* Providing proofs for the SLT_PSA_Metric_Issue
*/
@isTest
private class TST_SLT_PSA_Metric_Issue 
{
    
    @testSetup
    static void setupTestData(){
        Service_Line__c serviceLine = new Service_Line__c(
            Name='Test Service Line',
            Service_Line_Code__c='87654321');
        insert serviceLine;

        Service__c service = new Service__c(
            Name = 'Test Service',
            Service_Code__c = '12345678',
            Service_Line__c = serviceLine.Id);
        insert service;

        PSA_Metric__c metric = new PSA_Metric__c(
            Name='Test Metric',
            //PSA_Metric_Unique_ID__c='1111',
            External_ID__c='1111',
            Service_Line__c=serviceLine.Id
        );
        insert metric;
	
        PSA_Metric_Issue__c issue1 = new PSA_Metric_Issue__c(
            Service__c=service.Id,
            PSA_Metric__c=metric.Id);
        insert issue1;

        PSA_Metric_Issue__c issue2 = new PSA_Metric_Issue__c(
            PSA_Metric__c=metric.Id);
        insert issue2;
    }
    
    
    @isTest
    static void testGetSObjectFieldList() {
        Test.startTest();
        List<Schema.SObjectFIeld> fields = new SLT_PSA_Metric_Issue(true).getSObjectFieldList();
        Test.stopTest();
        System.assertNotEquals(0,fields.size());
    }

    @isTest
    static void testSelectByServiceLine(){
        //setupTestData();
        Service_Line__c serviceLine =  [Select Id, Name from Service_Line__c where Name ='Test Service Line'];
        Test.startTest();
        List<PSA_Metric_Issue__c> issues = new SLT_PSA_Metric_Issue(false).selectByServiceLine(serviceLine.Id, new Set<String>{'Id'});
        Test.stopTest();
        System.assertEquals(1,issues.size());
    }

    @isTest
    static void testSelectByService(){
        //setupTestData();
        Service__c service = [Select Id, Name from Service__c where Name ='Test Service'];
        Test.startTest();
        List<PSA_Metric_Issue__c> issues = new SLT_PSA_Metric_Issue().selectByService(service.Id, new Set<String>{'Id'});
        Test.stopTest();
        System.assertEquals(1,issues.size());
    }

    /*
    static Service_Line__c serviceLine;
    static Service__c service;
    static void setupTestData(){

        serviceLine = new Service_Line__c(
            Name='Test Service Line',
            Service_Line_Code__c='87654321');
        insert serviceLine;

        service = new Service__c(
            Name = 'Test Service',
            Service_Code__c = '12345678',
            Service_Line__c = serviceLine.Id);
        insert service;

        PSA_Metric__c metric = new PSA_Metric__c(
            Name='Test Metric',
            //PSA_Metric_Unique_ID__c='1111',
            External_ID__c='1111',
            Service_Line__c=serviceLine.Id
        );
        insert metric;

        PSA_Metric_Issue__c issue1 = new PSA_Metric_Issue__c(
            Service__c=service.Id,
            PSA_Metric__c=metric.Id);
        insert issue1;

        PSA_Metric_Issue__c issue2 = new PSA_Metric_Issue__c(
            PSA_Metric__c=metric.Id);
        insert issue2;
    }
	*/
}