src/objects/pse__Resource_Request__c.object
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Bid_History_Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CON_CBEx.cls
/**
 * This class used for constants used in CBEx project.
 * version : 1.0
 */
public class CON_CBEx {
    // This is all ProfileName Constant
    public static final String RDS_User = 'RDS User';
    public static final String administrator = 'Administrator';
    public static final String administratorSupport = 'IQVIA Salesforce Platform Support';
    public static final String Marketing_User_IQVIA = 'Marketing User IQVIA';
	public static final String ACCOUNT_OBJECT = 'Account';
    public static final String OPPORTUNITY_OBJECT = 'Opportunity';
    public static final String BIDHISTORY_OBJECT = 'Bid_History__c';
    public static final String RESOURCE_REQUEST_OBJECT = 'pse__Resource_Request__c';
    public static final String MULESOFT_SYNC_STATUS_PENDING = 'Pending';
}