src/objects/pse__Assignment__c.object
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Bid_History_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Resource_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Resource Request Lookup populated only when assignment is created from a resource request.</description>
        <label>Resource Request</label>
        <referenceTo>pse__Resource_Request__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Proj__c.object
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 Creating Bid History lookup for OWF Process</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Bid_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Bid</fullName>
        <active>true</active>
        <description>OWF-MC-ESPSFDCQI-2160</description>
        <label>Bid</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Resource_Request__c.object
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <fields>
        <fullName>Bid_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>OWF - IQVIAPSA-3950 - Lookup to Bid History</description>
        <label>Bid History</label>
        <referenceTo>Bid_History__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Bid_History_Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>pse__Assignment__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QBL_OWF_DeletionLogic.cls
/**
* This class contains Queuable Sub Class 
*/
public class QBL_OWF_DeletionLogic {
    
    /**
     * This queuable sub class delete Agreement
     */
    public class QueueAgreementDeletion implements Queueable {
        public List<Bid_History__c> deletedAgreementList{get;set;}
        public Map<Id, String> agreementIdToErrorMessageMap{get;set;}
        public QueueAgreementDeletion(List<Bid_History__c> recordList){
            deletedAgreementList = recordList;
            agreementIdToErrorMessageMap = new Map<Id, String>();
        }
        /**
     	* This overridden method used to deletion Agreement 
     	*/ 
        public void execute(QueueableContext context) {
            //delete deletedAgreementList;
            Database.DeleteResult[] drList = Database.delete(deletedAgreementList, false);
            if (drList.size() > 0){
                for (Integer i=0; i< drList.size(); i++){
                    if (!drList[i].isSuccess()){
                        agreementIdToErrorMessageMap.put(deletedAgreementList[i].Id, 'Error in Agreement deletion through queuable job: ' + drList[i].getErrors()[0].getMessage());
                    }
                }
            }
            
            if (agreementIdToErrorMessageMap.size() > 0 || Test.isRunningTest()){
                UTL_OWF.createApexErrorLogs('Bid/Agreement (Bid_History__c)', 'Error in Agreement deletion through queuable job: ', agreementIdToErrorMessageMap);
            }
        }
    }
    
    /**
     * This queuable sub class delete Project
     */
    public class QueueProjectDeletion implements Queueable{
        public List<pse__Proj__c> deletedProjectList{get;set;}
        public Map<Id, String> projectIdToErrorMessageMap{get;set;}
        public QueueProjectDeletion(List<pse__Proj__c> recordList){
            deletedProjectList = recordList;
            projectIdToErrorMessageMap = new Map<Id, String>();
        }
        /**
     	* This overridden method used to deletion Project 
     	*/ 
        public void execute(QueueableContext context) {
            //delete deletedProjectList;
            Database.DeleteResult[] drList = Database.delete(deletedProjectList, false);
            if (drList.size() > 0){
                for (Integer i=0; i< drList.size(); i++){
                    if (!drList[i].isSuccess()){
                        projectIdToErrorMessageMap.put(deletedProjectList[i].Id, 'Error in Project deletion through queuable job: ' + drList[i].getErrors()[0].getMessage());
                    }
                }
            }
            
            if (projectIdToErrorMessageMap.size() > 0 || Test.isRunningTest()){
                UTL_OWF.createApexErrorLogs('Project (pse__Proj__c)', 'Error in Project deletion through queuable job: ', projectIdToErrorMessageMap);
            }
        }
    }
    
    /**
     * This queuable sub class delete Resource Request
     */
    public class QueueResourceRequestDeletion implements Queueable{
        public List<pse__Resource_Request__c> deletedResourceRequestList{get;set;}
        public Map<Id, String> resourceRequestIdToErrorMessageMap{get;set;}
        public QueueResourceRequestDeletion (List<pse__Resource_Request__c> recordList){
            deletedResourceRequestList = recordList;
            resourceRequestIdToErrorMessageMap = new Map<Id, String>();
        }
        /**
     	* This overridden method used to deletion Resource Request 
     	*/ 
        public void execute(QueueableContext context) {
            //delete deletedResourceRequestList;
            Database.DeleteResult[] drList = Database.delete(deletedResourceRequestList, false);
            if (drList.size() > 0){
                for (Integer i=0; i< drList.size(); i++){
                    if (!drList[i].isSuccess()){
                        resourceRequestIdToErrorMessageMap.put(deletedResourceRequestList[i].Id, 'Error in Resource Request deletion through queuable job: ' + drList[i].getErrors()[0].getMessage());
                    }
                }
            }
            
            if (resourceRequestIdToErrorMessageMap.size() > 0 || Test.isRunningTest()){
                UTL_OWF.createApexErrorLogs('Resource Request (pse__Resource_Request__c)', 'Error in Resource Request deletion through queuable job: ', resourceRequestIdToErrorMessageMap);
            }
        }
    }
    
    /**
     * This queuable sub class delete Opportunity
     */
    public class QueueOpportunityDeletion implements Queueable{
        public List<Opportunity> deletedOpportunityList{get;set;}
        public Map<Id, String> opportunityIdToErrorMessageMap{get;set;}
        public QueueOpportunityDeletion(List<Opportunity> recordList){
            deletedOpportunityList = recordList;
            opportunityIdToErrorMessageMap = new Map<Id, String>();
        }
        /**
     	* This overridden method used to deletion Opportunity 
     	*/ 
        public void execute(QueueableContext context) {
            //delete  deletedOpportunityList;
            Database.DeleteResult[] drList = Database.delete(deletedOpportunityList, false);
            if (drList.size() > 0){
                for (Integer i=0; i< drList.size(); i++){
                    if (!drList[i].isSuccess()){
                        opportunityIdToErrorMessageMap.put(deletedOpportunityList[i].Id, 'Error in Opportunity deletion through queuable job: ' + drList[i].getErrors()[0].getMessage());
                    }
                }
            }
            
            if (opportunityIdToErrorMessageMap.size() > 0 || Test.isRunningTest()){
                UTL_OWF.createApexErrorLogs('Opportunity (Opportunity)', 'Error in Opportunity deletion through queuable job: ', opportunityIdToErrorMessageMap);UTL_OWF.createApexErrorLogs('Opportunity (Opportunity)', 'Error in Opportunity deletion through queuable job: ', opportunityIdToErrorMessageMap);
            }
        }
    }
    
     /**
     * This queuable sub class delete Assignment
     */
    public class QueueAssignmentDeletion implements Queueable{
        public List<pse__Assignment__c> deletedAssignmentList{get;set;}
         public Map<Id, String> assignmentIdToErrorMessageMap{get;set;}
        public QueueAssignmentDeletion(List<pse__Assignment__c> recordList){
            deletedAssignmentList = recordList;
            assignmentIdToErrorMessageMap = new Map<Id, String>();
        }
        /**
     	* This overridden method used to deletion Assignment 
     	*/ 
        public void execute(QueueableContext context) {
            //delete deletedAssignmentList;
            Database.DeleteResult[] drList = Database.delete(deletedAssignmentList, false);
            if (drList.size() > 0){
                for (Integer i=0; i< drList.size(); i++){
                    if (!drList[i].isSuccess()){
                        assignmentIdToErrorMessageMap.put(deletedAssignmentList[i].Id, 'Error in Assignment deletion through queuable job: ' + drList[i].getErrors()[0].getMessage());
                    }
                }
            }
            
            if (assignmentIdToErrorMessageMap.size() > 0 || Test.isRunningTest()){
                UTL_OWF.createApexErrorLogs('Assignment (pse__Assignment__c)', 'Error in Assignment deletion through queuable job: ', assignmentIdToErrorMessageMap);
            }
            
        }
    }
}