src/objects/pse__Assignment__c.object
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <fields>
        <fullName>pse__Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If an Assignment is associated with a Milestone, Timecards logged for that Assignment will, by default, also be associated with the Milestone on the Assignment at the time.</description>
        <inlineHelpText>If an Assignment is associated with a Milestone, Timecards logged for that Assignment will, by default, also be associated with the Milestone on the Assignment at the time.</inlineHelpText>
        <label>Milestone</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>pse__Milestone__c.pse__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.pse__Project__c</valueField>
            </filterItems>
            <infoMessage>Only milestones for the same project are shown. To display all milestones, click Show all results.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>pse__Milestone__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Resource_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Resource Request Lookup populated only when assignment is created from a resource request.</description>
        <label>Resource Request</label>
        <referenceTo>pse__Resource_Request__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tentative</fullName>
                    <default>true</default>
                    <label>Tentative</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Milestone__c.object
<CustomObject>
    <customHelpPage>pse__MilestoneHelp</customHelpPage>
    <description>A target event used to track project progress. In Time and Materials (T&amp;M) projects, individual milestone records are generally not billable, whereas in Fixed Price or mixed projects all or some generally are. You can group together timecards and expenses, submitted by assigned resources, with milestones on the same project, or associate milestones with a fixed external cost. Milestones have a linear (non-hierarchical) relationship with one another.</description>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Proj__c.object
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <fields>
        <fullName>pse__Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Immediate Sub-Projects</relationshipLabel>
        <relationshipName>ImmediateSubProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Start-up</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Conduct</fullName>
                </value>
                <value>
                    <fullName>Close-out</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Missing Paperwork</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Project_Task__c.object
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <fields>
        <fullName>pse__Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project Milestone that covers this Task.</description>
        <label>Milestone</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>pse__Milestone__c.pse__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.pse__Project__c</valueField>
            </filterItems>
            <infoMessage>Only milestones for the same project are shown. To display all milestones, click Show all results.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>pse__Milestone__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Project that the Task is a part of.</description>
        <inlineHelpText>You do not have to define the Project field when creating a child task. The Project field auto-populates from the parent task and overwrites any entered value.</inlineHelpText>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Status__c</fullName>
        <description>Pick list for Project Task status that may be customized as needed for possible Task status values</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for Billing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <recordTypes>
        <fullName>RDS_Deliverable</fullName>
        <active>true</active>
        <description>PSA-CLD-USNONE - RDS Project Task representing a deliverable unit</description>
        <label>RDS Deliverable</label>
    </recordTypes>
    <recordTypes>
        <fullName>RDS_Deliverable_Task</fullName>
        <active>true</active>
        <description>PSA-CLD-USNONE - RDS Project Task associated with a deliverable</description>
        <label>RDS Deliverable Task</label>
    </recordTypes>
    <recordTypes>
        <fullName>RDS_Project_Task</fullName>
        <active>true</active>
        <description>PSA-CLD-USNONE- RDS Project Task</description>
        <label>RDS Project Task</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/pse__Resource_Request__c.object
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <fields>
        <fullName>pse__Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>pse__Assignment__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Milestone</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>pse__Milestone__c.pse__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.pse__Project__c</valueField>
            </filterItems>
            <infoMessage>Only selected project&apos;s milestones are shown. To display all Milestones, click Show all results.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>pse__Milestone__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Resource Requests</relationshipLabel>
        <relationshipName>Resource_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ready to Staff</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Tentative</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BCH_PSA_UpdateCancelledStatus.cls
public class BCH_PSA_UpdateCancelledStatus implements Database.Batchable<sObject> {
    public static Set<Id> projectIdSet =  new Set<Id>();
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, pse__Stage__c, pse__Parent_Project__c '+
                       'FROM pse__Proj__c '+
            	       'WHERE pse__Parent_Project__r.pse__Stage__c =\'' + CON_PSA.PROJ_STAGE_CANCELED + '\' ' +
                       'AND (pse__Stage__c != \'' + CON_PSA.PROJ_STAGE_CANCELED + '\' ' +
            	       'OR (pse__Stage__c = \'' + CON_PSA.PROJ_STAGE_CANCELED + '\' ' +
            	       'AND LastModifiedDate > YESTERDAY ))' +
            	       'AND RecordType.Name = \'' + CON_PSA.PROJ_REC_TYPE_RDS_SERVICELINE + '\' ' +
                       'AND pse__Parent_Project__c != null';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<pse__Proj__c> records){
        String assignmentCondition = 'pse__Project__c IN : sObjectIdset AND pse__Status__c != \'' + CON_PSA.ASSIGNMENT_STATUS_CANCELLED + '\' AND RecordType.Name =\'' + CON_PSA.ASSIGNMENT_REC_TYPE_RDS + '\'';
        String projectTaskCondition = 'pse__Project__c IN : sObjectIdset AND(RecordType.Name = \'' + CON_PSA.RDS_DELIVERABLE + '\' OR RecordType.Name = \'' + CON_PSA.RDS_DELIVERABLE_TASK + '\' OR RecordType.Name = \'' + CON_PSA.RDS_PROJECT_TASK + '\') AND pse__Status__c != \'' + CON_PSA.PROJ_TASK_STATUS_CANCELLED + '\' AND pse__Status__c != \'' + CON_PSA.PROJ_TASK_STATUS_COMPLETE + '\'';
        String mileStoneCondition = 'pse__Project__c IN : sObjectIdset AND  ( RecordType.Name =\'' + CON_PSA.MILESTONE_REC_TYPE_BILLING + '\' OR RecordType.Name = \'' + CON_PSA.MILESTONE_REC_TYPE_SERVICE + '\') AND pse__Status__c != \'' + CON_PSA.MILESTONE_STATUS_CANCELLED + '\'';
        String resourceRequestCondition = 'pse__Project__c IN : sObjectIdset AND pse__Status__c != \'' + CON_PSA.RESOURCE_REQUEST_STATUS_CANCELLED + '\' AND RecordType.Name =\'' + CON_PSA.RESOURCE_REQUEST_REC_TYPE_RDS_REQUEST + '\'';
        List<sObject> sObjectToUpdateList = new List<sObject>();
        List<pse__Milestone__c> getMileStoneList = new List<pse__Milestone__c>();
        List<pse__Project_Task__c> getProjectTaskList = new List<pse__Project_Task__c>();
        Map<Id, pse__Assignment__c> getAssignmentIdToAssignmentMap = new Map<Id, pse__Assignment__c>();
        List<pse__Resource_Request__c> getResourceRequestList = new List<pse__Resource_Request__c>();
        for(pse__Proj__c project : records){
            projectIdSet.add(project.Id);
            projectIdSet.add(project.pse__Parent_Project__c);
            sObjectToUpdateList.add(new pse__Proj__c(Id = project.Id, pse__Stage__c = CON_PSA.PROJ_STAGE_CANCELED));
        }
        if(projectIdSet.size() > 0){
            //Retrive MileStone 
            getMileStoneList = new SLT_Milestone().getMileStoneByIdSet(projectIdSet, mileStoneCondition, new Set<String>{'Id', 'pse__Status__c'}); 
            for(pse__Milestone__c mileStone : getMileStoneList){
                sObjectToUpdateList.add(new pse__Milestone__c(Id = mileStone.Id, pse__Status__c = CON_PSA.MILESTONE_STATUS_CANCELLED)); 
            }
            
            // Retrive Project Task 
            getProjectTaskList = new SLT_Project_Task().getProjectTaskByIdSet(projectIdSet, projectTaskCondition,new  Set<String>{'Id', 'pse__Status__c'}); 
            for(pse__Project_Task__c projectTask : getProjectTaskList){
                sObjectToUpdateList.add(new pse__Project_Task__c(Id = projectTask.Id, pse__Status__c = CON_PSA.PROJ_TASK_STATUS_CANCELLED)); 
            }
            
            // Retrive Assignment
            getAssignmentIdToAssignmentMap = new SLT_Assignment().selectAssignmentsByIdSet(projectIdSet, assignmentCondition,new Set<String>{'Id', 'pse__Status__c'}); 
            for(pse__Assignment__c assignment : getAssignmentIdToAssignmentMap.values()){
                sObjectToUpdateList.add(new pse__Assignment__c(Id = assignment.Id, pse__Status__c = CON_PSA.ASSIGNMENT_STATUS_CANCELLED)); 
            }
            
            // Retrive Resource Request 
            getResourceRequestList = new SLT_Resource_Request().getResourceRequestByIdSet(projectIdSet, resourceRequestCondition, new Set<String>{'Id', 'pse__Status__c'}); 
            for(pse__Resource_Request__c resourceRequest : getResourceRequestList){
                sObjectToUpdateList.add(new pse__Resource_Request__c(Id = resourceRequest.Id, pse__Status__c = CON_PSA.RESOURCE_REQUEST_STATUS_CANCELLED)); 
            }
            
        }
        if(sObjectToUpdateList.size() > 0){
            UTL_ExecutionControl.stopTriggerExecution_OWF = TRUE;
            UTL_ExecutionControl.stopTriggerExecution = TRUE;
            update sObjectToUpdateList;
            UTL_ExecutionControl.stopTriggerExecution = FALSE;
            UTL_ExecutionControl.stopTriggerExecution_OWF = FALSE;
        }
    }

    public void finish(Database.BatchableContext BC){
        
    }
}