src/objects/pse__Proj__c.object
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <fields>
        <fullName>Project_Code__c</fullName>
        <description>PSA-CLD-USNONE - Project Code</description>
        <label>Project Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Line_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Service Line Lead</description>
        <label>Service Line Lead</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Service Line Manager)</relationshipLabel>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PSA-CLD-USNONE - Service catalogue service line grouping.</description>
        <label>Service Line</label>
        <referenceTo>Service_Line__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pse__Parent_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Immediate Sub-Projects</relationshipLabel>
        <relationshipName>ImmediateSubProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Line__c.object
<CustomObject>
    <label>Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Signal__c.object
<CustomObject>
    <description>IQVIA-PSA-MC-3417</description>
    <fields>
        <fullName>Date_Closed_Evaluation_Completed__c</fullName>
        <description>IQVIA-PSA-MC-3417</description>
        <label>Date Closed (Evaluation Completed)*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evaluation_Due_Date__c</fullName>
        <description>IQVIA-PSA-MC-3417</description>
        <label>Evaluation Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Code__c</fullName>
        <description>IQVIA-PSA-MC-3417</description>
        <label>Project Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>IQVIAPSA-MC-3189: As a SM user I can create/edit new Signals identified during SM project related metadata which are linked to the project and can be linked to a Signal Detection Run</description>
        <label>Project</label>
        <referenceTo>pse__Proj__c</referenceTo>
        <relationshipLabel>Signals</relationshipLabel>
        <relationshipName>Signals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signal_Prioritization_Category__c</fullName>
        <description>IQVIA-PSA-MC-3417</description>
        <label>Signal Prioritization Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validation_Date__c</fullName>
        <description>IQVIA-PSA-MC-3417</description>
        <label>Validation Date</label>
        <type>Date</type>
    </fields>
    <label>Signal</label>
    <nameField>
        <label>Signal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Target__c.object
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CNT_PSA_CreateSignals.cls
public class CNT_PSA_CreateSignals {
    
    @AuraEnabled
    public static Map<string,string> autoPopulatedFieldData(string projectID){
        
        list<pse__Proj__c> projRec  = new SLT_Project().selectSignalManagementProjectById(new Set<Id>{projectID}, new Set<String>{'pse__Account__c', 'pse__Parent_Project__r.Project_Code__c','Service_Line_Lead__c' });
        Map<string,string> projDetail = new Map<string,string>();
        if(projRec.size()>0){
            projDetail.put('account',projRec[0].pse__Account__c);
            projDetail.put('projectCode',projRec[0].pse__Parent_Project__r.Project_Code__c);
            projDetail.put('serviceLineLead',projRec[0].Service_Line_Lead__c);
        }
        return projDetail;
    }
    
    @AuraEnabled
    public static boolean hasSignalPermissionView(){
        boolean hasPermission = false;
        boolean hasSMEdit = false;
        boolean hasPMandFunctionalLead = false;
        SLT_PSA_Signal signalService = new SLT_PSA_Signal();
        List<PermissionSetAssignment> permissionSetList = new list<PermissionSetAssignment>();
        permissionSetList = signalService.checkPermmission();
        for(PermissionSetAssignment perRec: permissionSetList){
            if(perRec.PermissionSet.Name == 'RDS_ADMIN'){
                hasPermission = true;
                break;
            }
            if(perRec.PermissionSet.Name == 'RDS_SM_Edit') {
                hasSMEdit = true;
            }   
            if(perRec.PermissionSet.Name == 'RDS_Project_Manager_and_Functional_Lead'){
                hasPMandFunctionalLead = true;
            }  
        }
        
        if(hasSMEdit && hasPMandFunctionalLead){
            hasPermission = true;
        }
        
        if(hasPermission){
            return true;  
        }
        else{
            return false;
        }
    }
    
    @AuraEnabled
    public static boolean hasSignalPermissionCreate(string projectID){
        boolean hasPermission = false;
        boolean hasSMEdit = false;
        boolean hasPMandFunctionalLead = false;
        SLT_PSA_Signal signalService = new SLT_PSA_Signal();
        List<PermissionSetAssignment> permissionSetList = new list<PermissionSetAssignment>();
        permissionSetList = signalService.checkPermmission();
        for(PermissionSetAssignment perRec: permissionSetList){
            if(perRec.PermissionSet.Name == 'RDS_ADMIN'){
                hasPermission = true;
                break;
            }
            if(perRec.PermissionSet.Name == 'RDS_SM_Edit') {
                hasSMEdit = true;
            }   
            if(perRec.PermissionSet.Name == 'RDS_Project_Manager_and_Functional_Lead'){
                hasPMandFunctionalLead = true;
            } 
        }
        if(hasSMEdit && hasPMandFunctionalLead){
            hasPermission = true;
        }
        
        list<pse__Proj__c> projRec  = new SLT_Project().selectSignalManagementProjectById(new Set<Id>{projectID}, new Set<String>{'Service_Line__c'});
        if(hasPermission && projRec.size()>0){
            return true;  
        }
        else{
            return false;
        }
    }
    
    @AuraEnabled
        public static string signalGetProjectId(string signalId){
        SLT_PSA_Signal signalService = new SLT_PSA_Signal();
        list<Signal__c> signalList  = signalService.getSignalListById(signalId);
        if(signalList.size()>0 ){
            string recId =  signalList[0].Project__c;
            return recId;
        }
        else{
            return null;
        }
    }
    @AuraEnabled
    public static List<Target__c> getTargetRecords(string projectID){
        List<Target__c> activeTargetsList = new List<Target__c>();
        activeTargetsList = UTL_PSA.getTargetRecords(projectID);
        
        return activeTargetsList;
    }
    
    @AuraEnabled
    public static EvalResponse populateEvalDueDate(String signalPriorCategory, Date signalValidationDate) {
        EvalResponse response = new EvalResponse();
        Date evaluationDueDate= null;
        if(signalPriorCategory == 'Low'){
            evaluationDueDate = signalValidationDate.addDays(90);
        }
        else if(signalPriorCategory == 'Medium'){
            evaluationDueDate = signalValidationDate.addDays(50);
        }
        else if(signalPriorCategory == 'High'){
            evaluationDueDate = signalValidationDate.addDays(30);
        }
        else if(signalPriorCategory == null || signalPriorCategory==''){
            evaluationDueDate = signalValidationDate;
        }
        if( evaluationDueDate != null && ( signalPriorCategory == 'Low' || signalPriorCategory == 'Medium' || signalPriorCategory == 'High') ){
            response.isReadable = TRUE;
            response.evalDate = evaluationDueDate;
        }else if( signalPriorCategory =='Custom' ){
            response.isReadable = FALSE;
            response.evalDate = evaluationDueDate;
        }else if(signalPriorCategory ==null || signalPriorCategory==''|| signalPriorCategory.equalsIgnoreCase('None')){
            response.isReadable = FALSE;
            response.evalDate =null;
        }
        
        return response;
    }  
    @AuraEnabled
    public static boolean hasRDSAdminPermission(string signalId){
        boolean hasPermission = false;
        List<PermissionSetAssignment> permissionSetList = new list<PermissionSetAssignment>();
        permissionSetList = [SELECT  PermissionSet.Name FROM PermissionSetAssignment WHERE AssigneeId = :UserInfo.getUserId()];
        for(PermissionSetAssignment perRec: permissionSetList){
            if(perRec.PermissionSet.Name == 'RDS_ADMIN'){
                hasPermission = true;
                break;
            }
        }
        if(hasPermission){
            return true;
        }
        else{
            return false;
        }       
    }
	@AuraEnabled
    public static String populateSignalStatusValue(Date dateClosedEvaluationValue, String validationOutcomeValue) {
        String signalStatus = '';
        if(dateClosedEvaluationValue == null){
            if(validationOutcomeValue == 'Signal Validated') {
                signalStatus = 'Ongoing';
            } 
            if(validationOutcomeValue == 'Signal Not Validated(Specify Reason)'){
                signalStatus = 'Not Validated';
            }
        }
        else {
            signalStatus = 'Closed';
        }
        return signalStatus;
    }
    
    @AuraEnabled
    public static Signal__c getSignalRecord(string signalID){
        
        Signal__c signalList = [SELECT Id, Validation_Date__c,Evaluation_Due_Date__c, Date_Closed_Evaluation_Completed__c,Signal_Prioritization_Category__c FROM Signal__c WHERE Id =: signalID];
        return signalList;
    }
    public Class EvalResponse{
        @AuraEnabled
        public Boolean isReadable{get;set;} 
        @AuraEnabled
        public Date evalDate{get;set;} 
    }
}