src/objects/Queue_User_Relationship__c.object
<CustomObject>
    <description>CSM - ACN - S-0007 - Queue User Relationship</description>
	<fields>
        <fullName>AFU_Queue_Email__c</fullName>
        <description>CSM-US-0419-R&amp;D Automated Follow Up Email Enhancement</description>
        <label>AFU Queue Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Group_Id__c</fullName>
        <label>Group Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsDefaultQueue__c</fullName>
        <description>CSM-1809: All - User Queue Enhancements</description>
        <defaultValue>false</defaultValue>
        <label>Default Queue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_Emails_Text__c</fullName>
        <description>CSM-209 RnD-Email from field</description>
        <inlineHelpText>Enter email addresses separated by semi colon(;)</inlineHelpText>
        <label>Queue Emails Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Queue User Relationship</label>
    <nameField>
        <label>Queue User Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue User Relationship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_DAOH_QueueUserRelationship.cls
@isTest
private class TST_DAOH_QueueUserRelationship {

    @isTest
    private static void testCustomEmailAddressValidation(){
        List<Queue_User_Relationship__c> qList = new List<Queue_User_Relationship__c>();
        Queue_User_Relationship__c QURecord = new Queue_User_Relationship__c();
        QURecord.Name = 'Test Queue';
        QURecord.AFU_Queue_Email__c = 'testuser@mail.com';
        QuRecord.Group_Id__c = '00G6A000000nv2XUAQ';
        QURecord.Queue_Emails_Text__c = 'demodata@mail.com; userrecord@co.in';
        QURecord.Type__c = 'Queue';
        QURecord.OwnerId = UserInfo.getUserId();
        qList.add(QURecord);
        Queue_User_Relationship__c quR = new Queue_User_Relationship__c();
        quR.Name = 'Test Queue';
        quR.AFU_Queue_Email__c = 'testuser@mail.com';
        quR.Group_Id__c = '00G6A000000nv2XUAQ';
        quR.Queue_Emails_Text__c = 'demodata@mail.com; userrecord@co.in';
        quR.Type__c = 'User';
        quR.IsDefaultQueue__c = false;
        quR.OwnerId = UserInfo.getUserId();
        qList.add(quR);
        Test.startTest();
        insert qList;
        List<Queue_User_Relationship__c> quList = Database.query('Select Id,IsDefaultQueue__c from Queue_User_Relationship__c where Type__c =\'User\'');
        for(Queue_User_Relationship__c q : quList){
            q.IsDefaultQueue__c = true;
        }
        try{
            update quList;    
        }catch(DmlException e){
            
        }
        
        Test.stopTest();
    }
}