src/objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Stage__c</fullName>
        <description>This field captures the stage of the quote life cycle.</description>
        <label>Approval Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In-Progress</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                 <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>CPQ-IQ-LC-12533: This field captures the type of licenses.</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Per Study</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GBU__c</fullName>
        <description>This field provides visibility of quote global business unit.</description>
        <label>Pathway</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RDS</fullName>
                </value>
                <value>
                    <fullName>DPS</fullName>
                </value>
                <value>
                    <fullName>Tech Solution</fullName>
                </value>
                <value>
                    <fullName>RDS Non-SF</fullName>
                </value>
                <value>
                    <fullName>RDS SF</fullName>
                </value>
                <value>
                    <fullName>RDS Non-SF WRF</fullName>
                    <label>RDS Non-SF (WRF)</label>
                </value>
                <value>
                    <fullName>Non-RDS</fullName>
                    <isActive>false</isActive>
                    <label>Del-Others</label>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <isActive>false</isActive>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Tools__c</fullName>
        <description>Read-only field that captures the list of all the selected pricing tools at the time of Quote creation. It gives visibility to different pricing tools that need to be configured under the current Quote.</description>
        <label>Pricing Tool(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>GBU__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete Consent</fullName>
                </value>
                <value>
                    <fullName>Q2 Solutions</fullName>
                </value>
                <value>
                    <fullName>QIP Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Central Lab Spreadsheet Calculator</fullName>
                </value>
                <value>
                    <fullName>SMART Ready Upload Worksheet(s)</fullName>
                </value>
                <value>
                    <fullName>Regulatory-Non-QIP Budget tool</fullName>
                </value>
                <value>
                    <fullName>IntegRate ECD</fullName>
                </value>
                <value>
                    <fullName>ECG Standalone Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>Feasibility Calculator</fullName>
                </value>
                <value>
                    <fullName>Takeda CDM Fixed unit File</fullName>
                </value>
                <value>
                    <fullName>BMS Fixed Unit Pricing by Project</fullName>
                </value>
                <value>
                    <fullName>Functional Non-standard Pricing</fullName>
                </value>
                <value>
                    <fullName>Customer Non-standard Pricing</fullName>
                </value>
                <value>
                    <fullName>Fee for Service Budget - Rates Only</fullName>
                </value>
                <value>
                    <fullName>Small Study QIP</fullName>
                </value>
                <value>
                    <fullName>Client Pricing Tool</fullName>
                </value>
                <value>
                    <fullName>Biogen pricing tool</fullName>
                </value>
                <value>
                    <fullName>Proforma</fullName>
                </value>
                <value>
                    <fullName>LinkPSB</fullName>
                </value>
                <value>
                    <fullName>EBP QIP</fullName>
                </value>
                <value>
                    <fullName>PRISM</fullName>
                </value>
                <value>
                    <fullName>POP Spreadsheet</fullName>
                </value>
                <value>
                    <fullName>NOBI</fullName>
                </value>
                <value>
                    <fullName>LCS QIP</fullName>
                </value>
                <value>
                    <fullName>Client Budget Tool</fullName>
                </value>
                <value>
                    <fullName>Non SF Unit Pricing Tool</fullName>
                </value>
                <value>
                    <fullName>No QIP</fullName>
                </value>
                <value>
                    <fullName>Non SF LCS Unit Pricing Tool</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Unit Pricing Tool</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Read-only field that captures the account from the linked opportunity. Provide the capability to access the account directly from the quote.</description>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Read-only field that captures the opportunity value on which Quote is created.</description>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>IQVIA Quotes</relationshipLabel>
        <relationshipName>IQVIA_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>CPQ-IQ-LC-12308:Identity of Document type(PDF Documents, Interactive - Individual Documents, Interactive - Document Bundles)</description>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PDF - Individual Documents</fullName>
                </value>
                <value>
                    <fullName>PDF - Document Bundles</fullName>
                </value>
                <value>
                    <fullName>Interactive - Individual Documents</fullName>
                </value>
                <value>
                    <fullName>Interactive - Document Bundles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_ICF_Documents__c</fullName>
        <defaultValue>0</defaultValue>
        <description>CPQ-IQ-LC-12308:Multiplication of Total ICF and Adjusted Document Count.</description>
        <inlineHelpText>Total unique ICF documents</inlineHelpText>
        <label>Total ICF Documents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IQVIA Quote</label>
    <nameField>
        <displayFormat>IQ-{0000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IQVIA Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_SLT_IQVIA_Quote.cls
@isTest 
private class TST_SLT_IQVIA_Quote {

    @testSetup
    static void dataSetup() 
    {
        Account acc = UTL_OWF_TestData.createAccount();
        insert acc;
        
        Opportunity opp = UTL_OWF_TestData.createOpportunity(acc.Id);
        insert opp;
		
        Quote__c quote = new Quote__c();
        quote.Pricing_Tools__c = CON_CPQ.Complete_Consent;
        quote.Approval_Stage__c = CON_CPQ.DRAFT;
        quote.GBU__c = CON_CPQ.GBU_DPS;
        quote.Related_Opportunity__c = opp.Id; 
        quote.Document_Type__c = CON_CPQ.PDF_INDIVIDUAL_DOCUMENTS;
        quote.License_Type__c = 'Per Study';
        quote.Related_Account__c = acc.Id;
        insert quote;
    }
    
    @isTest 
    static void testGetQuoteId() { 
        Quote__c quote = [SELECT Id, Pricing_Tools__c FROM Quote__c LIMIT 1];
        SLT_IQVIA_Quote quoteSelector = new SLT_IQVIA_Quote(); 
        Quote__c retrievedQuote = quoteSelector.getQuoteId(quote.Id, new Set<String>()); 
        System.assertEquals(quote.Id, retrievedQuote.Id);  
    }
    
    @isTest 
    static void testGetQuoteDetails() { 
        Quote__c quote = [SELECT Id, Pricing_Tools__c FROM Quote__c LIMIT 1];
        SLT_IQVIA_Quote quoteSelector = new SLT_IQVIA_Quote(); 
        Quote__c retrievedQuote = quoteSelector.getQuoteDetails(Quote.Id); 
        System.assertEquals(Quote.Id, retrievedQuote.Id);
    }
    
    @isTest static void testGetQuoteRequisitesById() {
        Quote__c quote = [SELECT Id FROM Quote__c LIMIT 1];
        Set<Id> idSet = new Set<Id>{quote.Id};
            
        Test.startTest();
            List<Quote__c> quoteList = new SLT_IQVIA_Quote().getQuoteIdslist(idSet, new Set<String>{'Id', 'Total_ICF_Documents__c'});
        Test.stopTest();
        
        System.assertEquals(true, quoteList.size() > 0);
    }
    
    @isTest
    private static void testGetQuoteMap() {
	    Quote__c quote = [SELECT Id FROM Quote__c LIMIT 1];
        Set<Id> quoteIdsToRetrieve = new Set<Id>{quote.Id};
		Test.startTest();
            Map<Id, Quote__c> quoteMap = new SLT_IQVIA_Quote().getQuoteMap(quoteIdsToRetrieve, new Set<String>{CON_CPQ.ID, CON_CPQ.CURRENCYISOCODE});
        Test.stopTest();
        System.assertEquals(1, quoteMap.size());
    }

    @isTest
    private static void testGetQuotesByConditionOrderByAcceptedDate() {
	    Quote__c quote = [SELECT Id, Related_Opportunity__c FROM Quote__c LIMIT 1];
		Test.startTest();
            String condition = 'Related_Opportunity__c =: relatedOpportunityIdSet';
            List<Quote__c> quoteList = new SLT_IQVIA_Quote().getQuotesByConditionOrderByAcceptedDate(new Set<String>{CON_CPQ.ID}, condition, CON_CPQ.ID, CON_CPQ.SORT_DESC, new Set<Id>{quote.Related_Opportunity__c});
        Test.stopTest();
        Assert.areEqual(1, quoteList.size(), 'The expected list size is not returned.');
    }
}