src/objects/Revenue_Analyst__c.object
<CustomObject>
    <description>CRM-MC-ESPSFDCQI-3168 - This custom object is used to store the Revenue Analyst.</description>
    <fields>
        <fullName>Revenue_Analyst_Email__c</fullName>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>Revenue Analyst Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>User_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>User 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Revenue_Analysts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CRM-MC-ESPSFDCQI-3168 -</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N70000001hwojEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Revenue Analyst</label>
    <nameField>
        <label>Revenue Analyst Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Analysts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TST_BCH_CRM_RevenueAnalystSBSQueueSync.cls
/*
 * Author		: 
 * Purpose		: Test class for BCH_CRM_RevenueAnalystSBSQueueSync
 */
@isTest
public class TST_BCH_CRM_RevenueAnalystSBSQueueSync {
    
    @testSetup 
    static void setupTestData() {
        String profileName = 'System Administrator';
        List<User> userList = UTL_TestData.createUser(profileName, 10);
        insert userlist;        
        Group g1 = new Group(Name='group name', type='Queue');
        insert g1;
        QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Revenue_Analyst__c');
        insert q1;
        GroupMember gp = new GroupMember(UserorGroupId = UserInfo.getUserId(), GroupId=g1.Id);
        insert gp;   
    }
    
    //Test Batch
    public static testmethod void t1() {       
        Group g = [select id from group where name= 'group name' Limit 1];
        Revenue_Analyst__c revenueAnalyst = new Revenue_Analyst__c(OwnerId = g.Id, Name='TstAnalyst1',Revenue_Analyst_Email__c='test1@xyz.com' ,User__c=UserInfo.getUserId(), User_2__c=UserInfo.getUserId());
        insert revenueAnalyst;
        revenueAnalyst.Name = 'TestAnalyst';
        update revenueAnalyst;
        Test.startTest();
        BCH_CRM_RevenueAnalystSBSQueueSync obj = new BCH_CRM_RevenueAnalystSBSQueueSync();
        DataBase.executeBatch(obj);                
        Test.stopTest();
    }
    
    //Test Batch for Exception
    public static testmethod void t2() {
        Test.startTest();
        BCH_CRM_RevenueAnalystSBSQueueSync obj = new BCH_CRM_RevenueAnalystSBSQueueSync();
        obj.exception_List.add('Demo Exception');
        DataBase.executeBatch(obj);
        Test.stopTest();
    } 
}