src/objects/Sales_Revenue__c.object
<CustomObject>
    <description>Stores the data for Sales Team dashboard</description>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ESPSFDCQI-14420</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Revenue</relationshipLabel>
        <relationshipName>Sales_Revenue</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <description>Tells whether the Sales Data is of type Budget, Pipeline or Revenue</description>
        <label>Scenario</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                </value>
                <value>
                    <fullName>Revenue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Revenue</label>
    <nameField>
        <displayFormat>SD# {00000000}</displayFormat>
        <label>Sales Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Revenue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DAOH_Sales_Revenue.cls
public class DAOH_Sales_Revenue {
    
    /**
     * This method is used to set record Fields
     * @params  List<Sales_Revenue__c> newList
     * @return  void
     */
    public static void setSalesRevenueFields(List<Sales_Revenue__c> newList){
        Set<String> productFieldSet = new Set<String>{'Id', 'Name'};
            Set<String> productCodeSet = new Set<String>();
        Map<String,Id> productCodeToIdMap = new Map<String,Id>();
        
        for(Sales_Revenue__c sr: newList){
            if(String.isNotBlank(sr.Product_Code__c) && (sr.Scenario__c == 'Revenue' || sr.Scenario__c == 'Pipeline')){
                productCodeSet.add(sr.Product_Code__c);
            }
        }
        
        if(productCodeSet.size() > 0){
            for(Product2 pro: new SLT_Product2().getProductsByProductCode(productFieldSet, productCodeSet)){
                productCodeToIdMap.put(pro.ProductCode, Pro.Id);
            }
            
            for(Sales_Revenue__c sr: newList){
                if(productCodeToIdMap.containskey(sr.Product_Code__c) && String.isNotBlank(sr.Product_Code__c) && (sr.Scenario__c == 'Revenue' || sr.Scenario__c == 'Pipeline')){
                    sr.Product__c = productCodeToIdMap.get(sr.Product_Code__c);
                }
            }
        }
    }
}