src/objects/SObject_Sharing__c.object
<CustomObject>
    <description>Master table which stores Sharing Rules</description>
    <fields>
        <fullName>Account_Country_Api_Name__c</fullName>
        <description>API Name of Account Country Field on Parent SObject (For territory sharing only)</description>
        <inlineHelpText>API Name of Account Country Field on Parent SObject (For territory sharing only)</inlineHelpText>
        <label>Account Country Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Api_Name__c</fullName>
        <description>API Name of Business Unit Field on Parent SObject (For territory sharing only)</description>
        <inlineHelpText>API Name of Business Unit Field on Parent SObject (For territory sharing only)</inlineHelpText>
        <label>Business Unit Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Sobject_Share__c</fullName>
        <description>Child SObject Share object Api name(suffix with __share for custom object)</description>
        <inlineHelpText>Child SObject Share object Api name(suffix with __share for custom object)</inlineHelpText>
        <label>Child Sobject_Share</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Sobject__c</fullName>
        <description>API name of Child SObject which inherits sharing from its parent SObject</description>
        <inlineHelpText>API name of Child SObject which inherits sharing from its parent SObject</inlineHelpText>
        <label>Child Sobject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Sharing_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sharing Calculation is enabled for this record or not</description>
        <inlineHelpText>Sharing Calculation is enabled for this record or not</inlineHelpText>
        <label>Enable Sharing Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lookup_Name__c</fullName>
        <description>Field API name of the lookup field on Child Sobject to it’s parent SObject to be used for inherit sharing</description>
        <inlineHelpText>Field API name of the lookup field on Child Sobject to it’s parent SObject to be used for inherit sharing</inlineHelpText>
        <label>Lookup Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_Job_Status__c</fullName>
        <description>Status of Maintenance job</description>
        <inlineHelpText>Status of Maintenance job</inlineHelpText>
        <label>Maintenance Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Customer_Code_Api_Name__c</fullName>
        <description>API Name of Parent Customer Code Field on Parent Sobject (For territory sharing only)</description>
        <inlineHelpText>API Name of Parent Customer Code Field on Parent Sobject (For territory sharing only)</inlineHelpText>
        <label>Parent Customer Code Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Sharing_Team_Label__c</fullName>
        <description>Apex Sharing Reason on Parent SObject for Team Sharing(Only applicable for Type child)</description>
        <inlineHelpText>Apex Sharing Reason on Parent SObject for Team Sharing(Only applicable for Type child)</inlineHelpText>
        <label>Parent Sharing Team Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Sharing_Territory_Label__c</fullName>
        <description>Apex Sharing Reason on Parent SObject for Territory Sharing(Only applicable for type Child)</description>
        <inlineHelpText>Apex Sharing Reason on Parent SObject for Territory Sharing(Only applicable for type Child)</inlineHelpText>
        <label>Parent Sharing Territory Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Sobject_Share__c</fullName>
        <description>Parent SObject Share object Api name(suffix with __share for custom object)</description>
        <inlineHelpText>Parent SObject Share object Api name(suffix with __share for custom object)</inlineHelpText>
        <label>Parent Sobject Share</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Sobject__c</fullName>
        <description>Parent SObject Api Name to fetch sharing logic</description>
        <inlineHelpText>Parent SObject Api Name to fetch sharing logic</inlineHelpText>
        <label>Parent Sobject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Api_Name__c</fullName>
        <description>API Name of Record Type Field on Parent SObject (For territory sharing only)</description>
        <inlineHelpText>API Name of Record Type Field on Parent SObject (For territory sharing only)</inlineHelpText>
        <label>Record Type Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sharing_Owner_Label__c</fullName>
        <description>Apex Sharing Reason on SharingSObject from parent owner. (only applicable for type child)</description>
        <inlineHelpText>Apex Sharing Reason on SharingSObject from parent owner. (only applicable for type child)</inlineHelpText>
        <label>Sharing Owner Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sharing_Team_Label__c</fullName>
        <description>Apex Sharing Reason on Sharing Sobject for team</description>
        <inlineHelpText>Apex Sharing Reason on Sharing Sobject for team</inlineHelpText>
        <label>Sharing Team Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sharing_Territory_Label__c</fullName>
        <description>Apex Sharing Reason on Sharing Sobject for Territory</description>
        <inlineHelpText>Apex Sharing Reason on Sharing Sobject for Territory</inlineHelpText>
        <label>Sharing Territory Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sharing_Type__c</fullName>
        <description>Picklist to check whether its parent sharing is calculated from custom framework (Derive)or from other standard salesforce sharing rules/manual sharing (Manual)</description>
        <inlineHelpText>Picklist to check whether its parent sharing is calculated from custom framework (Derive)or from other standard salesforce sharing rules/manual sharing (Manual)</inlineHelpText>
        <label>Sharing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Derived</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Sharing_Lookup_Field__c</fullName>
        <description>Parent object lookup API name on team object</description>
        <inlineHelpText>Parent object lookup API name on team object</inlineHelpText>
        <label>Team Sharing Lookup Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Picklist to check whether sharing on parent Sobject or for its child SObject</description>
        <inlineHelpText>Picklist to check whether sharing on parent Sobject or for its child SObject</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Relational</fullName>
                    <isActive>false</isActive>
                    <label>Relational</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SObject Sharing</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sobject Sharing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SObject Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Included_in_Custom_Sharing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows if this territory is included in Custom sharing Framework</description>
        <label>Included in Custom Sharing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leaf_Node__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows if territory is last level</description>
        <label>Leaf Node</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Legacy_Id__c</fullName>
        <externalId>true</externalId>
        <label>Legacy Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sharing_Pillar__c</fullName>
        <label>Sharing Pillar</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SHR_TER</fullName>
                    <label>Geography</label>
                </value>
                <value>
                    <fullName>SHR_CUS</fullName>
                    <label>Global Customer</label>
                </value>
                <value>
                    <fullName>SHR_BU</fullName>
                    <label>Business Unit</label>
                </value>
                <value>
                    <fullName>SHR_OTR</fullName>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Territory_Sharing__c.object
<CustomObject>
    <description>Master table for defining Territory based Sharing Rule</description>
    <fields>
        <fullName>Account_Country__c</fullName>
        <description>Account Country Field Value Api Name</description>
        <inlineHelpText>Account Country Field Value Api Name</inlineHelpText>
        <label>Account Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Business Unit Field Value Api Name</description>
        <inlineHelpText>Business Unit Field Value Api Name</inlineHelpText>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_Job_Status__c</fullName>
        <description>To check whether initial sharing completed for existing records</description>
        <inlineHelpText>To check whether initial sharing completed for existing records</inlineHelpText>
        <label>Maintenance Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Customer_Code__c</fullName>
        <description>Parent Customer Code Field Value Api Name</description>
        <inlineHelpText>Parent Customer Code Value Api Name</inlineHelpText>
        <label>Parent Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Sobject_Name__c</fullName>
        <description>Api Name of SObject on which this rule executes</description>
        <inlineHelpText>Api Name of SObject on which this rule executes</inlineHelpText>
        <label>Parent Sobject Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <description>Record Type Field Value Api Name</description>
        <inlineHelpText>Record Type Field Value Api Name</inlineHelpText>
        <label>Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The criteria will execute or not</description>
        <inlineHelpText>The criteria will execute or not</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Territory Sharing</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Territory Sharing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CNT_GBL_SobjectSharingHandler.cls
public class CNT_GBL_SobjectSharingHandler {
    
    /*
    * @params 
    * Fetch Sobject sharing records
    */
    @AuraEnabled
    public static Map<String,Object> fetchSobjectSharingRecords(){
        Map<String,Object> mapToReturn = new Map<String,Object>();
        List<String> batchProcessingList = new List<String>{CON_CRM.BATCH_PROCESSING_NEW, CON_CRM.BATCH_PROCESSING_IN_PROCESSING};
        //List<SObject_Sharing__c> currentUserDetails = [SELECT Parent_Sobject__c, Child_Sobject__c, Enable_Sharing_Calculation__c, Lookup_Relationship_Name__c, Child_Sobject_Share__c, Lookup_Name__c, Sharing_Owner_Label__c, Parent_Sobject_Share__c, Sharing_Type__c, Sharing_Territory_Label__c, Sharing_Team_Label__c, Account_Country_Api_Name__c, Record_Type_Api_Name__c, Parent_Customer_Code_Api_Name__c, Business_Unit_Api_Name__c, Type__c, Parent_Sharing_Territory_Label__c, Parent_Sharing_Team_Label__c, Maintenance_Job_Status__c, Name, Id FROM SObject_Sharing__c where Parent_Sobject_Share__c != null];        
            List<SObject_Sharing__c> currentSharingRecords = [SELECT Parent_Sobject__c, Child_Sobject__c, Enable_Sharing_Calculation__c, 
                                                              Team_Sharing_Lookup_Field__c,Child_Sobject_Share__c, Lookup_Name__c, Sharing_Owner_Label__c, 
                                                              Parent_Sobject_Share__c, Sharing_Type__c, Sharing_Territory_Label__c, Sharing_Team_Label__c, 
                                                              Account_Country_Api_Name__c, Record_Type_Api_Name__c, Parent_Customer_Code_Api_Name__c, Business_Unit_Api_Name__c,
                                                              Type__c, Parent_Sharing_Territory_Label__c, Parent_Sharing_Team_Label__c,Maintenance_Job_Status__c, Name,
                                                              Id FROM SObject_Sharing__c where Parent_Sobject_Share__c != null AND 
                                                              Sharing_Type__c =: CON_CRM.SHARING_TYPE_DERIVED AND Enable_Sharing_Calculation__c = true order by CreatedDate DESC];        
        System.debug(currentSharingRecords.size()+'--'+currentSharingRecords);
        mapToReturn.put('allSharing',currentSharingRecords);
        mapToReturn.put('allTerritory',fetchAllTerritory());
        return mapToReturn;
    }
	@AuraEnabled
    public static List<SObject_Sharing__c> sObjectSharingProcessedRecords(){
        List<SObject_Sharing__c> currentSharingRecords = [SELECT Parent_Sobject__c, Maintenance_Job_Status__c from SObject_Sharing__c where Maintenance_Job_Status__c =: CON_CRM.BATCH_PROCESSING_IN_PROCESSING];

        return currentSharingRecords;
    }
    @AuraEnabled
    public static List<SObject> initiateSobjectSharing(String sharingType, List<String> sharingIds){
        List<SObject> allDataList = new List<SObject>();
        if(sharingType == 'allSharing'){
            List<SObject_Sharing__c> currentSharingRecords = [SELECT Parent_Sobject__c, Child_Sobject__c, Enable_Sharing_Calculation__c,Team_Sharing_Lookup_Field__c,
                                                              Child_Sobject_Share__c, Lookup_Name__c, Sharing_Owner_Label__c,Parent_Sobject_Share__c, Sharing_Type__c,
                                                              Sharing_Territory_Label__c, Sharing_Team_Label__c,Account_Country_Api_Name__c, Record_Type_Api_Name__c,
                                                              Parent_Customer_Code_Api_Name__c, Business_Unit_Api_Name__c,Type__c, Parent_Sharing_Territory_Label__c,
                                                              Parent_Sharing_Team_Label__c,Maintenance_Job_Status__c, Name, Id FROM SObject_Sharing__c where Id IN : sharingIds];
        allDataList.addAll(currentSharingRecords);
        }else if(sharingType == 'allTerritory'){
            List<Territory_Sharing__c> territorySharingList = [SELECT Id, Name, Maintenance_Job_Status__c, Record_Type__c, 
                                                               Account_Country__c, isActive__c, Parent_Sobject_Name__c,Business_Unit__c, Parent_Customer_Code__c FROM Territory_Sharing__c where
                                                               Id IN : sharingIds];
            System.debug('terr class ' + territorySharingList );
            allDataList.addAll(territorySharingList);
            System.debug('terr add '+allDataList );
        }
        if(allDataList.size() > 0){
            System.debug('terr class bactg'  );
            BCH_GBL_Sharing_Maintenance_Job sharingBatch = new BCH_GBL_Sharing_Maintenance_Job(allDataList); 
            database.executeBatch(sharingBatch);
        }
        return allDataList;
    }
    @AuraEnabled
    public static List<TerritoryModal> fetchAllTerritory(){
        List<Territory2> territoryList = [SELECT Id, Name, Territory2TypeId, ParentTerritory2Id, Territory2ModelId, Leaf_Node__c, 
                                          Sharing_Pillar__c, Included_in_Custom_Sharing__c, Legacy_Id__c FROM Territory2 where 
                                          Legacy_Id__c <> null and Leaf_Node__c = true and Sharing_Pillar__c = : CON_CRM.SHARING_PILLAR_GEOGRAPHY order by Name ASC limit 10];
        System.debug('-territoryList----'+territoryList);
        Map<String,Territory2> legacyIdToTerritoryMap = new Map<String,Territory2>();
        for(Territory2 ter : territoryList){
            legacyIdToTerritoryMap.put(ter.Legacy_Id__c,ter);
        }
        Map<String,Set<String>> legacyIdTostatusMap = new Map<String,Set<String>>();
        Map<String,List<Territory_Sharing__c>> legacyIdToTerritorySharingMap = new Map<String,List<Territory_Sharing__c>>();
        List<Territory_Sharing__c> territorySharingList = [SELECT Id, Name, Maintenance_Job_Status__c, Record_Type__c, Account_Country__c, isActive__c FROM Territory_Sharing__c where Account_Country__c IN : legacyIdToTerritoryMap.keySet()];
        for(Territory_Sharing__c tsc : territorySharingList){
            if(tsc.Maintenance_Job_Status__c != null){
                if(legacyIdTostatusMap.containsKey(tsc.Account_Country__c)){
                    legacyIdTostatusMap.get(tsc.Account_Country__c).add(tsc.Maintenance_Job_Status__c);
                }else{
                    legacyIdTostatusMap.put(tsc.Account_Country__c, new Set<String>{tsc.Maintenance_Job_Status__c});
                }
                if(legacyIdToTerritorySharingMap.containsKey(tsc.Account_Country__c)){
                    legacyIdToTerritorySharingMap.get(tsc.Account_Country__c).add(tsc);
                }else{
                    legacyIdToTerritorySharingMap.put(tsc.Account_Country__c, new List<Territory_Sharing__c>{tsc});
                }
            }else{
                legacyIdTostatusMap.put(tsc.Account_Country__c, new Set<String>{CON_CRM.BATCH_PROCESSING_NEW});
                legacyIdToTerritorySharingMap.put(tsc.Account_Country__c, new List<Territory_Sharing__c>{tsc});
            }
        }
        List<TerritoryModal> territoryModallist = new List<TerritoryModal>();
        for(String accCountry : legacyIdToTerritoryMap.keySet()){
            if(legacyIdTostatusMap.containsKey(accCountry)){
                if(legacyIdToTerritorySharingMap.containsKey(accCountry)){
                    territoryModallist.add(new TerritoryModal(legacyIdTostatusMap.get(accCountry),legacyIdToTerritoryMap.get(accCountry), legacyIdToTerritorySharingMap.get(accCountry))); 
                }else{
                    territoryModallist.add(new TerritoryModal(legacyIdTostatusMap.get(accCountry),legacyIdToTerritoryMap.get(accCountry), new List<Territory_Sharing__c>())); 
                }
                   
            }else{
                territoryModallist.add(new TerritoryModal(new Set<String>{CON_CRM.BATCH_PROCESSING_NEW},legacyIdToTerritoryMap.get(accCountry), new List<Territory_Sharing__c>()));
            }
        }
        return territoryModallist;
    }
    public class TerritoryModal{
        @AuraEnabled public String recId;
        @AuraEnabled public String recName;
        @AuraEnabled public String maintenanceStatus;
        @AuraEnabled public List<Id> terIdList;
        public TerritoryModal(Set<String> statusSet, Territory2 ter, List<Territory_Sharing__c> territorySharingList){
            recId = ter.Id;
            recName = ter.Name;
            terIdList = new List<Id>();
            if(territorySharingList.size() > 0){
                for(Territory_Sharing__c tsc : territorySharingList){
                    terIdList.add(tsc.Id);
                }
            }
            //maintenanceStatus = statusSet;
            if(statusSet.contains(CON_CRM.BATCH_PROCESSING_IN_PROCESSING)){
                maintenanceStatus = CON_CRM.BATCH_PROCESSING_IN_PROCESSING;
            }else if(statusSet.size() == 1){
                List<String> statusList = new List<String>();
                statusList.addAll(statusSet);
                maintenanceStatus = statusList[0];     
            }else{
                maintenanceStatus = CON_CRM.BATCH_PROCESSING_IN_PROCESSING;
                //maintenanceStatus = '';
            }
        }
    }
}