src/objects/SObject_Sharing__c.object
<CustomObject>
    <description>Master table which stores Sharing Rules</description>
    <fields>
        <fullName>Enable_Sharing_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sharing Calculation is enabled for this record or not</description>
        <inlineHelpText>Sharing Calculation is enabled for this record or not</inlineHelpText>
        <label>Enable Sharing Calculation</label>
        <type>Checkbox</type>
    </fields>
    <label>SObject Sharing</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Sobject Sharing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SObject Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SLT_sObjectSharing.cls
/*
* Version       : 1.0
* Description   : This Apex class is selector layer for SObject Sharing
*/
public class SLT_sObjectSharing extends fflib_SObjectSelector {
    
    /**
* constructor to initialize CRUD and FLS
*/
    public SLT_sObjectSharing() {
        super(false, true, false);
    }
    
    /**
* constructor to initialize CRUD and FLS
*/
    public SLT_sObjectSharing(Boolean enforceCRUD, Boolean enforceFLS) {
        super(false, enforceCRUD, enforceFLS);
    }
    
    /**
* This method used to get field list of sobject
*/
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{SObject_Sharing__c.Id,SObject_Sharing__c.Name,SObject_Sharing__c.Enable_Sharing_Calculation__c};
            }
    
    /**
* This method used to set up type of sobject
* @return  Schema.SObjectType
*/
    public Schema.SObjectType getSObjectType() {
        return SObject_Sharing__c.sObjectType;
    }
    
    /**
* This method is used to get SObject Sharing
* @return List<Group>
*/
    public List<SObject_Sharing__c> getSObjectSharing(Set<String> fieldSet) {
        return (List<SObject_Sharing__c>) Database.query(newQueryFactory(true).selectFields(fieldSet).toSOQL());
    }
}