src/objects/Time_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Spent__c</fullName>
        <inlineHelpText>In seconds.</inlineHelpText>
        <label>Time Spent(sec)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BCH_CRM_DeleteTimeTrackingRecords.cls
global class BCH_CRM_DeleteTimeTrackingRecords implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id from Time_Tracker__c where (Time_Spent__c = null OR End_Time__c = null) AND Start_Time__c < :DateTime.now().addHours(-1)]);
    }
    
    global void execute(Database.BatchableContext bc, List<Time_Tracker__c> ttList){
        delete ttList;
    }
    
    global void finish(Database.BatchableContext bc){
    }
}