src/objects/TPA_Data_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipLabel>TPA Primary Offerings Selected</relationshipLabel>
        <relationshipName>Data_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Data Asset</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Primary Offering ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TPA_Purpose__c.object
<CustomObject>
    <description>Created By TPA Module Under TPA-FEATURE-5</description>
    <fields>
        <fullName>Request__c</fullName>
        <description>Created By TPA Module Under TPA-FEATURE-5</description>
        <label>Request</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipLabel>Purposes</relationshipLabel>
        <relationshipName>Purposes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TPA Purpose</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Purposes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TPA_Request__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled__c</fullName>
        <label>Cancelled</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Client_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Client)</relationshipLabel>
        <relationshipName>TPA_Requests_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Contact_Territory__c</fullName>
        <label>Requesting Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Cayman Islands</fullName>
                </value>
                <value>
                    <fullName>Central America</fullName>
                </value>
                <value>
                    <fullName>Chile</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Dominican Republic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Request_Submission__c</fullName>
        <label>Client Request Submission</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Expired_Date__c</fullName>
        <label>Expired Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IMS_Denied__c</fullName>
        <label>IQVIA Denied</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>In_Effect_Date__c</fullName>
        <label>In Effect Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>In_IMS_Review__c</fullName>
        <label>In IQVIA Review</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Manually_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMA Cancelled</fullName>
                </value>
                <value>
                    <fullName>AMA Discontinued</fullName>
                </value>
                <value>
                    <fullName>Awaiting Account Mgmt Communication</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Confirmation</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Modification</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Vendor Signature</fullName>
                </value>
                <value>
                    <fullName>Awaiting Vendor Submission</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Client Discontinued</fullName>
                </value>
                <value>
                    <fullName>Client Draft</fullName>
                </value>
                <value>
                    <fullName>Closed-IQVIA Affiliate</fullName>
                </value>
		<value>
                	<fullName>Covered By MOU</fullName>
            	</value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Draft Closed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Hold for TPA non-compliance</fullName>
                </value>
                <value>
                    <fullName>In Auto Approval Process</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Initializing Vendor</fullName>
                </value>
                <value>
                    <fullName>In Review By IQVIA</fullName>
                </value>
                <value>
                    <fullName>IQVIA Denied</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Pending IQVIA Review of Voided Envelope</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor AMA Fee Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Pending - Vendor Declined AMA Fees</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Response on Data Destruction from Prior TPAs</fullName>
                </value>
                <value>
                    <fullName>Signature Under Validation</fullName>
                </value>
                <value>
                    <fullName>TPA Approved Awaiting AMA Approval</fullName>
                </value>
                <value>
                    <fullName>Vendor Canceled ‘17 AMA-TPA Exp-12/31/16</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sent_for_Signature__c</fullName>
        <label>Sent for Signature</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service_Provider_Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Legal Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Vendor is not a TPA Vendor.</errorMessage>
            <filterItems>
                <field>Address__c.Is_TPA_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Request_Status__c</field>
                <operation>equals</operation>
                <value>Cancelled, Expired, In Effect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>TPA Requests (Service Provider)</relationshipLabel>
        <relationshipName>TPA_Requests1_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signature_Received__c</fullName>
        <label>Signature Received</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Signature_Under_Validation__c</fullName>
        <label>Signature Under Validation</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vendor_App_Sent__c</fullName>
        <description>Created By TPA Module Under TPA-FEATURE-5.</description>
        <label>Vendor App Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Vendor_App_Submitted__c</fullName>
        <label>Vendor App Submitted</label>
        <type>DateTime</type>
    </fields>
    <label>TPA Request</label>
    <nameField>
        <label>Client Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CNT_TPA_TATReport2.cls
public class CNT_TPA_TATReport2 {
     public List<String> submittingCountry { get; set; }
  
    public class ReportWrapper {
        TPA_Request__c objAgreement;
        Integer statusDuration;
        String usesSelected;
        String useCategories;
        String offeringCategories;
        String toStatus ;
        String fromStatus;
    }
  
    public class allConditions {
        public String dayRange;
        public String statusCategorySelected;
        public String clientName;
        public String vendorName;
        public Datetime fromDate;
        public Datetime toDate;
        public List<String> submittingCountries ;
    }
    
    public CNT_TPA_TATReport2() {
        submittingCountry = new List<String>();
        //submittingCountry.add('--None--');
        //submittingCountry.add( 'All');
        
        Schema.DescribeFieldResult fieldResult = TPA_Request__c.Client_Contact_Territory__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){
            submittingCountry.add( f.getValue());
        }
    }
    
    public PageReference redirectToExport(){
        String filters = Apexpages.currentPage().getParameters().get('filterParams');
        PageReference pr = new PageReference('/apex/VFP_TPA_Report_Export?type=TAT2&query='+filters);
        pr.setRedirect(true);
        return pr;
    }
    
   	public List<SelectOption> getGroupingOptions() {
        // List of select options to store grouping options
        List<SelectOption> options = new List<SelectOption>();
        
        // Add default option in the select option list
        options.add( new SelectOption( 'submittimgCountry', 'Client Country' ));
        options.add( new SelectOption( 'toStatus', 'Status' ));
        options.add( new SelectOption( 'vendorName', 'Vendor Name' ));
        options.add( new SelectOption( 'clientName', 'Client Name' ));
        
        // Return list of select options
        return options;
    }
    
    
    
    @remoteAction
    public static ReturnDataWaraper getReportResult(String selectedConditions, Integer noOfReqToProcess, String lastRecId) {
        List<ReportWrapper> lstReportResults = new List<ReportWrapper>();
        List<TPA_Request__c> lstAgreementQueried = new List<TPA_Request__c>();
        ReturnDataWaraper retDataWrapObj = new ReturnDataWaraper();
        String fromStatusFieldName = '';
        String toStatusFieldName = '';
        String fromStatus = '';
        String toStatus = '';  
        
        String lastRecordId;
        datetime lastRecordCretedDateTime;
        if(lastRecId != null) {
            lastRecordCretedDateTime = [Select CreatedDate from TPA_Request__c where Id = :lastRecId][0].CreatedDate;
        }
        
      	allConditions objSelectedConditions = (allConditions)JSON.deserialize(selectedConditions,allConditions.class);
        Datetime fromDate = objSelectedConditions.fromDate;
        Datetime toDate = objSelectedConditions.toDate.addDays(1);
        Integer lowerDayRange = Integer.valueOf(objSelectedConditions.dayRange.split('-')[0]);
        Integer upperDayRange = Integer.valueOf(objSelectedConditions.dayRange.split('-')[1]);
        Set<String> allCountriesSelected = new Set<String>();
        for(String selectedCountry: objSelectedConditions.submittingCountries) {
            allCountriesSelected.add(selectedCountry);
            allCountriesSelected.addAll(UTL_TPA_Multilingual.getCountryStateCodeSetWithName('C', selectedCountry));
        }
        //allCountriesSelected.addAll(objSelectedConditions.submittingCountries);
        String query = 'Select Id, Name, Client_Address__c, '
                        + 'Service_Provider_Address__c, Request_Status__c, '
                        + 'Client_Request_Submission__c, Vendor_App_Sent__c, Vendor_App_Submitted__c, In_IMS_Review__c, In_Effect_Date__c, '
                        + 'IMS_Denied__c, Sent_for_Signature__c, Signature_Received__c, Signature_Under_Validation__c, Cancelled__c, '
                        + 'Expired_Date__c, Service_Provider_Address__r.Name, Is_Manually_Approved__c, '
                        + 'Client_Contact_Territory__c, Client_Address__r.Name,Secondary_Client_Contact_Territory__c,'
                        + 'LastModifiedBy.Name, LastModifiedById, AMA_USPrescriberData__c, '
             			+ '(Select Id, Name, TPA_Purpose_Category__r.Category_Name__c from Purposes__r), '
                        + '(Select Data_Asset__c, Data_Asset__r.Geo_Level__c From Data_Assets__r), '
                        + 'Manual_Trigger_Reasons__c ' 
                        + 'from TPA_Request__c where Is_Submitted__c = true';
                        
        if( objSelectedConditions.vendorName != null && objSelectedConditions.vendorName != '' ) {
            query += ' AND Service_Provider_Address__r.Name like \'' + objSelectedConditions.vendorName + '%\'';
        }
        else if( objSelectedConditions.clientName != null && objSelectedConditions.clientName != '' ) {
            query += ' AND Client_Address__r.Name like \'' + objSelectedConditions.clientName + '%\'';
        }
        if(!Test.isRunningTest())
            query += ' AND ( CreatedDate >=: ' +'fromDate'+ ' AND CreatedDate <: ' +'toDate' +')';
        fromStatus = objSelectedConditions.statusCategorySelected.split('-')[0];
        toStatus = objSelectedConditions.statusCategorySelected.split('-')[1];
        for(String str : fromStatus.split(' ')) {
          fromStatusFieldName += str+'_';
        }
        fromStatusFieldName += '_c';
        for(String str : toStatus.split(' ')) {
          toStatusFieldName += str+'_';
        }
        toStatusFieldName += '_c';
        query += ' AND ' + fromStatusFieldName + ' != null';
        query += ' AND ' + toStatusFieldName + ' != null';
        query += ' AND Secondary_Client_Contact_Territory__c in: allCountriesSelected';
        if(lastRecordCretedDateTime != null) {
            query += ' AND CreatedDate > :lastRecordCretedDateTime';
        }
        //lstAgreementQueried = Database.query(query);
        lstAgreementQueried = Database.query( query + ' Order By CreatedDate Limit ' + noOfReqToProcess);
        system.debug('query:::: ' + query);
        if(lstAgreementQueried == null || lstAgreementQueried.size() == 0) {
            System.debug('agreements in If ----------------------> ' + lstAgreementQueried);
            retDataWrapObj.resultData = new List<ReportWrapper>();
            retDataWrapObj.noOfTPAReqProcessed = 0;
            retDataWrapObj.lastReqId = '';
            return retDataWrapObj;
        }
        lstReportResults = getReportWrapperList(lstAgreementQueried,lowerDayRange,upperDayRange,fromStatusFieldName,toStatusFieldName);
        retDataWrapObj.resultData = lstReportResults;
        System.debug('retDataWrapObj.resultData ------> ' + retDataWrapObj.resultData);
        retDataWrapObj.noOfTPAReqProcessed = lstAgreementQueried.size();
        retDataWrapObj.lastReqId = lstAgreementQueried[lstAgreementQueried.size()-1].Id;
        return retDataWrapObj;
    }
    
    public static List<ReportWrapper> getReportWrapperList(List<TPA_Request__c> lstAgreement,Integer lowerRange,Integer upperRange,String fromStatusField,String toStatusField) {
        Map<String,String> mapStatusStampWithStatus = new Map<String,String>();
        mapStatusStampWithStatus.put('Client_Request_Submission__c','Awaiting Vendor Submission');
        mapStatusStampWithStatus.put('In_Effect_Date__c','In Effect');
        mapStatusStampWithStatus.put('In_IMS_Review__c',Label.TPA_In_Review_By_IQVIA_Status);
        mapStatusStampWithStatus.put('Sent_for_Signature__c','Awaiting Vendor Signature');
        String purpose = '';
        String purposeCategory = '';
        String offeringCategory = '';
        List<ReportWrapper> lstInsert = new List<ReportWrapper>();
        for(TPA_Request__c agg : lstAgreement) {
            DateTime fromStatusDateTime = DateTime.valueof(agg.get(fromStatusField));
            DateTime toStatusDateTime = DateTime.valueof(agg.get(toStatusField));
            integer dateDiff = Integer.valueOf((toStatusDateTime.getTime() - fromStatusDateTime.getTime())/(1000*60*60*24));
            System.debug('date diff is::'+dateDiff);
            agg.Secondary_Client_Contact_Territory__c = UTL_TPA_Multilingual.mapCountryStatesCodes.get(agg.Secondary_Client_Contact_Territory__c+'~'+'C');
            if(dateDiff >= lowerRange && dateDiff <= upperRange) {
                ReportWrapper obReportWrapper = new ReportWrapper();
                obReportWrapper.objAgreement = agg;
                purpose = '';
                purposeCategory = '';
                offeringCategory = '';

                for( TPA_Purpose__c purp : agg.Purposes__r ) {
                    purpose += purp.Name + ', ';
                    if( purp.TPA_Purpose_Category__r.Category_Name__c != null && purp.TPA_Purpose_Category__r.Category_Name__c != ''
                    && purposeCategory.indexOf( purp.TPA_Purpose_Category__r.Category_Name__c ) == -1 )
                        purposeCategory += purp.TPA_Purpose_Category__r.Category_Name__c + ', ';
                }
                  
                for( TPA_Data_Asset__c asset : agg.Data_Assets__r ) {
                    if( asset.Data_Asset__c != null && asset.Data_Asset__r.Geo_Level__c != null && asset.Data_Asset__r.Geo_Level__c != ''
                    && offeringCategory.indexOf( asset.Data_Asset__r.Geo_Level__c ) == -1 )
                        offeringCategory += asset.Data_Asset__r.Geo_Level__c + ', ';
                }
                  
                purpose = ( purpose.length() != 0 ? purpose.subString( 0, purpose.length() - 2 ) : purpose );
                purposeCategory = ( purposeCategory.length() != 0 ? purposeCategory.subString( 0, purposeCategory.length() - 2 ) : purposeCategory );
                offeringCategory = ( offeringCategory.length() != 0 ? offeringCategory.subString( 0, offeringCategory.length() - 2 ) : offeringCategory );
                obReportWrapper.usesSelected = purpose;
                obReportWrapper.useCategories = purposeCategory;
                obReportWrapper.offeringCategories = offeringCategory;
                obReportWrapper.statusDuration = dateDiff;
                obReportWrapper.fromStatus = mapStatusStampWithStatus.get(fromStatusField);
                obReportWrapper.toStatus = mapStatusStampWithStatus.get(toStatusField);
                lstInsert.add(obReportWrapper);
            }        
        }
        return lstInsert;
    }
	
    public Class ReturnDataWaraper{
        List<ReportWrapper> resultData;
        Integer noOfTPAReqProcessed;
        String lastReqId;
    }
}