src/objects/TPA_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>email recipients</description>
    <fields>
        <fullName>TLLA_Batch_Class_Id__c</fullName>
        <defaultValue>&apos;01pV000000018j6&apos;</defaultValue>
        <label>TLLA Batch Class Id</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>TPA Settings</label>
</CustomObject>

src/classes/SCH_TPA_CheckAgreementTLLACopy.cls
global class SCH_TPA_CheckAgreementTLLACopy implements Schedulable {
    global void execute(SchedulableContext SC) {
        TPA_Settings__c objSetting = TPA_Settings__c.getInstance();
        List<AsyncApexJob> lstApexJob = new List<AsyncApexJob>();
        lstApexJob = [select id, ApexClassID, Status FROM AsyncApexJob WHERE JobType='BatchApex' and ApexClassID =:objSetting.TLLA_Batch_Class_Id__c and status in ('Processing', 'Holding', 'Queued', 'Preparing')];
        if(lstApexJob.size() == 0){
            Database.executebatch(new BCH_TPA_CheckAgreementTLLA(), 1);  
        }
    }
}