src/objects/TPA_Commercial_Review__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Commercial Owner Decision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Under Validation</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Assigned to Commercial Owner (CO) – Awaiting CO Review</fullName>
                </value>
                <value>
                    <fullName>Approved for this specific TPA request</fullName>
                </value>
                <value>
                    <fullName>Approved for this specific TPA. The Vendor and specified Use(s) and IQVIA Offerings specific combination can be auto-approved moving forward for future requests</fullName>
                </value>
                <value>
                    <fullName>Approved for this specific TPA. Ad-Hoc Additional Term(s) and/or Exibhit Required can be auto-approved moving forward for future requests</fullName>
                </value>
                <value>
                    <fullName>Questions / Comments</fullName>
                </value>
                <value>
                    <fullName>Potential Denial - Request TP Processor to arrange meeting with IQVIA Legal</fullName>
                </value>
                <value>
                    <fullName>Confirmed - Include in Renewal</fullName>
                </value>
                <value>
                    <fullName>Confirmed - Include Updated Additional Term in Renewal</fullName>
                </value>
                <value>
                    <fullName>No Valid AMA Agreement on File</fullName>
                </value>
                <value>
                    <fullName>Valid AMA Agreement on File</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                    <isActive>false</isActive>
                    <label>--None--</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Review_Secondary__c</fullName>
        <formula>IF( OR(Manual_Review_Reason__c == &apos;Vendor Requires Secondary Review&apos;,Manual_Review_Reason__c == &apos;Offering Requires Secondary Commercial Review&apos;, CONTAINS(Manual_Review_Reason__c,&quot;Vendor - Use Secondary Review by&quot;),CONTAINS(Manual_Review_Reason__c,&quot;Vendor - Use - Offering Secondary Review by&quot;) ,Manual_Review_Reason__c == &apos;IQVIA Legal Approval Required: [New] TPA: Ad-hoc Additional Term Requested&apos;,Manual_Review_Reason__c == &apos;IQVIA Legal Approval Required: [Renew] TPA: Ad-hoc Additional Term Requested&apos;,Manual_Review_Reason__c == &apos;IQVIA Legal Approval Required: New TPA - Ad-hoc Additional Term(s) / Exhibit Page(s) Requested&apos;,Manual_Review_Reason__c == &apos;IQVIA Legal Approval Required: Prior TLLA had an Additional Term and/or Exhibit added and to be Renewed&apos;) , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Review Secondary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manual_Review_Reason__c</fullName>
        <label>Manual Review Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>TPA Manual Trigger Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting to Send: Primary Commercial Owner Not Complete</fullName>
                </value>
                <value>
                    <fullName>Awaiting Review</fullName>
                </value>
                <value>
                    <fullName>Combination Approved</fullName>
                </value>
                <value>
                    <fullName>Combination Approved and Future Approved</fullName>
                </value>
                <value>
                    <fullName>Pending TP Processor Response to Commercial Owner Questions or Comments</fullName>
                </value>
                <value>
                    <fullName>Pending TP Processor to Arrange meeting with IQVIA Legal via TP-US team</fullName>
                </value>
                <value>
                    <fullName>Pending TP Processor Response</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TPA_Request__c</fullName>
        <label>TPA Request</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipLabel>TPA Commercial Reviews</relationshipLabel>
        <relationshipName>TPA_Commercial_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TPA Commercial Review</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>TPA Commercial Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TPA Commercial Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TPA_Request__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <formula>HYPERLINK(URL__c&amp;Id&amp;&quot;&amp;name=View&quot;,&quot;View&quot;,&quot;_self&quot;) 

&amp; 

IF(ISPICKVAL(Request_Status__c,&quot;Client Draft&quot;) , 
&quot; | &quot;&amp;HYPERLINK(URL__c&amp;Id&amp;&quot;&amp;name=edit&quot;,&quot;Edit&quot;,&quot;_self&quot;) 
&amp;	&quot; | &quot;&amp;HYPERLINK(&quot;/imshealthPortal/VFP_TPA_CustomLandingPage?linkaction=closedDraft&amp;url=/imshealthPortal/VFP_TPA_ListView&amp;closedId=&quot;&amp;Id,&quot;Close Draft&quot;,&quot;_self&quot;) , 
NULL ) 

&amp; 

IF(	ISPICKVAL(Request_Status__c,&quot;In Effect&quot;) 
&amp;&amp;	Data_Access_End_Date__c&gt;=TODAY() 
&amp;&amp;	Data_Access_End_Date__c&lt;(TODAY()+61) 
&amp;&amp; !Is_Renewed__c 
&amp;&amp; $Profile.Name&lt;&gt;&quot;TPA Processor Profile CCP&quot; 
,	
&quot; | &quot;&amp;HYPERLINK(URL__c&amp;Id&amp;&quot;&amp;name=renew&quot;, &quot;Renew&quot;,&quot;_self&quot;) 

, 
NULL 
) 

&amp; 

IF(	ISPICKVAL(Request_Status__c,&quot;Expired&quot;) 
&amp;&amp;	$Profile.Name&lt;&gt;&quot;TPA Processor Profile CCP&quot; 
&amp;&amp; !Is_Renewed__c 
 &amp;&amp;  (  TODAY()  -  DATEVALUE(CreatedDate ) &lt; 1095 ) 
, 
&quot; | &quot;&amp;HYPERLINK(URL__c&amp;Id&amp;&quot;&amp;name=renew&quot;, &quot;Renew&quot;,&quot;_self&quot;) , 
NULL) 

&amp;
IF(Is_Renewed__c &amp;&amp;  ISPICKVAL( Renewed_Type__c , &quot;Renewed&quot;), &quot; | Renewed as &quot; + Renewed_As__r.Name , IF(Is_Renewed__c &amp;&amp;  ISPICKVAL( Renewed_Type__c , &quot;Modified Renewal&quot;),
 &quot; | Modified Renewal as &quot; + Renewed_As__r.Name, IF(Is_Renewed__c ,
 &quot; | Renewed as &quot; + Renewed_As__r.Name, NULL) )) 
&amp; 

IF( $Profile.Name&lt;&gt;&quot;TPA Processor Profile CCP&quot; &amp;&amp;
(ISPICKVAL(Request_Status__c,&quot;Awaiting Vendor Submission&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;In Auto Approval Process&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;TPA Approved Awaiting AMA Approval&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;In Review By IQVIA&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Pending Vendor Response on Data Destruction from Prior TPAs&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Awaiting Vendor Signature&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Initializing Vendor&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Signature Under Validation&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Pending Vendor AMA Fee Acknowledgement&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Pending - Vendor Declined AMA Fees&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Awaiting Client Modification&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Awaiting Account Mgmt Communication&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Awaiting Final Review&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Pending Cancellation&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Awaiting Client Acknowledgement&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Hold for TPA non-compliance&quot;)
|| ISPICKVAL(Request_Status__c,&quot;Pending IQVIA Review of Voided Envelope&quot;))
, 

IF(	
!ISPICKVAL(Request_Status__c,&quot;Signature Under Validation&quot;) , 

&quot; | &quot;&amp;HYPERLINK(URL__c&amp;Id&amp;&quot;&amp;name=edit&quot;,&quot;Edit&quot;,&quot;_self&quot;) , 
NULL ) 
&amp;	IF( 
$Profile.Name&lt;&gt;&quot;TPA Processor Profile CCP&quot; 
, 
&quot; | &quot;&amp;HYPERLINK(URL__c&amp;Id&amp;&quot;&amp;name=clone&quot;,&quot;Clone&quot;,&quot;_self&quot;) 

&amp;	&quot; | &quot;&amp;HYPERLINK(&quot;/imshealthPortal/VFP_TPA_CustomLandingPage?linkaction=cancelTPA&amp;url=/imshealthPortal/VFP_TPA_ListView&amp;cancelId=&quot;&amp;Id,&quot;Cancel&quot;,&quot;_self&quot;) 
, NULL 
) 
, IF( 
ISPICKVAL(Request_Status__c,&quot;In Effect&quot;) 
|| ISPICKVAL(Request_Status__c,&quot;Expired&quot;) 
||	ISPICKVAL(Request_Status__c,&quot;Cancelled&quot;) 
, 
IF( 
$Profile.Name&lt;&gt;&quot;TPA Processor Profile CCP&quot;, 
&quot; | &quot;&amp;HYPERLINK(URL__c&amp;Id&amp;&quot;&amp;name=clone&quot;,&quot;Clone&quot;,&quot;_self&quot;), 
NULL 
), NULL )) 

&amp;
IF(ISPICKVAL(Request_Status__c,&quot;Expired&quot;)
&amp;&amp; NOT(ISBLANK(Client_Set_Earlier_Expiry_Date__c)),
 &quot; | Client Expired Early&quot; ,
NULL)

&amp;
IF(ISPICKVAL(Request_Status__c,&quot;In Effect&quot;),
IF(NOT(ISBLANK(Client_Set_Earlier_Expiry_Date__c)),
&quot; | Client Set Earlier Expiry Date&quot;,
IF($Profile.Name = &quot;US TP Processor Profile CCP&quot;
|| $Profile.Name = &quot;TPA Customer Community Plus Login User&quot;
|| $Profile.Name = &quot;Super User Profile CCP&quot;, &quot; | &quot; &amp;
HYPERLINK(URL__c&amp;Id&amp;&quot;&amp;name=earlyexpire&quot;,&quot;Early Expire&quot;,&quot;_target&quot;), &apos;&apos;
 )),NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Action</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Off_Notification_Ack_Date__c</fullName>
        <label>Client Off Notification Ack Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMA Cancelled</fullName>
                </value>
                <value>
                    <fullName>AMA Discontinued</fullName>
                </value>
                <value>
                    <fullName>Awaiting Account Mgmt Communication</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Confirmation</fullName>
                </value>
                <value>
                    <fullName>Awaiting Client Modification</fullName>
                </value>
                <value>
                    <fullName>Awaiting Final Review</fullName>
                </value>
                <value>
                    <fullName>Awaiting Vendor Signature</fullName>
                </value>
                <value>
                    <fullName>Awaiting Vendor Submission</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Client Discontinued</fullName>
                </value>
                <value>
                    <fullName>Client Draft</fullName>
                </value>
                <value>
                    <fullName>Closed-IQVIA Affiliate</fullName>
                </value>
		<value>
                	<fullName>Covered By MOU</fullName>
            	</value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Draft Closed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Hold for TPA non-compliance</fullName>
                </value>
                <value>
                    <fullName>In Auto Approval Process</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Initializing Vendor</fullName>
                </value>
                <value>
                    <fullName>In Review By IQVIA</fullName>
                </value>
                <value>
                    <fullName>IQVIA Denied</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Pending IQVIA Review of Voided Envelope</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor AMA Fee Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>Pending - Vendor Declined AMA Fees</fullName>
                </value>
                <value>
                    <fullName>Pending Vendor Response on Data Destruction from Prior TPAs</fullName>
                </value>
                <value>
                    <fullName>Signature Under Validation</fullName>
                </value>
                <value>
                    <fullName>TPA Approved Awaiting AMA Approval</fullName>
                </value>
                <value>
                    <fullName>Vendor Canceled ‘17 AMA-TPA Exp-12/31/16</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request Initiation</fullName>
                </value>
                <value>
                    <fullName>Service Provider Request Details</fullName>
                </value>
                <value>
                    <fullName>Client Acknowledgement</fullName>
                </value>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Off_Notification_Ack_Date__c</fullName>
        <label>Vendor Off Notification Ack Date</label>
        <type>DateTime</type>
    </fields>
    <label>TPA Request</label>
    <nameField>
        <label>Client Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/QBL_TPA_sendCommercialMail.cls
public class QBL_TPA_sendCommercialMail implements Queueable,Database.AllowsCallouts { 
    public TPA_Request__c request; 
    public Map<String, Map<String, Map<String, String>>> BUPurposeGeoLevelDataAssetMap;
    public boolean sendVendorSecondaryEmail;
    public boolean sendSecondaryEmail;
    public Boolean isAwaitingClientConfirmationMailReq;
    public Boolean isdynamicOffNoticationReqOrNot;
    public Boolean isSecComReview;
    public List<TPA_Commercial_Review__c> commercialReasonListSecond;
    public String runType;
    public static Boolean isComReviewsInsert = false;
    public void execute(QueueableContext context) {
        SRV_TPA_TPARequest.tpaRequest = request;
        SRV_TPA_TPARequest.isSecComReview = isSecComReview;
        if(commercialReasonListSecond != null && commercialReasonListSecond.size() > 0) {
            try {
                isComReviewsInsert = true;
                upsert commercialReasonListSecond;
                isComReviewsInsert = false;
            } catch(Exception ex) {
                system.debug('ErrorCpc:'+ex.getMessage());
                UTL_LogFactory.getLogLst().Add(UTL_LogFactory.generateAndCommitLog(FALSE, FALSE, UTL_LogFactory.GUID, ex.getMessage(), 'TPA', 'Exception', 'ERROR', 'Line#' + ex.getLineNumber() + ':::QBL_TPA_sendCommercialMail:::update Com Records', request != null ? request.Id : ''));
                UTL_LogFactory.saveLogs(UTL_LogFactory.getLogLst(), TRUE);
            }
            
        }
        
        List<TPA_Commercial_Review__c> finalCommercialReviews = [Select Id,Is_Review_Secondary__c,Manual_Review_Reason__c,Status__c,TPA_Request__c From TPA_Commercial_Review__c where TPA_Request__c =: request.Id];
        Boolean isPrimaryApp = true,isAllSecondary = true,isAllRevApproved = true;
        boolean sendLegalMail = false;
        boolean sendVendorSecondaryEmail = false;
        boolean sendSecondaryEmail = false;
        List<TPA_Commercial_Review__c> secondaryReviews = new List<TPA_Commercial_Review__c>();
        List<TPA_Commercial_Review__c> secondaryReviewsToUpdate = new List<TPA_Commercial_Review__c>();
        
        for(TPA_Commercial_Review__c comRev:finalCommercialReviews){
            if(comRev.Status__c == null || (!comRev.Status__c.contains('Approved') && comRev.Status__c != 'Complete' )){
                isAllRevApproved = false;
            }
            if(comRev.Status__c == null || (!comRev.Is_Review_Secondary__c && !comRev.Status__c.contains('Approved') && comRev.Status__c != 'Complete' )){
                isPrimaryApp = false;
            }
            if(comRev.Is_Review_Secondary__c && !comRev.Status__c.contains('Approved')){
                secondaryReviews.add(comRev);
            }
            if(!comRev.Is_Review_Secondary__c){
                isAllSecondary = false;
            }
        }
        if(!isPrimaryApp && secondaryReviews != null && secondaryReviews.size() > 0){
            system.debug('in first if ****');
            sendVendorSecondaryEmail = false;
            sendSecondaryEmail = false;
            for(TPA_Commercial_Review__c comRev: secondaryReviews){
                if(comRev.Status__c == 'Awaiting Review'){
                    comRev.Status__c = 'Awaiting to Send: Primary Commercial Owner Not Complete';
                    comRev.Action__c = null;
                    secondaryReviewsToUpdate.add(comRev);
                }
            }
        }
        else if((isPrimaryApp || isAllSecondary) && secondaryReviews != null && secondaryReviews.size() > 0){
            system.debug('in second if ****');
            for(TPA_Commercial_Review__c comRev: secondaryReviews){
                if(comRev.Status__c == 'Awaiting to Send: Primary Commercial Owner Not Complete'){
                    comRev.Status__c = 'Awaiting Review';
                    comRev.Action__c = null;
                    secondaryReviewsToUpdate.add(comRev);
                }
                if(comRev.Manual_Review_Reason__c == 'Vendor Requires Secondary Review'){
                    sendVendorSecondaryEmail = true;
                }
                if(UTL_TPA.isManualReviewAddHoc(comRev.Manual_Review_Reason__c)){
                    sendLegalMail = true;
                }
                if(!sendLegalMail && !sendVendorSecondaryEmail){
                    sendSecondaryEmail = true;
                }
                if(sendVendorSecondaryEmail && sendLegalMail && sendSecondaryEmail){
                    break;
                }
            }
        }
        if(secondaryReviewsToUpdate.size() > 0 || sendVendorSecondaryEmail || sendLegalMail || sendSecondaryEmail){
            SRV_TPA_TPARequest.isSecComReview = true;
        }
        
        SRV_TPA_TPARequest.sendApprovalMailToCommericialOwnerForBulk();
        
        if(((request.Client_Off_Notification_Ack_Date__c != null && request.Vendor_Off_Notification_Ack_Date__c != null) || isAwaitingClientConfirmationMailReq) && isdynamicOffNoticationReqOrNot && request.Request_Status__c != 'Initializing Vendor')
        {
            System.debug('Call sent for notification...');
            SRV_TPA_TPARequest.isOffNotificationDocGenerated = true;
            TPA_Dyn_Off_Not_GeneratorQueue tpaDynOffNotGeneratorQueueObj = new TPA_Dyn_Off_Not_GeneratorQueue();
            tpaDynOffNotGeneratorQueueObj.reqId = request.Id;
            tpaDynOffNotGeneratorQueueObj.vendorAccountId = request.Service_Provider_Address__c;
            tpaDynOffNotGeneratorQueueObj.clientLanguage = request.Client_Language__c;
            tpaDynOffNotGeneratorQueueObj.vendorLanguage = request.Vendor_Language__c;
            tpaDynOffNotGeneratorQueueObj.reqName = request.Name;
            tpaDynOffNotGeneratorQueueObj.ClientContactEmail = request.ClientContact__r.email;
            tpaDynOffNotGeneratorQueueObj.isdynamicOffNotificationReqForVendor = isAwaitingClientConfirmationMailReq;
            tpaDynOffNotGeneratorQueueObj.reqStatus = request.Request_Status__c;
            tpaDynOffNotGeneratorQueueObj.GUID = UTL_LogFactory.GUID;
            tpaDynOffNotGeneratorQueueObj.runType = runType;
            if(!Test.isRunningTest()){
                System.enqueueJob(tpaDynOffNotGeneratorQueueObj);
            }
        } else if(runType == 'RunTpaBusinessRule'){
            SRV_TPA_DocusignEnvelope.generateDocForSign(request.Id, UTL_LogFactory.GUID); 
        }
    }
}