src/objects/TPA_Commercial_Review__c.object
<CustomObject>
    <fields>
        <fullName>TPA_Request__c</fullName>
        <label>TPA Request</label>
        <referenceTo>TPA_Request__c</referenceTo>
        <relationshipLabel>TPA Commercial Reviews</relationshipLabel>
        <relationshipName>TPA_Commercial_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TPA Commercial Review</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>TPA Commercial Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TPA Commercial Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TPA_Request__c.object
<CustomObject>
    <label>TPA Request</label>
    <nameField>
        <label>Client Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TPA Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TST_CNT_TPA_CODescisionTable.cls
@isTest(seeAllData = false)
public class TST_CNT_TPA_CODescisionTable {
    @isTest
    public static void testGetRelatedComList(){
        Test.startTest();
        TPA_Request__c testRequest = UTL_TPA_SetupTestData.getTestTPARequest();
        insert testRequest;
        system.debug(CNT_TPA_CODescisionTable.tpaCommunityUrl);
        system.debug(CNT_TPA_CODescisionTable.currentLoggedInUser);
        system.debug(CNT_TPA_CODescisionTable.currentUserProfileName);
        List<TPA_Commercial_Review__c> test1 = CNT_TPA_CODescisionTable.getRelatedComList(null,testRequest.id, 'CSubmit', 'rr');
        CNT_TPA_CODescisionTable testObj = new CNT_TPA_CODescisionTable();
        PageReference testPage = testobj.requestValidateOnLoad(); 
        Test.stopTest();
    } 
}